### ISSUE TITLE
something broke in inc./load.php ?

### ISSUE THREAD

**Issue by tonybaldwin** [splitbrain/dokuwiki#1004]
Last night I installed a doku with Andreas' dokuwiki-downloader.php script, and it went flawlessly, as expected...I've done it probably 100 times before and that's what I expect.
But this morning I'm trying to install another, and it's not working.
Either I get an error on the welcome page about data dir pages not found or not writeable (../data/pages/ was there and writeable, but it was apparently looking in /pages, not /data/pages).
That was earlier today.
Now I'm just getting a whitepage of death on the wiki:welcome page after installation. can't access anything else.
in /var/log/apache/error.log I find
PHP Fatal error:  require_once(): Cannot redeclare class doku_form in /path/to/wiki/inc/load.php on line 112, referer:(url)

**Comment by splitbrain** [comment]
The installer pulls the current stable release. There wasn't a change in that branch since Dec 3, 2014

Maybe something else was wrong on your machine?

**Comment by tonybaldwin** [comment]
Not sure what happened, but it does seem to have resolved itself.
It was weird...one day it worked, next day it didn't, day after that,
it worked again...no idea...

thanks,
Tony

-- 
http://tonybaldwin.me
all tony, all the time
