### ISSUE TITLE
Dokuwiki pulls AD users but not groups

### ISSUE THREAD

**Issue by jamie-lynne** [splitbrain/dokuwiki#1008]
Setting up Dokuwiki (hrun) on Ubuntu server. Pulling AD from a Server 2008 R2 box. With the "authtype" set to authad and "useacl" unchecked, I can login to Dokuwiki as an AD user. The single-sign on works perfectly etc.

The problem is that Dokuwiki isn't pulling any groups from AD. A little background - I am building a prototype now, and eventually will integrate with our company's AD. So changes to the AD configuration itself (or how the OUs are setup) is not possible. My AD setup is something like this

Company
     City
         Department1
              Users
                   User1
                   User2
         Department2
              Users
                    User1
                    User2
     Security Groups
         Group1
         Group2

My local.php config includes the settings for both the authad and authldap plugins (the default that come with dokuwiki). In the Configuration Manager I can switch back and forth, but neither works. I included all of this just so y'all would know. My config looks like this:

$conf['useacl'] = '1';
$conf['autopasswd'] = 0;
$conf['authtype'] = 'authplain';
$conf['superuser'] = 'myuser,administrator';
$conf['manager'] = 'myuser,administrator';
$conf['disableactions'] = 'register';
$conf['subscribers'] = 1;
$conf['plugin']['authad']['account_suffix'] = '@domain.msft';
$conf['plugin']['authad']['base_dn'] = 'DC=domain,DC=msft';
$conf['plugin']['authad']['domain_controllers'] = 'dc1.domain.msft';
$conf['plugin']['authad']['admin_password'] = 'null';
$conf['plugin']['authad']['real_primarygroup'] = 1;
$conf['plugin']['authad']['use_ssl'] = 1;
$conf['plugin']['authldap']['server'] = 'domain.msft';
$conf['plugin']['authldap']['usertree'] = 'ou=city, ou=company, dc=domain, dc=msft';
$conf['plugin']['authldap']['grouptree'] = 'ou=security_groups, ou=company, dc=domain, dc=msft';
$conf['plugin']['authldap']['userfilter'] = '(&(uid=%{user})(objectClass=posixAccount))';
$conf['plugin']['authldap']['groupfilter'] = '(&(cn=security_groups)(|(gidNumber=%{gid})(memberUID=%{user})))';
$conf['plugin']['authldap']['version'] = 3;

I've searched forums and documentation all day for almost two weeks. My goal is to make it so that users in the "Corporate Sales" security group can only see pages in the "Corporate Sales" namespace. I would prefer they not even see the "Accounting" namespace, but would be happy with them getting an Access Denied on that page (which I know I can set up elsewhere). Also, I need Dokuwiki to pull AD groups so that Domain Admins can be Administrators on Dokuwiki. Currently, Domain Admins are not recognized and have no admin privileges. 

Sorry for any noob errors. Thanks in advance!!

**Comment by splitbrain** [comment]
your setup uses authplain. You have configs for authldap and authad. It's not clear what you are using. Also your ad setup seems to have lost formatting, can you please reedit?

**Comment by jamie-lynne** [comment]
I have configs for authldap and authad because I have tried both, attempting to get the groups in AD to work. I included them both in the config so y'all could see both. I have tried disabling each of them and still no luck. My setup is using authplain because that's the only way I can be an administrator on the account and when I copied the config that's how I was logged in. When I switch "authtype" to authad or authldap, I lose all administrator access. I have to go back into my config, re-add the line

$conf['useacl'] = '1'

And change authtype back to authplain so I can get back into DokuWiki as an administrator and continue tinkering.

I didn't notice the AD formatting, sorry. Here's edited...

Company
       City
              Department1
                     Users
                            User1
                            User2
              Department2
                     Users
                            User1
                            User2
       Security Groups
                     Group1
                     Group2

**Comment by jamie-lynne** [comment]
Ugh!! Sorry!

Company
===>City
======>Department1
=========>Users
============>User1
============>User2
======>Department2
=========>Users
============>User1
============>User2
======>Security Groups
=========>Group 1
=========>Group 2

**Comment by splitbrain** [comment]
I notice that there's not an admin user set for authad. Can you try specifying a privileged user/password please? It might be that your AD simply refuses to give out the security group names.

**Comment by splitbrain** [comment]
Also try setting ```$conf['plugin']['authad']['recursive_groups'] = 1;```

**Comment by jamie-lynne** [comment]
Thank you. I set admin user for authad and set recursive groups. I logged in as a regular user from my AD and got in fine. But when I do [?do=check] this is the output...

![dokuwikicapture](https://cloud.githubusercontent.com/assets/10551221/5805345/97942faa-9fd3-11e4-8fea-17e630c8de2c.JPG)

If it was pulling from AD, wouldn't there be something like "You are a member of X groups" like there is when you use authplain?

**Comment by splitbrain** [comment]
Your screenshot shows you as not logged in.

**Comment by jamie-lynne** [comment]
I know :( But I am logged in. I am logged in as an AD user and am able to navigate the site just fine. Regardless of which AD user I sign in as, I get the "You are currently not logged in" message. That only disappears when I switch back to authplain and turn on useacl and login as a Dokuwiki-created user.

**Comment by splitbrain** [comment]
I'm not sure what you're doing. But when this shows "you're not logged in" then DokuWiki thinks you're not logged in. It is exactly what DokuWiki uses internally to identify you. Something is wrong with your setup.

**Comment by jamie-lynne** [comment]
I set it up according to the dokuwiki documentation. This is the second time I've set one up (I trashed the first one because of this issue, I assumed it was something I messed up). Do you recommend just trashing this one and trying again? I'm not an expert with this by any means but I can follow the instructions and I'm still having the problem.

**Comment by splitbrain** [comment]
There's no way to help you any further with the available info. Since the plugin is working at several setups I know, I assume it's some misconfiguration and close this ticket. Feel free to open a forum post or a new bug report when more info becomes available.
