### ISSUE TITLE
And (&) instead of question mark (?) in URLs

### ISSUE THREAD

**Issue by erlend-sh** [splitbrain/dokuwiki#1009]
Hi.

We've been using DokuWiki links with the `?do=export_xhtmlbody` action to render our wiki pages in a desktop application. We recently moved our DokuWiki to a new server and updated it to the latest version. We're using URL rewriting method 2.

For some reason, we now have to append posts with a `&` instead of a `?` to make the export action work, like such:

http://wiki.jmonkeyengine.org/doku.php/sdk:welcome:3_0&do=export_xhtmlbody

Any idea why that might be? We can make a change in the desktop application if we have to, but if there's a simple way to keep using the `?` in the URL we'd greatly prefer that.

**Comment by dom-mel** [comment]
What webserver are you using?
I test a apache with .htaccess and mod_rewrite = 1 and there are no problems.

The URL you provided is a "nice URL" like userewrite = 1 setting.
You can always use the long URL in your application like:
http://wiki.jmonkeyengine.org/doku.php?id=jme3&do=export_xhtmlbody

**Comment by normen** [comment]
We're using nginx, the thing about changing the request URL is that we'd have to push an update for our application to all users for that :/

**Comment by dom-mel** [comment]
I guess you can fix it in your nginx config.
Just ensure that the rewrites generate valid URLs.
i think the issue is that the generated URL from nginx is something like:
http://wiki.jmonkeyengine.org/doku.php/doku.php?id=sdk:welcome:3_0?do=export_xhtmlbody
So it wont recognize second parameter.

A example configuration for nginx rewrites is at https://www.dokuwiki.org/rewrite

**Comment by erlend-sh** [comment]
Seems to have been an nginx rewrite mishap on our end. Thanks for aiding our troubleshooting @dom-mel , much appreciated :+1:

**Comment by kwando** [comment]
Just for future reference I'll post there relevant parts of our fixed nginx config here =)
```
upstream wiki{
        # address to php container
        server <php docker server>;
}
server{
        listen 80;

        location ~ ^/doku.php/(.+) {
                proxy_set_header   Host             $host;
                proxy_set_header   X-Real-IP        $remote_addr;
                proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Port 80;
                proxy_set_header   X-Forwarded-Scheme http;

                proxy_pass http://wiki/doku.php?id=$1&$args;
        }

        location / {
                proxy_set_header   Host             $host;
                proxy_set_header   X-Real-IP        $remote_addr;
                proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Port 80;
                proxy_set_header   X-Forwarded-Scheme http;

                proxy_pass http://wiki;
        }
}
```
