### ISSUE TITLE
Footnote causes corruption (because of an hyperlink with no space before it)

### ISSUE THREAD

**Issue by gabrielcossette** [splitbrain/dokuwiki#1025]
Hi!

Here's a special case where a footnote causes corruption with the rest of the page:

Step to reproduce:

1. Insert a footnote with no space before the hyperlink like this:
((test testhttp://google.com test))

Upon preview, you'll see that all the content below the footnote will be included in it!

However, a footnote with a space before the hyperlink (like it should be) is fine:
((test test http://google.com test))

Let me know if you need more info! Thanks.

**Comment by splitbrain** [comment]
without a space, your URL is not recognized and the double slash is assumed to be the start of an italics section. the mission close of that section causes the corruption. this has nothing to do with footnotes.
