### ISSUE TITLE
Create new PDO auth plugin

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#1029]
The mysql extension used in the authmysql plugin is soon going away. #777 suggests to upgrade to mysqli. A better implementation would be to create a generic PDO auth backend.

Implementation might be tricky due to different SQL dialects. A small (lightweight) abstraction layer (or ORM) might help to avoid this problem. But making it usable with a limited set of databases would be fine too. At least MySQL and Postgres should be supported.

**Comment by badalmar** [comment]
Hello, could I help with this? I'm a little busy at the moment, which means I am unable to start working on it right away, so I am rather asking if it is ok.

**Comment by splitbrain** [comment]
@badalmar sure, go ahead

**Comment by badalmar** [comment]
So far I have tried replacing mysql_ and pg_ functions with their PDO counterparts, which works fine and this way there are only very few functions with differences between the two plugins.
However, I read through the #777 thread, from which I understand there might be a problem with availability of modern extensions (mysqli, PDO), does it mean there should exist the old plugin next to the PDO one?
Anyway, most importantly, I would like to ask how the abstraction layer should look like. Right now my idea would be to make an abstract ancestor out of the parts the two plugins have in common and its descendants would fill in the parts unique to them (kinda like it is now with authpgsql inheriting from authmysql), but I'm not quite sure.

**Comment by splitbrain** [comment]
The abstraction layer should most probably not be self written but use a lightweight existing library. It should allow specifying common DB  queries as code constructs thus abstracting away different SQL dialects. This would require a completely different configuration from what we currently have and might be hard to achieve in a flexible way. 

The alternative would be to keep an SQL based config approach and move all dialect specifics to the config. 

The task requires some knowledge of different database systems, common ways different applications store their user data and knowledge in PDO and available PHP libraries (thus difficulty:complex) but interaction with the DokuWiki core happens through a well defined interface only (thus: beginners project)
