### ISSUE TITLE
ACL list for a given scope

### ISSUE THREAD

**Issue by Startouf** [splitbrain/dokuwiki#1054]
I may be wrong, but there is no way to get the list of ACL rules affecting (only) a given page. Meaning, If I need to manage permissions from an external application through the XMLRPC API, I cannot even see the "current state" of permissions for a given page. 

It would be nice to be able to filter ACL rules for a given scope. 

A first step in this feature request would be to get a list of direct ACL rules affecting a given scope (existing ACL rules where the scope is exactly that of the one of the parameter)

A second step would be to list also the indirect ACLs affecting a given scope. For example : the rule `mynamespace:*` will affect the permissions of the page `mypage` which is situated under the namespace `mynamespace`

A third step would be to make this available for the XMLRPC API. I believe that if addAcl and removeAcl are available through the remote API, then it poses no additional security questions/issues to make such a function available remotely.

Because I need this functionnality for a project, I'll be working on a compromise Pull Request that adds a `get_all_ACL_settings()` function to the XMLRPC API.

**Comment by Klap-in** [comment]
Implemented via #1573 via #1550
