### ISSUE TITLE
authldap->retrieveUsers uses hardwired 'uid'

### ISSUE THREAD

**Issue by sklrrzn** [splitbrain/dokuwiki#1062]
I suggest introducing a new config variable in authldap, e.g. 'userkey' to declare the ldap attribute which holds the user id. The function 'retrieveUsers' could use it as follows:

```
$users_array = array();
$userkey     = $this->getConf('userkey', 'uid');
for($i = 0; $i < $entries["count"]; $i++) {
    array_push($users_array, $entries[$i][$userkey][0]);
}
```

**Comment by splitbrain** [comment]
see #1073
