### ISSUE TITLE
"::" breaks html

### ISSUE THREAD

**Issue by mdik** [splitbrain/dokuwiki#1065]
Minimal example:
`'':://''`

This can appear in something like
`''ftp:://localserver/files/something.txt''`

This makes the whole page italic.

**Comment by splitbrain** [comment]
because ```//``` opens an italic block and you never close it. Use ```''%%ftp:://localserver/files/something.txt%%''``` to escape wiki syntax if needed.

**Comment by mdik** [comment]
But it affects the _whole_ page, not only content. It would be nice if all dangling tags would be closed after content, so that the rest of the page is not affected.

**Comment by mdik** [comment]
PS: Thank you for the escaping syntax hint!
