### ISSUE TITLE
xmlrpc DokujClient Error: The processing instruction target matching “[xX][mM][lL]” is not allowed

### ISSUE THREAD

**Issue by flohmueller** [splitbrain/dokuwiki#1067]
This error occured when DokuJClient tried to parse an xml-response from dokuwiki.

The actual response is generated by a simple `echo '<?xml version="1.0"?>', "\n", $xml;` (see `IXR_Server\output($xml)`).
But what the client received contained a few whitespaces at the very beginning, which is a no-go for the xml parser (see http://stackoverflow.com/questions/19889132/error-the-processing-instruction-target-matching-xxmmll-is-not-allowed).

I couldn't find out where these whitespaces come from, but it might be a good idea in any case to insert an `ob_clean();` right before the echo. This solved the problem for me...

What do you think?

**Comment by splitbrain** [comment]
No. Figure out where the whitespace comes from and fix that (might be some config or language file). ob_clean() won't help unless your PHP is buffering by default.

**Comment by flohmueller** [comment]
just in case you're interested: I managed to identify the "real" cause.. it was the pagebreak's syntax.php file, which started with "&nbsp;&nbsp;&nbsp;&nbsp;<?php".

Thank you for the hint! Although it turned out it was neither a config nor a language file, it pointed me in the right direction.

**Comment by splitbrain** [comment]
can you please report this problem to the pagebreak author?
