### ISSUE TITLE
Enable/disable plugin with ACL

### ISSUE THREAD

**Issue by crash5** [splitbrain/dokuwiki#1069]
Hello,

please add a function to enable a plugin only to users with the appropriate ACL settings.

For example: pdf export works only for users in "export" group, or only for the registered users.

**Comment by splitbrain** [comment]
Plugin authors can implement this easily in their plugins. Alternatively a plugin could be written do this. However it is only useful for certain plugins. Disabling syntax plugins based on user/group would break with caching.
