### ISSUE TITLE
Adding "recursive_groups" setting for authad-plugin in configuration-manager

### ISSUE THREAD

**Issue by igittigitt** [splitbrain/dokuwiki#1075]
Should the adLDAP-Option "recursive_groups" added to be a configureable option inside Dokuwiki configuration manager?
To do this, the following changes should be applied
lib/plugins/authad/conf/default.php
  $conf['recursive_groups']   = 0;
lib/plugins/authad/conf/meta.php
  $meta['recursive_groups']   = array('onoff','_caution' => 'danger');
lib/plugins/authad/lang/en/settings.php
  $lang['recursive_groups']   = 'Resolve groups inside groups to their respective members (slower).';

**Comment by splitbrain** [comment]
can you create a pull request?
