### ISSUE TITLE
youarehere() problems

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#1082]
Other than the ongoing(?) discussion in #497, there are some problems in the current state of this function:

![2015-03-18-225844_249x66_scrot](https://cloud.githubusercontent.com/assets/86426/6720336/68dfe632-cdc2-11e4-8876-321ccaf7c20e.png)

* there are two colons after the "You are here" text
* the "You are here" text is styled differently from the trace text. Both should either be bold or not
* the current page is linked in the trace, but not the the youarehere navigation. Again this should be consistent

In addition there's an HTML error generated (a separator is outside the list scope):

![2015-03-18-231216_686x267_scrot](https://cloud.githubusercontent.com/assets/86426/6720573/58815972-cdc4-11e4-98e8-7a688dbd7b45.png)

@mprins @selfthinker I would like to have this resolved ASAP. Can you please have a look at this? Otherwise I will simply revert PR #497

**Comment by selfthinker** [comment]
@splitbrain, does that mean you hadn't even looked at the PR before you merged it?

As I mentioned earlier, I would vote for reverting. If I had time to fix things, I would also revert first and then start afresh.

**Comment by splitbrain** [comment]
I did look at it but didn't notice. So I guess we revert.

**Comment by selfthinker** [comment]
As the offending commits have been reverted, this can be closed.
