### ISSUE TITLE
Server timeout on large tables

### ISSUE THREAD

**Issue by qu3ns** [splitbrain/dokuwiki#1084]
I've got a large table on our dokuwiki with about 3300 lines. Whenever anybody hits the side that includes the table, the apache-server times out. On the server-log i get this message:

[Thu Mar 19 15:33:13 2015] [error] [client 10.0.1.6] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in [...]/dokuwiki/inc/parser/handler.php on line 1446

The Wiki is running on Version 2014-09-29d "Hrun".

This error surprised me, because i haven't had the issue on older releases of dokuwiki.

It is not possible to access the page anymore. For testing purpose I increased the ram of php to 2GB. It didn't help.

**Comment by joebordes** [comment]
Independently if the dokuwiki team can look into optimizing the time needed to process the table, you can try incrementing the max_execution_time directive in PHP

http://php.net/manual/en/info.configuration.php#ini.max-execution-time

**Comment by qu3ns** [comment]
@joebordes thank you very much for this idea. :+1: As you can see on the error message my `max_execution_time` is on 300 seconds. It previously was on 600 seconds when the error first occurs. I just gave it a try with 1200, but it didn't work. When the server throws the error message the user gets to see an blank white page with nothing but white. This happens after `max_execution_time` seconds. In the time between hitting the "table-page" and the server error, the particular user is not able to access any page of the wiki. Therefore i decided to decrease `max_execution_time` to 300. This way a user is cut of the wiki for "only" 300 seconds. :expressionless: However, the "table-page" does never get delivered to the user.

**Comment by joebordes** [comment]
A white page means a PHP error, in this case I understand that the only error you are getting in the logs is the timeout.

You can try setting error_reporting to E_ALL and display_errors ON so maybe you can get some additional clue to what is going on.

Can you share the page with us? So we can try to debug it?

**Comment by qu3ns** [comment]
Unfortunately I can not share the pageaddress as it is not publicly available without password anyway. However i created a gist with the txt file with dokuwiki-syntax that is very similar to the page we are talking about:
https://gist.github.com/qu3ns/5b72363a8ac61f3fc7ff

With
`php_value display_errors E_ALL`
`php_value display_errors ON`
i do not get any additional information on whats going on. I just got the error message i already had shown up in my browser.

On another dokiwiki-instance i've got the same behavior. i pasted the content of my gist to the public dokuwiki-playground to see what happens. and it is the same there:
https://www.dokuwiki.org/de:playground
hope this file gets reverted soon.

**Comment by joebordes** [comment]
This is the error I am getting:

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1048576 bytes) in /var/www/dokuwiki/inc/parser/handler.php on line 1502
```

**Comment by joebordes** [comment]
Doesn't look like there is an easy way around that. While somebody with more dokuwiki code knowledge than me has a look, I would suggest you break up the table into various pages.

**Comment by sascha-tasche** [comment]
Using \CachingIterator should help.

**Comment by qu3ns** [comment]
@sascha-tasche What do you mean with "Using \CachingIterator should help."?

**Comment by sascha-tasche** [comment]
I mean that the source should be rewritten and the class ```\CachingIterator``` should be used instead of an ```array```.

**Comment by splitbrain** [comment]
@sascha-tasche can you send a PullRequest wih your suggested changes?

**Comment by Klap-in** [comment]
Issue in our old tracker, that seems related: https://bugs.dokuwiki.org/index.php?do=details&task_id=2004

**Comment by qu3ns** [comment]
For some reason this error magically disappeared. I don't know how and why nor do i know when exactly it disappeared. For me it seams like the update to 2015-08-10 Detritus must have fixed this.

Thank you very much for your help. @joebordes @splitbrain @Klap-in @sascha-tasche 
@splitbrain and @dokufreaks thank you for creating DokuWiki. I love it!
