### ISSUE TITLE
Segmentation Fault Apache

### ISSUE THREAD

**Issue by rmfrankch** [splitbrain/dokuwiki#1086]
This seems to be a serious problem with Ubuntu and its latest software versions.

Environment:
Ubuntu 14.04LTS (upgraded from 12.04LTS) with latest patches (3.2.0-77-generic #112-Ubuntu)
apache (Apache/2.4.7 (Ubuntu), Mar 10 2015 13:05:59)
php5 (5.5.9-1ubuntu4.7 (cli), built: Mar 16 2015 20:47:39; Zend Engine v2.5.0; XCache v3.1.0) 
dokuwiki 2014-09-29d "Hrun" - 'naked' (only enabled user management and added one administrator)

all installed using apt-get, raised file upload size to 80M in php.ini
using virtual host on port 443 (https) for website access in apache with official certificate. (http shows same behaviour)

login as administrator
select site map, then syntax, or admin and then extension manager:
after an apache restart:
PHP Fatal error:  Cannot redeclare class DokuHTTPClient in /usr/local/web/dokuwiki/inc/HTTPClient.php on line 18
and no output. Back to admin, then extension manager again (and from there on always):
child pid 8773 exit signal Segmentation fault (11), possible coredump in /etc/apache2

If I disable php's xcache everything's fine. This does NOT happen without user management enabled!
If I remove the rss feed plugin and any code refering/using that, all is also fine.

**Comment by splitbrain** [comment]
```Cannot redeclare class DokuHTTPClient``` sounds wrong. That class should only be declared once and in that file. So maybe the package you used to install is broken? Have you tried to do a "normal" install?

**Comment by rmfrankch** [comment]
Hi,

Hmm, 'normal' ?
I simply donwloaded the current version, dumped that into a directory, called the installation script and added usermanagement with one user. Then logged in as that user. That's it. No other mods within dokuwiki.

-Robert

On 25 Mar 2015, at 09:44, Andreas Gohr <notifications@github.com> wrote:

> Cannot redeclare class DokuHTTPClient sounds wrong. That class should only be declared once and in that file. So maybe the package you used to install is broken? Have you tried to do a "normal" install?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Dep. Mathematik und Informatik  tel   +41 (0)61 267 14 66
Universität Basel
Robert Frank
Spiegelgasse 1 
CH-4051 Basel
Switzerland

**Comment by splitbrain** [comment]
I thought you said you installed DokuWiki via apt-get.

Anyway I must have missed the last line. It seems to be a bug in xcache. You can always pick a different accelerator. We're using APC without problems.

**Comment by T1st3** [comment]
I can confirm that, while using XCache, I have the same error. When Xcache is disabled or removed, the error disappears.
See: https://forum.dokuwiki.org/thread/10783

**Comment by NdK73** [comment]
I can confirm that xcache breaks updates and plugins manager on Debian Jessie too.
I think a check+warning could be useful.
