### ISSUE TITLE
Add new modern WYSIWYG editor?

### ISSUE THREAD

**Issue by nexflo** [splitbrain/dokuwiki#1091]
The current one looks and feels very oldschool. Most plugins for new ones are also not the best.

How about adding in redactor as native tool?

I do know it costs, but im sure we'll be able to get the money donated for it :)
http://imperavi.com/redactor/download/

Any thoughts?

**Comment by splitbrain** [comment]
uhm. no. this is wrong on many levels

* DokuWiki has no WYSIWYG editor, we have a syntax toolbar
* we can not distribute a proprietary editor with a opensource software
* integrating a HTML based WYSIWYG with a wiki syntax based backend is much more complicated than buying a license
* editors are not about looks
* ...

**Comment by q2apro** [comment]
> editors are not about looks

> uhm. no. this is wrong

Definitely vote for a doku-wysiwyg editor. There are also free open-source ones out there.
