### ISSUE TITLE
PHP 5.5 & Zend Server - Unable to Login - Possible root cause detected (related to #583)

### ISSUE THREAD

**Issue by pisc-software** [splitbrain/dokuwiki#1094]
We where fighting an issue with DokuWiki since months, documented in this thread:

https://github.com/splitbrain/dokuwiki/issues/583

Now after update to the current release we noticed that after the update Login did work and the logged-in session was sticking. A day after not anymore.

We also noticed that the update messages did not go away, despite having updated to the available release. Now reading the documentation we learned that deleting "data/cache/messages.txt" resets the update notifications.

Doing that also re-enabled sticking of the logged-in sessions. So apparently whenever DokuWiki has checked the update availability and the "data/cache/messages.txt" file exists the session does not stick is logged-in status.

**Comment by phy25** [comment]
Closing since we no longer support PHP 5.5 and I don't see any newly posted issues about this.
