### ISSUE TITLE
Update check fetches incorrect messages.txt

### ISSUE THREAD

**Issue by einhirn** [splitbrain/dokuwiki#1100]
I've got a problem with localization and Update check: Our wiki tries `http://update.dokuwiki.org/check/46,4` instead of  `http://update.dokuwiki.org/check/46.4` thus the update messages don't disappear although I've updated to the current version.

Problem seems to result from concatenating the float $updateVersion (from doku.php) with a string (in inc/infoutils.php -> checkUpdateMessages() )

Workaround is to modify doku.php so that $updateVersion is a string.

And to fix the problem with the current release for all those with non-english server localization: Please set "46,4" as a link to "46.4" on the server.

**Comment by magenbrot** [comment]
same problem here. As mentioned above putting "" around the the $updateVersion helped.
