### ISSUE TITLE
error during install in PassHash.class.php

### ISSUE THREAD

**Issue by drammock** [splitbrain/dokuwiki#1103]
This happened on first installation. I downloaded the stable tarball from the [official downloads page](http://download.dokuwiki.org/) with no extra language packs, and the "upgrade" and "wrap" plugins included.  Extracted tarball on my desktop and FTPd the whole folder to my webhost. When I go to `www.mydomain.com/dokuwiki/install.php` I get this error:

`unexpected T_STRING expecting T_OLD_FUNCTION T_FUNCTION T_VAR or } in PassHash.class.php line 79`

I tried deleting the whole installation, re-downloading from official page without the extra plugins, went through the same process, got the same error.  Then I tried using [the downloader script method](https://www.dokuwiki.org/install:downloader) which worked well up to the step where it passes me off to install.php, at which point I get a `500 Internal Server Error` (same issue as [this unanswered forum thread](https://forum.dokuwiki.org/thread/7016)).

I'm pretty sure the `unexpected T_STRING` is a bug.  I'll try the development snapshot next, and report back if it's still happening.  Not sure whether the downloader script `Internal server error` is a bug or a server config problem; my host's server is running PHP 5.3.x but maybe there's something else wrong with it.

**Comment by drammock** [comment]
Just tried again with the development snapshot 2015-04-02, still getting the error.  Here is the exact error text:

`Parse error: syntax error, unexpected T_STRING, expecting T_OLD_FUNCTION or T_FUNCTION or T_VAR or '}' in /home/booms0/public_html/dan/dokuwiki/inc/PassHash.class.php on line 98`

**Comment by splitbrain** [comment]
What's your environment?

**Comment by drammock** [comment]
Linux server. Kernel 2.6.18. Apache 2.2.24, PHP 5.3.26.

What's your environment?

—
Reply to this email directly or view it on GitHub
<https://github.com/splitbrain/dokuwiki/issues/1103#issuecomment-89509398>.

**Comment by drammock** [comment]
Here's a bit more server info (output of `curl --head`) now that I'm not responding from a phone:
```
HTTP/1.1 200 OK
Date: Sat, 04 Apr 2015 08:30:01 GMT
Server: Apache/2.2.24 (Unix) mod_ssl/2.2.24 OpenSSL/0.9.8e-fips-rhel5 mod_auth_passthrough/2.1 mod_bwlimited/1.4 FrontPage/5.0.2.2635 mod_fcgid/2.3.6
Last-Modified: Sun, 29 Mar 2015 08:54:25 GMT
ETag: "9740dc-1a0f-51269832a3240"
Accept-Ranges: bytes
Content-Length: 6671
Content-Type: text/html
```

**Comment by splitbrain** [comment]
Are you sure your webserver is using the right PHP version? The error message looks like a PHP4 failing at PHP5 syntax. From your curl output it seems your Apache is using FastCGI to access PHP, but it's not clear what version is used.
Can you create a ```phpinfo.php``` file in the dokuwiki directory with following content:

```
<?php
phpinfo();
```

and then call that file from your browser?

**Comment by drammock** [comment]
huh. You were right, it's 4.4.9.  I'll pester my webhost about it, since their web interface claims that they're running 5.3.26.
