### ISSUE TITLE
Problems after installing serveral plugins on Dokuwiki

### ISSUE THREAD

**Issue by juwa1310** [splitbrain/dokuwiki#1114]
Hi All,

running on private dokuwiki and version hirun. After installing plugins "anewssystem" or "tag", "pagelist" and "include" dokuwiki looses format, even installing only one of them:
Sidebar disappearing, buttons stagged, style is messed up. After removing plugins and saving with configuration manager, the format is ok.

1.) What is the problem with the plugins or my configuration?

2.) What I want to achieve is to mark serveral text snippets in varios pages of my wiki and display them as summary on one page. Should be a news summary or sort of news cloud. Is there another simple way without the plugins in 1.)?

I'm not a programmer and have already lost lots of time playing with dokuwiki. Can anybody help?

Thanks in advance for yr support!

Jürgen

**Comment by Klap-in** [comment]
Do you check the error log of your apache? Does it contain any errors?

**Comment by juwa1310** [comment]
Dear Gerrit,

my server runs on a Buffalo ls-wxl2 nas. Could only find the following 
over ssh:

Path:   /var/log/

apache/                         log.nmbd.2.gz
backup.log                      log.nmbd.3.gz
backup.log.1.gz                 log.nmbd.4.gz
backup.log.2.gz                 log.smbd
backup.log.3.gz                 log.smbd.1.gz
backup.log.4.gz                 log.smbd.2.gz

But cannot open the files! Is there another directory to access apache 
errors?

Best regards,

Jürgen

Jürgen Walther
Venantius-Arnold Str. 17
97877 Wertheim
Germany

Mobil 0160 376 90 21

Am 15.04.2015 um 20:56 schrieb Gerrit Uitslag:

**Comment by splitbrain** [comment]
First of all, figure out which of the plugins causes the problem by enabling them one by one. Once you figured that out report the bug at the appropriate bug tracker for that plugin.

**Comment by juwa1310** [comment]
Dear Andreas,

still couldn't solve the problem. Tried installation with Safemode hack 
but this feature gives me the following error:

Temporären Ordner konnte nicht erstellt werden, um Download zu empfangen

What is wrong with safemode hack?

You have a hint?

Best regards,

Jürgen


Jürgen Walther
Venantius-Arnold Str. 17
97877 Wertheim
Germany

Mobil 0160 376 90 21

Am 25.04.2015 um 08:36 schrieb Andreas Gohr:
