### ISSUE TITLE
Inconsistent ACL parsing

### ISSUE THREAD

**Issue by gturri** [splitbrain/dokuwiki#1115]
Under some circumstances, it's possible that the ACL displayed on the admin page, doesn't match the actual ones. Here is how we can reproduce this issue:
- Install a fresh new wiki (I just tested it with 2014-09-29a)
- Create a new user
- Activate xmlrpc interface, and add the admin to the list of authorized users (configs 'remote' and 'remoteuser')
- Add the 'read' permission for the new user on the start page. [1]
- Using the xmlrpc api, add the 'none' permission for the new user on the start page. [2]
- check the start page with the new user. Actual result: he can read it
- check the admin ACL page. Actual result: it says that the permissions for the new user on the start page is 'None'

Expected result 1: The ACL displayed on the admin page should match the actual permissions

Expected result 2:
- Either the new user cannot read the start page
- Or the last xmlrpc call should return an exception in order to show that we can't "add permissions '0'"

Misc: the issue seems to be due to the fact that the addAcl call add a line in acl.auth.php without removing / updating the existing one.
So it seems that if we fix the xmlrpc call, it could solve this issue.

[1]: it can be done easily using dokujclient (download and unpack [the archive](turri.fr/dokujclient/dokujclient-3.0.0.tar.gz)), with the command

```
 ./dokujclient --user new-user --password new-user-password --url http://localhost/dw-test-acl/lib/exe/xmlrpc.php addAcl --scope start  --username new-user --permission 1
```

[2]: it can be done with the command

```
 ./dokujclient --user new-user --password new-user-password --url http://localhost/dw-test-acl/lib/exe/xmlrpc.php addAcl --scope start  --username new-user --permission 0
```

**Comment by splitbrain** [comment]
Yes, I guess the RPC call should be fixed. Can you create a PR?

**Comment by gturri** [comment]
If I manage to find the time to do so, it would be with pleasure (perhaps during the "hackaton" in Paris in May)

**Comment by gturri** [comment]
Proposition of fix in https://github.com/splitbrain/dokuwiki/pull/2871
