### ISSUE TITLE
email/profile cache not updated after changing profile

### ISSUE THREAD

**Issue by lisps** [splitbrain/dokuwiki#1117]
after changing the email propterty in the users profile page and rechecking the profile page the email-field displays still the old value.

**Comment by splitbrain** [comment]
With which backend did you test that?

**Comment by selfthinker** [comment]
I just tested that and got the same issue with the standard `authplain`.
The value is correctly changed in `users.auth.php` though. Logging out and then in again also "fixes" it.

**Comment by lisps** [comment]
also with `authplain`

**Comment by Chris--S** [comment]
See my comments on #1488 about adding session invalidation code to updateProfile() when it updates a user's profile.
