### ISSUE TITLE
Option to make footnotes float where their references are.

### ISSUE THREAD

**Issue by FilSalustri** [splitbrain/dokuwiki#1120]
I use dokuwiki for courseware.
The movement to the bottom of the page for a footnote can be very distracting.  There is general agreement among my student users that it would be nice if footnotes appeared floating to the right or left of where they're referenced in the main text.
My current workaround is to use the wrap plugin.
However, I have to number those "sidenotes" and format the wrap boxes myself.
Given that the footnote syntax manages the numbering, and the wrap plugin shows it's possible to create sidenotes, I would like to suggest that something be added to allow footnotes to float like a WRAP can do.
This might be done by adding a new configuration option for footnotes - to have them appear at the end or to the side.
Alternatively, add an optional flag as the first argument to a footnote syntax element that tells it whether to float or to render at the end.
Or a whole other plugin could be generated.

**Comment by splitbrain** [comment]
Huh? That's a standard feature in DokuWiki since ages. If it doesn't work for you something is broken in your setup.

**Comment by michitux** [comment]
I think @FilSalustri means "float" not in the sense of an overlay as it is implemented in DokuWiki but in the sense of a HTML element with css style `float: right;` set. Nevertheless I think our current floating tool-tips should be enough in order to not to need to scroll to the bottom to the page.

**Comment by FilSalustri** [comment]
Yes, Michael is correct.  Setting the tool-tip functionality aside for a moment, the idea was to place the footnote to the side rather than at the foot, with, for instance, a `float: right;`.
This is just a suggestion that has been passed on to me by my students, which I thought I would post as such.
Clearly, if there is generally no interest in the idea, then just close the issue.
Thanks for the fast response in any case; it is appreciated

**Comment by splitbrain** [comment]
I think this could be achieved through some custom JavaScript (eg. in the template). I'm closing this.
