### ISSUE TITLE
protected passwords file

### ISSUE THREAD

**Issue by glensc** [splitbrain/dokuwiki#1137]
what you think if dokuwiki hold configuration items type password in separate file from local.php

the thing is that i version control my dokuwiki config, and would be good if passwords were excluded, i.e in separate file, which i would not track in VCS.

**Comment by selfthinker** [comment]
You could put those into `local.protected.php` and just not version control that file.

**Comment by glensc** [comment]
oh. that will do.

items in `local.protected.php` aren't configurable in admin config section anymore.

**Comment by selfthinker** [comment]
Yes, not modifying what's in `local.protected.php` is the point of that file.

You could also add a second `local` file to the `$config_cascade` in `inc/preload.php`. But that will also not help you if you'd like to configure it via the config manager as any changes will always be saved in only the last file.
