### ISSUE TITLE
Display different title when rendering admin page

### ISSUE THREAD

**Issue by FlominatorTM** [splitbrain/dokuwiki#1149]
When opening multiple tabs of my wiki where one contains the admin page, it would be really nice, if that tab would not be labeled like a tab that contains a normal article. 

Can you maybe add a prefix or something do be able to distinguish the admin page's title-attribute from others? For example in this screenshot it would then be "A:Start "or something

![admin](https://cloud.githubusercontent.com/assets/12448283/7636721/37f158de-fa69-11e4-8aa7-16911157d96c.png)

Thanks in advance,

Flo

**Comment by Klap-in** [comment]
I would suggest a more clear prefix like `[Admin]`

**Comment by FlominatorTM** [comment]
Thanks. Works like charm!
