### ISSUE TITLE
Add vary: accept-encoding header

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#1161]
We should send a vary header for all resources that are delivered gzip encoded (css, javascript)

some details why this is a good idead here: http://stackoverflow.com/questions/14540490/is-vary-accept-encoding-overkill

**Comment by splitbrain** [comment]
Hmm... we already do that. I forgot why I opened this ticket.

**Comment by duenni** [comment]
Here is the corresponding thread: https://forum.dokuwiki.org/thread/12586
