### ISSUE TITLE
code blocks not parsing -- correctly when at the start of line

### ISSUE THREAD

**Issue by grrrrr** [splitbrain/dokuwiki#1167]
If I create a code block, either done with double space or double ', where `--` are the first two characters, they are converted to a hyphen (`–`) instead of being preserved as two dashes.

for example

"--test" as code appears as

`–test`

"this is a --test" as code appears as 

`this is a --test`

The version of `Dokuwiki` being run is `2014-09-29b "Hrun"`

**Comment by selfthinker** [comment]
If a line starts with "  --test" it also shares the ordered list syntax (two spaces and a dash). I wouldn't necessarily say that's a bug. You always have the option to use `<code></code>` instead.

**Comment by grrrrr** [comment]
@selfthinker @ splitbrain it's not a line starts with, its a code block starts with.

So if I wanted to do a sentence with a code snippet in it like  "The correct switch to use would be --test to do option X."  I can use double ' and get the following

The correct switch to use would be `–test` to do option X.

Or I can do as you suggest  and use the <code></code> block but that messes with the layout and I get


The correct switch to use would be

    –test 

to do option X


So are my choices really break the layout or have incorrect information displayed (– instead of --)?

**Comment by splitbrain** [comment]
double ticks are not a code block, but monospace. You want non parsed a block possibly combined with monospace: ```The correct switch to use would be ''%%--test%%'' to do option X.```

**Comment by grrrrr** [comment]
@splitbrain ah ha. thank you...
