### ISSUE TITLE
FR: support for markup in headers

### ISSUE THREAD

**Issue by m384wwn** [splitbrain/dokuwiki#1170]
It would be nice if markup would be supported in headers. Not only would this allow for making headers more attention grabbing if needed it also this would provide better compatibility with some plugins such as CKGedit. (e.g. https://forum.dokuwiki.org/thread/12609 )

[Hope this is the right place for feature requests.]

**Comment by splitbrain** [comment]
This has been discussed a couple of times. It would require significant changes to our parser and complicate automatic TOC building.
