### ISSUE TITLE
Destroying the acl.auth.php using "UNDERCONSTRUCTION" tags

### ISSUE THREAD

**Issue by pizzarabe** [splitbrain/dokuwiki#1171]
Hi Guys,

some people in my department destroyed our Dokuwiki ACLS using the "CONSTRUCTION" tags.

They told my, they added the tags on a dokupage and after that nobody was able to edit pages. Anyway as a admin i can still edit pages except the one where they tried to add the construction tags.

After reviewing the acl.auth.php i saw that:

<code>*       @ALL    1*      @reader 1*      @nonmember      1*      @member 8layout:*       @ALL    0zzentwicklung:*        @ALL    0zzentwicklung:*        @member 16doku:name:page username        1       #UNDERCONSTRUCTIONdoku:name:page  @ALL    0       #UNDERCONSTRUCTIONdoku:name:page  username        0       #UNDERCONSTRUCTIONdoku:name:page  username        1       #UNDERCONSTRUCTIONdoku:name:page  @ALL    0       #UNDERCONSTRUCTIONdoku:name:page  username        0       #UNDERCONSTRUCTIONdoku:name:page username        1       #UNDERCONSTRUCTIONdoku:name:page @ALL    0       #UNDERCONSTRUCTIONdoku:name:page  username        0       #UNDERCONSTRUCTIONdoku:name:page  username        1       #UNDERCONSTRUCTIONdoku:name:page  @ALL    0       #UNDERCONSTRUCTIONdoku:name:page  username        0       #UNDERCONSTRUCTION </code>

"username" is the name of the user who added the CONSTRUCTION tag and "doku:name:page" ist the full doku name of the page.
Unfortunately i am not able to confirm any of these statements but i know they destroyed the acl conf using the webpage, because i am the only one with the passwords.

**Comment by splitbrain** [comment]
This should be reported in the bug tracker for the underconstruction plugin
