### ISSUE TITLE
pagetools-build.php should not be callable from the web

### ISSUE THREAD

**Issue by frankgajda** [splitbrain/dokuwiki#1184]
Pagetools-build.php should probably not be callable from the web. (Re)building the pagetools-sprite should not be possible/necessary from the web.

**Comment by gamma** [comment]
It would be great to have this tool or something different available globally - or from admin page or whatever so that plugins can add their own pagetool icons and have them rendered with correct colors.

**Comment by Klap-in** [comment]
The tool is located in the 'dokuwiki' template folder, so even available locally.
https://github.com/splitbrain/dokuwiki/blob/master/lib/tpl/dokuwiki/images/pagetools-build.php

**Comment by splitbrain** [comment]
#874 would solve the problem as it makes use of our new CLI class. It also provides a mechanism for plugin authors to create matching icons.

**Comment by splitbrain** [comment]
this has been fixed in b7f0385
