### ISSUE TITLE
unable to use wget in <code> tag - error 406

### ISSUE THREAD

**Issue by jensmuehlenberg** [splitbrain/dokuwiki#1186]
Unable to use wget in <code> tag :-( --Release 2014-09-29d "Hrun"

**Comment by Klap-in** [comment]
Can you place a sample of your syntax, please?

**Comment by jensmuehlenberg** [comment]
<code>sudo wget http://sourceforge.net/projects/phpipam/files/latest/download</code>

**Comment by jensmuehlenberg** [comment]
when saving the page, the page comes up wir error 404

**Comment by Klap-in** [comment]
On dokuwiki.org it looks fine:
https://www.dokuwiki.org/playground:codewget

Can you test there as well?

**Comment by ptbrown** [comment]
Could the error be a 403 "Forbidden" error? An application firewall may be flagging the embedded URL as suspicious and denying access. This happened to me when I tried to link to creativecommons.org. I know it wasn't anything in my DokuWiki or Apache configuration. I suspected then it must be the ISP.

**Comment by jensmuehlenberg** [comment]
This is the error im getting when using the wget in <code>
![bildschirmfoto 2015-06-08 um 23 54 50](https://cloud.githubusercontent.com/assets/9340084/8046302/16db2546-0e3a-11e5-9625-623133777a42.png)

**Comment by jensmuehlenberg** [comment]
ok, on dokuwiki playground it is working
https://www.dokuwiki.org/playground:codewget

is there something in configuration i have to change?

**Comment by ptbrown** [comment]
"Not Acceptable" is error 406. (The 404 is because there was no error page for 406 in the Apache configuration.)

DokuWiki does not generate a 406 error for anything.

**Comment by splitbrain** [comment]
see doku.wiki/faq:mod_security

**Comment by jensmuehlenberg** [comment]
@splitbrain. Thank u very much. this solved my problem. best regards jens
