### ISSUE TITLE
Request: pass more parameters to table_open() and tablerow_open()

### ISSUE THREAD

**Issue by simon-r-white** [splitbrain/dokuwiki#1188]
Currently Dokuwiki tables are opened using table_open() with the code:

    /**
     * Start a table
     *
     * @param int $maxcols maximum number of columns
     * @param int $numrows NOT IMPLEMENTED
     * @param int $pos     byte position in the original source
     */
    function table_open($maxcols = null, $numrows = null, $pos = null) {
        // initialize the row counter used for classes
        $this->_counter['row_counter'] = 0;
        $class                         = 'table';
        if($pos !== null) {
            $class .= ' '.$this->startSectionEdit($pos, 'table');
        }
        $this->doc .= '<div class="'.$class.'"><table class="inline">'.
            DOKU_LF;
    }

It would be helpful for writing custom CSS if plugins could add classes to the xhtml generating the table, for example

    function table_open($maxcols = null, $numrows = null, $pos = null, $classes = null) {
        // initialize the row counter used for classes
        $this->_counter['row_counter'] = 0;
        $class                         = 'table';
        if($pos !== null) {
            $class .= ' '.$this->startSectionEdit($pos, 'table');
        }
        if($classes !== null) {
            $class .= $classes;
        }
        $this->doc .= '<div class="'.$class.'"><table class="inline">'.
            DOKU_LF;
    }

Similarly, if instead of simply numbering the table rows (i.e. row1, row2, etc), we could insert plugin specified row names.

A specific use of this would be for the data-plugin or strata-plugin to customize the generated tables.

I'm not very familiar with the Dokuwiki codebase, but is there a reason this change wouldn't be simple (or would it break something)?

**Comment by Klap-in** [comment]
This issue is similar to #1360 (accompanied by PR  #1515 )
