### ISSUE TITLE
registration form allows registration of users with under three characters

### ISSUE THREAD

**Issue by Be-ing** [splitbrain/dokuwiki#1190]
The DocuWiki registration form for Mixxx (http://mixxx.org/wiki/doku.php/?do=register ) allows me to register a username with two letters and a period. When I first tried to register a user with two letters ("Be"), it did not let me register. It cleared the captcha and left the other fields of the form filled out but did not show any error.

So, I tried putting a period at the end of username. It let me register and sent an email with a password. However, after logging in, whenever I tried to edit a page, I was brought to a page that said nothing except: "Sorry, there was an error processing your request. If this is an error
contact us at info AT mydomain.com." Someone on the Mixxx mailing list suggested it might be because I had a username with less than three characters. The administrator deleted my original account and I reregistered an account with the username "be." When I went to log in, I noticed the actual username in the system was "be", without the period at the end.

**Comment by Klap-in** [comment]
Where is the length of the username checked? I cannot find any code doing this.

Only a not-empty check: https://github.com/splitbrain/dokuwiki/blob/master/inc/auth.php#L932

**Comment by phy25** [comment]
I am not sure if this is still an issue, but I am able to self-register users with one or two character username with the latest DokuWiki.
