### ISSUE TITLE
Page remains draft after confirmation of changes

### ISSUE THREAD

**Issue by m3t4lukas** [splitbrain/dokuwiki#1191]
The hint remains as to be seen in the screenshot after confirming the changes in the editor.
![screenshot-window-2015-06-10-154410](https://cloud.githubusercontent.com/assets/3659917/8083849/de7e2bf4-0f87-11e5-9e7c-3928daa053d5.png)

**Comment by Klap-in** [comment]
This notice is from a plugin, please look at the information of the plugin for how to use it.
Or when it is an issue, please report it at the issue tracker of that plugin.

**Comment by m3t4lukas** [comment]
Okay, didn't know what was plugin and what was core behaviour. Somebody else set it up so does anybody know the name of that plugin?

**Comment by Klap-in** [comment]
I don't know the plugin by heart, do you know/can you see which plugins are installed?
Maybe it is the Approve or the Publish plugin?

**Comment by m3t4lukas** [comment]
then it must be the publish plugin.
I will try an update of that particular plugin.

**Comment by m3t4lukas** [comment]
I kicked it out :P Now everything works just fine

**Comment by Klap-in** [comment]
Nice!
