### ISSUE TITLE
Standard mechanism to delete files from plugin directory

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki#1192]
For the ODT plugin I like to move from `action.php` to two components in the `action/` folder.
This is not possible because the `action.php` cannot be removed from the folder.

Is this worth a mechanism that let the plugin author remove blacklisted files?

`/lib/plugins/<plugin>/deleted.files`
which list files that can be removed e.g.
```
# This is a list of files that were present in previous plugin releases
# but were removed later. An up to date plugin should not have any of
# the files installed
action.php
folder/file.txt
```

**Comment by splitbrain** [comment]
Yes, I think such a mechanism would be helpful.
