### ISSUE TITLE
Edit page gives warning on unload even when nothing changed

### ISSUE THREAD

**Issue by zioth** [splitbrain/dokuwiki#1199]
1) Edit a page.
2) Click on the content and use the arrow keys to move around.
3) Refresh the page.
4) You get a warning, saying you've modified the page.

The fix can be made in edit.js:

			var content = $edit_text.val();
			window.onbeforeunload = function() {
				if (window.textChanged && content != $edit_text.val())
					return LANG.notsavedyet;
			};

This is an issue I run into frequently, because I often copy an existing page to the clipboard as the basis for a new page.

**Comment by Klap-in** [comment]
Does this check catch all changes by modifications via the mouse actions?
 * [ ] middle mouse click paste (default linux feature)
 * [ ] moving text
 * [ ] paste, cut etc
 * [ ] other?

**Comment by zioth** [comment]
Yes, it should cover all those cases, because the check is made when you close the window, not when you edit.

This fix does not address the edited state of the bar under the editor. That bar still exhibits the bug. To fix that, you'd need better keystroke handling, and you'd need to handle all the cases you mentioned seperately.

**Comment by Klap-in** [comment]
What do you mean with 'bar under the editor'? I don't get your point.

**Comment by zioth** [comment]
Sorry. I was talking about the way "edit summary" turns pink. My fix doesn't prevent it from turning pink when you use arrow or control keys.

**Comment by Klap-in** [comment]
Looking at code that sound related to the note about plugins of Michitux in the pull request. I will look how this can be impemented more gentle.
