### ISSUE TITLE
PHP7 compatibility patch breaks xmlrpc interface on ubuntu 14.04

### ISSUE THREAD

**Issue by gturri** [splitbrain/dokuwiki#1200]
* Steps to reproduce

** On Ubuntu 14.04 (more details on the environment below), install a development snapshot of dokuwiki (commit 26e22ab837dcabe137a0912fcd2f96d0c35f48c8 or newer)

** Make any request on the xmlrpc interface. For example, using [Dokujclient] (https://github.com/gturri/DokuJClient), we can do

    dokujclient --url http://<myHost>/<myWiki>/lib/exe/xmlrpc.php  getTime

* expected result: we get the result of the xmlrpc query
* Actual result: we get an error, and in the apache error logs we have

    PHP Fatal error:  Call to undefined method dokuwiki_xmlrpc_server::IXR_Server() in /var/www/html/wikiDev/lib/exe/xmlrpc.php on line 23
    PHP Stack trace:
    PHP   1. {main}() /var/www/html/wikiDev/lib/exe/xmlrpc.php:0
    PHP   2. dokuwiki_xmlrpc_server->dokuwiki_xmlrpc_server() /var/www/html/wikiDev/lib/exe/xmlrpc.php:65
 
* Misc: thanks to  git bisect, it can be seen that this regression has been introduced by 26e22ab837dcabe137a0912fcd2f96d0c35f48c8

* Environment:

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 14.04.2 LTS
    Release:	14.04
    Codename:	trusty
    $ php --version
    PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**Comment by Klap-in** [comment]
I committed a fix with 0c43e7198c135083b88bdad3dd7876a8ff8a2870, but I didn't test it.
Can you test it? Thanks!

**Comment by gturri** [comment]
yes, it's fixed.
Congrats! :+1:
