### ISSUE TITLE
Paragma: no-cache header breaks downloads over HTTPS for Internet Explorer

### ISSUE THREAD

**Issue by lawsonk** [splitbrain/dokuwiki#1201]
Due to a known issue in Internet explore you can't download MS office documents in IE when the "Paragma: no-cache" header is set. See the MS article under "Error message 4" here: 

https://support.microsoft.com/en-us/kb/316431

Removing the header fixes it here but I'm not sure of the security implications. Here's the diff with my working version: 

    diff -u orig_fetch.functions.php fetch.functions.php
    --- orig_fetch.functions.php    2015-06-17 15:46:49.540301479 -0400
    +++ fetch.functions.php 2015-06-17 15:47:07.772301997 -0400
    @@ -51,13 +51,11 @@
                 // cache in browser
                 header('Expires: '.gmdate("D, d M Y H:i:s", $expires).' GMT');
                 header('Cache-Control: private, no-transform, max-age='.$maxage);
    -            header('Pragma: no-cache');
             }
         } else {
             // no cache at all
             header('Expires: Thu, 01 Jan 1970 00:00:00 GMT');
             header('Cache-Control: no-cache, no-transform');
    -        header('Pragma: no-cache');
         }
    
         //send important headers first, script stops here if '304 Not Modified' response

**Comment by Klap-in** [comment]
How are other browsers behaving?

**Comment by lawsonk** [comment]
Works fine in Firefox and Chrome. I can only assume they ignore the header and download the file to a temp location anyway. IE won't do that to open it in Office if Pragma: no-cache is set.
