### ISSUE TITLE
GeSHI treating URL components as keywords

### ISSUE THREAD

**Issue by richardswinbank** [splitbrain/dokuwiki#1207]
This issue was reported on the forum by user guiguiche (https://forum.dokuwiki.org/thread/12651), relating to the scilab language.

The GeSHI language file for scilab includes the documentation URL www.scilab.org, and specifies "scilab" as a keyword. It looks as if DokuWiki is identifying the token between "www." and ".org" as this keyword, so rendering the URL suffix into the output code block.

**Comment by Klap-in** [comment]
What do you mean?
I cannot reproduce it at https://www.dokuwiki.org/playground:scilab
Please can you change it to your case to show the current behavior?

**Comment by richardswinbank** [comment]
I've added a third code block to the playground page which shows the issue.

**Comment by splitbrain** [comment]
The same error happens at https://qbnz.com/highlighter/

This should be reported and fixed upstream.

**Comment by richardswinbank** [comment]
Will do; thanks.

**Comment by Klap-in** [comment]
See also: https://github.com/GeSHi/geshi-1.0/issues/36

**Comment by BenBE** [comment]
Do you have some short sample code to reproduce/debug locally? TIA.
