### ISSUE TITLE
Zero-Width-Whitespace introduced in revision diff after / within <code> tags

### ISSUE THREAD

**Issue by micgro42** [splitbrain/dokuwiki#1208]
When changing text within `<code>` tags, zero-width-spaces are introduced within the diff-view, but they are not present before or after.

Example:
https://www.dokuwiki.org/playground:zwsp?rev=1435155666&do=diff

Try to copy the changed line into vim to see the zero-width-spaces.

I am not sure if this is a frontend or backend problem. It happens both with Firefox and with Google Chrome.

**Comment by Klap-in** [comment]
That is a feature in the diff view, to improve text wrapping. It is added quite recently.
In which manner are you affected by this?

**Comment by Klap-in** [comment]
I thought somewhere around these changes, however not exactly these.. https://github.com/splitbrain/dokuwiki/pull/179

**Comment by Klap-in** [comment]
@Chris--S do you know more about this?

**Comment by splitbrain** [comment]
I now remember doing it, but can't find the code either :-)

**Comment by micgro42** [comment]
Well since this happens inside `<code>` tags, one might be ocassionally be tempted to copy-paste code vom the diff-view into your IDE or terminal.
However unless your IDE is vim your code won't work. And there is no reason to expect code copied from the diff to not be just code, but code with `<200b>`.

concrete example: it took us quite some time to figure out why
`sudo cat /proc/fs/cifs/SecurityFlags`
worked, but
`sudo cat /​proc/​fs/​cifs/​SecurityFlags`
did not and apparently I did not even have the `/​proc` dir. The reason was, that the path of the second string was copied from a diff view.

**Comment by micgro42** [comment]
I think that's the one: #165

**Comment by micgro42** [comment]
As I get it the Motivation back than was to improve linebreaks. Could we do this with javascript?

**Comment by splitbrain** [comment]
I don't see how JavaScript would help here. What we would need is a way to insert breaking points that will not be copied when selecting text.

Replacing the zero-width space with ```&shy;``` or ```<wbr>``` might work. http://stackoverflow.com/questions/226464/soft-hyphen-in-html-wbr-vs-shy sends mixed signals on their compatibility. Needs research.

**Comment by micgro42** [comment]
Since I just again spent what feels like hours because of this, I've written a plugin to solve the problem for now: https://github.com/cosmocode/dokuwiki-plugin-preventzerowidthchars 😠
