### ISSUE TITLE
Why is this page broken?

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki#1209]
The page is empty and no pagetools are displayed at:

https://www.dokuwiki.org/plugin:keywords

@frankgajda: is there any server error?

**Comment by Chris--S** [comment]
Yes.  Did pluginrepo just get updated?

```
PHP message: PHP Fatal error:  Call to a member function diff() on boolean in /var/www/wiki/htdocs/lib/plugins/pluginrepo/syntax/entry.php on line 114
```

**Comment by Klap-in** [comment]
Just recently introduced in pluginrepo, the plugin is updated yesterday and today. See also refered issue above this comment.

**Comment by selfthinker** [comment]
Just as a reference (because it isn't clear the way the previous comment is written): This will be fixed with https://github.com/splitbrain/dokuwiki-plugin-pluginrepo/issues/94

**Comment by selfthinker** [comment]
I just "fixed" that page (by correcting the date). That is not the real fix and other pages might still be affected until the above mentioned fix is released.

**Comment by selfthinker** [comment]
Argh, sorry, I got that wrong, this will not be fixed by the above (that is just another bug report in the correct bug tracker) but by something in https://github.com/splitbrain/dokuwiki-plugin-pluginrepo/pull/96

**Comment by phy25** [comment]
Looks like this can be closed since the PR has been merged.
