### ISSUE TITLE
Disable "reset password" display if LDAP authentication is used

### ISSUE THREAD

**Issue by 3eka** [splitbrain/dokuwiki#1219]
Hi,

if we authenticate user from LDAP, then reset/resend password functionality has no meaning and is just misleading user...

Instead, show to user info that she/he has to use LDAP password (or even, add note for user to contact sysadmins to solve issue).

Regards.

**Comment by Klap-in** [comment]
In the development version a config is introduced for enabling/disabling pasword editing via the dokuwiki: https://github.com/splitbrain/dokuwiki/pull/1073

Text above the login form can be replaced by your own (localized) text. See https://www.dokuwiki.org/localization#changing_some_localized_texts_and_strings_in_your_installation

**Comment by Klap-in** [comment]
**Question**: 
Can enabling for pasword-changing via DokuWiki be detected automatically? (instead of that it is manually set via a config setting)

**Comment by 3eka** [comment]
Well,

I want to have password change disabled from DokuWiki, because that is not goal (we can use another way to change LDAP password).

To be more precise (if this is possible to integrate with that change from https://github.com/splitbrain/dokuwiki/pull/1073):

if LDAP auth; then disable passwd change and set proper message (wiki uses LDAP for auth, etc); fi

Regards.

**Comment by Klap-in** [comment]
We will not disable password editing via DokuWiki, or there should be more votes to have that as default...

We will not modify that message automatically. You have to change this text your self. But that is saved when if updating, if you use the correct folder

Original files are in (for English):
https://github.com/splitbrain/dokuwiki/blob/master/inc/lang/en/login.txt
https://github.com/splitbrain/dokuwiki/blob/master/inc/lang/en/denied.txt

Modified files you have to store in (for English):
` conf/lang/en/`

**Comment by 3eka** [comment]
Hi,

thanks, somehow I have missed that location..
Best regards.
