### ISSUE TITLE
missing urlencode for % in interwiki parser

### ISSUE THREAD

**Issue by Wyuld0** [splitbrain/dokuwiki#1220]
Hi,
I came accros a problem witch seems to be related to a parsing bug:
With the latest dokuwiki release version  2014-09-29d "Hrun", I found an interwiki parsing bug with  wikipedia when the page title contains character % because it is not urlencoded.
The following interwiki shortcut produces a wrong HTML code althoug the page https://fr.wikipedia.org/wiki/Real_Humans_:_100_%25_humain exists:
`[[wpfr>Real Humans : 100 % humain]]`

To workarround, I had to write:
`[[wpfr>Real Humans : 100 %25 humain|Real Humans : 100 % humain]]`

I Hope that report will be usefull.

**Comment by ptbrown** [comment]
Wiki links use the `{NAME}` substitution. Using the `{URL}` substitution would escape percent signs, but it will also encode spaces, colons, braces, etc. Wikipedia accepts encoded names just fine (from my brief testing of various escaped characters and UTF-8) but I don't know if other wiki software would complain that `This_Name` is not the same as `This%20Name`.

Is it right that `{NAME}` does no translation of the name? It should at least encode the URI reserved characters `"',;<>?[]{|}%&` (https://en.wikipedia.org/wiki/Help:URL) Note that the colon is not included, and although comma is I've seen some WP links that include it unescaped. Should spaces be converted to underscore or encoded?

On the other hand, there are other schemes using `{NAME}` that probably don't expect escapes. The `tel` scheme for instance uses semicolons. But it still requires escaping of other characters.

I think it will be best to have `{URL}` encode all characters as it already does, `{NAME}` encode the characters listed above and space as `%20`, and if you need a more complicated URL use a full external link.

**Comment by splitbrain** [comment]
@ptbrown yeah I guess doing minimal encoding as you suggested on {NAME} would be good.

However I would leave out the ```;```, ```?``` and ```;``` chars and keep them as is as these are commonly used for parameter delimiters and people may want to pass multiple parameters to the {NAME} shortcuts.

**Comment by ptbrown** [comment]
The next question is should the Wikipedia links be `{NAME}` or `{URL}`?

A strictly unencoded option will be needed for cache links like `coral>` as well.
