### ISSUE TITLE
Remove or made an Option to disabel local links warning

### ISSUE THREAD

**Issue by Mannshoch** [splitbrain/dokuwiki#1233]
With Firefox add-ons or a hack in the Firefox about:config its possible to open Links from a network drive.
Please add somewhere an Option to deactivate this Popup.

Our Server Admin say he do not edit source code. If an option in the settings of a Program is not given he do not set it. 
So at moment I do not use firefox as I originally wish.

thanks
Mannshoch

**Comment by splitbrain** [comment]
It can be disabled by setting the appropriate language string to an empty string. Strings can be overwritten in an upgrade safe way.

**Comment by Klap-in** [comment]
Explanation for changing (localized) language strings:
https://www.dokuwiki.org/localization#changing_some_localized_texts_and_strings_in_your_installation

Original strings:
https://github.com/splitbrain/dokuwiki/blob/master/inc/lang/en/lang.php#L143

Can be overwritten by creating `conf/lang/en/lang.php` with:
```php
<?php
/**
 * Customization of the english language file
 * Copy only the strings that needs to be modified
 */
 $lang['js']['nosmblinks'] = '';
```

**Comment by mrclschstr** [comment]
I created the file `conf\lang\de\lang.php` with the following content:

```php
<?php

/**
 * Customization of the german language file
 * Copy only the strings that needs to be modified
 */

$lang['js']['nosmblinks']      = '';
```

Unfortunately this has no effect. I still get the Javascript message. Do I have to clear the cache or something? I already cleared my browser cache and history.

**Comment by Klap-in** [comment]
Please go to the configuration manager and use the Save button.
Resaving clears some caching, I expect that could update your string as well.
After this resaving, use in your browser the shortcut `Ctrl + F5`. This refreshes some caches of your browser.

**Comment by mrclschstr** [comment]
Thanks!
