### ISSUE TITLE
I don't get subscribe notifications for my plugin

### ISSUE THREAD

**Issue by zioth** [splitbrain/dokuwiki#1241]
I recently created http://dokuwiki.org/plugin:fastwiki . I'm subscribed to all pages in the plugin: namespace (daily digest). Although I've edited the page many times, fastwiki never shows up in the daily email.

If this is because I'm logged in and I own the plugin, feel free to close this ticket as being stupid. :)

**Comment by Klap-in** [comment]
Did you notice my minor change?

It is not because you are owner of the plugin, but because you are editor *and* subscriber of the page. See the first section of https://www.dokuwiki.org/subscription for the details.

**Comment by selfthinker** [comment]
Yes, what Klap-in said. To quote the page he linked:

> When a page is changed by a user all *other* users who have subscribed to that page will receive an email describing the changes. The user changing the page will not receive an email.
