### ISSUE TITLE
make the table header to stay visible on very long tables

### ISSUE THREAD

**Issue by trebmuh** [splitbrain/dokuwiki#1243]
Hi and thanks for dokuwiki. This is a feature request. It'd be very nice to implement something like in Tiki. Example : http://www.linuxmao.org/Cat%C3%A9gorie+enregistreurs+%C3%A9diteurs+audio
If you are scrolling down, the header of the table stay a the top (and it disappears if you're scrolling downer).

**Comment by Klap-in** [comment]
A plugin that is recently added, could help you to layout your tables with some versatile options: 
https://www.dokuwiki.org/plugin:datatables

At first sight, this plugin has not yet the exact feature you like, but maybe you could consult with the author of that plugin if it is possible to add that extension to the datatable plugin ...
https://datatables.net/extensions/fixedheader/

**Comment by trebmuh** [comment]
Done. Thanks for your advice @Klap-in .

**Comment by trebmuh** [comment]
This one has been made https://github.com/LotarProject/dokuwiki-plugin-datatables/issues/3 .
It can be closed then.
