### ISSUE TITLE
Authgoogle plugin "Allowed email domains" configuration parameter not working

### ISSUE THREAD

**Issue by gaborherman** [splitbrain/dokuwiki#1244]
When you specify the "Allowed email domains" parameter for Authgoole it won't let anyone in, from any domain. The reason is:
auth_plugin_authgoogle::_check_email_domain compares the entire email address with a domain (which is never equal). Fix:
correct this:
                if ($email == $domain) return true;
to this:
                $emaildomain = substr(strrchr($email, "@"), 1);
                if ($emaildomain == $domain) return true;

**Comment by splitbrain** [comment]
This should be reported in the plugin's bug tracker.
