### ISSUE TITLE
Footnotes break metadata abstract saving

### ISSUE THREAD

**Issue by michitux** [splitbrain/dokuwiki#1250]
During metadata rendering, an abstract consisting of the first 250 bytes is captured. When a footnote is encountered during this first part of the page, strange things happen. If abstract saving ends inside the footnote, only the text of the footnote is in the abstract. If abstract saving continues, the part before the footnote is restored, but the length of the footnote still counts against the abstract length, so at the end it will be too short.

I think instead of saving away the current text footnotes should rather temporarily disable capturing and re-enable it at the end of the footnote if it was enabled before it (i.e. the state needs to be saved).

**Comment by Michaelsy** [comment]
This bug is again and duplicated reported (and discussed) in #2383.
