### ISSUE TITLE
Support Creative Commons 4.0

### ISSUE THREAD

**Issue by maliktunga** [splitbrain/dokuwiki#1286]
I noticed that DokuWiki only supports Creative Commons version 3.0. I would rather use version 4.0.

**Comment by Klap-in** [comment]
You can extend the default license list by `license.local.php` (see https://www.dokuwiki.org/config and https://www.dokuwiki.org/config:license)

It appears for me that CC4.0 could be a quite common license, you might create a pull request which add this license. Or you could share here the details, i.e. exact name and url, such that someone could create a pull request.

**Comment by maliktunga** [comment]
@Klap-in Here are the licenses.

Creative Commons Attribution 4.0 International (CC BY 4.0)
http://creativecommons.org/licenses/by/4.0/

Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
http://creativecommons.org/licenses/by-sa/4.0/

Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)
http://creativecommons.org/licenses/by-nd/4.0/

Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)
http://creativecommons.org/licenses/by-nc/4.0/

Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)
http://creativecommons.org/licenses/by-nc-sa/4.0/

Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
http://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by maliktunga** [comment]
@Klap-in Should the licenses be added, or should they replace version 3.0? If they are added, what should be their value inside $license[]?

**Comment by splitbrain** [comment]
@maliktunga that is an interesting question indeed. I guess people who picked a license didn't really care for the version and wouldn't mind using the new one. However I don't know how much versions really differ. Like GPLv2 and GPLv3 differ in very important points, so you can't exchange one against another. My gut feel is that version updates in CC licenses are just improved legalese to mean the same thing. But I'm not a lawyer. Could you research this?

**Comment by maliktunga** [comment]
@splitbrain From my understanding — I am no lawyer either — version 4.0 is indeed simply clearer (in legalese) than version 3.0, in order to protect the freedom of culture. All details are available at https://wiki.creativecommons.org/wiki/Version_4

Also from this page: http://creativecommons.org/version4

"Creative Commons worked for more than two years to develop the next generation of CC licenses — the version 4.0 CC license suite. **The new licenses are more user-friendly and more internationally robust than ever before.**"

I personally made text bold to highlight.
