### ISSUE TITLE
Subscript and superscript breaks links

### ISSUE THREAD

**Issue by grexe** [splitbrain/dokuwiki#1288]
When formatting a `[[link]]` that contains `<sup>` or `<sub>` tags, the link is rendered incorrectly, e.g.
`[[reference <sup>1</sup>]]` is literally rendered as `reference <sup>1</sup>`.
Using DokuWiki 2014-09-29d "Hrun" on Linux x64.

**Comment by splitbrain** [comment]
formatting within links is not supported for technical reasons
