### ISSUE TITLE
SwiftMail plugin has been obsoleted by SMTP plugin and should be removed

### ISSUE THREAD

**Issue by grexe** [splitbrain/dokuwiki#1294]
I had problems getting DokuWiki (Hrun) mail support to work and wasted some time with the old SwiftMail plugin only to find out that it has been replaced by a new SMTP plugin:
https://www.dokuwiki.org/plugin:smtp
There it says
"This plugin mainly replaces the old SwiftMail plugin."
Can we please bury the old plugin as it has problems with TLS authentication?
With the new SMTP plugin, everything worked out of the box - wish I had known this before.

So please could someone at least document this or deprecate the old plugin?

**Comment by splitbrain** [comment]
> Can we please bury the old plugin as it has problems with TLS authentication?

swiftmail should work with TLS

> With the new SMTP plugin, everything worked out of the box - wish I had known this before.

the wiki page mentions the new smtp plugin right at the ebginning

> So please could someone at least document this or deprecate the old plugin?

it's a wiki



-- 
splitbrain.org
