### ISSUE TITLE
Can not use the windows shares after the update to Detritus

### ISSUE THREAD

**Issue by LardVerschuren** [splitbrain/dokuwiki#1302]
My existing links to files via Windows shares in dokuwiki don't work after the update to Detritus. I have found that the code put too much slash by:

file:///server/test.xlsx

And that must be only two slashs such as file://server/test.xlsx.

Can somebody fix it? :-)

**Comment by Klap-in** [comment]
Here additional slashes are trimmed: 83b7e38df41d6f1c41ee6818b4838addfbf95e1a

Since 2005 the three slashes where already there: 
windows shares links modified: 1d47afe198e9605cb1a0bb7a80b16df1256f82ad
added as new code: 0cecf9d507451346a32ddf45a85b425784fbb0f8

Why has it works fine for so long time, but is it recently that people observe this behavior?

btw, What is the syntax that you used in the wiki text?

**Comment by splitbrain** [comment]
Three slashes should be correct. The first two are the protocol divider. The third is the root directory.

**Comment by LardVerschuren** [comment]
The syntax is very simple: [[\\server\data\ict\sheet.xlsx|Here is the sheet]. And it has worked for years. After the upgrade to Detritus it does not work. IE reports that the page can not found and the link in the address space is: 
res://ieframe.dll/dnserror.htm#file:///server/data/ict/sheet.xlsx

If I manual adjust the url to file://server/data/ict/sheet.xlsx then it works. 

Should it matter if my PHP version is 5.3.4? It should be supported, I mean.

**Comment by selfthinker** [comment]
Windows shares haven't worked for me since a while as well. Will try to figure out if it does work for me before that change.

**Comment by Chris--S** [comment]
According to this two slashes is correct, http://blogs.msdn.com/b/ie/archive/2006/12/06/file-uris-in-windows.aspx

**Comment by cahooa** [comment]
We have the exact same issue, after updating to Detritus, none of our windows share links work. Removing one of the slashes, from the file part of the URL fixes the problem. How can I fix this?

**Comment by selfthinker** [comment]
@Klap-in, you were reading the code wrong, it has always been **four** slashes until 83b7e38df41d6f1c41ee6818b4838addfbf95e1a. Read the line before... the `$url` always included one slash already... until it got removed by the change in #926.
@micgro42, what was the reason for that change? Was it actually breaking anything?

**Comment by selfthinker** [comment]
Fixed by #1309
