### ISSUE TITLE
Full disk may cause complete user database lost

### ISSUE THREAD

**Issue by cfsmp3** [splitbrain/dokuwiki#1303]
Because the users.auth.php is overwritten each time there's a change if this happens with a completely full disk the file is replaced with a zero-byte file effectively losing all users including admin.

Correct solution is create a new file then delete the old one and finally rename.

I just lost my user DB...

**Comment by selfthinker** [comment]
Which version of DokuWiki were you using?
If I understand it correctly, I think this will have been fixed by #1176 (so, since Detritus).
