### ISSUE TITLE
Hide namespace from unauthenticated users in sitemap.

### ISSUE THREAD

**Issue by blubberdiblub** [splitbrain/dokuwiki#1307]
Our company wiki is set up to be accessible only for subscribed users. Still, if you use the sitemap URI, you can see all the namespaces (which might convey information we don't want to disclose), even if you don't have access to them or if you're not logged in at all.

Note that I'm not talking about the articles themselves (they are already hidden), just about namespaces and subnamespaces.

@ALL has permission `None` on `*`

**Comment by splitbrain** [comment]
see http://doku.wiki/sneakyindex
