### ISSUE TITLE
Doku cookies can trigger XSS filter

### ISSUE THREAD

**Issue by zioth** [splitbrain/dokuwiki#1310]
A few times since I upgraded to the Detritus build of DokuWiki, my web host has blocked my attempt to save a wiki page, and then locked me out of my account. This happened because the save was being detected as an XSS attack. It happened both in a page that used the Doku <html> tag and a page that didn't. Here's the log from the web host:

```log
2015-08-17 12:42:52 zioth.com 192.170.136.184 CRITICAL 302 
Request:
GET /
Action Description:
Access denied with redirection to http://zioth.com/ using status 302 (phase 2).
Justification:
Pattern match "(?i)([\\s\"'`;\\/0-9\\=\\x0B\\x09\\x0C\\x3B\\x2C\\x28\\x3B]+on\\w+[\\s\\x0B\\x09\\x0C\\x3B\\x2C\\x28\\x3B]*?=)" at REQUEST_COOKIES:DW68700bfd16c2027de7de74a5a8202a6f.

This is the rule (ID 973337):

Status Staging Vendor ID Message
Enabled Published OWASP 973337 XSS Filter - Category 2: Event Handler Vector
#
# -=[ XSS Filters - Category 2 ]=-
# XSS vectors making use of event handlers like onerror, onload etc, e.g., <;body onload="alert(1)">;
#
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "(?i)([\s\"'`;\/0-9\=\x0B\x09\x0C\x3B\x2C\x28\x3B]+on\w+[\s\x0B\x09\x0C\x3B\x2C\x28\x3B]*?=)" "msg:'XSS Filter - Category 2: Event Handler Vector', id:'973337', phase:request, severity:'CRITICAL', rev:'2', ver:'OWASP_CRS/3.0.0', maturity:'4', accuracy:'8', t:none,t:removeNulls,t:utf8toUnicode,t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode, block, ctl:auditLogParts=+E, capture, tag:'OWASP_CRS/WEB_ATTACK/XSS', tag:'WASCTC/WASC-8', tag:'WASCTC/WASC-22', tag:'OWASP_TOP_10/A3', tag:'OWASP_AppSensor/IE1', tag:'CAPEC-242', logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}', setvar:'tx.msg=%{rule.msg}', setvar:tx.xss_score=+%{tx.critical_anomaly_score}, setvar:tx.anomaly_score=+%{tx.critical_anomaly_score}, setvar:tx.%{rule.id}-OWASP_CRS/WEB_ATTACK/XSS-%{matched_var_name}=%{tx.0}"
```

**Comment by Klap-in** [comment]
Do you use a plain installation?
Which plugins do you use?

Please explain more (setup,configuration,examples,...) , so that others could try to reproduce your situation.

**Comment by Chris--S** [comment]
Is this in anyway similar to the problems that can be caused by the Chrome XSS auditor (see https://github.com/splitbrain/dokuwiki/issues/1182)?

**Comment by selfthinker** [comment]
Can someone please translate that pattern match to us ordinary folk?

**Comment by zioth** [comment]
I'm not sure what cause the cookie to have that text in it. I saved the same page several times with only small edits, and one time, it hit the error.

I'm running a lot of plugins: acl, authplain, confmanager, fastwiki, indexmenu, menu, plugin, sqlite, tag, wrap, authad, bureaucracy, data, hidden, info, nssearch, poem, revert, statistics, testing, zioth, addnewpage, authldap, captcha, datatemplate, hiddenheader, orphanswanted, popularity, roleplay, styling, toucher, authmysql, cleanup, include, loadskin, pagelist, quickstats, safefnrecode, upgrade, anchor, authpgsql, config, extension, maintenence, pagequery, redirect, searchindex, usermanager

roleplay and zioth are custom plugins for my site (I may publish roleplay some day). I'm actively working on fastwiki and roleplay. Everything else was the same before I upgraded to Detritus, except for a couple upgrades.

I use httpd urls (no doku.php in the url).

Chris--S: This isn't the same as the Chrome XSS issue, because it's server-side validation done by the web host.

Selfthinker: Here's the break-down of the regular expression:

* Case insensitive search.
* One or more of: whitespace, double/single quotes, semicolon, number, forward slash, equals, tab, page break, comma, or left parenthesis.
* "on" followed by word characters. This matches javascript events (onclick, onload etc).
* Zero or more whitespace characters.
* Equals.

The point is to match things like <body onclick=

Something like the string, " onx=" would have had to appear in the cookie. Is there any way that can happen? The pattern doesn't match anything in my saved wiki page.

**Comment by splitbrain** [comment]
At least one of our cookies contains a base64 encoded string. it is possible that it ends in onx= or similar prefixed by a number. I would say that mod_security rule is too strict. it should at least check that there's anything following the equal sign.

**Comment by zioth** [comment]
It's also poorly written, since it duplicates a lot of the searched-for characters.
