### ISSUE TITLE
Navigation does "auto-scoll"

### ISSUE THREAD

**Issue by Fubber** [splitbrain/dokuwiki#1314]
Hi,

since i updated to Detritus i experienc strange behavior. The wiki is in some kind of auto scrolling mode. 

Before Hrun:
Lets pretend i have a namespace with 26 Items, from A to Z. These Items are too many, so usally when i enter the namespace only A to K are showing. i have to scroll down to see K and following. 
When i searched for P and clicked on the results Page on P, the Wiki opened Page P. Simultaneously the navigation bar (usind dokubook template) was showing the whole namespace, showing A, B, C till K.

After updating to Detritus the wikipage opens P, but it is scrolled so far down in the navigation bar, that the Entry P is seen. In other words, i have to scroll way up to see the beginning of the page P.

Too make it short. Since the update the wiki scrolls automatically the page till you can see the page you are looking at also on the left menu in the navigation bar. If you have a lot of entrys in every namespace (as i do) you always have to scroll up.

Is this a bug or a feature? Is this Dokuwiki, Tempalte Dokubook or perhaps even Firefox (40.0.2) related?

**Comment by Klap-in** [comment]
Which plugin are you using? the indexmenu?

Related issue: https://github.com/samuelet/indexmenu/issues/129

Autoscrolling is feature of DokuWiki's Sitemap, see https://github.com/splitbrain/dokuwiki/commit/f7dbf17
However the index-list is reused at other places as well, where this feature caused strange behaviour.

**Comment by Fubber** [comment]
Plugin indexmenu is installed, but deactivated. I followed your answer, and i guess it is this problem:

https://github.com/splitbrain/dokuwiki/commit/f7dbf17

![screenshot 339 erweiterungen verwalten rathaus intranet - mozilla firefox](https://cloud.githubusercontent.com/assets/13887813/9387795/80723e0c-4762-11e5-9629-ecf0c567bc3e.png)
