### ISSUE TITLE
Remove support for 'disabled' files in plugins

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki#1323]
The current mechanism is that the disabled plugins are stored in `conf/plugins.local.php`  
At the moment the `lib/plugins/[plugin]/disabled` files are deprecated since 2011, but still available.

https://github.com/splitbrain/dokuwiki/blob/master/inc/plugincontroller.class.php#L166

**Comment by Klap-in** [comment]
The condition `|| ($plugin === 'plugin' && isset($conf['pluginmanager']) && !$conf['pluginmanager'])` remains from the previous plugin manager.
I will remove it as well.
more background: https://github.com/splitbrain/dokuwiki/commit/c45608df2e8efbaeb1b4c29d87b976c0e6366ad1

Question: 
```php
               if (substr($plugin,-9) == '.disabled') {
                    // the plugin was disabled by rc2009-01-26
                    // disabling mechanism was changed back very soon again
                    // to keep everything simple we just skip the plugin completely
                    continue;
                } else
```
Is it ok for you, to remove this `<pluginfoldername>.disable` feature too?

**Comment by splitbrain** [comment]
Yes, that should go too.
