### ISSUE TITLE
JSINFO not set in media manager

### ISSUE THREAD

**Issue by gamma** [splitbrain/dokuwiki#1327]
The media manger used to have the JSINFO populated but with the commit below it only has the id and namespace set. This leads to JS errors at least with the folded plugin.

https://github.com/splitbrain/dokuwiki/commit/d1e37fb0c8f6a5f768bd6cacfcce6c338b4c3831#commitcomment-12850848

**Comment by Klap-in** [comment]
This is correct. There in the code only the basic information is added to the $JSINFO array.

Often JSINFO in javascript is only used on normal pages, which are accessed via `doku.php`. There  the event DOKUWIKI_STARTED is also triggered.
If you visit the pop-up mediamanager, you don't go through `doku.php` but through `lib/exe/mediamanager.php`. Now DOKUWIKI_STARTED is not triggered any more, but you have instead the event MEDIAMANAGER_STARTED (and for detail page respectively DETAIL_STARTED).

For population of JSINFO in the mediamanager you have to register the  MEDIAMANAGER_STARTED event e.g.:
`$controller->register_hook('MEDIAMANAGER_STARTED', 'AFTER',  $this, '_yourJSINFOfillmethod');`

I have updated the documentation about JSINFO as well: https://www.dokuwiki.org/devel:javascript#jsinfo
