### ISSUE TITLE
Wiki Upgrade hangs

### ISSUE THREAD

**Issue by kklepper** [splitbrain/dokuwiki#1332]
Last time,the upgrade (Demetrius) was quite a drag, I had to manually interfere and managed to do it somehow. Today I expected the source of the problems to be solved, but again I was disappointed.

The last screen shows

    Checking file permissions...
    /doku.php will be updated.
    /inc/Form/ButtonElement.php will be updated.
    /inc/Form/Form.php will be updated.
    /inc/Form/InputElement.php will be updated.
    /inc/Form/LabelElement.php will be updated.
    /inc/html.php will be updated.
    /inc/lang/cs/lang.php will be updated.
    /inc/lang/hu/admin.txt will be updated.
    /inc/lang/hu/lang.php will be updated.

and that's it: no buttons to proceed.

After refresh, this list gets longer. After at least half a dozen refreshs, I can proceed. And yes, I updated the update manager plugin first.

**Comment by splitbrain** [comment]
should be reported in the upgrade plugin's issue tracker (be sure to provide more info - see doku.wiki/bugs)

**Comment by Klap-in** [comment]
See: https://github.com/splitbrain/dokuwiki-plugin-upgrade/issues
