### ISSUE TITLE
Detritus: "Fatal error: Invalid opcode 153/1/8..." with eAccelerator

### ISSUE THREAD

**Issue by rikblok** [splitbrain/dokuwiki#1336]
It looks like DokuWiki Detritus is incompatible with eAccelerator in some configurations.

DokuWiki version:
  - Detritus (2015-08-10a)

Operating system of the server:
  - FreeBSD 10.2-RELEASE-p2

The used web server: 
  - Apache

The used PHP version:
   - PHP Version 5.3.29

Exact steps to reproduce the problem:
  1) Upgraded from Hrun to Detritus.
  2) Pages containing [[wp>...]] interwiki links showed as blank (only header and sidebar displayed, no body or footer).
  3) Added the following to .htaccess:
```
php_value display_errors 1
php_value display_startup_errors 1
```
  4) Page loaded with error:

> Fatal error: Invalid opcode 153/1/8. in /.../inc/parser/renderer.php on line 826 

  5) Host administrator disabled eAccelerator functionality.
  6) Page loaded normally, no issues.

It looks like Detritus doesn't work well with eAccelerator.  It might be related to PHP 5 closures (https://github.com/eaccelerator/eaccelerator/issues/12).  I recommend adding a warning to https://www.dokuwiki.org/changes

**Comment by Klap-in** [comment]
Recent changes in the interwiki source code, where a closure is introduced.
See https://github.com/splitbrain/dokuwiki/pull/1247/files

**Comment by rikblok** [comment]
Thanks for the explanation, Klap-in.  Should there be a warning in the changelog (https://www.dokuwiki.org/changes) or somewhere to check if eAccelerator is installed before upgrading to Detritus?  Let me know if I can add it myself.

**Comment by splitbrain** [comment]
TBH this seems to be a bug in eAccelerator. I'm not sure if it is common enough to warrant an extra mention in the changelog.
