### ISSUE TITLE
Feature Request: Parent Namespace replacement pattern

### ISSUE THREAD

**Issue by bailantilles** [splitbrain/dokuwiki#1337]
It would be nice if a replacement pattern existed for namespace templates to reference just the parent namespace instead of the full namespace.

Example:

ns1:ns2:page

`@NS@` returns `ns1:ns2`, it would be useful if there was a replacement pattern that would just return `ns2`.

**Comment by mazamachi** [comment]
This is my first comment to dokuwiki.

I think getting parent namespace can be done with `curNS($id)` method in inc/pageutils.php .
And adding `'@CURNS@'` in `parsePageTemplate(&$data)` function in inc/common.php can perform this replacement.

Is it ok if I implement these features and send a pull request?
I worry about the problem in this implementation that existing page including `'@CURNS@'` string may be influenced.

I have few experience in contributing to OSS, so I'm glad if somebody gives me an advice!

**Comment by splitbrain** [comment]
@mazamachi a pull request is always welcome
