### ISSUE TITLE
Feature Request: When uploading an media file and the media file's name already exists, automatically change the name to name (2).extension or so

### ISSUE THREAD

**Issue by raon0211** [splitbrain/dokuwiki#1338]
When editing the documents with an iPad and when I have an image to upload, I have no option but to upload it with a Safari's native uploader.

but Safari's native uploader automatically fixes the image's name to image.jpg, so I can't upload the image since the dokuwiki uploader doesn't allow uploading files that have an existing name.

So please make a feature that automatically changes the media file's name when it collapses with another.

Thanks very much.

**Comment by Klap-in** [comment]
Sofar I know you get a textfield with the name of the file you selected. You could edit the name in that text field according to your preferences. And after submitting that name should be used.

**Comment by selfthinker** [comment]
> the dokuwiki uploader doesn't allow uploading files that have an existing name

That's not true. You can tick the box that says "Overwrite existing files".
