### ISSUE TITLE
rename a user should also rename meta data

### ISSUE THREAD

**Issue by LMS235** [splitbrain/dokuwiki#1355]
when I change a username (for example "1 letter first name + surname" to "surname + 1 letter first name"), the metadata is not adjusted. When i change the user name, the metadata should be changed too.

**Comment by LMS235** [comment]
see https://github.com/ConX/dokuwiki-plugin-authorstats/issues/29

**Comment by splitbrain** [comment]
This would require scanning through and rewriting all metadata and changelogs. Time consuming and error prone. Not worth it in my opionion.

**Comment by LMS235** [comment]
it is not a simple search and replace over the files (in the meta folder)? 

lika a sed in linux?
#!/bin/bash
      for files in *.*; do
      mv $files $files.tmp
      sed 's/oldname/newname/g' $files.tmp > $files
      rm -f $files.tmp
      done

**Comment by splitbrain** [comment]
No. A user's name might occur in some metadata that is not actually user related at all. Each file would need to be read in, properly parsed and updated and be rewritten. With a huge wiki this could also hit the default time limit of 30 seconds, so you'd need to work around this as well.

**Comment by phy25** [comment]
If we are using username as a "primary key", it will be hard to change it.

Maybe we can place a warning on the username change (in usermanager) and use a shell script to update it (so that it won't time out).

**Comment by splitbrain** [comment]
I'm closing this as won't do. It would be possible to implement this in a plugin if anyone thinks this is important.
