### ISSUE TITLE
Enhance the row_counter

### ISSUE THREAD

**Issue by sunghlin** [splitbrain/dokuwiki#1360]
I think the table render should check the value of row_counter before it increases the value. Currently, I experienced a issue of using the plugin "Dir Plugin". It re-writes its table_open(), but forgets to initial row_counter to zero in general cases. So, the class of the first row is just row, which has a conflict with the bootstrap theme. I tried to initialize the value in its code, but apparently not work (it just died). So, will it be good to check the initialization of row_counter before increasing it? I think this will be more general.

In dokuwiki/inc/parser/xhtml.php

from

```
function tablerow_open() {
        // initialize the cell counter used for classes
        $this->_counter['cell_counter'] = 0;                                                                                                                                                          
        $class                          = 'row'.$this->_counter['row_counter']++;
        $this->doc .= DOKU_TAB.'<tr class="'.$class.'">'.DOKU_LF.DOKU_TAB.DOKU_TAB;
}
```

to

```
function tablerow_open() {
        // initialize the cell counter used for classes
        $this->_counter['cell_counter'] = 0;
        if (!isset($this->_counter['row_counter'])) {
            $this->_counter['row_counter'] = 0;
        }
        $class                          = 'row'.$this->_counter['row_counter']++;
        $this->doc .= DOKU_TAB.'<tr class="'.$class.'">'.DOKU_LF.DOKU_TAB.DOKU_TAB;
}
```

**Comment by Klap-in** [comment]
The Dir Plugin replaces the original `table_open()` function for adding the class to the opening tag, and therefore meets this issue

PR #1558 has added this feature to DokuWiki's renderer. So Dir Plugin can use now the tabel_open() function again e.g. see https://github.com/lupo49/dokuwiki-plugin-dir/pull/26 .
