### ISSUE TITLE
simplify getting heading anchor links

### ISSUE THREAD

**Issue by glensc** [splitbrain/dokuwiki#1363]
currently to get heading anchor link, i have to scroll up to the page, find  the toc (which may be even disabled, or even invisible due too few headings), and click the link

but it could be much simplier, like in [github](https://github.com/github/gitignore/#folder-structure) itself:

![ss1](https://cloud.githubusercontent.com/assets/199095/10039941/940ca0b4-61df-11e5-98c6-d1db69bee746.png)

hover over the heading, and little icon appears before the heading, which is clickable link. you can click or copy url from it. voila, very simple.

some other places put the paragraph symbol after the title: [trac](http://trac.edgewall.org/#AboutThisSite):

![ss2](https://cloud.githubusercontent.com/assets/199095/10039947/9e05b9b6-61df-11e5-8c3a-15aed43755f9.png)

but does not really matter which symbol or where it is :)

**Comment by polyzen** [comment]
https://github.com/Dric/Doku-Titles-Anchors

**Comment by sascha-tasche** [comment]
@polyzen link doesn't work.

**Comment by polyzen** [comment]
https://www.dokuwiki.org/plugin:titlesanchorlink
https://github.com/Dric/dokuwiki-titlesanchorlink

**Comment by glensc** [comment]
imho this should be in base template. but ok will install plugin for now

**Comment by polyzen** [comment]
@glensc, this works great: https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/113

**Comment by molefunk** [comment]
The ComboStrap theme, available at https://combostrap.com, will let you do this. :)
