### ISSUE TITLE
Cannot log in dokuwiki. Automatically redirects to homepage.

### ISSUE THREAD

**Issue by MikeGao-2000** [splitbrain/dokuwiki#1366]
Latest stable of dokuwiki. ACL enabled. Cannot log in.
Nginx/1.9.0
PHP/5.6.9 with Zend Opcache

**Comment by splitbrain** [comment]
please see doku.wiki/bugs on how to do a sensible bug report

**Comment by MikeGao-2000** [comment]
DokuWiki 2015-08-10a "Detritus"
CentOS 7.0 i586
Nginx/1.9.0
PHP/5.6.9
Browser: Tried Safari/IE/EDGE/Chrome/Firefox
Regular setup, removed a template before the problem occurs.
Problem: Cannot login. Every time enter login credentials it redirects to the home page.
Rewrite rules:
server
    {
        listen 80;
        #listen [::]:80;
        server_name xxx;

        client_max_body_size 40M;
        client_body_buffer_size 128k;

        index doku.php;
        root  /home/wwwroot/xxx/xxx;
        
        include none.conf;
        location ~ [^/]\.php(/|$)
        {
            # comment try_files $uri =404; to enable pathinfo
            try_files $uri =404;
            fastcgi_pass  unix:/tmp/php-cgi.sock;
            fastcgi_index index.php;
            include fastcgi.conf;
            #include pathinfo.conf;
        }

        location / { try_files $uri $uri/ @dokuwiki; }
        location @dokuwiki {
        rewrite ^/_media/(.*) /lib/exe/fetch.php?media=$1 last;
        rewrite ^/_detail/(.*) /lib/exe/detail.php?media=$1 last;
        rewrite ^/_export/([^/]+)/(.*) /doku.php?do=export_$1&id=$2 last;
        rewrite ^/(?!lib/)(.*) /doku.php?id=$1&$args last;
        }

        location ~ \.php$ {
        if (!-f $request_filename) { return 404; }
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param REDIRECT_STATUS 200;
        fastcgi_pass 127.0.0.1:9000;
        }
        access_log off;
    }

**Comment by MikeGao-2000** [comment]
No php error detected.
