### ISSUE TITLE
error in sortable prevents the creation of the TOC

### ISSUE THREAD

**Issue by LMS235** [splitbrain/dokuwiki#1368]
is the errro described in https://github.com/oiv/sortablejs/issues/9 located in dokuwiki or only a problem with sortable?

TOC created correctly
<code>
===== HEADER =====

text
</code>

TOC not created correctly
<code>
===== HEADER =====

\<sortable 1\>
\</sortable\>
text
</code>

**Comment by Chris--S** [comment]
Only in sortable.

**Comment by LarsGit223** [comment]
Isn't that a dokuwiki problem?

I uninstalled the plugins bureaucracy, pagemod, searchtablejs and sortablejs and only tried the following wiki code:
```
===== HEADER =====

text

NOT OK
===== HEADER =====

text
```
I don't see ANY toc, just empty. I'm using Detritus and the standard dokuwiki template. There is no plugin syntax tag included so in my opinion it can't be a plugin problem.

For example, this works correctly:
```
====== HEADER ======

===== HEADER =====

text

NOT OK
===== HEADER =====

text
```
I assume a problem in the toc code, not in a plugin. If you think I oversee something, please explain.
Thanks.

**Comment by LarsGit223** [comment]
Ok, completely forgot about the minimum three headers for the toc. Sorry, I will have a second look.
