### ISSUE TITLE
Errormessages while creating a user could be clearer.

### ISSUE THREAD

**Issue by DjSlash** [splitbrain/dokuwiki#1371]
I've been busy all day figuring out why I could not create a new user. Hours trying adjusting settings, updating and file permissions tweaking and nothing helped. All I got was "User addition failed". Well thanks, that isn't very helpfull. 

Then it struck me. I was trying to add a user without a name. Looking in the code all checks on the fields return the above mentioned error message. From a UX standpoint, not really convenient.

**Comment by Klap-in** [comment]
See also https://github.com/splitbrain/dokuwiki/issues/1172

**Comment by DjSlash** [comment]
Ah, i tried looking for a similar issue, apparantly missed that one. Thanks! Closing this one.
