### ISSUE TITLE
Good old dw_qsearch problem

### ISSUE THREAD

**Issue by Grahack** [splitbrain/dokuwiki#1374]
Hi,
My wiki logs this in the console:
`TypeError: jQuery(...).dw_qsearch is not a function`
It's up-to-date.
I found this little thread: <http://www.freelists.org/post/dokuwiki-teams/JavaScript-broken-on-dokuwikiorg,1>
Is it possible to know what the fix was?
Thanks.

**Comment by Chris--S** [comment]
I had a similar problem when updating a recent wiki.  It was due to the 'compatility' plugin.  That plugin was using dw_qsearch as the new/compatible function in place of an older js search function.  dw_wsearch itself is now deprecated hence the error.  Since my use of the compatibility plugin did not require that function, I simply commented out the lines involved.

**Comment by Grahack** [comment]
OK, I figured it out. The problem is that I was including another version of jQuery in a custom meta.html file. So any addition to jQuery was deleted when reading the `jquery.js` file again.

Thanks for the help. I typed an answer that is no longer relevant, but I'd like to leave it below. Cheers.

---

Chris said:
> I had a similar problem when updating a recent wiki. It was due to the 'compatility' plugin.

OK, in `lib/scripts/compatibility.js` I guess? I found nothing related to `dw_search` here.

> That plugin was using dw_qsearch as the new/compatible function in place of an older js search function.

Indeed, I can find some references to `dw_search` in older versions of this file, but not in my up-to-date version.

> dw_[q]search itself …is now deprecated hence the error. Since my use of the compatibility plugin did not require that function, I simply commented out the lines involved.

Could you please precise which lines ?

My attempt: I tried to remove the only file with `dw_qsearch` references (`lib/scripts/qsearch.js`). The error is gone, but I now have another one :

     TypeError: jQuery(...).effect is not a function

Since `effect` was not defined in `qsearch.js`, I guess that the first error just hid the second one. But the errors keep on cascading if I try to avoid them (after `effect`, it's `dw_toggle`). There must be something broken in my installation but I don't know what… Like some of the JS from Dokuwiki not read…

OK, I figured it out. See at the top of the comment.
