### ISSUE TITLE
auth_createToken() and $_SESSION[DOKU_COOKIE]['auth']['token'] never used

### ISSUE THREAD

**Issue by furun** [splitbrain/dokuwiki#1376]
I am not sure about this.

Seems like the auth_createToken() function and the $_SESSION[DOKU_COOKIE]['auth']['token'] mechanism is never used?

This are the Data which seems to be isolated:

auth_createToken()
auth_validateToken()

$_SESSION[DOKU_COOKIE]['auth']['token']
$INPUT->str('authtok')

**Comment by splitbrain** [comment]
true. this was introduced for the flash uploader. when we removed the flash again, we did not remove this. I guess we should.

**Comment by furun** [comment]
ok, then it is not so bad.
it looked like a not implemented (forgotten) CSRF security check.
