### ISSUE TITLE
 Unable to install plugins due to undocumented requirement

### ISSUE THREAD

**Issue by NigelGreenway** [splitbrain/dokuwiki#1382]
Server setup:
- Hiawatha | v9.12
- PHP | v5.6.14
- PHP-FPM | v5.6.14

I try to install any plugin and get a page with `server error`. Diving into the code I have had to make amendments to core code to enable `error_reporting` as the codebase overrides the setting in the ini file. After refreshing, I find that it displays a blank page. Further diving into the issue, I find that a hell of a lot of functions are suppressed with `@`. So, I have to install the pecl scream extension and found the issue was related to having installed php without the `--with-zlib` flag.

Would it be possible to list the minimum requirements or a basic `./configure` string and remove all of the error suppressions?

**Comment by michitux** [comment]
I think particularly annoying is the error-suppression in the auto-loader. If any plugin produces a fatal error (which is not unlikely), the auto-loader suppresses that error and DokuWiki fails silently. I had that problem now several times due to server migrations which broke some plugin. I think we definitely shouldn't suppress errors for plugins we are loading.

**Comment by splitbrain** [comment]
Hmm, I don't see where the autoloader supresses errors?

**Comment by NigelGreenway** [comment]
@splitbrain In [here](https://github.com/splitbrain/dokuwiki/blob/master/inc/init.php#L34), the `error_reporting` is overridden, and these are just a short list of where error suppression is used:

- https://github.com/splitbrain/dokuwiki/blob/master/inc/io.php#L39
- https://github.com/splitbrain/dokuwiki/blob/master/inc/io.php#L395
- https://github.com/splitbrain/dokuwiki/blob/master/inc/io.php#L401
- https://github.com/splitbrain/dokuwiki/blob/master/inc/io.php#L423
- https://github.com/splitbrain/dokuwiki/blob/master/inc/io.php#L452
- https://github.com/splitbrain/dokuwiki/blob/master/inc/io.php#L478

**Comment by splitbrain** [comment]
@NigelGreenway I was asking about including plugins. missing zlib is handled in #1410

**Comment by NigelGreenway** [comment]
Sorry, misread the question. cc/ @michitux

**Comment by michitux** [comment]
Oh, okay, I was looking at some old versions that we still had (I've updated them in the meantime), in the auto loader this has already been fixed, sorry for the noise.
