### ISSUE TITLE
Protocol support

### ISSUE THREAD

**Issue by bitnapper** [splitbrain/dokuwiki#1394]
Sadly dokuwiki ignores all protocols instead of http: and mailto:. It interpretes sip: and xmpp: du to the  address format as email address and makes it a link like mailto:xmpp:x@y.com and it ignores other protocols.
Dokuwiki is a great project and it would be even more great if it would handle protocols accordingly.

**Comment by Klap-in** [comment]
You mean this configuration possibility? https://www.dokuwiki.org/urlschemes

**Comment by bitnapper** [comment]
Oh, yes. That works. It doesn't work for xmpp though but that could be a browser problem.
