### ISSUE TITLE
"user: %USER% 1" from ACL docs not working

### ISSUE THREAD

**Issue by polyzen** [splitbrain/dokuwiki#1406]
From https://www.dokuwiki.org/acl#user_wildcards: 

```
# Allow to browse own namespace via the index
user:                  %USER%  AUTH_READ
```

The equivalent for group: also doesn't work.

Relevant ACLs:

```
* @user 8
* @ALL  1
group:  %GROUP% 1
group:%GROUP%:* %GROUP% 16
group:* @ALL  0
group:start %GROUP% 1
user: %USER%  1
user:%USER%:* %USER%  16
user:*  @ALL  0
user:start  %USER%  1
```

**Comment by Klap-in** [comment]
In the unittests the replacements are checked.
https://github.com/splitbrain/dokuwiki/blob/master/_test/tests/inc/auth_loadacl.test.php
https://github.com/splitbrain/dokuwiki/blob/master/_test/tests/inc/auth_aclcheck.test.php
And we don't see failing tests for them.

But I see only tests for `group:*  ...` like rules, and not for `group:    ...`. (so without `*`).
- General question: is there technical speaking a difference?

Could you add `?do=check` (or `&do=check`) to the url and check if you see the user and groups you expect?

To be sure, your report is about that these rules "don't work"?
`user: %USER%  1`
`group:  %GROUP% 1`

Which urls/pages/views do you visit? And what doesn't work? Are these forbidden? or shown? or ...?
Please explain in bit more detail. Then I could try to reproduce your steps.

**Comment by polyzen** [comment]
Thank you for responding.

> And we don't see failing tests for them.

The replacements are apparently working with the other rules.

> General question: is there technical speaking a difference?

Based on https://www.dokuwiki.org/acl#user_wildcards:
`ns:` browse subnamespaces via the index
`ns:*` access to subnamespaces (include view namespaces via the index)

> To be sure, your report is about that these rules "don't work"?
> Please explain in bit more detail.

Users cannot see user: and group: in the sitemap, and (apparently) consequently nspages.

Users can still access their start pages, group namespaces, and so on. Not sure if ?do=check is useful here, but it gave me "Permission denied" on user:start.

**Comment by Klap-in** [comment]
I will create some unit tests, let's see what that brings...
