### ISSUE TITLE
Pages have index info removed after viewing

### ISSUE THREAD

**Issue by tpazdera** [splitbrain/dokuwiki#1421]
Summary
Viewing a page has removed its ability to be found by keyword search. It is like the indexes are being cleared and never re-indexed.

Test case:
- I can search for a keyword, like 'coupon'
- Click on one of the pages that appear to view the page
- Click the browser <back> button
- Verify the page I just visited is no longer there.

My Environment
- Redhat 6.6
- PHP 5.3.3
- Apache 2.2.15
- Dokuwiki Release 2015-08-10a "Detritus"

What I have done:
- Verified that this behavior is browser independent - IE and Chrome.  There is also no adblocker software.
- Removed extra plug-ins and templates.  This behavior happens with both dokuwiki and bootstrap3 templates
- Verified file permissions don't _seem_ to be an issue.  All files are owned by Apache as 644.
- Downloaded a fresh copy and diffed for differences.  They were all accounted for (settings, missing files, etc.)
- Read through https://www.dokuwiki.org/faq:searchindex
     verified that /lib/exe/indexer.php?id=page created the 1x1 image (as verified in Chrome dev tools).  No new index was generated though.  Search still did not work.
     
Debug results:
runIndexer(): started
Indexer: <<namespace:namespace:namespace:page>> does not exist, ignoring
runSitemapper(): started
runSitemapper(): finished
sendDigest(): started
sendDigest(): sent 0 mails
sendDigest(): finished
runTrimRecentChanges(): started
runTrimRecentChanges(): finished
runTrimRecentChanges(1): started
runTrimRecentChanges(1): finished

Proof (search for coupon)
- Before going to the page in question
     verify that the dokuwiki/data/meta/page.indexed file existed
     verify that the dokuwiki/data/index/w6.idx, dokuwiki/data/page.idx, dokuwiki/data/index/i6.idx had the expected integrity.
- After going tot the page in question
     verify that the dokuwiki/data/meta/page.indexed file has been removed
     verify that dokuwiki/data/index/i6.idx had the reference for the page/word removed

If I go to all pages for that search term, and the search results come up blank, there is a blank line in the i6.idx file.  w6.idx still contains the term, and page.idx still contains the page.  

I did not look at how the rest of the index files work, but if I do "ls -lrt dokuwiki/data/index" there are many index files changed at the time of the page view.

I have been running the SearchIndex Manager plugin daily to return search to working.

**Comment by michitux** [comment]
What happens is probably that DokuWiki thinks the page has been deleted as it cannot find it and then it removes the page from the index. Do you use any kind of farm setup or custom rewrite rules? My guess would be that something has the effect that when `doku.php` is called, DokuWiki finds the page but not when DokuWiki is called from `lib/exe/indexer.php`. Is the id that is displayed in the debug output you pasted the correct page id?

**Comment by tpazdera** [comment]
No farm set up, no custom rewrite rules.

Yes, the page path displayed by the indexer in debug mode is accurate.

Anything else I can check?
