### ISSUE TITLE
Interaction of 'header' with folded/hidden/outliner containing 'included' text

### ISSUE THREAD

**Issue by bhepple** [splitbrain/dokuwiki#1430]
OK, so this involves 4 plugins and the header macro so not sure where to book this. 

Here's a minimal example of the fault. 'manpage' just contains some text (actually it starts with `<code>` and ends with `</code>` but I don't think that's important).

```
===== header =====
-->Title#
 {{page>manpage}}
<--

++++ Title | 
{{page>manpage}}
++++

<hidden>
 {{page>manpage}}
</hidden>

```

In all these 3 cases, the text is not hidden. 

Take away the header and it works fine - the text is hidden until you click the button. 

Weird.

I'm using Release 2015-08-10a "Detritus"

**Comment by michitux** [comment]
Have you tried using the inline mode of the include plugin as explained in it's [documentation] (https://www.dokuwiki.org/plugin:include#the_include_plugin_breaks_the_wrap_and_folded_and_similar_plugins_when_used_inside_them)?

**Comment by bhepple** [comment]
Oh my goodness me! If only people would read the documentation!

Thanks for that - working brilliantly now.

Sorry for the bandwidth


Cheers


Bob
