### ISSUE TITLE
Post new page

### ISSUE THREAD

**Issue by maequise** [splitbrain/dokuwiki#1437]
When publishing a new page, if we delete the preview in the console dev of chrome (maybe it can be the same on firefox) it makes bug.

When can't publish the new page anymore, doing a redirection to : data;,

**Comment by Klap-in** [comment]
Is this related to issue #1182 ?

**Comment by splitbrain** [comment]
huh? you delete parts of with a development tool and then wonder that it breaks? this report makes no sense

**Comment by dom-mel** [comment]
I'll close this issue due to a lack of information. @maequise if you can provide further information/details to your problem feel free to reopen the issue.
