### ISSUE TITLE
Feature Request: Side-by-Side Live Preview

### ISSUE THREAD

**Issue by Borkason** [splitbrain/dokuwiki#1444]
I think it would be fantastic if Dokuwiki could provide a side-by-side live preview as seen in Ghost Blog.

There is a video showing the editor in action: https://www.youtube.com/watch?v=n1HChHB0kj0

**Comment by splitbrain** [comment]
Since DokuWiki needs to parse and render syntax on the server implementing this is more complicated than with a client-side JavaScript markdown parser. Not impossible though. But this should be implemented in a plugin.

**Comment by q2apro** [comment]
Also voting for this, issue should not be "closed".

With jquery it should be simple to provide. Even if server is needed, an ajax request ~ 3 seconds after the user stopped typing, with a [simple delay function](http://stackoverflow.com/a/1909508/1066234)), is easy. 

See this as an idea of how to implement such a preview: http://slim-wiki.murfman.de/?edit

@Borkason Great point!
