### ISSUE TITLE
Incorrect syntax highlighting for PowerShell strings

### ISSUE THREAD

**Issue by Borkason** [splitbrain/dokuwiki#1445]
I stumbled over PowerShell code, that has incorrect syntax highlighting.

```
<code PowerShell>
$x = @"
"Curiouser and curiouser!" cried Alice (she was so much surprised, 
that for the moment she quite forgot how to speak good English); 
"now I'm opening out like the largest telescope that ever was! 
Good-bye, feet!" 
"@
</code>
```
This is how it looks like:
![geshi](https://cloud.githubusercontent.com/assets/2971735/12093175/9da21a64-b301-11e5-814d-3a26140a4df4.PNG)

There are more code examples here: https://technet.microsoft.com/en-us/library/ee692792.aspx

I also posted this over at https://github.com/GeSHi/geshi-1.0/issues/58 as I am not sure where this belongs to.

**Comment by splitbrain** [comment]
upstream issue.

**Comment by Borkason** [comment]
What does upstream issue mean?

**Comment by polyzen** [comment]
@Borkason, [Upstream](http://catb.org/jargon/html/U/upstream.html) being geshi
