### ISSUE TITLE
authad does not pull user's mail

### ISSUE THREAD

**Issue by mxjeff** [splitbrain/dokuwiki#1450]
I did set `$conf['plugin']['authad']['admin_username']` with an account with sufficient rights to fetch users info. But I don't get user mail address in `?do=profile` page.

Besides I get these messages on login (successful):
```
PHP Warning:  ldap_search(): Search: Operations error in /usr/local/lib/dokuwiki/dokuwiki-2015-08-10a/lib/plugins/authad/adLDAP/classes/adLDAPUsers.php on line 238
PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in /usr/local/lib/dokuwiki/dokuwiki-2015-08-10a/lib/plugins/authad/adLDAP/classes/adLDAPUsers.php on line 239
```
Here is my config:
```php
  // general DokuWiki options
  $conf['title']          = 'Wiki';
  $conf['start']          = 'start';
  $conf['useacl']         = 1;
  $conf['authtype']       = 'authad';
  $conf['license']        = 0;

  $conf['htmlmail']       = 0;
  $conf['rss_type']       = 'atom1';
  $conf['userewrite']     = 1;
  $conf['autopasswd']     = 1;
  $conf['passcrypt']      = 'smd5';
  $conf['remote']         = 0;
  $conf['remoteuser']     = '';
  $conf['savedir']        = '/usr/local/lib/dokuwiki/data';
  $conf['basedir']        = '';
  $conf['useslash']       = 1;

  // configure your Active Directory data here
  $conf['plugin']['authad']['account_suffix']     = '@example.org';
  $conf['plugin']['authad']['base_dn']            = 'DC=org,DC=example,OU="Unit",OU="Dept"';
  $conf['plugin']['authad']['domain_controllers'] = 'srv1.domain.org, srv2.domain.org';
  $conf['plugin']['authad']['recursive_groups']   = 0;
  $conf['plugin']['authad']['use_ssl']            = 0;
  $conf['plugin']['authad']['use_tls']            = 1;
  $conf['plugin']['authad']['additional']         = 'email,mail';
  $conf['plugin']['authad']['admin_username']     = 'super';
  $conf['plugin']['authad']['admin_password']     = 's3cr34';
  $conf['defaultgroup']= 'user';
```

Is there something wrong?

**Comment by splitbrain** [comment]
You don't need to put the mail attribute in the additional config - it will be fetched automatically. It seems something goes wrong within the LDAP communication, though I have no idea what. Googling the error suggests, the search was executed with non-sufficient permissions. Maybe your provided user is missing some permissions?

**Comment by mxjeff** [comment]
Actually the account used does have sufficient rights.
I set the same user account for AD auth in another web application and it fetch users info correctly (in moodle actually).
I'll try to figure out what's going on with dokuwiki and keep you informed of my findings, if any.

**Comment by Klap-in** [comment]
The authad plugin has a debug config setting that could be enabled temporary. Maybe that gives some useful information...
` $conf['plugin']['authad']['debug']              = 1;`

**Comment by mxjeff** [comment]
I already set the debug level for authad plugin.
I only get the PHP Warning mentioned above.
I also tried ``$conf['plugin']['authldap']['debug'] = 1;`` but I still get the same warnings.
