### ISSUE TITLE
Querystring list when forwarding to namespace startpage

### ISSUE THREAD

**Issue by micgro42** [splitbrain/dokuwiki#1454]
If only a namespace is given as location, then Dokuwiki forwards to the correct startpage for that namespace. However the querystring is lost in the process.

Example:
https://www.dokuwiki.org/devel:?foo=bar
should result in 
https://www.dokuwiki.org/devel:start?foo=bar
but actually results in
https://www.dokuwiki.org/devel:start

**Comment by dom-mel** [comment]
What does this break? Or what is it you need this for?

**Comment by micgro42** [comment]
I want to link a the generic namespace startpage of a dokuwiki-installation without knowing its specific configuration (i.e. not knowing what the value of $conf['start'] is) and at the same time intend to trigger a plugin with a url parametere e.g. ``plugin_foo=bar``.

**Comment by splitbrain** [comment]
@micgro42 can you provide a pull request?
