### ISSUE TITLE
Size control buttons are missing in Firefox and MSIE

### ISSUE THREAD

**Issue by slwcz** [splitbrain/dokuwiki#1455]
Hello all,
we are using DokuWiki 2015-08-10a "Detritus". We found out that in Firefox and MSIE, the size control buttons when editing a page are missing. Is it a bug or does anyone experience the same problem?

Chrome (version 48)
![chrome](https://cloud.githubusercontent.com/assets/8083466/12583668/3e35fefc-c444-11e5-94c7-ae780982607b.png)

Firefox (version 43)
![firefox_43](https://cloud.githubusercontent.com/assets/8083466/12583685/4e5c147e-c444-11e5-8411-e155d884d798.png)

Thank you in advance for your replies.

**Comment by splitbrain** [comment]
I can not confirm this. Can you please check for possible errors in the JavaScript console? See alos http://doku.wiki/bugs
