### ISSUE TITLE
abc - plugin: different authors overwriting each other's musical excerpts.

### ISSUE THREAD

**Issue by pav00** [splitbrain/dokuwiki#1459]
DW: Detritus, PHP: 7.0.2, abcm2ps-8.10.1
It is not a software bug as such, rather a design problem leading to the bug.

In the test case when author A working on page A embedding musical excerpt with X:1 and T:Name and author B working on the page B in the same namespace embedding a different musical excerpt with different contents and X:1 and T:name, who saves last overwrites previous authors content.

It is easily possible to have X and T identical for the different musical excerpts with different contents.

The ABC specification is that the X: (reference number) field is used to assign to each tune within a tunebook a unique reference number. 

A T: (title) field must follow immediately after the X: field; it is the human identifier for the tune.

Authors publishing for example orchestral excerpt cannot assign any X, no such X exist (yet it must be present according to specs), at best they can number the number of excerpts on the page  (starting with 1). At the same time different authors can work on the orchestral excerpt from the same piece (with different contents but the same title) on different pages.

abc plugin creates filename of the png file using X and T and that is not enough; the above scenario is easily reproducible, workaround none. Solution would be to add another parameter to the filename such as the name of the page from which the excerpt was created.

A side note: All the excerpts are saved in the namespace defined in mediaNS. In case of big number of excerpts it might lead to problems in the future.

**Comment by splitbrain** [comment]
this should be reported in the ABC plugin's tracker
