### ISSUE TITLE
information leak

### ISSUE THREAD

**Issue by wrohdewald** [splitbrain/dokuwiki#1467]
Using version 2015-08-10a "Detritus"
When nobody is logged in, the sitemap still shows the name space, and the trace shows last visited page names.

I would have hoped that this is confidential data, nobody needs to know how I name my pages.

**Comment by Klap-in** [comment]
I think you mean the behavior that could be dis/enabled with the config option `sneaky_index`
See https://www.dokuwiki.org/config:sneaky_index

**Comment by wrohdewald** [comment]
sneaky_index partially fixes the sitemap part. But this should never break the index view. Instead, if a higher level in the namespace cannot be shown because of missing permissions, show something like "????". With that fix, I guess the user would not need the sneaky_index option any 

more, it could always be "1".

Now about the trace: When logged out, the last visited page is still shown. IMHO that is a bug, I attached a patch.

**Comment by Chris--S** [comment]
I don't think that is the right place to fix the problem.  The trace should be cleared along with the session when a user logs off.

**Comment by splitbrain** [comment]
The breadcrumbs are already cleared from session when the user logs off. But a new breadcrumb is created for the new user starting with the current page.

If you log out on a non-public page, you stay on that page but get a Permission Denied. It's true that this page gets added to the breadcrumb trace. However that page name is also visible in the URL and is also still in the browser history (as are all the other possibly secret pages you visited before). If you want to avoid that, close the browser after logging out.
