### ISSUE TITLE
Editing a past revision in DW Edit mode uses most recent instead of selected revision

### ISSUE THREAD

**Issue by fslone** [splitbrain/dokuwiki#1469]
Found a bug that made editing confusing, since I usually edit a page in DW Edit mode. How I triggered the error:

1.) Visit a page with multiple past revisions
2.) Under the "Old Revisions" link, choose to display a version before the most recent version
3.) Choose "Edit this page" to edit this past version
4.) Note that when the editor loads in GUI mode the past page revision is displayed as expected.
5.) Click "DW Edit" to edit via dokuwiki syntax. Note that now the most recent version of the page is being used for editing, instead of the revision that had been selected.

**Comment by splitbrain** [comment]
This sounds like a bug in some WYSIWYG edito plugin. Please report there.

**Comment by fslone** [comment]
You're right, looks like it's CKG Edit. Didn't realize that was a plugin, thanks for your help.

**Comment by turnermm** [comment]
Not a bug. See: https://github.com/turnermm/ckgedit/issues/134
