### ISSUE TITLE
Importing odt files using the create button

### ISSUE THREAD

**Issue by ennooosterhuis** [splitbrain/dokuwiki#1473]
Hallo,

I use dokuwiki Release 2015-08-10a "Detritus"
with the odt2dw plugin.

When I import an odt file I use the addressbar in the browser as:
https://wiki.secret.org/manuals/playground/aa?do=odt2dw

For other users (students etc) this is not practical. I would like the create button to give the choice between importing an odt file or typing in the
dokuwiki_editor. How can this be achieved? I do not want the edit button to give the choice, the chance to overwrite the original file is too big.

Regards,

Enno Oosterhuis

**Comment by splitbrain** [comment]
This is not a support forum and not the odt2dw bugtracker. please use the proper channels.
