### ISSUE TITLE
Search heading still displayed although search disabled

### ISSUE THREAD

**Issue by ab-tools** [splitbrain/dokuwiki#1477]
I disabled the search by entering "search" in the "disabled actions" box and the search box disappeared correct.

But the `<link rel="search" type="application/opensearchdescription+xml" [...]` line is still included in the document heading which seems like a bug to me.

Or did I miss something?

**Comment by mprins** [comment]
The `tpl_metaheaders` function doesn't check for disabled search, see https://github.com/splitbrain/dokuwiki/blob/master/inc/template.php#L306

It think it should
