### ISSUE TITLE
feed.php error on line 38

### ISSUE THREAD

**Issue by HanFox** [splitbrain/dokuwiki#1480]
When going to the feed.php page (as displayed in the head of the page) I get this error:
`Fatal error: Uncaught Error: Function name must be a string in /server/http/default/wedge/wiki/feed.php:138 Stack trace: #0 /server/http/default/wedge/wiki/feed.php(26): rss_parseOptions() #1 {main} thrown in /server/http/default/wedge/wiki/feed.php on line 138`

When using a RSS viewer the feed is always blank.

No matter what the RSS settings are in the admin panel it doesn't seem to make a difference.

Using _Release 2015-08-10a "Detritus"_ and PHP7.

This happens on 2 separate dokuwikis.

**Comment by Klap-in** [comment]
line 138:
`$opt[$name] = $INPUT->$val[0]($val[1], $val[2], true);`
PHP7 changes the evaluation order
https://secure.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling

solution:
`$opt[$name] = $INPUT->{$val[0]}($val[1], $val[2], true);`

**Comment by HanFox** [comment]
Thanks very much. Works a treat :)

**Comment by splitbrain** [comment]
PR please

**Comment by Klap-in** [comment]
I searched the code for the 4 other changes of evaluation order in PHP7 as well. Nothing found.
