### ISSUE TITLE
.berlin is not recognized as mail

### ISSUE THREAD

**Issue by voxspox** [splitbrain/dokuwiki#1481]
It seems a mail address with a TDL longer than 4 characters is not recognized. The formatting string <user@domain.berlin> is shown (without link) in the rendered output.

**Comment by splitbrain** [comment]
E-Mail Addresses are not recognized as is. They have to be used either in proper link context ```[[user@domain.berlin]]``` or in pointy brackets ```<user@domain.berlin>```. Both forms are recognized just fine in my tests.

**Comment by voxspox** [comment]
ok, the braces in my post have been hidden by github. In 2014-09-29b "Hrun" `<user@domain.berlin>` is not converted. Maybe it was fixed in a later release.
