### ISSUE TITLE
New user passwords are emailed to the new user

### ISSUE THREAD

**Issue by johnhunt** [splitbrain/dokuwiki#1482]
This is incredibly bad practice and insecure. I wanted to use docuwiki but cannot as this is just massively insecure.

http://security.stackexchange.com/questions/17979/is-sending-password-to-user-email-secure

Unfortunately, I don't have time to hack on docuwiki, but I do have time to file this bug in the hope that someone with time will be able to pick it up. Until then I recommend nobody uses docuwiki.

**Comment by splitbrain** [comment]
https://www.dokuwiki.org/config:autopasswd

**Comment by johnhunt** [comment]
This doesn't fix the security issue.
