### ISSUE TITLE
instructions rendered multiple times

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#1484]
When trying to debug a bug in a plugin, I encountered that sometimes instructions are created twice (parser is run twice) after saving a page. Once during the show action in the main process and once again in the indexer process.

From my understanding, the indexer should only be triggered at the very end of the show process (the webbug is very last thing in the template) so the instructions should have been cached already. This does not always happen so it might be some race condition.

For reference I attached the xdebug function traces of the show and indexer run.

[xdebug.zip](https://github.com/splitbrain/dokuwiki/files/149324/xdebug.zip)

**Comment by michitux** [comment]
This is not unlikely if the instructions were created in less than a second as DokuWiki does not use the cache if `$this->_time <= @filemtime($file)` where `$this->_time` is the modification time of the cache and `$file` is some dependency. This means that if the page and the instruction cache are created in the same second, the instruction cache won't be used.

We could change this to `<`, but then we have possibly a problem if the instruction cache expires for some reason (a plugin e.g.) just before the page is saved. Then saving the page first re-creates the instruction cache for metadata rendering and then saves the page, i.e. it is likely that both get the same modification time.

**Comment by splitbrain** [comment]
Ah now that makes sense. I wonder if it would be an idea to have the indexer sleep a second before running to avoid this.

**Comment by splitbrain** [comment]
Ah wait, that makes no sense.

**Comment by splitbrain** [comment]
I'm closing this as I don't see how to fix this easily without possible side effects.
