### ISSUE TITLE
authAD password visible in local conf

### ISSUE THREAD

**Issue by Famok** [splitbrain/dokuwiki#1487]
The admin password for authAD is written as plain text in the local.conf file.
I don't think thats intended?!

**Comment by splitbrain** [comment]
In the end that password will be needed in cleartext anyway.

We do have an obfuscation option for the passwords, but it's not on by default as it needs special handling when used. (Currently we use it for the safemodehack FTP password and the HTTP proxy password only). It makes sense to use it here and in the other auth plugins, too.
