### ISSUE TITLE
implementation of syntax plugin render(...) method may break page display

### ISSUE THREAD

**Issue by flohmueller** [splitbrain/dokuwiki#1490]
Hi there,

I implemented a syntax plugin and everything worked fine..at first.
Then I added a php "exec(..)" call to my render method's "case DOKU_LEXER_ENTER:"-block, it doesn't really matter what..
But that's when dokuwiki started behaving strange. Sometimes the page rendered the template, but without the article's content, sometimes only texts and buttons of the template (the way some pages look like when a .css is missing).
I tried debugging with xdebug, but was quickly at a loss, as everything really seemed to work fine.. the whole page including the text created by my render method even showed up in my eclipse's "debug output". Only the text wouldn't turn up in my browser.. :(

For further testing and confirmation of a 'bug' I simply added a usleep(...); to the standard plugin "info"'s render method.
With small values everything was fine, but when I put in a delay > 1.0 seconds, things got weird again.. the article using a note wouldn't show up.

Can anyone confirm there's problem? Maybe with a higher value for usleep(..)?

**Comment by Klap-in** [comment]
a quote from the docs http://php.net/manual/en/function.exec.php:
```
Note:
If a program is started with this function, in order for it to continue running in the 
background, the output of the program must be redirected to a file or another output 
stream. Failing to do so will cause PHP to hang until the execution of the program ends.
```

the initiated (background) process is not to slow?

**Comment by flohmueller** [comment]
thank you for your answer..

But.. to get rid of any side effects caused by my "exec" call, I replaced it by a simple `usleep(...)`.
My test page contains only three lines:
```
~~NOCACHE~~
~~INFO:syntaxplugins~~
this is a test!
```
The code modification in my "info"-plugin is a simple `usleep(1000000)` at the beginning of the `render`-function in `\lib\plugins\info\syntax.php`

**Comment by splitbrain** [comment]
Where's your code?

**Comment by splitbrain** [comment]
Okay, I still don't fully understand the problem. You get unstyled content when the plugin sleeps for too long?

**Comment by flohmueller** [comment]
I don't get the article's content.
Sometimes I get some styled template-elements, sometimes unstyled template-elements..
When I use my browser to watch the html source code it looks like only half of the page was transferred.. it stops in the middle of a <div-tag or right after an <ul>-tag, but it's never the whole <html>...</html> page.

And yes, this happens when the plugin sleeps too long. 
Is this expected or maybe even intended behaviour?

**Comment by splitbrain** [comment]
No that's not intended behaviour. To me it sounds like your hoster kills processes using too much CPU time. Where are you hosting this?

**Comment by flohmueller** [comment]
The scenario to reproduce was really that simple (at least on my machine):
1. modify `\lib\plugins\info\syntax.php` which comes with the dokuwiki standard installation: put a `usleep(..)` at the beginning of the `render`-function
2. create an article with `~~INFO:syntaxplugins~~` and display it using `'&purge=true'` to prevent caching
3. increase the value used for `usleep(..)` until the described behaviour occurs

**Comment by flohmueller** [comment]
for now it's running on a wamp installation on my machine.

**Comment by flohmueller** [comment]
same stuff runs perfectly when i set the value used for `usleep(..)` below a certain amount...

**Comment by splitbrain** [comment]
Oh of course usleep 100000 is much too high. That's 100 seconds. Default max execution time in PHP is 30 seconds. Go check your error logs. PHP probably just kills the process.

**Comment by flohmueller** [comment]
uhm.. from the docs:
```
// wait for 2 seconds
usleep(2000000);
```

**Comment by flohmueller** [comment]
have you tried to reproduce the behaviour?

**Comment by splitbrain** [comment]
oh.. I was assuming milliseconds. Anyway. I just tried it. Using usleep(5000000); Page loads slow but outputs just fine.

Still. from your error description it sounds like some kind of fatal error. That should be logged somewhere. Find that log.

**Comment by flohmueller** [comment]
hm.. the only logfiles I can find are:
wamp/logs/apache_error.log
wamp/logs/php_error.log

..and there are no corresponding entries to my trying to display the page.

Maybe I should get a fresh wamp installation and try again..!?

**Comment by flohmueller** [comment]
ok, there must be something wrong with my server - i couldn't reproduce the behaviour on another machine.

When I filed this issue all I wanted to know was if it's intended behaviour, but I got carried away, sorry! And sorry for wasting your time...

**Comment by flohmueller** [comment]
WTF!
looks like this is one of those moments...

For everyone who's interested:
Looks like I wasted hours and hours of debugging and testing because of #*~%$* Avira AntiVir's Browser Protection.
When I turned it off, all of a sudden everything worked as expected!

turn it on - ugh!
turn if off - yay!
turn it on - ugh!
turn if off - yay!
turn..... turn turn...
