### ISSUE TITLE
Links break when page gets saved

### ISSUE THREAD

**Issue by jackdistortion** [splitbrain/dokuwiki#1500]
Whenever I try to add the following link to a page, the link gets broken:

[http://www.digikey.ch/product-detail/de/LTC1563-2CGN%23PBF/LTC1563-2CGN%23PBF-ND/890755]

It comes up as

[http://www.digikey.ch/product-detail/de/LTC2312CTS8-12#TRMPBF/LTC2312CTS8-12#TRMPBFCT-ND/4431236]

next time, which is not accepted by the host.

Cheers, André

**Comment by splitbrain** [comment]
Works fine for me: https://www.dokuwiki.org/playground:urlencode

I'm assuming you're using some kind of WYSIWYG editor plugin. You should report it there.
