### ISSUE TITLE
Some search results dont have text sample

### ISSUE THREAD

**Issue by MarcosMenegazzo** [splitbrain/dokuwiki#1505]
I'm prototyping an intranet running over Dokuwiki (Detritus). When testing search, i noticed that some results have only the link to the searched page, the text sample is missing. Please see the red rectangle at the screenshot.

![pesquisar_intranet_20160317_154917](https://cloud.githubusercontent.com/assets/1504086/13857315/25f66368-ec58-11e5-8fbc-827c27103826.png)

I inspected the search results HTML, i noticed something like:

```html
<dt>Link to page</dt>
<dd>Text sample with result highlights</dd>
<dt>Link to page</dt>
<dd>Text sample with result highlights</dd>
<dt>Link to page</dt>
<dd>Text sample with result highlights</dd>
...
<dt>Link to page</dt>
<dt>Link to page</dt>
<dt>Link to page</dt>
```

When i click these links at the bottom, i'm directed to the right pages, and its contents are highlighted correctly too, so my question is why there is no text sample for these pages in search results?

**Comment by splitbrain** [comment]
for performance reasons snippets are only generated for the first 15 results.
