### ISSUE TITLE
Add CSS Class for Wiki Content

### ISSUE THREAD

**Issue by drguildo** [splitbrain/dokuwiki#1508]
Please add a CSS class to distinguish CSS content from other elements such as the admin page.

For example I'd like to have all wiki content rendered using a serif font but I'd like to have the admin page rendered using a sans-serif font and there doesn't seem to be any (simple) way for me to do this.

**Comment by micgro42** [comment]
You can tell normal pages apart from admin pages by a class on ```div#dokuwiki__top```. For normal pages this div has the class ```mode_show``` whereas for admin-pages it has the class ```mode_admin```.

**Comment by drguildo** [comment]
Thanks @micgro42. I managed to achieve what I wanted using the `.mode_show .dw-content` CSS selector.
