### ISSUE TITLE
Allow caching of sidebar with changing curid

### ISSUE THREAD

**Issue by robinro** [splitbrain/dokuwiki#1511]
We use a mostly static set of pages on combination with a sidebar. To get the curid class on the active page in the sidebar, one currently has to disable caching, see also https://bugs.dokuwiki.org/index.php?do=details&task_id=2625

As the discussion in the old bug is quite old: Are there plans how to deal with this? What's the best approach? Should we add some custom javascript to write the curid class afterwards?

**Comment by splitbrain** [comment]
yeah I think a Javascript solution makes sense

**Comment by robinro** [comment]
The jquery solution worked, so we now run without ~~NOCACHE~~

Nevertheless the overall setup uses caching, due to phps `session.cache-limiter = nocache`. I tried to enable caching (setting to private), but that also cached internal pages when I logged out. Is there another solution for caching full pages in the browser?

**Comment by robinro** [comment]
There is a snippet at https://www.dokuwiki.org/plugin:smartcache
```
if(!isset( $_SERVER['REMOTE_USER'])){
header('Cache-Control: public, max-age='.max($conf['cachetime'], 2000000));                          
header('Pragma: cache'); }
```
This sounds feasible.

**Comment by splitbrain** [comment]
Got a PR for the curid thingy?

Please do not discuss multiple issues in one ticket.

**Comment by robinro** [comment]
The implementation is in a custom theme based on dokucms. It's not using the `span` with `curid` but modifies the `li` around it.
We plan to publish the theme once it's cleaned up a bit more. Maybe I backport it to the default theme some time. There is also the indexmenu plugin, so the use case might be rather limited.

Regarding the caching I'll open a separate issue once I looked into it in more detail. The page is currently fast enough so it might take some time to find the necessity to do so.

**Comment by robinro** [comment]
The javascript solution is at https://github.com/particleKIT/dokuKIT/blob/master/script.js
It is a bit of a hack and not fully cleaned up, but the idea works well for our usecase.
