### ISSUE TITLE
ajax.php permissions rewritten

### ISSUE THREAD

**Issue by cpedraza-ca** [splitbrain/dokuwiki#1512]
Something is rewriting the permissions for DokuWiki's ajax.php file to 0000.

When that happens all ajax-related function just hang (e.g., autocomplete in the search bar, Link Wizard, file upload, Media Manager edit feature). I have to manually go into doku/lib/exe/ajax.php to change the permissions to allow me to interact with ajax functions on the wiki.

What is causing this? Is some plugin accessing the ajax file and automatically changing the permissions?

I'm running Detritus.

— _Carlos Pedraza_

**Comment by Klap-in** [comment]
Nothing in the wiki should trigger this kind of behaviour.
Do you have logs or does the server admin has logs to reveals details about the changed permissions of this file?

**Comment by cpedraza-ca** [comment]
I'm checking with my web host. Thanks!

/carlos



--

Carlos Pedraza

Writer-Producer [IMDb <http://www.imdb.com/name/nm1408672/>]

Upcoming Feature
*Something Like Summer *[Website <http://somethinglikesummer.com/>][IMDb
<http://www.imdb.com/title/tt2196053/>][Facebook
<http://facebook.com/SomethingLikeSummerMovie>][Twitter
<http://twitter.com/LikeSummerFilm>]

*The Dark Place *[Website <http://thedarkplacemovie.com/>][IMDb
<http://www.imdb.com/title/tt2196059/>][Facebook
<http://facebook.com/thedarkplacemovie>][Twitter
<http://twitter.com/darkplacemovie>][Trailer <http://youtu.be/OOXrDCD0cP4>]

*Judas Kiss *[Website <http://judaskissmovie.com/>][IMDb
<http://imdb.to/jk_imdb>][Facebook <http://facebook.com/judaskissmovie>] [
Twitter <http://twitter.com/JudasKissMovie>][Reviews
<http://judaskissmovie.com/category/reviews>][Press Kit
<http://judaskissmovie.com/media/press-kit>][Trailer
<http://youtu.be/MsGOL5HAeFQ>]
