### ISSUE TITLE
dwpage -t does not work

### ISSUE THREAD

**Issue by glensc** [splitbrain/dokuwiki#1518]
dwpage -t option no longer work:

```
# /usr/share/dokuwiki/bin/dwpage.php -h
...
  OPTIONS

  -m <summary>,       Summary describing the change (required)            
  --message <summary>                                                     

  -t, --trivial       minor change                                        

```

```
+ /usr/share/dokuwiki/bin/dwpage.php checkout start /tmp/tmp.ylcDhxuQEr
+ /usr/share/dokuwiki/bin/dwpage.php -t -m 'test' /tmp/tmp.ylcDhxuQEr commit start
E: No such option -t
```

**Comment by Klap-in** [comment]
It is in the code...
https://github.com/splitbrain/dokuwiki/blob/master/bin/dwpage.php

**Comment by glensc** [comment]
ps: use permalink (sha1 commit), not branch name, so the link would still work if commits added to dwpage!  (replace word `master` with hash, i.e: `dc0b9000`), and you probably wanted to point to some  line number, or lines range? click on the line number on the left it will update url which you can copy paste

**Comment by glensc** [comment]
looks like it works if i move the options after command name. not sure is the breakage intentional

**Comment by splitbrain** [comment]
Yeah, the tool has global options like -f or -u and options that are valid for a certain command only. Command options have to follow the command.
