### ISSUE TITLE
RSS record disappeared fast when page is deleted

### ISSUE THREAD

**Issue by pandamasta** [splitbrain/dokuwiki#1520]
When deletion of a page occurs, it remain recorded few seconds in the RSS feed and disappear
Dokuwiki version: 2015-08-10a

Let me know if you need more details
Thanks

**Comment by splitbrain** [comment]
What are you expecting?

**Comment by pandamasta** [comment]
That the deletion record remain in the feed to inform the user that a deletion event has been triggered.

**Comment by peterstrong123** [comment]
The only limit to our realization of tomorrow will be our doubts of today [url=http://www.192-168-1-1.co]192.168.1.1[/url]
