### ISSUE TITLE
Not able to email while registering users. I have installed Docuwiki in iis 8.5 in windows server 2012 r2.

### ISSUE THREAD

**Issue by anjan-cele** [splitbrain/dokuwiki#1522]
Not able to email while registering users. I have installed Docuwiki in iis 8.5 in windows server 2012 r2.
![mail issue](https://cloud.githubusercontent.com/assets/13432517/14285148/ff6178a4-fb67-11e5-9f57-7a1b69759ff0.PNG)

Whether I need to do some mail configuration?

**Comment by splitbrain** [comment]
Please refer to the PHP documentation on how to configure PHP to be able to use the mail() function on Windows. Or use the sMTP plugin for DokuWiki.

**Comment by anjan-cele** [comment]
Hi splitbrain

I have installed SMTP Plugin , I have filled SMTP details in default.php

What will be the values for :
$conf['auth_user'] 
$conf['auth_pass']

?
