### ISSUE TITLE
Security issue Alert is showing while clicking on Admin hyperlink from Admin Login in Internet Explorer

### ISSUE THREAD

**Issue by anjan-cele** [splitbrain/dokuwiki#1523]
Security issue Alert is showing while clicking on Admin hyperlink from Admin Login in Internet Explorer.
It is telling that Data Directory is not secured but I have correctly gave the permissions in Data Directory.
![security message in dokuwiki](https://cloud.githubusercontent.com/assets/13432517/14285297/8cc36ab8-fb68-11e5-9f7f-b45db813313f.PNG)

**Comment by splitbrain** [comment]
Make sure your browser hasn't cached that image. If the image remains visible, your data directory is not secured. Please refer to https://www.dokuwiki.org/security#web_access_security

**Comment by anjan-cele** [comment]
Hi Splitbrain



After replacing with My server IP, It(http://yourserver.com/data/pages/wiki/dokuwiki.txt.) is not accessible. I have gone thru the link above mentioned by you and did the same.

Cleared the Cache and tested also, Nothing changed.

Any other advise may be helpful. Thanks
