### ISSUE TITLE
One unremovable empty line on top off every dokuwiki page, no disaster but itchy : )

### ISSUE THREAD

**Issue by bolibompa** [splitbrain/dokuwiki#1524]
Hi, 
I have noticed that (on my configuration of dokuwiki) I always get one empty line on top of every wikipage that I create, when using Namespace Templates, wikipages created in namespaces without templates are correctly created. The itchy part of this "feature" is that I haven't found a way to remove the inserted extra empty line : (  Not even by deleting the page and recreating it by the workaround below.
Workaround: If I 1) create a namespace template that have a first line of plain unformated text, 2) create a wikipage with this template, 3) save the page, 4) edit the page and removes the first line of plain text, 5) saves the page again. Then I get a wikipage without a empty line at top of the page.

Anyone else seen this, do you have some suggestions, if so I you deserve to be richly rewarded : )

Example of a page with an un-removable empty line at top of the page 
- "http://omans.se/plats/acklinga_r_sn" (the page is written i Swedish)

using the browser to see the HTML I get, where **<p>?</p>** is the problem (I think)
the question-mark (?) pops up when pasting to this mail form
```
<!--********** CONTENT **********-->
<div id="dokuwiki__content">
  <div class="pad group">
    ::before
    <div class="pageId">
      <span>plats:acklinga_r_sn</span>
    </div>
    <div style="min-height: 771px;" class="page group">
      ::before
      <!-- wikipage start -->
      <p>?</p>
      <h1 class="sectionedit1" id="acklinga_r_sn">Acklinga (R) sn</h1>
      <div class="level1">
        <p>Namnet skrevs 1311 .......
```

**Comment by splitbrain** [comment]
Looking at the source in Chrome shows a &#65279; entity.

Quick googling brought me to this: http://stackoverflow.com/questions/6538203/how-to-avoid-echoing-character-65279-in-php-this-question-also-relates-to-java

See also https://www.dokuwiki.org/utf-8#editing_files

**Comment by bolibompa** [comment]
Thank you,
amasing what one can do when you know how
Hope this answer is the golden key it looks to be : )

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfritt.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

mvh / Björn Öman

2016-04-06 18:00 GMT+02:00 Andreas Gohr <notifications@github.com>:

**Comment by bolibompa** [comment]
Problem solved,
saving the Namespace Template without  UTF8 "BOM" encoding did the trick.

Again, tank you

mvh / Björn Öman

2016-04-06 18:57 GMT+02:00 Björn Öman <bjorn@omans.se>:
