### ISSUE TITLE
code block breaks when include full html page

### ISSUE THREAD

**Issue by radzhome** [splitbrain/dokuwiki#1525]
This seems to break code block

```
<code>
    <html>
    <head>
    <style> p { color: Green; } </style>
    </head>
    <body>
    <p>My Future is so bright</p>
    <div id="foo"></div>
    <script>
        var foo = document.getElementById('foo');
        // WARNING: Pseudocode, not a real API.
        foo.shadow = document.createElement('p');
        foo.shadow.textContent = 'I gotta wear shades';
    </script>
    </body>
    </html>
</code>
```

On release 2015-08-10 "Detritus"

**Comment by splitbrain** [comment]
Seems to work fine: https://www.dokuwiki.org/playground:code

**Comment by LarsGit223** [comment]
I tested it with the current release on my installation, also looks fine.

@radzhome:
Do you still have this issue?
Do you also have it with the current DokuWiki release?
Could this be related to any plugins/which plugins do you have installed?

> This seems to break code block

How does the code block break? What does that mean in detail?

**Comment by phy25** [comment]
I am closing this because of lack of response, but feel free to add more information and I can reopen the issue if necessary.
