### ISSUE TITLE
wikiFN caches filenames w/o considering $clean

### ISSUE THREAD

**Issue by micgro42** [splitbrain/dokuwiki#1536]
The function [```wikiFN``` in inc/pageutils.php](https://github.com/splitbrain/dokuwiki/blob/6834946f90dd76dce275261b44d4018d64622857/inc/pageutils.php#L282) caches the retrieved filenames for further use. However it does so without considering the ```$clean``` flag. Hence one might get a cached filename for an uncleaned id, when actually requesting the filename for a cleaned id and vice versa.

Is this the intended behavior or should I make an PR?

**Comment by splitbrain** [comment]
I guess that's not intended. PR and unit test welcome.
