### ISSUE TITLE
www.dokuwiki.org editable for all, check access rights!

### ISSUE THREAD

**Issue by WorldException** [splitbrain/dokuwiki#1544]
Check access rights for edit on www.dokuwiki.org !!!
I try edit page https://www.dokuwiki.org/changes and it's work.
All not registered users can edit pages except start page.

**Comment by selfthinker** [comment]
That is intentional, it's called a [wiki](https://en.wikipedia.org/wiki/Wiki). It has been like this since the very beginning (2004).

**Comment by splitbrain** [comment]
thanks for your notice. However it is perfectly fine that the pages at
dokuwiki.org are editable by the public. DokuWiki is a Wiki, a
software designed to encourage and facilitate collaborative text
editing. This is achieved by lowering the barriers to contribute and
making it easy to participate. By default, everyone is invited to edit
nearly any page on the wiki.

To ensure robustness against mistakes and vandalism, each edit creates
a new version of a page. Old revisions can be easily accessed and
unwanted edits be reverted.

More information about Wikis in general can be found at
http://en.wikipedia.org/wiki/Wiki and if you'd like to run your own
wiki, DokuWiki might be just the right tool for you.


On Wed, Apr 20, 2016 at 9:57 AM, Evgeniy <notifications@github.com> wrote:
> Check access rights for edit on www.dokuwiki.org !!!
> I try edit page https://www.dokuwiki.org/changes and it's work.
> All not registered users can edit pages except start page.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub



-- 
splitbrain.org
