### ISSUE TITLE
Remove jquery-migrate

### ISSUE THREAD

**Issue by selfthinker** [splitbrain/dokuwiki#1546]
We deprecated jquery-migrate on 2013-02-03 (the moment we integrated it) and it was only intended as a temporary solution. We should remove it rather sooner than later.
But its removal might cause more problems (we still use it in the core, [see potential warnings](https://github.com/jquery/jquery-migrate/blob/master/warnings.md)), so it might be a bigger task.

Part of this task is identifying where the issues are. So far I've found these affected instances which would need to be rewritten. Please add more here if you find more:
- [x] `jQuery.browser` is used in editor.js in `init()`
- [x] `jQuery.browser` is used in media.js in `update_resizable()`
- [x] `jQuery.fn.load()` is used in linkwiz.js in `autocomplete_exec()`
- [x] `jQuery.fn.load()` is used in linkwiz.js acl/script.js in `loadinfo()`
- [ ] JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos, from jquery-ui
- [x] JQMIGRATE: jQuery.fn.click() event shorthand is deprecated, in script.js
- [x] JQMIGRATE: jQuery.fn.keyup() event shorthand is deprecated, in qsearch.js
- [x] JQMIGRATE: jQuery.fn.focus() event shorthand is deprecated, in behaviour.js
- [x] JQMIGRATE: jQuery.fn.change() event shorthand is deprecated, in behaviour.js
- [x] JQMIGRATE: jQuery.fn.removeAttr no longer sets boolean properties: disabled, in behaviour.js
- [x] JQMIGRATE: jQuery.fn.mouseover() event shorthand is deprecated, in page.js
- [x] JQMIGRATE: jQuery.fn.mouseout() event shorthand is deprecated, in page.js

**Comment by micgro42** [comment]
The problematic occurrences of `jQuery.fn.load()`  in `linkwiz.js` and `acl/script.js` seem to be fixed?

**Comment by phy25** [comment]
`jQuery.fn.load` seems unrelated, because we are not using it for the event handling purpose.

> Note: Prior to jQuery 3.0, the event handling suite also had a method named .load(). Older versions of jQuery determined which method to fire based on the set of arguments passed to it.
>
> https://api.jquery.com/load/

So looks like everything on the list is done..? It's just very hard to do a comprehensive browser test against this though.

**Comment by micgro42** [comment]
Automated browser-tests. That is something we should start doing. But for now, manual testing will have to make do.

I too think that we can remove jQuery migrate. Feel free to create a pull request and then we can play around with it and see if anything comes up :)

**Comment by Klap-in** [comment]
https://codesearch.dokuwiki.org/search?project=dokuwiki&project=plugin&project=template&q=load&defs=&refs=&path=&hist=&type=javascript I guess there are some potential plugins with these old functions...

**Comment by phy25** [comment]
I think some polyfill plugin or config can be made so that if this breaks legacy things, they can just add it back.

Since DokuWiki uses production version of jquery-migrate, it would also help if we made a plugin with the development version shipped, for deprecation message console output.

I thought there is such a plugin but I only found deprecated [plugin:jquery](https://github.com/cosmocode/dokuwiki-plugin-jquery) so far. If there is none I can quickly work on a new one.

**Comment by phy25** [comment]
I created a plugin [plugin:jquerymigrate](https://www.dokuwiki.org/plugin:jquerymigrate) to load jQuery-migrate after we removed it from core. When I tested the plugin it looks like there are still warnings in the console (the plugin can use the dev variant which will show warnings not present in the production variant). Will do a through test later.
