### ISSUE TITLE
Use preg_replace_callback in authldap for php7 compability

### ISSUE THREAD

**Issue by pgauret** [splitbrain/dokuwiki#1551]
Upgrading to PHP7 broke the authldap pluging with the following error.

`PHP Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /var/lib/dokuwiki/lib/plugins/authldap/auth.php on line 392`

The fix is trivial, just replacing the call to preg_replace by preg_replace_callback without even changing the parameters does the job.

**Comment by Klap-in** [comment]
http://php.net/manual/en/reference.pcre.pattern.modifiers.php#reference.pcre.pattern.modifiers.eval

**Comment by Klap-in** [comment]
In the development branch it is fixed recently: https://github.com/splitbrain/dokuwiki/pull/1373

You run the last stable release? The coming release will contain this fix.
