### ISSUE TITLE
Since upgrade to an https SSL certificate on our domain, dokuwiki no longer works

### ISSUE THREAD

**Issue by kevinstevens** [splitbrain/dokuwiki#1560]
Since an upgrade to an https SSL certificate on our domain, docuwiki no longer allows saving or previewing of an article.  When you click either button, the page refreshes (blinks) briefly but nothing changes.  I also tried to log in to the admin panel and after entering my user name and password it give the error:

Warning: stream_set_blocking() has been disabled for security reasons in /home/trigin2/public_html/wiki/inc/HTTPClient.php on line 369

Warning: Cannot modify header information - headers already sent by (output started at /home/trigin2/public_html/wiki/inc/HTTPClient.php:369) in /home/trigin2/public_html/wiki/inc/common.php on line 1818

**Comment by splitbrain** [comment]
The problem is not your upgraded certificate. The problem is that someone (your hoster) disabled a vital PHP function ``stream_set_blocking``. Get that fixed and your problem should vanish.
