### ISSUE TITLE
Respect showuseras everywhere

### ISSUE THREAD

**Issue by ndarilek** [splitbrain/dokuwiki#1561]
I'm the author of the DokuWiki [Sandstorm](https://sandstorm.io) port. Sandstorm makes administering servers as easy as working with apps on your phone. With my port, users can spin up secure, shareable wiki instances in a single click, and upgrade them just as easily.

Sandstorm acts as an HTTP proxy between users and apps. It handles authentication, and passes usernames/handles to the app via HTTP headers. In Sandstorm, the thing that is most like a Unix username is a non-user-friendly hash. Users can have their own preferred display names, but these aren't guaranteed to be unique and can change any time the user wants them to. That's not usually a big deal since most Sandstorm apps are used for smaller groups (I.e. I could easily spin up half a dozen wikis for a group and share them with a handful of users, so the likelihood of display names clashing is usually low enough to not worry about.)

So I've set the following in local.php:

```
$conf['showuseras']  = 'username';
```

My hope was that this would display the friendly, human-readable Sandstorm usernames everywhere. I've also written a custom auth plugin. Here is how I'm setting up the user:

```
    public function trustExternal($user, $pass, $sticky = true) {
        global $USERINFO;
        global $conf;
        $sticky = true;
        $USERINFO['name'] = rawurldecode($_SERVER['HTTP_X_SANDSTORM_USERNAME']);
        $USERINFO['mail'] = 'user@example.com';
        $USERINFO['grps'] = str_getcsv($_SERVER['HTTP_X_SANDSTORM_PERMISSIONS']);
        $_SERVER['REMOTE_USER'] = $_SERVER['HTTP_X_SANDSTORM_USER_ID'];
        $_SESSION[DOKU_COOKIE]['auth']['user'] = $USERINFO['name'];
        $_SESSION[DOKU_COOKIE]['auth']['pass'] = $pass;
        $_SESSION[DOKU_COOKIE]['auth']['info'] = $USERINFO;
        return true;
    }
```

In Sandstorm, X-Sandstorm-User-Id is the unique, hash, non-human-friendly userID while X-Sandstorm-Username is the human-friendly, non-unique name. I want user-id to be what Dokuwiki stores in whatever it needs to uniquely track users, while x-sandstorm-username is what is always, always, always shown to users. Granted, this makes it difficult to link to users, but most of the wikis I use don't rely on that feature anyway, and Sandstorm will eventually have autocomplete widgets that can detect when someone starts typing a Sandstorm username and replace it inline with whatever you want, so in this case wiki links to the ugly hashes.

With the above config snippet in place, I still get user hashes displayed just about everywhere. The username is displayed when showing what the user is logged in as, but it is followed immediately by the hash. Additionally, the recent changes page and information about who last edited a page is still displayed as a hash. I've made a few tweaks that eliminate some of these hashes, but instead they end up showing the logged-in user, so I'm probably pulling the incorrect data from some confusingly-named global or other. Seems like it'd be easier to get this config option to meet my expectations so I don't have to diverge the Sandstorm port much.

I'd thought that showuseras would resolve this, but it seems selectively applied. What am I missing? Am I setting up my user incorrectly in my auth plugin? I'm not a PHP person and this code isn't exactly the easiest to jump into for someone who just wants to get Doku running in Sandstorm so he doesn't have to poke it anymore. :)

Thanks.

**Comment by Klap-in** [comment]
Nice to see application of this feature! I tried to apply it to all relevant locations when writing this. But maybe I forgot some or do you have installed plugins that do not yet use this feature.

Could you please list the places were you discover that this feature was not yet applied? 

That the username is visible at the top was a design choice... but indeed with the assumption that the username was meaningfull, so that it is instructive for the normal user to see the username.

I will look at the code, maybe it is possible to tune it easily.

**Comment by ndarilek** [comment]
Thanks. I listed a few later in the issue--on top, in the recent changes 
page and in the "Last modified" bit at the bottom of each page. There 
aren't any plugins installed and this is pure Doku, which is why I 
included part of my auth plugin. I'm uncertain as to whether I'm setting 
up the user correctly, but I think I am.

Thanks.

**Comment by ndarilek** [comment]
Also, is it possible that I'm setting it incorrectly? I'm not entirely 
clear on Doku's terminology for unique login names vs. friendly display 
names.

**Comment by Klap-in** [comment]
I have to look into the details, before I can provide a more elaborating answer

**Comment by Klap-in** [comment]
Could you show your getUserdata function of your Auth plugin?

**Comment by ndarilek** [comment]
I don't actually have one. Would I need one for that code to work? When 
I look at the data for the changes, I see the usernames alongside the 
hashes so assume they're alongside the change data.

Here's the constructor function for my auth plugin:

```
     public function __construct() {
         parent::__construct(); // for compatibility

         // FIXME set capabilities accordingly
         //$this->cando['addUser']     = false; // can Users be created?
         //$this->cando['delUser']     = false; // can Users be deleted?
         //$this->cando['modLogin']    = false; // can login names be 
changed?
         //$this->cando['modPass']     = false; // can passwords be changed?
         //$this->cando['modName']     = false; // can real names be 
changed?
         //$this->cando['modMail']     = false; // can emails be changed?
         //$this->cando['modGroups']   = false; // can groups be changed?
         //$this->cando['getUsers']    = false; // can a (filtered) list 
of users be retrieved?
         //$this->cando['getUserCount']= false; // can the number of 
users be retrieved?
         //$this->cando['getGroups']   = false; // can a list of 
available groups be retrieved?
         $this->cando['external']    = true; // does the module do 
external auth checking?
         $this->cando['logout']      = false; // can the user logout 
again? (eg. not possible with HTTP auth)

         // FIXME intialize your auth system and set success to true, if 
successful
         $this->success = true;
     }
```

**Comment by splitbrain** [comment]
you will need a getUserData function. DokuWiki always stores the real login name everywhere and queries the auth backend when needing to show a real name. Without that function you can't have real names for anything done by someone who is not the current user. Also the email subscription feature won't work.

**Comment by Klap-in** [comment]
Details about the required functions in an auth plugin:
https://www.dokuwiki.org/devel:auth_plugins

Some of the locations with wrong username are using the method `editorinfo()`. Which is calling `userlink()`, which is calling `getUserdata()`: https://github.com/splitbrain/dokuwiki/blob/master/inc/common.php#L1730

**Comment by koenigchristoph** [comment]
Hi,

I am a user of ndarilek's port and 'helping' him by sending him annoying bug reports ;-)

IANAP, but do i understand corectly that 

a) A getUserData function would greatly help and maybe email notifications would even start working (jay!)
b) There is a general mismatch between the datamodels here:

DokuWiki has

* login which is unique and must be a valid pagename 
* real name 

Sandstorm has

* id which is a hash, that is unique over all Sandstorm apps and users 
* username which is userfrendly name, can change and does not need to be unique

Adding a getUserData function will help to map Sandstorm's username to DokuWiki's real name.

But mapping Sandstorm's id to DokuWiki's login will mean that user pages will be named after that hash. That makes userpages close to unusable for humans. Also, are the hashes _always_ valid pagenames?

Do I get this right?

**Comment by ndarilek** [comment]
Email won't start working unless someone bridges whatever Doku uses to 
send email with Sandstorm's custom secure mechanism:

https://docs.sandstorm.io/en/latest/developing/email-from-apps/

I am unlikely to do this as PHP isn't my strength, and I'm short on 
time. I would except a PR for it though, but I don't know that it will 
work as expected since the email will always appear to come from the 
grain owner.

That said, I will probably look into implementing the necessary 
functions for the auth plugin, since that likely just involves putting 
user data in SQLite/LevelDB/something equally easy to work with. Can't 
say when I'll get to it, but I have a medium (50-60 members) 
organization on Doku now and I'd like to move that into Sandstorm, so I 
definitely have personal stake in that.

**Comment by splitbrain** [comment]
@koenigchristoph user names in DokuWiki do not need to be valid page names. The auth backend can decide what is a valid user name (but it has to be unique). If you use user pages of course those pages need to have valid names.

**Comment by splitbrain** [comment]
Is there anything left to do here on the DokuWiki side?

**Comment by phy25** [comment]
I am closing this because of lack of response, but feel free to add more information and I can reopen the issue if necessary.
