### ISSUE TITLE
Why my editor area becomes so small ?

### ISSUE THREAD

**Issue by ZHANGYANKUN** [splitbrain/dokuwiki#1562]
Why my editor area becomes so small ?

How to make it to be fullwidth ?

![2016-05-04-00001](https://cloud.githubusercontent.com/assets/3318669/15003901/977d9dc0-11e3-11e6-8d84-fc97653ddf02.png)

**Comment by Klap-in** [comment]
First guess is that your template css style code has parts that add or remove lines that influences the styling of this field.

(please note that you make it impossible for anybody to reproduce your case. What should someone install/configure to see your case on an own machine? or does your wiki have a public link?)
