### ISSUE TITLE
Dokuwiki breaks external jquery plugins

### ISSUE THREAD

**Issue by q2apro** [splitbrain/dokuwiki#1567]
I am using some jquery plugins to enhance dokuwiki. However, I just [realized](https://www.dokuwiki.org/devel:javascript) that: 

> jQuery is only used in compatibility mode. There is no $() method

So how can I load external plugins then (there are minified and I cannot modify the code) and let them run. 

I have also tried without success: 

    jQuery.noConflict();

And why is it not allowed to use `$()` which is everywhere, on every jquery article, tutorial, ...

**Comment by splitbrain** [comment]
Proper jQuery plugins will not rely on the availability of $() but register within the global jQuery object. So your plugin is probably broken anyway.

You can always map jQuery to $ with ``$ = jQuery;`` if needed.

**Comment by q2apro** [comment]
`$ = jQuery;` helped, thanks a thousand!
