### ISSUE TITLE
Change name of namespace in DokuWiki not possible

### ISSUE THREAD

**Issue by q2apro** [splitbrain/dokuwiki#1568]
I am a bit lost, probably due to my lack of dokuwiki knowledge. Weird enough I have a namespace in access permissions and media manager: 

![capture](https://cloud.githubusercontent.com/assets/6764548/15111838/7ffafa4a-15f2-11e6-92e6-993622901940.PNG)

![capture2](https://cloud.githubusercontent.com/assets/6764548/15111839/81c2b4f8-15f2-11e6-87ae-bd355f3cf625.PNG)

I could not find a way to remove the `[Wurzel]` namespace or to rename it. 

Even searching for this file/folder on my server was without success. Stuck here.

Is this a bug? Do I have to clean a cache or something?

**Comment by splitbrain** [comment]
That's the root namespace. You're using a german wiki, so it's named Wurzel.

PS: please use the forum for support requests.

**Comment by q2apro** [comment]
Ah gosh, since I was doing mathematics, I thought I did a mistake defining it myself somewhere (root == Wurzel). Is there any chance to rename "Wurzel" to "root". Ah found it at \inc\lang\de-informal

IMO, it should be named differently, not "Wurzel" but "Stamm" or just "root" like in English.

**Comment by Klap-in** [comment]
See here how you apply changes to your localization that are resistant to DokuWiki upgrades:
https://www.dokuwiki.org/localization#changing_some_localized_texts_and_strings_in_your_installation

Improved translations could be submitted via the translation tool.
"Wurzel" vs "Stamm" is equivalent to "Root" vs "Trunk", it isn't?

**Comment by micgro42** [comment]
> "Wurzel" vs "Stamm" is equivalent to "Root" vs "Trunk", it isn't?

Yes.

**Comment by q2apro** [comment]
@Klap-in Thanks for the link. 

Regarding "Wurzel", well, I have never seen this word being used in this context after 10+ years of programming. I would just go for root. "Wurzel" does mean the root of a real tree. I vote for "root" since we have hundreds of English words included in the German language anyways - which make more sense to us.
