### ISSUE TITLE
new Form-system needs documentation on dokuwiki.org

### ISSUE THREAD

**Issue by micgro42** [splitbrain/dokuwiki#1571]
The new Form-system in ```inc/Form/``` is currently not documented anywhere. We should have at least some basic documentation for it on dokuwiki.org.

For example on [devel:form](https://dokuwiki.org/devel:form)?

Related: #1570  #1312

**Comment by micgro42** [comment]
I started this with [two basic examples](https://www.dokuwiki.org/devel:form)

**Comment by micgro42** [comment]
Though I didn't find any obvious dokuwiki.org pages from where to link to the documentation of the new Form system

**Comment by splitbrain** [comment]
I prefixed it with a short introduction and linked it from the development manual.
