### ISSUE TITLE
Linking the "create page" on empty page to create new page

### ISSUE THREAD

**Issue by q2apro** [splitbrain/dokuwiki#1574]
Instead of just showing the *text* message: 

![7raopok](https://cloud.githubusercontent.com/assets/6764548/15226386/1fbd411a-188b-11e6-8c41-c218e59531c1.png)

I would like to link this marked part so that the user only has to click the link to come to the editor.

How to achieve this?

PS: Posting at https://forum.dokuwiki.org/thread/13677;watch=1;nocount;key=98ED27AA was not helpful.

**Comment by Klap-in** [comment]
This text is in: https://github.com/splitbrain/dokuwiki/blob/master/inc/lang/en/newpage.txt

See here you could modify in your own wiki:
https://www.dokuwiki.org/localization#changing_some_localized_texts_and_strings_in_your_installation
that is copy the file to `conf/lang/<lang>/newpage.txt` and modify.

Or you could propose a change of the file included in DokuWiki by creating a pull request.

**Comment by q2apro** [comment]
I solved it using jquery.

In conf/userscript.js I have added: 

	// link create page
	if($('.level1').length>0 && $('.level1 strong:contains("Seite anlegen")'))
	{
		$('.level1 strong:contains("Seite anlegen")').html( $('strong:contains("Seite anlegen")').html().replace('Seite anlegen', '<a href="?do=edit">Seite anlegen</a>') );
		// $('.level1').html
	}

**Comment by q2apro** [comment]
Better version, just add your language string: 

	// link create page
	var createphrase = 'Seite hier anlegen';
	if($('.level1').length>0 && $('.level1 strong:contains("'+createphrase+'")'))
	{
		$('.level1 strong:contains("Seite hier anlegen")').html( $('strong:contains("'+createphrase+'")').html().replace(createphrase, '<a href="?do=edit">'+createphrase+'</a>') );
	}
