### ISSUE TITLE
How to handle Latex in Footnotes?

### ISSUE THREAD

**Issue by q2apro** [splitbrain/dokuwiki#1578]
We are doing a math wiki and the problem we face is that [footnotes](https://www.dokuwiki.org/wiki:syntax#footnotes) contain Latex such as `$$ x^2 $$` which does not get parsed. 

Any idea how to handle such cases?

Workaround idea: Add the footnotes in the end of the page (disabling the mouseover footnotes). But is something like this possible?

**Comment by splitbrain** [comment]
please report in the plugin's bug tracker

**Comment by q2apro** [comment]
I am new to dokuwiki. What plugin?

**Comment by splitbrain** [comment]
what ever plugin you use to render Latex

**Comment by q2apro** [comment]
mathjax.js
