### ISSUE TITLE
Strange issue if clearing /data/cache folder

### ISSUE THREAD

**Issue by blacklord049** [splitbrain/dokuwiki#1579]
Hello,

I'm using Dokuwiki with PHP 7.0.6 (x64) on Apache 2.4.20 x64, Windows Server 2008 R2. If I delete the content of the /data/cache folder, it is recreated but going on some pages kills my session. Then I have to put my login and password to connect, but browsing the same page gives the same issue.

If I restore my previously deleted cache folder, the issue goes away.

Some changes I recently did : 
- pageutils -> wikiFN() fix.
- edited some styles in Bootstrap3 cerulean theme.

Plugin list : 
![plugin](https://cloud.githubusercontent.com/assets/16919700/15249356/5d2d816a-191f-11e6-9ce9-4162c96cb340.png)

What the hell is wrong ?
Thank you

**Comment by splitbrain** [comment]
Sorry, that is not enough information for even an educated guess. What pages. What's special about them? What plugins do they use? What is the ``pageutils -> wikiFN() fix``?

**Comment by blacklord049** [comment]
I'm using a super-admin login, so I should have an access to ALL pages. But if I clear the cache folder I start getting DW  "Access denied" errors and have to login again... And this does not stop until I restore the initial content of that folder.

There is nothing special about the pages where I get the error : for example the issue is encountered on a page with a title, a list and a link. 

The fix mentioned https://github.com/splitbrain/dokuwiki/issues/1536

**Comment by splitbrain** [comment]
what auth backend do you use?

**Comment by blacklord049** [comment]
Default authentication background (DW user + password).

**Comment by micgro42** [comment]
The fix you mentioned was merged over two weeks ago. Could you use the current master branch of Dokuwiki and see if the issue persists?

Also: For what problem did you need the ```wikiFN()```-fix?

**Comment by blacklord049** [comment]
So I downloaded the master branch of DW. I replaced everything, then deleted the content of /data/cache/ but the issue is not gone.

**Comment by blacklord049** [comment]
I tried again to purge /data/cache/* files but gives me auth error.
It's weird because it affects only some pages. But I don't know why...

**Comment by phy25** [comment]
I am going to close this since it's untouched for a long time (and does not seem to happen on another environment), and without further debugging there is nothing we can do. If this happens again, we can troubleshoot this somehow (it's just so weird).
