### ISSUE TITLE
How to disable the \\ linebreaks of dokuwiki?

### ISSUE THREAD

**Issue by q2apro** [splitbrain/dokuwiki#1580]
Since we are using Latex in all pages, we just discovered that the `\\` within the latex code block - which is the line break in latex - gets [parsed](https://www.dokuwiki.org/wiki:syntax#basic_text_formatting) by dokuwiki and get removed (!)

   $$ latex^2 \\ next_{line} $$

becomes 

   $$ latex^2 next_{line} $$

which results in one latex line instead of two. 

Is there any way how to disable this dokuwiki parsing?

**Comment by splitbrain** [comment]
please report in the plugin's bug tracker

**Comment by q2apro** [comment]
Which plugin would that be? Link?

I thought it is a core issue.

**Comment by q2apro** [comment]
PS: I tried the workaround to set <code>LATEX</code> but it renders it differently. 

Is there any TAG that can preserve the input as is?

**Comment by splitbrain** [comment]
I assume you use a plugin to render latex. Otherwise see https://www.dokuwiki.org/wiki:syntax#no_formatting

**Comment by q2apro** [comment]
Thanks, I tried nowiki but still not fixed. I investigate and report back later on.

**Comment by q2apro** [comment]
That is weird, using the nowiki tag, in the html source the original latex code survives, however: 

    $$A_{\rm{1}} \wedge A_{\rm{2}} \Leftrightarrow A_{\rm{2}} \wedge A_{\rm{1}} \\
    A_{\rm{1}} \vee A_{\rm{2}} \Leftrightarrow A_{\rm{2}} \vee A_{\rm{1}}$$

does not set the expected line break.

Example: http://www.mathelounge.de/repo/start#testbereich

Trying directly in this [online tex tool](http://www.matheretter.de/tools/tex/?tex=%24%24A_%7B%5Crm%7B1%7D%7D%20%5Cwedge%20A_%7B%5Crm%7B2%7D%7D%20%5CLeftrightarrow%20A_%7B%5Crm%7B2%7D%7D%20%5Cwedge%20A_%7B%5Crm%7B1%7D%7D%20%5C%5C%0AA_%7B%5Crm%7B1%7D%7D%20%5Cvee%20A_%7B%5Crm%7B2%7D%7D%20%5CLeftrightarrow%20A_%7B%5Crm%7B2%7D%7D%20%5Cvee%20A_%7B%5Crm%7B1%7D%7D%24%24), the same latex code works however.

Any idea what could be going on?

**Comment by q2apro** [comment]
Okay, I have found the problem. In using: 

    <script type="text/x-mathjax-config"> MathJax.Hub.Config({ "HTML-CSS": { scale:100, linebreaks: { automatic: true } }, SVG: { linebreaks: { automatic: true } }, displayAlign: "left" }); </script>

the `linebreak automatic` part does obviously interfere with the real linebreak. Changing it to: 

    <script type="text/x-mathjax-config"> MathJax.Hub.Config({ "HTML-CSS": { scale:100 }, SVG: { linebreaks: { automatic: true } }, displayAlign: "left" }); </script>

solved it. 

Note (for others with the same problem): You need to wrap your $$ LATEX (with linebreaks) $$ always in the &lt;nowiki&gt; tag.
