### ISSUE TITLE
How to automatically link all headlines on a page to itself?

### ISSUE THREAD

**Issue by q2apro** [splitbrain/dokuwiki#1581]
It would be handy to be have the headline linked to itself (its own section). So the users could just click > copy link and paste it externally to reference quicker. 

I have seen that one of the boostrap themes had this LINK icon showing up when hovering the single headlines, which made them linkable. 

You might know this automatic linking from the README.md files on github :) 

It would be really helpful, either the direct link or the link icon just behind the heading.

**Comment by splitbrain** [comment]
Again: this is not a support forum (forum.dokuwiki.org is). Please use this issue tracker when you a) found a bug or b) want a feature that currently does not exist. In general, when your issue title starts with "How to do X?" you probably want to write a forum post.

**Comment by q2apro** [comment]
Yes, I know about it. But the answer(s) I got over there were unfortunately not helpful. I will try to give it a try again.
