### ISSUE TITLE
Encoding issue with static assets.

### ISSUE THREAD

**Issue by viswanathct** [splitbrain/dokuwiki#1585]
Hello,

Assets which are delivered statically instead of css.php or js.php has an encoding mismatch. While the  response header has *Content-Encoding* set to *gzip*, the assets are delivered as plain text.

This occurred while installing the themes bootstrap3 and codowik.

**Comment by splitbrain** [comment]
Assets that are delivered statically are delivered by your webserver and their encoding and headers are thus set by your webserver not by dokuwiki.
