### ISSUE TITLE
interwiki.conf amazon

### ISSUE THREAD

**Issue by peterdd** [splitbrain/dokuwiki#1588]
Product urls on amazon .com and .de seem to be currently in this format:
and redirects to http, not https. (canonical rel-tag)

http://www.amazon.com/seo-blabla/dp/ASIN
http://www.amazon.de/seo-blabla/dp/ASIN

So this could be enough..:

http://www.amazon.com/dp/
http://www.amazon.de/dp/

or 
http://www.amazon.com/dp/{URL}....
http://www.amazon.de/dp/{URL}....
(bonus tracking not checked..)

**Comment by Klap-in** [comment]
Some pointers:
https://affiliate-program.amazon.com/gp/associates/help/t64/a1
https://github.com/splitbrain/dokuwiki/blob/master/conf/interwiki.conf
