### ISSUE TITLE
change editor to markdown : editor.md

### ISSUE THREAD

**Issue by zangetsudo** [splitbrain/dokuwiki#1591]
guys, I'm new to dokuwiki since i just used it and merged the markdowku but it's very arge ugly because some syntax cannot be parsed.
so i plan to make  editor.md the default editor for dokuwiki.
that's what i have done so far:
1. add js in lib/tpl/dokuwiki/main.php like:
editormd.min.css
editor.md/examples/js/jquery.min.js
editor.md/editormd.min.js

and : 

testEditor = editormd("editormd", /*... */ )

2. modify value returned in form_wikitext from inc/form.php like this:
	return '<div id="editormd"><textarea name="wikitext">'.DOKU_LF  
	.formText($attrs['_text'])
	.'</textarea></div>';  

now the new editor seems to be visible but it does not work.
please anyone can tell me how to change the default editor of doku ???

**Comment by Klap-in** [comment]
This sounds like features for the markdowku plugin itself, so not for DokuWiki.
