### ISSUE TITLE
Weird problem with "Administration/Extension Manager" on Ubuntu 14.04.4 LTS

### ISSUE THREAD

**Issue by asteve2016** [splitbrain/dokuwiki#1597]
I've followed these instructions to do a "Custom Installation" of Dokuwiki on Ubuntu:

    https://www.dokuwiki.org/install:ubuntu

I deviated slightly, on items 7 and 8, since I needed to integrate with an existing Apache configuration.  My configuration looks like this:

    <VirtualHost 10.10.1.2:80>
      ServerName dwiki.lansvr.co.uk
      ServerAlias dwiki.lansvr.co.uk
      ServerAdmin admin@lansvr.co.uk
      DocumentRoot /var/www/dokuwiki
      <Directory /var/www/dokuwiki>
        Options FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
      </Directory>
      ErrorLog /var/log/apache2/dwiki_error.log
      LogLevel warn
      CustomLog /var/log/apache2/dwiki.log combined
    </VirtualHost>

I ran the install.php script - and could then access the application.  Under "Administration" it reports:

    Release 2015-08-10a "Detritus"

Almost everything works properly... with one exception.  When I click on "Extension Manager" under "Administration" my web browser reports a zero-length response.  Corresponding with this is an entry in my apache2 log that reads:

    [Tue May 24 18:51:27.961841 2016] [core:notice] [pid 16438] AH00051: child pid 4519 exit signal Segmentation fault (11), possible coredump in /etc/apache2

When I run "php -v", I get:

    PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57)
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
        with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
        with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
        with XCache Optimizer v3.1.0, Copyright (c) 2005-2013, by mOo
        with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
        with XCache Coverager v3.1.0, Copyright (c) 2005-2013, by mOo

When I generated a core-dump, gdb gave the following stack trace:

	Core was generated by `/usr/sbin/apache2 -k start'.
	Program terminated with signal SIGSEGV, Segmentation fault.
	#0  0x00007f69751aac01 in zend_hash_find (ht=0x7f697c109b30, 
	    arKey=0x7f69586af258 "sendRequest", nKeyLength=12, pData=0x7ffcad5edc10)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_hash.c:924
	924	/build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_hash.c: No such file or directory.
	(gdb) 
	(gdb) back
	#0  0x00007f69751aac01 in zend_hash_find (ht=0x7f697c109b30, 
	    arKey=0x7f69586af258 "sendRequest", nKeyLength=12, pData=0x7ffcad5edc10)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_hash.c:924
	#1  0x00007f69672f2697 in xc_restore_zend_op_array ()
	   from /usr/lib/php5/20121212/xcache.so
	#2  0x00007f69672f3173 in xc_restore_HashTable_zend_function ()
	   from /usr/lib/php5/20121212/xcache.so
	#3  0x00007f69672f3ad2 in xc_restore_zend_class_entry ()
	   from /usr/lib/php5/20121212/xcache.so
	#4  0x00007f69672f427f in xc_restore_xc_entry_data_php_t ()
	   from /usr/lib/php5/20121212/xcache.so
	#5  0x00007f69672f4367 in xc_processor_restore_xc_entry_data_php_t ()
	   from /usr/lib/php5/20121212/xcache.so
	#6  0x00007f69672f7e3d in ?? () from /usr/lib/php5/20121212/xcache.so
	#7  0x00007f69672fa84a in ?? () from /usr/lib/php5/20121212/xcache.so
	#8  0x00007f69672fc1bf in ?? () from /usr/lib/php5/20121212/xcache.so
	#9  0x00007f69672fe3cc in ?? () from /usr/lib/php5/20121212/xcache.so
	#10 0x00007f697524a911 in ZEND_INCLUDE_OR_EVAL_SPEC_VAR_HANDLER (
	    execute_data=0x7f697a039878)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_vm_execute.h:13311
	#11 0x00007f69751c6358 in execute_ex (execute_data=0x7f697a039878)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_vm_execute.h:363
	#12 0x00007f697518c999 in dtrace_execute_ex (execute_data=<optimized out>)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_dtrace.c:73
	#13 0x00007f697518ec91 in zend_call_function (fci=fci@entry=0x7ffcad5efcf0, 
	    fci_cache=<optimized out>, fci_cache@entry=0x7ffcad5efcc0)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_execute_API.c:939
	#14 0x00007f69751b37a5 in zend_call_method (object_pp=0x0, 
	    obj_ce=<optimized out>, fn_proxy=0x7f6979d7fb18, 
	    function_name=0x7f6979d7fd58 "load_autoload", 
	    function_name_len=<optimized out>, 
	    retval_ptr_ptr=retval_ptr_ptr@entry=0x7ffcad5efdd8, 
	    param_count=param_count@entry=1, arg1=0x7f697c0ee930, arg2=arg2@entry=0x0)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_interfaces.c:97
	#15 0x00007f697508cdd6 in zif_spl_autoload_call (ht=<optimized out>, 
	    return_value=<optimized out>, return_value_ptr=<optimized out>, 
	    this_ptr=<optimized out>, return_value_used=<optimized out>)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/ext/spl/php_spl.c:436
	#16 0x00007f697518ca9b in dtrace_execute_internal (
	    execute_data_ptr=<optimized out>, fci=<optimized out>, 
	    return_value_used=<optimized out>)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_dtrace.c:97
	#17 0x00007f697518edeb in zend_call_function (fci=fci@entry=0x7ffcad5f0080, 
	    fci_cache=fci_cache@entry=0x7ffcad5f0050)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_execute_API.c:959
	#18 0x00007f697518f562 in zend_lookup_class_ex (
	    name=name@entry=0x7f69586a5088 "DokuHTTPClient", 
	    name_length=<optimized out>, key=0x7f69586a6640, 
	    use_autoload=use_autoload@entry=1, ce=ce@entry=0x7ffcad5f0118)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_execute_API.c:1115
	#19 0x00007f697518fc52 in zend_fetch_class_by_name (
	    class_name=0x7f69586a5088 "DokuHTTPClient", 
	    class_name_len=<optimized out>, key=<optimized out>, fetch_type=4)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_execute_API.c:1595
	#20 0x00007f69751d4689 in ZEND_FETCH_CLASS_SPEC_CONST_HANDLER (
	    execute_data=0x7f697a039728)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_vm_execute.h:1197
	#21 0x00007f69751c6358 in execute_ex (execute_data=0x7f697a039728)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_vm_execute.h:363
	#22 0x00007f697518c999 in dtrace_execute_ex (execute_data=<optimized out>)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_dtrace.c:73
	#23 0x00007f697524c070 in zend_do_fcall_common_helper_SPEC (
	    execute_data=0x7f697a039520)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_vm_execute.h:584
	#24 0x00007f69751c6358 in execute_ex (execute_data=0x7f697a039520)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_vm_execute.h:363
	#25 0x00007f697518c999 in dtrace_execute_ex (execute_data=<optimized out>)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_dtrace.c:73
	#26 0x00007f697524c070 in zend_do_fcall_common_helper_SPEC (
	    execute_data=0x7f697a039268)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_vm_execute.h:584
	#27 0x00007f69751c6358 in execute_ex (execute_data=0x7f697a039268)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_vm_execute.h:363
	#28 0x00007f697518c999 in dtrace_execute_ex (execute_data=<optimized out>)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_dtrace.c:73
	#29 0x00007f697524c070 in zend_do_fcall_common_helper_SPEC (
	    execute_data=0x7f697a0390a0)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_vm_execute.h:584
	#30 0x00007f69751c6358 in execute_ex (execute_data=0x7f697a0390a0)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_vm_execute.h:363
	#31 0x00007f697518c999 in dtrace_execute_ex (execute_data=<optimized out>)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend_dtrace.c:73
	#32 0x00007f697519dff0 in zend_execute_scripts (type=type@entry=8, 
	    retval=retval@entry=0x0, file_count=file_count@entry=3)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/Zend/zend.c:1316
	#33 0x00007f697513e9f5 in php_execute_script (
	    primary_file=primary_file@entry=0x7ffcad5f29f0)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/main/main.c:2506
	#34 0x00007f697524d6c2 in php_handler (r=<optimized out>)
	    at /build/php5-jAqhLZ/php5-5.5.9+dfsg/sapi/apache2handler/sapi_apache2.c:667
	#35 0x00007f6979f66be0 in ap_run_handler (r=0x7f6979fbc0a0) at config.c:169
	#36 0x00007f6979f67129 in ap_invoke_handler (r=r@entry=0x7f6979fbc0a0)
	    at config.c:439
	#37 0x00007f6979f7c6ca in ap_process_async_request (r=0x7f6979fbc0a0)
	    at http_request.c:317
	#38 0x00007f6979f7c9a4 in ap_process_request (r=r@entry=0x7f6979fbc0a0)
	    at http_request.c:363
	#39 0x00007f6979f79442 in ap_process_http_sync_connection (c=0x7f6979fce290)
	    at http_core.c:190
	#40 ap_process_http_connection (c=0x7f6979fce290) at http_core.c:231
	#41 0x00007f6979f70220 in ap_run_process_connection (c=0x7f6979fce290)
	    at connection.c:41
	#42 0x00007f6979f70608 in ap_process_connection (c=c@entry=0x7f6979fce290, 
	    csd=<optimized out>) at connection.c:202
	#43 0x00007f6975b6d767 in child_main (child_num_arg=child_num_arg@entry=2)
	    at prefork.c:704
	#44 0x00007f6975b6d9a6 in make_child (s=0x7f697a16bde0, slot=slot@entry=2)
	    at prefork.c:800
	#45 0x00007f6975b6da06 in startup_children (number_to_start=3) at prefork.c:818
	#46 0x00007f6975b6e6e0 in prefork_run (_pconf=<optimized out>, 
	    plog=0x7f697a167028, s=0x7f697a16bde0) at prefork.c:976
	#47 0x00007f6979f4d8ae in ap_run_mpm (pconf=0x7f697a19a028, 
	    plog=0x7f697a167028, s=0x7f697a16bde0) at mpm_common.c:96
	#48 0x00007f6979f47046 in main (argc=3, argv=0x7ffcad5f3118) at main.c:777

**Comment by splitbrain** [comment]
Seems your PHP version or one of your PHP extensions is buggy. Might be xcache. Try disabling it.

A PHP script should never be able to crash the PHP process. When it happens it's a bug in PHP not in the script.

**Comment by asteve2016** [comment]
Many thanks!

On your suggestion, I removed the php5-xcache package (using apt-get)
and everything started working.

I've no idea why php5-xcache was installed in the first place, I don't
think that anything I have installed depends upon it.

Steve
