### ISSUE TITLE
plugin help

### ISSUE THREAD

**Issue by zangetsudo** [splitbrain/dokuwiki#1600]
hi, everyone.
i'm new to this project. when i'm going to modify a plugin, i face a problem after i installed it
the input of TextArea is putty ugly, its style looks like this:

```ccs
pre, code, samp, kbd {
    font-family: Consolas,"Andale Mono WT","Andale Mono","Bitstream Vera Sans Mono","Nimbus Mono L",Monaco,"Courier New",monospace;
    font-size: 1em;
    direction: ltr;
    text-align: left;
    background-color: #fbfaf9;
    color: #333;
    box-shadow: inset 0 0 .3em #ccc;
    border-radius: 2px;
}
```

i traced the networking and found it's from http://localhost/dokuwiki/lib/exe/css.php?t=dokuwiki&tseed=d94a217fac5a4ed2c0a69eb697e449ec

is there any way i can trace the code down from css.php to disable attr like :
**box-shadow: inset 0 0 .3em #ccc;**

please tell me if any. thanks in advance.

**Comment by Klap-in** [comment]
Plugins are stored in the folder `<yourdokuwikifolder>/lib/plugins/<pluginname>/ `
In this folder you can find the style files for this plugin, or you could at your own per plugin.
Or if you like to set some modifications that are only for your wiki, and should kept on wikiupgrades:
Create or modify the file `<yourdokuwikifolder>/conf/userstyle.css` and add there your styling codes.

Some more general info about styling in DokuWiki:
 * https://www.dokuwiki.org/css
 * https://www.dokuwiki.org/devel:css#user_styles

**Comment by zangetsudo** [comment]
sorry Klap-in, im new to javascript too.
thanks for the first replay.
this is what i got now 
![snap](https://cloud.githubusercontent.com/assets/8794088/15633380/42bcae84-25de-11e6-9645-97bea6dd0b9d.png)
![text](https://cloud.githubusercontent.com/assets/8794088/15633381/42cd7d36-25de-11e6-8204-5de77b96eb5b.PNG)

please tell me what's wrong. thanks

**Comment by splitbrain** [comment]
please use the forum for support questions. closing this.
