### ISSUE TITLE
Revise link reference regex

### ISSUE THREAD

**Issue by dmak** [splitbrain/dokuwiki#1609]
As the followup to the [thread in maillist](https://www.freelists.org/post/dokuwiki/Migration-from-DokuWiki-20101107-Anteater-to-latest-in-HEAD,2) I suggest to revise the internal link reference which was changed in c34c77725873a495f375a815dd89be723cd2a512. Prior to that commit it was like that:

```
\[\[.+?\]\]
```

and now it is:

```
\[\[(?:(?:[^[\]]*?\[.*?\])|.*?)\]\]
```

I have the URL example that does not match this regex (but used to):

```
[[http://forum.com/search.php?f[]=1470&f[]=1257&nm=watson|search]]
```

There is one case that is matched by none of them (I have also tested in [playground](https://www.dokuwiki.org/playground:playground)):

```
[[http://www.imdb.com/title/tt1564585/|Skyline (Colin Strause) [2010]]]
```

and in order it to match I suggest much more simple regex which assumes that all square brackets are part of link up to outermost `]]`:

```
\[\[.+?\]\](?!\])
```

**Comment by splitbrain** [comment]
similar to #1587

**Comment by dmak** [comment]
... and similar to [Greedy brackets for footnote syntax](http://www.freelists.org/post/dokuwiki/Greedy-brackets-for-footnote-syntax)

**Comment by splitbrain** [comment]
Did you ever open a Pull Request for this? Could you do so? And could you provide unit tests?

**Comment by LarsGit223** [comment]
I think this can be closed now.
