### ISSUE TITLE
Sitemaps autodetect on migrations / new installs 

### ISSUE THREAD

**Issue by mat-witts** [splitbrain/dokuwiki#1611]
In some setups _autodetect_ for _sitemaps_ doesn't seem to work for _subdomains_, so this must be set explicity in _config_ using `baseurl`?

**Comment by splitbrain** [comment]
"some setups"? can you please elaborate what exactly the problem is under which conditions?

**Comment by mat-witts** [comment]
APACHE 2, DOCUMENT_ROOT `httpdocs` no with no server side (301) redirect.

`http://subdomain.example.com/dir/page` delivers 
`http://example.com/dir/page` to XML

**Comment by splitbrain** [comment]
Sorry. I can't follow. Please try to spent more than 5 seconds describing the problem. What do you expect? What happens instead? What did you try?

**Comment by mat-witts** [comment]
DOKUWIKI installed in top directory at `http://subdomain.example.com`
Expect `http://subdomain.example.com/sitemap.xml` to have something like this:
```
<urlset><url><loc>http://subdomain.example.com/dir/page</loc><lastmod>2015-05-15T10:10:31+00:00</lastmod></url>
</urlset>
```
Currently it delivers this:
```
<urlset><url><loc>http://example.com/dir/page</loc><lastmod>2015-05-15T10:10:31+00:00</lastmod></url>
</urlset>
```
Previous installation used PHP without GZIP support, so produced a raw XML file.

New installation uses new PHP configuration with GZIP support so used sitemap.xml.gz and is updated in cache.

The old XML file is redundant (not updated) but still accessible. The result is search engine index errors.

Maybe a line of code to DELETE old XML `if (file_exists("sitemap.xml")){unlink("sitemap.xml")}` after PING success to search engines might be a good idea for new installs / upgrades?

**Comment by splitbrain** [comment]
Sitemaps are no longer placed as a physical file in current DokuWiki releases. Your sitemap should be located at http://subdomain.example.com/?do=sitemap That one is also linked from the head of the page as ```<link rel="contents" href="/?do=index" title="Sitemap">``` or similar.

Deleting old XMLs might be an idea...
