### ISSUE TITLE
External image with non-ASCII URL is not loaded / embedded

### ISSUE THREAD

**Issue by dmak** [splitbrain/dokuwiki#1613]
Wiki code:
```
{{http://геомат.рф/viewImg.php?img_id=332&.jpg?200|image with non-ASCII URL}}
```
If you open [this URL](http://геомат.рф/viewImg.php?img_id=332), the image is loaded correctly (in Firefox remove auto-guessed `www.` prefix, [bug#1142083](https://bugzilla.mozilla.org/show_bug.cgi?id=1142083)).

**Comment by splitbrain** [comment]
It works for me: https://www.dokuwiki.org/playground:bug1613

**Comment by splitbrain** [comment]
Can you provide additional info please?

**Comment by dmak** [comment]
I have tested it again and it seems to work for me as well. Perhaps is related to FF version (on 45.0.2 works just fine). Closing as invalid.
