### ISSUE TITLE
Interwiki substitution does not work for image embedding

### ISSUE THREAD

**Issue by dmak** [splitbrain/dokuwiki#1614]
Provided that the following is in `conf/interwiki.conf` (that is the default setting)

```
phpfn     https://secure.php.net/{NAME}
```

the following 

```
{{https://secure.php.net/images/to-top@2x.png?30|try one}}
{{phpfn>images/to-top@2x.png?30|try two}}
```

Once the "alias" works for page URLs, I would expect it works also for resource URLs.

**Comment by splitbrain** [comment]
Interwiki links are not implemented for resources. PRs welcome.

**Comment by dmak** [comment]
I have completed the PR with solution.
@splitbrain could you please review it?

**Comment by salsa-dev** [comment]
Thank you very much for this PR! I was just about to submit the same issue.

I'm using interwiki links to link to data on IPFS running locally.
