### ISSUE TITLE
Submitted Arabic Translation but No Sign of It

### ISSUE THREAD

**Issue by damascene** [splitbrain/dokuwiki#1621]
Hi, I've submitted an Arabic translation more than 48 hours ago. I did not see any thing that shows that my translation was delivered except for the Thank you message on the translation software.

I wonder if there is an issue, is it under review  or it got lost?

I asked in L10N mailing list with no real answer.

I hope the translation system would be a little more verbose or if you can use PO files.

Best regards

**Comment by Klap-in** [comment]
Hmmm, not nice indeed.
I tried also two submits for Arabic, but these translation didn't appear too.

So there is something going on somewhere...I will request our server admins for a check of the logs of the translation tool.

**Comment by splitbrain** [comment]
closing this, assuming it was fixed in the translation interface
