### ISSUE TITLE
Update Release 2016-06-26 "Elenor of Tsort":  Ampersands too often substituted

### ISSUE THREAD

**Issue by hillschmidt** [splitbrain/dokuwiki#1622]
see the German entry in https://forum.dokuwiki.org/post/52729;nocount - I'll try to say the same in English:

It seems that after the Update to 2016-06-26 ALL "kaufmännischen UNDs" (&, Ampersand) are substituted with `&amp;` ... obviously not correct in all cases ....
Example in Code of the HEAD Section: (shortened URLs;  red marking will not work in here)

```
<link rel="contents" href=".../doku.php?id=index&amp;do=index" title="Übersicht"/>
<link rel="edit" title="Diese Seite bearbeiten" href=".../doku.php?id=index&amp;do=edit"/>
<link rel="alternate" type="text/html" title="HTML Klartext" href=".../doku.php?do=export_xhtml&amp;id=index"/>
<link rel="alternate" type="text/plain" title="Wiki Markup" href=".../doku.php?do=export_raw&amp;id=index"/>
```

I saw this in theoutput of the statdisplay Plugin. History of http://pe.hillschmidt.de/doku.php?id=allgemein:statistik shows here a `&#xa0;` ... instead of just the space entity, correctly coded, which has been wrongly replaced with `&amp;#xa0;`

```
Monatsauswertung
Monat	Täglicher Durchschnitt	Monatliche Gesamtwerte
Zugriffe	Dateien	Seiten	Besucher	Zugriffe	Dateien	Seiten	Besucher	Bytes
2016-01	2417	745	1672	251	74916	23081	51835	7778	1.8&#xa0;GB
2016-02	2633	862	1771	251	76345	24998	51347	7270	2&#xa0;GB
2016-03	2184	750	1434	234	67713	23251	44462	7242	1.8&#xa0;GB
2016-04	2513	779	1733	208	75381	23384	51995	6249	2.1&#xa0;GB
2016-05	2811	746	2065	193	87131	23113	64016	5988	1.9&#xa0;GB
2016-06	2134	738	1395	202	61883	21415	40465	5861	1.6&#xa0;GB
```

Solution?

**Comment by hillschmidt** [comment]
Hi Andreas, the problem in the output of the plugin arises 1st after the installation of the new Wiki release ... in the Wiki release before, the plugin's output was correct ...

**Comment by hillschmidt** [comment]
... and that means???

**Comment by Klap-in** [comment]
The commit of splitbrain that referenced this issue improves the code, so that your issue doesn't happen anymore. So this issue is now solved.
