### ISSUE TITLE
[Feature Request]Please consider adding a < Code > wrapper to the Editor toolbar

### ISSUE THREAD

**Issue by richardskumat** [splitbrain/dokuwiki#1624]
Would it be possible to add a button to the editor which wraps a selected text in:

```
<code>
Selected text here.

Another paragraph.

I love text.
</code>
```

opening and closing code tags?

I myself save lots of guides or code snippets and love wrapping parts of them in < code > tags for better visibility and formatting.

Sometimes pages I save text or snippets from are themselves indented with several space characters, which cause dokuwiki to treat them sometimes as code blocks, as explained on https://www.dokuwiki.org/wiki:syntax#code_blocks.

Manually typing out < code> and < /code > is somewhat tedious.

For example, github's "Insert code" button works just like Dokuwiki's Monospace Text[M] button. I don't use Monospace button that much.

I'm sorry if this there is already a shortcut for this I don't know about.

**Comment by selfthinker** [comment]
You could install the [CodeButton plugin](https://www.dokuwiki.org/plugin:codebutton) which does exactly that.

**Comment by richardskumat** [comment]
That seems to use ```file``` tags but also functions the way I want it to, so I'll settle for that.

Thank you, so I'll close this then.
