### ISSUE TITLE
Incorporating other GeShi's features

### ISSUE THREAD

**Issue by ricardovirtudazo** [splitbrain/dokuwiki#1625]
It's really cool to see that dokuwiki incorporated GeShi's syntax highlighting into its core, but it would be great if it also incorporates all other features of GeShi such as:
- enabling line numbers (http://qbnz.com/highlighter/geshi-doc.html#enabling-line-numbers)
- highlighting special lines "extra" (http://qbnz.com/highlighter/geshi-doc.html#highlighting-special-lines-extra)

to name a few.

**Comment by phy25** [comment]
Closed by #2307.
