### ISSUE TITLE
footnoteDisplay id replacement regex bug

### ISSUE THREAD

**Issue by liffiton** [splitbrain/dokuwiki#1626]
The regular expression on [line 99 of page.js](https://github.com/splitbrain/dokuwiki/blob/master/lib/scripts/page.js#L99) in `footnoteDisplay()` is incorrect, with the result that including TeX math in a footnote with the MathJax plugin prevents the footnote popup from displaying: see liffiton/dokuwiki-plugin-mathjax#27.  (Super-critical issue, I know.)

The issue is that the replacement does not include the terminating quotation mark.

In the Mathjax case, for example, `<script id="MathJax-Element-1" type="math/tex">` is changed to `<script id="insitu__MathJax-Element-1 type="math/tex">` (note the missing `"`), which then confuses jQuery when creating the footnote popup.

I believe the fix is simple:

Now `\bid=(['"])([^'"]+)\1`
Fixed `\bid=(['"])([^'"]+\1)`

This will include the terminating quotation mark in the replacement text.

**Comment by selfthinker** [comment]
This could be fixed by #1548 as that solves that problem differently.

**Comment by selfthinker** [comment]
As #1548 was merged today, I just tested the Mathjax syntax in a footnote and it is indeed fixed now.
