### ISSUE TITLE
in sandstorm, url's are not updated 

### ISSUE THREAD

**Issue by germakoci** [splitbrain/dokuwiki#1631]
@ndarilek:  When creating DokuWiki pages inside Sandstorm, I have to add the "name" of the page manually to the main grain url in order to be able to hyperlink across grains. 

DokuWiki is not updating the general url, I have only one for the entire DokuWiki set-up, for all pages. (as opposed to say GitLab where the Issues urls get updated, so I can hyperlink across grains for those with access permissions)

**Comment by splitbrain** [comment]
sorry, I have no idea how sandstorm works. This is probably better reported upstream to the sandstorm DokuWiki package maintainer.

**Comment by ndarilek** [comment]
This is probably fixed in the latest version.
