### ISSUE TITLE
Media Manager does not show XMP keywords

### ISSUE THREAD

**Issue by S-V-S** [splitbrain/dokuwiki#1633]
If a .jpg image has keywords inserted in Windows file explorer they are not visible in the keywords of Dokuwiki Media Manager.

**Comment by Klap-in** [comment]
If I understand your case correctly, than I think you could configure these fields by improving the configuration of field with `conf/mediameta.local.php`.

See https://www.dokuwiki.org/exif

**Comment by phy25** [comment]
I am closing this because of lack of response, but feel free to add more information and I can reopen the issue if necessary.
