### ISSUE TITLE
Possibility to view "Recently Created Pages" / "Recently Updated Pages"

### ISSUE THREAD

**Issue by LeDistordu** [splitbrain/dokuwiki#1641]
I tested plugins for that but I nothing really works

This plugin is the closest to what I want

https://github.com/cosmocode/changes

But for created page it do not work 

https://github.com/cosmocode/changes/issues/30

one example :

https://demo.bookstackapp.com/

**Comment by Klap-in** [comment]
This is an issue for the Changes plugin, not DokuWiki.
