### ISSUE TITLE
Feature request : URL to pull just one section of page (2nd Attempt )

### ISSUE THREAD

**Issue by cjohnsonuk** [splitbrain/dokuwiki#1642]
Summary
I can pull the whole page content by appending &do=export_xhtml and &do=export_xhtmlbody. I'd like to extract just the text under the named section

Detail
I have a system for managing manuals created using Dokuwiki. I use the "include" plugin to pull the ====Content==== part of my topic pages into pages for each Chapter allowing the authors to reuse topics in chapters for different clients. Each topic page includes support and other information under different headings. I use "include" so this information does not show within the Chapters.

I'd like to extract the topic content text programmatically to include as the text in help "pop ups" on a web page. I can pull the whole page content by appending &do=export_xhtml and &do=export_xhtmlbody but using the #pagesection syntax (that works with include) in the url doesn't work. I tried looking at the xml but even the "wiki.getPageHTML" appears to pull the whole page, not just the section.

Is there a way to do an equivalent to "?do=export_xhtml&section=content&inline=1&noheader=1"? (ie the include syntax via the URL?)

Any suggestions as to how I can get round this appreciated...

**Comment by splitbrain** [comment]
I think this would be better implemented in a plugin instead of the core. Maybe it could even be part of the include plugin.

**Comment by cjohnsonuk** [comment]
OK, thought I'd air it here first to save spending time looking into it only to find its either on a roadmap, an existing hidden feature or in a plugin already.  I'd thought it best in core because the existing page extract functionality is already part of core... (AFAICT)
