### ISSUE TITLE
Deprecated method use in tests

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#1643]
Current phpunit complains about ``PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead`` (See https://travis-ci.org/splitbrain/dokuwiki/jobs/145754995 for examples).

Our test cases need to be adjusted for the new PHPUnit methods.

**Comment by micgro42** [comment]
Also, PHPUnit 5.4 dropped support for PHP 5.3-5.5 and now only supports PHP 5.6 and PHP 7.0.

Support for PHP 5 will be completely dropped with PHPUnit 6, being scheduled for February 3, 2017.

To have full Support for PHP 5.3-5.6 one would have to use PHPUnit 4.8, currently Old-Stable. Would ``PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder()`` be compatible with PHPUnit 4.8?

**Comment by splitbrain** [comment]
good question. We'll have to figure this out and may need to adjust the travis setup to use the right phpunit release.

We probably want to increase the required PHP version with the next release, but probably to 5.6 not 7.0.

**Comment by micgro42** [comment]
> We probably want to increase the required PHP version with the next release

:+1:
