### ISSUE TITLE
Article shown based on timestamp

### ISSUE THREAD

**Issue by BlackLotus** [splitbrain/dokuwiki#1644]
When adding an article to dokuwiki it uses the newest version based on the timestamp and not on the order it was edited.
After a day working with a wrongly set clock a few wiki sites that got changed show the old version.
Dokuwiki showing articles based on order and not on timestamp would solve that problem.

Dokuwiki version: 20160626_a

Way to reproduce:
* Write an article
* Set your clock back 2 hours
* Edit the article again your changes won't be shown

**Comment by splitbrain** [comment]
DokuWiki requires a correctly set clock.

**Comment by Klap-in** [comment]
Related issue in old tracker: https://bugs.dokuwiki.org/index.php?do=details&task_id=2106
