### ISSUE TITLE
"Elenor of Tsort" gives a fatal error during CSS compilation

### ISSUE THREAD

**Issue by Naclador** [splitbrain/dokuwiki#1652]
Since the latest update I get the following error:

"A fatal error occured during compilation of the CSS files. If you recently installed a new plugin or template it might be broken and you should try disabling it again. [parse error: failed at `height: expression( this.scrollHeight > 300 ? "300px" : "auto");` in /lib/plugins/indexmenu/style.css at line 131]

I used the arctic template so far. Switching to "default" or "dokuwiki" does not remedy this error though. 
Any suggestions? Please answer in a foolproof fashion, I am just an unwitting user and have no idea about CSS programming.

**Comment by mprins** [comment]
You should talk to the maintainer of the indexmenu plugin that you are using or turn it off/remove it as that seems to be the cause of this

**Comment by Naclador** [comment]
Hello mprins,

thank you a lot! It was indeed the indexmenu plugin (I should have guessed it from the file path, of course). An update of the plugin resolved the issue. Thanks again!
