### ISSUE TITLE
Auth:AD No documentation regarding user authentication

### ISSUE THREAD

**Issue by atlarep** [splitbrain/dokuwiki#1656]
I have looked everywhere for an answer to this, but I haven't been successful finding it.
I have installed the AuthAD plugin, I can configure the access for superuser and managers, but I don't know what to use for regular (simple) users.

Example of AuthAD config:
```
<?php
  // general DokuWiki options
  $conf['useacl']         = 1;
  $conf['authtype']       = 'authad';
 
  // configure your Active Directory data here
  $conf['plugin']['authad']['account_suffix']     = '@MYAD.MYNET.COM';
  $conf['plugin']['authad']['base_dn']            = 'DC=myad,DC=mynet,DC=com';
  $conf['plugin']['authad']['domain_controllers'] = 'dcserver.mynet.com'; //multiple can be given
  .....
  $conf['manager']   = '@wikiadmins';
  $conf['superuser'] = '@wikiadmins';

```
What can I do to add other user groups like 'READONLY' or 'CONTRIB'?
There is no information out there as to how to authenticate users other than superuser or manager. Any help or advise would be appreciated.

**Comment by splitbrain** [comment]
You don't add any groups in DokuWiki when using AD. Instead you use the groups provided by AD in the ACLs.

**Comment by atlarep** [comment]
Can you please elaborate a little bit? I am a little bit new. I have the groups created in AD; I just don't know how to add them to the auth:ad config.

Would this work?
```
  $conf['readonly']   = '@wikireadonly';
  $conf['contrib'] = '@wikicontrib';
```

**Comment by splitbrain** [comment]
No. Read about ACLs. You're editing the config. That has nothing to do with permissions (except for defining who's a superuser or manager - as those gain more permissions than ACLs provide).

**Comment by atlarep** [comment]
Not the kind of tone/response I expected to be honest. Thanks anyway.

**Comment by splitbrain** [comment]
huh? what did you expect? I answered your question and pointed you into the direction of the appropriate documentation.
