### ISSUE TITLE
Editing dokuwiki tabs with CKG Editor make them broken

### ISSUE THREAD

**Issue by WorldofNyms** [splitbrain/dokuwiki#1658]
Hello !

We have updated our DokuWiki and CKGEdit to the latest versions and we are currently experiencing a bug when we are creating or editing a tab (see attached pictures).

We edit the tab with CKGEdit and save : tab is suddenly broken
If we edit the same page with DW Edit : we can see blanks after the " // "
When removing all the blanks created by CKG Edit (?) and save again with DW Edit, the tab is fixed.

Could you help us to fix this problem ?
Thank you :)

Picture 1 : when the tab is correct
![1_wiki_normal](https://cloud.githubusercontent.com/assets/20888793/17463216/879d54bc-5cc1-11e6-8f7d-4c057297fae0.png)

Picture 2 : after editing the page with CKG Editor and save
![2_wiki_bug](https://cloud.githubusercontent.com/assets/20888793/17463217/879e4f3e-5cc1-11e6-9064-ff7f10034c78.png)

Picture 3 : look at the page code with DW Edit
![3_wiki_source_bug](https://cloud.githubusercontent.com/assets/20888793/17463218/879f79cc-5cc1-11e6-86fe-36104c93dbbe.png)

Picture 4 : how to solve the problem - removing blanks manually
![4_wiki_source_corrected](https://cloud.githubusercontent.com/assets/20888793/17463219/87a0d4c0-5cc1-11e6-90bf-9a0fe7e018a3.png)

The problem occurs again everytime we edit the page with CKG Editor.

**Comment by splitbrain** [comment]
please report that at the ckg plugin's bug tracker.
