### ISSUE TITLE
Long path names on windows

### ISSUE THREAD

**Issue by Xeenych** [splitbrain/dokuwiki#1661]
The maximum length of filename+path is 260 chars in windows.

If pages in DW named in non-latin language and are long and encoded in "URL encoding", then in some cases DW cannot write files with such name because ath is too long.

There is an article in MSDN about MAX_PATH and a method to avoid it
https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#maxpath

You should prepend "\?\" to a path

For example, "\?\D:\very long path".

**Comment by mprins** [comment]
I think the php runtime should take care of that

**Comment by phy25** [comment]
Looks like PHP fixes this in 7.1: https://www.php.net/manual/en/migration71.windows-support.php
