### ISSUE TITLE
How to insert an image by external link without uploading to media?

### ISSUE THREAD

**Issue by chenweiyj** [splitbrain/dokuwiki#1662]
I want to insert an image to dokuwiki without uploading the image to the server where the dokuwiki is hosted, like `<img src="http://cdn-domain/xxx.png">` does.

How can I realize it? I have tried `{{http://cdn-domain/xxx.png}}`. However, it will use `/lib/exe/fetch.php?media=url` to use my server as a proxy to fetch the image which will burden my server and consume my server network traffic. Since my images are stored in an external cloud storage service, I want to direct link to the image like `<img>` tag does, which indicates that a user's browser can directly request the media with `url`.

**Comment by polyzen** [comment]
https://www.dokuwiki.org/wiki:syntax#image_links

**Comment by selfthinker** [comment]
This was [cross-posted in the forum](https://forum.dokuwiki.org/thread/13931).

It is currently not possible to use external media URLs directly. But as I wrote in the forum:
> The "burden" to your server is **extremely minimal** as the proxy does not download the image itself, it only **redirects** to the original image (unless you changed the default [fetchsize config option](https://www.dokuwiki.org/config:fetchsize)).

**Comment by selfthinker** [comment]
Closing as there was no response.
