### ISSUE TITLE
[feature request] add authmethods to existing account

### ISSUE THREAD

**Issue by TheRojam** [splitbrain/dokuwiki#1663]
Hello,
I really like to login in to my personal wiki with my _google-acount_ into my already _existing_ account.
[Plugin for authgoogle](https://www.dokuwiki.org/plugin:authgoogle) is already installed and set up. I can login via my google-account. How can I add (link) my google-account to my existing account?

@splitbrain #featurerequest

**Comment by Klap-in** [comment]
Sorry, this sounds as a feature request for the authgoogle plugin, and not for DokuWiki itself.
https://www.dokuwiki.org/plugin:authgoogle


Another plugin with Google login support as well is the oath plugin. If I understand that plugin correctly there the DokuWiki user accounts and Google accounts are linked with the unique email address of the user.
https://www.dokuwiki.org/plugin:oauth

**Comment by TheRojam** [comment]
@Klap-in  for it looks like that is an "Problem" within #dokuwiki. **thanks a lot for this hint!**
