### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by fpoto** [splitbrain/dokuwiki#1664]
In dokuwiki-2016-06-26a I see these in my Apache error log:

PHP Warning:  Invalid argument supplied for foreach() in /usr/share/dokuwiki/lib/exe/css.php on line 81, referer: ...

PHP Warning:  Invalid argument supplied for foreach() in /usr/share/dokuwiki/lib/exe/js.php on line 79, referer: ...

These warning appear twice each whenever a dokuwiki page is retrieved.

**Comment by Klap-in** [comment]
Please provide context of your situation.
(OS, apache version, your dokuwiki plugins, etc etc)
Did you change the config cascade or do you have any overrides in the preload.php (e.g. for a farm)?

Without context we cannot reproduce anything.

If you know php, please try to discover which exact arguments are provided to these foreach functions.

**Comment by fpoto** [comment]
Debian testing.

Dokuwiki packaged for Debian was over one year old and showed this problem. I manually upgraded it to the current stable (overwriting the distribution files and correcting permissions) and essentially nothing has changed.

Apache 2.4.23.

Plugins:
- ACL Manager
- Active Directory Auth (disabled)
- LDAP Auth (disabled)
- authpdo (disabled)
- Plain Auth
- Bureaucracy
- Configuration Manager
- do
- edittable
- Extension Manager
- Fastwiki
- Info
- Popularity Feedback
- prettytables
- Revert Manager
- safefnrecode
- sqlite
- styling
- Table Calculations
- User Manager
- Simple universal list

I do not know PHP, but I do know how to program and debug. If you can suggest a debugging path, please let me know and I'll try.

I can provide access to the wiki and even to the machine itself.

**Comment by fpoto** [comment]
No debugging suggestions? Hints?

**Comment by Klap-in** [comment]
Could you disable all plugins (at least self installed plugins)? And see if that changes the state of the css and js output?

**Comment by Chris--S** [comment]
First off, I'm not familiar with the debian dokuwiki page.

Both those lines are essentially the same thing, the css & js processors looking through the config cascade for file names to add to the list of files it needs to process.
```
css.php#81:            foreach($config_cascade['userstyle'][$mediatype] as $userstyle) {
js.php#79:          foreach($config_cascade['userscript']['default'] as $userscript) {
```
The $config_cascade values are set by default in inc/config_cascade.php, but can be modified using inc/preload.php (https://www.dokuwiki.org/devel:preload)

Iirc correctly, some of the linux distributions move dokuwiki's config files into ```/etc``` and presumably use preload.php (or something similar) to setup a modified config cascade.

For debugging.
- is there a inc/preload.php
- at line 59 in inc/init.php add ```echo '<pre>'; print_r($config_cascade); echo '</pre>';```
- visit http://your-wiki/lib/exec/css.php, view the source and look for the array values mentioned in the two lines above.

They should look something like that shown below.  The values aren't key here, but that where the array keys exist and they hold arrays.
```
[userstyle] => Array
        (
            [screen] => Array
                (
                    [0] => /path/to/file
                    [1] => /path/to/file
                )

            [print] => Array
                (
                    ...
                )

            [feed] => Array
                (
                    ...
                )

            [all] => Array
                (
                    ...
                )

        )

    [userscript] => Array
        (
            [default] => Array
                (
                    [0] => /path/to/file
                )
```

**Comment by Klap-in** [comment]
I suspect somewhere some error in css or js. Or some error in a configuration file that is somewhere used for performing the building of js and css. But not specific ideas..

So you have to tailor down possible changes.
If it is possible, could you test with a clean installed version of the wiki without existing data/configs etc? (edit: if suggestions of @Chris--S are not working)

**Comment by Chris--S** [comment]
@Klap-in it can't be a css or js error.  The warning comes before any processing of the files is started.  We're definitely looking at the ```$config_cascade```.  

Note this is only a "warning".  This part of the config cascade deal with custom wiki css & javascript.  If you don't have any of these files, the problem will not have any affect on your wiki.

**Comment by fpoto** [comment]
I see. So it is consequent to the preload.php distributed with Debian, and I should direct my bug to the Debian packager.

And no, I do not have custom css nor js. Thanks

**Comment by Chris--S** [comment]
If your installation does include that file, yes.  Dokuwiki installed from github or using our own installation instructions does not include that file (only an example file inc/preload.php.dist)

**Comment by vlirsub** [comment]
In file inc/preload.php

```php
$config_cascade = array(
...
...
    'userstyle' => array(
        'default' => DOKU_CONF.'userstyle.css', // 'default' was renamed to 'screen' on 2011-02-26, so will be deprecated in the next version
        'screen'  => DOKU_CONF.'userstyle.css',
        'rtl'     => DOKU_CONF.'userrtl.css',
        'print'   => DOKU_CONF.'userprint.css',
        'feed'    => DOKU_CONF.'userfeed.css',
        'all'     => DOKU_CONF.'userall.css',
    ),
    'userscript' => array(
        'default' => DOKU_CONF.'userscript.js'
    ),
```

change to 

```php
    'userstyle' => array(
        'default' => array(DOKU_CONF.'userstyle.css'), // 'default' was renamed to 'screen' on 2011-02-26, so will be deprecated in the next version
        'screen'  => array(DOKU_CONF.'userstyle.css'),
        'rtl'     => array(DOKU_CONF.'userrtl.css'),
        'print'   => array(DOKU_CONF.'userprint.css'),
        'feed'    => array(DOKU_CONF.'userfeed.css'),
        'all'     => array(DOKU_CONF.'userall.css'),
    ),
    'userscript' => array(
        'default' => array(DOKU_CONF.'userscript.js')
    ),
```

**Comment by phy25** [comment]
Looks like this has been fixed: https://salsa.debian.org/debian/dokuwiki/commit/d1476d23dae11ea185d0d1dfc29ccc5e6ed43781

Further issues should be reported at https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=dokuwiki.
