### ISSUE TITLE
CSS compilation: non-ASCII font name accepted or not?

### ISSUE THREAD

**Issue by GJRobert** [splitbrain/dokuwiki#1668]
Hi, here's what I'm adding to my userall.css today:

> font-family: Zantroke, Bevan, Bookman Old Style, 華康儷金黑, 華康儷金黑 Std, 標楷體, serif; font-weight: normal;

I'm trying to apply these bold fonts to headlines.

However, after CSS cache purged, DokuWiki gave me:

> 'A fatal error occured during compilation of the CSS files. If you recently installed a new plugin or template it might be broken and you should try disabling it again. [parse error: failed at `font-family: Zantroke, Bevan, Bookman Old Style, 華康儷金黑, 華康儷金黑 Std, 標楷體, serif;`  in /conf/userall.css at line 23]'

For explanation: 華康儷金黑, 華康儷金黑 Std, 標楷體 are all Chinese fonts. After taking these three fonts with Chinese names away from the list, DokuWiki can parse the CSS normally.

I have also converted the encoding of userall.css from a local standard ("Big5" actually, used mostly in Taiwan), to UTF-8, but that did not improve the situation.

I have just found the English names for all these fonts, and in using them in the CSS file, DokuWiki does not raise any objections.

So this makes me wondering if there is some limit in the current code of DokuWiki so that it does not accept non-ASCII font names in CSS codes?

**Comment by ssahara** [comment]
This is NOT a DokuWiki issue.
If font name consists more than a word or non-ASCII, it must must be in quotation marks. 
```
font-family: Zantroke, Bevan, "Bookman Old Style", "華康儷金黑", "華康儷金黑 Std", "標楷體", serif;
```
