### ISSUE TITLE
DokuWiki on a Stick - Crash using updated Apache and PHP version

### ISSUE THREAD

**Issue by PPPCR** [splitbrain/dokuwiki#1680]
Due to #1678, I completely replaced the folder "server" of my existing DokuWiki on a Stick bundle (stable 2016-06-26a "Elenor of Tsort" with Apache/2.4.7 PHP 5.4.25) with the folder "server" of the actual 2016-08-30 "snapshot", which is Apache/2.4.23 (Win32) PHP/5.6.25).

After that, I get crashes on my system (Win7 Professional x64 with SP1) of mapache.exe inside the module php5ts.dll. As far as i know, the c0000005 is an access violation exception:
![dokuwiki crash](https://cloud.githubusercontent.com/assets/6929356/18224909/056b0a4a-71e6-11e6-8b86-dd9a3711281f.png)

mapache.exe seems to span child processes, and the crashing process is one of them. Therefore, the parent process keeps running, in Process Explorer, a new child process will be started which crashes again. Therefore, the browser keeps loading the page and an incomplete page is rendered.

last content of error.log
> [Sat Sep 03 14:43:20.367407 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00455: Apache/2.4.23 (Win32) PHP/5.6.25 configured -- resuming normal operations
[Sat Sep 03 14:43:20.367407 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00456: Apache Lounge VC11 Server built: Jul  7 2016 11:13:22
[Sat Sep 03 14:43:20.367407 2016] [core:notice] [pid 480:tid 720] AH00094: Command line: 'mapache.exe -d E:/DokuWikiStick/server'
[Sat Sep 03 14:43:20.367407 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00418: Parent: Created child process 7336
[Sat Sep 03 14:43:21.584209 2016] [mpm_winnt:notice] [pid 7336:tid 768] AH00354: Child: Starting 64 worker threads.
zend_mm_heap corrupted
[Sat Sep 03 14:43:21.911810 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00428: Parent: child process 7336 exited with status 1 -- Restarting.
[Sat Sep 03 14:43:22.005410 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00455: Apache/2.4.23 (Win32) PHP/5.6.25 configured -- resuming normal operations
[Sat Sep 03 14:43:22.005410 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00456: Apache Lounge VC11 Server built: Jul  7 2016 11:13:22
[Sat Sep 03 14:43:22.005410 2016] [core:notice] [pid 480:tid 720] AH00094: Command line: 'mapache.exe -d E:/DokuWikiStick/server'
[Sat Sep 03 14:43:22.005410 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00418: Parent: Created child process 6932
[Sat Sep 03 14:43:23.362612 2016] [mpm_winnt:notice] [pid 6932:tid 764] AH00354: Child: Starting 64 worker threads.
[Sat Sep 03 14:43:26.747818 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00428: Parent: child process 6932 exited with status 3221225477 -- Restarting.
[Sat Sep 03 14:43:26.841418 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00455: Apache/2.4.23 (Win32) PHP/5.6.25 configured -- resuming normal operations
[Sat Sep 03 14:43:26.841418 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00456: Apache Lounge VC11 Server built: Jul  7 2016 11:13:22
[Sat Sep 03 14:43:26.841418 2016] [core:notice] [pid 480:tid 720] AH00094: Command line: 'mapache.exe -d E:/DokuWikiStick/server'
[Sat Sep 03 14:43:26.841418 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00418: Parent: Created child process 7064
[Sat Sep 03 14:43:28.058221 2016] [mpm_winnt:notice] [pid 7064:tid 768] AH00354: Child: Starting 64 worker threads.
[Sat Sep 03 14:43:29.493423 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00428: Parent: child process 7064 exited with status 3221225477 -- Restarting.
[Sat Sep 03 14:43:29.587023 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00455: Apache/2.4.23 (Win32) PHP/5.6.25 configured -- resuming normal operations
[Sat Sep 03 14:43:29.587023 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00456: Apache Lounge VC11 Server built: Jul  7 2016 11:13:22
[Sat Sep 03 14:43:29.587023 2016] [core:notice] [pid 480:tid 720] AH00094: Command line: 'mapache.exe -d E:/DokuWikiStick/server'
[Sat Sep 03 14:43:29.587023 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00418: Parent: Created child process 4944
[Sat Sep 03 14:43:30.850626 2016] [mpm_winnt:notice] [pid 4944:tid 764] AH00354: Child: Starting 64 worker threads.
[Sat Sep 03 14:43:32.488628 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00428: Parent: child process 4944 exited with status 3221225477 -- Restarting.
[Sat Sep 03 14:43:32.566629 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00455: Apache/2.4.23 (Win32) PHP/5.6.25 configured -- resuming normal operations
[Sat Sep 03 14:43:32.566629 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00456: Apache Lounge VC11 Server built: Jul  7 2016 11:13:22
[Sat Sep 03 14:43:32.566629 2016] [core:notice] [pid 480:tid 720] AH00094: Command line: 'mapache.exe -d E:/DokuWikiStick/server'
[Sat Sep 03 14:43:32.566629 2016] [mpm_winnt:notice] [pid 480:tid 720] AH00418: Parent: Created child process 7476
[Sat Sep 03 14:43:33.845831 2016] [mpm_winnt:notice] [pid 7476:tid 768] AH00354: Child: Starting 64 worker threads.

**Comment by splitbrain** [comment]
Hmm, I can not reproduce this. Can you explain what you are doing? Are there any special plugins involved? Could you provide me with your complete wiki setup?

**Comment by PPPCR** [comment]
I don't know why, but it seems that Comodo Internet Security sandboxed the apache executable even if it is inserted on the exception list and set to trusted.

I'll test the updated apache and php with my "old" installation (pages and plugins). Until now, after forcing the wiki do get some work (update search index by plugin, minimal changes to config to purge caches), it looks fine.
