### ISSUE TITLE
PHP 7.1 incompatibilities

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#1682]
Our test suite throws a whole bunch of errors on PHP 7.1: https://travis-ci.org/splitbrain/dokuwiki/jobs/157642628

**Comment by splitbrain** [comment]
Remaining issue seems to be a bug: https://bugs.php.net/bug.php?id=71822

**Comment by micgro42** [comment]
> Remaining issue seems to be a bug: https://bugs.php.net/bug.php?id=71822

Reminds me of: https://xkcd.com/1700/

**Comment by selfthinker** [comment]
What about `auth_encryption_test::testDeEncrypt`?
>  Function mcrypt_list_algorithms() is deprecated

**Comment by splitbrain** [comment]
@selfthinker the mcrypt_list_algorithm() problem is fixed with #1683
