### ISSUE TITLE
Add new action: MEDIAMANAGER_INSERT

### ISSUE THREAD

**Issue by stevenmg** [splitbrain/dokuwiki#1684]
Having a MEDIAMANAGER_INSERT action that would fire when an image is being inserted into the editor would make it easier to integrate the standard DokuWiki media manager with other editors. One could simply call the editor and wait for the action to fire, and that action listener could handle inserting the image into the editor.

**Comment by stevenmg** [comment]
Quick note, I have found a workaround for implementing the mediamanager with another editor, but it involves manually overriding the dw_mediamanager.insert function in a MEDIAMANAGER_STARTED action call and checking if the editor is loaded. This works, but of course it poses some maintainability issues.

**Comment by stevenmg** [comment]
I just realized that you can set the onselect URL parameter which takes care of my needs. Documentation is hard to find on this though I had to dig through the code to find it.

**Comment by splitbrain** [comment]
please feel free to improve the documentation
