### ISSUE TITLE
Server 500 error when adding headline directly after unordered list

### ISSUE THREAD

**Issue by staze** [splitbrain/dokuwiki#1687]
Hi All,

I reported this here: https://forum.dokuwiki.org/post/53664 but I'm unsure if anyone will see.

I'm happy to provide more info, but so far I can't figure out how to get dokuwiki to actually provide error logs (this doesn't seem to work: https://www.dokuwiki.org/faq:error500)

Please advise. Or let me know if you can/can't reproduce. This used to work... I'm unsure which revision may have broken things.

**Comment by staze** [comment]
What's weirder about this issue, I can not reproduce on a different page, but it does follow this content to a different page (I can cut the page, and recreate the content on a new page (new title) and the issue reoccurs). 

Content is simply: 

> ====== Unknown Questions ======
>   * How do we manage Google homepage, print dialog, etc.
>   * How do we manage Firefox settings (prevent update dialogs, set default homepage, etc). 
>   * Set to print duplex by default, etc.
>   * Self cleaning oven (people login, accounts are deleted, or clean, after 1 hour)
>   * Automount shares (classes)
> ===== Test =====

**Comment by splitbrain** [comment]
https://www.dokuwiki.org/faq:mod_security maybe

**Comment by staze** [comment]
Interestingly, and I can't say if this is the issue yet, I did find this in my logs:

[Sat Sep 10 23:40:10.645080 2016] [access_compat:error] [pid 495992:tid 140169533396736] [client xxx.xxx.xxx.xxx:29435] AH01797: client denied by server configuration: /home/sites/wiki/data/security.png, referer: http://wiki.domain.org/work/casper/unknowns?do=admin

I found this reported here: https://bugs.dokuwiki.org/index.php?do=details&task_id=2818

Unsure if that's what's causing the issue...

**Comment by staze** [comment]
Interestingly, I just installed "why spam" and tried pasting in that same text... same result. Error 500. 

Going go try disabling (I can't tell if it's enabled) mod_security...

**Comment by staze** [comment]
btw: dokuwiki version 2016-06-26a. php 5.6.25. Lightspeed 6.9. I do have opcache enabled, but that doesn't seem to be an issue. 

Any other hints would be great. I can't get dokuwiki to actually log what the error is, in a file, or anything... so I'm at a bit of a dead end. =(

**Comment by staze** [comment]
Okay, nevermind. 

Webhost admin just got back to me, and said indeed mod_security is the cause. Generic "SQL Injection protection". 

```
#Generic SQL sigs
SecRule ARGS "((alter|create|drop)[[:space:]]+(column|database|procedure|table)|delete[[:space:]]+from|update.+set.+=)" "id:300015,t:lowercase,rev:1,severity:2,msg:'Generic SQL injection protection'"

Request:	POST /work/casper/unknown_questions?do=edit
Action Description:	Access denied with code 500 (phase 2).
Justification:	Pattern match "((alter|create|drop)[[:space:]]+(column|database|procedure|table)|delete[[:space:]]+from|update.+set.+=)" at ARGS:wikitext.
```

Good guess!!!

**Comment by staze** [comment]
Anywho, thanks!
