### ISSUE TITLE
Relative Sizing for Media

### ISSUE THREAD

**Issue by KeenRivals** [splitbrain/dokuwiki#1697]
I often insert screencasts (mp4 / webm video) into my wiki via the media manager. The default sizing for the videos is very small. I know I can change the absolute size with _?widthxheight_ on the file link, but with video this does not work too well. Specifying a large width causes the video to fit the page width, but the height is still very small. Specifying a large width and height causes the width to scale with the container but not the height. 

I've found that by specifying the size of a 720p video to 912x513 I get a good result on a desktop, but with a small viewport that width shrinks and you end up with a large 513px block with a small video inside of it.

**Comment by Klap-in** [comment]
See https://www.dokuwiki.org/playground:videosizes for a video inserted at different sizes.

In Chrome I see not nice boxes around the video. In Firefox the syntax with ?0x100 and ?0x400 are scaled in the desired manner. 

How much does this behaviour depend on the browser used?

**Comment by KeenRivals** [comment]
I'm seeing the same undesirable behavior in Firefox and Chrome (did not test IE) on your page. If I add ``height: auto`` to the css rule ``img, object, embed, iframe, video, audio {max-width: 100%;}`` the height scales with the video element width while keeping the aspect ratio.

**Comment by KeenRivals** [comment]
I made a modification to my site to apply ``height: auto`` to the video element. You can [check it out there](https://help.lasallehs.net/doku.php?id=parents:powerschool#powerschool_account_creation_video_guide). I'll put together a pull request shortly.
