### ISSUE TITLE
timeout during ldap-auth if certificate is expired

### ISSUE THREAD

**Issue by jankowa** [splitbrain/dokuwiki#1710]
If authldap module is used for authentication with tls, there is a problem if the certificate is expired:

Instead of any reasonable error message the ldap connection hangs until configured php timeout. This can easly crash apache/php with

   server reached max_children setting (10), consider raising it

if a lot of pages with any kind of authentications are accessed (a ldap connection is also established to get user informations).

The problem is not consistent for other certificate issues: trying to access the ldap server with a hostname not matching the cn of the certificate leads to an "tls error" with no timeout.

All problems in establishing a tls connection should be handled this way. 

dokuwiki version: 2016-06-26a
ldap server: 389ds
plattform: debian wheezy
php version: 5.4.45

**Comment by jankowa** [comment]
dokuwiki version: 2016-06-26a
ldap server: 389ds
plattform: debian wheezy
php version: 5.4.45

**Comment by splitbrain** [comment]
I fear there's nothing we can do about it. TLS is handled within the ldap extension. Your PHP version is quite old, I could imagine that there's better handling in newer versions already. If not you should try to come up with a minimal code example and submit a bug at PHP directly.
