### ISSUE TITLE
Minimum height for page

### ISSUE THREAD

**Issue by mlinchitstest** [splitbrain/dokuwiki#1716]
see [earlier](https://github.com/MrClow/dokuwiki-template-2011/issues/17). 

This is still an issue if you add external buttons to page-tools (plugins). I think a cleaner look would be to automatically expand the whitespace to the bottom of the window—or to blur out the bottom shadow. Otherwise the borders are too prominent.

**Comment by phy25** [comment]
This may eventually ended up using a JavaScript to calculate minimum height - which I think is too much. You can always add custom CSS rule to fix it.

Maybe a won't fix?

**Comment by splitbrain** [comment]
We already have some JavaScript in place for that

https://github.com/splitbrain/dokuwiki/blob/d9051c44e9ebf5cd8dd6e13851ea797598679fb4/lib/tpl/dokuwiki/script.js#L73-L78

A proper fix would be to rework the template to make use of flexbox for the sidebar/content layout which was not available back in 2012.

**Comment by phy25** [comment]
> We already have some JavaScript in place for that

Hum, I did not notice this one before. I will submit a PR to calculate based on the two heights.
