### ISSUE TITLE
AuthAD plugin clarifications

### ISSUE THREAD

**Issue by Lord-Dimwit-Flathead-the-Excessive** [splitbrain/dokuwiki#1734]
I am setting up Dokuwiki on LAMP as a internal corporate knowledge-base in a multi-domain AD environment and have gotten everything to work up to the point of enabling SSO.   Then things get pretty wonky.   I think there is a bug somewhere in here but need some clarification on configuration of ['plugin']['authad'] entries in local.protected.php before I would say.

1. First, has the ['sso'] setting been deprecated subsequent to multi-domain?  This might explain a lot.
2. If not, is ['sso'] a global setting intended to affect all domains?  This seems to be its behavior.

Along the lines of my second question, it would be very helpful if someone could provide a definitive list of the 'global' vs domain specific ['plugin']['authad'] settings in local.protected.php.  Thank you.

**Comment by splitbrain** [comment]
1. no
2. yes

please restrict usage of the issue tracker to reporting bugs or feature requests. otherwise use the support forum.

**Comment by Klap-in** [comment]
In the issues are some todos with respect to sso/multidomain. Please search for 'Single sign on' and 'SSO'.

**Comment by Lord-Dimwit-Flathead-the-Excessive** [comment]
Yes, already did.  Andreas clarified some things for me here and I have better characterized the issue under #1736 .  Thanks, Klap-in.  This thread is closed.
