### ISSUE TITLE
tablecalc plugin cannot be updated

### ISSUE THREAD

**Issue by vikaskedia** [splitbrain/dokuwiki#1746]
The admin/extension manager web interface says that the plugin needs to be updated:

![image](https://cloud.githubusercontent.com/assets/6703876/19833063/3862b1b6-9dea-11e6-97a7-c5cd13a3a7f7.png)

When I click on the update button:

![image](https://cloud.githubusercontent.com/assets/6703876/19833070/53971a12-9dea-11e6-8d80-f8835ba41d10.png)

**Comment by flammy** [comment]
The download path listed here:

https://www.dokuwiki.org/plugin:tablecalc

does not exists (404 file not found).

You should try to contact the plugin author.
