### ISSUE TITLE
Writing a new plugin: Kanban board with namespaces as column names and pages as cards with drag to reorder

### ISSUE THREAD

**Issue by vikaskedia** [splitbrain/dokuwiki#1759]
I am planning to write a Kanban plugin that will be like trello but on the dokuwiki architecture of namespace and pages.

Before I write it I want to make sure:

1. Will it be useful to others?

2. I have searched the plugin directory and not found anything similar. Did I miss a plugin that already does this?

**Comment by splitbrain** [comment]
sounds cool. I'm sure people will like it. AFAIK nothing like that exists, yet.

PS: please use the forum for questions like these next time.
