### ISSUE TITLE
Salt does have a hardcoded default instead of using a CSPRNG

### ISSUE THREAD

**Issue by kelunik** [splitbrain/dokuwiki#1763]
https://github.com/splitbrain/dokuwiki/blob/65d3a5db1b1c8fa46b1aa39f43ae3598dc6dafb4/inc/PassHash.class.php#L526-L538

Having a hardcoded salt, no matter which value, does defeat the salt.

**Comment by splitbrain** [comment]
I'm not sure I follow. The lines you highlighted use ``$this->gen_salt()`` to generate a random salt if it hasn't been provided from the outside.

**Comment by kelunik** [comment]
This one is my bad, missed the `gen_salt` in the next line of https://github.com/splitbrain/dokuwiki/blob/65d3a5db1b1c8fa46b1aa39f43ae3598dc6dafb4/inc/PassHash.class.php#L533. Just saw the `str_pad` padding `0` and thought that'd generate the salt.

**Comment by kelunik** [comment]
Nevertheless, the API should probably be updated to use the `password_hash` API introduced in PHP 5.5 and https://github.com/ircmaxell/password_compat on earlier versions if they need to be supported.
