### ISSUE TITLE
Clear text password sent to database

### ISSUE THREAD

**Issue by kelunik** [splitbrain/dokuwiki#1764]
https://github.com/splitbrain/dokuwiki/blob/3c4f540783853073899836d757e562eb2b3d0bad/lib/plugins/authpdo/auth.php#L168-L170

I think I saw a switch to turn sending it off somewhere.

**Comment by splitbrain** [comment]
This is intentional. It only happens when an administrator explicitly enables it by creating a configuration for the check-pass config option (see https://www.dokuwiki.org/plugin:authpdo#option_check-pass). Normally this shouldn't be needed and thus not be used.
