### ISSUE TITLE
'0' headline isn't displayed.

### ISSUE THREAD

**Issue by epeios-q37** [splitbrain/dokuwiki#1770]
A headline containing only the '0' digit is not displayed. I put an example in the playground.

**Comment by Klap-in** [comment]
Thanks for the clear example.
https://www.dokuwiki.org/playground:bug1770

I guess somewhere is checked if we have an [empty](http://php.net/manual/en/function.empty.php) value.

**Comment by Klap-in** [comment]
https://github.com/splitbrain/dokuwiki/blob/master/inc/parser/xhtml.php#L1691

If $heading is `'0'`, it is skipped, and $default is returned instead.
```php
            if(useHeading($linktype) && $id) {
                $heading = p_get_first_heading($id);
                if($heading) {
                    return $this->_xmlEntities($heading);
                }
            }
            return $this->_xmlEntities($default);
```

**Comment by Klap-in** [comment]
Hmm this is of titles of the urls.

This is the check for headers, same logic:

https://github.com/splitbrain/dokuwiki/blob/master/inc/parser/xhtml.php#L194
```php
    if(!$text) return; //skip empty headlines
```

**Comment by micgro42** [comment]
So we should use `blank()` in these cases?
