### ISSUE TITLE
Form: attribute type not allowed in select tag

### ISSUE THREAD

**Issue by micgro42** [splitbrain/dokuwiki#1776]
Currently a dropdown created with DokuWiki's `Form` class has invalid html: A `<select>` tag must not have a `type` attribute. You can verify this error by pasting the code below into a validator like https://validator.w3.org/nu/#textarea

```html
<!DOCTYPE html>
<html>
<head>
<title>Title</title>
</head>
<body>
<select name="name" type="dropdown"><option selected="selected" value="1">1</option><option value="2">2</option></select>
</body>
</html>
```

**Comment by selfthinker** [comment]
The equivalent would be `size="1"` but most browsers nowadays show a dropdown box by default instead of a bigger box showing multiple options anyway. So, it might not be necessary.
