### ISSUE TITLE
authpdo: wrong return types of retrieveUsers and getUserCount in auth.php

### ISSUE THREAD

**Issue by arnomann** [splitbrain/dokuwiki#1781]
In dokuwiki-2016-06-26a, the return values of those two functions seem to be wrong. They both do not match the type given in the "@return" tag. retrieveUsers should return an array list of userinfo, but returns an array of user names. getUserCount should return the number of users as integer but returns a boolean. 

I couldnot get the authPDO plugin to work without two simple replacements:
line 406: return $this->getUserData($user); // was: return $user;
line 430: return $result[0]['count']; // was: return isset($result[0]['count']);

I am pretty sure that this is independend of the sql configuration. However, I can hardly imagine that such an error would go by unnoticed. Did I miss something?

**Comment by splitbrain** [comment]
You're right. Those were bugs. They indeed went unnoticed for two reasons: my tests were wrong (I assumed different return values for `retrieveUsers()` and did a type insensitive comparison for `getUserCount()`) and apparently most people (including myself) never configure more than the basic setup for authentication.

PR #1784 fixes both problems and a third I noticed while going over the code.

**Comment by arnomann** [comment]
Hmm, strange. I think that database authentication is a very useful plugin. I have been using it for a couple of years in one project together with external authentication via Cookies.

Thank you for the quick response.
