### ISSUE TITLE
Guaranteed color placeholders are not guaranteed

### ISSUE THREAD

**Issue by michitux** [splitbrain/dokuwiki#1792]
Due to a [bug report in the move plugin](https://github.com/michitux/dokuwiki-plugin-move/issues/68) I noticed that there are plugins without style.ini (like [dokubootstrapsimplified](https://www.dokuwiki.org/template:dokubootstrapsimplified)) that therefore also do not define any of the [guaranteed placeholders](https://www.dokuwiki.org/devel:style.ini#guaranteed_color_placeholders). The [template survey](https://www.dokuwiki.org/devel:template_survey) also shows that there are quite some templates without style.ini. Indeed, the documentation of  [style.ini](https://www.dokuwiki.org/devel:style.ini) includes a footnote "if the template supports it", which I interpret that it is no requirement for plugins to contain a style.ini.

As a plugin developer I find this quite sad because this means even the guaranteed color placeholders cannot be used in places where they must be defined (and a color). Two ideas for solving this:

* Provide fallback colors for the guaranteed color placeholders that are used when the template does not specify a color.
* Change the template specification to require style.ini and enforce it e.g. by displaying an error message when a template without style.ini is configured.

**Comment by splitbrain** [comment]
Actually I think we should do both.

**Comment by selfthinker** [comment]
Fallback colours make sense. They could produce bad colour combinations but that's better than failing.

> the documentation of style.ini includes a footnote "if the template supports it", which I interpret that it is no requirement for plugins to contain a style.ini.

But on the other hand it says under "guaranteed color placeholders":

> All templates have to implement these at least, but are free to add more.

which I interpret as a requirement.
We could remove that footnote, but on the other hand it's a fact of life that there are some templates which don't support it. (Judging from the history that footnote was there from the very beginning when style.ini was a new feature. That was before the guaranteed color placeholders existed.)

Enforcing a template to use a style.ini file is a mixed bag. It would be bad to show such an error message to everyone as it would be unhelpful and alarming for people using such templates as they usually cannot do anything about it.

I wonder if we could do some automated tests a) when developers are building templates (or generally running locally) and b) when developers are adding templates to dokuwiki.org. In the latter case we could add a warning to the page.

This now gets slightly off topic but there are more things which are worth checking:

* has style.ini
* has template.info.txt
* correct `base` in template.info.txt
* download or repo not within directory
* has no old `DOKU_TPL*` constants
* (I'm sure there is more)

**Comment by splitbrain** [comment]
When adding the default values it might make sense to reevaluate the placeholders. Adding `__link__` might make sense.
