### ISSUE TITLE
Empty mail body 

### ISSUE THREAD

**Issue by tutench** [splitbrain/dokuwiki#1799]
When I create a new user  the DokuWiki sents out a mail with the password info but the mail body is completely empty... The same happens when I get a notification about a changed article.

Release 2016-06-26a "Elenor of Tsort"
SMTP plugin is working

If more information is needed, let me know.

**Comment by splitbrain** [comment]
This seems to be more of a problem with the SMTP plugin than with DokuWiki. You should report it over there. When you do be sure to add some more details, like what kind of mail server you're using.
