### ISSUE TITLE
SimplePie v1.3.1 causes warning in PHP 7

### ISSUE THREAD

**Issue by ssahara** [splitbrain/dokuwiki#1800]
PHP warning caused by inc/SimplePie.php after upgrading PHP 7.1,
```
[07-Jan-2017 21:55:54 Asia/Tokyo] PHP Warning:  A non-numeric value encountered 
in /var/www/sites.d/site2/html/dokuwiki/inc/SimplePie.php on line 15343
```
Following fix will solve this issue as same as [patched](https://github.com/simplepie/simplepie/commit/1111dab1baced14aaf05509c41ee416c3fc6a961) in recent SimplePie v1.4.3 which is newer than v.1.3.1 of that current DokuWiki uses.
```
15343c15343
<                       $second = round($match[6] + $match[7] / pow(10, strlen($match[7])));
---
>                       $second = round((int)$match[6] + (int)$match[7] / pow(10, strlen($match[7])));
```

**Comment by Klap-in** [comment]
When updating SimplePie it is handy to consider moving to composer for this as well https://packagist.org/packages/simplepie/simplepie
