### ISSUE TITLE
monospaced text changes straight double quotes to left/right double quotation mark.

### ISSUE THREAD

**Issue by kjpluck** [splitbrain/dokuwiki#1802]
When placing code into `''monospace''` that includes double quotes docuwiki changes the quotes to left/right double quotation marks. This means when the code is copied from docuwiki and pasted into an editor all the quotation marks need replacing.

E.g. `foo="bar"` becomes `foo=“bar”`

**Comment by kjpluck** [comment]
I understand I can use codeblocks but this is useful for little code snippets inside a sentence.

**Comment by Klap-in** [comment]
In DokuWiki `''monospace''` syntax is really only applying a monospace text style. Nothing more. Therefore, the text in this monospace styled text is just interpreted as normal text. 

An alternative for using code or file block syntax, is modifying the behaviour of the monospace syntax with following plugin: https://www.dokuwiki.org/plugin:unformattedcode

**Comment by Klap-in** [comment]
Or just using:
`''%%foo="bar"%%''`  (see for more examples: https://github.com/splitbrain/dokuwiki/issues/941)

**Comment by kjpluck** [comment]
''%%foo="bar"%%'' does the trick but quite the cumbersome thing!

**Comment by kjpluck** [comment]
Sorry, hit the wrong button

**Comment by Chris--S** [comment]
As @Klap-in has pointed out this is by design and won't be altered.  There are other syntaxes for code.  A plugin could be developed to provide a monospace replacement which behaves as you would like.

**Comment by Klap-in** [comment]
That plugin does already exist: https://www.dokuwiki.org/plugin:unformattedcode
