### ISSUE TITLE
Access to raw post data and "always_populate_raw_post_data" setting in php.ini lead to problems in media manager

### ISSUE THREAD

**Issue by m4tze** [splitbrain/dokuwiki#1803]
Release 2016-06-26a "Elenor of Tsort"

When uploading a file (ajax.php), the post data is accessed via $HTTP_RAW_POST_DATA. This method is deprecated in php5.6 (will be removed in php7) and triggers an error message. This message prevents the ajax headers to be sent correctly which renders the upload impossible.

Hotfix: Set always_populate_raw_post_data = -1 in php.ini
Fix: Access post data via stdin as described in http://php.net/manual/en/wrappers.php.php

Kind regards
- M4tze

**Comment by Klap-in** [comment]
An issue with some background about this: https://github.com/splitbrain/dokuwiki/issues/1104

**Comment by splitbrain** [comment]
As I said in #1104 already. I can not find any references to $HTTP_RAW_POST_DATA in DokuWiki's code. @m4tze can you give any further hints where exactly in the code the problem occurs?

**Comment by splitbrain** [comment]
never mind. I just found we're not doing anything wrong. It's PHP being stupid. I'll add an explanation to #1104

**Comment by m4tze** [comment]
Well, "I just found we're not doing anything wrong" might be true so far. But, ... PHP prints this warning when receiving data that is not of type `application/x-www-form-urlencoded`. What you do is sending data of type `application/json`. This seems to be a problem.

The problem occurs in `wiki/lib/exe/ajax.php` in function `ajax_mediaupload`. The problem is, that the deprecation warning immediately sends headers and the content type cannot be changed anymore.

Even though you are not going/able to work around this problem (have you thought about using a custom error handler for `E_DEPRECATED` warnings?), you might mention it in your corresponding wiki/readme/whatever.

I personally fixed it with setting the ini value to -1 and I am fine with that. But it took some time to figure it out.

**Comment by Klap-in** [comment]
What about adding a release note that warns that php 5.6 requires this value added to the initial file?
