### ISSUE TITLE
path resolution broken on Windows Server 2012 R2

### ISSUE THREAD

**Issue by Mapel** [splitbrain/dokuwiki#1813]
I tried to install dokuwiki with WPN-XM server stack (needed it for restyaboard) on a Windows server. I got it working no problem on Windows Server 2008 R2, but on 2012 R2 I get the following error from php:

> Warning: require_once(C:\www\root/vendor/autoload.php): failed to open stream: No such file or directory in C:\www\root\inc\init.php on line 194
> 
> Fatal error: require_once(): Failed opening required 'C:\www\root/vendor/autoload.php' (include_path='.;C:\php\pear') in C:\www\root\inc\init.php on line 194

So as you see php is mixing slashs and blackslashes in the path.

I tried php 5.5, 5.6 and 7 and even tried another web server all together without any difference. My guess is that the fullpath()-function in init.php is the cause, but my php knowledge is not good enough to resolve it and I don't have enough time to investigate a lot further...

**Comment by splitbrain** [comment]
mixed slashes and backslashes do not matter. PHP's file methods will translate them internally. Make sure the files are actually all there (maybe a corrupt download) and they are accessible by the web server (I don't know about the permissions windows server uses).

**Comment by Mapel** [comment]
Thanks a lot for this fast reply.

You got me thinking and now I kinda feel stupid: the common source of the problem with all my tests on Windows Server 2012 R2 was the same dokuwiki-folder, which I always just copied.

After redownloading dokuwiki everything works again.
