### ISSUE TITLE
Memory leak in plugin installation?

### ISSUE THREAD

**Issue by BurninLeo** [splitbrain/dokuwiki#1815]
The issue is quite simple: When trying to install the dw2pdf plugin via extension manager -> search and install, I quickly receive the error message ["Elenor of Tsort"]

Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 49895088 bytes) in /<snip>/inc/HTTPClient.php on line 703

Of course, I could increase the memory. But 64 MB should be sufficient to install a plugin that is only 1,1 MB when downloaded directly. Unfortunately, installing the manually downloaded targ.gz file also fails and makes the plugin manager load and load.

**Comment by Klap-in** [comment]
The dw2pdf plugin is big. Bigger than 1.1MB, see also: https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/194
