### ISSUE TITLE
ODT export failing cause of missing Ziplib

### ISSUE THREAD

**Issue by LarsGit223** [splitbrain/dokuwiki#1818]
I am continuously getting build errors in Travis CI with the DokuWiki master branch. The Travis CI builds with "Elenor of Tsort" run through without any issues.

So I decided to download the latest snapshot and test it. When I try to export a page to ODT then I get a blank page. This is the error line from the Apache error log:
```
[Sat Feb 04 18:46:40.617515 2017] [:error] [pid 9661] [client 127.0.0.1:36658] PHP Warning:  require(/home/lars/public-html/dokuwiki/inc/ZipLib.class.php): failed to open stream: No such file or directory in /home/lars/public-html/dokuwiki/inc/load.php on line 107, referer: http://localhost/doku.php?id=start
[Sat Feb 04 18:46:40.617560 2017] [:error] [pid 9661] [client 127.0.0.1:36658] PHP Fatal error:  require(): Failed opening required '/home/lars/public-html/dokuwiki/inc/ZipLib.class.php' (include_path='.:/usr/share/php') in /home/lars/public-html/dokuwiki/inc/load.php on line 107, referer: http://localhost/doku.php?id=start
```

It seems like the file **ZipLib.class.php** is missing in sub-directory **inc**.

**Comment by Klap-in** [comment]
That is intentionally:
https://github.com/splitbrain/dokuwiki/commit/fa2c560da3df273672806893a2f660982c0011f0

See for devel docs: https://www.dokuwiki.org/devel:phparchive

**Comment by LarsGit223** [comment]
Thanks! Will check that and come back with questions, if any.

**Comment by LarsGit223** [comment]
A little question:
Is there a helper plugin or other code that handles the backwards compatibility to older DokuWiki versions?

No problem if not, then I will write a little helper on my own (But I better ask before doing unnecessary work that has already been done ;-) ).

**Comment by splitbrain** [comment]
> Is there a helper plugin or other code that handles the backwards compatibility to older DokuWiki versions?
> No problem if not, then I will write a little helper on my own

Please don't. There should be no reason to do so. The new library is
in place since two releases. Your plugin does not need to be
compatible with older releases.



-- 
splitbrain.org

**Comment by LarsGit223** [comment]
@splitbrain: Thanks, good to know.

I replaced the calls to the old ZipLib and everything is fine now. All Travis CI builds have been passed successfully.

Is there already a release date planned for "Frusterick Manners"? I think I should prepare a ODT release before this or at the same time.

**Comment by splitbrain** [comment]
> Is there already a release date planned for "Frusterick Manners"? I think I should prepare a ODT release before this or at the same time.

No date, yet. I actually wanted to write a post about that. But I can
do it here. I merged most outstanding PRs and integrated the (little)
feedback I got over the last weeks. There are only 3 PRs left:

https://github.com/splitbrain/dokuwiki/milestone/3

Two of them are waiting for feedback/changes from the original
submitters. One is my own where I need feedback/advice on how to
implement suggested changes.

None of them is super important, so I would like to get a release out
soon regardless of the state of these three. I'm thinking about maybe
one or two weeks?

I would really appreciate it if everyone could:

* check if their language is complete (translate.dokuwiki.org)
* try the current master branch in their live environment (gotta do
that next week at work, dokuwiki.org is already updated)
* let me know if there are any things that really really need fixing
before a release

Andi

-- 
splitbrain.org

**Comment by LarsGit223** [comment]
My little home installation looks fine so far, but that has not got much to say I think :-)
Only thing is that I gout blue icons on the admin page for some reason:

![dokuwiki-admin-blueicons](https://cloud.githubusercontent.com/assets/9009011/22628790/e4d846fc-ebda-11e6-9c01-754e3bf6925c.png)

But I guess that's just some kind of installation problem.

**Comment by LarsGit223** [comment]
Ok, just read in your weblog that the icons changed. So everything is fine.

**Comment by Klap-in** [comment]
The new 'php-archive' is there since August 2015 release. So the backward compatibility of the new solution is already quite well, I guesss.

**Comment by LarsGit223** [comment]
I agree, let's close this.
