### ISSUE TITLE
Add highlight code with HighlightJS

### ISSUE THREAD

**Issue by Kirill** [splitbrain/dokuwiki#1826]
Please add support to [highlightjs](https://highlightjs.org/) library. Geshi don't support unicode for writing own syntax with national character such Cyrillic. For example, https://highlightjs.org/static/demo/ first demo code with 1C on russian cyrillic language. Geshi have not changed. Not improving. Work to improve HighlightJS is now.

**Comment by splitbrain** [comment]
there's a geshi update in the works. replacing geshi with a client side implementation makes no sense and will break plugins relying on the backend rendered syntax highlighting (like pdf and odt exports)
