### ISSUE TITLE
Wrong ACL check in search(..., 'search_allpages', ...)?

### ISSUE THREAD

**Issue by LarsGit223** [splitbrain/dokuwiki#1851]
Hi,
I am currently trying to fix issue https://github.com/dokufreaks/plugin-task/issues/21 in plugin task. I examined the situation up to the following:
- I am logged in as user **'test'** who is a member of group **'testgroup'**
- The following pages exist:
  - tasks:bring_out_garbish
  - tasks:buy_a_birthday_present
  - tasks:do_homework
  - tasks:overview
  - tasks:watch_tv
- as issue 21 describes the problem is that the user **'test'** is not seeing the tasks listed in the overview (on page tasks:overview)
- BUT:
  - user test can access all pages under namespace **'tasks'** without problems
  - the task plugin just gets a list of the pages using search and is doing an ACL check itself

I noticed that not the ACL check in the task plugin is failing but the call to **search** is returning no pages at all! See file **helper.php** in the task plugin installation directory. In line **87-90** there is this function call:
```
        // returns the list of pages in the given namespace and it's subspaces
        $items = array();
        $opts = array();
        search($items, $dir, 'search_allpages', $opts);
```
The search returns no pages if user **'test'** is logged in. If the **admin** is logged in, all pages under namespace **'tasks'** are returned and the task overview works as it should. Then I changed the code to:
```
        // returns the list of pages in the given namespace and it's subspaces
        $items = array();
        $opts = array('skipacl'=>1);
        search($items, $dir, 'search_allpages', $opts);
```
And suddenly all pages/tasks were listed correctly for logged in user **'test'** also! That surprised me a bit because the **search/search_allpages** functions do a ACL check just like the task plugin itself is doing it later in **helper.php**:
```
        // add pages with comments to result
        $result = array();
        foreach ($items as $item) {
            $id   = ($ns ? $ns.':' : '').$item['id'];

            // skip if no permission
            $perm = auth_quickaclcheck($id);
            if ($perm < AUTH_READ) continue;
```
Then I found the difference:
- **search/search_allpages** seems to only do a ACL check on the page name **without** the namespace (this fails because I have a page tasks:watch_tv but no page watch_tv in the root directory of my wiki)
- the task plugin is adding the namespace to **$id** before calling **auth_quickaclcheck($id)**. See line ```$id   = ($ns ? $ns.':' : '').$item['id'];```, **$ns** hold the namespace of the page (**'tasks'** in our example)

**My question:**
This looks like an issue in the **search** function to me. Is this true or is there some _"in-depth"_ reason for this behaviour that the plugins have to know and work around it (like I did by disabling the ACL check)?

Thanks for your help in advance.

Kind regards,
Lars (LarsDW223)

**Comment by splitbrain** [comment]
That sounds weird. All the acl checks in all the search functions do their checks on the return of pathID() which gets filled with $file. What you describe would mean that $file is only the local file, not the one prefixed with the correct directory. That in turn would mean the whole search mechanism wouldn't work as intended. I don't say you're wrong, but I somehow doubt such a grave bug would not have been surfaced earlier (as opposed to a "simple" ACL check bug).

Please check how you're calling the search function. It's important that $base points the pages directory and you use $dir for whatever namespace you want to search in.

I don't have time to look into this right now. If it is a bug I would like to have it fixed immediately as Guy is preparing the release this weekend.  So it would be great if could invest further and open a PR if you can indeed confirm its generally broken.

**Comment by LarsGit223** [comment]
Ok, I will check the function call in the task plugin now.

**Comment by LarsGit223** [comment]
Thanks for the hint. The old code in the task plugin is wrong. It is not using the **$dir** parameter but instead it passed **.../pages:tasks** in **$base**.

So it is not a bug, works as it should if called correctly!
