### ISSUE TITLE
install.php gives fatal error for random_int without PHP 7

### ISSUE THREAD

**Issue by iainhallam** [splitbrain/dokuwiki#1852]
As per https://forum.dokuwiki.org/thread/14245, the latest stable release of DokuWiki (Frusterick Manners) gives a fatal error when trying to save from install.php:

    Fatal error: Call to undefined function random_int() in /var/www/public/inc/PassHash.class.php on line 630

`vendor/paragonie/random_compat/lib/random_int.php` is in-place, but it's not being found.

OS: Ubuntu 16.04 image from https://box.scotch.io/ containing PHP 5.6.

**Comment by yousong** [comment]
Same here

```
[yousong@sq1 dokuwiki]$ uname -a
Linux sq1 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[yousong@sq1 dokuwiki]$ php -v
PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
[yousong@sq1 dokuwiki]$ cat VERSION
2017-02-19 "Frusterick Manners"
```
