### ISSUE TITLE
It shows black popup when clicking anything after update to latest version(Frusterick Manners)

### ISSUE THREAD

**Issue by koshuang** [splitbrain/dokuwiki#1854]
After I upgrade to new version 2017-02-19, it always shows black popup. Does any have same issue? 

![_086](https://cloud.githubusercontent.com/assets/1978357/23114290/2afd5fc4-f779-11e6-9b73-7ecede4f55da.png)

**Comment by gamma** [comment]
I just installed the fresh version and did not have this problem. Can you post us some more information? Are there errors in the JS console, Did you try a hard re-load of the JS? Which plugins are installed?

**Comment by koshuang** [comment]
Hi @gamma,

I think I found the root cause. I was using `vector` template, and it works when I changed back to use `dokuwiki` template.

Thanks for your reply.

**Comment by dubcl** [comment]
Hi, I already use dokuwiki template and have the same problem, I test on firefox, chrome, iexplore on windows and Linux. I already clean cache from browser but the problem persist, any other idea how to fix?

**Comment by splitbrain** [comment]
As mentioned in the release notes, be sure to have an up-to-date gallery plugin (if you're using that plugin).

**Comment by laoyur** [comment]
@dubcl 
@splitbrain Hi, I still have the same problem after downloading and replacing gallery-plugin from https://github.com/splitbrain/dokuwiki-plugin-gallery/zipball/master

**Comment by laoyur** [comment]
@splitbrain sorry to bother, problem solved.
I deleted gallery folder and made a full refresh of wiki, and then reinstalled gallery in plugin manager.

**Comment by JW-IT** [comment]
manually updating the gallery plugin didn't solve it for me too.

so i did manually edit ''...../conf/local.php" and reset my template to dokuwiki ''$conf['template'] = 'dokuwiki';''
afterwards i could update all plugins and set my template to bootstrap3

hope that helps someone

**Comment by bernhardbrunner** [comment]
I had a similar problem, a last version of the odt broke the config dialog. Small problem if you can and know how to edit the local.conf by hand. But big problem for people who are not used to going to the shell.

So, I would like to propose the feature that the updater checks and warns of outdated plugins before starting the install.
