### ISSUE TITLE
2017-02-19a "Frusterick Manners" breaks config interface when odt plugin is installed

### ISSUE THREAD

**Issue by bernhardbrunner** [splitbrain/dokuwiki#1860]
History: 
* Updated system to Release 2017-02-19a "Frusterick Manners"
* Noted that ZipLib.class.php was deleted during the upgrade to 2017-02-19a

Symptoms: 
* Config interface not showing
* Webserver error log shows: [Tue Feb 21 20:28:50.199270 2017] [:error] [pid xxxx] [client xxxx] PHP Fatal error:  require_once(): Failed opening required '/var/www/xxx/inc/ZipLib.class.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/xxx/lib/plugins/odt/ODT/docHandler.php on line 16, referer: http://yyy.com/xxx/doku.php?id=start&do=admin

Immediate fix: 
* Remove lib/plugins/odt Plugin directory

**Comment by Klap-in** [comment]
Solution is to update the ODT plugin. Last release of that plugin exactly solved this issue.

https://github.com/LarsGit223/dokuwiki-plugin-odt/releases
https://www.dokuwiki.org/plugin:odt

**Comment by bernhardbrunner** [comment]
Thanks, good to know. Anyway, after 10+ years of working with DW, this was the first time that an upgrade broke something.
