### ISSUE TITLE
empty Initialization Vector error

### ISSUE THREAD

**Issue by farmascript** [splitbrain/dokuwiki#1861]
I'm using Release 2017-02-19a "Frusterick Manners". Works fine. When i use a 'fresh' browser (one that never have "seen" the dokuwiki) it works ok. After a few views of several (random) pages, on each page comes:

> Warning: openssl_encrypt() [function.openssl-encrypt]: Using an empty Initialization Vector (iv) is potentially insecure and not recommended in /home/content/yyy/xxxxxx/html/dokuwiki/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php on line 1017
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home/content/yyy/xxxxxx/html/dokuwiki/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php:1017) in /home/content/yyy/xxxxxx/html/dokuwiki/inc/auth.php on line 1233
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home/content/yyy/xxxxxx/html/dokuwiki/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php:1017) in /home/content/yyy/xxxxxx/html/dokuwiki/inc/actions.php on line 210
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home/content/yyy/xxxxxx/html/dokuwiki/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php:1017) in /home/content/yyy/xxxxx/html/dokuwiki/lib/tpl/dokuwiki/main.php on line 12

**Comment by splitbrain** [comment]
which php version are you using?

**Comment by farmascript** [comment]
PHP Version 5.3.24

**Comment by splitbrain** [comment]
This seems to be a bug in certain 5.3.x versions. PHP 5.3 is ancient, I would recommend upgrading to a newer version. It probably also fixes this problem.

**Comment by farmascript** [comment]
Thnx! I will try. GoDaddy says 5.3 id their default version. Also it didn(t give any problems with the eralier version of dokuwiki. Problems started when i updated the wiki to "Frusterick Manners"

**Comment by Klap-in** [comment]
For more background about outdated PHP versions see also:
http://www.freelists.org/post/dokuwiki/PHP-minimum-requirement-was-new-release
http://www.freelists.org/post/dokuwiki/new-release,9

**Comment by gregkuhnert** [comment]
Yes, this is an old PHP version. However, the root cause of the problem is the fact that the parameter to openssl_encrypt for IV is not provided, and you are therefore using the php default of a empty IV value. From a cryptography perspective, this does indeed make this easier to break, and therefore insecure as the error message stated. Just because later PHP versions do not display this error does not make this any less of a security concern that needs to be addressed...

**Comment by phy25** [comment]
@gregkuhnert This is more of an upstream issue (phpseclib/phpseclib#1087)... We have to fix from there.
