### ISSUE TITLE
Farm installation broken with 2017-02-19a

### ISSUE THREAD

**Issue by shoodle** [splitbrain/dokuwiki#1869]
Hosting installation with Apache 2.4.7 (Ubuntu) and PHP 5.5.9.

I made an update today from 2016-06-26a. Afterwards the animals in my (normal) farm installation are no longer available. There is nothing shown on the web pages. Also the website source code is just blank.

Rolling back to the old version.

**Comment by Klap-in** [comment]
Which template do you use? Did you had old plugins?

Did you catch anything in the log files that provide us guidance?

**Comment by shoodle** [comment]
All plugins were updated before and the template is just the standard DokuWiki Template.

Looking into the logs I see the following error several times:

> mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'There is no suitable CSPRNG installed on your system' ... in ... dokuwiki/vendor/paragonie/random_compat/lib/random.php:203,

**Comment by shoodle** [comment]
I searched for "CSPRNG" in the internet. This brought up also this link: https://community.contao.org/de/showthread.php?63170-Contao-4-2-no-suitable-CSPRNG-installed. According to the discussion therein I made an addition to my php configuration like this:
`open_basedir = "/dev/urandom:"`

This solved the problem. The farm animals are accessible also with the new version 2017-02-19a.
