### ISSUE TITLE
AuthAD SSO isn't working after upgrade to Frusterick Manners (2017-02-19a)

### ISSUE THREAD

**Issue by proxymus** [splitbrain/dokuwiki#1871]
Hello,

I've installed the upgrade today and now I've problems with the SSO. Users are still authenticated, but the authorization seems to be broken. They have no permissions anymore. The admin login is broken too.
I haven't change anything on the authad configuration. The debug isn't working or I don't no where I will find the debug log messages. What should I do to get it working again? Please let me know if you will need further information.

Thank you for help.

Kind regards
Proxymus

**Comment by proxymus** [comment]
When I use my user account as superuser instead of the AD group I can access the wiki normal. For me it looks as if the AD groups are not used or that they have a wrong format? 

**old config in the local.protected.php file**
`$conf['superuser'] = '@dokuwikiadmin';`

**workaround**
`$conf['superuser'] = 'username';`

**Comment by proxymus** [comment]
I think I've found the cause of the issue. I had to change the LDAP Port in the ../lib/plugins/authad/adLDAP/adLDAP.php file to 3268. 
I think that it would be better to configure the port within the local.protected.php file. What do yo think?

**Comment by splitbrain** [comment]
Hmm, I'm getting mixed infos here and am not sure what's going on:

* you say SSO doesn't work, but then say users are authenticated - please provide more info on your SSO setup
* you then mention that only groups seem not to work - please confirm if groups are found or not, use do=check
* you then say you fixed the problem by adjusting a port - if the port was wrong how did users authenticate in the first place?

**Comment by proxymus** [comment]
Hello,
I'm sorry for the confusion. 
I could see that the users are authenticated, but that they had no permissions, that's the reason that I had written that 
> AD groups are not used or that they have a wrong format.

![grafik](https://cloud.githubusercontent.com/assets/1539498/23456803/3c0e4ea6-fe75-11e6-98ac-f2e2e0603f32.png)

A do=check showed me that the groups could not be retrieved.
![grafik](https://cloud.githubusercontent.com/assets/1539498/23456646/9200120a-fe74-11e6-905f-beb4ada2c02d.png)
We use  security groups with universal scope for our dokuwiki users. Therefore I had to change the LDAP port in the adLDAP.php file otherwise the groups could not being retrieved.

I can share my SSO setup, but I think it isn't necessary anymore, because it is working when I change the LDAP port to **3268**. For me the problem is that the LDAP port is not configurable through the local.protected.php file. Any new Dokuwiki update will overwrite my changes.

**Comment by mprins** [comment]
AD can/may use different ports for different ldap traffic and the role the server has in the domain. see 
- https://technet.microsoft.com/en-us/library/dd772723(v=ws.10).aspx#Communication to Domain Controllers.
- https://technet.microsoft.com/en-us/library/cc978012.aspx

**Comment by Klap-in** [comment]
Is it working if you set `$conf["ad_port"]` in your `local.protected.php`?
I got the impression the plugin setting values are made available to the adldap constructor. And the constructor can set another port using the provided `$options["ad_port"]` option value.

**Comment by proxymus** [comment]
I've added the following line to my local.protected.php file:
>  9         $conf['ad_port'] = '3268';

and I've changed the values in the adLDAP.php file back to its defaults. 

> 73     /**
> 74     * The default port for LDAP non-SSL connections
> 75     */
> 76     const ADLDAP_LDAP_PORT = '389';
> 77     /**
> 78     * The default port for LDAPS SSL connections
> 79     */
> 80     const ADLDAP_LDAPS_PORT = '389';
> 81
> 82     /**

The result is, that the groups are not fetched.
![grafik](https://cloud.githubusercontent.com/assets/1539498/23501188/365e7cf6-ff33-11e6-95da-925c9cd347c1.png)

**Comment by Klap-in** [comment]
Hmmm. Sorry, wrong request from my side.
You have to use: `$conf['plugin']['authad']['ad_port']`
You could check it by looking in the Configuration Manager. It should appear somewhere there.

**Comment by proxymus** [comment]
I've tested it this way, but it isn't working.

**Comment by Klap-in** [comment]
Is this `ad_port` value passed to the `lib/plugins/authad/adLDAP/adLDAP.php` file?
Could you add some debug statements to check?
And in the function `_loadServerConfig()` to see if it is added to the $opts array?

**Comment by proxymus** [comment]
I've added a `print_r($opts)` to the _loadServerConfig() and the configured `$conf['plugin']['authldap']['port'] = 3268;` isn't in this array (I've tried it also with `$conf['plugin']['authad']['port'] = 3268;`. 

And I've added a ` print "Port: " . $adPort;` to the `public function setPort($adPort)` function. I can see that the configured value from the local.protected.php file isn't used. Instead the `const ADLDAP_LDAP_PORT = '389';` is used.

**Comment by Klap-in** [comment]
After reading your opening post again, I'm wondering what kind of settings (and their interpretation by authad plugin) could have changed between current and previous version of DokuWiki.
Could you share a (censored) copy of your configuration please?

Please note that adLDAP library looks for option with name `ad_port` and not `port`.
https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/authad/adLDAP/adLDAP.php#L591

**Comment by proxymus** [comment]
As I've started with SSO I've changed the port in the adLDAP.php to 3268, because I didn't find a working configuration parameter.

>https://www.dokuwiki.org/plugin:authad
> If you have an organisation with multiple DCs under a single parent, you may need to connect to port >3268, rather than the default port 389. Otherwise, users from the remote DC may not show up as >members of any groups. The easiest way to do this is to change adLDAP.php in the source code, because >the base call to ldap_connect needs port as a separate argument (line 364 in inc/adLDAP.php version 3.3.2). 

The Dokuwiki upgrade has overwritten the change I've made and I didn't remember that I've done change in the past. The result was the not working authentication, because our groups couldn't be retrieved.

As you've mentioned I've changed `port` to `ad_port` in the local.protected.php file. This parameter is passed to the adLDAP.php file. I think that the documentation needs an update.
Thank you all for your help to find the right configuration parameter.

**Comment by splitbrain** [comment]
please update the documentation accordingly.

**Comment by proxymus** [comment]
Done!
