### ISSUE TITLE
Deleted files list misses some files

### ISSUE THREAD

**Issue by jpameli** [splitbrain/dokuwiki#1874]
Hi I compared the old stable with current stable and it seems like some more files where deleted inside inc/phpseclib folder. Maybe we need to fix this inside deleted files list (https://raw.githubusercontent.com/splitbrain/dokuwiki/stable/data/deleted.files). Regards!

**Comment by bug** [comment]
Which files are missing for you?

**Comment by jpameli** [comment]
I think the complete folder should be deleted, because it is not there anymore in newest version, this include this missing files which are not mentioned in the deleted files list:

> Crypt_Base.php
Crypt_Hash.php
LICENSE
Math_BigInteger.php

**Comment by bug** [comment]
You're right, git recognized the files content:

    rename {inc => vendor/phpseclib}/phpseclib/LICENSE (89%)
    rename inc/phpseclib/Crypt_Base.php => vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php (58%)
    rename inc/phpseclib/Crypt_Hash.php => vendor/phpseclib/phpseclib/phpseclib/Crypt/Hash.php (79%)
    rename inc/phpseclib/Math_BigInteger.php => vendor/phpseclib/phpseclib/phpseclib/Math/BigInteger.php (66%)

but practically the old inc/phpseclib/ directory has gone. Thanks for the notice.

Commit 4074bbe
