### ISSUE TITLE
Compatibility info '2017-02-19a "Frusterick Manners"' is not shown at dokuwiki.org

### ISSUE THREAD

**Issue by LarsGit223** [splitbrain/dokuwiki#1876]
I added the compatibility info ```2017-02-19a "Frusterick Manners"``` to the ODT plugin page but after saving it was not displayed. Checked again and yes - everything is fine, the change was saved. But it is not displayed.

I thought the problem would be in ```dokuwiki-plugin-pluginrepo```. But there I found lines like this:
```
$this->getConf('releases')
```
So I assume you only have to adjust the config of dokuwiki.org to fix this?

**Comment by splitbrain** [comment]
fixed
