### ISSUE TITLE
PHP Fatal error:  Call to undefined function random_bytes()

### ISSUE THREAD

**Issue by iiipgciii** [splitbrain/dokuwiki#1881]
I just updated to the newest version of Dokuwiki.  It worked for a day, and now when try to login I get a 500 error.  My apache log shows:

[Fri Feb 24 16:15:59.980384 2017] [:error] [pid 1169] [client 192.168.1.28:55317] PHP Fatal error:  Call to undefined function random_bytes() in /var/www/html/dokuwiki/inc/auth.php on line 333, referer: http://IP/dokuwiki/doku.php

running PHP v7.0.3
Ubuntu 14.04.5

**Comment by splitbrain** [comment]
random_bytes is a PHP 7 function that should be available if you're really running 7.0.3 http://php.net/manual/en/function.random-bytes.php

Otherwise it's provided by phpseclib in vendor. Since you say it worked for a day, then stopped, I assume something in your server setup changed.

**Comment by arnost00** [comment]
I think in first day, he was logged from update session.

**Comment by hv15** [comment]
Does this then mean that users using <PHP7 need to install phpseclib?

**Comment by splitbrain** [comment]
phpseclib is included with DokuWiki.

**Comment by hv15** [comment]
Ah I see, well I'm running Dokuwiki with the following setup:

```sh
$ httpd -v
Server version: Apache/2.2.15 (Unix)
Server built:   Jan 12 2017 17:09:39
```
```sh
$ php --version
PHP 5.6.30 (cli) (built: Jan 19 2017 10:06:11)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

I have no administrative rights over the system from which dokuwiki runs. The error I get from Dokuwiki is the same as @iiipgciii. Is there any more information I can provide?

**Comment by splitbrain** [comment]
Is this still an issue?

**Comment by iiipgciii** [comment]
No, all good.  Thanks

Paul Como
