### ISSUE TITLE
Change name of security.png to something more descriptive?

### ISSUE THREAD

**Issue by RJWoodhead** [splitbrain/dokuwiki#1889]
In the process of checking my logs after upgrading to Frusterick, I saw the access attempts to security.png, then wasted 10 minutes trying to figure out what was "wrong" with my configuration.

Multiply my 10 minutes by a few thousand casual dokuwiki users and it's a serious time sink, not to mention it means less space in my brain for important data like Star Trek trivia.

Might I suggest that `security.png` be renamed to something self-descriptive, like:

`dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.png`

Best, Robert

**Comment by splitbrain** [comment]
Good idea. Maybe we can come up with something shorter though. Maybe ``all_fine-google_XRFTGH.png`` and we set up some page with the term XRFTGH (or whatever unique string we can come up) with some more info?

**Comment by RJWoodhead** [comment]
Given that it's only a few tens of bytes and it only actually gets fetched during updates, better to go longer and eliminate the time-sink of googling. This is all about being immediately obvious to stupid meatbags, and one should not underestimate how clueless we can be, especially when insufficiently caffeinated or on days that end in 'y'.

Also, if you google `dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.png` this thread already comes up as the first response, so *Mission Accomplished*.

Bonus points if the contents of the png are something like this:

![panic](https://cloud.githubusercontent.com/assets/10821401/23675712/31fe1216-0348-11e7-9592-613f18c9ab91.png)

**Comment by DeathCamel57** [comment]
Does #2179 suffice @RJWoodhead?

**Comment by RJWoodhead** [comment]
Hahaha... sure does!

**Comment by DeathCamel57** [comment]
I didn't feel like going for the bonus points for the custom picture haha

**Comment by RJWoodhead** [comment]
Not everyone is a HHGTTG fan, I guess... :)
