### ISSUE TITLE
There is no suitable CSPRNG installed on your system - more info when install/upgrade ?

### ISSUE THREAD

**Issue by arnost00** [splitbrain/dokuwiki#1892]
New version of dokuwiki (Frusterick Manners")
And after update I cannot login.
I try new install, and I cannot install it.

Only what I found was info in apache log :
Uncaught exception 'Exception' with message 'There is no suitable CSPRNG installed on your system'  ...

Which came with this issues: https://github.com/splitbrain/dokuwiki/issues/1760 and https://github.com/splitbrain/dokuwiki/pull/1761

Why is there any test when install new dokuwiki ?
And maybe some warning in release notes for upgrade ?

**Comment by tmugford** [comment]
@arnost00 You might want to take a look at #1869. As described, adding `/dev/urandom` to the `open_basedir` path resolved the issue for me.

**Comment by splitbrain** [comment]
I'm leaving this open because it might be a good idea to check for this in the installer.

**Comment by wiebeytec** [comment]
This just bit me. Luckily I saw it, and found this issue. 

I'm not sure how to test for it, though. The official upgrade instructions are just untarring (there is no installer), so the warning needs to be visible on the site, and to all users, because the admin can't log in to see anything...

**Comment by splitbrain** [comment]
`/dev/urandom` is the standard source of entropy used in crypto mechanisms on Linux systems. `open_basedir` restricts PHP to only access certain paths. PHP needs to be able access `/dev/urandom` for reading or it can not create secure passwords, cookies, etc. There's nothing to argue about. It's basically a misconfiguration your provider's side. If a provider denies your PHP applications access to read from `/dev/urandom` you should switch providers - your setup is not secure then.

**Comment by valscion** [comment]
Thank you! Your answer is really great :+1:

**Comment by oliversl** [comment]
Please be aware that your plain text password is printed in the apache ssl_error log file. Can we avoid printing plain text password on system level log file? Should I create a new ticket? Thanks
