### ISSUE TITLE
XML-RPC server  - synchronize wiki 

### ISSUE THREAD

**Issue by RottenRonnie** [splitbrain/dokuwiki#1895]
I've got XMLRPC enabled on the remote server, and it used to work fine until post upgrade.

I now get an error message when selecting a profile:

    Failed to talk to remote wiki. Make sure the remote wiki allows XMLRPC requests and that you set up the endpoint URL correctly. parse error. not well formed

I navigated to the XMLRPC URL https://mysite.com/lib/exe/xmlrpc.php and got this error message:
Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /home/mysite/public_html/dokuwiki/lib/exe/xmlrpc.php on line 7

I edited line 7 of the file and commented it out for testing, and the sync worked perfectly.
`//if(!$conf['remote']) die((new IXR_Error(-32605, "XML-RPC server not enabled."))->getXml());`

**Comment by phy25** [comment]
What's your PHP version? Seems like a compatibility issue.

**Comment by Klap-in** [comment]
It seems to be not possible to call a method on an object just created with new before PHP 5.4. While the requirements of DokuWiki are PHP version 5.3.4 or later.

Introduced by: https://github.com/splitbrain/dokuwiki/pull/1704

**Comment by RottenRonnie** [comment]
That would do it. Im hosted on a legacy server running 5.3.

With that line commented out I've been able to sync local to remote again.

**Comment by annda** [comment]
I think this should be closed since the minimum required PHP version is 5.6.

**Comment by RottenRonnie** [comment]
They upgraded the PHP version on the server, so this can be closed. 
Thank you.
