### ISSUE TITLE
Feature Request: Gchart get $data from Doodle3

### ISSUE THREAD

**Issue by siggi11** [splitbrain/dokuwiki#1925]
is it possible to extend gchart systax around access to a specific doddle3-data ? ... they would be a dream-team and would give us a great benefit...

Intention: watch (only) doodle-titel; the questions an their results....  a kind "overview"... on (the same) or a different page(s) as a chart,

Usage:   `<gchart [option] ...[new Option: "doodle"] > doodle-Titel.doodle </gchart>`   
Because: All doodle's data is saved in <dokuwiki>/data/meta/title_of_vote.doodle. The filename is the (masked) title. So the filename should be to enough. Option "doodle": read data from file

Datamapping (doodle  -   gchart):
`titel (= Filename)                           =    titel-value (option titel)` 
`"* Option 1" value (full as given)   =    name of the pair "name=value` 
`"column Option 1 RESULT"           =    value of the pair "name=value`    
`"* Option n ...                                 =    dto n-name `
`"column Option n RESULT"           =    dto n-value `

Maybe doodle option like "Option 2 **some wikimarkup** \\ is __allowed__!" cause problems...but i don't need it realy. Nice to have...

Example doodel overview as HBar:

![doodlegchart](https://cloud.githubusercontent.com/assets/7629603/24149589/568bc442-0e43-11e7-91c9-b8509d785ecb.png)

P.s.
Hmmm... maybe a own color for each bar? ..cause it's stronger... yes (green), no (red), whatever...

That would be nice !!!! :-)

**Comment by mprins** [comment]
You probably want to whoever maintains the doodle plugin and or gchart plugin
