### ISSUE TITLE
Wrong example in "/lib/plugins/authldap/lang/en/settings.php"

### ISSUE THREAD

**Issue by kazh98** [splitbrain/dokuwiki#1926]
At the line 7 of "/lib/plugins/authldap/lang/en/settings.php",
```php
$lang['groupfilter'] = 'LDAP filter to search for groups. Eg. <code>(&amp;(objectClass=posixGroup)(|(gidNumber=%{gid})(memberUID=%{user})))</code>';
```
`uid` variable is denoted by `%{user}` in the example, but I think it is correctly `%{uid}`.

**Comment by phy25** [comment]
Not quite sure about this since https://www.dokuwiki.org/plugin:authldap#plugin_configuration_settings has conflicting syntax as well. I assume this uid and user attribute names are based on results returned by LDAP?

**Comment by splitbrain** [comment]
The example is correct. The user filter has only `%{user}` available, once that has been resolved to a user entry, `%{uid} ` is available.

**Comment by kazh98** [comment]
Thank you for confirming my issue and for giving me a kind explanation.
