### ISSUE TITLE
self-closing script tags not handled correctly in template.php

### ISSUE THREAD

**Issue by chchch** [splitbrain/dokuwiki#1927]
line 453-454:
```
if(isset($attr['_data']) || $tag == 'script') {
    if($tag == 'script' && $attr['_data'])
```
throws a notice if the "_data" field is not set (as in the Codemirror plugin). It would perhaps be better to do something like this:

```
if(isset($attr['_data']) || $tag == 'script') {
    echo '>';
    if($tag == 'script' && isset($attr['_data'])) {
        $attr['_data'] = "/*<![CDATA[*/".$attr['_data']."\n/*!]]>*/";
        echo $attr['_data'];
    }
    echo '</', $tag, '>';
 } else {
    echo '/>';
```

**Comment by splitbrain** [comment]
self closing script tags are not a thing. See http://stackoverflow.com/a/28719226/172068

**Comment by chchch** [comment]
Yes sorry the title of my post was wrong -- it's the logic that puts a closing script tag that throws a notice. If the script tag is empty, i.e. the data attribute is not set, it throws a Notice.

- Charles

On March 27, 2017 8:23:47 PM GMT+01:00, Andreas Gohr <notifications@github.com> wrote:
>self closing script tags are not a thing. See
>http://stackoverflow.com/a/28719226/172068
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/splitbrain/dokuwiki/issues/1927#issuecomment-289558103

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
