### ISSUE TITLE
Lost in cache documentation

### ISSUE THREAD

**Issue by gsurrel** [splitbrain/dokuwiki#1946]
This issue is linked to my misunderstanding of the documentation about caching. Maybe my issue can be helpful for updating the docs.

I am contributing to a plugin and I am facing a problem: it dynamically loads data from a remote server but the page using the plugin stays still. I cannot afford `~~NOCACHE~~` as the remote content changes at a very low frequency (less than once a day) and I can hammer that server for every request.

I have read the DokuWiki pages related to cache [Caching](https://www.dokuwiki.org/devel:caching) & [PARSER_CACHE_USE](https://www.dokuwiki.org/devel:event:parser_cache_use) as well as some [specific source code](https://github.com/samuelet/indexmenu/blob/2f40fa871af02db9c14dbf2ee97e67285bdc2b00/action.php#L57-L99) but I do not understand how to use it.

My question is the following: what is needed to force the rendering of the page according to the [cachetime](https://www.dokuwiki.org/config:cachetime) setting? And if it does, how can I debug this caching problem?

(Clearing the instruction cache updates the page as expected)

**Comment by splitbrain** [comment]
There is absolutely nothing you need to do. Pages are automatically rerendered when cachetime has reached for that page. Note that only the second stage cache (the rendering step) is refreshed after cache time.

BTW. "How to do X" questions are much better suited for the mailing list or user forum and will probably answered faster there.
