### ISSUE TITLE
XMLRPC does not work anymore since Release “Frusterick Manners”

### ISSUE THREAD

**Issue by NDee303** [splitbrain/dokuwiki#1947]
Since the last update the XML-RPC API does´nt work anymore.  With "Elenor of Tsort" everything was working fine.

For example the following Request gets an "500 internal Server Error" in the REST-Client and the ssl_access.log shows "POST /dokuwiki/lib/exe/xmlrpc.php HTTP/1.1" 500 - "-" too

```
<methodCall>
 <methodName>wiki.getPage</methodName>
 <params>
 <param>
 <value>    
 <string>bookmarks</string>
 </value>
 </param>
 </params>
 </methodCall>
```

- Linux version 2.6.32-573.22.1.el6.x86_64 (mockbuild @ x86-029.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) # 1 SMP Thu Mar 17 03:23:39 EDT 2016
- Apache/2.2.15 (Red Hat) DAV/2 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips PHP/5.3.3
- Dokuwiki Release 2017-02-19b “Frusterick Manners”

**Comment by smhaller** [comment]
same here: not working with
 * Dokuwiki: 2017-02-19b "Frusterick Manners"
 * Apache/2.2.15
 * PHP 5.3.3
but working with e.g.:
 * an older Dokuwiki Version

**Comment by smhaller** [comment]
quick fix:
in lib/exe/xmlrpc.php

change line 7 to:
```
if(!$conf['remote']){
        $IXRErr =  new IXR_Error(-32605, "XML-RPC server not enabled."); 
        die($IXRErr->getXml());
}
```
</code>

The short version: 

`if(!$conf['remote']) die((new IXR_Error(-32605, "XML-RPC server not enabled."))->getXml());`

can only be used in PHP 5.4 and later.

**Comment by splitbrain** [comment]
@smhaller thanks for figuring this out. I recommend to upgrade to a newer PHP release.

**Comment by NDee303** [comment]
I've seen on dokuwiki.org that the requirements have been recently adjusted on php 5.6. minimum. So we will update this shortly and test. If it works with php 5.6 than a non-functionality under php 5.3.3 would not be a bug in my opinion.

**Comment by NDee303** [comment]
@smhaller : I just tried your workaround/fix and it works perfekt. thx

**Comment by sheesupport** [comment]
Some platforms where dokuwiki runs (like here) have a long support window. Like the initial reporting by NDee303 shows - the used platform (e.g. os/php/httpd) have support for PHP 5.3 at least until 2020 (RHEL/CentOS6). So, for the enterprise usage it would be make sense to provide a hotfix release for "Frusterick Manners" - at least I would appreciate it, thanks!


```
--- dokuwiki-2017-02-19e/lib/exe/xmlrpc.php  2017-05-13 18:50:04.463008471 +0200
+++ dokuwiki-2017-02-19e/lib/exe/xmlrpc.php  2018-05-25 19:13:16.507941703 +0200
@@ -4,7 +4,10 @@
 require_once(DOKU_INC.'inc/init.php');
 session_write_close();  //close session
 
-if(!$conf['remote']) die((new IXR_Error(-32605, "XML-RPC server not enabled."))->getXml());
+if(!$conf['remote']){
+    $IXRErr = new IXR_Error(-32605, "XML-RPC server not enabled.");
+    die($IXRErr->getXml());
+}
 
 /**
  * Contains needed wrapper functions and registers all available
```

**Comment by phy25** [comment]
I would close this because the mentioned PHP version is not supported by newer DokuWiki anymore, but anyone that needs it to work can patch the code manually.
