### ISSUE TITLE
update from dokuwiki-2015-08-10a to dokuwiki-2017-02-19b  = ZipLib missing 

### ISSUE THREAD

**Issue by Vegge** [splitbrain/dokuwiki#1948]
after updating from dokuwiki-2015-08-10a  TO dokuwiki-2017-02-19b  

config page was not working at all... log showed : 

[Tue Apr 11 15:57:42.003406 2017] [:error] [pid 26831:tid 25] [client ...] PHP Warning:  require_once(/users2/webmaster/WEB_GRM/dokuwiki-2017-02-19b/inc/ZipLib.class.php): failed to open stream: No such file or directory in /users2/webmaster/WEB_GRM/dokuwiki-2017-02-19b/lib/plugins/odt/renderer.php on line 20, referer: https://www.grm.polymtl.ca/wiki/doku.php?id=start&do=admin

ZipLib was missing because it was in the deletes files !

I copied it back from dokuwiki-2015-08-10a/inc and the page combe back right away.

**Comment by splitbrain** [comment]
you should upgrade the odt plugin instead.
