### ISSUE TITLE
New plugin: Pull-down menues for filtering datatable

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [splitbrain/dokuwiki#1950]
When using the function "datatable" of the data plugin it would be nice to have a possibility to define filters as dropdown menu like the [tagfilter plugin](https://www.dokuwiki.org/plugin:tagfilter)

Best regards 
Juergen

**Comment by phy25** [comment]
I think you should submit this to https://github.com/splitbrain/dokuwiki-plugin-data
