### ISSUE TITLE
Support wildcards or regex in ACL

### ISSUE THREAD

**Issue by iainhallam** [splitbrain/dokuwiki#1957]
I'd like to grant access to users to edit certain pages wherever they occur in the same structure anywhere in the site, so as well as using the %USER% wildcard, I'd like to be able to specify some kind of pattern matching in the ACL specification. It would be ideal if this were based on regular expressions to give maximum flexibility.

In my current use case, I'd like users to be able to update a reply to an event, so would want something like:

    ns1:ns2:events:/[0-9]{10,}:/:%USER%    %USER%    2

(I'm using Unix timestamps at the moment for event IDs.)

**Comment by splitbrain** [comment]
I will not add this to the core. However it should be possible to implement something like that through an action plugin.

**Comment by iainhallam** [comment]
For anyone interested, I've now written a plugin for this:

https://www.dokuwiki.org/plugin:aclregex
