### ISSUE TITLE
A different approach for multiple wiki instances using env variables over farms

### ISSUE THREAD

**Issue by spaeps** [splitbrain/dokuwiki#1974]
I had recently the need for setting **multiple wiki instances** on the same web server using **virtual hosts** and I discovered the **farms** approach.

I would like to propose the introduction of another approach based on **environmental variables** as other engines do.

As an example, in **NextCloud** or **RoundCubeMail** serving multiple istances using the same engine is done by defining [**NEXTCLOUD_CONFIG_DIR**](https://github.com/nextcloud/server/commit/cc8b50898768805f4e3b2e91bc9346db831a08bc) and [**RCUBE_CONFIG_PATH**](https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_config.php#L62) respectively, so the engine can check em with [**getenv()**](http://php.net/manual/en/function.getenv.php) and use them if defined. **That's all**.

This could be surely achieved in DokuWiki too by letting the engine check for **DOKU_CONF** overriding its default value. _Optionally_ it could be needed a new **DOKU_DATA** variable introduction too for forcing, when defined, a custom path for **$conf['savedir']**.

IMHO, this could be implemented in multiple steps and options:
1. Call **getenv('DOKU_CONF')** [before defining it](https://github.com/splitbrain/dokuwiki/blob/master/inc/init.php#L32) and optionally overwrite [$conf['savedir']](https://github.com/splitbrain/dokuwiki/blob/master/inc/init.php#L257) by calling **getenv('DOKU_DATA')** as a replacement in **inc/init.php**.
2. Let the **installer** be aware of the two paths: **DOKU_CONF** would be redefined when [requiring **inc/init.php**](https://github.com/splitbrain/dokuwiki/blob/master/install.php#L13) in **install.php**, while the **savedir** variable should be defined **at installation time** by the user or, optionally a **DOKU_DATA** should be explicitly checked when [checking permissions](https://github.com/splitbrain/dokuwiki/blob/master/install.php#L509).

Alternatively, a solution could just be _suggested_ as a commented code implemented in **inc/preload.php.dist**, but the ability of setting the savedir at installation time would be required; also, the **inc/init.php** requirement in **install.php** should be called **before** defining **DOKU_CONF** in the first lines.

The whole solution would let every instance being really independent and well separated without touching a line of code (**preload.php**), so each one can have its custom and not hierarchical path for data and conf, and its installation procedure.
Also this would not affect the other method based on farms.

I didn't implement a patch yet since I would like to know if it would be any intention of adopting the solution.

If I got something wrong in my analysis please forgive me ;) and let me know.

**Comment by splitbrain** [comment]
As you said, this could easily be implemented in inc/preload.php However keep in mind that additional configuration may be needed to make the envirnoment variable available within PHP. At least certain SAPI versions will not import all environment variables into the php process.

PS: the easiest version for a farm setup is probably the farmer plugin.
