### ISSUE TITLE
Replace Doku_Form with \dokuwiki\Form\Form

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#1981]
It would be desirable to get rid of the old form mechanism some day. A first step would be replacing it wherever it used in core. However there are lots of plugins relying on the ``HTML_*FORM_OUTPUT`` events which pass a ``Doku_Form``.

The way I envision this to be implemented is to have a method to optionally convert a `Form\Form` to a `Doku_Form`. This would mean that all elements not supported in `Doku_Form` would simply be converted to HTML.

Core would trigger a new event passing a `Form\Form` to all plugins handling the new event. Next core would check if there are any plugins registered for the old event and would then convert the `Form\Form` to a `Doku_Form` which is passed on to the legacy plugins.

`Doku_Form` and this special handling of legacy events would be marked as deprecated and be removed in the future.

**Comment by Klap-in** [comment]
#3198 implements new events which give the new Forms. 
The old events are not triggered anymore in the coming release.

See also the blog at https://www.patreon.com/posts/better-forms-58551930 and the spreadsheet tracking the progress: https://docs.google.com/spreadsheets/d/193e-wrgej6DGqKQxcsghEbMR4OmQtDUmnmp9cfjF07o/edit?usp=sharing
