### ISSUE TITLE
Debian/Ubuntu package

### ISSUE THREAD

**Issue by nucfisher** [splitbrain/dokuwiki#1986]
Update Debian/Ubuntu packages regularly.
Make package install/upgrade the main path.

**Comment by splitbrain** [comment]
The Debian package is not maintained by us. Debian takes it's own approach to dependencies and path layout which creates a whole bunch of work.

**Comment by Klap-in** [comment]
Please see for upgrading details also https://wiki.debian.org/DokuWiki
or https://tracker.debian.org/pkg/dokuwiki

**Comment by intensite** [comment]
For Debian Stretch what is the recommended way to Install Dokuwiki?
Since it looks like the package is no longer provided by Debian,  can you provide with a replacement package?
