### ISSUE TITLE
double hyphen converted to emdash within code tags. 

### ISSUE THREAD

**Issue by edgreenberg** [splitbrain/dokuwiki#1989]
Within a code block or code text, double hyphen is being converted to em-dash.  This means that the reader cannot copy commands out of the page and into the command window. 

Example:
```
ansible-playbook playbookname --limit=foo.bar
```
is rendered with a unicode em-dash before limit.

**Comment by mszkb** [comment]
You could try %%--limit=foo.bar%%.

https://www.dokuwiki.org/faq:quoting

I tested the code block in a clean installation and the dashes do not change into a em-dash. Do you use some rendering plugins?



![selection_360](https://cloud.githubusercontent.com/assets/10475327/26518821/6172cd02-42b8-11e7-8b4f-0f08a670ab4f.jpg)

**Comment by mszkb** [comment]
Converting reason: [HTML conversion](https://www.dokuwiki.org/wiki:syntax#text_to_html_conversions)
You could try to disable the conversion in the [configurtion](https://www.dokuwiki.org/config%3Atypography).

Use it with caution. It would have an affect on all of your pages

**Comment by edgreenberg** [comment]
When I get to work on Monday I will play with this further. I will let you know how it comes out.

On May 27, 2017 2:51:12 AM EDT, MSZ <notifications@github.com> wrote:
>Converting reason: [HTML
>conversion](https://www.dokuwiki.org/wiki:syntax#text_to_html_conversions)
>You could try to disable the conversion in the
>[configurtion](https://www.dokuwiki.org/config%3Atypography).
>
>Use it with caution. It would have an affect on all of your pages
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/splitbrain/dokuwiki/issues/1989#issuecomment-304432964

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Klap-in** [comment]
This suggests that html conversions have priority above the `<code>` syntax. But testing this on dokuwiki.org doesn't reproduce the situation...

https://www.dokuwiki.org/playground:htmlconversationcode
