### ISSUE TITLE
Media Manager: Make old revisions of (binary) files directly downloadable from "view" tab

### ISSUE THREAD

**Issue by fthommen** [splitbrain/dokuwiki#1990]
HI,

when browsing the revision history of (binary) files in the media manager, the "view" tab seems to offer a link to this older version:

![dw_mediamanger_binary_oldrevision_view](https://cloud.githubusercontent.com/assets/279232/26497744/da4f9de0-422c-11e7-9d8c-52491204d2bc.png)

In reality despite the seemingly clear date, the link still goes to the current revision of the file.  IMHO in this situation the link should point to the old revision to give the opportunity do directly download this specific version.

It looks like older revision of (binary) media files can only be downloaded from the History -> Compare view, which is ok, but only as an _additional_ download possibility.  Download of older revisions should be possible w/o comparing them first ;-)

frank

**Comment by splitbrain** [comment]
has been fixed a while ago in #2155
