### ISSUE TITLE
HTML ordered list not displaying correctly

### ISSUE THREAD

**Issue by Rabun0510** [splitbrain/dokuwiki#1995]
I am using HTML to duplicate code from Visual Studio. To show the line numbers, an `<ol>` tag is used. Dokuwiki does not display the numbers, although the exact same HTML works correctly in a browser...

### Correct display as per browser
![correct](https://cloud.githubusercontent.com/assets/9697661/26631684/7c04586e-460c-11e7-8d55-bd4ecef885cd.jpg)

### Incorrect display in DokuWiki
![incorrect](https://cloud.githubusercontent.com/assets/9697661/26631674/74133774-460c-11e7-8da5-3b728be64d85.jpg)

I downloaded the newest DokuWiki version but it still did not fix it. Is there something you could do about it?

**Comment by Klap-in** [comment]
I have no clue how you did this in Dokuwiki.
Could you share the steps to reproduce this?

(another solution: maybe this pull request in progress could become a solution for your task? https://github.com/splitbrain/dokuwiki/pull/1985 )

**Comment by Rabun0510** [comment]
I'm using the bootstrap3 template. Where can I check to see the default behaviour with ordered lists?
