### ISSUE TITLE
Bootstrap3 template - ol display issue

### ISSUE THREAD

**Issue by Rabun0510** [splitbrain/dokuwiki#1996]
I am using html to display an ordered list. In the bootstrap3 theme, the numbers for the list are not displayed. 

### Sample code
```
<html>
<div style="border: #000080 1px solid; color: #000; font-family: Consolas, 'Courier New', Courier, Monospace; font-size: 10pt">
<div style="background: #f3f3f3; color: #000000; overflow: auto">
<ol start="1" style="background: #ffffff; margin: 0 0 0 4em; padding: 0;">
<li><span style="color:#0000ff">function</span> zoomend() {</li>
<li>&#160;&#160;&#160;&#160;<span style="color:#0000ff">if</span> (zoomInitiated) {</li>
<li>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;console.log(<span style="color:#a31515">&quot;Zoom ended&quot;</span>);</li>
<li>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;zoomInitiated = <span style="color:#0000ff">false</span>;</li>
<li>&#160;&#160;&#160;&#160;}</li>
<li>}</li>
</ol>
</div>
</div>
</html> 
```
### Output
![incorrect](https://cloud.githubusercontent.com/assets/9697661/26631674/74133774-460c-11e7-8da5-3b728be64d85.jpg)

I inspected the item in the web browser and found the following style setting to be the culprit:
![list style error](https://cloud.githubusercontent.com/assets/9697661/26670773/410685b4-46b3-11e7-9b0e-690a31b865aa.jpg)

When I change this style setting to visible, the numbers are displayed correctly. I was unable to find this in the .css files. Can someone please advise on how I can remove this setting?

**Comment by Klap-in** [comment]
You can (temporary!) enabling the debug configuration setting. This will disable compressing of the comments in the joined css files, so you could find back the original file in the joined file.

**Comment by Klap-in** [comment]
Also you could search the files of your installation for this specific text. 

https://github.com/LotarProject/dokuwiki-template-bootstrap3/search?utf8=%E2%9C%93&q=fix-media-list-overlap&type=

**Comment by Rabun0510** [comment]
Ah yes, thank you so much! I found it and just changed the code where the <ol> tag is classed as fix-media-list-overlap.
