### ISSUE TITLE
Media Manager Upload's button

### ISSUE THREAD

**Issue by elassabe** [splitbrain/dokuwiki#1998]
The Media Manager Upload button to put files on this page will not stop. Ideas of the problem?

**Comment by elassabe** [comment]
![upload capt](https://cloud.githubusercontent.com/assets/29043333/26730014/d9658ba0-47af-11e7-97c7-911568e878d8.PNG)
This one... And I click and nothing 's happening

**Comment by Klap-in** [comment]
You have selected first the files?

**Comment by elassabe** [comment]
Yes and the button doesn't working

**Comment by elassabe** [comment]
And I think the problem comes in the jQuery code

**Comment by splitbrain** [comment]
Thanks for opening the issue. Unfortunately your issue does not contain enough information. Please try to provide as much info as possible, generally following these three main questions:

* What did you do?
* What did you expect to happen?
* What happened instead?

Your issue should contain everything that might help in analyzing and reproducing the issue. That includes but isn't limited to:

* versions of the involved software
* exact error messages
* debug logs (also check your JavaScript console for web related issues)

Thanks for your help.

PS: You may want to refer to [How to Ask Questions the Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) for more tips on improving your issue creation game ;-)

**Comment by elassabe** [comment]
What happens in this situation,
When you enter the DokuWiki (2017-02-19b's Version) and you click on the Media Manager to edit or create files, I click the "Upload" button and select the file on our computer. Instead of opening a window for us to select one of the files, nothing happens absolutely.
In the console, there is the following message: In doku.php, _gat is not defined
Can you help me ?

**Comment by splitbrain** [comment]
your template is shit. unfortunately you did not specify which one it is. anyway it fails to style the select files button correctly and thus you're confused about the interface. You have to click the "select files..." text to select the files, only then use the upload button to select the files.
