### ISSUE TITLE
Bug when parsing links containing brackets

### ISSUE THREAD

**Issue by zdimension** [splitbrain/dokuwiki#1999]
This code:
```
Some text [[a_page#​an_anchor|[struct_name].member]] some other text [[a_page#​an_anchor|[struct_name].member]] another text.
```
Renders correctly:
![image](https://cloud.githubusercontent.com/assets/4533568/26755078/768444b8-4886-11e7-93df-ba78cae8a1ba.png)

This one however:
```
Some text [[a_page#​an_anchor|[struct_name].member]] some other text [[a_page#​an_anchor|[struct_name].member]] another text. Some text [[a_page#​an_anchor|[struct_name]]].
```
Renders incorrectly:
![image](https://cloud.githubusercontent.com/assets/4533568/26755093/a5fc9196-4886-11e7-9fe3-ef5028ba0b33.png)

Notice that the only change is the addition of a third link after the text.
It's like if DW's link parser were using regexes or something similar and detects everything as a big link.

**Comment by LarsGit223** [comment]
Please re-test with current version/master. The merge of #1987 might have fixed your problem.

**Comment by splitbrain** [comment]
seems to work now.
