### ISSUE TITLE
Exception 'no data passed' in subsciption.php

### ISSUE THREAD

**Issue by turnermm** [splitbrain/dokuwiki#2003]
An exception arising out of subsciption.php.
'Exception' with message 'no data passed' in /www/itwiki/inc/subscription.php:119

Two instance, both from the same user, but out of different wikis:
https://forum.dokuwiki.org/post/56976
https://forum.dokuwiki.org/post/56921

**Comment by phy25** [comment]
I guess some auth backend wrote REMOTE_USER with an empty string `""` (although I am not seeing this behavior in plugin:adfs), and the check in `pageinfo()` does not expect that?

https://github.com/splitbrain/dokuwiki/blob/13831edddf6edc68c9b5fe3143c3a22253bb7bec/inc/common.php#L220-L225

So a proper fix would be in `dokuwiki/Subscriptions/SubscriberManager->userSubscription()`, return false if $user is eventually empty, and eliminate the check in `pageinfo()` I guess?

However I am not sure if this is still an issue as of now.
