### ISSUE TITLE
Upload button in the Media Manager 

### ISSUE THREAD

**Issue by elassabe** [splitbrain/dokuwiki#2005]
In this situation,
When you enter the DokuWiki (2017-02-19b's Version) and you click on the Media Manager to edit or create files, I click the "Upload" button and select the file on our computer. Instead of opening a window for us to select one of the files, nothing happens absolutely.
In the console, there is the following message: In doku.php, _gat is not defined
Can you help me ?

**Comment by splitbrain** [comment]
duplicate of #1998
