### ISSUE TITLE
How connect to self-signed server with DokuHTTPClient

### ISSUE THREAD

**Issue by algorys** [splitbrain/dokuwiki#2008]
Hello,

I'm trying to get some data (on a gitlab server with ssl) with your DokuHTTPClient for my plugin https://github.com/algorys/gitlabproject/.

But I can't find a way to make it works.

Here si the request I make:

```php
$this->client = new DokuHTTPClient();
$url = "https://gitlab.local.fr/api/v3/projects/MyGroup%2FGrouProj/?private_token=ySfJKq914HiT889DA2DQ"
$project = json_decode($this->client->get($url_request), true);
```

But it returns empty result or if I do `$this->client->error` I've the following error:

`Could not connect to ssl://gitlab.local.fr:443`

I've made some tests after to see what's wrong: FQDN is resolved by Dokuwiki server, telnet on server and 443 works... 

I think it's because, client try to check the certificate who is self-signed with the Certificate Authorities...

If I do the same with `curl`, I get the expected response:

```php
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Content-Type: application/json',
    'Accept: application/json'
 ));
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, '1');
// Here I set SSL_VERIFIERPEER to 0 and it's works !!
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, '0');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$output = curl_exec($ch)
```

Is thete a way to do that with DokuHTTPClient also ? I've search on forums, gitlab, IRC but can't find a way to get it work :cry: !

Thanks.

**Dokuwiki version** : Release 2017-02-19b "Frusterick Manners"

**Comment by splitbrain** [comment]
We're not using curl in DokuWiki but rely on PHP's socket library and openssl extension. Please refer to the PHP documentation on how to make your certificate known to PHP: http://php.net/manual/en/openssl.configuration.php

**Comment by algorys** [comment]
@splitbrain I do not want to use curl in Dokuwiki but I wanted to know if we could not use the SSL checks via the HTTP client of Dokuwiki ?

I've read the documentation of PHP (I searched all day) but it did not make much progress. 

So I've to tell my Dokuwiki server to check somewhere the certificate of the Gitlab server ?

**Comment by splitbrain** [comment]
Yes. Your PHP setup needs to trust the certificate of your gitlab server. So you need to add it one of the two locations where PHP checks for trusted certificates. openssl.capath is probably the easiest one as you can simply place another file into that directory without affecting any other trusted certs.
