### ISSUE TITLE
Fatal error: Maximum execution time of 30 seconds exceeded in htdocs/inc/utf8.php on line 283

### ISSUE THREAD

**Issue by Patharwong** [splitbrain/dokuwiki#2014]
Hi there, 

Regarding this maximum execution time error, I've read through some posts online and managed to alert the maximum execution time variable.  However, there is an account which is still experiencing this error during submitting a from while other accounts haven't encountered such.  Is there any possibility that this error could be somehow dependent on accounts? 
Appreciate if anyone could shed some light.

Thanks, 
Pathar

**Comment by Klap-in** [comment]
Please provide any information that allows others to reproduce your case. Thanks!
(what is your system, version dokuwiki, installed plugins, task you are performing etc etc)

**Comment by splitbrain** [comment]
no feedback provided. closing. you probably want to install the mb_string extension
