### ISSUE TITLE
Variable "$regex" used, but never defined in "html_search()"

### ISSUE THREAD

**Issue by igittigitt** [splitbrain/dokuwiki#2017]
Function: "html_search()"
File: "inc/html.php"

starting at line 410, the variable "$regex" is used 3 times, but is never defined:
```php
    $data = ft_pageSearch($QUERY,$regex);
    if(count($data)){
        print '<dl class="search_results">';
        $num = 1;
        foreach($data as $id => $cnt){
            print '<dt>';
            print html_wikilink(':'.$id,useHeading('navigation')?null:$id,$regex);
            if($cnt !== 0){
                print ': '.$cnt.' '.$lang['hits'].'';
            }
            print '</dt>';
            if($cnt !== 0){
                if($num < FT_SNIPPET_NUMBER){ // create snippets for the first number of matches only
                    print '<dd>'.ft_snippet($id,$regex).'</dd>';
```

**Comment by Klap-in** [comment]
The `$regex` parameter is a reference.
So it got the value that is assigned in the function (or this case function in that function) to this variable.

https://github.com/splitbrain/dokuwiki/blob/65d3a5db1b1c8fa46b1aa39f43ae3598dc6dafb4/inc/fulltext.php#L27

It doesn't need to be defined on for hand. For some cases that would have been more clear..

**Comment by igittigitt** [comment]
I see. It my be filled with a regex after ft_pageSearch() function executed.
Even if it is allowed in PHP, using undeclared variables is bad coding style in every programming language. A single "$regex = '';" in front of the routine would make it more readable.
Just my 2cent ;-)

**Comment by Klap-in** [comment]
Coding styles/language structures change in the time. PR is welcome of course.

I think its an array:
`$regex = array()`

**Comment by igittigitt** [comment]
So i did. PR generated.
