### ISSUE TITLE
broken links to W3C validators

### ISSUE THREAD

**Issue by juckins** [splitbrain/dokuwiki#2021]
The bottom of the Dokuwiki pages has URL links to "W3C HTML5" and "W3C CSS" validation tools.  Both are giving broken link errors.

Could the dokuwiki template be updated to fix these links to:

W3C HTML5: https://validator.w3.org/

W3C CSS: https://jigsaw.w3.org/css-validator/

Thanks for your consideration.

**Comment by yurii-github** [comment]
are you sure about links? Do you try to validate local webapp?

**Comment by juckins** [comment]
Hi, I may not have been clear in the trouble I was reporting.  

If you go to https://www.dokuwiki.org/ and scroll to the bottom of it you will see a little icon with a link titled "W3C HTML5".  The URL it is trying to go to is http://validator.w3.org/check/referer but it should be going to https://validator.w3.org/ instead.

Similarly, at the bottom of the same page is another little icon titled "W3C CSS".  The URL it is trying to go to is http://jigsaw.w3.org/css-validator/check/referer?profile=css3 but it should be going to https://jigsaw.w3.org/css-validator/ instead. 

Can those links be updated?  If you click on those 2 icons right now you get error pages.

**Comment by yurii-github** [comment]
funny. I have installation of dokuwiki and referer is fine.
It looks like something is resetting referer on official dokuwiki.

Do you have same issue on your setup?

**Comment by yurii-github** [comment]
i got the issue!
 it's because of HTTP instead of HTTPs in link. I'll make a change

**Comment by juckins** [comment]
That would be great.  Thanks for your help!
