### ISSUE TITLE
Add support for Sass compiler

### ISSUE THREAD

**Issue by molefunk** [splitbrain/dokuwiki#2023]
Ahem! I'd like to chime in with my 2 paisa, if you won't mind... DokuWiki was the reason I got into Less in the first place, it was just too easy to resist. And although I may prefer the simplicity of Less to that of Sass, I see many developers switching to Sass. Not only that, but many frameworks are Sass-only...

I humbly suggest that DokuWiki could support Sass in addition to Less, to make it easier for simpletons like me to convert (Sass) frameworks into DokuWiki themes. I'm sure it would not hurt for the DokuWiki template directory to get a few (more?) good-looking themes!

**Comment by splitbrain** [comment]
Switching to SASS would be complicated. It would break compatibility to all plugins using LESS since we can not in a useful way support both.

We support CSS and LESS because CSS is valid less and can be just run through the LESS compiler. We can not do the same for SASS.

I'm leaning towards closing this as won't fix.

**Comment by mprins** [comment]
adding to that there are currently several implementations of Sass but the only PHP version (leafo/scssphp) is lagging behind wrt. api compatibility. Having a Sass compiler is only worth it if it supports the current (3.5) reference release.

@molefunk there is no reason for you to not provide compiled (css) versions of the themes in any templates you wish to share

**Comment by molefunk** [comment]
Thanks for the explanation, @splitbrain. However, css is also valid .scss, as described [in their docs](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax):

> There are two syntaxes available for Sass. The first, known as SCSS (Sassy CSS) and used throughout this reference, is an extension of the syntax of CSS. This means that every valid CSS stylesheet is a valid SCSS file with the same meaning. In addition, SCSS understands most CSS hacks and vendor-specific syntax, such as IE's old filter syntax. This syntax is enhanced with the Sass features described below. Files using this syntax have the .scss extension.

I wouldn't dwell any more on this, except it seems just about "everyone" is switching from Less to Sass. Bootstrap 4 will be all Sass. The upcoming Primer (from GitHub) is built with Sass. (Wouldn't it be cool to have a DokuWiki theme looking like GitHub?) Or Flexbox frameworks like [Bulma](http://bulma.io), also only Sass...

I built a DokuWiki theme from [Base](http://getbase.org), and it was as easy as just dropping the Less files in and referencing them in the style.ini file. But Base is also moving away from Less, although they still maintain the branch. If one could bake in an option to choose between Less or Sass in DokuWiki, at least it would be possible to gradually prepare for a foreseeable future where Less is obsolete.

Just adding that to my 2 paisa, now up to 4...

**Comment by molefunk** [comment]
@mprins I didn't think of precompiling. Thanks for pointing it out. May even fit better with my workflow, and I won't have to learn any new preprocessor code. I'm out of this discussion then, and rather let the experts decide how to (not) go about this.

**Comment by splitbrain** [comment]
@molefunk I totally get where you coming from.

To explain my statement about CSS being piped through LESS. Yes, we could also pipe CSS through SASS. But we can't pipe LESS through SASS. Or SASS through LESS.

Let me explain. Currently we do the following:

- concat all LESS and CSS files into one big chunk in the correct order
- replace our custom ini placeholders in that
- create LESS variables from our ini placeholders and prepend them to the chunk
- run all this through the LESS compiler

There is no way to introduce SASS in the above steps without breaking the correct order of files or breaking backward compatibility with LESS based templates and plugins.

I'm closing this now. Feel free to open a pull request if you (or anyone) can come up with a workable solution to slowly phase out LESS and move to SASS without suddenly breaking everything.
