### ISSUE TITLE
Extension manager shows differing information

### ISSUE THREAD

**Issue by cjohnsonuk** [splitbrain/dokuwiki#2024]
In all my installs the information relating to a particular extension shown in the "search and install" tab is not always the same as the information shown for the same plugin in the "installed plugins" tab.  It would be great if these matched up so that when adding plugins already in one wiki to new wiki its easy to work out which is which.

The titles don't always match, the authors and descriptions don't always match.

It would be great to have tick boxes and the option to choose "install selected" on the install tab 
and "update selected" on the installed tab.

Its a small thing but its quite annoying...
:-)

**Comment by Klap-in** [comment]
There are more sources of information for the extension manager:
- plugin.info.txt or template.info.txt
- via api of plugins/template repository at dokuwiki.org

My guess is that before installation the api is used, and after installation that file from the plugin/template directory.

**Comment by phy25** [comment]
I would say this is a won't fix due to how this works? Feel free to add more information if necessary and I can reopen.
