### ISSUE TITLE
Add configurable mail return-path

### ISSUE THREAD

**Issue by wiebeytec** [splitbrain/dokuwiki#2025]
The `Mailer` class does not seem to set a `Return-Path` header anywhere. This results in all bounces being sent to `www-data@server.com`, or variants of that.

A configurable return-path is an important piece of the mail configuration. Code wise, it can be done like [this](https://stackoverflow.com/a/12446081/648159), depending on what mail infrastructure is used.

**Comment by flammy** [comment]
@wiebeytec I added the returnpath:

5f43dcf4974f7308330e107a5b71027b0da739d1

and tried it with my mail setup. As the message is send via local socket without authentification the mailserver removes the return-path and adds `username@hostname` from the sending process.

**Comment by wiebeytec** [comment]
Back then, I was able to fix it with:

    php_admin_value mail.force_extra_parameters "-fbounces@bla.com"

I would have liked to have put this in the `.htaccess` (which is under version control for our project), but setting it there, with `php_value`, didn’t work, even though it should, because it’s a `PHP_INI_PERDIR` param. I never figured out why, but it seems there are quirks to setting this. You may be running into similar issues.
