### ISSUE TITLE
Enabling plugins only on certain pages/namespaces

### ISSUE THREAD

**Issue by alawatthe** [splitbrain/dokuwiki#2030]
Is there a way to enable plugins only on certain pages/namespaces? This came up in https://github.com/liffiton/dokuwiki-plugin-mathjax/issues/29.

**Comment by mprins** [comment]
Depending on the type of plugin, at runtime and after loading a plugin may have access to the page id and namespace and at that time could decide not to e.g.. render, however some plugins are not page bound, e.g. remote or admin plugins so that would not be possible.

**Comment by splitbrain** [comment]
This is currently not possible and not planned. Implementing this would open a whole can of worms security wise.
