### ISSUE TITLE
Dokuwiki unauthorized changes the image size in tables.

### ISSUE THREAD

**Issue by Chemnitz** [splitbrain/dokuwiki#2059]
Dokuwiki unauthorized changes the image size in tables. The specification of a width is not interpreted correctly. The image size depends on the content of the other cells.

**Comment by Klap-in** [comment]
Could you please create an example at e.g. https://www.dokuwiki.org/playground:issue2059
or provide in a different manner some illustration of the situation? Thanks

**Comment by Chemnitz** [comment]
I have created a small example of the issue: https://www.dokuwiki.org/playground:issue2059

**Comment by splitbrain** [comment]
The dokuwiki template has ``max-width: 100%`` for images, videos etc. Which is useful to make sure large images will not destroy the overall layout or create horizontal scrolling. A side effect seems to be that images are scaled down very much in autosized tables. I'm not sure how to fix this.

We could add a ``table img {max-width: none}``, but that could create problems with large images again.

Better would be to specify a minimum width so images are not scaled down to unrecognizable sizes. But I'm not sure how to do that in a sensible way.

Maybe @selfthinker has an idea?

**Comment by phy25** [comment]
The browser scaled down the image because the initial width of column with an image only is 1em (padding). If you give the parent column a width things will go on well (but it's impossible with DokuWiki's syntax).

Some thoughts:
- Use `table {table-layout: fixed}` to let the header decide the width;
- Use `max-width: 100vw`, at least make the image not that big;
- Give way to `table img {max-width: none}`, as we can really do nothing about oversized images in the table. Set the width manually to the oversized image in the table if necessary.

**Comment by splitbrain** [comment]
`table img {max-width: 80vh}` seems reasonable to me, it removes the autoscaling inherited from the 100% width but still ensures at least *some* downscaling.

**Comment by phy25** [comment]
`80vh` seems unfit in mobile. Maybe this is better:
```css
@media screen and (orientation:landscape) {
    table img {max-width: 80vh}
}
@media screen and (orientation:portrait) {
    table img {max-width: 40vw}
}
```

**Comment by micgro42** [comment]
What is the motivation behind having the image's max-width in landscape be dependent on the viewport height instead of viewport width?

**Comment by phy25** [comment]
@micgro42 I came out this question before like you. That looks not theorically correct, but it works best between 4:3 - 16:9 ratio's screens.

**Comment by selfthinker** [comment]
I personally would prefer `table img {max-width: none}`. But I guess it's all a question of use cases. In which cases would that be bad?

**Comment by splitbrain** [comment]
@selfthinker it would be bad in all the usecases where a large image is added to the table without any resizing. It pushes all the content out of the viewport.

**Comment by selfthinker** [comment]
Not really. I mean, it can never be changed by the editor but editors are only likely to want to change it within tables.
The fact that `max-width` affects the size of an image in a way the author hasn't intended and which might not break the layout only happens within smaller containers. And that's just tables within the core syntax. Everywhere else the image is fine to grow until it fits the main content area.
While that cannot be changed by the editor either, it is very likely that they will not even notice it while they will notice it straight away within tables.

**Comment by splitbrain** [comment]
True, though the problem is, that within tables it's quite hard to manually specify the right width. I might specify something that looks fine on my desktop. But for someone looking at it on a mobile phone the experience might be horrible.

**Comment by selfthinker** [comment]
Yeah, true. Mobile vs desktop will be harder for images in tables. It's already hard enough without images.

**Comment by Sayuuk** [comment]
Any news on this? I'm running into the same issue and would love to get it resolved.
