### ISSUE TITLE
Docu wiki giving me php errors when the swift mail plug in is executing.

### ISSUE THREAD

**Issue by KipOmaha** [splitbrain/dokuwiki#2070]
I am running DocuWiki on windows 10 via a xampp application...

When I installed it I immediately get a php error stating that the, `new` keyword was in a place not  
expected...so I remove it and I got the php to execute correctly, and now see the wiki page.  

but...  

I still have one more error and it states: 
  `Warning: Declaration of action_plugin_swiftmail::register(&$controller) should be compatible with DokuWiki_Action_Plugin::register(Doku_Event_Handler $controller) in H:\xampp\apps\dokuwiki\htdocs\lib\plugins\swiftmail\action.php on line 138 `

I'm not sure if any of this is documented or anything but if you want info please let me know.

**Comment by splitbrain** [comment]
Plugin problems should be reported in the plugin's bug tracker. However the swiftmail plugin is deprecated.
