### ISSUE TITLE
After upgrade to Frusterick Manners from Elenor of Tsort with upgrade plugin, every button in my wiki doesn't action.

### ISSUE THREAD

**Issue by JedBeom** [splitbrain/dokuwiki#2073]
Please read title. Thanks.

**Comment by phy25** [comment]
Please say specifically what button is not operational. You can also see what happened in `Web Developer Console` (F12) when clicking buttons.

**Comment by JedBeom** [comment]
When I click any document link in start, strange black box called 'swipebox-container' fills my display. Clicking 'setting' button actions too. Sorry my short English.

**Comment by splitbrain** [comment]
upgrade your gallery plugin
