### ISSUE TITLE
Enable SSL with update server

### ISSUE THREAD

**Issue by phy25** [splitbrain/dokuwiki#2082]
Currently DOKU_MESSAGEURL is on HTTP (http://update.dokuwiki.org/check/). Because text there will be directly shown on the website without sanitation, it would be nice if this update check is under HTTPS, to prevent MITM attacks.

**Comment by splitbrain** [comment]
I agree, however first a check if the current PHP install supports SSL should be done. If not, a fallback to HTTP might be preferable. PR welcome.
