### ISSUE TITLE
URI schema ignored when rendering URIs containing @

### ISSUE THREAD

**Issue by penguineer** [splitbrain/dokuwiki#2084]
When adding a URI (aka URL) containing an @ symbol, like
`[[xmpp:lounge@conference.jabber.n39.eu?join|lounge@conference.jabber.n39.eu]]`
the href is rendered as
`mailto:xmpp:lounge@conference.jabber.n39.eu?join` 
instead of
`xmpp:lounge@conference.jabber.n39.eu?join`,
even though a URI scheme (xmpp) has been stated.

Assuming `mailto:` when the URI contains @ and does not specify the scheme is a very nice feature. However, when the schema is specified the generated URI is invalid and not what the user intended.

**Comment by splitbrain** [comment]
schemas not using the colon-doubleslash format are not supported through the scheme configuration. A workaround is to create a interwiki shortcut. see the configuration for callto links as an example.

**Comment by penguineer** [comment]
So there is no way to create a URL just as it is? The only thing I want to achieve is that the renderer inserts a link in the form of `<a href="xmpp:lounge@conference.jabber.n39.eu?join">lounge@conference.jabber.n39.eu]</a>`.

I could not see how this can be done with the callto-workaround.

**Comment by splitbrain** [comment]
Define the interwiki link:

```
xmpp       xmpp:{NAME}
```

Then use ``[[xmpp>lounge@conference.jabber.n39.eu]]``

**Comment by penguineer** [comment]
Ah, this seems to work. Thanks.
