### ISSUE TITLE
Stored XSS in wiki title (admin required)

### ISSUE THREAD

**Issue by chb9** [splitbrain/dokuwiki#2085]
Maybe no big impact because admin is required, but if admin set the wiki title to

`<img src=x onerror=alert(1)> `

the alert is triggered.

**Comment by phy25** [comment]
Actually this is a template-related issue, and many templates have this issue.

https://github.com/splitbrain/dokuwiki/blob/e4fa63f365d4ef00ca4a99df96d6fae5529d3b6f/lib/tpl/dokuwiki/tpl_header.php#L26-L30

I do see `strip_tags()` sanitation in other code of the template, so it's unknown whether this is a feature or a bug.

**Comment by splitbrain** [comment]
Admin provided values are used as is at many places. In fact some templates use this as a feature, eg, allowing users to add an image into the wiki title. Since an admin can execute arbitrary code (by installing plugins) anyway, I think this is not really an issue.
