### ISSUE TITLE
p_get_metadata problem

### ISSUE THREAD

**Issue by qwe852147** [splitbrain/dokuwiki#2087]
There some problem when I try to get contributes.
When contributes ID all is number I get contributes  index number of array rather than ID.

There is I find my metadata. The user name ttt and 111 there ID is not "0" and "1" 
`"contributor":{"0":"ttt","1":"111","pochin":"\u5f35\u67cf\u6b3d"}}}`

I can't get real  contributor ID

**Comment by phy25** [comment]
The contributor attribute is written here: https://github.com/splitbrain/dokuwiki/blob/e4fa63f365d4ef00ca4a99df96d6fae5529d3b6f/inc/changelog.php#L113-L121 , while https://github.com/splitbrain/dokuwiki/blob/e4fa63f365d4ef00ca4a99df96d6fae5529d3b6f/inc/changelog.php#L82

Thus you can log in as these questionable users and try editing pages again, and see whether this is reproducible or not. It might also be the issue of your auth plugin, so the auth plugin you are using matters as well.

**Comment by qwe852147** [comment]
I find the problem is here
https://github.com/splitbrain/dokuwiki/blob/e4fa63f365d4ef00ca4a99df96d6fae5529d3b6f/inc/parserutils.php#L338

array_merge will change number key to reset from 0
example 
`
ary 1 = array("987"=>"test1","111"=>"test2","pochin"=>"\u5f35\u67cf\u6b3d");
ary 2 = array("555"=>"test3");
array_merge(arr1,arr2) 

result will be Array
(
    [0] => test1
    [1] => test2
    [pochin] => \u5f35\u67cf\u6b3d
    [2] => test3
)
` 
so meta can't get real user id

**Comment by phy25** [comment]
@qwe852147 You are right 👍, and one more related code:
https://github.com/splitbrain/dokuwiki/blob/e4fa63f365d4ef00ca4a99df96d6fae5529d3b6f/inc/parserutils.php#L354-L363

As [PHP docs suggests](http://php.net/manual/en/function.array-merge.php#example-5601) we need to use the `+` operator. These arrays does not have numeric keys I think. We can make a PR now 😄

**Comment by phy25** [comment]
By the way, it's tricky to fix these corrupted contributor arrays. Maybe we need a helper script to rebuild contributors in the changelog?

**Comment by qwe852147** [comment]
I paste wrong line .Just fix https://github.com/splitbrain/dokuwiki/blob/e4fa63f365d4ef00ca4a99df96d6fae5529d3b6f/inc/parserutils.php#L354-L363

to 
`if (is_array($value)) {
                if($key=="contributor") {
                    $meta['current'][$key] = !empty($meta['current'][$key]) ? array_replace((array)$meta['current'][$key],$value) : $value;
                    if ($persistent) {
                        $meta['persistent'][$key] = !empty($meta['persistent'][$key]) ? array_replace((array)$meta['persistent'][$key],$value) : $value;
                    }
                }else{
                    $meta['current'][$key] = !empty($meta['current'][$key]) ? array_merge((array)$meta['current'][$key],$value) : $value;
                    if ($persistent) {
                        $meta['persistent'][$key] = !empty($meta['persistent'][$key]) ? array_merge((array)$meta['persistent'][$key],$value) : $value;
                    }
                }
            }`
I jsut do for 'contributor' key.
I don't know if  other key has same situation .

**Comment by phy25** [comment]
According to https://www.dokuwiki.org/devel:metadata `contributor` is affected with numeric and string keys mixed. `subject` needs to use array_merge explicitly, but it's not merged in core. For other keys using both methods is fine.

I think just replacing all `array_merge` to `+` union in 'relation' and $protected clauses is fine.

**Comment by qwe852147** [comment]
I think the array_replace will be better because of following two array
`$array1 = array("color" => "red", 2, 4);
$array2 = array("a", "b", "color" => "green", "shape" => "trapezoid", 4);`


in "+" 
`
output : Array
(
   [color] => red
    [100] => 2
    [101] => 4
    [0] => a
    [1] => b
    [shape] => trapezoid
)
`


in "array_merge"
`
output : Array
(
    [color] => green
    [0] => 2
    [1] => 4
    [2] => a
    [3] => b
    [shape] => trapezoid
    [4] => 4
)
`

in "array_replace"
`
output : Array
(   
    [color] => green
    [100] => 2
    [101] => 4
    [0] => a
    [1] => b
    [shape] => trapezoid
)`

You can see "color" key in merge and replace will be replace but "+" not .
 And array_merge will include all element of two array and sometimes key is number will be changed.
 array_replace does not change key and it can be replace when key is duplicate

**Comment by phy25** [comment]
A fix (as well as a test) is available at #2091.
In the meanwhile, if you need to fix these damaged contributors meta, you can try this homemade plugin (Admin > Fix contributors in meta... > Fix): https://gist.github.com/phy25/871390a4816eef9b9db634c3bd96c1c5

**Comment by qwe852147** [comment]
Sorry the fix meta plugin will not work .
It can fix meta when click button but when I modify the page wrong meta will appear.

**Comment by phy25** [comment]
@qwe852147 That plugin is a rough script for a one-time fix for reference only. "when I modify the page wrong meta will appear", could you specify the issue?

**Comment by qwe852147** [comment]
OK ! 
for example 
I have a wrong meta following
`"contributor";a:110:{s:7:"henrywu";s:9:"person6";s:6:"pochin";s:9:"person5";i:0;s:9:"person1";i:1;s:9:"person1";i:2;s:9:"person1";i:3;s:9:"person1";i:4;s:9:"person1";i:5;s:9:"person1";i:6;s:9:"person1";i:7;s:9:"person1";i:8;s:9:"person1";i:9;s:9:"person1";i:10;s:9:"person1";i:11;s:9:"person1";i:12;s:9:"person1";i:13;s:9:"person1";i:14;s:9:"person1";i:15;s:9:"person1";i:16;s:9:"person1";i:17;s:9:"person1";i:18;s:9:"person1";i:19;s:9:"person1";i:20;s:9:"person1";i:21;s:9:"person1";i:22;s:9:"person1";i:23;s:9:"person1";i:24;s:9:"person1";i:25;s:9:"person1";i:26;s:9:"person1";i:27;s:9:"person1";i:28;s:9:"person1";i:29;s:9:"person1";i:30;s:9:"person1";i:31;s:9:"person1";i:32;s:9:"person1";i:33;s:9:"person1";i:34;s:9:"person1";i:35;s:9:"person1";i:36;s:9:"person1";i:37;s:9:"person1";i:38;s:9:"person1";i:39;s:9:"person1";i:40;s:9:"person1";s:8:"chunyang";s:9:"person4";i:41;s:9:"person1";i:42;s:9:"person1";i:43;s:9:"person1";i:44;s:9:"person3";i:45;s:9:"person3";i:46;s:9:"person3";i:47;s:9:"person2";i:48;s:9:"person2";i:49;s:9:"person2";i:50;s:9:"person2";i:51;s:9:"person3";i:52;s:9:"person3";i:53;s:9:"person2";i:54;s:9:"person3";i:55;s:9:"person2";i:56;s:9:"person3";i:57;s:9:"person2";i:58;s:9:"person2";i:59;s:9:"person2";i:60;s:9:"person2";i:61;s:9:"person3";i:62;s:9:"person3";i:63;s:9:"person3";i:64;s:9:"person2";i:65;s:9:"person3";i:66;s:9:"person3";i:67;s:9:"person3";i:68;s:9:"person3";i:69;s:9:"person2";i:70;s:9:"person2";i:71;s:9:"person2";i:72;s:9:"person2";i:73;s:9:"person2";i:74;s:9:"person2";i:75;s:9:"person2";i:76;s:9:"person2";i:77;s:9:"person2";i:78;s:9:"person2";i:79;s:9:"person2";i:80;s:9:"person2";i:81;s:9:"person2";i:82;s:9:"person2";i:83;s:9:"person2";i:84;s:9:"person2";i:85;s:9:"person2";i:86;s:9:"person2";i:87;s:9:"person3";i:88;s:9:"person3";i:89;s:9:"person2";i:90;s:9:"person2";i:91;s:9:"person2";i:92;s:9:"person2";i:93;s:9:"person2";i:94;s:9:"person2";i:95;s:9:"person2";i:96;s:9:"person2";i:97;s:9:"person2";i:98;s:9:"person2";i:99;s:9:"person2";i:100;s:9:"person2";i:101;s:9:"person2";i:102;s:9:"person2";i:103;s:9:"person2";i:104;s:9:"person2";i:105;s:9:"person2";i:106;s:9:"person2";}"`

you can find person 2 and person 3 is too many in contributor array.
Then I use this plugin to fix this meta and I get correct meta following`"contributor";a:6:{s:7:"henrywu";s:9:"person6";s:6:"pochin";s:9:"person5";i:88016;s:9:"person1";s:8:"chunyang";s:9:"person4";i:92043;s:9:"person3";i:96064;s:9:"person2";}`

But the meta will go wrong after I edit the page . The meta will be recovered to the   wrong meta

**Comment by phy25** [comment]
Well that's weird. Did you get those metadata you mentioned by the files or in DokuWiki's PHP environment?
I have the idea that the only suspect recovering the meta is the cache, or I missed something in the meta saving process (maybe I shouldn't directly modify the meta files?).

**Comment by qwe852147** [comment]
In the meta file. I open it and check it .

**Comment by phy25** [comment]
@qwe852147 Sorry for the late reply. Just found a typo in the plugin leading to this issue (and I didn't test it throughly). You can try redownloading at https://gist.github.com/phy25/871390a4816eef9b9db634c3bd96c1c5.

**Comment by qwe852147** [comment]
Sorry for the late reply ,I test it after finish some work.
The plugin is work best , my meta files were fixed.
