### ISSUE TITLE
array_keys() expects parameter 1 to be array, null given...

### ISSUE THREAD

**Issue by LMS235** [splitbrain/dokuwiki#2088]
After Upgrade form 2017-02-19c to 2017-02-19d following error occours with PHP 5.6.27 and 5.6.30 but not with 7.1.8 and 7.0.22 (see also https://forum.dokuwiki.org/post/57836):

Warning: array_keys() expects parameter 1 to be array, null given in .../wiki/vendor/easybook/geshi/geshi.php on line 2039

Warning: Invalid argument supplied for foreach() in .../wiki/vendor/easybook/geshi/geshi.php on line 2039

Warning: Invalid argument supplied for foreach() in .../wiki/vendor/easybook/geshi/geshi.php on line 2411

Warning: implode(): Argument must be an array in .../wiki/vendor/easybook/geshi/geshi.php on line 3365

Warning: array_keys() expects parameter 1 to be array, null given in .../wiki/vendor/easybook/geshi/geshi.php on line 3388

**Comment by phy25** [comment]
Sorry about this. Are you using `<code>`? What language are you using in `<code>`?

**Comment by LMS235** [comment]
yes, error only on pages with <code> blocks. But with different languages.
<code>, <code bash> and <code sql>

**Comment by phy25** [comment]
I see... Actually I can reproduce this on PHP 7 (without render cache with this: `<code>1</code>`). Line 633 is making null to (string) "", causing line 654 fail to check.

https://github.com/splitbrain/dokuwiki/blob/3637ffa998f499e0e6f50733867b4d9e91360a38/inc/parser/xhtml.php#L629-L668

My bad. You can fix this by changing line 654 to `if(empty($language)) {`. Will make a PR.

**Comment by LMS235** [comment]
after change 654 it works without errors, thanks!
