### ISSUE TITLE
FEATURE REQUEST hide recent changes, media-manger and overview form not logged in users

### ISSUE THREAD

**Issue by bastardop** [splitbrain/dokuwiki#2090]
Hello there,

when my ACL says * @ALL none  it is still possible for not logged in Users to the the overview of the namespaces. I think * @ALL none should also prevent that.

on stackoverflow the solution form the user escobrice 
`If no user is logged, $INFO["userinfo"] is empty

in /lib/tpl/dokuwiki/tpl_header.php replace

tpl_toolsevent('sitetools', array(
                    tpl_action('recent', true, 'li', true),
                    tpl_action('media', true, 'li', true),
                    tpl_action('index', true, 'li', true)
                ));
with

             if(!empty($INFO["userinfo"]))  {
                tpl_toolsevent('sitetools', array(
                    tpl_action('recent', true, 'li', true),
                    tpl_action('media', true, 'li', true),
                    tpl_action('index', true, 'li', true)
                ));
             }`
seems to be very fine but it is hard coded into the template and so it will be outnumbered by the next update. 
So i ask if it is possibly to integrate this feature as an config option?

Cheers and thx for the great dokuwiki

**Comment by phy25** [comment]
You are talking about two things:
- Hide links for non logged-in users. Actually if they have no permission, when they click the link it will raise a no permission warning. This actually can be done by a plugin (hook `TEMPLATE_USERTOOLS__DISPLAY`; I will give examples later), thus it won't be overwritten by updates.
- Showing namespaces for unprivileged users. This can already be configured by `$conf['sneaky_index']= 0`.

**Comment by bastardop** [comment]
all right thx for that, sneaky_index did right what i wanted

**Comment by phy25** [comment]
Glad to hear that! If that fits your need, please close this issue.
