### ISSUE TITLE
do not show upgrade notice for a period of time

### ISSUE THREAD

**Issue by jsmota** [splitbrain/dokuwiki#2092]
Sorry because of my idea may be differ from what most of people think.
I have minimum willing to upgrade my dokuwiki as soon as possible because I run it on localhost and I have failed to enable SSL even I followed the [tutorial](https://www.google.com.tw/search?client=aff-cs-360chromium&hs=wCa&q=appserv+enable+ssl&oq=appserv+ssl&gs_l=psy-ab.3.2.0i22i30k1l4.121275.124436.0.126659.11.11.0.0.0.0.113.701.10j1.11.0....0...1.1.64.psy-ab..0.11.699...0j0i67k1j0i10k1.c5f06casPLI), which makes upgrading cumbersome.
Therefore, I only upgrade once after several updates were released.
However, I upgraded it several weeks after the upgrade is released but the next upgrade is released a few days later.
This makes me misunderstand dokuwiki build its happiness on my pain by reminding me my dokuwiki is upgradable.
This is why I request this feature, do not show upgrade notice for a period of time.  The period is decided by the time from the upgrade release time to the upgrade apply time.

**Comment by splitbrain** [comment]
sorry. no. if you don't want upgrade notifications you can disable them in the config.
