### ISSUE TITLE
Increase bcrypt default rounds to 10

### ISSUE THREAD

**Issue by whnr** [splitbrain/dokuwiki#2093]
https://github.com/splitbrain/dokuwiki/blob/dd865c4c6604d037f6293807f0f822838ffefd13/inc/PassHash.class.php#L533

The current standard for bcrypt is mostly 10 rounds. I would suggest to use this for dokuwiki as well.

––Florian

**Comment by splitbrain** [comment]
I'm happy to adjust that, but out of curiosity, can you link to some document describing this standard? Or at least a few examples from other tools?

**Comment by phy25** [comment]
PHP default in documents: http://php.net/manual/en/password.constants.php#constant.password-bcrypt
