### ISSUE TITLE
Config 'showuseras' seems not to work with authAD enabled - Only 'loginname' is displayed

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [splitbrain/dokuwiki#2102]
Hi,

I have configured the latest Dokuwiki release with AD integration (authAD). Everything works fine.

My problem is that the configuration 'showuseras' seems not to have any use. Only the 'loginname' is shown everywhere, even when 'username' is configured. Our AD 'loginname' contains only digits, so it is hard for people to tell, who is behind the 'loginname'.

In this screenshot (bootstrap3 template) you can see that there is a perfectly fine 'username' (... Thomas) and a 'loginname' (318...):
![grafik](https://user-images.githubusercontent.com/1389907/29770574-10148ee2-8bf0-11e7-966a-f7d9531efedd.png)

But on the bottom of the page, there is always the 'loginname'
![grafik](https://user-images.githubusercontent.com/1389907/29771060-4303edc8-8bf2-11e7-8d0e-37d840bf9552.png)

or on the revisions page:
![grafik](https://user-images.githubusercontent.com/1389907/29771121-7b54f5d2-8bf2-11e7-9ebc-2b177cddc527.png)

Any advice?

Thanks
Thomas

**Comment by phy25** [comment]
> Please note that other settings than default may give performance penalties in combination with authentication plugins like authAD plugin. - https://www.dokuwiki.org/config:showuseras

You can try debug in here (see the value of $info): 
https://github.com/splitbrain/dokuwiki/blob/8723856a9bb8aa41ea4a30e60c16c911f9f2d1c7/inc/common.php#L1755

If $info is null, it might be that your AD server is not stable, and the `authAD` plugin doesn't have a good cache.

**Comment by splitbrain** [comment]
Make sure to have configured `admin_username` and `admin_password`. Otherwise the name of users other than the currently logged in user is not available.

**Comment by Speedy-Gonzalez** [comment]
Thank you for your replies. I will try that.

**Comment by Speedy-Gonzalez** [comment]
Thanks. Now everything works fine.
