### ISSUE TITLE
headline named advertisement hidden from text

### ISSUE THREAD

**Issue by yang-dev** [splitbrain/dokuwiki#2111]
create  a headline with `== advertisement ==` (case insensitive), it is shown in TOC but not invisible in the text.

**Comment by phy25** [comment]
Not reproducible: https://www.dokuwiki.org/sandbox:issue-2111

What template are you using?

**Comment by splitbrain** [comment]
@yang-dev probably your adblocker

@phy25 please use playground: instead of sandbox:

**Comment by yang-dev** [comment]
That was indeed caused by Adguard AdBlocker on Chrome
