### ISSUE TITLE
Unable to get ODT export working with new ActionRouter

### ISSUE THREAD

**Issue by LarsGit223** [splitbrain/dokuwiki#2117]
I began to adjust the ODT plugin to support the new menu system, also see https://github.com/LarsGit223/dokuwiki-plugin-odt/issues/212.

It was simple to add the button using the new system. There is no SVG icon yet but the button is displayed anyway with a default icon (a simple circle).

But I cannot get the export itself working. As soon as I click the export button I get the message ```No renderer 'odt' found for mode 'odt'```. This also happens if I manually add ```&do=export_odt``` to the URL, so the button seems to work correct.

There is one thing to mention about the ODT plugin:
It tries to re-write the action. It registers for the event ```ACTION_ACT_PREPROCESS```. If ```$ACT``` has the value ```export_odt``` then ```$ACT``` will be set to ```export_odt_page``` (accordingly ```export_odt_pdf``` would become ```export_odt_pagepdf```). The old code would simply return ```false``` and then DokuWiki would have called the renderers in ```plugins/odt/renderer/page.php``` or ```plugins/odt/renderer/pagepdf.php``` according to the new value of ```$ACT```.

How can I achieve that with the new ```ActionRouter``` class? I tried throwing an exception like one of these:
``` php
    // $ACT == 'export_odt_page'
    throw new ActionAbort($ACT);
```
or
``` php
    // $ACT == 'export_odt_page'
    throw new ActionException($ACT);
```
But if I throw any of the two exceptions I get a huge red error message:

> DokuWiki Setup Error
> 
> Something unforseen has happened: Infinite loop in actions
> 

I am stuck on this, please advise.

**Comment by splitbrain** [comment]
I think 68667f4a8a7262b7290ae60572d9bbbe42bccc8c should fix this problem.

**Comment by LarsGit223** [comment]
Unfortunately not (copied ```ActionRouter.php``` again to be sure I did not forget it). I can confirm that registering ```ACTION_ACT_PREPROCESS``` now works, the event gets triggered.

But what is the correct thing to do to "switch" the action to ```export_odt_page```. Just return ```false``` or throw an exception? What is the ODT plugin expected to do?

**Comment by splitbrain** [comment]
The event should continue to work exactly as before. If not it's a bug. There should not be a change required for the ODT plugin. I have to look into it when I find time. Maybe @micgro42 has an idea what's wrong.

**Comment by LarsGit223** [comment]
Ok, thanks. 

In case I use the old code in the ODT action plugin I just get the message ```No renderer 'odt' found for mode 'odt'```. I assume it could have to do with the class names. The ODT plugin has multiple renderers. So the class is e.g. not called ```renderer_plugin_odt``` but ```renderer_plugin_odt_page``` instead.

Take your time and have look when you got time for it. Only needs to be addressed before the next release.

**Comment by LarsGit223** [comment]
I found a dirty hack to get it working:
In file ```inc/Action/Export.php```, the code starting at line 50 looks like this:
``` php
        $mode = substr($this->actionname, 7);
        switch($mode) {
            case 'raw':
                $headers['Content-Type'] = 'text/plain; charset=utf-8';
```
I changed it to this to make it work:
``` php
        //$mode = substr($this->actionname, 7);
        $mode = substr($ACT, 7);
        switch($mode) {
            case 'raw':
                $headers['Content-Type'] = 'text/plain; charset=utf-8';
```
So it really looks like a bug in that way that ```actionname``` is not updated to the new action.

**Comment by splitbrain** [comment]
Okay, the actual problem is that the ODT plugin is using the `ACTION_ACT_PREPROCESS` wrong. The event passes the action with the '$event->data' but instead of using and modifying that, the plugin simply accesses the global `$ACT`. Changing all references in `action_plugin_odt_export::convert()` from `$ACT` to `$event->data` should probably fix the problem.

I wonder if it's worth fixing this in ActionRouter for backward compatibility.

**Comment by splitbrain** [comment]
I add a small change that fixes the compatibility problem. But I'm not sure if it's a good idea. Please see c7d61a4

@micgro42 I'd like your opinion on that

**Comment by LarsGit223** [comment]
> Changing all references in action_plugin_odt_export::convert() from $ACT to $event->data should probably fix the problem.

Sorry, I read that part over. Yes, if I change all references to ```$event->data``` then the export works (without my workaround and without your change for backwards compatibility).

**Comment by LarsGit223** [comment]
I changed the ODT plugin, see https://github.com/LarsGit223/dokuwiki-plugin-odt/commit/0a837b1bc708cac4656cd8a6d741f5c3de651ccf. This can be closed, thanks for your help.
