### ISSUE TITLE
 The plugin repository could not be contacted,  Possible blacklist

### ISSUE THREAD

**Issue by budbay** [splitbrain/dokuwiki#2118]
I think dokuwiki has blacklisted my IP.  I have my router configured to us PIA VPN.  So all my network traffic hours through the VPN. Recently I started getting the error message:  "The plugin repository could not be contacted. Make sure your server is allowed to contact www.dokuwiki.org and check your proxy settings. [Retry]" I also cannot contact www.dokuwiki.org from my browser.  If I switch off the VPN then I can connect.  Is there any help I can get with this as it's not an ideal situation to have to switch off VPN and reboot router to admin my dokuwiki instance.  Thanks.

**Comment by splitbrain** [comment]
Our server blacklists IPs that try to login too fast or try to abuse it for spamming. If your VPN is shared among many users, than someone might have used it to attack the dokuwiki.org server.
I recommend setting up some exceptions (eg. define custom routes) to access DokuWiki without your VPN.
