### ISSUE TITLE
jquery.php: Timeout when using http/2

### ISSUE THREAD

**Issue by nisenbeck** [splitbrain/dokuwiki#2120]
## Problem description:
When using http 1.1 DokuWiki works as expected, fast and smooth - no problems. But as soon as I enable mod_http2 in Apache and activate h2 protocol jquery.php needs ~150 seconds to load which is exactly the [TimeOut](https://httpd.apache.org/docs/2.4/en/mod/core.html#timeout) value specified in my Apache config.

## Steps to reproduce:
1. Start Firefox and navigate to https://h2-wiki.tech-network.de/doku.php
2. If the site loads fast, press F5
3. Repeat 2. until the problem appears (usually 2-3 times)

## Additional information:
- I was also able to reproduce the issue with Google Chrome when using Linux but not on Windows
- https://h1-wiki.tech-network.de/doku.php is configured exactly the same way, but without http2 enabled (Everything works fine here)
- Both installations are the latest DokuWiki version 2017-02-19e with no further configuration.
- There is no error logged on the server (PHP or Apache) and the response code is 200

## Workaround:
Enable jQuery CDN or set `$conf['gzip_output'] = 1;`

## Server configuration:
- Apache 2.4.27
- mod_http2 enabled
- "Protocols h2 http/1.1"
- SSL with HSTS enabled
- PHP-FPM 7.1.9

**Comment by phy25** [comment]
Maybe you can try setting `$conf['gzip_output']` to 0 to see whether that is faulty.

**Comment by nisenbeck** [comment]
`$conf['gzip_output'] = 0;` is the default setting.

But when I enable gzip_output the issue does not appear. That's interesting!

**Comment by phy25** [comment]
I guess that is more of a server issue because of the large output size. You can try

- saving and upload the output of `jquery.php` as a static file (like [this jquery.js](https://github.com/splitbrain/dokuwiki/files/1293057/jquery.zip)), and then visit it with HTTP/2 to see whether there are issues
- uploading that file onto DokuWiki as a media file, and then download that file with DokuWiki's media manager (with a PHP output)

**Comment by nisenbeck** [comment]
I've uploaded an image (~2 mb) and there are no problems when downloading the static file or with the media manager:
- Static file: https://h2-wiki.tech-network.de/img_0663.jpg
- Media manager: https://h2-wiki.tech-network.de/lib/exe/fetch.php?media=img_0663.jpg

Some more informationen on my setup:
https://h1-wiki.tech-network.de/ and https://h2-wiki.tech-network.de/ are absolutely identical configured except one single line:
`Protocols http/1.1` vs. `Protocols h2 http/1.1`

**Comment by nisenbeck** [comment]
I finally found out that this is a bug in Apache 2.4.27 / mod_http2:
https://github.com/icing/mod_h2/issues/143
https://bz.apache.org/bugzilla/show_bug.cgi?id=61382

Patch: https://dist.apache.org/repos/dist/release/httpd/patches/apply_to_2.4.27/PR61382-Fix.patch
