### ISSUE TITLE
tree based move manager not showing empty namespaces

### ISSUE THREAD

**Issue by vincentkersten** [splitbrain/dokuwiki#2128]
Hello DW!

While using the tree based move manager to move media,  (e.g. https://example.com/doku.php/start?do=admin&page=move_tree ) empty namespaces are not shown in the media mover. (the right column). My way around currently is to first create a bogus file in the empty namespace i want to move media to. 

Would it be possible to also list empty namespaces, avoiding this extra step?

**Comment by micgro42** [comment]
Please open this issue at the move plugin https://github.com/michitux/dokuwiki-plugin-move
