### ISSUE TITLE
php7.*-xml need to be installed

### ISSUE THREAD

**Issue by pandamasta** [splitbrain/dokuwiki#2130]
Hi all;

I have installed dokuwiki release_stable_2017-02-19e on php7.0 but when I create a page; I get

[:error] [pid 16243] [client 127.0.0.1:54460] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_decode() in /home/x/git/public/dokuwiki/inc/utf8.php:152

I fix this with "php7.0-xml" module . 
https://stackoverflow.com/questions/35701730/utf8-endecode-removed-from-php7#36902105

Maybe it could be required for dokuwiki installation

Have a good day
Cheers;Aurelien

**Comment by splitbrain** [comment]
install.php checks for `utf8_decode` when mb_string is not available. However, `utf8_strlen` is using `utf8_decode` regardless of availability. The function should be adjusted to to use either `utf8_decode` or `mb_strlen` according to what is available.
