### ISSUE TITLE
Use constant time comparison for password hashes.

### ISSUE THREAD

**Issue by kelunik** [splitbrain/dokuwiki#2132]
https://github.com/splitbrain/dokuwiki/blob/c5d5fc7e1ea4ea563cf5016720695edb5f0e3f10/inc/PassHash.class.php#L94

^ That should use `\hash_equals()`, but that's only available on PHP 5.6+. I think Symfony has a polyfill package for it for lower versions of PHP.

Another possibility would be to hash both sides again, but `\hash_equals()` is preferred.

**Comment by phy25** [comment]
DokuWiki [now requires PHP 5.6+](https://github.com/splitbrain/dokuwiki/blob/master/composer.json), so using `hash_equals()` is just fine.

**Comment by kelunik** [comment]
Oh, that's even better. I'll add a PR.

**Comment by kelunik** [comment]
See #2133.
