### ISSUE TITLE
Can  not upload any file

### ISSUE THREAD

**Issue by glaukos78** [splitbrain/dokuwiki#2135]
I have tried upload files in the dokuwiki and received following error message   ** xx.xxkB Failed**

My version is DokuWiki 2017-02-19e "Frusterick Manners" 
Please for your advice

**Comment by splitbrain** [comment]
Thanks for opening the issue. Unfortunately your issue does not contain enough information. Please try to provide as much info as possible, generally following these three main questions:

* What did you do?
* What did you expect to happen?
* What happened instead?

Please also describe what steps you took to analyze the issue and what (failed) attempts you made to fix the problem yourself.

Your issue should contain everything that might help in analyzing and reproducing the issue. That includes but isn't limited to:

* versions of the involved software
* exact error messages
* debug logs (also check your JavaScript console for web related issues)

Thanks for your help.

PS: You may want to refer to [How to Ask Questions the Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) for more tips on improving your issue creation game ;-)

**Comment by glaukos78** [comment]
Hello, 
In the previous version I had uploaded files (txt, zip,rar) without  any problem.
The problem with upload files I facing is in the current version.
Could you please advise me how I can to export logs files to send you.

Thanks

**Comment by phy25** [comment]
@glaukos78 What does `** xx.xxkB Failed**` means? Is `xx` represents numbers? You can also use browser's developers tools (press F12) to see the exact network request, and see what is exactly returned (Status code, content, etc).

**Comment by glaukos78** [comment]
The ** xx.xxkB Failed** is the file size.
I have check with F12  end return error status 403 (Forbiten

Request URL: http://xxxxxxxxxxx.xxxx/lib/exe/ajax.php?tab_files=files&tab_details=view&do=media&ns=&sectok=6548d4acb&mediaid=&call=mediaupload&qqfile=test_file.txt&ow=false 

Status code: 403 Forbidden

Any idea about above error

**Comment by glaukos78** [comment]
The problem solved it was the mod_serurity,
