### ISSUE TITLE
Table of contents is not created properly

### ISSUE THREAD

**Issue by LMS235** [splitbrain/dokuwiki#2139]
In our wiki we have a page with transaction codes (for SAP, but that doesn't matter) divided into tables with headings A... Z. 

Unfortunately, the table of contents is not always correctly constructed. The first time the page is called, it starts at T, for example. When you press F5, it is usually (not always) correctly assembled. See screenshots.

I can do this in several installations (with php 5.6.30 on Apache, php 7.0.22 on Apache and php 7.1.8 on nginx).

If I use e. g. `~~NOCACHE~~` it is always wrongly built.

First Call or Call with `~~NOCACHE~~`:
![grafik](https://user-images.githubusercontent.com/8693550/31003779-bf9c7e96-a4f1-11e7-8f1b-4946493ffd27.png)

Second Call without `~~NOCACHE~~`:
![grafik](https://user-images.githubusercontent.com/8693550/31003801-de2516a2-a4f1-11e7-9843-2a820b1cf494.png)

**Comment by splitbrain** [comment]
could you copy the page's content to a page in the DokuWiki playground and link it here please?

**Comment by LMS235** [comment]
can I make the text available elsewhere? I don't want to post it to the public completely;)

**Comment by LMS235** [comment]
I have the problem with active sortable (https://www.dokuwiki.org/plugin:sortablejs) plugin on each table. but I can't recreate it on the playground because no sortable installed

**Comment by Klap-in** [comment]
If you don't have sortablejs applied, it is working ok?

**Comment by LMS235** [comment]
Without sortable I have not yet detected the error. The problem is also that it doesn't always occur. And when it occurs, it is fixed by an F5 refresh.

**Comment by phy25** [comment]
So there is no actions we can do at this point, and I am closing this issue. If you have anything to add please feel free to comment.
