### ISSUE TITLE
Unnecessary div elements (and spaces) in lists

### ISSUE THREAD

**Issue by scytho** [splitbrain/dokuwiki#2140]
When you make a list, like so
`  * li1`,
you get this html code:
`<li class="level1"><div class="li"> li1</div></li>`.
That div ist utterly waste, which makes for poor code quality.

The space preceding the text inside the div is there, because I wrote `* li1` instead of `*li1`. Maybe there are good reasons for this behaviour, but I think `* li1` is easier to read than `*li1`.

**Comment by Chris--S** [comment]
The html is structured as it is to allow the bullet to be given a different colour from that of the text.   The standard dokuwiki makes use of this feature to colour the bullets in a lighter grey than the usual text.

The extra whitespace makes no difference (unless you changed the normal whitespace handling).  If you use the list button in the editor it will put that space in for you.
