### ISSUE TITLE
Dokuwki Additional syntax / bitcoin

### ISSUE THREAD

**Issue by bjacquin** [splitbrain/dokuwiki#2153]
Hi,

I see on https://www.dokuwiki.org/donate that you are using additional syntax such as [[bitcoin>.]] as per https://www.dokuwiki.org/teams:documentation:additional_syntax.

I'd like to setup such link to Enlightenment dokuwiki as well, but I can't find where this syntax is available on the main dokuwiki since our installation does not support this. Is it mainstream ? If not, could it be included ?

Thanks!

**Comment by phy25** [comment]
See https://www.dokuwiki.org/interwiki
