### ISSUE TITLE
Config Manager: Plugin config's name appears as a black box

### ISSUE THREAD

**Issue by dregad** [splitbrain/dokuwiki#2154]
In the config manager, each setting's "technical" name is displayed on the list above the description.

![screenshot-20171018-1646](https://user-images.githubusercontent.com/449891/31725233-214b53e2-b424-11e7-8e9b-ebbd95a352da.png)

I realized that DokuWiki sometimes displays a black box instead of the text. This usually occurs in the Plugins section, but not always on the same plugin:

![screenshot-20171018-1652](https://user-images.githubusercontent.com/449891/31725549-eb57e47a-b424-11e7-9574-d284df7d4a91.png)

Furthermore, the behavior seems to depend on the vertical scrolling position... After moving down a bit:
![screenshot-20171018-1654](https://user-images.githubusercontent.com/449891/31725671-36237ce4-b425-11e7-91cd-57693b2ca882.png)

And even more weird, it happens on Firefox, but not on Chrome.

It's not a big deal - display only, and the config page works just fine apart from that, as far as I can tell.

**Comment by splitbrain** [comment]
This looks like a rendering bug in your special Firefox/Graphics Environment. Nothing I have ever seen. Maybe a problem with your Browsers Hardware Acceleration settings? You try disabling it to see if it fixes the problem (Menu -> Options -> Advanced -> General. Uncheck Use hardware acceleration when available)

**Comment by splitbrain** [comment]
no feedback given
