### ISSUE TITLE
video in page

### ISSUE THREAD

**Issue by qwe852147** [splitbrain/dokuwiki#2159]
I insert  more than 10  vidoe  of inter media and each video size around 120Mb.
After saving , videos of the page usually not show and show browser message "Processing Request" in left-bottom.
And I open the same page at the same time ,the new page cannot be open just show empty web untill I close first web page.

**Comment by phy25** [comment]
I guess this is more of a server configuration issue. Maybe it's not working with multi worker processes?

**Comment by qwe852147** [comment]
I tried the number of video from one to more then ten when over eleven this problem will show.

**Comment by qwe852147** [comment]
I find it . It possible to add new option preload in <video> tag? 
This defualt is auto which will cause problem when video is to many.
https://github.com/splitbrain/dokuwiki/blob/e1c5b79f58f3b5dfcd4d8c932a6503dfde41ff53/inc/parser/xhtml.php#L1821
