### ISSUE TITLE
Allow the link to the syntax page to be set in config

### ISSUE THREAD

**Issue by kruff-a-lon** [splitbrain/dokuwiki#2167]
Hi,

I've set up a wiki in a sub-directory called wiki, so I want to remove the default namespace 'wiki', mostly this is not an issue.

_The idea is that I want a collection of sites for a specific purpose: [purpose.example.com](purpose.example.com) and one of those purposes is a wiki at [purpose.example.com/wiki](purpose.example.com/wiki) and then I also want other tools in [purpose.example.com/tool1](purpose.example.com/tool1), [purpose.example.com/tool2](purpose.example.com/tool2), etc_

I created a custom syntax page (as per the suggestion on [Getting Started - Best Practices](https://www.dokuwiki.org/tips:tailorwikirules) that I link to elsewhere but I also wanted to make it the default syntax page, that is linked from the editor. I had to dig through quite some files to find where the link to the default syntax page is created (for when you are editing a page) and change it to my syntax page.

This is not a big thing, and maybe having too many config-options is worse than having the admin of a wiki edit a file, but then at least the documentation could be updated to include instructions on how to it.

**Comment by splitbrain** [comment]
You can change the link to the syntax page by creating your own version of `lang/<lc>/edit.txt` as described in https://www.dokuwiki.org/localization#changing_some_localized_texts_and_strings_in_your_installation
