### ISSUE TITLE
Please add classes to elements with IDs

### ISSUE THREAD

**Issue by bitstarr** [splitbrain/dokuwiki#2172]
As designer/front end developer I won't style any ID, because that's not how we do frontend in 2017.

https://github.com/splitbrain/dokuwiki/blob/0f8cc87bd3c00da5e455ea3abf06e9893c9b9d70/inc/html.php#L2102
Please replace ``<div id="dw__toc">`` with ``<div id="dw__toc" class="dw__toc">``

Or provide ways to hook the output or at least to add classes.

**Comment by Klap-in** [comment]
Good idea. A pull request is welcome of course :)

**Comment by bitstarr** [comment]
You are right, but at the moment I'm trying to build a template and I have no experience with the code of dokuwiki. I simply saw the shortcomings for providing quality styling.

I hope someone who is more involved will help out.

**Comment by Klap-in** [comment]
If you spot more, please add them here :)

**Comment by krisak** [comment]
@bitstarr It makes perfect sense to just use ID there. TOC is unique element.

I would argue that it is against "how we do frontend in 2017" to just duplicate ID name into class because it just spams html. Seems a bit demagoguery.

Is specificity a problem or what?

**Comment by bitstarr** [comment]
Yes, specifity is still a big deal for writing sane and reusable CSS. Also the spearation of concerns is a best practice.

**Comment by mprins** [comment]
@bitstarr It's your itch, please either scratch it by providing a PR or enjoy it in silence.

**Comment by DeathCamel57** [comment]
Will this work @bitstarr?

**Comment by DeathCamel57** [comment]
Sorry about the first PR, I totally forgot to add a fix branch to my fork.

**Comment by bitstarr** [comment]
This looks nice. Thanks for the effort @DeathCamel57!

**Comment by DeathCamel57** [comment]
Anytime @bitstarr!

**Comment by Klap-in** [comment]
Implemented by #2178
