### ISSUE TITLE
.htaccess.dist line still useful?

### ISSUE THREAD

**Issue by bttrx** [splitbrain/dokuwiki#2181]
`## Enable this to restrict editing to logged in users only`

What does "this" mean?

**Comment by phy25** [comment]
This seems to have existed since 2005 when the file is first edited in Git:
https://github.com/splitbrain/dokuwiki/blob/65c9a6432594d03159c83e61ec4954a6da1b8d5b/.htaccess.dist#L1

**Comment by Chris--S** [comment]
I don't think the comment makes sense any more.  User access is controlled through auth modules and access control lists (acl), both of which are controlled via dokuwiki's administration interface.  The htaccess file applies to Apache based dokuwiki installations which wish to use "nice urls".  For instructions on using user authentication and acls refer to dokuwiki.org.  For information on using nice urls refer to the configuration settings at dokuwiki.org

**Comment by bttrx** [comment]
@splitbrain: Then please remove this line.
