### ISSUE TITLE
Save fails when page contains more than 26669 chars

### ISSUE THREAD

**Issue by NoodleBB** [splitbrain/dokuwiki#2213]
When a page contains more than 26669 chars, then saving an edit fails.

**Comment by phy25** [comment]
What error message? What server are you using? Guess this is a server misconfiguration issue.

**Comment by NoodleBB** [comment]
Sadly there's no error message. Just a blank page. 
Server Apache 2.2

**Comment by splitbrain** [comment]
Please see https://www.dokuwiki.org/faq:blankpage You need to find the error message!

Your problem is probably caused by limits to the POST body or variable sizes in your PHP or Apache configuration.

**Comment by NoodleBB** [comment]
That's the error
> PHP Fatal error:  Maximum execution time of 30 seconds exceeded

**Comment by splitbrain** [comment]
Hmm there's no reason a page save should take that long. It seems something is taking more time than it should. However I don't see how this should happen at exactly 26669 chars.

Please provide more detailed info. See https://www.dokuwiki.org/bugs#report_a_bug
