### ISSUE TITLE
Using  $$PRINT or $$STACK in source text remove some parts in rendered output,

### ISSUE THREAD

**Issue by nutilius** [splitbrain/dokuwiki#2214]
If  I embed $$PRINT or $$STACK strings in dokuwiki, part of rendered  text will disappear.
For example seqeunce: 

```
==== ICCF areas ====
Each ICCF terminal user has different areas:
  * Input area - represents reader for 
  * Print area ($$PRINT)
  * Punch area ($$PUNCH)
  * Edit stack area ($$STACK)
  * Log` area ($$LOG)
```

display only:
`
ICCF areas

Each ICCF terminal user has different areas:

    Input area - represents reader for
    Print area (PUNCH)
    Edit stack area (LOG)
`

**Comment by splitbrain** [comment]
Works fine for me: https://www.dokuwiki.org/playground:issue2214

Maybe you have plugin installed that uses ``$$`` as a syntax element?
