### ISSUE TITLE
bundled styling plugin allows saving empty color, which crashes LESS/CSS parser

### ISSUE THREAD

**Issue by bcristian** [splitbrain/dokuwiki#2246]
In the Template Style Settings, set a color to nothing (i.e. an empty input), and save.
It will crash the LESS/CSS parser, as the saved value in conf/tpl/[...]/style.ini will be empty, e.g. __link__ = ""

P.S. I know this is actually a plugin, but I could not find it's own repository or issues tracker, and considering the author I though this would be the next best place.

**Comment by Klap-in** [comment]
* [ ] A very minimal check can be added by adding the `required` attribute to the input fields. 

But that prevents only empty values, not wrong values. wrong values will stop the parser as well.

For more complete checks the plugin should know what kind of value a placeholder is (at the moment color or size, but I think template developers are free in there choice of placeholder usages). 

I think a more elaborate input test is not that urgent and maybe not needed, if looking at the consequences: the less parser breaks, but you will see that immediately and you can directly input new values to fix the situation.

**Comment by bcristian** [comment]
Making the fields required would actually help a lot. I found this bug as a non-technical colleague accidentally cleared one of the color fields (probably by clicking the small "x" clear button in the input), without noticing it, as the UI allows it without any prompts. And then I had to fix it, and although I am a programmer I have no knowledge of the code and don't work in this field.
This would have been much easier if the LESS parser would have logged errors somewhere, including a file name and line. I don't know how feasible this would be, or maybe it could already be configured to do so, but since I don't work in web programming it's been a google-intensive couple of hours.

**Comment by mprins** [comment]
html5 provides the input type "color" eg. `<input type="color" name="colorField"/>` which would probably be the best option (it defaults to `#000000` for no value

see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

**Comment by Klap-in** [comment]
Then also some hinting is needed in the style.ini for the styling plugin, such that it choices the right input type. 

Or is type guessing from the original style.ini from the template folder feasible?

(current values are css lengths or colors, but template developers can add anything as placeholer in style.ini)

**Comment by splitbrain** [comment]
@Klap-in This kind of hinting is already done. We display the color picker for colors only.

**Comment by Klap-in** [comment]
Ah indeed! nice
