### ISSUE TITLE
Wiki Syntax colouring in editor (on the fly, testversion presented)

### ISSUE THREAD

**Issue by rjmaris** [splitbrain/dokuwiki#2255]
Sampe of the test output:
![dwedit-colouring](https://user-images.githubusercontent.com/1149309/36196951-3c06cd44-116a-11e8-8ca6-95775bd17047.png)
The work is based on a **small jquery** project, namely https://www.jqueryscript.net/text/jQuery-Based-Text-Highlighter-For-Textarea.html
Notes:
1. This work is not carried out as plug-in, because it is firstly a _quick&dirty_ test, also due to lacking deep knowledge of underlying stuff.
1. I treat this stuff as a sort of wiki editor usability and readability enhancer, especially with modifying text on existing pages in mind. This may well serve as an alternative to **ckgedit** and its clones, since this solution does not suffer from wiki text changes not edited by the user, because of absence of any html to wiki conversion upon text save.
1. A couple of buttons have gone, due to possible name conflicts (see below).
1. The window resizing must be regained (due to applying a basic overlaying technique without overlaying scrollbars).

Before doing the work, I investigated in several `textarea` on-the-fly syntax hightlighters, but some of that stuff don't operate correctly (or at all) on older browsers.

Details: see follow-up posting. The mentioned problem issues are discussed there, too.

**Comment by rjmaris** [comment]
Steps to establish the wiki syntax colouring as shown in the screenshot (you can apply it on existing pages):
add the 5 files according to attached ZIP file where its directory structure is reflected such that you could unpack it in the target wiki.
Replace `form_wikitext` in `inc/form.phl by next stuff, at least the return statement:
```php
function form_wikitext($attrs) {
    // mandatory attributes
    unset($attrs['name']);
    unset($attrs['id']);
    return '   <link rel="stylesheet" href="inc/highlighter.css">
<div id="highcontainer"><div class="formatlayer"><textarea name="wikitext" id="wiki__text" class="target" dir="auto" '
                 .buildAttributes($attrs,true).'>'.DOKU_LF
                 .formText($attrs['_text'])
                 .'</textarea></div></div>
<script src="lib/scripts/jquery/jquery.min.js"></script>
<script src="lib/scripts/jquery/highlighter/trie.js"></script>
<script src="lib/scripts/jquery/highlighter/helper.js"></script>
<script src="lib/scripts/jquery/highlighter/jquery.textarea-highlighter.js"></script>
<script src="inc/highlighter.js"></script>';
}
```
The line `<script src="lib/scripts/jquery/jquery.min.js"></script>` actually switches the functionality on and off, but when included, a couple of buttons on top of the edit windows are gone.

The three lines below that originate from the small jquery project mentioned in the start posting of this issue.

Currently, the highlighter script looks like this:
```javascript
$(function(){
  'use strict';

  $('.formatlayer').find('.target')
    .textareaHighlighter({
      matches: [
        {'matchClass': 'htmltagHi', 'match': /\<.*?\>/g, 'priority': 3}, // doesn't work with added < and >
        {'matchClass': 'specialHi', 'match': /~~.*?~~/g, 'priority': 3},
        {'matchClass': 'textattrHi', 'match': /(\/\/|__|\*\*).*?(\1)/g, 'priority': 3},
        {'matchClass': 'headerHi', 'match': /===* .* ===*/g, 'priority': 3},
        {'matchClass': 'pipeHi', 'match': /\|/g, 'priority': 5},
        {'matchClass': 'imageHi', 'match': /\{\{.*?\}\}/g, 'priority': 1},
        {'matchClass': 'linkHi', 'match': /\[\[.*?\]\]/g, 'priority': 1}
      ]
    });
});
```
*Cont'd in the final third posting.*

**Comment by rjmaris** [comment]
https://www.cdolivet.com/editarea/editarea/exemples/exemple_full.html
One of the projects that was taken into account as to adapt it for dokuwiki was EditArea 0.8.2, which runs fairly well, also on older browsers, in contrast to more recent stuff, e.g. CodeMirror or highlight-ta.

The example (link) shows that enhancing the view is not limited to background stuff, but also text colouring is possible - as numerous web based text editors actually show.
Example 1 on top features a checkbox ("Toggle editor") below the editor window, where you can switch on&off the overlay, and see the naked `textarea` box.

I was almost going to use this resource, as it would include the ability to resize the overlay. But since it seems not that easy to remove the decorations on top and bottom of the text window in this example, I looked further, as is documented above.

**Comment by splitbrain** [comment]
https://github.com/marexandre/jquery.textarea-highlighter.js looks interesting indeed and might be a good lightweight alternative to full blown WYSIWYG editors. Since this is based on simple regex matching instead of a proper parser, it will occasionally fail highlighting correctly (eg. when a syntax is used within a code block).

Implementing this as a simple JavaScript-only plugin should be relatively straightforward and I encourage you to do so. I don't see this as a core functionality though.

**Comment by rjmaris** [comment]
Hm, javascript-only. That means that javascript shall allow the repacking of elements (here: textarea) within a newly added container while the page has been loaded.

Anyhow: I'd appreciate it when javascript & dokuwiki plugin nerds take care of creating a plugin, of course taking the two testversion flaws (failing a couple buttons + failing box resize) into account. I'd be able to engage in some finetuning (e.g. extend with additional regexps).
I'm not a web programmer at all. I don't even know what jquery does or which function is the caller of `form_wikitext` (no reference found outside of `form.php`).

**Comment by micgro42** [comment]
It might be useful to have a look at https://www.dokuwiki.org/plugin:codemirror . Maybe this already does what you need?

**Comment by rjmaris** [comment]
Yes it does, even colouring of text and true representation of italic & bold text. However where the `**` with bold text is included in the bold representation, the `[[` does not include it. But for sure that's the smaller problem.

Some remarks:
1. It's all in the name. Nobody, seeking for a certain functionality, will find what he seeks when searching using e.g. the phrase `syntax`. Meanwhile I've added this as tag to this plugin. Moreover: now (alas not earlier) I'm aware that a generic plugin page exists where you can filter. Would be nice when a **link to that page** on `admin->maintain extensions->search&install` would exist.
1. Codemirror conflicts with ckgedit (you'll see two edit windows, one showing the underlying html code).
1. I'd use it when no conflicts would arise and customizability is easy. BTW: probably the simplicity of the proposal speaks for this, too.

**Comment by fstorck** [comment]
I would really appreciate an lightweight syntax highlighting in the editor for links, headlines etc. since editor plugins like CodeMirror tend to conlict with other really useful extensions like Dropfiles or search an d replace etc. Switching between the editor engines is rather annoying, but I really miss it when I have to to add media files to a page. The other solution would be only a kind of editing API to avoid conflicts when changing the internal editor by a plugin. But this is probably much more work with no real benefits in most cases.

**Comment by splitbrain** [comment]
I am closing this issue. As I said, this will not be added as a core function. Making it a plugin would be great, but is beyond the scope of this issue tracker.
