### ISSUE TITLE
Which is the correct value for $conf['proxy']['host'] ?

### ISSUE THREAD

**Issue by tormec** [splitbrain/dokuwiki#2259]
This is a merely technical question just to better understand how the `$conf['proxy']['host']` works, since I managed to solve the problem 

> "The plugin repository could not be contacted. Make sure your server is allowed to contact www.dokuwiki.org and check your proxy settings."

every time I tried to download a plugin.

In particular, my DokuWiki is hosted in a free web hosting  which doesn't work under any proxy server (or at least this is what I believe) and the only way to allow the download of a plugin is to set the `$conf['proxy']['host']` to any value not null (see image below), while here https://www.dokuwiki.org/config:proxy it is said that it must be 

> "The IP or hostname of the proxy server to use"

![conf-proxy-host](https://user-images.githubusercontent.com/10964663/36349830-f7f475ae-148c-11e8-8bc5-5ae8bee43976.png)

**Comment by phy25** [comment]
https://github.com/splitbrain/dokuwiki/blob/2f139f9517a75268269c73da8746f3d577137cf3/inc/HTTPClient.php#L188-L209

That's weird. Maybe your web hosting doesn't support `fsockopen()`? And maybe you can try installing a new instance of DokuWiki (i.e. use the latest code) and using the plugin manager again (may have no difference, anyway)?

**Comment by tormec** [comment]
I verified and the web hosting that I'm using supports 'fsockopen()'. It's very strange that is sufficiently any non empty value for '$conf['proxy']['host'] ' to bypass the above-mentioned issue.
