### ISSUE TITLE
css.php:169 - removed [ ] -operator

### ISSUE THREAD

**Issue by gitstupid** [splitbrain/dokuwiki#2264]
Hello,
I found a problem in  my css.php:
`
[Mon Feb 26 07:26:10.994926 2018] [php7:error] [pid 445] [client 127.1.84.1:57540] PHP Fatal error: 
 Uncaught Error: [] operator not supported for strings in /usr/share/dokuwiki/lib/exe/css.php:169
Stack trace:
#0 /usr/share/dokuwiki/lib/exe/css.php(140): css_parseless('@ini_text: #fff...')
#1 /usr/share/dokuwiki/lib/exe/css.php(18): css_out()
#2 {main}
 thrown in /usr/share/dokuwiki/lib/exe/css.php on line 169
`
So I got the response-code 500.

I use 
Server version: Apache/2.4.29 (Debian)
PHP 7.2.2-1 
Plugin: indexmenu
Plugin: catlist
Plugin: styling plugin by Andreas Gohr

at first i tried of course to disable the plugins (styling plugin) but it didnt change anything .

After checking my configuration for hours and testing, i tried to understand PHP....

in line 169 i found : `$less->importDir[] = DOKU_INC;`
if i change it in `$less->importDir = DOKU_INC;`
everything looks fine. I don't know anything about PHP, but perhaps I found a bug?

**Comment by mprins** [comment]
time to upgrade, you're running the "old-stable" which pre-dates php 7.2
