### ISSUE TITLE
OpenSSL Error messages: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by mrclschstr** [splitbrain/dokuwiki#2265]
Hi everyone,

since Github disabled TLSv1/TLSv1.1 (see: https://githubengineering.com/crypto-removal-notice/) I'm not able to install plugins directly via the Plugin Manager any more.

I figured out that you can change `STREAM_CRYPTO_METHOD_TLS_CLIENT` to `STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT` in [HTTPClient.php](https://github.com/splitbrain/dokuwiki/blob/master/inc/HTTPClient.php#L539) to keep it running.

Anybody else experiencing this issue?

**Comment by phy25** [comment]
I can install wrap plugin (from GitHub) on Windows PHP 7.1.4, just now.

Actually the line you mentioned is in "SSL tunnel" function. It only triggers when you have set `$conf['proxy']`. What's more, the line of `STREAM_CRYPTO_METHOD_TLS_CLIENT` is only effective within PHP 5.6.0 - PHP 5.6.6. Just wondering whether you are using the latest code and your configuration.

https://github.com/splitbrain/dokuwiki/blob/081d7365a19e65810b237098556fc1ff03ff0c57/inc/HTTPClient.php#L536-L543

**Comment by mrclschstr** [comment]
I'm actually using a proxy. Sorry, I schould have mentioned that before...

I just realised that my `HTTPClient.php` looks slightly different than the version in the master. I have to carefully check my Dokuwiki version tomorrow.

**Comment by mrclschstr** [comment]
I have the latest 2017-02-19e "Frusterick Manners" version installed. The lines you mentioned were modified in https://github.com/splitbrain/dokuwiki/commit/f7813a6826e073e65a6fe7b667c199aa1e660e47 which apparently are not included in the latest stable build.

What can I do? Is it safe to update to the latest snapshot build? Maybe it's time for a new stable release of Dokuwiki :wink:

**Comment by phy25** [comment]
You can just cherry-pick the commit you mentioned, and I think the issue can be resolved ([in newer PHP  `STREAM_CRYPTO_METHOD_TLS_CLIENT` = TLSv1 only, without v1.2](http://php.net/manual/en/function.stream-socket-enable-crypto.php#119122)).

It's rather safe to use the master, but you can wait for the next stable release (in several months, I guess) if you don't want to be risky.

**Comment by Klap-in** [comment]
The open issues which needs attention for the release are https://github.com/splitbrain/dokuwiki/milestone/4
