### ISSUE TITLE
Updated authmysql to mysqli

### ISSUE THREAD

**Issue by NFGman** [splitbrain/dokuwiki#2276]
I run an SMF forum which uses a custom Simple Machines Forum auth plugin, along with the authmysql plugin.  But when upgrading to PHP7, everything died.  PHP7 has deprecated MYSQL_ in favour of MYSQLI_, which is just different enough to break everything.

There was a partial fix on the dokuwiki site already, and I've used that as a starting point for what is a dangerously hacked up mysqli-compatible version.  I've posted it on the dokuwikiwiki:

https://www.dokuwiki.org/plugin:authmysql#php_7_mysqli

I don't know if this is worth anything to anyone else. I detailed the bit I'm not sure about at that link, and it works for me.

**Comment by splitbrain** [comment]
authmysql is deprecated in favor of authpdo.
