### ISSUE TITLE
startSectionEdit changes missing documentation

### ISSUE THREAD

**Issue by selfthinker** [splitbrain/dokuwiki#2290]
The section edit refactoring (#2220) broke a couple of plugins.
Plugins affected will show this error message:

> startSectionEdit: $data is NOT an array!

selfthinker/dokuwiki_plugin_wrap#162 is an example of how that is fixed and also made backwards-compatible.

Ideally that should be documented somewhere, either in the wiki or in here. The minimum should be linking wherever it is documented from [DokuWiki's changelog](https://www.dokuwiki.org/changes).

**Comment by selfthinker** [comment]
Ah, just found this wiki page which should also be updated: https://www.dokuwiki.org/devel:section_editor

**Comment by LarsGit223** [comment]
Done. I updated the [changelog](https://www.dokuwiki.org/changes) and the [devel:section_editor](https://www.dokuwiki.org/devel:section_editor) page.

**Comment by Klap-in** [comment]
Please see for examples how to fix a plugin:
https://github.com/dokufreaks/plugin-include/commit/de790317615bccbc2a2276b1d8c455e2ae5a9090
https://github.com/selfthinker/dokuwiki_plugin_wrap/pull/162
