### ISSUE TITLE
Hitting Return on Edit Summary tries to delete the page

### ISSUE THREAD

**Issue by andygates-nhs** [splitbrain/dokuwiki#2298]
Problem: In the wysiwig editor, if you finish an edit by entering text in the Edit Summary field and hit Return, it brings up a deletion confirmation (with "OK" selected).  This is a page-eating trap, as unthinking confirmations are a thing.

Expected: It should do a save, not a delete. 

(Chrome, IE and Firefox)

**Comment by splitbrain** [comment]
there's no wysiwyg editor in core (and no delete button). should be reported to the plugin's bugtracker.

**Comment by andygates-nhs** [comment]
Thanks, I've raised it in the right place.
