### ISSUE TITLE
Greebo: load.php error on line 110

### ISSUE THREAD

**Issue by jmcouffin** [splitbrain/dokuwiki#2328]
Hi there, 
after upgrading to Greebo, I got the error load.php on line 110, could not load plugin.php and could not see my DW anymore.

I fixed it by copy pasting the missing plugin.php from a previous snapshot and it all went well but you might want to check it out as I do get why it is suppressing the inc/plugin.php

**Comment by jmcouffin** [comment]
Current PHP version: 7.1.1

**Comment by Klap-in** [comment]
https://github.com/splitbrain/dokuwiki/blob/8ca3665ea10b9e2b70b6a87462685e577510eb15/data/deleted.files#L12

https://github.com/splitbrain/dokuwiki/blob/8ca3665ea10b9e2b70b6a87462685e577510eb15/inc/load.php#L87

`inc/plugins.php` is replaced by `inc/Plugins.php`.

What was your procedure to do the upgrade of your DokuWiki installation?

**Comment by jmcouffin** [comment]
> What was your procedure to do the upgrade of your DokuWiki installation?

I went through the upgrade process of @splitbrain dokuwiki upgrade plugin

![image](https://user-images.githubusercontent.com/7872003/39113021-95d54936-46da-11e8-99e4-97ef999975ef.png)

**Comment by mprins** [comment]
Are you using a windows file system eg. NTFS? (this may be an issue with case-agnostic, but not case-sensitive filesystems)

**Comment by Klap-in** [comment]
If you add `?do=check` (or `&do=check`) to an url, does it provide information about your setup?

**Comment by jmcouffin** [comment]
i get this 
![image](https://user-images.githubusercontent.com/7872003/39115721-e0d6e61c-46e2-11e8-90ec-bc3e56e3ae4c.png)

**Comment by mprins** [comment]
It's a touch cookie, using eg Explorer you cannot even rename the file.

**Comment by splitbrain** [comment]
The problem has been fixed in https://github.com/splitbrain/dokuwiki-plugin-upgrade/commit/7b7da9aa0b4871c2238e7ba2388f2f63c61c5f17

**Comment by bgx4k3p** [comment]
I am getting the same error on MacOS 10.13.4 with the latest plugin and PHP 7.1.14. Any ideas?

dokuwiki/inc/Plugin.php): failed to open stream: No such file or directory ... /dokuwiki/inc/load.php on line 110

**Comment by splitbrain** [comment]
For everyone having this problem:

* delete any existing `inc/plugin.php` (lower case P)
* download https://raw.githubusercontent.com/splitbrain/dokuwiki/stable/inc/Plugin.php and place it as `inc\Plugin.php` (upper case P)

Next time you upgrade keep in mind that files in `data/deleted.files` are case sensitive. The upgrade plugin has been fixed to take care of that for you. If you manually delete files you have to ensure case sensitivity yourself.

**Comment by splitbrain** [comment]
See also #2359 for continued discussion on this topic.
