### ISSUE TITLE
todo: Replace css_styleini() in lib/tpl/index.php

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki#2330]
DokuWiki still uses in a template related file the function `css_styleini()`.
(found it by code search, not tested)

https://github.com/splitbrain/dokuwiki/blob/851f9842d7d7f016130f7e99e55a2d0e58ea20aa/lib/tpl/index.php#L46-L49

**Comment by micgro42** [comment]
Tested it: broken. (I didn't even know we had that functionality 😕 )
