### ISSUE TITLE
Wish: Save/Reset buttons in-between the individual sections of the Configuration Manager

### ISSUE THREAD

**Issue by fthommen** [splitbrain/dokuwiki#2337]
Currently the only way to save changed DokuWiki settings is to scroll down to the bottom of the Configuration Manager and to klick the "Save" button.  This is cumbersome and a long way on installations with lots of installed plugins (and not all keyboards have an easily reachable "Go to Bottom of Page" key). It would be nice to have Save/Reset buttons in-between each section of the Configuration Manager.

It coule be discussed if these buttons should save/reset globally or only the settings of the section above.

**Comment by Klap-in** [comment]
I think the buttons should save everything and expire the caches like the current saving does. Otherwise a lot of confusion is created.

Please further see also https://github.com/splitbrain/dokuwiki/issues/764

**Comment by fthommen** [comment]
ok for me.  I'll continue to follow #764
