### ISSUE TITLE
(Greebo)"...is NOT an array! One of your plugins needs an update." - Solution

### ISSUE THREAD

**Issue by borgendorf** [splitbrain/dokuwiki#2339]
I just upgraded (and got bit by the Windows "Plugin.php" vs. "plugin.php" bug) but then saw several messages like "startSectionEdit: $data "plugin_include_start" is NOT an array! One of your plugins needs an update." at the top of all my pages. A search found a German forum that identified the Include plug-in as the source of the error. The solution for me (and I hope for others) was to click Re-Install next to Include. After I did that, so far, so good!

Thanks for the update, and for all you do on Dokuwiki.

**Comment by micgro42** [comment]
Thank you! While the include plugin already contains the fixes, I just now updated its version number. Hopefully it will start showing up as updateable to people.
