### ISSUE TITLE
Lost breadcrumbs on start page with Greebo

### ISSUE THREAD

**Issue by Misterkeros** [splitbrain/dokuwiki#2345]
Hello,

My breadcrumbs were fully fonctionnal on Frusterick Manners.

When I upgrade to Greebo, the breadcrumbs line disapears with the default template. It disapears only on start pages. For example :

category 1
     - start = breadcrumbs line disapears
     - page 1 = breadcrumbs line visible
     - page 2 = breadcrumbs line visible
category 2
     - start = breadcrumbs line disapears
     - page 1 = breadcrumbs line visible
     - page 2 = breadcrumbs line visible

The line also disapear when I go to the administration panel.

I tried with a new installation starting from scratch, it is the same.

Is there a problem with my configuration ?
Thanks for your answers

**Comment by Klap-in** [comment]
Is this related to https://github.com/splitbrain/dokuwiki/issues/2325?
