### ISSUE TITLE
Problem after update (PHP Parse error)

### ISSUE THREAD

**Issue by gerhro** [splitbrain/dokuwiki#2348]
Problem after update to Version: "2018-04-22 "Greebo"
`HTTP ERROR 500`

> 2018/04/25 10:33:49 [error] 1794#0: *8 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in    PATH_TO_WIKI/inc/ActionRouter.php on line 95" while reading response header from upstream, client: 172.16.128.11, server: HOSTNAME, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "HOSTNAME"

It happens on this setup:

> os	CentOS Linux release 7.4.1708
> webserver	nginx/1.12.2
> php_version	PHP 5.4.16 (fpm-fcgi) (built: Mar  7 2018 13:36:16)

**Comment by splitbrain** [comment]
new release requires PHP 5.6
