### ISSUE TITLE
Page Syntax shoulsd link to syntax highlighting details

### ISSUE THREAD

**Issue by LarsGit223** [splitbrain/dokuwiki#2352]
The page Syntax should link to the page Syntax Highlighting Details, see https://www.dokuwiki.org/wiki:syntax_highlighting_details. (I have no permission to do this on my own)

**Comment by Michaelsy** [comment]
Suggestion: I've created for your issue page: https://www.dokuwiki.org/wiki:syntax_mirror so you can make your desired changes there. And someone with enought permission can "merged" the new.

**Comment by Michaelsy** [comment]
Ok, these information should be merged to the syntax page at prominent position.

**Comment by Michaelsy** [comment]
... I will do these job.

**Comment by Klap-in** [comment]
This page is included in every installation. Is it really useful for every person that starts reading (the first time) the syntax page to get this as important message from the syntax page? I would consider to be careful with the attention of our readers. 

Of course it is bit cumbersome if you have to edit this (the first time), that you have to discover the edit approach via via... 

I think that is the challenge of writing (this kind of manuals in general, and) of this important page for more groups of readers. (from people new to DokuWiki who first time read this vs. people like you and me that help maintaining DokuWiki)

**Comment by Klap-in** [comment]
Please use the doku interwiki syntax for creating the link. If you use `[[doku> ... ]]` then the urls in every installation will be correct pointing to dokuwiki.org.

**Comment by Michaelsy** [comment]
> This page is included in every installation.

I totally agree. Of course the "cannot edit information" should / must not be shown in every installation. It is a meta information only correct at www.dokuwiki.org.
