### ISSUE TITLE
[DokuWiki.org] To take a note on the wiki syntax page (dokuwiki.org only)

### ISSUE THREAD

**Issue by Michaelsy** [splitbrain/dokuwiki#2364]
Maybe it's a good idea to place a note on the wiki syntax page (dokuwiki.org only) that the page is blocked and how to make changes on it. Something like [this](https://www.dokuwiki.org/sandbox:playground:michaelsys_syntax#this_wiki_page_is_blocked).
(would fix #2352 )

Furthermore I would suggest to inform the user about the reason of blocking. (Maybe in a footnote?) Is the reason to keep in sync the syntax page on dokuwiki.org with the syntax page in the core?

**Comment by Klap-in** [comment]
The entire syntax page is included in every installation. For these readers this message is meaningless...

**Comment by Michaelsy** [comment]
> The entire syntax page is included in every installation. For these readers this message is meaningless...

Do you have read what I already wrote in #2352 to you?:

> I totally agree. Of course the "cannot edit information" should / must not be shown in every installation. It is a meta information only correct at www.dokuwiki.org.

With "dokuwiki.org only" (mentioned above) I mean: My indented message should be placed only and exactly [here at that syntax page in dokuwiki,org](https://www.dokuwiki.org/wiki:syntax). (Again: It would fix #2352)
