### ISSUE TITLE
Uncaught Error: Class 'lessc' not found in [...]/lib/exe/css.php:186

### ISSUE THREAD

**Issue by sychron** [splitbrain/dokuwiki#2368]
After auto upgrating to Grebo, my main style sheet is broken. I turned on php error logging, and it tells me that in css.php, lessc is unknown.

I looked over other Grebo issues (the P/plugin.inc one) and saw there should be a lessc.inc -- which is not present neither in my filesystem, nor in the current stable release.

So my main stylesheet is broken right now and I don't know how to fix it.

**Comment by splitbrain** [comment]
Please post the exact error message. It sounds to me that your update was incomplete. `lessc` should be defined by `vendor/marcusschwarz/lesserphp/lessc.inc.php` which is autoloaded.

**Comment by sychron** [comment]
[03-May-2018 15:20:27 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'lessc' not found in [...]/lib/exe/css.php:186
Stack trace:
#0 [...]/lib/exe/css.php(158): css_parseless('@ini_text: #333...')
#1 [...]/lib/exe/css.php(18): css_out()
#2 {main}
  thrown in [...]/lib/exe/css.php on line 186

[...] is the wiki path in the file system -- shortened here for security reasons.

**Comment by sychron** [comment]
I had a look at my server: vendor/marcusschwarz was not present after the update.
In fact, I was missing marcusschwarz, aziraphale, openpsa, and paragonie in the vendor subdirectory compared to the stable release downloaded for comparison

**Comment by splitbrain** [comment]
Check your vendor directory. Try restarting your PHP interpreter (apache/mod_php or php-fpm)

**Comment by sychron** [comment]
see my comment above: I'm missing several vendors. I'm currently backing up my vendor directory, planning to completely replace it with the one from the stable release
