### ISSUE TITLE
Configuration manager not showing all settings

### ISSUE THREAD

**Issue by kmlucy** [splitbrain/dokuwiki#2372]
I just updated to Greebo, and now my configuration manager does not display all my settings. The 'Basic', 'Display', and 'Authentication' sections are there, but at least the template and plugin settings are not. The save button is also not on the page. 

Here is the relevant section of my NGINX log:
```
[php-fpm:access] 127.0.0.1 -  04/May/2018:13:17:58 -0400 "GET /doku.php?id=start&do=admin&page=config" 200 /app/doku.php 16.318 2048 122.56%
2018/05/04 13:17:58 [error] 68#68: *74 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot access protected property
admin_plugin_config::$localised in /app/lib/plugins/config/settings/extra.class.php:184
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Cannot access prot
ected property admin_plugin_config::$localised in /app/lib/plugins/config/settings/extra.class.php:184"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "Stack trace:"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "#0 /app/lib/plugins/config/admin.php(151): setting_disableactions->html(O
bject(admin_plugin_config), false)"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "#1 /app/inc/template.php(186): admin_plugin_config->html()"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "#2 /app/inc/Action/Admin.php(53): tpl_admin()"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "#3 /app/inc/template.php(98): dokuwiki\Action\Admin->tplContent()"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "#4 /app/inc/events.php(111): tpl_content_core('admin')"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "#5 /app/inc/events.php(256): Doku_Event->trigger('tpl_content_cor...', tr
ue)"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "#6 /app/inc/template.php(83): trigger_event('TPL_ACT_RENDER', 'admin', 't
pl_content_cor...')"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "#7 /app/lib/tpl/bootstrap3/main.php(97): tpl_content(false)"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "#8 /app/inc/actions.php(27): include('/app/lib/tpl/bo...')"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "#9 /app/doku.php(120): act_dispatch()"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "#10 {main}"
[04-May-2018 13:17:58] WARNING: [pool www] child 94 said into stderr: "  thrown in /app/lib/plugins/config/settings/extra.class.php on line 184"
Stack trace:
#0 /app/lib/plugins/config/admin.php(151): setting_disableactions->html(Object(admin_plugin_config), false)
#1 /app/inc/template.php(186): admin_plugin_config->html()
#2 /app/inc/Action/Admin.php(53): tpl_admin()
#3 /app/inc/template.php(98): dokuwiki\Action\Admin->tplContent()
#4 /app/inc/events.php(111): tpl_content_core('admin')
#5 /app/inc/events.php(256): Doku_Event->trigger('tpl_content_cor...', true)
#6 /app/inc/template.php(83): trigger_event('TPL_ACT_RENDER', 'admin', 'tpl_content_cor...')
#7 /app/lib/tpl/bootstrap3/main.php(97): tpl_content(false)
#8 /app/inc/actions.php(27): include('/app/lib/tpl/bo...')
#9 /app/doku.php(120): act_dispatch()
#10 {main}
  thrown in /app/lib/plugins/config/settings/extra.class.php on line 184" while reading upstream, client: <IP>, server: , request: "GET /
doku.php?id=start&do=admin&page=config HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "<URL>", referrer: "<URL>"
```

**Comment by Michaelsy** [comment]
Do you upgrade with the upgrade manager?

**Comment by kmlucy** [comment]
No. I run in a Docker container, so the container just rebuilt with the new version.

**Comment by Michaelsy** [comment]
Maybe...
If you do not use the upgrade manager then it could be appears a problem with the capitalization of filenames: #2328 #2340 #2359

**Comment by splitbrain** [comment]
@Michaelsy please refrain from wild guesses in bug reports.

@kmlucy seems like you're hitting some fatal error, which simply interrupts the rendering of the config manager and you end up with only half of it. Judging from your error logs, it seems something tried to access a protected variable.

Since this doesn't happen for me I assume it's triggered by one of your installed plugins, but I can't figure out which one from the stack trace above.

Could you try disabling all 3rd party plugins and reenable them one by one and report back?

**Comment by micgro42** [comment]
As @kmlucy just wrote, the wiki was not upgraded, but the Docker container was rebuild with the new version.

> PHP Fatal error:  Uncaught Error: Cannot access protected property admin_plugin_config::$localised in /app/lib/plugins/config/settings/extra.class.php:184"

We started to refactor old PHP syntax and make internal variables protected, which wasn't possible before (See #1971 and 61e35c35347bc7b9e089398f6d76270e137a0709 for a related commit affecting that line). I would assume that you still use some old plugin that still tries to access that now protected field.

**Comment by kmlucy** [comment]
I got it fixed. It was a problem with how I had my plugins directory mounted. Basically, I was still using the previous versions of the built in plugins. I replaced them with the new versions and it is working now.

I'm going to have to look at my Docker container to find the best way around this.

**Comment by Michaelsy** [comment]
@splitbrain 
> @Michaelsy please refrain from wild guesses in bug reports.

Sorry ... :'‑(

**Comment by alxrohr** [comment]
> I got it fixed. It was a problem with how I had my plugins directory mounted. Basically, I was still using the previous versions of the built in plugins. I replaced them with the new versions and it is working now.
> 
> I'm going to have to look at my Docker container to find the best way around this.

Hi, I've got exactly the same problem but I do not understand how to apply your solution. What exactly did you do to fix the problem? What do you mean by "problem with how I had my plugins directory mounted" and what exactly did you do to replace the built in plugins with the new versions?

**Comment by Klap-in** [comment]
Please ensure that you use for DokuWiki and all the plugins the latest version. e.g. by reinstalling plugins, etc

**Comment by phy25** [comment]
@alxrohr What DokuWiki version are you using? And what server (Apache/NGINX/bitnami/...)?

**Comment by kmlucy** [comment]
My issue was specific to using DokuWiki in a Docker container with the plugins directory volume mounted. When Dokuwiki updates the normal way, it also updates the built in plugins. But when the plugins directory is volume mounted, the built in plugins don't get updated, so you are using the new DokuWiki version with old plugins. The way I fixed it was to manually copy the new versions of the old plugins over the old versions.

**Comment by alxrohr** [comment]
I'm using Dokuwiki in a Docker container with mounted plugins dir, too, and I have the exact same problem. I will try to replace the old built in plugins manually, as you describe it. I suppose you downloaded the correct DokuWiki version (outside of docker) and extracted the files you needed to replace, right?

**Comment by kmlucy** [comment]
Basically, yes. I just started another instance Docker instance without the mount and copied the files out. I actually managed to fix the problems in my image: kmlucy/docker-dokuwiki. You're welcome to take a look at how I did it or use it yourself.
