### ISSUE TITLE
install/update plugin not working in 2018-04-22a "Greebo"

### ISSUE THREAD

**Issue by frank-w** [splitbrain/dokuwiki#2374]
clicking the update/install-button in extensions-area of admin-interface results in a blank page

manual install from url also not working, using that url: https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master

**Comment by frank-w** [comment]
seems to be a temporary problem...had try it again and it worked

**Comment by Klap-in** [comment]
dw2pdf plugin is a bit large download, what creates sometimes issues.
