### ISSUE TITLE
Make old revisions easier to discover

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#2376]
When a page does not exist, we show the `newpage.txt` message. However when a page once existed, but then was deleted, we show the same message.

Inspired by the discussions in #2370, I think it would make sense to explicitly tell users that the page they are looking for _no longer_ exists.

Example:

```
======= This page does not exist anymore ======

You've followed a link to a page that no longer exists. You can check the list of [[?do=revisions|old revisions]] to see when and why it was deleted, access old revisions or restore it.
```

**Comment by Michaelsy** [comment]
Good idea! This lack of information I noticed already too.

I think a better concept could be "purged" not "deleted" or "does not exist".

**Comment by Klap-in** [comment]
So far I know 'purge' means to remove thoroughly, while 'delete' means remove. 

The idea of the wiki is that is should not be completely thoroughly erase the page, without keeping it somewhere... . So does 'delete' not fit better for a page that is restorable?

**Comment by Michaelsy** [comment]
All what I "know" is what Leo writes: German translations: [Leo:purge](https://dict.leo.org/englisch-deutsch/purge)  [Leo remove](https://dict.leo.org/englisch-deutsch/remove) [Leo:delete](https://dict.leo.org/englisch-deutsch/delete)

So far I Leo understand: If something is purged it is empty from something (maybe thoroughly).

What is the apperception of the user? I guess the page is for him, what he see on the screen.

**Comment by splitbrain** [comment]
@Michaelsy maybe you're not the best person to give advice on English wording? Or to quote yourself: "auf Englisch zu schreiben ist für mich so [...] anstrengend und mühsam"

**Comment by Michaelsy** [comment]
> maybe you're not the best person to give advice on English wording

I wrote "I think ... could ... " The best person for advicing is surely an english native speaker.

**{off-topic}** Auf englisch zu schreiben ist vor allem deshalb so mühsam für mich, weil ich es oft viel zu perfekt machen möchte und jedes zweite Wort dreimal bei Leo nachschlage. Aber mittlerweile habe ich mir schon etwas mehr Mut zur Lücke beigebracht... **{/off-topic}**

**Comment by LarsGit223** [comment]
> ======= This page does not exist anymore ======
You've followed a link to a page that no longer exists. ...

IMHO the header and the first sentence of the message make it very clear. Nothing to improve from my side.

**Comment by Michaelsy** [comment]
> ... access old revisions or restore it.

Of course this makes it very clear.
