### ISSUE TITLE
PHP 7.2 Update causes Warnings

### ISSUE THREAD

**Issue by mbromley-voxel** [splitbrain/dokuwiki#2377]
I've updated PHP to 7.2 and now am receiving warnings each time a new page loads.  The two warnings are:

Warning: Declaration of syntax_plugin_issuetracker::handle($match, $state, $pos, Doku_Handler &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler)

Warning: Declaration of syntax_plugin_issuetracker::render($mode, Doku_Renderer &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data)

If there is additional information that I can provide to help troubleshoot this please let me know.

**Comment by splitbrain** [comment]
Looks like your issuetracker plugin needs an upgrade.

**Comment by mbromley-voxel** [comment]
There is no options to update under my extension manager to upgrade, is there somewhere else I should be looking?

**Comment by splitbrain** [comment]
report the bug in the plugin's bugtracker?

**Comment by mbromley-voxel** [comment]
Ah I apologize, I thought that was the Github page I was on, I must have gotten redirected at some point.  Sorry!
