### ISSUE TITLE
Email not being send

### ISSUE THREAD

**Issue by japhinraj** [splitbrain/dokuwiki#2379]
I made a site with dokuwiki http://uknow.ga but the registered users are not getting email of their password even though it says its send.i have setup email in my hosting.and its working .please solve the issue.please

**Comment by splitbrain** [comment]
DokuWiki passes mails on to PHP's send() method. When this function does not return an error we have to assume the mail was sent properly. Your mail system is probably not set up correctly for PHP at your hoster. Best contact their support and ask them to fix it.
