### ISSUE TITLE
Plugin installed incorrectly

### ISSUE THREAD

**Issue by gtbu** [splitbrain/dokuwiki#2385]
After installation of the release candidate i  copied the dokuwiki-plugin-addnewpage-2015-11-02.zip
into the plugins-folder, renamed it and unzipped it. I still get the permanent error :
Plugin installed incorrectly. Rename plugin directory 'dokuwiki-plugin-addnewpage-2015-11-02' to 'addnewpage'. -----------------------------------
The same is with unrenamed templatedirectories. I needed  a new installation.
Why does the system give  a warning that the templatefolder is not LotarProject-dokuwiki-template-bootstrap3-v2018-02-16-32-g119aa21 but 'bootstrap3' and then keeps the error in mind  - so that  i need an new installation(at first on xampp..) - browsercache and new start of apache do not help
The System should rename  itself as it knows the exact name !
( the further thing that is missing is a pagemanager ala cmsimple xh - rather as chaotic as other cmssses)

**Comment by splitbrain** [comment]
* there is no current release candidate
* renaming the zip file is not useful
* you need to rename the folder that gets extracted
* you could also use the extension manager to install plugins and it would take care of the naming for you
* why would you need a new installation
* I have no idea what a "pagemanager" is supposed to do but that would be another ticket anyway
