### ISSUE TITLE
[Bug] View source button not hide from user although view source action is disabled

### ISSUE THREAD

**Issue by Michaelsy** [splitbrain/dokuwiki#2396]
View source button is not hide from user although view source action is disabled

### Conditions:
- Greebo.a
- View source action: disabled
- Edit action: enabled
- Read-only for non-logged-in-users (`@all`)
- Logged out

### Result
- View source button is shown whereas its function is disabled.

In "Frusterick Manners.e" it works fine. See also live demos: [Greebo.a](http://test4.informantum.de) versus  [Frusterick Manners.e](http://test3.informantum.de)

HTH - Michael Sy.

**Comment by eiroca** [comment]
to fix...
in inc\Menu\Item\Edit.php
change from
                }
            } else {
                if(!actionOK($this->type)) throw new \RuntimeException("action disabled: source");
                $params['rev'] = $REV;
                $this->type = 'source';
                $this->accesskey = 'v';
            }

to

            } else {
                **if(!actionOK("source")) throw new \RuntimeException("action disabled: source");**
                $params['rev'] = $REV;
                $this->type = 'source';
                $this->accesskey = 'v';
            }
