### ISSUE TITLE
[Feature request] Wide screen support (or CSS override support)

### ISSUE THREAD

**Issue by michalmiddleton** [splitbrain/dokuwiki#2397]
I use the DokuWiki default template and I love it... except I wish there was a convenient way to keep it in wide-screen (ie. fill out unused width of browser window). 

As a workaround/hack, I edit `./lib/styles/screen.css` and add this css override to the top:
```
#dokuwiki__site {
    max-width: 100% !important;
}
```
Unfortunately I have to add this change after each DokuWiki update. 
I'd love this to be an official feature or at least have an option to override default CSS by sourcing custom CSS first.

**Comment by phy25** [comment]
You can do customizations without modifying the default CSS: https://www.dokuwiki.org/devel:css

**Comment by Michaelsy** [comment]
@michalmiddleton  All what you want is already there:

=> Admin => Template Style Settings => The width of the full site

Furthermore:
https://www.dokuwiki.org/devel:css
https://www.dokuwiki.org/devel:style.ini
https://www.dokuwiki.org/plugin:styling

HTH - Michael Sy.

**Comment by michalmiddleton** [comment]
Thank you so much... I have been changing the CSS by hand for years lol :-(
