### ISSUE TITLE
“Greebo” not longer renders simple URL as link at start of line.

### ISSUE THREAD

**Issue by t-aus-o** [splitbrain/dokuwiki#2399]
With update from “Frusterick Manners“ to “Greebo” I discovered dokuwiki to fail rendering simple text URL (those without prefix http:) under some circumstance:

Cut below example and paste in playground and save:

```
This url www.google.com is correctly rendered as link.
www.google.com however starting at the beginning of a line is no longer rendered as link.
```
Same happens inside bullet lists:
```
  * This url www.google.com is correctly rendered as link.
  * www.google.com however starting at the beginning of a line is no longer rendered as link.
```

**Comment by micgro42** [comment]
I can reproduce this _partially_ at dokuwiki.org: https://www.dokuwiki.org/playground:issue_2399

The `www.google.com` at the beginning of a line is not rendered as link. However the one at the beginning of a bullet point is rendered as such.

**Comment by ssahara** [comment]
This issue might be caused by #1988

**Comment by LarsGit223** [comment]
I wanted to work on this and first thing I tried was to write a unit test for it. I added this function
``` php
    function testExternalWWWLinkStartOfLine() {
        $this->P->addMode('externallink',new Doku_Parser_Mode_ExternalLink());
        $this->P->parse("Foo\n\nwww.google.com Bar");
        $calls = array (
            array('document_start',array()),
            array('p_open',array()),
            array('cdata',array("\n\n")),
            array('externallink',array('http://www.google.com', 'www.google.com')),
            array('cdata',array(' Bar')),
            array('p_close',array()),
            array('document_end',array()),
        );

        $this->assertEquals(array_map('stripByteIndex',$this->H->calls),$calls);
    }
```
to the file ```parser_links.test.php```. Unfortunately this does still seem to generate a correct external link. I can't figure out why the test code is working instead of producing the error seen in a real wiki. Can anybody help me?

**Comment by Chris--S** [comment]
Your test (above) fails for me at all of greebo, master & psr2.

**Comment by t-aus-o** [comment]
I tried the patch suggested by  @ssahara.
It solves my issue  #2399.

**Comment by LarsGit223** [comment]
@Chris--S: yes, I know my test fails but it is not producing the expected error. I mean if e.g. I add a dump to the function like this:
``` php
    function testExternalWWWLinkStartOfLine() {
        $this->P->addMode('externallink',new Doku_Parser_Mode_ExternalLink());
        $this->P->parse("Foo\n\nwww.google.com Bar");
        $calls = array (
            array('document_start',array()),
            array('p_open',array()),
            array('cdata',array("\n\n")),
            array('externallink',array('http://www.google.com', 'www.google.com')),
            array('cdata',array(' Bar')),
            array('p_close',array()),
            array('document_end',array()),
        );

        var_dump($this->H->calls);

        $this->assertEquals(array_map('stripByteIndex',$this->H->calls),$calls);
    }
```
then I see entries in the var_dump showing ```externallink``` which to me means that the test correctly rendered an external link. Instead I would expect a ```cdata``` entry containing ```www.google.com```. So I know I have to adjust my result check but the renderer doesn't seem to produce the error I want.

I did not apply any bugfix yet, so I should get the error in that unit test but I don't.

**Comment by LarsGit223** [comment]
That did not change anything in my tests. But
``` php
$instructions = p_get_instructions("www.google.com Bar");
```
is giving the expected negative result.

**Comment by LarsGit223** [comment]
@ssahara: thanks for the examination and the patch :+1:  I have put your patch into PR #2433 and added a unit test.

**Comment by ssahara** [comment]
@LarsGit223 Thanks for your kind words.
The good description of the parser by @Chris--S , I prefer to use `(?<=^|\s)` to find correct position where simple URL may appear, rather than to find exceptions by using `(?<!/)\b` which was my initial suggestion.

The `(?<=^|\s)` works well as expected on my local wiki.

**Comment by LarsGit223** [comment]
@ssahara: Ok, I will adjust the PR

**Comment by Chris--S** [comment]
@LarsGit223 @ssahara I thought about that, I prefer your character black listing way.  E.g. 
(www.google.com) won’t become a link with the ^|\\s regex.

**Comment by ssahara** [comment]
The simple URL in parenthesis had become link, which (I think) should be kept as well. 
`(?<![/\\\\])\b` works well for both cases: a) enclosed in parenthesis, and b) appears in unix/windows path.

**Comment by 5shekel** [comment]
i find it also fails in middle of line with special links like 
```
  - host: git clone git://gitorious.org/air-sd-logger/air-sd-logger.git
  - this line (and anything following)  will lose formatting
```

**Comment by phy25** [comment]
> i find it also fails in middle of line with special links like
> 
> ```
>   - host: git clone git://gitorious.org/air-sd-logger/air-sd-logger.git
>   - this line (and anything following)  will lose formatting
> ```
> 
> this works
> 
> ```
>   - host: <code>git clone git://gitorious.org/air-sd-logger/air-sd-logger.git</code>
>   - this line (and anything following)  will lose formatting
> ```

Please read https://www.dokuwiki.org/urlschemes - this may be expected.
