### ISSUE TITLE
page marked as not existing

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki#2405]
If `[[:Plugins]]` is used at dokuwiki.org the url is marked as not existing.

If it is changed to `[[:plugins|Plugins]]`, it start working as expected i.e. it is marked as existing.

aspect that could have influence:
- there is repository table at this page
- syntax `~~NOCACHE~~` is used

examples:
not existing: https://www.dokuwiki.org/plugin:watchcycle#installation
existing: https://www.dokuwiki.org/plugin:templatepagename#installation

Resaveing e.g. watchcycle don't change the case.
Also resaving the plugins page doesn't change anything. 

https://www.dokuwiki.org/plugins

**Comment by micgro42** [comment]
hover over the link on https://www.dokuwiki.org/plugin:watchcycle#installation . there is a zero-width character in the link.

Most likely I copied it from the wiki diff at some point. I already mentioned the problem with zero-width unicode chars in the diffs a while ago... #1208

**Comment by Klap-in** [comment]
Ah, I copied indeed from the diff view. Good observation!
