### ISSUE TITLE
"Compatible with DokuWiki" box is partly hidden if TOC is folded

### ISSUE THREAD

**Issue by lpaulsen93** [splitbrain/dokuwiki#2407]
If the table of contents is folded, then the "Compatible with DokuWiki" box is partly hidden and the assigned value for a specific DokuWiki release (e.g. "Yes") cannot be seen. See this screenshot:

![dokuwikiorgcomptobox](https://user-images.githubusercontent.com/9009011/40733546-300ef952-6436-11e8-83dc-0d4c694f7639.png)

Tested with Firefox.

**Comment by Michaelsy** [comment]
And more unexpected on smaller screens
PR https://github.com/splitbrain/dokuwiki-plugin-pluginrepo/pull/121 fixes both

(Sorry for the needless references...)

**Comment by phy25** [comment]
Closing in favor of https://github.com/splitbrain/dokuwiki-plugin-pluginrepo/issues/134.
