### ISSUE TITLE
userlink() does not return realname

### ISSUE THREAD

**Issue by runout-at** [splitbrain/dokuwiki#2411]
I can't get the `userlink($username)` function to return the realname of the given `$username`.

https://xref.dokuwiki.org/reference/dokuwiki/nav.html?_functions/userlink.html

The usecase is in todo plugin:

https://github.com/leibler/dokuwiki-plugin-todo/blob/6321dc1c6949d762a9c230b84f44621285bea38f/syntax/todo.php#L325

**Comment by runout-at** [comment]
Thanks for that hint!
You're right this behaviour is depending on the config:showuseras setting.
This was to me not obvious from the documentation of the userlink function.

As this is not a solution for the todo plugin i'd like to ask if there is an other possibility to return the realname for a specified (not only the logged in) user.

Or otherwise if it would be possible to extend the userlink function with an an optional parameter to override the config setting on calling eg userlink($username, false, 'realname')?

**Comment by splitbrain** [comment]
`$auth->getUserData()` gives you info available on an arbitrary user.
