### ISSUE TITLE
RFE: Add guest group

### ISSUE THREAD

**Issue by ludi113** [splitbrain/dokuwiki#2421]
Hi, 

I have a site that has a public and a private part. Thus, I am using the @ALL group to deny access to the private part of the dokuwiki, so that users that are not logged in don't have access to the private part. However, afterwards, I have to re-enable access for the various groups with a login. This results in quite a long list of users and namespaces with explicit access privileges. 

Could you consider adding a guest group to dokuwiki, so that I could simply deny access to the private part by setting the privileges of the private part for guests to none? The presence of a guest group, that would be the set of users that are not logged in, would IMHO significantly simply ACLs for wikis with a private and public part. 

Thanks in advance for taking it into account. 

Have a nice day.

**Comment by micgro42** [comment]
All users get a default group, usually `@user`, unless you changed it in the [defaultgroup setting](https://www.dokuwiki.org/config:defaultgroup).

You can use this group to give all logged in users access to the private parts of your wiki with a single ACL rule.

**Comment by ludi113** [comment]
Thanks for your reply. 

Could you please be more specific? How can I give all logged in users access to the private part of the site with a single rule, if the private parts are scattered through different namespaces? Will I not have to use two rules per namespace? The first to deny access to @ALL and a second rule for the user group to restore access for them? (And I am not talking of the pages, where I use the include plugin, to make part of the page only visible to the logged in users.)

**Comment by splitbrain** [comment]
I don't understand the problem. Set `@ALL` to `0` for the top private namespace, then add read or write permissions for the namespaces you want to be accessible by different groups.

**Comment by ludi113** [comment]
It is not about doing something that is not possible to do; it is about adding a way to do it more simply: I don't have a top private namespace. Simple example: 
ns1:nsA 
ns1:nsB 

There are private and public parts/pages in nsA; there are also public and private parts/pages in nsB. 

I could have placed the private parts/pages of nsA and nsB namespace into a ns2 namespace; but this has the drawback, that I have to move parts/pages in and out of ns2, when I want to switch them from private to puplic. Further, I assume that it is more safe to work with ACL rules than start to move pages around.

**Comment by micgro42** [comment]
If you are concerned about moving pages manually, have a look at the move plugin: https://www.dokuwiki.org/plugin:move

Otherwise, it is as stated before: deny access for every user by setting `@ALL` to 0, then allow it for logged-in users by setting the permissions for `@user` or whatever the default group is for your wiki. Repeat for every namespace that you want to be private.

If you have a complex setup, then you have a complex setup.

**Comment by ludi113** [comment]
You are right: in namespaces with more private than public pages, making the whole namespace private and opening only the public pages results in less rules than starting with a public namespace and then denying access to non logged in users to the many private pages. Thanks to both of you for the advice. 

Thanks also for pointing me to the move plugin.
