### ISSUE TITLE
Substitution to unicode characters not working consistently

### ISSUE THREAD

**Issue by ituri** [splitbrain/dokuwiki#2424]
Hi everyone,

I'm on _2018-04-22a "Greebo"_ and in this version, dokuwiki seems to substitute an ascii-arrow (->) to its unicode equivalent (→).  However, it doesn't work that way when used inside a link. Here, the ascii-arrow won't get substituted into the unicode version.
If you want to recreate this error, just use the following example:
```
[[foobar|foo -> bar]]
foo -> bar
```

I'd suggest using the aforementioned substitution in links, too.

**Comment by splitbrain** [comment]
No syntax (and that includes entity replacements) is possible within link titles or headlines. It's a limitation of how our parser works.
