### ISSUE TITLE
Purging the cache

### ISSUE THREAD

**Issue by trailjeep** [splitbrain/dokuwiki#2435]
My dokuwiki (2018-04-22a "Greebo") seems only to truly purge the cache when appending `?purge=1` and not `?purge=true` as documented at [Caching](https://www.dokuwiki.org/devel:caching).
This holds true for pagecache/css/js.
This seems like no big deal except I use the [Bootstrap3 Template](https://www.dokuwiki.org/template:bootstrap3) and [Advanced Plugin](https://www.dokuwiki.org/plugin:advanced) which both have `?purge=true` hard-coded in.

**Comment by trailjeep** [comment]
After further testing it seems this issue is with the aforementioned tpl & plugin and not with dokuwiki. It's strange because the URL is correct when injected but only works when i manually click in the URL bar and hit enter. I will report this issue in the respective places.

**Comment by splitbrain** [comment]
Purging the cache via purge variable only works when manually submitted and is ignored when a referrer header is present.
