### ISSUE TITLE
Question about dokuwiki, git and deployment

### ISSUE THREAD

**Issue by Organizm238** [splitbrain/dokuwiki#2436]
Hi everyone! I have an existing Laravel project and I want to add dokuwiki into it. I have added whole dokuwiki directory into 'public' dir in my local copy of project and have opened it in browser. Everything is working. I want to deploy dokuwiki to dev server. 
I have my local version of project, dev server and production server. It is ok if all servers will have the same wiki. Should I just add the whole directory to git?

**Comment by splitbrain** [comment]
I'm not sure I understand what you're asking but this seems not to be a bug or feature wish and is probably better suited for the forum.
