### ISSUE TITLE
Create page from search link is broken

### ISSUE THREAD

**Issue by bactram** [splitbrain/dokuwiki#2439]
When searching for a new page in a namespace, the search results page says that there is no such page, and helpfully has a link to create the page. But the link to create the page makes the page in the root namespace, not the namespace I specified.

Example: I enter a search for ":ns:newpage". I want to create this page. The link on the search results page is for ":ns_newpage" instead of ":ns:newpage". The second colon is being replaced with an underscore, but it should remain a colon. 

If I do this in a nested namespace, all the colons except the first one are replaced with underscores. So ":ns1:ns1a:newpage" is changed to ":ns1_ns1a_newpage".

This behavior worked properly in Frustrick Manners, but is broken in Greebo.

**Comment by mprins** [comment]
#2355

**Comment by Michaelsy** [comment]
This unexpected behavior should be fixed in Greebo Hotfix 2018-04-22a. Please take a look at the [changelog](https://www.dokuwiki.org/changes#release_2018-04-22a_release_greebo):
> [...] better support for creating pages from search #2355 [...]
