### ISSUE TITLE
Non-existing "loading.gif" in lib/scripts/media.js

### ISSUE THREAD

**Issue by tmo26** [splitbrain/dokuwiki#2441]
Dokuwiki Release 2018-04-22a "Greebo"

Issue: `lib/scripts/media.js` contains the non-existing `loading.gif`

`$container.html('<img src="' + DOKU_BASE + 'lib/images/loading.gif" alt="..." class="load" />');`

According to `data/deleted.files`, this gif has been removed in 2018-04-22.
This missing `loading.gif` frequently shows up in the webservers error logs.

**Comment by phy25** [comment]
Removed by #2076.
