### ISSUE TITLE
Prevention of configuration backup exposure

### ISSUE THREAD

**Issue by pes-soft** [splitbrain/dokuwiki#2446]
Hi,

Accidental exposure of `conf` directory via web access could reveal content of configuration backup files to public. This can occur for example in distributions where upstream .htaccess files are not used. To prevent such accidents and employ the php exit code for backup files as well, backups should be saved with extension `.bak.php` instead `.php.bak`.

**Comment by splitbrain** [comment]
You're right that makes sense. It should be implemented on top of my changes in #2382
