### ISSUE TITLE
Don't send 'page changed' mail for own changes

### ISSUE THREAD

**Issue by nerdoc** [splitbrain/dokuwiki#2451]
If you (as admin) make many changes, you (yourself) get a mail for every change on the configured mail address. This is really annoying after a while: *Yes, I know I have changed something myself, I don't need another notification for that.*

So I pledge to modify the mail send mechanism (there should be a config switch for that!):
**If a user that changed something has the same email address as the address in config var "notify" - don't send a mail.**

If you can think of other possibilities, please let me know - but I think this would be easy to implement and would prevent a lot of "spam" mails.

Don't get me wrong: I don't want to remove these notifications at all (in that case I could leave the *notify* address empty. If any other user than me changes anything, I *want* to get notified. It's just that my own changes don't need to be reported.
This could be addressed to the "subscribers" as well. If I subscribe to a page, I want to get notified to changes of *others*, not my own. Again: *I know that I have changed the page*.

**Comment by splitbrain** [comment]
Use the page subscription mechanism then. The notify config is to be informed about *all* changes made.

**Comment by nerdoc** [comment]
Sorry, but did you read my issue (before closing it instantly)? It is not about page/namespace/etc subscriptions.
The page subscription mechanism is to receive subscriptione "per page", or sub namespages.

What I suggest is to **NOT get notified by my own changes**. What has that to do with page subscriptions?

**Comment by splitbrain** [comment]
I understand that this issue is about the notify config option. It will send one mail per change, including your own. However when you use the page subscription mechanism, it will only send you mails about changes made by others, which is what you're asking about (unless I still didn't understand you)

**Comment by nerdoc** [comment]
ok, so I could just subscribe the `en:*` namespace and get changes for all English subpages except changes I did for myself? In this case, yes, you are right ;-)

**Comment by micgro42** [comment]
https://www.dokuwiki.org/subscription
