### ISSUE TITLE
Make it easy to change path to static content

### ISSUE THREAD

**Issue by janinko** [splitbrain/dokuwiki#2452]
From https://bugs.dokuwiki.org/2592.html
> Make it easy to move static content (i.e. static images) to different domain (so no cookies are sent).
Maybe implement a config option to easily change the path to all static content. (Obviously, the syncing to a CDN server needs to be done by an external source or a plugin.) Although this might be more complicated with CSS and JS, but it should be doable.
>
>This was suggested here: https://forum.dokuwiki.org/thread/7766

**Comment by Klap-in** [comment]
Please see also 
https://github.com/splitbrain/dokuwiki/issues/1020

**Comment by splitbrain** [comment]
600ms for a call to fetch.php with a fetchsize of 0 seems excessive. How exactly are you measuring this? Any chance you can profile where the time is spent within fetch?

**Comment by janinko** [comment]
I measure it using DevTools in Chrome: 
![snimek z 2018-08-22 17-44-54](https://user-images.githubusercontent.com/644267/44474510-1f17da80-a633-11e8-995d-00bec5de1544.png)

Any idea how could I try to profile it?

**Comment by splitbrain** [comment]
dev tools is a good start. Unfortunately your screenshot is missing all the interesting bits. Like are those external images? Are they going to different servers? How is the time spent? Are there other requests that chrome is waiting for before even asking for the images?

To truly analyse this a profile with xdebug would be helpful.

**Comment by janinko** [comment]
Single request details from DevTools:
![snimek z 2018-08-22 19-15-44](https://user-images.githubusercontent.com/644267/44479079-d1559f00-a63f-11e8-870d-f08c84f981f9.png)
And output from xdebug profiler: 
[cachegrind.out.002.gz](https://github.com/splitbrain/dokuwiki/files/2311362/cachegrind.out.002.gz)

**Comment by splitbrain** [comment]
Thanks for the data! It's very helpful. One thing I notice is that the initial DNS lookup is already taking a lot of time, but that's beyond the scope here. Chrome waits 323.99ms for the first byte which corresponds nicely with the profile data which says processing took 306ms.

I only looked briefly at the call tree, however most of the time is spent in two things: autoloading and plugin initialization. And that makes me wonder...

First of all what PHP version are you using? I believe autoloading would greatly benefit from PHP7's opcache. You should enable that if you can.

The only other thing that comes to mind that would be slow in the mentioned two things would be file system accesses. What file system is your wiki running on? What's the memory utilization of the system and the availability of memory for filesystem caching? In the same line of thinking, is this server by any chance a Windows system?

**Comment by janinko** [comment]
PHP 5.4.16, filesystem xfs, around 3 GB of memory is used for caching right now, 4 GB used by apps out of 7,6 GB total and it runs on CentOS.

**Comment by splitbrain** [comment]
PHP 5.4 is seriously outdated and also indicates that you are running an old version of DokuWiki - that's a problem.

I have no experience with the xfs file system. From a quick look at wikipedia it's meant to be especially fast for parallel accesses - I wonder if that means it's slower for a single process accessing a lot of files...

My recommendation would be to upgrade to a recent PHP version and enable opcache. That probably speeds up things considerably. If not reopen this ticket.
