### ISSUE TITLE
Option to disable javascript

### ISSUE THREAD

**Issue by zuglufttier** [splitbrain/dokuwiki#2463]
Dokuwiki is awesome and can be used in various scenarios where loading speed and/or security does matter a bit. Downloading all javascript takes about 500kb and a smaller codebase often will minimize attack vectors.

I removed these lines as a test: https://github.com/splitbrain/dokuwiki/blob/bc42db0f26c729b8d03590eb112af4d76c617d9a/inc/template.php#L342-L358

Dokuwiki is still working for me. Is there anything that will be broken by removal of these lines? If not, can you consider to add an option to remove javascript alltogether?

**Comment by phy25** [comment]
Javascript is required as far as I remembered for the following features: search suggestions, media manager, editor toolbar... No major features indeed, but the Internet is *not* going to a no-Javascript future. So maybe a minimum template is possible for your intention?

By the way, we can improve the load performance, for example, by splitting files served to read-only users and admin users. This can reduce a lot of script size like jQuery UI. The coverage results on Dokuwiki.org now seems horrible:

![Chrome's JS+CSS Coverage](https://user-images.githubusercontent.com/331403/43845572-e1746862-9b5e-11e8-831b-d14345c5467b.png)

**Comment by zuglufttier** [comment]
I know, javascript will be there in the future ;) Also, for editing, it is a wonderful addition.

But for reading users that aren't logged in, it could really make sense. It really depends how you are using dokuwiki.

**Comment by splitbrain** [comment]
DokuWiki uses progressive enhancement so yes, it technically works without JavaScript. But no, we will not let you disable it in a config. You can however write a plugin using the TPL_METAHEADER_OUTPUT event.

You may also want to look into https://www.dokuwiki.org/config:jquerycdn to use a CDN to speed up JavaScript loading.
