### ISSUE TITLE
Media(images) urls bad made: lib/exe/fetch.php/logo.png

### ISSUE THREAD

**Issue by dpineiden** [splitbrain/dokuwiki#2464]
Hello
I'm trying to configure the dokuwiki, the set used is nginx+php fpm+dokuwiki
I found that the problem is on the dokuwiki system, but i have no idea why
The preoblem is:
**Despite build the url's images as ?media=logo.png, write: lib/exe/fetch.php/logo.png**
What can i do?

**Comment by splitbrain** [comment]
Thanks for opening the issue. Unfortunately your issue does not contain enough information. Please try to provide as much info as possible, generally following these three main questions:

* What did you do?
* What did you expect to happen?
* What happened instead?

Please also describe what steps you took to analyze the issue and what (failed) attempts you made to fix the problem yourself.

Your issue should contain everything that might help in analyzing and reproducing the issue. That includes but isn't limited to:

* versions of the involved software
* exact error messages
* debug logs (also check your JavaScript console for web related issues)

Thanks for your help.

PS: You may want to refer to [How to Ask Questions the Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) for more tips on improving your issue creation game ;-)

**Comment by dpineiden** [comment]
Hi Slipbrain.

What did i do?
- Install dokuwiki with pack (nginx+php-fpm)

These configurations:
nginx /1.12.2
https://gist.github.com/dpineiden/32db039952bb1587398d199c15d181f6
php-fpm (v 7)
https://gist.github.com/dpineiden/bb69fd40eda26795707dc0544a089010

What happend?
When go to the media manager--> image files
Click, send to link like this:
http://datawork.csn.uchile.cl/lib/exe/fetch.php/logo.png
404 Not Found

But must be, instead, the correct url:
http://datawork.csn.uchile.cl/lib/exe/fetch.php?media=logo.png

**Comment by Klap-in** [comment]
Which setting are your using for: https://www.dokuwiki.org/config:userewrite ?

**Comment by dpineiden** [comment]
Sorry, but i'm not using the apache config, is on the nginx file where the rewrites are setted like the official page

**Comment by phy25** [comment]
@dpineiden Your config of `userrewrite` might be wrong. Please read https://www.dokuwiki.org/config:userewrite and set the value accordingly.

**Comment by phy25** [comment]
I am closing this because of lack of response, but feel free to add more information and I can reopen the issue if necessary.
