### ISSUE TITLE
CSRF: is failing vulnerability test.

### ISSUE THREAD

**Issue by prachinikhade** [splitbrain/dokuwiki#2468]
Despite of being prevented by default by dokuwiki, the tokens were not changing for each request. It is failing the vulnerability test. 

It was possible   to change password of a user using a random frame
--

**Comment by splitbrain** [comment]
Please provide more details. CSRF tokens are session dependent.

**Comment by phy25** [comment]
You might mean the current `sectok` mechanism, intended to prevent CSRF attacks, is vulnerable to some replay attacks, but please do provide more details.

**Comment by splitbrain** [comment]
Since we received absolutely no feedback here, I'm closing this.
