### ISSUE TITLE
ACL right management does not allow user to upload files

### ISSUE THREAD

**Issue by PifPof73** [splitbrain/dokuwiki#2472]
Hi,
we use dokuwiki <Release 2018-04-22a "Greebo"> on Ubuntu 18.04 LTS with Apache2 Webserver and PHP 7.2.
The User backend is [authad] against a Windows 2012 R2 Active Directory.

Our acl.auth.php is looking like this:
```
# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 06 Jun 2011 14:58:41 +0000
*       @ALL    1
*       @sg%5fhfm%5fit  16
*       @domain%5fusers 8
```

so we want that in default the wiki is read only, we do have a administrative group (*sg_hfm_it*) and we want that the **domain_users** are allowed to upload files (if logged in).

But in the most time the logged in domain Users see the error Message "no user right to upload file" both in media manager as in the popup, but the same users are allowed to edit pages or generate new ones.

So somehow these users get the right "4" instead of "8".
The members of *sg_hfm_it* are always working correctly (configured as manager inside the local.protected.php).
Whats even more confusing is that sometimes after a restart of the apache some (not all) of these users are allowed to upload files, some not. 
And sometimes (we don't find out when and why) these lucky users are loosing their right over night...

Has somebody an idea where we can find more hints on what's going on with our configuration?
Thanks.

**Comment by splitbrain** [comment]
"no user right to upload file" is not a message that exists in DokuWiki. Did you copy the exact words?

Also when you do a ?do=check with a logged in user, are the groups and page permissions reported as expected?

**Comment by PifPof73** [comment]
Sorry, was my free translation to English.
My german installation says:
"Sie besitzen nicht die notwendigen Berechtigungen um Dateien hochzuladen."
![wiki no - right](https://user-images.githubusercontent.com/7371047/44266156-cbb81d80-a229-11e8-8ed5-3c446040b875.png)

The ?do=check I will test the next time the users do have the problem (at the moment I am writing the user does have the right and a do=check reports a permission of 8, which is the expected value).

**Comment by PifPof73** [comment]
This morning the same user where it worked last week, is blocked again, do_check seems to be ok:
![grafik](https://user-images.githubusercontent.com/7371047/44322901-e4098180-a44f-11e8-8d16-f6408d9917b1.png)

do_check:
![grafik](https://user-images.githubusercontent.com/7371047/44322999-482c4580-a450-11e8-8bca-bc6e8c3f687d.png)

In ACL the rule is for group <domain_user> (and the do_check reports 8):
![grafik](https://user-images.githubusercontent.com/7371047/44323051-83c70f80-a450-11e8-90ce-95ba4b6a43e7.png)

The strange part: Sometimes it is working (after a new session - login), but this time not (after the weekend I expect a completly new session).
Greetings,
PifPof73

**Comment by phy25** [comment]
Don't know whether it makes a difference, but there are two ways of opening media manager:

- At the header there is a link to "Media Manager" (full screen one)
- Editor's media manager icon

Maybe next time you can try using the "full screen" one to see whether it works, because they are in different path, and they initialize differently.

**Comment by PifPof73** [comment]
Hi phy25,
We tested both ways with same result.
It does not matter if we are using the "full screen" nor editor mode.

The do_check gives us the expected right result "8" (in this case), so I would guess it is inside the routine of the media manager.
It is still an issue for us.
Greetings,
PifPof73

**Comment by PifPof73** [comment]
Hi all,
this point is still open.
I put the collegue into the administrator AD - Group (We do have a ACL rule for this group) - and now the colleuge does have ADMIN rights inside the wiki (he sees the config pages and can do things), but he still gets this error "no permission to upload files".

Is there any possiblity to delete the local AD cache or the local user and let the plugin "refresh" the user database to see, if there is a clinch inside some historical (cached) data?

Is there a priority in ACL rules? 
The first rule is blocking everybody not logged in, the second rule let the "sg_hfm_it" - group "delete files" and the third rule let the "@domain_users" group upload files.

So I do not understand why one collegue is not allowed to do it, but all others do.
We also used all available browser and always used "purge cache" on the browers during our tests.

Greetings,
PifPof73

**Comment by phy25** [comment]
Sorry for the late reply. This is really a tricky issue, and I guess there is some backend "cache" in your environment, which might not be easily cleared. I would debug every step involved to see what's wrong inside, but this requires through understanding to the auth code...

**Comment by PifPof73** [comment]
No problem.
Can I help you with debugging?
Is there a log / cache in dokuwiki where the ldap / AD information is stored?
Does anyone knows how to force a resync?

It would be nice to have a button "forget all users and reload them from ldap/ad" to reinitialize the users and there rights.

Maybe I could switch to local user management, delete all users and reenable the authad module?
But I am a little chicken doing so without knowing the side effects (it IS a productive system and people working with it).

**Comment by splitbrain** [comment]
What @phy25 meant is that *you* would need to debug this. Because it is impossible for us to figure out what's going on without access to the system in question.
There is nothing to "resync" - all AD data is fetched directly from the directory server. The current users' data is stored in the session (for about $conf[securitytimeout] seconds). Requested data about other users is cached in memory for a single request only. You can try setting security timeout to 0 but this will probably make everything too slow for everyone.

**Comment by PifPof73** [comment]
I understand.
My question was, if there is any in between caching. I know systems which requests LDAP one, two times a day and store the users in an own database file to enable authentication even if the LDAP is down.
As far as I understand, dokuwiki does not have such a cache.
The strange thing is, that the collegue now does have super administrator rights (he can administrate the dokuwiki itself), but he does not have the right to upload files in the filemanager window.
So this part have to be programmed differently.
I am no php programmer, so its difficult for me to debug the code, but I will try my best.

Regards,
PifPof73

**Comment by PifPof73** [comment]
In the file

/dokuwiki/inc/media.php

I found this line in some functions (e.g. media_tab_files):
`if(is_null($auth)) $auth = auth_quickaclcheck("$ns:*");`

But not in the functions:
-  media_uploadform
- media_metaform

It seems that this line force a check, in case $auth is not set before checking against it.
Could it be that this is the problem?

In my case I am superuser (with $auth=16), but sometimes get the descripted error. 
From outside it looks like the $auth parameter is not correct set inside the media.php file.

As I mentioned, I am no skilled php coder, how could I force a debug print to a log file to see:
- which data is inside the function?
- where is the call of this function and which data is inside the call function?

Regards,
PifPof73

**Comment by phy25** [comment]
@PifPof73 Hi, sorry for the late reply in the new year. [The line you mentioned](https://github.com/splitbrain/dokuwiki/blob/30def7da1b644298a9135d5b6e6a9cc9838e951b/inc/media.php#L671) exists out of [`media_uploadform()`](https://github.com/splitbrain/dokuwiki/blob/30def7da1b644298a9135d5b6e6a9cc9838e951b/inc/media.php#L876) and [`media_metaform()`](https://github.com/splitbrain/dokuwiki/blob/30def7da1b644298a9135d5b6e6a9cc9838e951b/inc/media.php#L943), in their wrapper functions, so usually this should not be a problem.

However, you are on the right track debugging it. You can manually add code to the program (inside the media functions) to either output the variable value to the browser (or write to some file) using [debug_backtrace()](http://php.net/manual/en/function.debug-backtrace.php) and [var_dump()](http://php.net/manual/en/function.var-dump.php). `$auth` inside those functions is a good starting point. This might be a long journey, but if your issue still exists consistently, it should be very easy to dig out the cause.

**Comment by PifPof73** [comment]
@phy25 Hi, Phy.
Thanks for this hints.
Meanwhile I have upgraded to 2018-04-22b "Greebo" and the last few days I got no complains from users - and some users could successfully upload files.
So at the moment I will leave with the hope, that the problems is solved.
If not I will try the debugging and reopen a new issue.
Thanks for your help and patience.
Regards,
PifPof73
