### ISSUE TITLE
bitnami-dokuwiki  deprecated.  (bootstrap3)

### ISSUE THREAD

**Issue by rgleason** [splitbrain/dokuwiki#2477]
09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:25:24 ::1: checkUpdateMessages(): messages up to date

**Comment by phy25** [comment]
Please ask on https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues

**Comment by rgleason** [comment]
I think this is the wrong place. Deleting.
