### ISSUE TITLE
Extension Manager hardly readable when using dark theme

### ISSUE THREAD

**Issue by MarcinOrlowski** [splitbrain/dokuwiki#2479]
Extension Manager hardly readable when using dark theme. It looks like on picture below. This happens when using recent Bootstrap3 Template by Giuseppe Di Terlizzi (@LotarProject) plugin with "Darkly" theme. 

![manager](https://user-images.githubusercontent.com/8041294/44403843-c4f51780-a555-11e8-958c-150770537185.png)

**Comment by mprins** [comment]
please take this to the template author, it is not a DW issue.
