### ISSUE TITLE
Feature request: Enable possibility to generate different hyperlinks

### ISSUE THREAD

**Issue by PifPof73** [splitbrain/dokuwiki#2480]
Hi,
we use Microsoft Navision as ERP System, which allows some special sort of hyperlinks like
``dynamicsnav:////runpage?Page=7139``
We would like to enable these type of links inside dokuwiki, so that we can use the wiki as knowledgebase / helppages with direct references to the ERP.
The documentation of this type of hyperlinks is here: [https://docs.microsoft.com/en-us/dynamics-nav/creating-and-running-hyperlinks](url).

As far as I understand the mechanics inside dokuwiki, there is a type of "url-recognition", because of three different type of linke enabled by the same mark [[ ... ]]:
- internal links
- web links
- links on the filesystem

Do you have an idea how to enable the wiki to display this sort of hyperlinks?
Is there a plugin to archive this?

Greetings,
PifPof

**Comment by splitbrain** [comment]
either configure a new schema or define a custom interwiki link.

**Comment by splitbrain** [comment]
https://www.dokuwiki.org/urlschemes
https://www.dokuwiki.org/interwiki

**Comment by PifPof73** [comment]
Thanx a lot! 
Stupid me - didn't found that.
