### ISSUE TITLE
CKG Edit Doesn't Allow Code Block and Numbered List

### ISSUE THREAD

**Issue by AntonPalmqvistGBK** [splitbrain/dokuwiki#2481]
It doesn't let me use a code block in a numbered list. It breaks the numbered list.
I have to go into DW Edit to do that change, which looks like this:
`- <code>Numbered list item with a code block</code>`

Repro:
In CKG Edit mode, create a numbered list and make one of the list items a code block. 
Observe how the numbered list breaks.

I would rather not switch modes just to do this action.

Thanks,
Anton

**Comment by splitbrain** [comment]
please report this to the plugin's issue tracker

**Comment by AntonPalmqvistGBK** [comment]
Will do. Sry for that!
