### ISSUE TITLE
More support hash algorithms for authldap

### ISSUE THREAD

**Issue by mizunashi-mana** [splitbrain/dokuwiki#2489]
LDAP supports {CRYPT}, {MD5}, {SMD5}, {SSHA}, and {SHA}.
However, now, authldap plugin supports only {SSHA}: https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/authldap/auth.php#L348

We can support more algorithms by simple logic, such that:

1. Encrypt password by `auth_cryptPassword`
2. Check hash method such as https://github.com/splitbrain/dokuwiki/blob/cbaf278c50e5baf946b3bd606c369735fe0953be/inc/PassHash.class.php#L31
3. Add scheme
   - smd5, crypt, bcrypt, sha512: {CRYPT}
   - sha1: {SHA}
   - md5: {MD5}
   - ssha, lsmd5: do nothing
   - others: not supported

How is this?

References:
* https://tools.ietf.org/html/rfc2307
* https://linux.die.net/man/8/slappasswd

**Comment by Klap-in** [comment]
Implemented by #2490
