### ISSUE TITLE
Error wehnn the Word "shell" in in Namespace

### ISSUE THREAD

**Issue by mod2509** [splitbrain/dokuwiki#2492]
Hello,
i don't can create a Namenspce with 'powershell' the word 'shell' make Problems.

https://helpdesk.mod2509.de/doku.php?id=software:microsoft:powershell:exchange the result ist Error 403

when i create a site https://helpdesk.mod2509.de/doku.php?id=software:microsoft:powershell then can i edit this.

when i edit the Namespace to 'shells' then can i create ist.
https://helpdesk.mod2509.de/doku.php?id=software:microsoft:powershells:exchange

i have tha last version of dokuwiki

can you help me?

**Comment by mprins** [comment]
perhaps your provider blocks creating directories with the name "powershell", eg https://helpdesk.mod2509.de/doku.php?id=powershell: fails in the same manner

**Comment by splitbrain** [comment]
see https://www.dokuwiki.org/faq:mod_security
