### ISSUE TITLE
Forbidden error when page has specific String

### ISSUE THREAD

**Issue by IvoFritsch** [splitbrain/dokuwiki#2509]
I'm getting an "Forbidden, You don't have permission to access /wiki/doku.php on this server." error when editing/creating an page that contain the string "chmod +x". It's an linux documentation page, so the "chmod +x" string is inside an < code > tag, but even if it's not inside, the error happens.
![image](https://user-images.githubusercontent.com/14312761/45829484-6ac0b100-bcd1-11e8-8899-4508cb313d79.png)
After clicking save:
![image](https://user-images.githubusercontent.com/14312761/45829512-7e6c1780-bcd1-11e8-8f08-a0d80a5b89ef.png)

Thanks in advance for the support.

**Comment by splitbrain** [comment]
https://www.dokuwiki.org/faq:mod_security
