### ISSUE TITLE
Failed to open install.php in Firefox browser but IE.

### ISSUE THREAD

**Issue by Howld** [splitbrain/dokuwiki#2526]
Firefox Version: 62.0.3 (64) Chinese Edition

No idea how dit it happen with show you a dialouge about to save it, and toke a long time on php with my poor konwledge.

**Comment by mprins** [comment]
it would seem that you don't have the php interpreter configured correctly

**Comment by Howld** [comment]
But I can open it with IE.

**Comment by splitbrain** [comment]
your Firefox probably cached the reaponse when the php setup was still faulty.
