### ISSUE TITLE
Dokuwiki - problem with export

### ISSUE THREAD

**Issue by Petebuhler** [splitbrain/dokuwiki#2528]
Hello, 
I`d like to export contain of dokuwiki so we could migrate it to VSTS. I have a couple of points:
1. Is export and then import to VSTS supported?
2. I found this plugin https://www.dokuwiki.org/plugin:advanced, installed it. When I try to do export, I`m getting empty zip file. See the attached screenshot. 
Could you please advise?
Thank you.
Best regards,
Petr

**Comment by splitbrain** [comment]
This is not the right place to ask for support. Use the forum or mailing list instead. Bugs in plugins should be reported in their respective trackers.

**Comment by Petebuhler** [comment]
Hello, Well, I read your first comment. Could you please advise then how I can submit it in the mailing list? I couldn`t find the option there...I`d appreciate that. Thx.

**Comment by mprins** [comment]
see https://www.dokuwiki.org/faq:support

**Comment by Michaelsy** [comment]
>  Could you please advise then how I can submit it in the mailing list?

First you have to subscribe to the mailing list: https://www.dokuwiki.org/mailinglist
After the successful subscription, you can post to the mailing list.

**Comment by Petebuhler** [comment]
Hello,

Ok, thank you. I think I`ve done it before. So I`ll wait for an answer.

Regards,

Petr Smid
Software Tester / Support

Buhler Praha s.r.o.
Jihlavská 1558/21
CZ-14000 Prague 4
Tel: +420 775 668 728

petr.smid@buhlergroup.com<mailto:petr.smid@buhlergroup.com>
www.buhlergroup.com<http://www.buhlergroup.com/>
