### ISSUE TITLE
Have permission but have no rights to edit content

### ISSUE THREAD

**Issue by zcsd007** [splitbrain/dokuwiki#2530]
Hint: "This page is read-only. You can see the source code, but you can't change it. If you think it shouldn't be locked, ask the administrator." And I am the administrator, but I don't know what caused it, request assist.

**Comment by zcsd007** [comment]
+ &do=check Get related tips, but don't know how to fix it
![image](https://user-images.githubusercontent.com/30069113/46843728-b9f88e00-ce06-11e8-97a0-66e0f1acb0e3.png)

**Comment by phy25** [comment]
Please refer to #2525 to get the result of `do=check`.

Again this is a bug tracker, not for general questions, so I have to close this. You may further post that result here, or on the mailing list or the forum.

**Comment by phy25** [comment]
And your issue is the same as #2525. Your webserver's file permission is wrong.
