### ISSUE TITLE
XML RPC Authentication Issue

### ISSUE THREAD

**Issue by gareth-johnstone** [splitbrain/dokuwiki#2544]
So i've got a weird issue (and im not sure if its relating to the current open issues regarding xml-rpc)

I have the following NodeJS Code:

```
const xmlrpc = require('xmlrpc')

let client = xmlrpc.createSecureClient({
	host: 'mydomain.co.uk', 
	port:443, 
	path: '/lib/exe/xmlrpc.php',
	cookies: true,
	basic_auth: {
		user: 'gareth',
		pass: 'NOPE'
	}
})

client.methodCall('dokuwiki.getVersion', [], (error, value) => {
	if (error) {
		console.log('error:', error)
		console.log('req headers:', error.req && error.req._header)
		console.log('res code:', error.res && error.res.statusCode)
		console.log('res body:', error.body)
	} else {
		console.log('value:', value)
	}
})
```

I get the following response from the wiki: 

`<value><string>server error. not authorized to call method dokuwiki.getVersion</string></value> `
(error 401)

I can see that Basic Authentication is being sent.

If i turn off config:remoteuser (or set to `!!NOT-SET!!`) it works no problem at all.

EDIT: Put code in code block

EDIT2: Just tried this in POSTMAN and same issue

**Comment by phy25** [comment]
I cannot reproduce this. Please (1) post your expected format of `config:remoteuser` (you can remove sensitive info, but it should be like `@group,user,@user`); (2) whether your password is correct and (3) clear cookie (that's important) and try again.

**Comment by gareth-johnstone** [comment]
my config:remoteuser is the following: @superusers

My user is in the following groups: editors, new******es, s******ases, j******er, t******al, w*ker, superusers, bloggers, internal (some info starred out)

Password is 100% correct

I've resorted to testing this with postman at the moment and i can confirm that all cookies have been `nuked`

I'm not too sure why this is failing 😂

**Comment by gareth-johnstone** [comment]
my config:remoteuser is the following: @superusers

My user is in the following groups: editors, new******es, s******ases, j******er, t******al, w*ker, superusers, bloggers, internal (some info starred out)

Password is 100% correct

I've resorted to testing this with postman at the moment and i can confirm that all cookies have been `nuked`

I'm not too sure why this is failing 😂

**Comment by gareth-johnstone** [comment]
my config:remoteuser is the following: @superusers

My user is in the following groups: editors, new******es, s******ases, j******er, t******al, w*ker, superusers, bloggers, internal (some info starred out)

Password is 100% correct

I've resorted to testing this with postman at the moment and i can confirm that all cookies have been `nuked`

I'm not too sure why this is failing 😂

**Comment by gareth-johnstone** [comment]
my config:remoteuser is the following: @superusers

My user is in the following groups: editors, new******es, s******ases, j******er, t******al, w*ker, superusers, bloggers, internal (some info starred out)

Password is 100% correct

I've resorted to testing this with postman at the moment and i can confirm that all cookies have been `nuked`

I'm not too sure why this is failing 😂

**Comment by phy25** [comment]
I guess the group name is case sensitive? If you are using `authad` it is case insensitive; the default one is case sensitive; if you are using other auth backend you need to check its definition of `$auth->isCaseSensitive()`, or you can post here and we can help check it.

**Comment by gareth-johnstone** [comment]
Sorry my brain is still in Monday mode 😂

I'm assuming you mean `authtype` `Authentication backend` - in which case this is set to `authplain`

**Comment by phy25** [comment]
Yeah, I don't remember the exact name of it 😂 `authplain` is case sensitive.

As you posted `$config['remoteuser'] = '@Superusers'`, and your user is in `superusers` group. They have different capital letter.

**Comment by gareth-johnstone** [comment]
@phy25  see my edit on the previous post :)

**Comment by phy25** [comment]
@gareth-johnstone OK that's weird. Might need further investigation on this, because I just tried on a local fresh installation several days ago, and it worked.

**Comment by gareth-johnstone** [comment]
When i click the save config button, where is the info saved to?

If i know this i might be able to see what the value of it is

**Comment by phy25** [comment]
`conf/local.php`. It should be the same though.

**Comment by gareth-johnstone** [comment]
Hi, so i've checked the local.php file and i can see the following 2 lines:

```
$conf['remote'] = 1;
$conf['remoteuser'] = '@superusers';
```

**Comment by gareth-johnstone** [comment]
Basic auth is as follows:
![image](https://user-images.githubusercontent.com/13420337/47350113-023c6980-d6ad-11e8-8492-7ff87124853d.png)

Headers:
![image](https://user-images.githubusercontent.com/13420337/47350127-0e282b80-d6ad-11e8-8b0f-78257120960b.png)

Body:
![image](https://user-images.githubusercontent.com/13420337/47350136-141e0c80-d6ad-11e8-83c5-c79c0d18a36d.png)


And the POST URL is: https://******.**.uk/***help/lib/exe/xmlrpc.php

**Comment by gareth-johnstone** [comment]
BUMP =)

**Comment by phy25** [comment]
Hi, sorry for the late reply. Everything you posted looks good, so I would recommend debugging this yourself. You can start with the following to see where the access is blocked:

https://github.com/splitbrain/dokuwiki/blob/cbaf278c50e5baf946b3bd606c369735fe0953be/inc/remote.php#L231-L251

**Comment by MerlinR** [comment]
Im having similar issue's currently with the XMLRPC, im using C and the Basic Auth appears to always fail.

Calling any method such as `dokuwiki.getTime` results in a the `-32603` error, however if I call `dokuwiki.login` with my username and password as parameters rather then relying on Basic Auth i can login. 

Any call after this login still results in `Method does not exist - wrong parameter count. (-32603)`

**Comment by phy25** [comment]
@MerlinR Your issue is totally different from this one. Please either open a new issue or make use of mailing list or forum.

Please try using a debugging proxy with your program (e.g. Fiddler) and checking the request your program actually sends.

**Comment by mpcjanssen** [comment]
I have the same issue.  Debugging it shows that `$INPUT->server->str('REMOTE_USER')` is empty. This is using Caddy. This issues https://caddy.community/t/php-server-remote-user-not-set/4881 seems related.

**Comment by mpcjanssen** [comment]
`return auth_isMember($conf['remoteuser'], $INPUT->server->str('PHP_AUTH_USER'), (array) $USERINFO['grps']);`
gives the correct username from the basic authentication header (auth still fails though)

**Comment by mpcjanssen** [comment]
Not sure wether this is relevant, but authentication is `plainauth`. The actual call to `auth_isMember` returns false and is:

```
return auth_isMember("@admin", "myusername", (array) "");
```

**Comment by mpcjanssen** [comment]
If I change `remoteuser` to `mysusername` it does work (after changing the auth_isMember parameter to `$INPUT->server->str('PHP_AUTH_USER')`)

**Comment by mpcjanssen** [comment]
Postman is also very tenacious with storing cookies it receives.

**Comment by phy25** [comment]
I would assume this is resolved, but if anyone still needs help, please ping us or reopen the issue.
