### ISSUE TITLE
Upgrade Plugin: Download Failed

### ISSUE THREAD

**Issue by benbrunner** [splitbrain/dokuwiki#2552]
The Archive seems to be moved. Any solution to upgrade dokuwiki using the Plugin?

>  Downloading archive from https://github.com/splitbrain/dokuwiki/archive/stable.tar.gz...
> ! Could not connect to ssl://github.com:443 (0)
> ! Download failed.

Unfortunately upgrading manual results in Permissions not working, although the config has been copied over from the running version.

**Comment by Klap-in** [comment]
I'm enable to download that archive here.

Please provide more details e.g. about your setup.
OS/webserver/PHP, versions, etc etc.

**Comment by benbrunner** [comment]
It`s running on IIS8, Server 2012 R2, PHP 5.3.28, Dokuwiki 2014-09-29b "Hrun".

- I tried newer PHP versions, but then I get an Error 500 from IIS, even with just PHP 5.6.0.
- Also tried different versions of the Upgrade Plugin.

**Comment by Klap-in** [comment]
As explained at https://www.dokuwiki.org/requirements, the minimum PHP version is 5.6.
Not sure if that the older version give already troubles for this issue, but otherwise you will face other issues later. (Further, older versions of PHP do not receive (security) updates anymore).

If you have a Error 500, you need to check your logs of the webserver to see why it stops.

**Comment by benbrunner** [comment]
Thanks, the error was caused by the PHP_MYSQL in php.ini. After disabling it, I can reach the Login-Page of DokuWiki, yet can not login:

> AD Auth: PHP LDAP extension not found.
> User authentication is temporarily unavailable. If this situation persists, please inform your Wiki Admin.
> No ACL setup yet! Denying access to everyone.

**Comment by phy25** [comment]
You need to install LDAP extension to your PHP installation.

**Comment by splitbrain** [comment]
Woah, there's a lot in this ticket that doesn't add up. Let's take a step back.

First of all this is a report related to the upgrade plugin and thus should be reported in the plugins' tracker. However it seems not to be a bug but more an issue of usage/configuration, so the forum would be a better place anyway. But let's look at the issues here.

Your original report says "Could not connect to ssl://github.com:443" - that can have multiple reasons:

* no SSL support
* a firewall blocking outgoing connections
* some TLS incompability
* maybe something else

Then you started upgrading PHP, which makes sense as you need at least 5.6 to upgrade to the recent version. However you ran into problems with MySQL, which you fixed somehow only to run into problems with LDAP. Both are not used by DokuWiki unless you use the mysql or ldap/AD authentication backends. Unfortunately you never specified your setup...

Here is what you need to do:

Upgrade your PHP to 5.6 as this is probably the only version your current DokuWiki release will run on. Methodically analyse and fix any problems you find. Your Wiki must run okay on 5.6 before you go any further. Be sure your PHP has SSL support and the needed extensions for your auth backends.

Once you have it running on 5.6, use the upgrade plugin to upgrade to the most recent version. Ensure everything is running fine (this includes upgrading plugins).

Finally upgrade to a more recent PHP version. Again methodically analyse and fix any problems.

Once you're done, keep PHP and your wiki up-to-date.

If you have problems with the steps in between, ask in the forum (be sure to describe your problems with all the symptoms, error messages etc and always tackle one problem a time) or hire someone to help if this is a business setup.
