### ISSUE TITLE
Bug of encoding of specific Chinese character in link

### ISSUE THREAD

**Issue by changgang** [splitbrain/dokuwiki#2557]
One bug is found when using latest version of Dokuwiki (installed on October. 15, 2018) on Windows Server 2012 R2.

Since I am using Doku as my group wiki in China, I changed 'fnencode' option to 'utf-8' to support Chinese, and enabled 'canonical'.

If I create a page with pagename including character of '雅', the creation will fail. For example, if I add '[[.newpage雅abc]]' to some page, the link will lead me to create a new page named 'newpage'. Any character following the character '雅' will be lost. All links to pagename or media files with the character ’雅' are failed to work. As far as I tested, links with other Chinese characters work very well.

Maybe this is a general bug of encoding. 

Is it possible to fix the bug by changing any options?

**Comment by splitbrain** [comment]
What filesystem are you using? Which PHP version? Does it work with any of the other fnencode options?

**Comment by phy25** [comment]
Are you using IIS? I think it might be related to IIS, because on (Apache-based environment) it works: https://www.dokuwiki.org/playground:newpage%E9%9B%85abc

**Comment by phy25** [comment]
I guess you are using URL rewrite? I can reproduce this on XAMPP, but your config of `.htaccess` is important to diagnose the issue.

**Comment by changgang** [comment]
> @changgang You can try replacing a line in .htaccess (`RewriteRule (.*) doku.php?id=$1 [QSA,L]`) with the following:
> 
> ```
> RewriteRule ([\W\w]*)                 doku.php?id=$1  [QSA,L]
> ```
> 
> Windows Apache seems not smart enough to match every Chinese character.


Great. I do use .htaccess.

With your suggestion, all pages with the problem character work very well. But some links to media files still suffer this problem.

So, I changed all `(.#)` to `([\W\w]#)`. Original four lines in my htaccess file were:

`RewriteRule ^_media/(.*)              lib/exe/fetch.php?media=$1  [QSA,L]
RewriteRule ^_detail/(.*)             lib/exe/detail.php?media=$1  [QSA,L]
RewriteRule ^_export/([^/]+)/(.*)     doku.php?do=export_$1&id=$2  [QSA,L]
RewriteRule (.*)                      doku.php?id=$1  [QSA,L]`

Now they are
`RewriteRule ^_media/([\W\w]*)              lib/exe/fetch.php?media=$1  [QSA,L]
RewriteRule ^_detail/([\W\w]*)             lib/exe/detail.php?media=$1  [QSA,L]
RewriteRule ^_export/([^/]+)/([\W\w]*)     doku.php?do=export_$1&id=$2  [QSA,L]
RewriteRule ([\W\w]*)                      doku.php?id=$1  [QSA,L]`

And everything works very well.

Thanks a lot. I do appreciate your work in dokuwiki. @phy25 @splitbrain

**Comment by splitbrain** [comment]
Interesting. I wonder if it would be worth to include this change into our .dist files. I don't really understand why `.*` should fail to match a chinese UTF-8 char when `[\W\w]` does. This is either a bug in Apache or some badly documented behaviour.

**Comment by changgang** [comment]
@splitbrain Thank you very much for your contribution. I would like to suggest that UTF-8 should be set as the default encoding. In case I need to modify something from the server directly, I should be able to locate the specific files. If I am using languages different from EN, the folder name or file name may be something like %E2%E3, which is not friendly to human beings.
Rewrite is also a good method to show links to someone else.

**Comment by phy25** [comment]
@changgang Do you mean `$config['fnencode']`? I believe the default will never be `utf8` due to compatibility reason:

> Warning: Changing this option could cause unintended behaviour. By changing it you can make pages created under a previous setting inaccessible.
>
> Please also note that storing UTF-8 filenames might not be possible with all file systems. Windows systems have been reported to not work with this setting. (See discussion below).

https://www.dokuwiki.org/config:fnencode

Please let me know if you think it's necessary to reopen the issue.
