### ISSUE TITLE
sitemap (do=index) only shows top level namespaces

### ISSUE THREAD

**Issue by peter013** [splitbrain/dokuwiki#2560]
Sitemap only shows namespaces in the toplevel - if I click on such a toplevel namespace dokuwiki should show also lower level namespaces but it doesn't - two rotating arrows are shown.
In the past all namespaces have been shown without problem - so maybe due to some update this has changed.

The problem occurs also  if I'm locked in as Admin.
Searching for pages is not a problem.
Once I have found a lower level page the sitemap shows the related namespace ... but only for this page not for other namespaces (this was different in the past).

I didn't change the configuration:
- 'disableactions'  are not selected
- 'sneaky_index' is not selected

I have the problem on two different (in-depended) systems both running dokuwiki (20140505.a+dfsg-4+deb8u1) on Debian (Jessie, 3.16.0-5-amd64).

Suggestions are welcome.

**Comment by mprins** [comment]
perhaps best to upgrade to a supported version of DW, many things have changed for the better

**Comment by peter013** [comment]
Unfortunately, Debian 9 ('stretch') does not offer dokuwiki (at all) and Debian 10 ('buster') which includes a new version of dokuwiki is not yet released (but only available as testing) ...
