### ISSUE TITLE
Please upgrade geshi for PHP 7.2 compatible

### ISSUE THREAD

**Issue by mizunashi-mana** [splitbrain/dokuwiki#2563]
See https://github.com/GeSHi/geshi-1.0/issues/98.

Current geshi bundled DokuWiki uses `create_function` which is deprecated by PHP >= 7.2 .
Now, when plugin developers use https://github.com/splitbrain/dokuwiki/blob/433bb3d9e325aaf5ef5336ade064384fe07977dd/inc/parser/xhtml.php#L586, they get below errors:
```
Function create_function() is deprecated
```

Please upgrade geshi version to one removed `create_function`.

**Comment by phy25** [comment]
This can be done after waiting for GeSHi's version release (currently 1.0.9.0). The change is in master, but not in a released version yet.

**Comment by mbomb007** [comment]
It has been committed to master, but there hasn't been a new release yet. See https://github.com/GeSHi/geshi-1.0/issues/106

**Comment by Oreolek** [comment]
[GeShi 1.0.9.1](https://github.com/GeSHi/geshi-1.0/releases) everyone

**Comment by phy25** [comment]
Already fxed in #2894.

@Oreolek I am not sure if you actually see the issue in the latest master branch, but if you do please let us know.
