### ISSUE TITLE
support drag n drop image n auto insert image syntax

### ISSUE THREAD

**Issue by fghhfg** [splitbrain/dokuwiki#2579]
insert a image to a page need at least 5 step:

click img icon - drag n drop - click upload - click img url - click insert.
  https://www.inmotionhosting.com/support/edu/dokuwiki/writing-content-dokuwiki/inserting-images-doku

suggest 1 step:
drag n drop images in editor, it would upload images and automatically insert image syntax is a better ideal.

**Comment by Klap-in** [comment]
This plugin performs exactly your requested feature: https://www.dokuwiki.org/plugin:dropfiles
It has a configuration setting, that let you enable auto including a link in the editor as well.

**Comment by fghhfg** [comment]
@Klap-in thx, I don't know it has a configuration setting.

I'm a newbie.
In my opinion, by current standards, it should be a default feature.
