### ISSUE TITLE
Make it more user-friendly

### ISSUE THREAD

**Issue by kalahiri** [splitbrain/dokuwiki#2583]
I am new at DokuWiki and it looks very promising. Great!

But the management system is way too complex. It took me a while to understand how to create new user groups. Now I am trying to give a user group permission to create pages, but that is not possible. Apparantley, one has to create namespaces for that. This is way to difficult for a normal user, like me. 

Can there be a button to create a new user group?
Can there be a simple way to give users the permission to create pages?

Thanks!

**Comment by nilssiegle** [comment]
Hey kalahiri, welcome to DokuWiki!

It is entirely possible to specifiy access rights on a file basis, there is no need to create (additional, as you will always have a root-namespace) namespaces.  
You dont have to explicitly create groups, just assign them to a user in the [User Manager](https://www.dokuwiki.org/plugin:usermanager). The group will be created automatically if it is used the first time.

To specify access rights, please check the documentation on [ACLs](https://www.dokuwiki.org/acl). In short, select the page (or namespace) you want to specify rights for on the right side, the select a group (or user) from the dropdown in the top center of the page, and use the radio button menu for selecting the access level.

I hope I could help you
