### ISSUE TITLE
Namespace called 0 creates some problems

### ISSUE THREAD

**Issue by tormec** [splitbrain/dokuwiki#2610]
From the search bar, try to create the page
`0:start`

- put some content, save the page but the sidebar vanishes. Come back to `:start` and the sidebar reappear;
- from any page, try to add a link to `0:start` using `Link Wizard`  but you can't navigate into `0` namespace.

These issues don't happen if `0` namespace is in the middle, i.e. `foo:0:start`, or with `00:start`, `01:start`.

Tested with: Release 2018-04-22a "Greebo"

**Comment by tormec** [comment]
This is an error that I caught installing a plugin:

> Fatal error: Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /home/tormec/dokuwiki/inc/pageutils.php on line 713

and the last two functions (255 and 256) in the call stack are:

> metaFN(  ) | .../parserutils.php:424
> utf8_encodeFN(  ) | .../pageutils.php:352

Maybe could give a clue (right or wrong) from where to start..

**Comment by splitbrain** [comment]
Yeah, we probably have a lot of places where we do a simple boolean comparison without strict type checking. "0" evaluates to false even though it's not an empty string. Fixing this will be tedious. First start should be creating (failing) unit tests for all these problems. PRs welcome.

**Comment by phy25** [comment]
Hello @tormec, when you say "sidebar vanishes", what template are you using? The default dokuwiki template doesn't have a sidebar.

**Comment by Klap-in** [comment]
@phy25 DokuWiki has a setting for enabling the sidebar. This setting is also supported by the default 'dokuwiki' template. See also 
https://www.dokuwiki.org/config:sidebar

**Comment by phy25** [comment]
@Klap-in Thanks! Hardly uses that 😅

I have reproduced the sidebar behavior as well... Fix coming.

**Comment by tormec** [comment]
The second point of this issue
> from any page, try to add a link to 0:start using Link Wizard but you can't navigate into 0 namespace.

still persists (tested the master branch)
