### ISSUE TITLE
Error: A PCRE backtrack error occured

### ISSUE THREAD

**Issue by VadimBalabin** [splitbrain/dokuwiki#2611]
Get error on a new version Dokuwiki - **2018-04-22a "Greebo"**, and page not parsed.
![err](https://user-images.githubusercontent.com/44360083/49284719-d9c73c80-f4ae-11e8-9525-e4ff81996944.png)

Edit `pcre.backtrack_limit` in php.ini on more value - no result.
On a previous version - **2017-02-19e "Frusterick Manners"** no problems, page parsed correct

**Debug info:**
[debug.txt](https://github.com/splitbrain/dokuwiki/files/2632946/debug.txt)

**Comment by splitbrain** [comment]
does this happen on all pages or just this one? Is this page using any plugins? can you attach the page source here?

**Comment by VadimBalabin** [comment]
This problem happen on some page. 
Are use plugins on a page: **Bootstrap Wrapper Plugin** and **fontcolor**

**Example source  page:**
[playground.txt](https://github.com/splitbrain/dokuwiki/files/2636054/playground.txt)

**Comment by Klap-in** [comment]
Just trying this source text at dokuwiki.org, without plugins, parses without interuption.
(of course not everything is interpreted due to missing plugins)

e.g. https://www.dokuwiki.org/playground:issue2611

**Comment by VadimBalabin** [comment]
Yes, if disable **Bootstrap Wrapper Plugin**, page parsed without error.
But on previous version - **2017-02-19e "Frusterick Manners"**, not happened error.

**Comment by phy25** [comment]
I would recommend reporting the issue to https://github.com/LotarProject/dokuwiki-plugin-bootswrapper/issues as well.
