### ISSUE TITLE
Reload of read protected page fails after some time

### ISSUE THREAD

**Issue by ypl-github** [splitbrain/dokuwiki#2612]
If I view a page which is not readable by everyone (but for the user I am logged in as), wait for >2 hours, and press reload, I will be forwarded to the start page.

(This can be unhandy in teaching situations or while having pages open for documentation while coding.)

**Comment by splitbrain** [comment]
Which auth backend are you using? What DokuWiki version?

**Comment by splitbrain** [comment]
It's a (somewhat known) problem with the oauth plugin. Please report in the plugin's tracker.
