### ISSUE TITLE
Namespace with (at least 1) upper cases becomes page

### ISSUE THREAD

**Issue by tormec** [splitbrain/dokuwiki#2613]
Tring to create the following pages from the search bar, the namespaces are converted in pages:
`Foo` -> `:foo`
`Foo:bar` -> `:foo_bar`
`foobar:Foo:bar` -> `:foobar_foo_bar`
`FooBar:foo:bar` -> `:foobar_foo_bar`

A similar issue was discussed here #2355.

The problem doesn't happen if these pages are created as links.

Tested with: Release 2018-04-22a "Greebo"

**Comment by phy25** [comment]
That's because the upper cased page name is not a clean ID. Does it help (and is it safe) if the following comparison is case insensitive (through `strtolower`)?

https://github.com/splitbrain/dokuwiki/blob/42690e4d38f9519f308f64893283e7d5ad3616f4/inc/Ui/Search.php#L501-L504
