### ISSUE TITLE
Use Popularity plugin to collect events used in action.php by each plugin

### ISSUE THREAD

**Issue by tormec** [splitbrain/dokuwiki#2615]
The list of plugins that use action events (the one at the bottom of each action event page) is neither complete nor up-to-date.

Do you think it's worth to use the [Popularity plugin](https://www.dokuwiki.org/plugin:popularity) to collect all the events `register()`ed by each plugin and print the data in only one page in dokuwiki.org?

If different dokuwiki installations have different versions of the same plugin (the last one and an older one), before check if the plugin installed is the last release, otherwise, don't send any data.

**Comment by phy25** [comment]
😕 This can be done with (maybe) static/dynamic code check, automated with robots crawling the plugin codebase. I don't think this is the data that popularity plugin is intended to collect.

**Comment by tormec** [comment]
You are right and what I'm looking for was already done with https://www.dokuwiki.org/devel:plugin_survey:start, in particular with https://www.dokuwiki.org/devel:plugin_survey:events but data seem to be not up-to-date (last survey 2011?). Maybe that info could be collected once a year.

**Comment by splitbrain** [comment]
The easiest way is to use https://codesearch.dokuwiki.org which allows you to search nearly all the dokuwiki plugins. There's also a interwiki shortcut (which should be added to all the event pages) eg. ``[[codesearch>TPL_ACT_RENDER|Code related to this event]]``

**Comment by tormec** [comment]
At this point, I wonder if the `Plugins handling this event` paragraph can be removed from each event page in favour of the more complete and up-to-date interwiki link provided by `[[codesearch>...]]`.

If necessary that link could be inserted in a more explicative sentence as in:

> ### See also
> - Which DokuWiki's files, plugins and templates have `[[codesearch>TPL_ACT_RENDER|Code related to this event]]`

or

> ### See also
> - `[[codesearch>TPL_ACT_RENDER|Code related to this event]]` used in any DokuWiki's files, plugins and templates

**Comment by splitbrain** [comment]
I am all for it. Go ahead and change the pages accordingly.
