### ISSUE TITLE
Some bullet points are displayed as code block

### ISSUE THREAD

**Issue by KiraResari** [splitbrain/dokuwiki#2616]
The following text, when written in a DokuWiki Page...

```
=== Test ===

----

**Test1**

  * test:<code>
test
</code>
  * test

**Test2**
  
  * test
  * test

**Test3**

  * test
  * test
    * **test:** test
```

...for some reason the central two bullet points (under Test2) are displayed as code instead.

![doku wiki formatting error bullet points code block](https://user-images.githubusercontent.com/28697173/49361842-53b22c80-f720-11e8-9332-35d03fd5c739.png)

**Comment by subi54** [comment]
@KiraResari, yes I think it's in the [Syntax](https://www.dokuwiki.org/wiki:syntax) under Code Blocks that code blocks can be included in a document by indenting 2 spaces. Use the normal `\\ ` for line breaks in lists or anywhere really.

**Comment by tormec** [comment]
@KiraResari Under `**Test2**` you have 2 blank spaces (try to select the code you posted here), which determine the beginning of a `code` block as @subi54  point out.

Remove those spaces and the bullet points are rendered as you would expect.

**Comment by KiraResari** [comment]
Ahh, I see! Formatting by whitespace!
Thank you for pointing that out! I would have never thought of that =^,~'=
