### ISSUE TITLE
Warning messages with PHP 7.3

### ISSUE THREAD

**Issue by yasuhirokimura** [splitbrain/dokuwiki#2622]
OS: FreeBSD 11.2-RELEASE
PHP: 7.2.12 -> 7.3.0 (Installed using FreeBSD port)
DokuWiki: 20180422a (Installed using FreeBSD port)

After update PHP to 7.3, following messages are displayed on the top of page.

```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/www/dokuwiki/inc/parser/handler.php on line 1552

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/www/dokuwiki/inc/parser/handler.php:1552) in /usr/local/www/dokuwiki/inc/actions.php on line 38

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/www/dokuwiki/inc/parser/handler.php:1552) in /usr/local/www/dokuwiki/lib/tpl/dokuwiki/main.php on line 12
```
They are disappeared when accessing same page. But displayed again if I clear files and directories under `$conf['savedir']/cache`.

**Comment by onkobu** [comment]
This also breaks JavaScript. jquery.php starts with: <br />
<b>Warning</b>:  …

**Comment by splitbrain** [comment]
This has been fixed in 296be24e7163baa3d0fe1d80f2e107320e88010a

@bug this is a simple one-line fix. Should we release a hotfix for PHP 7.3 compability?

**Comment by phy25** [comment]
Closing because of the release of 2018-04-22b.

**Comment by onkobu** [comment]
Works perfectly, thanks a lot.
