### ISSUE TITLE
Superimposed "This topic does not exist yet" when printing page from browser

### ISSUE THREAD

**Issue by jfrench206** [splitbrain/dokuwiki#2623]
Hi,

I'm trying to print pages from the wiki at https://docs.pixycam.com (where I'm an admin) using the browser's Print function -> save to PDF. The page formats properly, but also, I get the "This topic does not exist yet" message superimposed on top of the text at the beginning of the page. See example, attached.

Release 2018-04-22a "Greebo"
Ubuntu 16.04
Chrome & Firefox
doesn't matter if I'm logged into dokuwiki or not.

[pantilt help.pdf](https://github.com/splitbrain/dokuwiki/files/2658808/pantilt.help.pdf)

**Comment by Michaelsy** [comment]
Another hint: When I click on "Index" at https://docs.pixycam.com I get the error message "This topic does not exist yet" too.

**Comment by Michaelsy** [comment]
By disabling javascript the error message in the print output disappears.

**Comment by Michaelsy** [comment]
> Could you share the list of plugins you installed in your wiki please?

I suspect the error is due to the (likely) incorrectly configured plugin, which is responsible for the "Index" button.

**Comment by Klap-in** [comment]
After a bit digging, I think that a part of the overlay plugin ( https://www.dokuwiki.org/plugin:overlay ) is shown during printing.
I expect that this plugin could add some specific CSS for hiding during printing (e.g. using a `print.css` file, https://www.dokuwiki.org/devel:css).

**Comment by Michaelsy** [comment]
> After a bit digging, I think that a part of the overlay plugin ( https://www.dokuwiki.org/plugin:overlay ) is shown during printing.

Yes, that seems obvious to me, since the same error message also appears in an overlay window, which appears after clicking the "Index" button.

**Comment by jfrench206** [comment]
Oops - I wasn't receiving updates on this, sorry for lack of response! Thank you for the detective work - I disabled the Overlay plugin, which we weren't using anyway, and the issue is resolved.

**Comment by phy25** [comment]
An issue can be opened at https://github.com/turnermm/Dokuwiki-Nav-Overlay
