### ISSUE TITLE
Inability to Save Via VPN

### ISSUE THREAD

**Issue by Softball15** [splitbrain/dokuwiki#2625]
My colleagues and I have noticed an inability to save edits to our wiki via VPN. We get an error message saying the connection was reset, but this happens even in the short span of clicking to edit and adding a space (less than 10 seconds). We did some trouble shooting and noticed that things seemed to fail around the phrase "case when" in code blocks. We tried moving things around on the page and adding additional random text after case when. We couldn't save with case when, but we could add whatever else we wanted in place of case when to extend the length of the page. At one point we were able to save if we had 4 spaces between case and when, but that wasn't consistent. In consulting with IT, there doesn't seem to be a setting they have on the VPN to regulate this. What are we missing here?

**Comment by splitbrain** [comment]
sounds like https://doku.wiki/mod_security to me
