### ISSUE TITLE
future wish : full markdown support 

### ISSUE THREAD

**Issue by F3000** [splitbrain/dokuwiki#2637]
It would be grade to write text in standard markdown without a plugin for that . 

Is this planned for one of the next updates ?

**Comment by phy25** [comment]
You are welcome to use a plugin: https://www.dokuwiki.org/plugin:markdownextra

**Comment by MyIgel** [comment]
Unfortunately this plugins have some sideffects and especially problems when using tags that are interpreted by the default parser

**Comment by phy25** [comment]
@MyIgel [Renderer plugins](https://www.dokuwiki.org/devel:renderer_plugins) should be able to do that. You may want to build such one based on existing plugins.

**Comment by mprins** [comment]
There is no such thing as "standard" when it comes to markdown - there are many, many "flavours", the common denominator compares poorly to the wealth of DW-built-in + syntax plugins available today, eg. no support for tables in [markdown](https://daringfireball.net/projects/markdown/syntax)

Also markdown allows inlining HTML markup, which circumvents various XSS security features built into DW

**Comment by phy25** [comment]
> "markdown allows inlining HTML markup"

I believe this can be adjusted in line with `htmlok` config. Shouldn't be a big deal.

---

The issue here is if anyone has the resource to develop an "official" plugin for this. I don't think it will be "a standard of DokuWiki" based on the syntax system DokuWiki already has.

**Comment by Klap-in** [comment]
btw: this plugin https://www.dokuwiki.org/plugin:markdowku has a more integrated approach. However, the exact working of these plugins I do not know. So that is something you have to test your self.

**Comment by mckaygerhard** [comment]
HI it seems  https://www.dokuwiki.org/plugin:markdowku has a more integrated approach but development is stalled since 2023.. so still dokuwiki need a modern markdown parser

Most wikis moved to markdown today!
