### ISSUE TITLE
User Manager does not open with Authad plugin

### ISSUE THREAD

**Issue by carloscondit** [splitbrain/dokuwiki#2643]
Hi all! I have install 2018-04-22a "Greebo" dokuwiki. Activate and configuire Authad plugin. Authentication work but User manager page does not open. I see "500 internal server error". I use IIS7 on windows server 2008 R2 and php 7.3. Can anybody help me? Help in advance!

**Comment by Klap-in** [comment]
See the log of your web server, please.

**Comment by carloscondit** [comment]
> See the log of your web server, please.

Can you give me instructions how do this right?

**Comment by carloscondit** [comment]
> See the log of your web server, please.

Sory. I resolve my problem. I have too many objects in base DN. PHP Warning:  ldap_search(): Partial search results returned: Sizelimit exceeded in C:\inetpub\wwwroot\wiki\lib\plugins\authad\adLDAP\classes\adLDAPUsers.php on line 557
