### ISSUE TITLE
Update coding standard to support phpcs version 3.x

### ISSUE THREAD

**Issue by cvoltz** [splitbrain/dokuwiki#2654]
The `PHP_CodeSniffer` [coding style](https://www.dokuwiki.org/devel:coding_style) provided in `_cs/DokuWiki` doesn't support the latest version of [PHP_CodeSniffer](http://pear.php.net/package/PHP_CodeSniffer). Version 3.x broke compatibility with earlier sniffs. Running `phpcs` version 3.3.2 results in errors like this:
```
PHP Fatal error:  Interface 'PHP_CodeSniffer_Sniff' not found in .../_cs/DokuWiki/Sniffs/Functions/OpeningFunctionBraceSniff.php on line 6
```

Documentation on how to upgrade 2.x sniffs to 3.x is available at https://github.com/squizlabs/PHP_CodeSniffer/wiki/Version-3.0-Upgrade-Guide.

Also, on Fedora 29, the command to install the DokuWiki coding style is:
```
ln -s /path/to/dokuwiki/_cs/DokuWiki /usr/share/pear/PHP/CodeSniffer/src/Standards/DokuWiki
```
as the coding standards have been moved to the `src` subdirectory.

**Comment by phy25** [comment]
Thanks for your information. Just read through the upgrade guide, and hopefully this only involves class name changes to namespaced ones.

The issue is if we want to support both 2.x and 3.x, a compatibility layer has to be written from scratch  (like the one we use for PHPUnit).

**Comment by splitbrain** [comment]
With #2358 the _cs dir will become obsolete. The recommended way to run codesniffer will be the phar file, so we only need to support 3.x
