### ISSUE TITLE
New unknown version 2018-04-22b

### ISSUE THREAD

**Issue by zeldor** [splitbrain/dokuwiki#2655]
Hey all,

just saw a new version of dokuwiki: 2018-04-22b
But don't found any changelogs related to this release as usual on https://www.dokuwiki.org/changes

Please provide some information to this release to help me and the community to make decisions about this update and the criticality of it.

Thanks and BR
zeldor

**Comment by phy25** [comment]
Specifically you can see what's changed at GitHub compare, if you cannot wait: https://github.com/splitbrain/dokuwiki/compare/release_stable_2018-04-22a...release_stable_2018-04-22b

Click on the ellipsis icon on each commits, and it gives you a more detailed description.

[The mailing list announcement](https://www.freelists.org/post/dokuwiki/New-Hotfix-releases-are-available,2) should give you a TL;DR version:
> They contain a compatibility fix for PHP 7.3 and a fix for ACL check.

And yeah, I agree that the changelog should be added anyway.

**Comment by bug** [comment]
Changelog updated
