### ISSUE TITLE
Icon for SVG file

### ISSUE THREAD

**Issue by tiborepcek** [splitbrain/dokuwiki#2674]
Hi.

As i wrote in forum (https://forum.dokuwiki.org/post/64438), i need a new icon for SVG file.

I managed to draw 16x16 and 32x32 png icons for svg files thanks to file icon generator. I also added these png files to lib/images/fileicons and lib/images/fileicons/32x32. And how can i now show that icons?

Thanks.

**Comment by Klap-in** [comment]
I guess the previous icons are still cached.
Resave the Configuration Manager to expire DokuWiki caches. And refresh the browser caches by Ctrl+F5 or Ctrl+R, or what your browser supports.

**Comment by tiborepcek** [comment]
It helped, problem solved. :)

Thank you @Klap-in !

**Comment by Klap-in** [comment]
Could you provide these icons here as well please? Or, of course, a pull request to include them is welcome!

**Comment by tiborepcek** [comment]
![svg16](https://user-images.githubusercontent.com/10828749/51426342-9bfeae80-1be9-11e9-92bd-bb1af0f67e81.png)
![svg32](https://user-images.githubusercontent.com/10828749/51426343-9bfeae80-1be9-11e9-8ee0-2b7f05a55cd1.png)

**Comment by Klap-in** [comment]
Added via #2675 and #2677.
