### ISSUE TITLE
copy paste data repo dokuwiki  issue

### ISSUE THREAD

**Issue by Balduin94** [splitbrain/dokuwiki#2685]
I copy pasted the data repo in a new dokuwiki, although i can acces the pages the sitemap doesn't get updated so i can't control the ACL and other stuff.

I have pushed the dokuwiki to an ftp server and now not only the sitemap doesn't exist, but the internal link to the pages doesn't work anymore. Internal links to those files doesn't work..

**Comment by Balduin94** [comment]
what i mean is tpl_content return page not yet created, and so   
```
  $html_output = ob_get_clean();
    trigger_event('TPL_CONTENT_DISPLAY', $html_output, 'ptln');
```  
In template.php doesn't find my pages and so give me back the nothing here answer.

**Comment by phy25** [comment]
Would you please do a `?do=check` and see the results?

e.g. if this is your homepage `https://www.dokuwiki.org/start`, then visit `https://www.dokuwiki.org/start?do=check`.
