### ISSUE TITLE
Update requiered PHP version

### ISSUE THREAD

**Issue by AnaelMobilia** [splitbrain/dokuwiki#2688]
Hello,

As wrote on the dokuwiki site and on the composer.json file, dokuwiki 2018-04-22 requiered at least PHP 5.6 .

When you make an install on PHP 5.6 and you try to authenticate, you got an error : 
Fatal error: Call to undefined function random_bytes() in /path/to/dokuwiki/inc/auth.php on line 339

As random_bytes is introduced on PHP7.0, website and composer.json files should be updated :-).

Regards,
Anael

**Comment by splitbrain** [comment]
We use a compatibility layer when random_bytes is not available. Your installation went wrong.
