### ISSUE TITLE
mixing client certificate authentication with ldap (or any other) authentication

### ISSUE THREAD

**Issue by paweljasinski** [splitbrain/dokuwiki#2694]
What I need:
- user from ldap (or any other auth source) is directed to standard username/password page for authentication
- user with smartcard (client certificate) are not directed to standard authentication page, instead they are automatically logged on. In addition, if the user with smartcard logs in first time, the user record is created and default group is assigned.

What I have done:
- configure reverse proxy (haproxy) to verify and forward user cert as http header
- modified authremoteuser plugin to consume user certificate and logon user (create if missing). Username, real name and email are retrieved from certificate.
- tested above plugin as standalone
- made modification to inc/auth.php and authchained plugin to make it work with other plugins

What would be ideal:
- New plugin is published/documented.
- New plugin is configurable (e.g. cert -> user info mapping).
- The changes I made to dokuwiki and authchained are accepted as PR

As soon as I have published the plugin, I will post link here.

I am new to dokuwiki and php - any feedback is appreciated.

**Comment by Klap-in** [comment]
If you have a proposal for changes in DokuWiki, please open a PR. Using a PR is a practical manner to have a specific discussion about these changes. 

About how to develop and publish your own plugin, you could find more details at:
https://www.dokuwiki.org/devel:plugins and https://www.dokuwiki.org/devel:auth_plugins
Success!
