### ISSUE TITLE
ACL wildcard for translation

### ISSUE THREAD

**Issue by Rainbow-Spike** [splitbrain/dokuwiki#2700]
I use Translation plugin and try to write ACL as
```*:folder:* @user 8```
Failed. Please, fix first asterisk checking with list from $lang['translations']

**Comment by phy25** [comment]
Hello, is this the exact error message or translated from other languages? I don't seem to find this sentence from either DokuWiki or translation plugin. Please post the original error message if there's any. Also it might come from other plugins.

**Comment by Dr-Yukon** [comment]
No, it's my phrase. Please add wildcards.

**Comment by phy25** [comment]
I am still not sure if this is an issue with translations plugin, or you want multiple wildcard support in ACL. Will look into this later.

**Comment by Dr-Yukon** [comment]
> I am still not sure if this is an issue with translations plugin, or you want multiple wildcard support in ACL. Will look into this later.

Even without translation plugin it would be very useful

**Comment by phy25** [comment]
See #1957 and #30. Though, your use case is definitely a new idea.

**Comment by Rainbow-Spike** [comment]
I think about already implemented %USER% variable. What if set %LANG% in the rules?

**Comment by Rainbow-Spike** [comment]
I think about already implemented %USER% variable. What if set %LANG% in the rules?

≺(☉6☉)≻ +18 points in Google PageSpeed!
