### ISSUE TITLE
Accessing invalid page with slash in results in infinite redirect

### ISSUE THREAD

**Issue by abeverley** [splitbrain/dokuwiki#2706]
If an invalid page is requested within Dokuwiki then a user is redirected to the main index page. However, if the invalid page that is requested contains a slash, then an infinite redirect loop is encountered. That is because the redirect code here: https://github.com/splitbrain/dokuwiki/blob/3d25409cdbc5c6da66d7e0bc8fe1eff5d5bcf9d3/index.php#L17 does not redirect to an absolute URL, and therefore the relative URL that the browser uses will simply redirect back to another invalid URL.

E.g. if the invalid URL of http://example.com/index.php/doku.php is requested, then a redirect to ```doku.php``` will result, which will just redirect back to the same page.

**Comment by micgro42** [comment]
Example: https://www.dokuwiki.org/index.php/doku.php
