### ISSUE TITLE
Locked edit page is missing read-only source 

### ISSUE THREAD

**Issue by bobcanthelpyou** [splitbrain/dokuwiki#2714]
In "Greebo" the read-only source code of a page is no longer shown on a locked edit page (compared to "Frusterick Manners"). That issue was already fixed by #2475. Will that fix be released with one of the next Hotfix releases of “Greebo”? Or will it be available in the next stable release, only?

**Comment by splitbrain** [comment]
hotfixes are usually only released for security bugs or severe issues. So this fix will have to wait for a release.
