### ISSUE TITLE
graphviz

### ISSUE THREAD

**Issue by yahbluez** [splitbrain/dokuwiki#2715]
The graphviz plugin did not work with lokal install graphiz.

The bug is in this file:

/var/lib/dokuwiki/plugins/graphviz/img.php +9

This is the issue, with a PATH definded that way the require_once git wrong

if(!defined('DOKU_INC')) define('DOKU_INC',dirname(__FILE__).'/../../../');

I fixed it that way on my machine, but it would be better to with the PATH definition.

require_once('/usr/share/webapps/dokuwiki/inc/init.php');

wbr
fridolin

**Comment by phy25** [comment]
Hello, please report the issue to https://github.com/splitbrain/dokuwiki-plugin-graphviz/ , since this is not the repo for plugins. Thanks!
