### ISSUE TITLE
Suddenly, no more image shown

### ISSUE THREAD

**Issue by julian70400** [splitbrain/dokuwiki#2718]
Hello,

I was using normally Dokuwiki and now, I have no more image showed, by the way, the ckeditor seem to be broken.

I am using :  2018-04-22b "Greebo"
With these plugins :
ckgedit 
Dw2Pdf 
edittable plugin 
DokuWiki Upgrade Plugin
Wrap Plugin
And the other defaults plugins.

I am using url rewritting, it's worked until now.

I don't know from when it's like this beause I saw this problem while flush cache.. So I saw no more images. When I tryed to navigate in the ckeditor, when I clicked on "browse the server", it seem to be broken, like this : https://pasteboard.co/I4WRVHU.png

What's wrong ? I do not remember modify anything which should broke something.

Can you help me please ? Thanks.

**Comment by phy25** [comment]
Looks like more of a server issue. Could you please use Chrome's Web Developer tool to check what those network requests return?

**Comment by julian70400** [comment]
You're right ! It was w-frame option, I deactivate it from nginx and ckeditor is now working fine but... I still not have my images :(
It seem I had 2 differents problems.

Well, in the actual case, when I try to add a new image, it works, but I don't find my old images.. It seem that the default directory is not use correctly.

**Comment by julian70400** [comment]
I understand the problem. Since a plugin update (maybe..), my images are now reached in this directory : 

./lib/plugins/ckgedit/fckeditor/userfiles/image

But initially, everything is under 

./data/media

How do I fix this to have my media is the right directory ?

**Comment by splitbrain** [comment]
Sorry, there seems to be no bug in DokuWiki here so I am closing this issue. From your description it is unclear if you have problems in ckgedit only or if normal page views are affected too. In any case it is probably better discussed in the forum.
