### ISSUE TITLE
Problems with set_doku_pref

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#2721]
Our PHP method to set values to the preferences cookie has some problems regarding unsetting values:

* setting a cookie value to an empty string will completely break the entry, any further attempt to set the entry will start duplicating it
* deleting the last remaining entry is not possible

We should write some tests for this. I haven't looked into our JavaScript equivalents - they might have the same or similar troubles.

**Comment by phy25** [comment]
Tested manually in JavaScript, which looks good:

```javascript
// test_set_empty_string
DokuCookie.setValue('foo1', 'bar1');
DokuCookie.setValue('foo2', 'bar2');

DokuCookie.setValue('foo2', '');
console.log(DokuCookie.getValue('foo1')); // bar1
console.log(DokuCookie.getValue('foo2')); // 

DokuCookie.setValue('foo2', 'bar2');
console.log(DokuCookie.getValue('foo1')); // bar1
console.log(DokuCookie.getValue('foo2')); // bar2

// test_set_delete
DokuCookie.setValue('foo1', 'bar1');
DokuCookie.setValue('foo2', 'bar2');

DokuCookie.setValue('foo1', false);
console.log(DokuCookie.getValue('foo1')); // false
console.log(DokuCookie.getValue('foo2')); // bar2

DokuCookie.setValue('foo2', false);
console.log(DokuCookie.getValue('foo1')); // false
console.log(DokuCookie.getValue('foo2')); // false
```

I am creating a branch for the working fix.
