### ISSUE TITLE
feed.php bug

### ISSUE THREAD

**Issue by dryoo** [splitbrain/dokuwiki#2727]
In search mode, if someone put large query utf-8 string, Server process may suffer time out.

like this.

> http://dokuwiki.example/feed.php?mode=search&q=미네이랑의_비극_을_예견한_듯한_브라질의_독일전_패배가_묘사_되어_팬들이_감탄하기도_하였다._해당_에피소드는_월드컵_전에_방송되었거늘..._물론_준결승이_아니라_결승에서_진_것임이_다르긴_하다._1315_영국미네이랑의_비극_을_예견한_듯한_브라질의_독일전_패배가_묘사_되어_팬들이_감탄하기도_하였다._해당_에피소드는_월드컵_전에_방송되었거늘..._물론_준결승이_아니라_결승에서_진_것임이_다르긴_하다._1315_영국미네이랑의_비극_을_예견한_듯한_브라질의_독일전_패배가_묘사_되어_팬들이_감탄하기도_하였다._해당_에피소드는_월드컵_전에_방송되었거늘..._물론_준결승이_아니라_결승에서_진_것임이_다르긴_하다._1315_영국

**Comment by phy25** [comment]
I tested on my development DokuWiki (with a few pages only), and the speed looks normal. May we know the server environment and the number of pages you have in total?

**Comment by dryoo** [comment]
I currently disabled feed.
my server status is below.

Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40G
32 GiB System Memory (8GiB DIMM DDR3 Synchronous 1600 MHz x 4)
128GB Samsung SSD 840, 2TB WDC WD20EZRX-00D
Ubuntu 16.04.2 LTS, PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS ), Nginx, MariaDB
 
total pages : 10779 
total media : 13858

**Comment by phy25** [comment]
I see. Search in feed.php is a full text search. Do you experience slowness using the search on the webpage UI (it's also a full text search)?

http://dokuwiki.example/doku.php?do=search&q=미네이랑의_비극_을_예견한_듯한_브라질의_독일전_패배가_묘사_되어_팬들이_감탄하기도_하였다._해당_에피소드는_월드컵_전에_방송되었거늘..._물론_준결승이_아니라_결승에서_진_것임이_다르긴_하다._1315_영국미네이랑의_비극_을_예견한_듯한_브라질의_독일전_패배가_묘사_되어_팬들이_감탄하기도_하였다._해당_에피소드는_월드컵_전에_방송되었거늘..._물론_준결승이_아니라_결승에서_진_것임이_다르긴_하다._1315_영국미네이랑의_비극_을_예견한_듯한_브라질의_독일전_패배가_묘사_되어_팬들이_감탄하기도_하였다._해당_에피소드는_월드컵_전에_방송되었거늘..._물론_준결승이_아니라_결승에서_진_것임이_다르긴_하다._1315_영국

**Comment by dryoo** [comment]
Oh. I use currently google custom search. 

but I tested dokuwiki's own search engine. 
and
The answer is Yes.

then is this not a problem of feed.php?

**Comment by phy25** [comment]
OK, it's just that you have too many content in your wiki and the native search should take that much time. Also the search indexes may not work with Unicode string well.

You may want to disable search functions as well, besides your already disabled feed.

⭐️ Looks like search in `feed.php` does not respect `disableaction`=search; should we enhance this a bit?
