### ISSUE TITLE
Feature request : Page life time, and validator

### ISSUE THREAD

**Issue by BenoitPoulet** [splitbrain/dokuwiki#2728]
Hello,

We need to be compliant to some ISO norm. For this, we must do review of the documentation on a regular basis, correct them,  and a manager must validate the changes.

So it would be great to be able to do this in Dokuwiki, for some pages/name spaces

- Set a life time on pages, and have a way to show expired pages
- An editor can edit the page, but the new version of the page is on hold, until a manager validate this new version.

Regards.

**Comment by splitbrain** [comment]
This should be solved by a plugin. The watchcycle plugin might already do what you want.

**Comment by phy25** [comment]
Also you may want to have a look at publish plugin, which provides an approval process.

**Comment by BenoitPoulet** [comment]
Ok, thanks for all your advices.
