### ISSUE TITLE
Support for the URI scheme geo:

### ISSUE THREAD

**Issue by velldes** [splitbrain/dokuwiki#2729]
Please, add support for the URI scheme _geo:_.
For example [[geo>52.5148,13.3858?z=11]]. Currently this code will create link to google search `https://www.google.com/search?q=52.5148,13.3858?z=11&btnI=lucky`

Ideally would be nice to have aside links to google maps and openstreetmap with marker.
Finally, on page it should look like this:
geo:52.5148,13.3858?z=11 GM OSM

`<a id="geo_uri" href="geo:52.5148,13.3858?z=11">geo:52.5148,13.3858?z=11</a><a google map>GM</a> <a href="https://www.openstreetmap.org/?mlat=52.5148&mlon=13.3858&zoom=11#map=11/52.5148/13.3858">OSM</a>`

**Comment by phy25** [comment]
Please see https://www.dokuwiki.org/urlschemes and probably you can make it with Google maps link with a plugin
