### ISSUE TITLE
Weird flies/bugs on home page

### ISSUE THREAD

**Issue by slaymaker1907** [splitbrain/dokuwiki#2734]
It looks like someone probably put https://github.com/Auz/Bug on the home page for this project at https://www.dokuwiki.org/dokuwiki which is causing a bunch of gross flies to pop up all over the page.

**Comment by phy25** [comment]
https://www.freelists.org/post/dokuwiki/Has-dokuwikiorg-been-hacked-There-are-many-flies-running-across-the-screen,1
