### ISSUE TITLE
Dokuwiki on a stick - Pretty URL

### ISSUE THREAD

**Issue by onomori** [splitbrain/dokuwiki#2736]
Is useslash supposed to work on Dokuwiki on a stick? I've followed the instructions on the rewrite page but I'm getting 500 Internal Server Error.

**Comment by phy25** [comment]
Please try getting the error log.

Do you eam that you are using https://www.dokuwiki.org/install:dokuwiki_on_a_stick ?

**Comment by onomori** [comment]
Ah, the error log pointed me to the right direction, thanks. It was my fault in the end. Yes I was referring to that. I dumped the extracted folder in a folder somewhere in my drive to test it and I was getting a bunch of "RewriteEngine not allowed here" errors. Moved it to the root of the drive and it all started working.

Thanks for the tip and sorry for the trouble!
