### ISSUE TITLE
The definition of DOKU_UHC and DOKU_UHN produce JS Errors in Safari

### ISSUE THREAD

**Issue by gamma** [splitbrain/dokuwiki#2742]
see https://github.com/splitbrain/dokuwiki/blob/908724b22478083c95aa2ae6917df5c273cbe5ee/lib/exe/js.php#L103

The properties produce errors in Safari which lead to other JavaScript related problems on our website. Since there already is a fixme this should be resolved or removed (I just removed it from out code with no side effects yet)

**Comment by phy25** [comment]
I cannot see any Javascript error regarding this in Safari on dokuwiki.org and my own DokuWiki instance. Could you please post the specific error message?

**Comment by phy25** [comment]
I am closing this because of lack of information and there is nothing we can do at this point, but feel free to add more information and I can reopen the issue.
