### ISSUE TITLE
Failing tests on nightly PHP

### ISSUE THREAD

**Issue by phy25** [splitbrain/dokuwiki#2744]
See https://travis-ci.org/splitbrain/dokuwiki/jobs/517897743, for example.

> php: error while loading shared libraries: libonig.so.2: cannot open shared object file: No such file or directory

**Comment by phy25** [comment]
See discussion here (it's not resolved yet as of now, because they want to decide how to install `libonig2`): travis-ci/php-src-builder#31

**Comment by splitbrain** [comment]
Adding the package to our travis setup might be a good temporary fix.

**Comment by phy25** [comment]
Looks like they fixed `libonig` on Apr 11: https://github.com/travis-ci/php-src-builder/commit/efd74acf2b3a7a3b81d27b2c9d55ff77bec61773#diff-6fef59a74bf3bc29566e9742089f7636

Currently it is a lot noisier: https://travis-ci.org/splitbrain/dokuwiki/jobs/600157053

> PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /home/travis/build/splitbrain/dokuwiki/_test/core/phpQuery-onefile.php on line 2156

#2875 is related.

**Comment by phy25** [comment]
Closing. The only failing test in nightly is about `marcusschwarz/lesserphp` which exists on PHP 7.4 and will be fixed in #2927.

https://travis-ci.org/splitbrain/dokuwiki/jobs/639697554
