### ISSUE TITLE
User Management > Add Users form missing

### ISSUE THREAD

**Issue by lee5378** [splitbrain/dokuwiki#2745]
My "Add User" form is missing, but the overall user list is there. 

Any guidance would be much appreciated.

Thanks, 
David

**Comment by phy25** [comment]
What auth backend are you using? It might be that `$auth->canDo('addUser') == false`.

Also [forum](https://forum.dokuwiki.org/) is a better fit for this kind of questions :-)

**Comment by splitbrain** [comment]
no feedback given
