### ISSUE TITLE
Warning: A non-numeric value encountered in wiki/inc/common.php on line 1675

### ISSUE THREAD

**Issue by polygontwist** [splitbrain/dokuwiki#2756]
I have set to the current version (2018-04-22b "Greebo", download 14.4.2019) with PHP 7.2, the data taken from the old installation (data / pages, data / media) and get erroneous error message instead of images.

I have changed the line and it works again:
` $ret = substr($v, 0, -1);`
to
` $ret = intval(substr($v, 0, -1));`

```
function php_to_byte($v) {
    $l   = substr($v, -1);
    $ret = intval(substr($v, 0, -1));
    switch(strtoupper($l)) {
        /** @noinspection PhpMissingBreakStatementInspection */
        case 'P':
            $ret *= 1024;
        /** @noinspection PhpMissingBreakStatementInspection */
        case 'T':
            $ret *= 1024;
        /** @noinspection PhpMissingBreakStatementInspection */
        case 'G':
            $ret *= 1024;
        /** @noinspection PhpMissingBreakStatementInspection */
        case 'M':
            $ret *= 1024;
        /** @noinspection PhpMissingBreakStatementInspection */
        case 'K':
            $ret *= 1024;
            break;
        default;
            $ret *= 10;
            break;
    }
    return $ret;
}
```

**Comment by peterfromearth** [comment]
Should be already fixed with #2556

**Comment by polygontwist** [comment]
The function is still used in other places:
media.php
mediamanager.php

some pictures and pictures in the media manager were not displayed.

**Comment by Michaelsy** [comment]
@polygontwist Your provider is 1&1-IONOS?

**Comment by polygontwist** [comment]
yes

**Comment by Michaelsy** [comment]
Ok, @peterfromearth  is right. Here is detailed information how to fix it: https://forum.dokuwiki.org/post/64705. I prefer the php.ini-solution.

**Comment by polygontwist** [comment]
I have no problem with a memory limit. substr **returns a string**, and this is **multiplied** by a **number**. That's not good from syntax. That also says the error message.

**Comment by Michaelsy** [comment]
Did you try the patches?  You should.

**Comment by polygontwist** [comment]
I will not patch anything else if the problem is so obvious.  In my solution, the images are displayed against. Above all there 1&1 could override the next version. Respectively because I would have to think about it at the next installation.

**Comment by Michaelsy** [comment]
Ok, who doesn't want, doesn't want.

But so that others are not put on the wrong track, here is some background information:

DokuWiki definitely can not calculate images under these conditions:
- Version: Greebo
- memory-limit is set to "-1" (this is the case with 1&1)
- PHP 7.1 or higher

The root cause is that DokuWiki can not interpret the value of "-1" correctly.

As already stated, [here are the solutions](https://forum.dokuwiki.org/post/64705) that will eliminate the root cause (and not the aftereffects of this incompatibility).

BTW: I guess it would be a good idea to offer a corresponding hotfix. This problem is always in demand, again and again. 1&1 is one of the largest mass providers in Germany. There are now only the PHP versions offered, with which (in connection with Greebo) the malfunction occurs. That is, almost all DokuWiki users at 1&1 are affected.

HTH - Michael Sy.

**Comment by polygontwist** [comment]
Thanks for the background information. 

> The root cause is that DokuWiki can not interpret the value of "-1" correctly.

I wonder why you work with `strings` and then treat them as `numbers` - that's logically wrong, isn't it? Or is there an automatic conversion in php that turns string numbers into numbers? 

With the change in the function everything works. View upload - the images are displayed correctly. 

As you wrote, the next one will stumble over it, too. I think the small change in the function is also the better solution - everything else is too complicated.

**Comment by phy25** [comment]
You are welcome to provide a PR before others have time to investigate.

**Comment by Michaelsy** [comment]
The necessary pull requests (#2420 & #2556) have already been merged.
What we IMHO need is a hotfix. See my comments above.

**Comment by phy25** [comment]
https://github.com/splitbrain/dokuwiki/issues/2714#issuecomment-542240432

> hotfixes are usually only released for security bugs or severe issues. So this fix will have to wait for a release.

Closing since #2760 has been merged.

**Comment by Seppeltronics** [comment]
Hello @polygontwist,

what I did was just patching /inc/common.php as you mentioned and it seems to have fixed the problem.

However, I'm not sure about the files such as: media.php, mediamanager.php,...(not sure what is effected) and how to patch theme. Could you please tell me if and how the other files must be "fixed"?

Thank you very much, Best Regards,

Seppel

P.S. I also run my dokuwiki on 1&1 IONOS,... and I think a lot people got that problem. It would be rally awesome if you could write a small "How To", I think many people would enjoy it and be very thankful.

**Comment by polygontwist** [comment]
Hallo Seppel, 
ja nur in der einen Datei. Die beiden erwähnten Dateien benutzen nur die Funktion und crashen wenn da was ungültiges zurück kommt.
Ich weis aber nicht ob das in der aktuellen Version noch relevant ist.
