### ISSUE TITLE
Feature request: Show a plugin's version in extension manager

### ISSUE THREAD

**Issue by bttrx** [splitbrain/dokuwiki#2762]
Hi!
Before updating a plugin I'd like to check what version of a plugin my wiki currently runs.
As a workaround I'm now using a separate page with "~~INFO:syntaxplugins~~" etc.
Cheers,
Robert

**Comment by phy25** [comment]
![Detail of the plugin](https://user-images.githubusercontent.com/331403/56768671-fffeb900-677c-11e9-8944-27f427bb81c2.png)

Let us know if this is not what you want.

**Comment by bttrx** [comment]
I didn't notice the arrows before.
So this *is* what I want.
Thanks.
