### ISSUE TITLE
PNGs are freezing the browser and max an entire CPU core

### ISSUE THREAD

**Issue by a20eac1d** [splitbrain/dokuwiki#2764]
I have installed the latest version of DokuWiki and created an article. I've uploaded a picture and added it to the article. The picture shows correctly within the article. When I click on the picture, I get redirected to this page:

`http://wiki.domain.com/lib/exe/detail.php?id=welcome&media=2019_04_24_11_05_40_Webwood_Lurker_NPC_Classic_DB.png`

The page is supposed to show the picture in a bigger format and also some additional information related to the picture.

What happens instead is, the page loads about 5% of the picture and then freezes the browser tab. The browser keeps loading in an endless loop and soon reports that "one tab is freezing your browser". The CPU usage for that core jumps to almost maximum.

As far as I can tell, this only happens with certain PNG images. I have confirmed that the attached three images cause this issue 100% of the time. I hope attaching them here does not change them in any way.

How to reproduce: Create an article, attach one of the pictures and embed it with a link to the detail page, save the article and click on the picture.

![2019_04_24_11_03_58_Nightsaber_Stalker_NPC_Classic_DB](https://user-images.githubusercontent.com/29063569/56822997-019ab080-6853-11e9-9e46-2d9c1b79fc95.png)

**Comment by splitbrain** [comment]
Are you using libgd or ImageMagick? Does this happen in all browsers? Is
the 100% cpu on the server or the client side?

**Comment by a20eac1d** [comment]
No libgd (disabled) or ImageMagick (no path).
It happens in both Chrome (latest version) and Firefox (latest version).
It happens with browser plugins enabled and with plugins disabled (fresh browser).
The CPU usage happens only on the browser (client) side. Neither CPU nor RAM are being used on the server.

**Comment by a20eac1d** [comment]
I have confirmed that the image I attached in this topic also causes the problem. I right click -> saved the image, uploaded it to DokuWiki and it hangs the browser. Feel free to replicate.

**Comment by Michaelsy** [comment]
Related?: https://forum.dokuwiki.org/post/62842

**Comment by phy25** [comment]
I cannot reproduce this on my local DokuWiki (by opening the detail page, within Windows Chrome): http://localhost/dokuwiki/lib/exe/detail.php?id=0%3Astart&media=0:56822997-019ab080-6853-11e9-9e46-2d9c1b79fc95.png

Could you please try opening your wiki on a different computer, since it seems like more of a browser issue? Information on your client machine (OS, Memory, etc.) might be useful as well. Also could you please provide result of `?do=check` on your wiki?

BTW if anyone has upload permission on dokuwiki.org, we may create a sandbox page to test this.

> Related?: https://forum.dokuwiki.org/post/62842

@Michaelsy Nope. This issue is about client-side browser CPU issue.

**Comment by a20eac1d** [comment]
Wow I feel like an idiot right now.

I don't know how or why, but the template "STM" caused the issue. I was about to run the ?do=check but decided to switch back to the default template before doing that. The problem no longer occurs.

https://www.dokuwiki.org/template:stm

Does anybody have a clue why a template could cause this?

Maybe the template should be removed from the official website or marked as broken?

**Comment by phy25** [comment]
Interesting. I can reproduce this with template:sim now. An issue can be opened here: https://github.com/Fraina/STM-Dokuwiki-Template/issues
