### ISSUE TITLE
Chinese character not url decode in pages

### ISSUE THREAD

**Issue by JackKuo-tw** [splitbrain/dokuwiki#2765]
Hi, I'm a Traditional Chinese user from Taiwan.
If my page title is Chinese, e.g., "2018選課爭議", then it will be url-encode to "2018%E9%81%B8%E8%AA%B2%E7%88%AD%E8%AD%B0.txt", not the expected name "2018選課爭議.txt"
Apparently, it didn't do url-decode before named the file.
Here is an example:
<img width="1111" alt="圖片" src="https://user-images.githubusercontent.com/21074047/56850153-1b122a00-6931-11e9-9aa2-d85edd9a93bc.png">

I'm using Ubuntu 18.04.2 LTS with Nginx and PHP 7.2.17

**Comment by phy25** [comment]
Please see https://www.dokuwiki.org/config:fnencode. Does that help?

**Comment by JackKuo-tw** [comment]
Solved. Thank you. 😄
