### ISSUE TITLE
about dokuwiki toc

### ISSUE THREAD

**Issue by venano** [splitbrain/dokuwiki#2773]
When I use DokuWiki ，the toc makes me fill uncomfortable ，when I browse the page, the TOC can always appear on the right side of my page as I browse. I think it shouldn`t just appear at the top of the article. What should I do? thanks！

**Comment by splitbrain** [comment]
There's the ``~~NOTOC~~`` macro and the various configurations for the TOC. But really you should ask questions like this in the forum, not the bug tracker.
