### ISSUE TITLE
"Permission Denied" when specific content saved on page

### ISSUE THREAD

**Issue by wg4568** [splitbrain/dokuwiki#2781]
DokuWiki Release 2018-04-22b "Greebo" gives:

```
Forbidden
You don't have permission to access /doku.php on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```

When saving the following content to a page: `sleep(a`

Some things to note, `a` can be substituted with any character to reproduce the issue. Also, the specific keyword `sleep` is important, using other words in its place does not cause the issue.

**Comment by phy25** [comment]
What server/provider are you using? Looks like a code execution prevention on your server rather than DokuWiki: https://www.dokuwiki.org/faq:mod_security

**Comment by wg4568** [comment]
I did some digging around with my host, you were right-- it was a ModSecurity rule blocking the request. Thank you!

Note, for those using Namecheap, they don't have a ModSecurity section on their cpanel. They require you to contact customer support and to change the rules (in case anyone is in a similar situation).
