### ISSUE TITLE
JavaScript with defer and async

### ISSUE THREAD

**Issue by Dr-Yukon** [splitbrain/dokuwiki#2782]
I think that the /lib/exe/js.php script should be set with the **defer** attribute, and the jQuery library should be separate and **async**

**Comment by Dr-Yukon** [comment]
JavaScript is a blocking resource for the parser. This means that JavaScript blocks parsing of the HTML document itself. When the parser comes to the <script> tag (it doesn't matter if it is internal or external), it stops, takes the file (if it is external) and starts it.
Workline https://hsto.org/files/fc6/581/de4/fc6581de40d249e5905cf3fa238286eb.png

**Comment by Dr-Yukon** [comment]
Fortunately, the <script> element has two **async** and **defer** attributes that give us the ability to control how external files are loaded and executed. Asynchronous and deferred execution is most important when the <script> element is not at the very end of the document (**_which requires dividing the tpl_metaheaders() function into two parts_**). HTML documents are parsed in order, from opening <html> to closing it. If an external JavaScript file is placed immediately before the closing </ body> tag, then using async and defer becomes less relevant, since by that time the parser will already parse most of the document and the JavaScript files will no longer affect it.

**Comment by Dr-Yukon** [comment]
_Is the script self-contained?_ For scripts that are independent of other files and/or have no dependencies, the **async** attribute will be most useful. Since it does not matter to us when the file is executed, asynchronous loading is the most suitable option.
Workline https://hsto.org/files/a07/823/bae/a07823bae90b4612bc5e4933674b34ce.png

**Comment by Dr-Yukon** [comment]
_Does the script relies on a fully disassembled DOM?_ In many cases, the script file contains functions that interact with the DOM. Or perhaps there is a dependency on another file on the page. In such cases, the DOM must be completely parsed before the script is executed. As a rule, such a file is placed at the bottom of the page to make sure that everything has been disassembled for its operation. However, in a situation where, for whatever reason, the file must be placed elsewhere, the **defer** attribute may be useful.
Workline https://hsto.org/files/378/af7/eff/378af7eff5e34d89b75584d626c48cae.png

**Comment by Dr-Yukon** [comment]
At last, browser supporting
https://hsto.org/files/d33/64e/d8f/d3364ed8f1d34517b4d12d44f9eea73b.png
https://hsto.org/files/d33/64e/d8f/d3364ed8f1d34517b4d12d44f9eea73b.png

**Comment by phy25** [comment]
This might be a breaking change if some other plugins does not use either the JS hook or `jQuery.ready()` correctly. In the meantime, looks good to me.

**Comment by Dr-Yukon** [comment]
> This might be a breaking change if some other plugins do not use either the JS hook or `jQuery.ready()` correctly. In the meantime, looks good to me.
That's why Jquery library must be started early (= async), not later (= defer)

**Comment by Dr-Yukon** [comment]
>> https://github.com/splitbrain/dokuwiki/pull/2786/files
