### ISSUE TITLE
bootswrapper plugin not installed properly on dokuwiki

### ISSUE THREAD

**Issue by VaniArshi** [splitbrain/dokuwiki#2785]
i get below 3 warnings, after installing bootswrapper plugin. I have also installed bootstrap3 plugin and currently using it.
Warning: array_keys() expects parameter 1 to be array, null given in D:\Xampp\htdocs\dokuwiki\lib\plugins\bootswrapper\exe\popup.php on line 165

Warning: Invalid argument supplied for foreach() in D:\Xampp\htdocs\dokuwiki\lib\plugins\bootswrapper\exe\popup.php on line 165

Warning: Invalid argument supplied for foreach() in D:\Xampp\htdocs\dokuwiki\lib\plugins\bootswrapper\exe\popup.php on line 176

**Comment by phy25** [comment]
Duplicate of LotarProject/dokuwiki-plugin-bootswrapper#97.
