### ISSUE TITLE
[Farmer plugin]Cannot use uppercase in naming animal

### ISSUE THREAD

**Issue by Jigglypuff222** [splitbrain/dokuwiki#2799]
Hello.
In Farmer plugin, I found, when creating new animal and naming it, uppercase cannot be used.
If you use uppercase naming new animal, the control panel of "Farming" says it succeeded creating the new animal, the name be added to the list, but, in fact, the page of it is not existing and when you try to get access to the URL of the new animal, you will be forced to jump to your Farmer page or bump into error messages.

For example, if you try to create new animal named "Test" , control panel says,
"The Animal "baka" has been successfully created"
But, as it includes the uppercase "T", the page itself fails to be created.

**Comment by phy25** [comment]
You may want to create the issue here: https://github.com/cosmocode/dokuwiki-plugin-farmer

I don't have the permission to transfer this issue to there :-)

**Comment by splitbrain** [comment]
See cosmocode/dokuwiki-plugin-farmer#49
