### ISSUE TITLE
Redirect no working properly after login with modified basedir and Nginx reverse proxy

### ISSUE THREAD

**Issue by Zosoworld** [splitbrain/dokuwiki#2806]
I have setup Dokuwiki in an LXC Container, and I am using an nginx reverse proxy to redirect [nginx_lxc]/dokuwiki/ to [dokuwiki_lxc]/.
The configuration for the redirect is:
```
location /dokuwiki/ {
    proxy_pass http://dokuwiki_ip/;
}
```
and I have set the basedir config to /dokuwiki/.
Everything works smoothly aside from the fact that when I login, I get redirected to 
`[nginx_ip]/dokuwiki/dokuwiki/doku.php`, so the url is not found. If I delete one of both "dokuwiki", everything works as it should, and I am able to navigate the wiki without problems. 

I thought about using one of the plugins that allow for redirection to a custom page after login, but I think this should be fixed to properly include the basedir in the redirect after login.

I am running Release 2018-04-22b "Greebo".

Thank you very much.

**Comment by phy25** [comment]
I looked at the code and this is unlikely to happen. It will never detect one if `basedir` and `baseurl` exists (and during detection `baseurl` which is used to generate absolute URL will never generate any extra folder in path). Could you please:

1. Check value of `$conf['baseurl']`
2. Check if feed's absolute URL is correct by visiting `feed.php`
3. Use Network tab in Web Developer console (with "preserve log" on) to see where the URL is wrong

**Comment by Zosoworld** [comment]
> I looked at the code and this is unlikely to happen. It will never detect one if `basedir` and `baseurl` exists (and during detection `baseurl` which is used to generate absolute URL will never generate any extra folder in path). Could you please:
> 
>     1. Check value of `$conf['baseurl']`
In local.php:
```php
conf['basedir'] = '/dokuwiki/';
```
>     2. Check if feed's absolute URL is correct by visiting `feed.php`
I'm unsure about what you mean, but all URLs are prepended by: http://192.168.x.xx/dokuwiki/
>     3. Use Network tab in Web Developer console (with "preserve log" on) to see where the URL is wrong
First it does a POST to `http://192.168.x.xx/dokuwiki/doku.php?id=start&amp;do=login`, which is responded by a 302.
Then, it does a GET to `http://192.168.x.xx/dokuwiki/dokuwiki/doku.php?id=start`, which returns a 404.

**Comment by phy25** [comment]
Interesting. In this case you need to debug this on your own to see who outputs that path. To start with, go to `inc/Action/Redirect.php` and replace `send_redirect` with `echo`?

**Comment by splitbrain** [comment]
`base_url` and `base_dir` are two separate settings - please tell us the contents of both.

**Comment by Zosoworld** [comment]
This is the output:
`http://[dokuwiki_lxc_ip]/dokuwiki/doku.php?id=start`

After it redirects to this URL, Nginx substitutes `http://[dokuwiki_lxc_ip]` with `http://[dokuwiki_lxc_ip]/dokuwiki/` and then appends `/dokuwiki/doku.php?id=start`, probably.

> `base_url` and `base_dir` are two separate settings - please tell us the contents of both.
base_url is not set in `local.php`

**Comment by phy25** [comment]
I believe the problem lies in your NGINX config rewriting the link, since DokuWiki outputs the expected URL.

See http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect that may help.

**Comment by Zosoworld** [comment]
For future reference, I fixed this by adding 
```
proxy_set_header Host $http_host;
```
to the NGINX config. 

Thank you all for the discussion.
Best regards.
