### ISSUE TITLE
node mapper plugin

### ISSUE THREAD

**Issue by 808y808** [splitbrain/dokuwiki#2807]
hello
i never coded a plugin and i'm no real coder but i would like to use the node mapper jquery plugin inside dokuwiki for a project.
the idea is to analyse links inside a page or tags and propose a visual map of the wiki..
the page content or part of it could be the 'description' field available in the map.
after some research, nodemapper seems to be the most convenient and easily adaptable for this
i got no idea on how to produce and manage the json files inside dokuwiki
any advice from anyone here ?

best
bobybob

**Comment by 808y808** [comment]
i forgot the link, here it is: http://poderomedia.github.io/nodemapper/docs/

**Comment by splitbrain** [comment]
best discuss this on the forum. https://www.dokuwiki.org/tips:grapher might give you some ideas on how to implement it
