### ISSUE TITLE
less @import won't work in a farm animal

### ISSUE THREAD

**Issue by garu57** [splitbrain/dokuwiki#2808]
Dokuwiki Greebo
windows 10 and 7

I have a number of css changes that i'd like to keep in separate files, but putting these files into `conf` dir of a farmer:
```
/* userstyle.less */
@import "./underlinehx.less";
```
```
/* underlinehx.less */
 h1:after, h2:after {
    content: "";
    display: block;
    border-bottom: 1px solid #cccccc;
    overflow: hidden;
}
```
the content of `underlinehx.less` is correctly embedded into the css sent to the browser.

If the same files are put into the `conf` dir of a virtual host farm animal the second `less` file is not embedded and here is what I find into the css sent to browser
```
 @import "/home/web/httpd/dokuwiki/farm/sandbox-wiki-devel/conf/./underlinehx.less";
```
that obviously has no meaning for the browser.

**Comment by phy25** [comment]
This should be sent to https://github.com/cosmocode/dokuwiki-plugin-farmer/ (unfortunately I cannot help you transfer the issue)

**Comment by garu57** [comment]
Transferred as requested, thanks.

Closing this.
