### ISSUE TITLE
dokuwiki included in CheckMK: "User Management" link is not shown

### ISSUE THREAD

**Issue by J-Damian** [splitbrain/dokuwiki#2812]
Hi

I'm trying to create local users in a dokuwiki included in **CheckMK** (release 1.4.0p22).

The **usermanager** plugin is installed but I cannot create users because the "User Management" is not displayed.

How can I make appear the "User Management" in the "Admin" screen?
Is there any other way to create local users?

Thanks in advance

**Comment by mprins** [comment]
perhaps CheckMK uses a different user management? you should ask them.

**Comment by J-Damian** [comment]
> 
> 
> perhaps CheckMK uses a different user management? you should ask them.

As I did not find info/documentation about Dokuwiki in [CheckMK site](https://checkmk.com/cms.html), I post a question [here](https://lists.mathias-kettner.de/pipermail/checkmk-en/2019-July/028259.html)... No luck.

**Comment by phy25** [comment]
May we know what auth backend you are using? It might be the backend that prevents you from using the user manager.

In the meantime, here's something that you may find useful:
https://git.onesystems.ch/monitoring/check_mk/tree/master/omd/packages/dokuwiki

**Comment by splitbrain** [comment]
I'd guess it's this backend: https://git.onesystems.ch/monitoring/check_mk/blob/master/omd/packages/dokuwiki/authmultisite/auth.php

And yes, that has no capabilities that would be required for the user manager.
