### ISSUE TITLE
A way to bypass the ban

### ISSUE THREAD

**Issue by cgoxopx** [splitbrain/dokuwiki#2828]
![img](https://raw.githubusercontent.com/cgoxopx/cgoxopx.github.io/master/img/2019-08-02%2020-16-11%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by cgoxopx** [comment]
Modify X-Forwarded-For and then you can bypass the ban

**Comment by phy25** [comment]
How do you ban these IP since I don't think DokuWiki has internal blocker by IP addresses?

However, will take a look at how DokuWiki processes IP forwarded header.

**Comment by phy25** [comment]
Introduced by #799.

I agree that modern application should have some control about this behavior. Usually this IP address information should be controlled by the web server (and thus it's not the PHP application's duty to filter the data), but:

- WordPress doesn't support `X-Forwarded-For` header by default (they change it by [modifying wp-config.php](https://gist.github.com/ryanjbonnell/9509696)).
- GitLab has some control with `trusted_proxies` in the config. They also document NGINX's `real_ip_trusted_addresses` in their ommibus package.
- [Sympony has `Request::setTrustedProxies`](https://symfony.com/blog/fixing-the-trusted-proxies-configuration-for-symfony-3-3).

I would recommend that we introduce config similar to `trusted_proxies` in Sympony (and GitLab).

**Comment by splitbrain** [comment]
trusted proxies seem sensible

**Comment by phy25** [comment]
@cgoxopx Sorry, but why are you closing the issue?
