### ISSUE TITLE
Table url udp

### ISSUE THREAD

**Issue by arfong** [splitbrain/dokuwiki#2831]
Hi,

I'm having an issue with table.
It's completely messy with this : 

^ Tracker ^
| openbittorrent.com |
| udp://tracker.torrent.eu.org:451 |
| udp://tracker.pirateparty.gr:6969/announce |

![image](https://user-images.githubusercontent.com/53687840/62421804-f3f19400-b6a7-11e9-8827-b47e02ca543e.png)

It's correct that way :-
^ Tracker ^
| openbittorrent.com |
| %%udp://tracker.torrent.eu.org:451%% |
| %%udp://tracker.pirateparty.gr:6969/announce%% |

![image](https://user-images.githubusercontent.com/53687840/62421819-2d2a0400-b6a8-11e9-9d0f-e4f1e11b3bb4.png)

**Comment by phy25** [comment]
`//` is for italic style. I am not sure if https://www.dokuwiki.org/urlschemes helps.

**Comment by phy25** [comment]
> To allow any other protocol you will need to add the protocol to your `conf/scheme.local.conf` (create it when non-existing).
