### ISSUE TITLE
Error in formatting with 3x'

### ISSUE THREAD

**Issue by LMS235** [splitbrain/dokuwiki#2834]
The display for a text with ' is not correct in the '' block.

![image](https://user-images.githubusercontent.com/8693550/62519778-8e7ae000-b82c-11e9-8f6d-d45a6e5ac8f4.png)

--> becomes -->

![image](https://user-images.githubusercontent.com/8693550/62519817-a05c8300-b82c-11e9-9bee-65a7b033e9de.png)

the last ' is no longer in the code formatting. Here we have 3x' because the code itself already contains a ' and with the end of '' it becomes 3. Here the last one is not recognized correctly anymore.

Is now only the question whether it comes from the Dokuwiki core or from the UnformattedCode Plugin

**Comment by splitbrain** [comment]
`''` is not a code block. It's monospaced text and it ends at the next occurance of `''`. If you want to avoid parsing use the appropriate syntax. Eg. `''%%zypper se -si 'kernel'%%''` or use an actual `<code>` block.
