### ISSUE TITLE
Action unknown: menuitem : failed to rename page on mobile view

### ISSUE THREAD

**Issue by bansan85** [splitbrain/dokuwiki#2837]
With Dokuwiki 2018-04-22b "Greebo", when I try to rename a page in mobile view, I have an error "Action unknown: menuitem".
I have to enable "computer view" on my device to be able to rename my page.

**Comment by phy25** [comment]
Page rename is powered by [plugin:move](https://github.com/michitux/dokuwiki-plugin-move/), not the core.

**Comment by bansan85** [comment]
Oh, right. I forget it was a plugin.

It was already reported in https://github.com/michitux/dokuwiki-plugin-move/issues/150

Thanks,
