### ISSUE TITLE
Broken Tests on Travis CI due to PHPUnit and MySQL

### ISSUE THREAD

**Issue by phy25** [splitbrain/dokuwiki#2841]
Looks like recently Travis CI [switched the default Linux distribution from Ubuntu Trusty 14.04 LTS to Ubuntu Xenial 16.04](https://docs.travis-ci.com/user/trusty-to-xenial-migration-guide), which fails all our tests.

Two concerns:
- [x] Default PHPUnit installed in the environments of older PHP releases are totally incorrect (Someone did address it in Travis CI's forum but did not get attention from the developers yet: https://travis-ci.community/t/the-preinstalled-version-of-phpunit-is-incompatible-with-php/3704)
- [x] Database services are not enabled by default, and may be a new version, which causes new incompatibilities

This is preventing our master branch from testing correctly. I may submit a temporary patch to downgrade the environment on Travis CI first and fix the tests on Xenial later, but I believe concern 1 really needs to be fixed on Travis CI's end.

**Comment by phy25** [comment]
Just found that 457a5f785edda4d7fae283c0df34b9d607a0a301a already addressed my concern 1, but I will keep it unchecked because:

> We should replace this with a composer dev dependency some time.

I agree, but not sure if constraints between PHPUnit support regarding PHP and DokuWiki support regarding PHPUnit resolve correctly.

**Comment by splitbrain** [comment]
I fixed both these things this morning. But one mysql test is still failing - probably some behaviour changed with a newer mysql version

**Comment by phy25** [comment]
@splitbrain Could you try downgrading Travis CI's OS, just for testing? I believe they changed a lot of internals between OS environment. (I may be available several hours later)

**Comment by splitbrain** [comment]
I currently can't do anything. I'm travelling and this hotel's WiFi is blocking SSH :angry:

**Comment by phy25** [comment]
https://travis-ci.org/splitbrain/dokuwiki/builds/572935990

Only `nightly` is complaining now under trusty (as #2693 mentioned we simply cannot use PHPUnit 8 for now). At least we know it's not about PHP.

Will play around Travis's new Xenial later.

**Comment by splitbrain** [comment]
I was able to reproduce the MySQL error on my local machine. It's very weird. The test breaks for testing the mybb test data on inserting a new user with (simplified):

```
SET @salt = LEFT(UUID(), 10);
INSERT INTO mybb_users
(username, email, salt, password, regdate)
VALUES ('foobaruser', 'u@e.com', MD5(CONCAT(MD5(@salt), MD5('clear'))), 'pass', UNIX_TIMESTAMP());
```

When I try this directly in the mysql commandline (on mariadb on my archsystem), I get an error:

```Field 'buddylist' doesn't have a default value```

This is weird for two reasons:

* why is this not throwing an exception in our code when executing the sql (auth.php line 685)? This only fails later when we try to retrieve the user.
* why did this work on older MySQL instances?

The immeadiate fix is to supply all the missing values in the insert statement (buddylist is not the only one). But getting proper exceptions would be more important.

**Comment by phy25** [comment]
> why is this not throwing an exception in our code when executing the sql (auth.php line 685)? This only fails later when we try to retrieve the user.

This specific mybb testcase reveals a bug in authpdo: its insert-sql has multiple queries, which probably requires `PDOStatement::nextRowset`. I added this logic locally which seems to work, but more tests are required - looks like we need to ignore or check multirow support or sqlite will complain.

Also the SQL error I got is "Field 'signature' doesn't have a default value".

https://github.com/splitbrain/dokuwiki/blob/67d5efaa1083c6734ddb4ac18f9e9ff8ffaafe93/lib/plugins/authpdo/auth.php#L686-L690

Reference: https://stackoverflow.com/questions/23247553/how-can-i-get-an-error-when-running-multiple-queries-with-pdo

> why did this work on older MySQL instances?

https://dev.mysql.com/doc/refman/5.7/en/upgrading-from-previous-series.html

> In MySQL 5.7.5, these SQL mode changes were made: ... Strict SQL mode for transactional storage engines (`STRICT_TRANS_TABLES`) is now enabled by default.

See also https://dev.mysql.com/doc/refman/5.7/en/data-type-defaults.html

> For data entry into a NOT NULL column that has no explicit DEFAULT clause, if an INSERT or REPLACE statement includes no value for the column, or an UPDATE statement sets the column to NULL, MySQL handles the column according to the SQL mode in effect at the time:
>
> If strict SQL mode is enabled, an error occurs for transactional tables and the statement is rolled back. For nontransactional tables, an error occurs, but if this happens for the second or subsequent row of a multiple-row statement, the preceding rows will have been inserted.
