### ISSUE TITLE
stable branch not updated since 2017-02-19e

### ISSUE THREAD

**Issue by Zugschlus** [splitbrain/dokuwiki#2842]
Hi,

various documentation on the net suggests cloning the stable branch of thie github project to "install from git". However, this branch hasn't been updated for two and a half years while the project has been active.

Please consider updating your stable branch or even possibly offering a branch containing the stable+hotfixes state of the project as this is the one that one would want to run.

If you intend to discontinue the stable branch and discourage installing from git, you should take measures to that people cloning the stable branch as given in the docs at least get some error message.

Greetings
Marc

**Comment by splitbrain** [comment]
can't reproduce. the stable branch is up to date with the last hotfix release.

**Comment by Zugschlus** [comment]
confirmed. stupidity on the issue reporters side. I apologize.
