### ISSUE TITLE
Feature-Request: Mailvelope-API-Support for encrypted wiki

### ISSUE THREAD

**Issue by user9209** [splitbrain/dokuwiki#2846]
To encrypt the wiki there would be nice to support the mailvelope api.

Some kind of client side encryption would be nice, so I think mailvelope is an easy way.

**Comment by phy25** [comment]
Though the idea sounds cool, could you please elaborate a bit about how the integration should work? Is it just encrypting the content of the wiki page? If it's the case, I believe a third-party plugin should be enough.

Also I cannot easily find any documentation about their API.

**Comment by user9209** [comment]
I also had no look to find any good info on their API :-(

Can you give me a hit, which type of plugin runs after editing a page and storing it to the disk.
I think that will be no client side encryption any more, as the plugin runs at the server.
The plugin must provide a javascript encryption on client side.

So it would be nice to use the mailvelope api doing it for us.

**Comment by user9209** [comment]
Documentation: https://mailvelope.github.io/mailvelope/

**Comment by phy25** [comment]
> The Mailvelope extension injects a script into the page to make its client-api accessible.

The problem with such things is that I don’t want to favor specific services or products over other ones and thus stick to the standards and service-independent solutions. Therefore, I will go ahead and close the issue.

However, anyone interested in this can create a plugin.

https://www.dokuwiki.org/devel:event:common_wikipage_save
https://www.dokuwiki.org/devel:event:io_wikipage_write
https://www.dokuwiki.org/devel:event:io_wikipage_read
https://www.dokuwiki.org/devel:javascript
