### ISSUE TITLE
getgooglequery does not work correctly with Google Forms links

### ISSUE THREAD

**Issue by jakubklimek** [splitbrain/dokuwiki#2848]
### Description

When I access a dokuwiki page on some dokuwikis and the HTTP request has `referer` HTTP header set to, e.g. `referer: https://www.google.com/url?q=https://opendata.gov.cz/edu:konference:2019&sa=D&ust=1567692046621000&usg=AFQjCNG_0v_FF28O_RTQNJ0RZqqp49fGig` - this is what Google Forms does when a link to https://opendata.gov.cz/edu:konference:2019 is used - the page has words from the `https://opendata.gov.cz/edu:konference:2019` URL marked as search results, even though I did no search.

Apparently (https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/438#issuecomment-528441921) this is a Dokuwiki `getgooglequery` [functionality](https://xref.dokuwiki.org/reference/dokuwiki/nav.html?inc/common.php.source.html#l1462) for highlighting search results from search engines, which, however, does not work correctly when placing a link into a Google Form.

### Steps to reproduce

1. See [this](https://www.google.com/url?q=https://opendata.gov.cz/edu:konference:2019&sa=D&ust=1567692046621000&usg=AFQjCNG_0v_FF28O_RTQNJ0RZqqp49fGig) example, or this one: `curl https://wiki.bash-hackers.org/ -H 'referer: https://www.google.com/url?q=https://opendata.wiki.gov.cz/edu:konference:2019&sa=D&ust=1567692046621000&usg=AFQjCNG_0v_FF28O_RTQNJ0RZqqp49fGig' | grep mark`

**Expected behavior:** [What you expected to happen]
No search results marked with `<span class="mark">`

**Actual behavior:** [What actually happened]

Words from the `referer` header marked as `<span class="mark">`
### Versions

[DokuWiki] Release 2018-04-22b "Greebo"

### Screenshots or Logs

[Paste your logs or attach the screenshot]
![image](https://user-images.githubusercontent.com/718827/64346515-8ca26900-cff2-11e9-8b5c-399ef5f5f449.png)

**Comment by phy25** [comment]
This one is interesting. I don't think we can get user query from referrer anymore from Google, if users are being redirected from the Google `/url` endpoint.

One example: https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.dokuwiki.org/&ved=2a-long-string-that-may-include-my-search-info

Maybe we should ignore it if it's from `google.com/url`? I am not that familiar with how Google's recent referrer works, so we need more input.

**Comment by phy25** [comment]
We can:

1. Remove Google (since they never include query in url)
2. or drop the query if query is a URL (we can just check if `//` is included)

I decided to implement 2.
