### ISSUE TITLE
avoid point at end of generated password ;)

### ISSUE THREAD

**Issue by vinsse2001** [splitbrain/dokuwiki#2851]
It is not really a bug, but a trap for users !!
When an account is created, and password generated, the last char of the password is often point or comma. 
But users think that is not part of the password...
Can you change it, to be more clear ?
Thank you !
Vincent

**Comment by phy25** [comment]
https://github.com/splitbrain/dokuwiki/blob/8902b37d8e5bd11eeb34c7cc6879533fd1a8702c/inc/auth.php#L786

I would make it `!@#$%^&` to make sure they are not among those "hard to speak ones" (quite arbitrary choices though). Needs more feedback about this.

Reference:
- https://www.roboform.com/password-generator: `!@#$%^&`
- https://www.lastpass.com/password-generator: `!@#$%^&*`

**Comment by vinsse2001** [comment]
you need more feedbacks from me ?

Le mar. 10 sept. 2019 à 19:36, Henry Pan <notifications@github.com> a
écrit :

**Comment by phy25** [comment]
@vinsse2001 Mostly others. Your are welcome as well 😄

**Comment by splitbrain** [comment]
I would keep the list of special chars as is but move the special char between the words and the number. So we `foobar.20` instead of `foobar20.`
