### ISSUE TITLE
Add Support for rel="ugc"

### ISSUE THREAD

**Issue by StarArmy** [splitbrain/dokuwiki#2852]
This is a feature request to add support for adding "ugc" and "ugc nofollow" as an alternative to rel="nofollow" in external links in page content. The option would be a dropdown available in the ACP to replace the current checkbox to add nofollow to links.

The usage of UGC hints for search indexing is described here on the Google blog: https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html

**Comment by splitbrain** [comment]
I don't think we would need a change in the config option. We could simply always set "nofollow ugc" when the current option is enabled.

**Comment by StarArmy** [comment]
That update sounds OK and very easy to implement, but it would also make it impossible to add (only) rel="ugc" to links without having to manually edit the code. A dropdown would be better. For example, on my own wiki I would like to transitionally use both ugc and nofollow but eventually use ugc only.

**Comment by phy25** [comment]
Change from checkbox to dropdown requires old config migration which requires more code. Maybe we could do the transition on our core end while keeping the checkbox, i.e. remove `nofollow` when support for `ugc` is complete (which I believe will happen at least several years later).

**Comment by phy25** [comment]
Merged #2855. Thanks for your contributions!
