### ISSUE TITLE
Related Changes (filters recent changes based on current article)

### ISSUE THREAD

**Issue by StarArmy** [splitbrain/dokuwiki#2853]
Feature Request

I was looking at Wikipedia today and I happened to notice that the old "recent changes" there on the sidebar was replaced with "related changes" which has a functionality of being like recent changes, but only showing changes on pages that are linked TO or linked FROM the currently loaded wiki page. This seems like it would be extremely useful to add to Dokuwiki (not to replace recent changes, but as an additional option). For example, if I'm on the Star Army's sci-fi worldbuilding Dokuwiki looking at a page for a solar system, this would show me all the changes to the pages for planets, cities, and locations in that Solar System because they'd be linked from (or linked to) the solar system's page.

I am requesting that we consider adding this related changes feature to a future Dokuwiki release.

**Comment by phy25** [comment]
Sounds like a great plugin idea! I remember we have existing code to check backlinks.

**Comment by phy25** [comment]
Closing because this can and should be implemented as a plugin :-).
