### ISSUE TITLE
Role names in farmer plugin...

### ISSUE THREAD

**Issue by MatthijsBerlicum** [splitbrain/dokuwiki#2861]
The farmer plugin works fine, only positive feedback from my side.

However, I believe that role names could be improved. Why use terms like "farmer" and "animal"? I am not a small kid, and neither are you (I think).

My suggestion is to rename the roles, e.g.
1. Farmer = a system administrator
2. Animal = a managed website

By improving the terminology the plugin documentation becomes more clear for technical people. E.g. when defining virtual hosts it makes more sense to direct to the system administrator's directory than directing to a farmer's directory.

I am glad to translate the plugin documentation into Dutch, but I don't like to write about farmers and animals. The analogy doesn't make sense. A farmer doesn't provide tools (templates/plugins) to animals.

**Comment by splitbrain** [comment]
won't fix. The farm terminology is well established in the wiki community. Feel free to improve the documentation if you think the terminology is not clear to newcomers.

**Comment by MatthijsBerlicum** [comment]
Hi Andreas,

The term "farm" is fine, of course. "Farm" is used for server farms, wiki
farms, etc.The term "farmer" is used less frequently, but is also fine.

However, the term "animal" is really awkward. That is not common practice
in the IT-world nor in the Wiki world. When you would use Google to search
for "wiki" combined with "animal", you won't find relevant hits. At least,
I did not.

Nevertheless, I really like you Farmer plugin and admire all your DokuWiki
work..

Kind regards,
Matthijs

Op wo 18 sep. 2019 om 15:48 schreef Andreas Gohr <notifications@github.com>:
