### ISSUE TITLE
extension manager can't download from sourceforge

### ISSUE THREAD

**Issue by schplurtz** [splitbrain/dokuwiki#2863]

**Comment by phy25** [comment]
Duplicate of #2410. It's in master but not in stable probably?

**Comment by LarsGit223** [comment]
#2417 fixed it and was merged on 8th of January. So it is not yet released.

**Comment by schplurtz** [comment]
Sorry for :  
  * not putting correct description. It regularly happens to me and I don't know how to fix that...
  * not searching enough in open issues

Thanks to both of you
