### ISSUE TITLE
Upload a file question

### ISSUE THREAD

**Issue by junozhou** [splitbrain/dokuwiki#2873]
![image](https://user-images.githubusercontent.com/18303569/65852206-04f91180-e388-11e9-9a2c-fe5dc6960dd2.png)
As shown in figure。
There are two copywriting tips that are not clear
1、this file upload failed。as the tips i can not know the question。I did the test， If delete “梅” or “琛”, upload success
2、it is said that “Upload max. 8 MB per file.” but i upload 53MB per file

**Comment by phy25** [comment]
What's your server version (OS/Apache/PHP)? Can you replace your “梅” or “琛” with another Chinese character because I guess it's just too long?

**Comment by phy25** [comment]
Closing because of no response. I highly suspect this is a web server related issue.
