### ISSUE TITLE
Authorisation Error

### ISSUE THREAD

**Issue by artemtugin** [splitbrain/dokuwiki#2876]
Hi, I found such a problem if the password contains an exclamation point (!), Registration is successful, but authorization does not work.

**Comment by splitbrain** [comment]
what's your authbackend?

**Comment by artemtugin** [comment]
Now I conducted a test, created two users with the same passwords, only one had an exclamation mark and authorization worked correctly. The strange bug was temporary. I think the problem can be closed.
