### ISSUE TITLE
XMLRPC doesn't return dates in iso8601 format.

### ISSUE THREAD

**Issue by mpcjanssen** [splitbrain/dokuwiki#2883]
The dates in the XMLRPC results are not according to ISO8601 format. The Java apache XMLRPC client crashes because of this.

Can be fixed by changing the `toDate` function in `inc/remote.php` to:

``` php
    public function toDate($data) {
            return call_user_func($this->dateTransformation, $data)->getIso();
    }
```

**Comment by mpcjanssen** [comment]
I would love to create a pull request, but I am having some problems with creating the unit test. The XMLRPC serve function echo's the XML to stdout. Trying to capture this in the test case with `ob_start` doesn't work. Any tips?

**Comment by splitbrain** [comment]
Good question. I first thought this could be added to the `tests/inc/remote*.test.php` files, but I guess this is XMLRPC specific?

So for a real unit test it would simply check that the appropriate method in the XMLRPC server returns the proper value. But an additional integration test that actually checks that the API returns the proper result could be helpful too. It should be possible to that using our TestRequest mechanism (see https://www.dokuwiki.org/devel:unittesting#integration_tests)

**Comment by mpcjanssen** [comment]
I will look if I can get a more limited test in remote.test.php

**Comment by mpcjanssen** [comment]
@splitbrain PR #2885.

**Comment by mpcjanssen** [comment]
I needed to add some testing provisions in XmlRpcServer because looking at the values directly doesn't help, the issue is with the actual on the wire XML representation.

**Comment by splitbrain** [comment]
For future reference. The [XMLRPC specification](http://xmlrpc.scripting.com/spec.html) is not very clear about the date type format. It calls the type `dateTime.iso860` but it is not really a `ISO8601`. The specification does not say anything about time zones.

For comparison:

```
2019-10-17T09:52:55+0200  DateTime::ISO8601 (what have right now)
2019-10-17T09:52:55+02:00 DateTime::ATOM (what the PHP docs suggest as "better")
20191017T09:52:55+0200    "Ymd\TH:i:sO" (what @mpcjanssen suggests)
20191017T09:52:55         example from the XMLRPC spec
```

I assume that most XMLRPC libraries are aware of this ambiguity and will parse any of these formats, but being closer to the spec (without dropping the timezone info) is probably the best choice.

**Comment by splitbrain** [comment]
As per Ticket #1970 we probably want to replace the IXR library by a composer dependency in the future. Looking at [kissifrot/php-ixr](https://github.com/kissifrot/php-ixr) they seem to use DateTime::ATOM:

https://github.com/kissifrot/php-ixr/blob/4477cd1a67416ce5b6a2080f9a79d9eb50a965c1/src/DataType/Date.php#L59

They also try a whole bunch of formats when parsing a date:

https://github.com/kissifrot/php-ixr/blob/4477cd1a67416ce5b6a2080f9a79d9eb50a965c1/src/DataType/Date.php#L34-L54
