### ISSUE TITLE
Bug with emojis that are based on more than one emoji

### ISSUE THREAD

**Issue by Microcrap** [splitbrain/dokuwiki#2884]
Their is some strange behavour with emojis based on other emoji, example 🏴‍☠️ transformed in `🏴 ☠️` in some circumstances (in the cloud of tag/word ; sometimes when editing an article the tags using this kind of emoji are modified)

**Comment by splitbrain** [comment]
We need more info here. What are the exact steps to reproduce this?

Also note that emoji are heavily influenced by the available/used fonts. for example this is how you post looked in my gmail:

![2019-10-15-221838_376x44_scrot](https://user-images.githubusercontent.com/86426/66866518-c1aebd80-ef99-11e9-824d-475b258a909c.png)

**Comment by Microcrap** [comment]
1. Just add this emoji : https://emojipedia.org/pirate-flag/ in the tag or your article.
1. Edit your tag with the button, and now the emoji is bugged. If you change another tag on your article, you need remove this bugged emoji and re-add the good with copy-paste.
![Screenshot_2019-10-15_22-26-09](https://user-images.githubusercontent.com/56029538/66867096-dccdfd00-ef9a-11e9-9592-b00270595211.png)

The cloud tag word bug : 
![Screenshot_2019-10-15_22-20-32](https://user-images.githubusercontent.com/56029538/66867120-e6effb80-ef9a-11e9-94b4-3b660f12abe3.png)

**Comment by splitbrain** [comment]
Wait, this is about the use in the tag plugin (or some related plugin)? Please report it to the plugin's author/issue tracker.
