### ISSUE TITLE
Doku_Handler::addCall() is not accessible from plugins

### ISSUE THREAD

**Issue by ssahara** [splitbrain/dokuwiki#2887]
https://github.com/splitbrain/dokuwiki/blob/3623073f5adbca901ac0c77e239a84413a9ed10a/inc/parser/handler.php#L47

`addCall()` corresponds to former `_addCall()`. The method visibility has altered to "protected", and now it is not accessible anymore from syntax plugin class.

Some third-party syntax plugins eg. wrap plugin uses `_addCall()`, and the relevant plugin developers will need to modify their codes so that it will work both with current stable DokuWiki and the Snapshot versions.

It seems that syntax plugins can add any type of call/instruction directly to Doku_Handler::calls array in its handle() method. For example, 
```` 
   $handler->_addCall('header', [$title,$level,$pos], $pos);
````
can be rewritten as 
````
      $handler->calls[] = array('header', [$title,$level,$pos], $pos);
````
I wonder whether this is a practical approach to make one plugin code work well both with "Greebo" and the Snapshot versions?

**Comment by splitbrain** [comment]
Well spotted. That's exactly the feedback we need.

I think adding calls is reasonable for plugins so we should make this call public again and have a `deprecated` tagged legacy method for a while.
