### ISSUE TITLE
Enhancement : get picture from LDAP

### ISSUE THREAD

**Issue by Dual-Boot** [splitbrain/dokuwiki#2888]
Hello,

 When using AuthLDAP plugin, I was just wondering if it would be possible to import picture from OpenLDAP photo attribute to push it into Dokuwiki user profile.

   Regards,

**Comment by phy25** [comment]
I don't think there is any user picture in core. Maybe you are using a template/plugin?

Reference: https://forum.dokuwiki.org/thread/13067

**Comment by Dual-Boot** [comment]
Hello,

I am not using any avatar template/plugin. I was thinking of enabling the possibility to add a picture in the user profile; this picture would be retrieved from OpenLDAP jpegPhoto attribute with the authLDAP plugin. Like it retrieves email adress, uid ect.

 regards,

**Comment by Klap-in** [comment]
The user profile is only for the user itself, to change email/password/etc. So far I remember the profile is not accessible for others. So the picture would be only for yourself...

**Comment by Dual-Boot** [comment]
Profile picture is always a good but not essential feature for enterprise deployment.
