### ISSUE TITLE
Not to use special character in autogenerated passwords

### ISSUE THREAD

**Issue by sergey-inform** [splitbrain/dokuwiki#2901]
https://github.com/splitbrain/dokuwiki/blob/1b0271152be79fb7c3fff69500b86a8ce9878128/inc/auth.php#L799

https://github.com/splitbrain/dokuwiki/blob/1b0271152be79fb7c3fff69500b86a8ce9878128/inc/auth.php#L790

The need to use special characters is inconvenient and doubtful. 
1. It's not convenient since special characters are not selected if you double-click the password in the letter (you have to manually select the whole word).
2. The other characters are random which provides sufficient protection against brute force attacks.
3. It doesn't add any strength to the password since the length is constant and the special character is always the last one. Just an extra letter will give more randomness.

Example
Password: holfuvroc50.
Password: farjazimt42$
-- seems confusing. Is '.' a part of a password or just a dot?
-- you can't select the whole password with double click.

Solution: leave only letters and numbers.

**Comment by splitbrain** [comment]
don't use autogenerated passwords or the passpolicy plugin when you have special needs for passwords

**Comment by sergey-inform** [comment]
@splitbrain C'mon. This have nothing to do with password policies. Using special characters just make no sence in this case and creates issues with user support.

**Comment by phy25** [comment]
> And this have nothing to do with password policies.

I think what @splitbrain means is that you can use https://www.dokuwiki.org/plugin:passpolicy to change this. It can be overridden by a plugin.
