### ISSUE TITLE
after Greebo update, link to a section of pages from another page not work correctly

### ISSUE THREAD

**Issue by sabrinasonno** [splitbrain/dokuwiki#2910]
hi, 
I've installed Greebo version and migrate my pages from Frusterick Manners version.

So, I notice an inusual behavior:
when I edit a section, and I save, or not, the section that appear is another. The page is the same, but the section is positioned a little higher, or a little further down.

The same happen when I use the link to a page#section from another page, as this:
https://wiki.geowebframework.com/doku.php?id=gwusermanual:interface:widget#gw_digital_document_widget

Can you tell me something about this?

thanks in advance
Sabrina

**Comment by splitbrain** [comment]
That's a problem with your template. The fixed header offsets all anchors
