### ISSUE TITLE
"Docs" and "Bugs" links in Extension Manager should open in new window/tab

### ISSUE THREAD

**Issue by fthommen** [splitbrain/dokuwiki#2912]
The per-extension links "Docs" and "Bugs" in the Extension Manager currently open in the same window/tab which is quite annoying, especially when you are e.g. looking up documentation to use a plugin in your own Wiki.  Instead these links should better either always open to a new window/tab or respect the DW setting "Target window for external links" from the  Configuration Manager

**Comment by alexgearbox** [comment]
> respect the DW setting "Target window for external links" from the Configuration Manager

:+1:
