### ISSUE TITLE
dokuwiki wiki title stored xss

### ISSUE THREAD

**Issue by Talhasen** [splitbrain/dokuwiki#2926]
Hello,

I have found a security vulnerability in dokuwiki. 
I want to get a CVE number. Could you please fix the vulnerability and inform me.
### **My dokuwiki info:**
**version:** 2018-04-22b "Greebo"

### **The vulnerability detail:**

it is in title input in the configuration manager page. The request was given below. 
![dokuwiki-xss-configuration-manager](https://user-images.githubusercontent.com/15148883/69916984-96f9c500-1472-11ea-84f4-2b01a2687e03.png)

My payload in the POST parameter **config[title]** is **mywiki<script>alert('33333333\n'+document.cookie)</script>**

**The Request SS:**
![dokuwiki-xss-burp-req-ss](https://user-images.githubusercontent.com/15148883/69917025-fc4db600-1472-11ea-93d2-7ec5011020f2.png)

After saving the titile as mentioned above. Every page is affected by the stored XSS(cross-site scripting) vulnerability. For a proof the response of main page request is added below.

**The main page response SS:**
![dokuwiki-xss-burp-home-page-res-ss](https://user-images.githubusercontent.com/15148883/69917033-19828480-1473-11ea-857c-f23bf6168179.png)

As shown below, the vulnerability affects every user of dokuwiki while any page is loading
**The Stored XSS proof SS:**
![dokuwiki-xss-home-page-alert-ss](https://user-images.githubusercontent.com/15148883/69917048-37e88000-1473-11ea-8c1f-8319cb3f290d.png)

**Comment by phy25** [comment]
Since only admin can modify this title, I am not sure if this should be considered a XSS. Meantime, I am also not sure if someone did rely on HTML feature of title, or maybe this should depend on the value of htmlok?

**Comment by phy25** [comment]
Meantime if this is considered an issue, there will be tons of config settings that needs to be checked as well.

**Comment by Talhasen** [comment]
Yes, Only admin can modify this title. But admin normally can not ad script into a page as below. But Because title input is not sanitezed, or the value is not encoded while echoing in the page. I think that this is a stored XSS. Please asses it again with these infomations.

![page-edit-script-not-allowed](https://user-images.githubusercontent.com/15148883/69917900-2f487780-147c-11ea-98db-2360b13bef9d.png)

**Comment by splitbrain** [comment]
The title tag and many other admin settings are deliberately not sanitized. Admins are allowed to put arbitrary HTML into their settings including Javascript. Admins have the power to install arbitrary php code. yif you don't trust the admin then there's no sense in running DokuWiki. This will not be fixed and should not be assigned a CVE. It is not a vulnerability.

**Comment by Talhasen** [comment]
Okay, thanks for your time.
