### ISSUE TITLE
Dokuwiki 2018-04-22b - Username Enumeration

### ISSUE THREAD

**Issue by Talhasen** [splitbrain/dokuwiki#2928]
At login page there is set new password page as below:

Forgotten your password? Get a new one: Set new password

At this page there is username enumeration vulnerability.

========================================================================

## Testing for non-valid user:

POST /doku.php?id=start&do=resendpwd HTTP/1.1

sectok=&do=resendpwd&save=1&login=sss

## Response for non-valid user(sss):

`<div class="error">Sorry, we can't find this user in our database.</div>`

========================================================================

## Testing for valid user:

POST /doku.php?id=start&do=resendpwd HTTP/1.1

sectok=&do=resendpwd&save=1&login=admin

## Response for valid user (admin):

```
<div class="error">There was an unexpected problem communicating with SMTP: Could not open SMTP Port.</div>
<div class="error">Looks like there was an error on sending the password mail. Please contact the admin!</div>
```

**Comment by splitbrain** [comment]
This is another deliberate choice. We want our users to know when they provided the wrong user name. Related article on this: https://hackernoon.com/username-or-password-is-incorrect-is-bullshit-89985ca2be48

**Comment by Talhasen** [comment]
Thanks for quick response. I recommend you to read this OWASP article for username enumeration as well.

https://www.owasp.org/index.php/Testing_for_User_Enumeration_and_Guessable_User_Account_(OWASP-AT-002)

about OWASP
https://www.owasp.org/index.php/About_The_Open_Web_Application_Security_Project

**Comment by phy25** [comment]
While enumerating username is definitely possible when registration is open, this "protection" may have some value if the registration of the wiki is disabled.

However, then you may argue that there is no *native* brute-force protection in DokuWiki - these are all in OWASP best practices, but I believe they were being left out for some reason before (maybe for simplicity?).
