### ISSUE TITLE
Doku_Handler::$status['section'] is not accessible from plugins

### ISSUE THREAD

**Issue by ssahara** [splitbrain/dokuwiki#2931]
https://github.com/splitbrain/dokuwiki/blob/6e0d35582815257160c7d90ff45f03cb2088834b/inc/parser/handler.php#L25-L28

The visibility of the `Doku_Handler::$status` property had been public until DokuWiki Greebo 2018-04-22b,  but now it has altered to "protected" and is not accessible anymore from syntax plugins.

The [NumberedHeadings](https://github.com/ssahara/dw-plugin-NumberedHeadings/blob/e9da83fd2ee320fc3c6193b51ea35493224ed318/syntax.php#L69) plugin, which I am maintaining to catch up with the DokuWiki core developments, uses `$handler->status['section']` in its `handle()` method to know current section status of the page.  And I am looking for a way to make it compatible with DokuWiki snapshot version.

Could I ask you to a) revert the protected $status to public, or b) implement public getter/setter methods for  $status['section']? I prefer b) alternative.

**Comment by RaphaelWimmer** [comment]
I have documented a similar issue with a protected variable [on the DokuWiki forum](https://forum.dokuwiki.org/d/17870-problem-fixing-markdowku-plugin-doku-handler-callwriter-is-protected).
