### ISSUE TITLE
Trace

### ISSUE THREAD

**Issue by zounp** [splitbrain/dokuwiki#2932]
I tried to hide the "Media Manager" link and trace when not logged in. I could not find a solution.
I also tried the "Other actions (comma separated)" field but with no succes.

It would be nice if every object, like trace, the "Media Manager" link, the, backlink & back to top ..., object / items and ... except of course "Log in" could be hidden
Configurable in the Configuration Manager under "disableactions -> Disable DokuWiki actions'

Also it would be nice if there are two "disableactions -> Disable DokuWiki actions' blocks. One when not logged in and one when logged in. In this way Dokuwiki is applicable in more use cases.
Thanks.

**Comment by phy25** [comment]
> It would be nice if every object, like trace, the "Media Manager" link, the, backlink & back to top ..., object / items and ... except of course "Log in" could be hidden

I don't think it's possible in core to hide these based on login status. I am not sure if a plugin is able to hide them all, but some frontend trick can do it as well (output CSS that hides these links based on login status).

Meantime, I don't think this should be in core.

**Comment by zounp** [comment]
I think it should be in core as are all the other options in the Configuration Manager under "disableactions. That makes Dokuwiki more powerful / universal and it feels logical to me if they where hideable . 
Also in if they can be turned off, at least for users not logged in, it gives the site owner the choice, he  / she can decide what is shown and what not.  

Maybe a frontend trick can that outputs CSS that hides these links based on login status can work. However not all users of Dokuwiki have enough knowledge of the code / structure of Dokuwiki and / or CSS to accomplish that.

Like me, their main objective is making a nice wiki, website, with Dokuwiki. I like to use Dokuwiki as much as I can for websites since I am very, very productive with Dokuwiki. There is not much of a learning curve, like Wordpress for instance, and  far most of the things I want to accomplish work (almost) out of the box. That is very very good !!!
Thanks for all the effort.

**Comment by phy25** [comment]
I want to stress that my point is on **login-status based**.

Also, I believe it's doable using a plugin (see the tag on this issue), but I mentioned CSS solution because I was not sure if a plugin can inject at PHP level to control this based on login status. I think about this again and maybe it's doable through hooks by a plugin as well.

**Comment by zounp** [comment]
Login-status based would be fine. The main objective is to hide objects that readers do not need, objects that distract (in the view of the author of the wiki / website). So all objects on in when logged in and every object selectable when not logged in would also be nice and flexible

**Comment by molefunk** [comment]
https://dokuwiki.org/plugin:denyactions and/or https://www.dokuwiki.org/plugin:tplmod can achieve something like that. :)

**Comment by molefunk** [comment]
Relevant settings from Tplmod plugin:

<img width="1077" alt="Screenshot 2021-07-17 at 10 26 56 AM" src="https://user-images.githubusercontent.com/328728/126026391-2a8876c8-006b-4600-a249-6da77a239939.png">
