### ISSUE TITLE
Page locked by unknown host

### ISSUE THREAD

**Issue by zounp** [splitbrain/dokuwiki#2933]
On my Dokuwiki instance I have a page called (replaced the domain name with example) https://wiki.example.nl/dokuwiki This page gets locked all the time. No one but me can edit this page. I have seen: Currently locked by: 147.135.225.193 or 107.152.239.44 or 195.154.61.122

The page does not get changed, at least I do not get an e-mail because of a change. 
Is this a bug caused by the fact that the page is called Dokuwiki or is something else going on?
Thanks.

**Comment by phy25** [comment]
Hello, could you please check your server access log related to these IP addresses? It is possible that your account is compromised, but without more information I cannot guess how this will happen.

147.135.225.193 - ovh.com
107.152.239.44 - servermania.com
195.154.61.122 - online.net

**Comment by zounp** [comment]
Thanks.
Looked in the log from the Dokuwiki Log Stats plugin. Found a lot of "https://wiki.webevaluation.nl/dokuwiki?do=login&sectok=" which results in the login page if I do that myself.
And https://wiki.webevaluation.nl/dokuwiki?do=register which results in "Action disabled: register" on a red background if I do that myself. Both found for 147.135.225.193
A few attempts for 107.152.239.44 and some more for 195.154.61.122
All in all there have been attempts from 130 different IP's. It can not tell from the logs that somebody was able to login. 
What information are your looking for?
Do you have any idea how can I tell if the wiki has been breached?
As far as I can tell I followed https://www.dokuwiki.org/security
Thanks.

**Comment by zounp** [comment]
After the lock expired I have moved the contents of https://example.com/dokuwiki to an other page say https://example.com/dokuwikiForTEST  and made a new https://example.com/dokuwiki with some random text. https://example.com/dokuwiki still gets locked almost right away. So it has nothing to do with the contents of the page. The new https://example.com/dokuwikiForTEST does not get locked. Maybe it is an idea to try yourself and create a https://yourdomain.com/dokuwiki page and see if it gets locked.

https://example.com/dokuwiki is the only page that gets locked in this way in my Dokuwiki installation I have encountered so far.

**Comment by phy25** [comment]
I don't run a public DokuWiki instance anymore but DokuWiki has https://www.dokuwiki.org/dokuwiki.

If I were you, I would see if those IPs that lock the page are actually visiting `do=edit` - those IPs are not random and I guess they are bots. Meantime what's your DokuWiki version and what are the installed plugins?

**Comment by zounp** [comment]
No do=edit 's
Verison: Release 2018-04-22b "Greebo"
Plugins: Maybe later,
I did an experiment: I moved the contents of the dokuwiki page to an other page say dokuwikinew and put a line of text in the dokuwiki page. Since then it does not get locked.  I will watch for a bit more time dokuwiki to see if it gets locked again. Then I will continue this experiment by putting back parts of dokuwikinew to dokuwiki and see what happens.

**Comment by zounp** [comment]
Update: The dokuwiki page gets locked again. Since the page contains only:
"
====== Dokuwiki ======
Some line of text
"
the contents of the page does not seem to be the problem.
dokuwikinew does not get locked so far.
I have set up an other public instance of dokuwiki and added a page named dokuwiki. It does not get locked so far. I am going to investigate the differences between the two instances.

**Comment by phy25** [comment]
I am closing this because of lack of information and there is nothing we can do at this point, but feel free to add more information and I can reopen the issue.
