### ISSUE TITLE
alternate text color

### ISSUE THREAD

**Issue by zounp** [splitbrain/dokuwiki#2934]

**Comment by phy25** [comment]
See https://www.dokuwiki.org/plugin:styling. If you are not sure how this works, please clarify what you need.

**Comment by zounp** [comment]
When I go to "Admin" "Template style settings" I can change the "Alternative text color" this changes the color of the border around the text and also the color of the bullet points. It would be nice if I could change the color of the border independent of the color of the bullet points. 
Also I searched on dokuwiki.org but could find which items are influenced by "Alternative text color" Also I could not find it for "Main text color" and "Neutral text color" . It would be nice if somewhere is clarified which objects are influenced by which text color setting.
Thanks.

**Comment by zounp** [comment]
@phy25 Clicked "Submit new issue" by accident before entering the text.
"please clarify what you need" See above.

**Comment by phy25** [comment]
What specific color is being changed depends on what specific template you use. `plugin:styling` only saved these colors so that the template can use them.

**Comment by zounp** [comment]
I use the default Dokuwiki template.
