### ISSUE TITLE
io_savefile possibly f in stead of capital F ?

### ISSUE THREAD

**Issue by zounp** [splitbrain/dokuwiki#2937]
I was looking through the dokuwiki/inc/cache.php and noticed that the function io_saveFile is called on line 122 with io_savefile ( no capital F ). Also on line 335,. Also in the comment line 391 in file inc/io.php .
Maybe it is right. It looks odd to me.
Thanks for Dokuwiki :-)

**Comment by phy25** [comment]
PHP's function name is case-insensitive but yes this should be consistent. PR welcome!

**Comment by zounp** [comment]
Never done a PR. I'll give it a try.
