### ISSUE TITLE
Democratic Wiki based on Dokuwiki

### ISSUE THREAD

**Issue by obel1x** [splitbrain/dokuwiki#2939]
This is no Bug, but a suggestion of how to improve the Wiki- Idea to help Democratic evolving of the content itself. I hope to find supporters that may be able to implement this based on Dokuwiki - or maybe point the direction to where it will be supported.

Basic thougths
A Wiki describes a situation in the words of someone on a page. If someone else thinks, that this may be changed, he will edit the page. There is no process of decissions so far what implies that the new version improves the old one.
Sometimes the page or maybe the situation should be changed and different people are having different solutions.

Democratic Aspect
It would be ideal to have the possibility to create many "versions" in "draft" of the page - each one of it changed as the corresponding author thinks is the best. After the versions have been finished, there should be a way to decide which version is the best implementing a restistance principle including the option to leave the page as it is.
After some time (that could be defined in early state), the "winnig" page will become the current version. The participannts may be the followers of the page.

This in brief. Can anyone follow my thougths and maybe support the idea?

**Comment by phy25** [comment]
[plugin:publish](https://www.dokuwiki.org/plugin:publish) is quite similar to what you describe.

**Comment by splitbrain** [comment]
check out Ward Cunningham's federated wiki. I think he's trying to implement something like that. Personally I find it much too complicated and thus not very "wiki".
