### ISSUE TITLE
"invisible" spaces in table 

### ISSUE THREAD

**Issue by icf20** [splitbrain/dokuwiki#2940]
_no posting this i realize that i should have inspected the html in developer mode_

so i had a table, the table was originally copy pasted 

|bla1|bla2|
|bla3|bla4|
|bla5|bla6|

|bla3|bla4| dint get the any formatting

i went to the /data/ folder and the bla.txt file dint have any space

so i vent in front of (here)|bla3|bla4| with the cursor in the web editor pressed backspace one time, the expected result it was for the text to move one line above but in dint when i pressed backspace the second time it went one line above like |bla1|bla2||bla3|bla4| then a enter in front of |bla3|bla4| it went an line below and the table was rendering correctly

i dont have any extensions installed related to tables

**Comment by phy25** [comment]
There might be hidden spaces in your text - Those unicode characters are sometimes confusing, but I don't think we can do anything.

View non-printable unicode characters: https://www.soscisurvey.de/tools/view-chars.php
