### ISSUE TITLE
Feature request: Limit cache size

### ISSUE THREAD

**Issue by zioth** [splitbrain/dokuwiki#2948]
The hosting service I use puts a strict cap on disk space, and my Doku cache can easily get up to 500MB, so I have to manually delete my cache every couple weeks. The obvious solution would be to switch to a better web host, but a feature to limit the size of the disk cache would be useful.

I realize this would be non-trivial, and might impact performance (since you'd need an index/manifest file to avoid frequent directory listing).

**Comment by phy25** [comment]
See also:
https://www.dokuwiki.org/plugin:cleanup
https://www.dokuwiki.org/tips:maintenance
