### ISSUE TITLE
/usr/share/dokuwiki/conf/ directory not created during install + multiple permission issues (Ubuntu Server 18.04 LTS 64bit)

### ISSUE THREAD

**Issue by johays** [splitbrain/dokuwiki#2951]
Trying to setup DokuWiki on a fresh Ubuntu Server 18.04 LTS 64-bit install.

**Setup-method:** apt
**Webserver:** apache2
**php-versoin:** 7.2.24

After installing I tried to run `localhost/dokuwiki/install.php` - there was a long error list (missing write-permissions on 10+ folders and files). 
Following this guide (https://www.dokuwiki.org/install:ubuntu), all but one error disappears.

**Remaining error:** 

`/usr/share/dokuwiki/conf/ is not writable by DokuWiki. You need to fix the permission settings of this directory!`

_**Consulting both /var/lib/dokuwiki/data/ and /usr/share/dokuwiki/ it results that the conf-directory has not been created at all during installation.**_ 
The installation (apt) did not report any errors.

**Tried fixes (negative):**
- manually create conf-directory and changing ownership to `www-data:www-data`
- `chmod -R 0777` on ../dokuwiki directory (desperate, I know)
- clear cache in browser

It is not a strange thing that an admin would try to set up DokuWiki on an Ubuntu Server. This should really work out of the box. Can we please fix this? <3

**Comment by phy25** [comment]
We don't officially build `dokuwiki` package on ubuntu - you can open a bug or check existing bugs here: https://launchpad.net/ubuntu/+source/dokuwiki/+bugs
