### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by rusly-id** [splitbrain/dokuwiki#2953]
Hi
 
I am from Indonesia and not a programmer, I want to tell you there is a truncated translation in Indonesian

![Opera Snapshot_2020-01-07_025837_wartapedia 000webhostapp com](https://user-images.githubusercontent.com/59580932/71846226-a8329300-30fc-11ea-9ea9-d3312b8278ec.png)
> Konfigurasi berwarna putih atau b...?

Here is the correct full text : 

Konfigurasi berwarna putih atau biru dapat diubah.

Ingatlah untuk menekan tombol simpan sebelum meninggalkan halaman ini, jika tidak perubahan Anda akan hilang.

Thank you

**Comment by rusly-id** [comment]
Sorry after I noticed again it turns out that many other words are cut off and not arranged correctly

![Opera Snapshot_2020-01-07_033253_wartapedia 000webhostapp com](https://user-images.githubusercontent.com/59580932/71847275-0a8c9300-30ff-11ea-8a19-9cc6012bcc86.png)

Here I am corrected as a whole :

Gunakan halaman ini untuk mengontrol pengaturan instalasi DokuWiki anda. Untuk bantuan tentang pengaturan individual, lihat [config](url). Untuk detail lebih lanjut tentang plugin ini lihat [plugin: config](url).

Pengaturan yang ditunjukkan dengan latar belakang merah muda dilindungi dan tidak dapat diubah dengan plugin ini. Pengaturan yang ditunjukkan dengan latar belakang biru adalah nilai bawaan (default) dan pengaturan yang ditunjukkan dengan latar belakang putih telah diatur secara lokal oleh anda. Pengaturan biru dan putih dapat diubah.

Ingatlah untuk menekan tombol simpan sebelum meninggalkan halaman ini, jika tidak perubahan anda akan hilang.

**Comment by phy25** [comment]
Hello, could you submit a patch here? https://translate.dokuwiki.org/translate/dokuwiki?lang=id

In this way you can add your credit to this translation change. Thanks!

**Comment by rusly-id** [comment]
Do I just add these words to Indonesian? I mean without coding etc. :D

If yes I will try it

**Comment by phy25** [comment]
Hi @rusly-id, if you go to the translate website, you should see a GUI to submit translations with no coding required. You are also welcome to submit more translations if you have time (currently Indonesian translation is only 41% complete) - you don't need to fill in everything to submit though:

https://translate.dokuwiki.org/translate/dokuwiki?lang=id

**Comment by rusly-id** [comment]
Ok I will try it

Thank you
