### ISSUE TITLE
Argon2i hash support (needed to AuthPDO against nextcloud 16.x)

### ISSUE THREAD

**Issue by einhirn** [splitbrain/dokuwiki#2956]
I want to AuthPDO against our nextcloud database, but they are using Argon2i hashes. Now it seems that I'll have to patch "inc/PassHash.php" to support that, am I correct? I'll give it a spin and try to create a pull request.

**Comment by einhirn** [comment]
Is there a particular reason for not using php's own `password_hash `/ `password_verify` functions - other than support for legacy PHP versions and/or special password hash schemes not supported by the native functions?

**Comment by phy25** [comment]
> Is there a particular reason for not using php's own `password_hash `/ `password_verify` functions - other than support for legacy PHP versions and/or special password hash schemes not supported by the native functions?

If you `git blame` those code you will see how old they are - DokuWiki currently supports PHP 5.6+ but these legacy code hasn't been refactored to make full use of the new features. (We also use legacy fallback JSON library now if I remembered correctly 😂)
