### ISSUE TITLE
login page leaks struct plugin Information of closed wiki without being logged in

### ISSUE THREAD

**Issue by b3nks** [splitbrain/dokuwiki#2963]
My Wiki Release 2018-04-22b "Greebo" showed one of my struct entrees at the login page without being logged in. ACL of * is set to  "none" for @ALL

After having set cachetime to 10 seconds the leaked information immediately disappeared.

The leaked information can be found in the page source here:

</div></div>

        <div class="wrapper group">

            
            
            <div id="dokuwiki__content"><div class="pad group">
                
                <div class="pageId"><span>start</span></div>

                <div class="page group">
                                                            
                    <div id="plugin__struct_output"><div class="table"><table class="inline">
	<thead>
	@@@LEAKED INFORMATION@@@
	</tbody></table></div></div><p>Bitte hier anmelden: </p> <div class="centeralign"> <form id="dw__login" method="post" action="" accept-charset="utf-8"><div class="no">

**Comment by phy25** [comment]
The cache in DokuWiki does not consider user sign-in status - a user either sees a permission error, or sees the cached page.

I am not sure why you have this wiki content showing up on a login page. Do you know where you use this struct plugin information in the wiki page? Could you please provide steps to reproduce the issue?

**Comment by b3nks** [comment]
![wikileaks](https://user-images.githubusercontent.com/20385436/72685380-d8f5cd80-3ae9-11ea-855d-cb8a3d5c6670.png)
Here's a screenshot for now. You can see one entree of struct from one file.
I'll try to reproduce later.

**Comment by splitbrain** [comment]
@b3nks Can you please reopen the issue in the struct plugin's bug tracker? Please also be sure to have the most recent release. Any hints on how to reproduce would be helpful.

**Comment by b3nks** [comment]
@splitbrain 
done
