### ISSUE TITLE
Installing a plugin yields a blank page and a corrupted Dokuwiki instance

### ISSUE THREAD

**Issue by zounp** [splitbrain/dokuwiki#2966]
See also #2965 for the introduction.
When I click on "Install" in the "Color Plugin" case, which I am getting now as search result, Dokuwiki returns a blank screen. I have to restore from backup, putting public_html back, to get Dokuwiki working again.
After that when I click on "Extension Manager" tab "Installed Plugins" I get no results although plugins are installed.
Then I search again for "color" Now the "Color Syntax Plugin" is found. I now can click on "Un-install" which I do. I get the blank page and have to restore from backup. Maybe I should do a complete reinstall via Installatron.
I needs some more investigation though. Later more.

Some time later:
Did a (re)install of Dokuwiki twice.
After installing some plugins one instance of Dokuwiki does not show the installed plugins. The information pane opens briefly and closes again. In the other instance it works fine. 
What the difference is has to be investigated. Later more.

**Comment by phy25** [comment]
Do you have any further information that can be attached? When you say "corrupted" there is no PHP error logs so we don't know which part went wrong.

**Comment by phy25** [comment]
I am going to close this, but if you have any information to add we can definitely reopen it.

**Comment by zounp** [comment]
You are right. Sorry for the delay. 
When I encounter it again I will have a look in the PHP error logs.
Can you tell me where I can find them? Thanks.

**Comment by phy25** [comment]
Well it depends on your set up. Did you set up the environment yourself or use a shared environment?

**Comment by zounp** [comment]
I did the setup myself via FTP.

**Comment by zounp** [comment]
Ah, logs, I checked on the server but could not find any other than from May.
