### ISSUE TITLE
NOCACHE requiered to add in sidebar every time

### ISSUE THREAD

**Issue by HonkXL** [splitbrain/dokuwiki#2968]
Because of the caching the functionality that the selected item is bold in the sidebar is not working well. Most time nothing is bold, or any (random) entry is displayed bold.
The solution is to add `~~NOCACHE~~` to the sidebar to fix this problem.

I think it would be better to add this automatically or to handle the caching better for the sidebar, because manually adding it brings up the problem that it is forgotten often. When you have multilingual wikis, this is a real problem.

Solution: never cache the sidebar - so `~~NOCACHE~~` is no longer required on this place.

Tested with latest release and standard theme on 3 different installations.

**Comment by phy25** [comment]
I am not quite sure what selected item you are referring to in the sidebar. Are you using some plugins?

I am not sure if this can be implemented by a plugin in the meantime.

**Comment by alexgearbox** [comment]
It's work! Thanks for this hint!

**Comment by phy25** [comment]
@alexgearbox I assume that you were saying the cache can be disabled by a plugin right?

**Comment by Klap-in** [comment]
The `~~NOCACHE~~` is intended for disabling the cache. We are using it also in dokuwiki.org's sidebar https://www.dokuwiki.org/aside?do=edit
There is no feature for adding this property default to a page. 
By the way, if a lower level page is not available, it can be retrieved from its parent namespace.
Of course for more namespaces, which are language dependent, you need indeed a sidebar per namespace.

**Comment by alexgearbox** [comment]
@phy25 No, you aren't.

My reply was for @HonkXL.

**Comment by splitbrain** [comment]
The proper way to fix the actual problem described by @HonkXL is to drop the generation of the `.cur` class in PHP alltogether and add it dynamically by JavaScript. This way it's completely independent from the page cache.

**Comment by phy25** [comment]
Sorry I didn't know it's about `.curid`:

https://github.com/splitbrain/dokuwiki/blob/c22dd092c4c44d7d648d88cb32606880af5156c7/inc/parser/xhtml.php#L921

Maybe we can make the sidebar cache mainpage-aware?

**Comment by Klap-in** [comment]
> Maybe we can make the sidebar cache mainpage-aware?

I guess a bit of javascript is easier.. ;-)

**Comment by phy25** [comment]
A previous issue: #1511.
