### ISSUE TITLE
Security Token did not match. Possible CSRF attack.

### ISSUE THREAD

**Issue by icf20** [splitbrain/dokuwiki#2973]
![image](https://user-images.githubusercontent.com/17784575/73101811-ce27a800-3ef0-11ea-8913-6265993f6c5a.png)

i am willing to bet it is because international domain name, installing and using a standard english only dont have this issue

the install is new, all default

**Comment by Klap-in** [comment]
Could you you mean a internationalized domain name? 
e.g. https://en.m.wikipedia.org/wiki/Internationalized_domain_name
Could you provide an example name to test with?

**Comment by icf20** [comment]
i made few more test
dont work for ñ, ă, Я, н ,д ,е etc


now i wonder if a user can have a user@Яндекс.рф email :rofl:

**Comment by phy25** [comment]
I cannot reproduce this. Also this security token is generated from your session_id and username, not email.

https://github.com/splitbrain/dokuwiki/blob/246d33375d7a319f09d2b596725e38a48dd90794/inc/common.php#L100-L110

What's your DokuWiki version and PHP/Apache version?

You can check if your session_id is always rotating, or if you have a UTF-8 username (I tested this as well, which should not be an issue). You can make use of [`?do=debug`](https://www.dokuwiki.org/devel:debugging) and search for `$_SESSION` to see if this is working properly.

**Comment by icf20** [comment]
> Also this security token is generated from your session_id and username, not email.

then ignore this, it means is a LDAP Auth issue
