### ISSUE TITLE
PHP function utf8_decode is not available.

### ISSUE THREAD

**Issue by DorukUlucay** [splitbrain/dokuwiki#2975]
Trying to install dokuwiki on ubuntu. I have php 7.2 installed. When I go to site I can see the page 

> This topic does not exist yet

When I go to installer I get the error:

> PHP function utf8_decode is not available. Maybe your hosting provider disabled it for some reason?

I tried;

- Installing php-xml
- Installing php-mbstring
- Having seperate php.ini file for dokuwiki and enabling this extensions.

But still can not get it to work. 

Thanks in advance for any help.

**Comment by phy25** [comment]
Do you have a message of utf8_encode as well or you only have this utf8_decode messgae? How did you install DokuWiki on Ubuntu? What version of Ubuntu do you have?

**Comment by DorukUlucay** [comment]
- I missed that. Yes there's also utf8_encode message.
- I wget'ted it, unpacked it. That's how I installed.
- My Ubuntu version is 18.04

**Comment by phy25** [comment]
How did you install your PHP? `apt`?

**Comment by DorukUlucay** [comment]
Probably through apt since we don't have gui. But I'm not sure because I was not the one who installed it.

**Comment by Klap-in** [comment]
It are the correct versions? Did you restart it after installing?

**Comment by DorukUlucay** [comment]
Restarted apache2.

**Comment by phy25** [comment]
I guess you either have a separate PHP running than the `apt` one (and thus `php-xml` package won't work by default), or you have a misconfiguration. This is more suited as [a forum question](https://forum.dokuwiki.org/), but you can look at `doku.php?do=debug` to find useful information. Please note that this will contain sensitive config information of your server, so please do not post this information publicly. You can continue to comment here though I am closing this issue.

**Comment by DorukUlucay** [comment]
@phy25 thank you for advice. I'll try to find that out. One more thing:
When I try to go to myhostname.com/doku.php?do=debug I see the page.

> This topic does not exist yet

I'll be glad if you can help me with that too.

**Comment by Klap-in** [comment]
I guess you should temporary enable the debug setting as well.
https://www.dokuwiki.org/devel:debugging

**Comment by DorukUlucay** [comment]
debug does not reveal anything.

**Comment by phy25** [comment]
Well, `<?php phpinfo(); ?>`.

> I guess you either have a separate PHP running than the apt one (and thus php-xml package won't work by default), or you have a misconfiguration.

**Comment by DorukUlucay** [comment]
You were right. App's php was different than the latest one installed in server.
it is 7.0.33.
adding AddHandler application/x-httpd-php72 .php to .htaccess in app root did not work.

**Comment by phy25** [comment]
I would recommend that you reach out to whoever configured this PHP 7.0 environment to let them install `xml`, or you will need to figure out how to configure your Apache correctly to use the PHP version that you want (e.g. the `apt` packaged one).

**Comment by DorukUlucay** [comment]
thanks a lot @phy25 
you helped me a lot. 
I'll try to configure my app to work with php7.2. I guess i can do that.
