### ISSUE TITLE
AuthAD: Ignore certificate for SSL?

### ISSUE THREAD

**Issue by dougthor42** [splitbrain/dokuwiki#2976]
## Summary:

Is there a way to tell the AuthAD plugin to ignore invalid SSL certificates when using LDAP-over-SSL?

Other services required me to ignore self-signed/invalid certs to get LDAPS working, so I expect I need to do the same for DokuWiki.

## Config

These are the config differences when going from a working non-SSL LDAP connection to a **non-working** LDAPS connection:

```diff
-$conf['plugin']['authad']['use_ssl'] = 0;
+$conf['plugin']['authad']['use_ssl'] = 1;
+$conf['plugin']['authad']['ad_port'] = 636;      // Is this actually needed? Does use_ssl set this automatically?
```

Other relevant config:

```php
$conf['plugin']['authad']['domain_controllers'] = 'dc1.company.local, dc2.company.local';
$conf['plugin']['authad']['version'] = 3;
```

## Background

With the upcoming changes to Windows AD LDAP channel binding and LDAP signing requirements (see [here](https://www.reddit.com/r/sysadmin/comments/ephd6j/attention_all_windowsad_admins_march_2020_will_be/), [here](https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirement-for-windows), and [here](https://docs.microsoft.com/en-us/archive/blogs/russellt/identifying-clear-text-ldap-binds-to-your-dcs)), I'm trying to enable LDAP over SSL for our DokuWiki instance.

I currently use the [AuthAD](https://www.dokuwiki.org/plugin:authad) plugin for auth.

We use self-signed certs since everything is internal, so for other tools, such as Snipe-IT and Apache httpd, I had to ignore invalid SSL certificates.

**Snipe-IT:**
![image](https://user-images.githubusercontent.com/5386897/73559145-5d5d2000-4409-11ea-8919-a64a76ea9b45.png)

**Apache httpd:**
[Reference](https://www.reddit.com/r/sysadmin/comments/2ec41m/apache_auth_and_active_directory_over_ldaps_thats/)
Change AuthLDAPURL in `/etc/apache2/sites-available/our_website.cfg`:
```diff
-AuthLDAPURL "ldap://dc.company.local:389/dc=company,dc=local?sAMAccountName"
+AuthLDAPURL "ldaps://dc.company.local:636/dc=company,dc=local?sAMAccountName"
```
Change Global Config in `/etc/apache2/apache2.conf`:
```diff
+LDAPTrustedMode SSL
+LDAPVerifyServerCert off
```

**Comment by phy25** [comment]
This is an upstream issue because authad uses https://github.com/Rich2k/adLDAP.

Some reference:
https://gist.github.com/heiglandreas/8a299a6f47a13ba463c3f2da41c679f7
https://stackoverflow.com/questions/3866406/need-help-ignoring-server-certificate-while-binding-to-ldap-server-using-php/7586808#7586808

**Comment by dougthor42** [comment]
Thanks, I had found some [other references](https://www.php.net/manual/en/function.ldap-bind.php) mentioning [`putenv("TLS_REQCERT=never")`](https://github.com/Adldap2/Adldap2-Laravel/issues/318#issuecomment-300532754) and the like, but wasn't sure if there was already an option available in AuthAD.

Should I post the request on the upstream? Or perhaps there's a hack I can do to inject 

```php
ldap_set_option($con, LDAP_OPT_X_TLS_REQUIRE_CERT, LDAP_OPT_X_TLS_NEVER);
```

into my own DokuWiki instance?

**Comment by phy25** [comment]
Upstream code - https://github.com/Rich2k/adLDAP/blob/master/lib/adLDAP/adLDAP.php#L612

Please open an issue upstream. I am not familiar with PHP's ldap stuffs, but I am afraid you will have to hack the library code yourself before it's added to upstream.

**Comment by dougthor42** [comment]
Perfect, that means I'm looking in the exact right spot. Thanks!

It looks like the [Rich2k/adLDAP](https://github.com/Rich2k/adLDAP) repo is stale (and doesn't support Issues). That was forked from [adldap/adLDAP](https://github.com/adldap/adLDAP), which is now [dead](https://github.com/adldap/adLDAP/issues/144). The successor to adLDAP is [adLDAP2](https://github.com/Adldap2/Adldap2), which is now being replaced by [LdapRecord](https://github.com/DirectoryTree/LdapRecord).

I'll see what I can hack and report back if I find something.

**Comment by dougthor42** [comment]
Well that was a heck of a lot easier than expected.

To allow insecure certificates when using LDAP-over-SSL, edit `adLDAP.php` in your dokuwiki installation folder. For me, that was located at `/var/www/dokuwiki/lib/plugins/authad/adLDAP/adLDAP.php`:

```diff
diff --git a/adLDAP.php.bak b/adLDAP.php
index c84a4f4..955154f 100644
--- a/adLDAP.php.bak
+++ b/adLDAP.php
@@ -625,6 +625,7 @@ class adLDAP {
         // Connect to the AD/LDAP server as the username/password
         $domainController = $this->randomController();
         if ($this->useSSL) {
+            putenv("LDAPTLS_REQCERT=never");
             $this->ldapConnection = ldap_connect("ldaps://" . $domainController, $this->adPort);
         } else {
             $this->ldapConnection = ldap_connect($domainController, $this->adPort);
```

The above was done on DokuWiki Release 2018-04-22b "Greebo".

----

I'm not going to submit a patch to the upstreams for 2 reasons:

1. They don't appear to be maintained
2. I don't know enough PHP to be able to add this as a option that can be toggled on and off.

So instead I'm just going to leave this here as documentation for future users.

I'll let you decide to keep this Issue open or close it as wontfix or whatever.

Thanks again for your help!

**Comment by phy25** [comment]
You actually pointed out a legacy library in this issue. I will keep this issue open for some time because I am not sure if someone wants to replace it.

**Comment by Klap-in** [comment]
About the adldap update, please note there is already an issue for that step: https://github.com/splitbrain/dokuwiki/issues/1553

**Comment by phy25** [comment]
Thanks @Klap-in! Then I can close this issue.
