### ISSUE TITLE
Require password change at next login

### ISSUE THREAD

**Issue by listerr** [splitbrain/dokuwiki#2981]
Hello,

Having recently upgraded from old version of Dokiwiki to latest (Greebo), we migrated from previous .htaccess passwd file auth backend to using the DokuWiki inbuilt user/passwd file and ACLs.

The old htpasswd file used simple crypt hash, and these work when added to users.auth.php, but I would like for users to change their passwords when they next log in, so that it is updated using a more secure password hash.

Although the new password / password recovery process sends the user an email with a link to change their password, if autopasswd is enabled, it then sends the new password in plain text via email, but does not require the user to change this password on next login.

If autopasswd is disabled, then the user is prompted just to set a new password when they follow the password reset link.

A "Require password change at next login" option would be useful for other reasons too.

This might have an option to just allow the user to enter a new password and continue, or send a URL first to the registered email address, and when following this link, this takes them to an "Enter new password" link. (Then it could be used in other situations like if passwords were ever compromised, or used in "forgot password" code without having to.

**Comment by phy25** [comment]
I understand the usefulness of the functionality, but I am not sure if this should be implemented as a plugin. Putting it in core is probably too much?

**Comment by listerr** [comment]
I'm not all that familiar with the code, but it looks like it would need changes to at least usermanager plugin (which is bundled and suggests putting requests here.) and possibly auth.php so that it can redirect a user that needs to reset password at login and redirects them to the password reset process.

**Comment by phy25** [comment]
You can definitely create a new plugin with the dependency of usermanager - I don't think modifying existing code is needed.

Probably by hooking [`auth_login_check` event](https://www.dokuwiki.org/devel:event:auth_login_check) to check against your requirement (the default authplain does not store much attributes though - maybe you can put all users requiring a password reset to a dedicated group and remove them from the group during [`AUTH_USER_CHANGE`](https://www.dokuwiki.org/devel:event:auth_userdata_change)?). You can start by using the plugin wizard: https://pluginwiz.dokuwiki.org/

**Comment by phy25** [comment]
I created [plugin:forceuserchange](https://www.dokuwiki.org/plugin:forceuserchange) for this purpose.
