### ISSUE TITLE
Review / suggestions on git-remote-dokuwiki

### ISSUE THREAD

**Issue by lyda** [splitbrain/dokuwiki#2984]
I have an [initial pass] at a [git remote] for dokuwiki.  It will do fetches, but not pushes yet. It's loosely modeled on [Git-Mediawiki] but I'm so far including less options.

It's been a while since I did perl so trying to figure out the packaging framework again - the important file is `git-remote-dokuwiki`.

Would appreciate any feedback or suggestions.

[initial pass]: https://github.com/lyda/git-remote-dokuwiki
[git remote]: https://git-scm.com/docs/git-remote-helpers
[Git-Mediawiki]: https://github.com/Git-Mediawiki/Git-Mediawiki

**Comment by splitbrain** [comment]
Sorry, this is not the right place for this. I suggest taking this to the forums or the mailing list. Please also include a little more background on what this is actually about (for people not familiar with git-mediawiki). Eg. what does it do and how would I use it?
