### ISSUE TITLE
Weak Password Policy

### ISSUE THREAD

**Issue by mohammedabdulkareem0** [splitbrain/dokuwiki#2986]
Hi team,

Found weak password issue in your website  https://www.dokuwiki.org/
your website allowing users to set their password too simple, at this time, I can set my password to (aaaaaa) Determine the resistance of the application against brute force password guessing using available password dictionaries by evaluating the length, complexity, reuse and aging requirements of passwords.
 
Some policies suggest or impose requirements on what type of password a user can choose such as:
The use of both upper-case and lower-case letters (case sensitivity)
inclusion of one or more numerical digits
inclusion of special characters, such as @, #, $
prohibition of words found in a password blacklist
prohibition of words found in the user's personal information
prohibition of the use of company name or an abbreviation
prohibition of passwords that match the format of calendar dates, license plate numbers, telephone
numbers, or other common numbers
The password should not be the same as the username.

Step To Reproduce:-

Navigate to the signup page.

Fill your details and give the password as simple as aaaaaa

You can see you will be registered and there is no strong enforcement.

Refer to this link: https://en.wikipedia.org/wiki/Password_policy

Hope it will be fixed soon,
Thanks, And Regards,
Mohammed Abdul Kareem.

**Comment by splitbrain** [comment]
We let users decide what they consider safe enough. If you want to enforce a password policy in your own wiki, use the passpolicy plugin.

**Comment by mohammedabdulkareem0** [comment]
iIf you decided that user will be safe enough if the account will take over then is it safe for user
