### ISSUE TITLE
Add syntax highlighting for systemd unit files

### ISSUE THREAD

**Issue by Serranya** [splitbrain/dokuwiki#2988]
Hi, I want to use systemd files in code and file tags.

I'm no PHP programmer but maybe I can contribute the language file myself. Can you give me a few pointers to get started?

**Comment by LarsGit223** [comment]
Syntax highlighting in DokuWiki is done using the GeSHi syntax highlighter. That means you would need to do changes in that project and not in DokuWiki itself. See [the GeSHi project homepage](http://qbnz.com/highlighter/). You can find the GeSHI source code in your DokuWiki installation in the folder ```vendor/geshi```.

Once a new GeSHI release with your changes is out, it could be integrated in the next DokuWiki release.

**Comment by phy25** [comment]
I am going to close this issue since it's more of a question for upstream. You can continue to comment if you have any further questions.
