### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by rs-github** [splitbrain/dokuwiki#2998]
After completing install.php the following warning pops up:
Deprecated: Array and string offset access syntax with curly braces is deprecated in C:\xampp\htdocs\dokuwiki\inc\PassHash.class.php on line 204

**Comment by phy25** [comment]
What DokuWiki and PHP version are you using? I cannot find the line your error message is pointing to. Also this should only be a warning, not error. 

This should have already been fixed in master by #2902.
