### ISSUE TITLE
toc - only two header levels are displayed

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [splitbrain/dokuwiki#3017]
Hi,

I've a problem with our toc configuration.

toptoclevel is set to 2
maxtoclevel is set to 4
tocminheads is set to 3

My question: Is it normal that only two header levels are displayed. I'm not able to display more levels not matter what configuration is set.

Any hints how I can get more header levels displayed?

Thanks
Speedy

**Comment by phy25** [comment]
What is the template that you use? Could you try the following to see what is the TOC output?

```
====== Headline 1 ======

===== Headline 2 =====

==== Headline 3 ====

=== Headline 4===

== Headline 5 ==
```

**Comment by Speedy-Gonzalez** [comment]
Thank you! Never thought that the template could be the problem. I've found a solution.

I'm using the bootstrap3 template. I had to set 'tpl»bootstrap3»tocCollapseSubSections' to false to get the right result.

Now it works as expected.
