### ISSUE TITLE
Feature Request: Event Handler for image events (resizing / cropping)

### ISSUE THREAD

**Issue by takuy** [splitbrain/dokuwiki#3032]
I would like to write a plugin that handles image events like resizing and cropping without GD/IM.

I'm assuming the events will need to be added here: https://github.com/splitbrain/dokuwiki/blob/95704c8797ed14fd8ed9427be6121e56efe343de/lib/exe/fetch.php#L82

I can try my hand at implementing this, but not sure what all needs to be done just yet.

**Comment by Klap-in** [comment]
Did you read these  https://www.dokuwiki.org/devel:events and https://www.dokuwiki.org/devel:event_handlers ?

(The source of the development version of DokuWiki has changed compared to the last release. The development version has just had a big refactoring, which is not yet applied to the development manual. So functions are renamed and moved.

Please ask if you cannot find them anymore. You should get deprecation messages if you would use older pieces of code. Probably it is practical to find another feature in the current DokuWiki code that triggers events.)

**Comment by takuy** [comment]
Thanks @Klap-in, I have looked over those pages but not in great detail. Can you tell me what branch is used for active development? Not seeing any obvious dev branch.

**Comment by phy25** [comment]
master branch is the development branch.
