### ISSUE TITLE
For `mediarevisions` / `media_attic`, allow some files not to be revisioned.

### ISSUE THREAD

**Issue by tatewake** [splitbrain/dokuwiki#3035]
Hello,

Someone reported an issue with [BackupTool for DokuWiki](https://github.com/tatewake/dokuwiki-plugin-backup) that backups made (into `:wiki:backup`) are being auto-added to the `media_attic` directory as well.

The bigger issue here is that when a user downloads their backup and deletes the file from the media manager, the `media_attic` file remains…

…but of course for some users the backup will also contain the contents of `media_attic`, so every backup made by these users will then contain previous backups made.

And generally speaking, backup files will always be named by the timestamp at which they were generated, so there's no point to having a "revision" in `media_attic` since they will all have different filenames.

My guess is that there was some change that was made within DokuWiki to auto-backup files that were directly uploaded (or in the plugin's case, "generated") by the user outside of the normal "media manager" method of uploading. I don't know when this change was made, however I suspect this wasn't always the behavior.

Can I recommend that we have one of these solutions:

 * A user-configurable field under `mediarevisions` allowing for directories or file pattern to skip
 * A user-configurable field to not backup media files in `:wiki:backup`
 * Silently not backup media files in `:wiki:backup` when making media file backups into `media_attic`

Any of these solutions will fix the issue for users of the BackupTool plugin.

Thank you.

**Comment by splitbrain** [comment]
No, externally created media files do not generate attic versions. Only if you were to upload a new version of the same file through the media manager would be an attic file be created.

The way the backup plugin saves files is the same as if it were done externally.

The backup plugin also ensures to not backup it's own files: https://github.com/tatewake/dokuwiki-plugin-backup/blob/master/admin.php#L387-L390

So I don't know what your user is experiencing but the given info makes no sense.

**Comment by tatewake** [comment]
Hi @splitbrain ,

So what I didn't mention initially was that I was able to reproduce the issue, which is why I opened this issue to begin with…

You are correct, and my theory was wrong. DW does not automatically create the `media_attic` versions, and of course the backup plugin does not backup it's own files (written nearly 14 years ago, I believe, so I had long forgotten this.)

However, I wanted to verify, since I was able to reproduce this one…

So I reproduced this issue again, and the actual issue appears to be that the act of "deleting" a backup file from `:wiki:backup` via the "Media Manager" automatically creates a backup of the file into `media_attic` before actually deleting it from `media`… and I don't see a way to delete this new "media attic backup" without actually SSH'ing into my server and manually deleting it.

Is there a way to permanently delete a file from DokuWiki (thus ensuring there's no `media_attic` "backup" of a file)? Or some other existing solution I'm not aware of…?

If not, perhaps there should be some functionality to ensure a deleted file's old revisions can be permanently deleted somehow? I don't see a method of doing so from the UI.

Best regards

**Comment by splitbrain** [comment]
I see. That actually makes a lot more sense. I still think this should be solved in the backup plugin in two ways:

* ignore any attic files for the configured backup namespace
* have an option to automatically delete old backups when creating new backups (circumventing the creation of attic files) based on either number of backups (keep last 5) or age (delete all older than 5 weeks)

**Comment by tatewake** [comment]
Hi Andi,

Yes, I will probably implement both of those items then.

I might suggest adding some option in DokuWiki of permanently deleting orphaned files whose revisions 
 are otherwise left in `media_attic`, but I'll leave that decision to you.

Feel free to close the issue otherwise.

Best regards
