### ISSUE TITLE
Page called 0 creates some problems

### ISSUE THREAD

**Issue by tormec** [splitbrain/dokuwiki#3037]
Inside `foo:start` create the links:
- `[[foo:0]]`: points to `foo:0` but it takes the name `foo`
- `[[0]]`: points to `foo:0` but it takes the name `start`

Also note that, after visiting `foo:0`, the **Trace** show the name `foo` (instead of `0`).

**Comment by phy25** [comment]
What version do you use? The latest release or master branch?

**Comment by tormec** [comment]
> The latest release or master branch?
The latest release Release 2018-04-22b "Greebo" (downloaded months ago)

**Comment by phy25** [comment]
Could you try the master branch, because of #2610 and #2724?

**Comment by tormec** [comment]
Tested the master branch and confirm the issue.
