### ISSUE TITLE
Dokuwiki error “A newer version exists” every time a page is edited

### ISSUE THREAD

**Issue by jakob1111** [splitbrain/dokuwiki#3043]
I moved [my dokuwiki site](https://physicstravelguide.com/) to a new server. Now the following error appears whenever a user makes an edit to a page:

> A newer version exists
> 
> A newer version of the document you edited exists. This happens when another user changed the document while you were editing it.
> 
> Examine the differences shown below thoroughly, then decide which version to keep. If you choose save, your version will be saved. Hit cancel to keep the current version.
> 

The error appears every time and thus there can't be someone else editing the pages. Once I edited a page, saved it despite the error, the error no longer appears when I try to edit the page again.

So one solution would be to go through all pages, do some minor edit, and save them manually. But since the instance is quite large this is not really a viable option.

**Comment by phy25** [comment]
https://www.dokuwiki.org/tips:fixmtime

**Comment by jakob1111** [comment]
That solved my problem. Thanks!
