### ISSUE TITLE
Personnalize translation doesn't work on farm

### ISSUE THREAD

**Issue by Zatalyz** [splitbrain/dokuwiki#3051]
I'd like to use custom strings for translation, as specified in https://www.dokuwiki.org/start?id=localization&go=%E2%86%92#changing_some_localized_texts_and_strings_in_your_installation

I have a wiki farm, manually installed (the structure is from before the plugin, and the farm work well otherwise, for a long time.). Following the instructions, I create a translation in conf/lang/fr/lang.php. It works on the farmer (I have my custom strings), but not on the animals. On animals, I have the core translation.

I purged the cache (?purge=true) and touch on the local.php files. The rights on folders and files look good (owner: www-data). It's as if the animals didn't know that the "lang" folder has been added in the farmer's "conf".

I don't know what's wrong with the animals, whereas it works on the farmer. Do you have any idea ?

**Comment by phy25** [comment]
Please try setting up your preload file with `$config_cascade['lang']['core']`:

https://github.com/splitbrain/dokuwiki/blob/e7be4021bb9b156be34aac483c6fec89f9db8174/inc/config_cascade.php#L83-L87

If it's not working, you need to post your preload config or we will never have an idea.

**Comment by Zatalyz** [comment]
Thanks a lot, you put me on the track of resolution. 

I added this in the preload.php
```
$config_cascade['lang'] = array(
             'core'      => array('/var/www/dokuwiki/conf/lang/'), 
             'plugin'    => array('/var/www/dokuwiki/conf/plugin_lang/'), 
             'template'  => array('/var/www/dokuwiki/conf/template_lang/') 
);
```
Absolute links are necessary for this to work in animals as well. There may be a more elegant solution... but this works.

**Comment by phy25** [comment]
Well there is a default in config_cascade.php, but when you are setting up a farm you have to override it yourself. Since you are able to make it I am closing this issue.
