### ISSUE TITLE
Your PHP seems to miss SSL support. Downloading will not work for many DokuWiki extensions.

### ISSUE THREAD

**Issue by remixcastle** [splitbrain/dokuwiki#3052]
Dear, Administrator 

I used doku - wiki in over a year, and nearly here, my page has some problem to this one but i don''t know how to fix it.  Please help me to solve this problem step by step, Thanks. 

![image](https://user-images.githubusercontent.com/32756795/79725294-354bd180-8313-11ea-9370-f8b0c9b7582c.png)

**Comment by splitbrain** [comment]
The error message is clear, you need to enable the openssl extension for your PHP. If this is a hosted environment contact your hoster about it.
