### ISSUE TITLE
Is the php mail function needed to install?

### ISSUE THREAD

**Issue by turnermm** [splitbrain/dokuwiki#3053]
An issue came up on the forum, where a user couldn't install because the hosting provider had removed access to the php mail function.  Dokuwiki initially does not seem to need that function to install and the user can then install the smtp plugin.

**Comment by splitbrain** [comment]
Hmm good question. The installer tries to check for functions we later simply assume to be available. So, yes `mail` isn't needed during the install process but we will call it later on assuming that it's there. This means the first time somewhere a mail is sent, the process will crash. Of course this could be avoided using the smtp plugin, but a user may not know that.

So to properly solve this, we'd need to check for the availability of the `mail` function before using it (and showing the appropriate error message). Then we could remove it from the requirements in the installer.

PRs welcome

**Comment by turnermm** [comment]
OK.  I'll look at it.

**Comment by turnermm** [comment]
Is it enough to just handle it in the installer by notifying the user that a plugin is required and allowing the install to go forward?

**Comment by phy25** [comment]
> Is it enough to just handle it in the installer by notifying the user that a plugin is required and allowing the install to go forward?

Probably no, or it will take a long time for the user to finally realize that the mail function is not working.

**Comment by Klap-in** [comment]
There appears to be two locations in DokuWiki's core code that use `@mail()`
Codesearch: [@mail](https://codesearch.dokuwiki.org/search?project=dokuwiki&project=plugin&project=template&q=%22%40mail%22+-%22%40mail%40%22+-%22%40mail.%22&defs=&refs=&path=-lang&hist=&type=php  )

And bit wider: to catch `mail()` as well: 
Codesearch:  [refs:mail](https://codesearch.dokuwiki.org/search?project=dokuwiki&project=plugin&project=template&q=&defs=&refs=mail&path=-lang&hist=&type=php)
