### ISSUE TITLE
Links with parenthesis '(' ')' don't work

### ISSUE THREAD

**Issue by louwers** [splitbrain/dokuwiki#3054]
To reproduce:

Put this in a page:

```
https://en.wikipedia.org/wiki/San_Francisco_(disambiguation)
https://en.wikipedia.org/wiki/San_Francisco
```

You can click on the second link, but the first will get cut off and won't work.

**Comment by splitbrain** [comment]
Use the link syntax for pages with special chars in it.

**Comment by louwers** [comment]
Makes sense, thanks.
