### ISSUE TITLE
Is the site down?

### ISSUE THREAD

**Issue by lizat** [splitbrain/dokuwiki#3057]
Sorry to contact like this but no other option.

I can't log into:

https://forum.dokuwiki.org/ reported error is 'UNB Error: Cannot connect to database. Check the error log for details.'

https://www.dokuwiki.org/, several errors reported: https://www.dokuwiki.org/

Thank you

**Comment by splitbrain** [comment]
see https://twitter.com/dokuwiki/status/1253574176411193345
