### ISSUE TITLE
How to find the Access Control List file to move to new one

### ISSUE THREAD

**Issue by remixcastle** [splitbrain/dokuwiki#3072]
Hi Administrator, 

I am moving the old doku wiki to the new one because the problem of old version of PHP, but unfortunately, it takes a lot of time to configurate the Access Control List, so Are there any chance to get the Access Control List file from the old doku wiki move to the new one. 

Thanks

**Comment by phy25** [comment]
> ACLs can be enabled in the installer and an initial ACL policy is set there as well. To manually enable ACLs, switch on the useacl option and create a copy of the example files '​'​conf/​acl.auth.php.dist'​'​ and '​'​conf/​users.auth.php.dist'​'.​ Rename the files to '​'​conf/​acl.auth.php'​'​ and '​'​conf/​users.auth.php'​'​ respectively.
>
> https://www.dokuwiki.org/acl

> If you want to save some space you should at least backup the following directories...
>
> https://www.dokuwiki.org/faq:backup

So basically you want to back up data in `conf/` and `data/`.

I am closing this but feel free to reply if you have further questions. Next time please make use of https://forum.dokuwiki.org or mailing list (https://www.dokuwiki.org/mailinglist).
