### ISSUE TITLE
[Wiki Feature Request] A list of newly added plugins

### ISSUE THREAD

**Issue by Michaelsy** [splitbrain/dokuwiki#3073]
It would be nice if the [plugin search page](https://www.dokuwiki.org/plugins) offers the option to list newly added plugins. 

That means all plugins are listed, sorted by their first date entrys in "Old Revisions". 

(Of course with the templates this would be helpful also.)

**Comment by phy25** [comment]
A workaround which show every update: https://www.dokuwiki.org/plugin:start?do=recent

**Comment by Michaelsy** [comment]
Thank you for your answer, but ...

...my motivation is: I would like to have the option to check for new plugins every few weeks or months. I assume this is a feature that would be useful for many DokuWiki users. Especially for those who offer regular support in the forum. And also for many who maintain and extend their wikis in the long run.

The workaround you offered is unfortunately not applicable for this purpose.

And I don't see any other practicable way to keep up to date on the new plugins offered. At least not with a reasonable effort.

Another variant would be to automatically store the creation date in the plugin's data record when a plugin wiki page is new created. Plugins that do not have this date do not necessarily have to appear on the list.

**Comment by phy25** [comment]
Well I think what you want is "recently created *only*" v.s. "recently updated + created" right? You might be able to make use of feed.php but the one on dokuwiki.org does not allow customizing the filter on it.

https://github.com/splitbrain/dokuwiki-plugin-pluginrepo might be a better place to raise the issue and implement it, though I know there is more attention here.

**Comment by Michaelsy** [comment]
> Well I think what you want is "recently created _only_" v.s. "recently updated + created" right?

Yes, that's almost the same what I mean:  A list of (more or less) all plugins, sorted by creation date, recent date at the top.

> https://github.com/splitbrain/dokuwiki-plugin-pluginrepo might be a better place to raise the issue and implement it, though I know there is more attention here.

Ok, I had forgotten that this was done with a plugin.

**Comment by Klap-in** [comment]
The repository is the place to implement this kind of features, but the repository plugin doesn't store this info at the moment.

**Comment by Michaelsy** [comment]
This issue [reopened here](https://github.com/splitbrain/dokuwiki-plugin-pluginrepo/issues/129).
