### ISSUE TITLE
'&' character tripping-up acronym recognition?

### ISSUE THREAD

**Issue by ryliejamesthomas** [splitbrain/dokuwiki#3074]
One of the acronyms I have defined in my wiki is 'OH&S', but it doesn't get recognised, I assume because of the ampersand. Every other one I have defined works just fine.

I'm on `2018-04-22b "Greebo"`

**Comment by Michaelsy** [comment]
I tried to reproduce your problem, but I failed.

Maybe your effect has something to do with the fact that the HTML representation of your acronym  is this: `OH&amp;S`

I suspect that this form (entered via the clipboard) is on the wiki page and/or in the acronyms config  file.

You should check this via a plain text editor that is not somehow operated via a browser.

**Comment by ryliejamesthomas** [comment]
It... seems to actually be working fine today.

Maybe I hadn't refreshed the cache or something, or my theme was out of sync--

Thanks for taking the time to test <3
