### ISSUE TITLE
Documentation : Security page Lighttpd item

### ISSUE THREAD

**Issue by zounp** [splitbrain/dokuwiki#3076]
While installing Dokuwiki on a lighttpd server version lighttpd/1.4.53 (ssl) and understanding the information on https://www.dokuwiki.org/security#deny_directory_access_in_lighttpd I rewrote the "Deny Directory Access in Lighttpd" section" to: see below for my proposal.

"mod_rewrite" is not present any more in /etc/lighttpd/lighttpd.conf . It needs to be added.
Form what I understand it has to be added in the server.modules +=  (not the server.modules =  (without the plus sign)) section. Correct me if I am wrong.

My proposal:
==== Deny Directory Access in Lighttpd ====
Using a URL re-write you can deny access to the above directories. In your /etc/lighttpd/lighttpd.conf file adding the following URL ;;[[https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModRewrite|rewrite rule]]” should be sufficient to keep people out. It suppose your Dokuwiki files are installed under http://yourwebsite.tld/dokuwiki/. 
  url.rewrite-once = ( "^/dokuwiki/(data|conf|bin|inc|vendor)/+.*" => "/nonexistentfolder" )
Don't forget to uncomment or add “mod_rewrite” in the server.modules section of /etc/lighttpd/lighttpd.conf. It should look like this:
  server.modules += (
       "mod_compress",
       "mod_dirlisting",
       "mod_staticfile",
       "mod_rewrite",
  )
Unfortunately it does not keep people out who are using Vivaldi and probably other chromium based browsers. When combined with “[[https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModAccess|mod_access]]” it does keep people out. More mod_access examples are available [[https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModAccess|here]].\\
In **/etc/lighttpd/lighttpd.conf** "mod_access" should be in the "server.modules = (" section. Also add
  $HTTP["url"] =~ "^/dokuwiki/(data|conf|bin|inc|vendor)/+.*" {
      url.access-deny = ("")
  }
to /etc/lighttpd/lighttpd.conf.\\
Restart lighttpd with systemctl reload-or-restart lighttpd and check the status with systemctl status  lighttpd

**Comment by phy25** [comment]
Thank you for your contribution. Please go ahead to edit wiki pages. Those don't have a review process.

**Comment by zounp** [comment]
:-)
Ok. Done
