### ISSUE TITLE
_ft_pageLookup not work with capital letters in NS or pID

### ISSUE THREAD

**Issue by asereq** [splitbrain/dokuwiki#3077]
The function _ft_pageLookup not work properly if the wiki has capital letters in some namespace or page ID. In fact is necessary to use the function strtolower() in the first argument of the strpos function, lines 278 and 293 of inc/fulltext.php

Sorry if it is not the way to report this, maybe I can change the file directly but github says I don't have enough permissions.

Thanks for develop a great project!

**Comment by michitux** [comment]
Capital letters in namespaces and IDs are not supported by DokuWiki and there is no way to create such pages without modifying DokuWiki's code. Therefore, this is not a bug.

**Comment by asereq** [comment]
I'm not understanding, I'm not change the code, only set a configuration: https://www.dokuwiki.org/config:camelcase My wiki has a lot of uppercase letters; ¿will be disabled in future releases?

**Comment by michitux** [comment]
Regardless of that setting, all page IDs in DokuWiki are only using lowercase letters, as far as I know this has always been the case. What is the problem you are trying to solve here?

**Comment by asereq** [comment]
When the camelcase setting is enable, there is not impediment to create pages or namespaces with capital letters. Then, when there is a namespace Foo and one try to use the function _ft_pageLookup to find a page inside Foo, te result is null. Why? Because the ns for the search is converted to lowercase, so that never match with Foo. This is why I suggest the use of strtolower() function to convert the existing ID at the moment of the compare. (See my first comment).

Why I want that? because the struct plugin, when a Page field is configured to restrict the search to a namespace with Uppercases, the autocomplete doesn't work.

If you think the page ids and namespaces must be in lowercase, it's ok, but I am not finding that in the documentation. If you think the problem is with the struct plugin, it's also ok, I can use the forum or the plugin issues.

I hope my explication be clear. Thanks again.

**Comment by phy25** [comment]
Unfortuntately I am not a struct user, so I am not sure how your issue happens.

> When the camelcase setting is enable, there is not impediment to create pages or namespaces with capital letters.

Not sure how that works for you, but by enabling camelcase, the behavior change in DokuWiki should only be parsing additional links with camelcase format, rather than actually allowing uppercase in the ID.

> If you think the page ids and namespaces must be in lowercase, it's ok, but I am not finding that in the documentation.

https://www.dokuwiki.org/pagename

**Comment by asereq** [comment]
Ok, you are right, I did a hack following that page and I had forgotten that, sorry for my mistake.
Maybe I could add another hack to fix that but it's clear the spirit of dokuwiki is to have pagenames in lowercase. In conclusion, I have to change the names to fit the pagenames rules.
Thank you very much for your time!
