### ISSUE TITLE
install.php script disallows user names allowed by the user manager

### ISSUE THREAD

**Issue by bwalzer866** [splitbrain/dokuwiki#3080]
In particular a user name of the form jb.smith is rejected by the install script because of the embedded period. Adding the same user with the user manager works as it does not remove the period. Just to be clear, I think that having periods in user names is OK and can sometimes be helpful so I am suggesting that the install script be made consistent with the user manager.

**Comment by phy25** [comment]
Well... This is install.php:

https://github.com/splitbrain/dokuwiki/blob/3f6872b1fc0e676dafffb7488df32f2425bbd29f/install.php#L303

`authplain` uses cleanID, which is actually quite complex:

https://github.com/splitbrain/dokuwiki/blob/a405cfffe056fd9afe95e457fd8130f5c1b194d5/inc/pageutils.php#L114

Probably we can reuse `cleanID` in install.php. I am not sure if plugins are available during installation, but I think just by using internal function should be enough.
