### ISSUE TITLE
some php errors which possibly popped up after php upgrade from 7.0 to 7.3

### ISSUE THREAD

**Issue by df8oe** [splitbrain/dokuwiki#3081]
Hi,
at the weekend I switched my server from php7.0 to 7.3. I am not sure if these error messages started wit this upgrade or they were present all the time - in fact I watched the error logs since then intensively ;)

1)
[Tue May 19 16:09:45.623768 2020] [proxy_fcgi:error] [pid 13623] [client xyzybc] AH01071: Got error 'PHP message: PHP Warning:  Declaration of syntax_plugin_latex_common::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /var/www/wiki/lib/plugins/latex/latexinc.php on line 157PHP message: PHP Warning:  Declaration of syntax_plugin_latex_eqnarray::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/wiki/lib/plugins/latex/syntax/eqnarray.php on line 5PHP message: PHP Warning:  Declaration of syntax_plugin_latex_equationstar::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/wiki/lib/plugins/latex/syntax/equationstar.php on line 33PHP message: PHP Warning:  Declaration of syntax_plugin_latex_displaymath::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/wiki/lib/plugins/latex/syntax/displaymath.php on line 33PHP message: PHP Warning:  Declaration of syntax_plugin_latex_eqnarraystar::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/wiki/lib/plugins/latex/syntax/eqnarraystar.php on line 33PHP message: PHP Warning:  Declaration of syntax_plugin_latex_dollar::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/wiki/lib/plugins/latex/syntax/dollar.php on line 28PHP message: PHP Warning:  Declaration of syntax_plugin_latex_latex::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/wiki/lib/plugins/latex/syntax/latex.php on line 39PHP message: PHP Warning:  Declaration of syntax_plugin_latex_ddollar::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/wiki/lib/plugins/latex/syntax/ddollar.php on line 33PHP message: PHP Warning:  Declaration of syntax_plugin_latex_equation::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/wiki/lib/plugins/latex/syntax/equation.php on line 33', referer: https://www.google.de

2)
[Tue May 19 16:02:32.827645 2020] [proxy_fcgi:error] [pid 12386] [client ybcxyz] AH01071: Got error 'PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/wiki/lib/plugins/discussion/action.php on line 425', referer: https://www.google.de

**Comment by phy25** [comment]
Looks like those errors have something to do with latex plugin and discussion plugin. Could you upgrade those plugins and create tickets in their issue tracker if it's still happening?

The latex one is interesting though, not sure we can do anything about it but it's just PHP complaining about the new type annotation.

**Comment by df8oe** [comment]
I have upgraded the plugins already. Yes - only complaining. But complaining often is followed by ERRORs ;) I will do as you propose.

**Comment by phy25** [comment]
Sorry didn't read this carefully before. Similar to #2377. PHP is making some warnings more obvious. The plugins need to be updated.

If you want to fix this yourself you can consult https://stackoverflow.com/questions/36079651/silence-declaration-should-be-compatible-warnings-in-php-7
