### ISSUE TITLE
Media.php possibly broken in latest release when using rewrite rules on nginx

### ISSUE THREAD

**Issue by edgepacket** [splitbrain/dokuwiki#3086]
Using nginx and Git 2020-05-22 we are having issues with jpg files when the rewrite rule is set to htaccess or dokuwiki internal

Please see the forum post for further
https://forum.dokuwiki.org/d/17799-rewrite-issues-with-images-using-nginx

https://host/start?image=something.jpg&ns=&tab_details=view&do=media
and the direct link
https:/host/_media/something.jpg 

do not retrieve the image

2020/05/24 01:05:34 [error] 32013#0: *30 open() "/u01/web/wiki/dw/_media/example-image.jpg" failed (2: No such file or directory), client: 1.1.1, server: wiki.example.com, request: "GET /_media/example-image.jpg?t=1590205103&w=499&h=170&tok=d58095 HTTP/1.1", host: "wiki.example.com", referrer: "https://wiki.example.com/start?do=media&ns="

This file does not exist /u01/web/wiki/dw/_media/example-image.jpg

This file does exist   /u01/web/wiki/dw/data/media/example-image.jpg

NGINX configuration --- we used the example from the rewrite page

location / {
 try_files $uri $uri/ @dokuwiki;
 }

location @dokuwiki {
 rewrite ^/_media/(.*) /lib/exe/fetch.php?media=$1 last;
 rewrite ^/_detail/(.*) /lib/exe/detail.php?media=$1 last;
 rewrite ^/_export/([^/]+)/(.*) /doku.php?do=export_$1&id=$2 last;
 rewrite ^/(?!lib/)(.*) /doku.php?id=$1&$args last;
 }

Our PHP rules are
location ~ \.php$ {
add_header X-Robots-Tag "noindex, nofollow";
 fastcgi_pass 127.0.0.1:9000;
 if (!-f $request_filename) { return 404; }
  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  fastcgi_param REDIRECT_STATUS 200;
  include fastcgi_params;
  fastcgi_intercept_errors off;
  fastcgi_buffer_size 16k;
  fastcgi_buffers 4 16k;

**Comment by phy25** [comment]
```
2020/05/24 01:05:34 [error] 32013#0: *30 open() "/u01/web/wiki/dw/_media/example-image.jpg" failed (2: No such file or directory), client: 1.1.1, server: wiki.example.com, request: "GET /_media/example-image.jpg?t=1590205103&w=499&h=170&tok=d58095 HTTP/1.1", host: "wiki.example.com", referrer: "https://wiki.example.com/start?do=media&ns="
```

Looks like your NGINX is not redirecting request to DokuWiki at all, so it's not a DokuWiki issue. Let's continue the discussion on the forum.
