### ISSUE TITLE
[question] nginx gzip_static on;

### ISSUE THREAD

**Issue by xaozai** [splitbrain/dokuwiki#3087]
Please tell me how to configure dokuwiki to use the nginx [gzip_static on](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html) directive. Is it possible? And if possible, do I need to compress *. less files?

**Comment by phy25** [comment]
DokuWiki serves the file for you by PHP. The "static" means the gzipped files are those served directly by NGINX.

Please see https://www.dokuwiki.org/config:gzip_output

**Comment by xaozai** [comment]
Please clarify if I understood correctly that gzip_static on (nginx) and mod_gzip_static_suffix (apache) do not make sense in the case of dokuwiki?

And when using the gzip_output = true setting, is traffic compressed every time it is requested?

**Comment by phy25** [comment]
I am not a server configuration expert so I am not quite sure. If you look into those requests you should see that those files are served by PHP, so you should find a solution that processes PHP responses.

See also https://www.dokuwiki.org/config:gzip_output
