### ISSUE TITLE
hierarchical breadcrumbs are gone after upgrade to Hogfather

### ISSUE THREAD

**Issue by bradbulger** [splitbrain/dokuwiki#3114]
It is showing spaces for the parents but no page names, so I see something like

You are here: » » create_new_user

I can add, the links are there, but have no text.

**Comment by splitbrain** [comment]
@phy25 I think this was somehow introduced by  b65274e as it seems to be the only code that has changed in the path of execution for `tpl_youarehere`.

`$p` used to be compared loosely to `false` which made it true for empty strings. The breadcrumbs code passes IDs ending with a colon, so `noNS` always returns an empty string, which consequently is returned...

**Comment by giterlizzi** [comment]
Confirm the resolution with #3116 PR

Thanks!
