### ISSUE TITLE
update to Hogfather causes admin page to be empty

### ISSUE THREAD

**Issue by tracing-home** [splitbrain/dokuwiki#3118]
Tried copying the archive over the old version, and using the current upgrade plugin. The content is readable, the admin page shows headers but no content. Permissions were set. Downgrading from the backup removes the error.

apache error.log shows this after every access to the admin page:

`
[php7:error] [pid 24486] [client 127.0.0.1:49616] PHP Fatal error:  Cannot declare class HTTPClient, because the name is already in use in /var/www/dokuwiki/inc/HTTPClient.php on line 29, referer: http://localhost
`
```
php --version
PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )/start
```

**Comment by JohannesKleine** [comment]
Do you use the indexmenu plugin? Have a look at https://github.com/samuelet/indexmenu/issues/214

**Comment by tracing-home** [comment]
Yes, I have the indexmenu plugin installed.

I just ran the update of the plugin (version 2020-06-02) then ran Wiki 
upgrade from the admin menu -- all is fine


Thanks! That is my solution
