### ISSUE TITLE
[Plugin] QC Quality Check Plugin Compatibility Issue with Hogfather

### ISSUE THREAD

**Issue by StarArmy** [splitbrain/dokuwiki#3119]
When testing Hogfather I found that the QC plugin's contents are no longer displayed on pages (they do not load) after Dokuwiki was updated from Greebo, The template I was using was essentially Adoradark.

**Comment by StarArmy** [comment]
Is this what we need? https://github.com/cosmocode/qc/pull/42

**Comment by phy25** [comment]
Not sure, but if you look at its issues board there are also major changes that breaks the plugin (the Fulltext one - but it probably won't arrive at Hugfather)

**Comment by StarArmy** [comment]
Yeah, I just tested my fix on my site and it still needs work (simply updating the location of the parser to Parsing did not make the plugin work again.

**Comment by StarArmy** [comment]
Ah, I see https://github.com/cosmocode/qc/issues/41

**Comment by phy25** [comment]
I am going to close this issue because the plugin should work fine with Hogfather now after the plugin fix.
