### ISSUE TITLE
JSINFO not defined

### ISSUE THREAD

**Issue by bradbulger** [splitbrain/dokuwiki#3120]
I am seeing Javascript errors - "Uncaught ReferenceError: JSINFO is not defined". The result was that the editing toolbar stopped after the header buttons. The errors were coming from lib/scripts/linkwiz.js and a script in the Move plugin. When I edited linkwiz.js and removed the JSINFO references, the toolbar came back. I assume the Move plugin won't work, I haven't tried it.

I get multiple errors about refusing to execute inline scripts, I don't know if that is related.

I am seeing this in Greebo and Hogfather.

**Comment by phy25** [comment]
Any plugins? What's your environment?

**Comment by bradbulger** [comment]
I have several plugins, yes. This was working in the past with all of them. I don't know what you mean by "environment", this is in Chrome and Firefox.

**Comment by bradbulger** [comment]
Firefox is giving an error I hadn't seen in Chrome


<script type="text/javascript">/*<![CDATA[*/var NS='';var SIG= --- //[[bradford.bulger@nasa.gov|bradb]] 2020/06/02 12:10//;var JSINFO = {"move_renameokay":false,"useslash":0,"userewrite":1,"sepchar":"_","id":"start","namespace":"","ACT":"edit","useHeadingNavigation":0,"useHeadingContent":0};
/*!]]>*/</script>

**Comment by phy25** [comment]
Forgot to ask what template you are using. PHP version? Apache/NGINX?

**Comment by bradbulger** [comment]
Putting the value of SIG in quotes in inc/template.php fixed the problem on my production server, in Chrome and in Firefox. I can confirm that undoing that change causes the problem to return (the toolbar buttons are missing again).

I don't quite know why it doesn't suffice for my local installation. I had upgraded to Hogfather and then had to back that out because of bugs. I hadn't noticed any problems, and the code is the same on both installations. But there may be caching issues, I don't know.


The default dokuwiki template as far I as know. It's the only choice for that value in the admin screen. This is on an Apache webserver. I see it on my local installation and on our production system.

**Comment by bradbulger** [comment]
OK, the local site is failing in Firefox still with the fix because of inline script errors:
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
So I assume there is an Apache setting that is different, or that the lack of a valid certificate is related.

**Comment by bradbulger** [comment]
I added these lines into js_out() in lib/exe/js.php and the JSINFO errors stop on the local installation.

`    global $JSINFO;
    jsinfo();
    print 'var JSINFO = ' . json_encode($JSINFO).';' . "\n";
`

**Comment by splitbrain** [comment]
What is your content security policy? Eg. what headers is your web server sending? Is it public? Can we have a look?

**Comment by bradbulger** [comment]
The public site worked after fixing the syntax error in the definition of SIG. I don't know how to see what the content security policy is in either Chrome or Firefox.

**Comment by bradbulger** [comment]
from wget

Content-Security-Policy: default-src 'self'; frame-ancestors 'none'; style-src 'self' 'unsafe-inline'; script-src 'self'; img-src 'self' 'self' data:

**Comment by bradbulger** [comment]
This is in our .htaccess file

```
<IfModule mod_headers.c>
Header set Content-Security-Policy "default-src 'self'; media-src *; img-src * 'self' data:; script-src 'self' 'unsafe-inline' ; style-src 'self' 'unsafe-inline';"
</IfModule>
```

**Comment by splitbrain** [comment]
Okay, there seem to be two independent issues here. Let's focus on the signature thing.

The actual problem is that you say you had the following in your page source:

```
var SIG= --- //[[bradford.bulger@nasa.gov|bradb]] 2020/06/02 12:10//;
```

Which is indeed wrong as it is missing the quotes. Compare to my output:

```
var SIG=" --- \/\/[[andi@splitbrain.org|Andreas Gohr]] 2020\/06\/02 22:19\/\/";
```
The output is generated in https://github.com/splitbrain/dokuwiki/blob/0884c254723c9fa99e70acf920c59d7f3dbcab55/inc/template.php#L341

And that `toolbar_signature` uses `json_encode`: https://github.com/splitbrain/dokuwiki/blob/0884c254723c9fa99e70acf920c59d7f3dbcab55/inc/toolbar.php#L274

It should enclose a string in double quotes. Can you check that your code is the same? Because I have no idea why this should be different for you.

**Comment by bradbulger** [comment]
and that's the thing - mod_headers was not enabled on the local installation

**Comment by bradbulger** [comment]
in Greebo, there is no call to json_encode() in toolbar_signature(). I can't swear about the past but I would have noticed if the toolbar had been gone like this, I feel pretty sure.

**Comment by splitbrain** [comment]
`json_encode` is there since hotfix c for Greebo and you said you're seeing the same in Hogfather!?

**Comment by bradbulger** [comment]
that's where there are two issues, as you said. I was seeing it locally in Hogfather but that was probably that mod_headers was not enabled and so the security policy was not being set to allow unsafe-inline. i hadn't noticed the syntax complaint about SIG until i looked at the live site in Firefox. the VERSION file there says 2018-04-22c "Greebo" fwiw.

**Comment by bradbulger** [comment]
Prior to this recent attempt to update and then roll back to Greebo, we had been running 22b, not 22c. So my guess at this point is that I have a munged version of 22c somehow, that has the template.php line expecting the encoded value but not the toolbar.php to create it. I haven't confirmed that but it seems likely.

**Comment by phy25** [comment]
Might be related to #3109. (Haven't read the latest comments here yet, sorry)

**Comment by bradbulger** [comment]
That may be. I rebuilt it from a fresh full copy of 22c and everything was as it should be.

So I think that resolves this issue:
- a bad copy of Greebo was causing a syntax error in the line that defined JSINFO
- my local installation would not execute that line in any case because the browser defaulted to not running inline Javascript, and my Content-Security-Policy header was not being set by my .htaccess file because I didn't have mod_headers installed in Apache, which is why I was seeing errors in Hogfather as well

Thanks all!
