### ISSUE TITLE
Handle disabled parse_ini_file function

### ISSUE THREAD

**Issue by juangacovas** [splitbrain/dokuwiki#3124]
I've found a hosting that disables the function "parse_ini_file", therefore the file "style.ini" cannot be loaded on templates (I found 3 calls in the code). This is done through "disabled_functions" directive on php.ini

In this situation the following warning gets logged/showed:
Warning: parse_ini_file() has been disabled for security reasons.

But DokuWiki goes ahead with it (an empty array for the INI file settings) and the page styles get pretty bad with no other warning/error that could prevent people to make it work.

I'm trying to get my hosting enabling the function, but a solution could be also use a polyfill function in case "parse_ini_file" doesn't work (I found one that had to hack a bit, and it works, but is less than ideal).

**Comment by splitbrain** [comment]
The installer already checks for the existence of the method. See also https://www.dokuwiki.org/tips:disabled_functions

**Comment by juangacovas** [comment]
Thanks! Just wanted to note that my frustration came when migrating an already installed dokuwiki, hence the opportunity to improve that. Kind regards.

**Comment by phy25** [comment]
The `parse_ini_check` installer check was there 14 years ago https://github.com/splitbrain/dokuwiki/blame/3f6872b1fc0e676dafffb7488df32f2425bbd29f/install.php#L585 so I agree we don't quite have the interest to fix it.
