### ISSUE TITLE
Plugin Codebutton2 crashes whole wiki

### ISSUE THREAD

**Issue by benkees** [splitbrain/dokuwiki#3126]
After upgrading from greebo to hogfather my browser just showed a blanc page with zero byte.
Apache logs showed

'PHP message: PHP Fatal error:  Declaration of action_plugin_codebutton2::register(&$controller) must be compatible with dokuwiki\\Extension\\ActionPlugin::register(Doku_Event_Handler $controller) in /var/www/dokuwiki/www/dokuwiki-2018-04-22b/lib/plugins/codebutton2/action.php on line 0', referer: https://wiki.MYSERVER.com/start?do=admin&page=extension&tab=search&q=code%20button

after deleting "/lib/plugins/codebutton2"  dokuwiki was available again. Reinstalling codebutton2 with Plugin Manager leaded to the same problem again.

The Plugin shouldn't be available in hogfather. Maybe also there could be a mechanism, that a plugin cannot tear down the whole interface or that you don't need access to filesystem to get an error message.

**Comment by splitbrain** [comment]
please report this at the plugin's bug tracker.

**Comment by benkees** [comment]
@splitbrain 
The Plugin's bugtracker is dead, but the plugin is still available in the plugin manager of hogfather and crashes the wiki without warning or error message. So I guess the possibility to install it there should be disabled.

**Comment by phy25** [comment]
You can mark it as incompatible or deprecated on https://www.dokuwiki.org/plugin:codebutton2
