### ISSUE TITLE
hidden plugin inconsistently working with upgrade, including RC2

### ISSUE THREAD

**Issue by andylynchpe** [splitbrain/dokuwiki#3130]
I have pages which utilize the hidden plugin. On maybe 90% of my pages, it works correctly, but the remainder will randomly display all of the text that's supposed to be hidden.

Refreshing does not fix it (including shift or ctrl + F5).

If I edit the page in any way and save it, then the hidden plugin will work as expected again, but eventually the page may revert to displaying the full contents of the hidden text.

Edit: In case it's important, all of my hidden text is enclosed in nowiki tags. The nowiki functionality is working as expected.

**Comment by phy25** [comment]
Could you create an issue on https://github.com/gturri/hidden/issues ?

**Comment by andylynchpe** [comment]
Just did. Thanks.
