### ISSUE TITLE
Sitemap XML is broken

### ISSUE THREAD

**Issue by nfriedli** [splitbrain/dokuwiki#3134]
In my "Hogfather" RC2 relsease, the automatic `sitemap.xml?do=sitemap` seems to be broken.
My DokuWiki is vanilla, no hacks, no extra plugins.

```
Fatal error:  Uncaught Error: Call to undefined method dokuwiki\Action\Sitemap::getFilePath() in [...]/inc/Action/Sitemap.php:35

Stack trace:
#0 [...]/inc/ActionRouter.php(83): dokuwiki\Action\Sitemap-&gt;preProcess()
#1 [...]/inc/ActionRouter.php(48): dokuwiki\ActionRouter-&gt;setupAction('sitemap')
#2 [...]/inc/ActionRouter.php(60): dokuwiki\ActionRouter-&gt;__construct()
#3 [...]/inc/actions.php(16): dokuwiki\ActionRouter::getInstance(true)
#4 [...]/doku.php(122): act_dispatch()
#5 {main} thrown in [...]/inc/Action/Sitemap.php on line 35
```

**Comment by Klap-in** [comment]
The fiction is located in another class: https://github.com/splitbrain/dokuwiki/blob/31a58aba4c24b34c34ad5764d1a35b7c398c3a2c/inc/Sitemap/Mapper.php#L106

**Comment by wisze** [comment]
Since upgrading to Hogfather the sitemap.xml does not seem to be updated. New pages do not appear, timestamp of the file is not updated. I made sure the existing sitemap.xml.gz file permissions allow it to be written.

**Comment by phy25** [comment]
@wisze It's working for me fine. Could you create a new issue with more information about your environment and settings, or seek help on https://forum.dokuwiki.org/? 

> If your sitemap won't be created you can try to get some debug output from the indexer by calling http://yourserver/dokuwiki/lib/exe/indexer.php?debug=1 in your browser.
>
> https://www.dokuwiki.org/sitemap

**Comment by wisze** [comment]
There appears to be a link to spatialhelper. My error log:

`wiki.wisze.net/lib/plugins/spatialhelper/action.php:133\nStack trace:\n#0 /var/www/vhosts/wisze.net/wiki.wisze.net/inc/Extension/EventHandler.php(81): action_plugin_spatialhelper->handle_sitemap_generate_before(Object(dokuwiki\\Extension\\Event), NULL)\n#1 /var/www/vhosts/wisze.net/wiki.wisze.net/inc/Extension/Event.php(72): dokuwiki\\Extension\\EventHandler->process_event(Object(dokuwiki\\Extension\\Event), 'BEFORE')\n#2 /var/www/vhosts/wisze.net/wiki.wisze.net/inc/Sitemap/Mapper.php(68): dokuwiki\\Extension\\Event->advise_before(true)\n#3 /var/www/vhosts/wisze.net/wiki.wisze.net/inc/TaskRunner.php(213): dokuwiki\\Sitemap\\Mapper::generate()\n#4 /var/www/vhosts/wisze.net/wiki.wisze.net/inc/TaskRunner.php(50): dokuwiki\\TaskRunner->runSitemapper()\n#5 /var/www/vhosts/wisze.net/wiki.wisze.net/lib/exe/taskrunner.php(16): dokuwiki\\TaskRunner->run()\n#6 /var/www/vhosts/wisze.net/wiki.wisze.net/lib/exe/indexer.php(5)...'
`

**Comment by wisze** [comment]
I'll see whether i can get some sensible info to open another issue about this. For now i'm just puzzled.

**Comment by Klap-in** [comment]
What is the notice, warning or error message before this trace?

**Comment by Klap-in** [comment]
On that line SitemapItem is used. In the last release it renamed to \dokuwiki\Sitemap\Item https://github.com/splitbrain/dokuwiki/tree/master/inc/Sitemap. It is a good idea to report this in the issue tracker of that plugin.

**Comment by mprins** [comment]
@wisze please open a PR for https://github.com/mprins/dokuwiki-plugin-spatialhelper/blob/master/action.php if you want this fixed quickly
