### ISSUE TITLE
SMTP Plugin not working in "Hogfather" RC2

### ISSUE THREAD

**Issue by bjquast** [splitbrain/dokuwiki#3138]
The SMTP Plugin works in "Hogfather" RC1 but runs int an error after upgrading to "Hogfather" RC2.

The error message is:

> There was an unexpected problem communicating with SMTP: Start TLS failed to enable crypto

Log in `Check SMTP configuration` is like that:

```
SMTP log:
Set: the server
Set: the auth
Set: a message will be sent
Connecting to ***.de at 587
Got: 220 mail.***.de ESMTP
Sent: EHLO ***.eu
Got: 250-mail.***.de
Got: 250-STARTTLS
Got: 250-PIPELINING
Got: 250-SMTPUTF8
Got: 250-8BITMIME
Got: 250 SIZE 31457280
Sent: STARTTLS
Got: 220 ready for tls
```

I experienced that on two wikis after update from "Hogfather" RC1 to "Hogfather" RC2 via the Upgrade Plugin.

System is Ubuntu 18.04, Apache, PHP 5.6.4

Thanks in advance
Björn

**Comment by splitbrain** [comment]
I don't see how anything between the two RCs that should influence TLS communication. Are you sure nothing else changed on your server?

**Comment by bjquast** [comment]
Hmm, I am quite sure because I did the upgrade first with one wiki, figured out that there was a problem and tried to fix it by resetting the configuration. Does not help.
After that i checked that smtp is running in the other wiki and did an upgrade there too, without touching it in any other way. After the upgrade the error occurred in the second wiki too.

Björn

**Comment by splitbrain** [comment]
:man_shrugging: first step: open an issue in the smtp plugin repo. The we'll see how to debug this.

**Comment by bjquast** [comment]
I figured out, that the problem was caused by an TLS version error as before mentioned in:

https://github.com/splitbrain/dokuwiki-plugin-smtp/issues/31

so changing:
`STREAM_CRYPTO_METHOD_TLS_CLIENT`

to

`STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT`

in lib/plugins/smtp/subtree/txtthinking/Mailer/src/Mailer/SMTP.php, line 201
fixes the problem for me. I have no idea why the problem suddenly occurs after update to 'Hogfather' RC2

Best Björn
