### ISSUE TITLE
XML Sitemap on Hogfather

### ISSUE THREAD

**Issue by StarArmy** [splitbrain/dokuwiki#3139]
In reference to: https://forum.dokuwiki.org/d/17873-xml-sitemap-is-broken

and https://www.dokuwiki.org/sitemap

In Hogfather RC2, going to the sitemap location, for example mine at:

https://stararmy.com/wiki/doku.php&do=sitemap

Results in a 404 file not found error.

**Comment by splitbrain** [comment]
Your location is wrong. It's https://stararmy.com/wiki/doku.php?do=sitemap

Otherwise this is a duplicate of #3134
