### ISSUE TITLE
Hogfather: navbar and menus malfunction

### ISSUE THREAD

**Issue by FloMiLe** [splitbrain/dokuwiki#3140]
After upgrading from 2018-04-22c "Greebo" to 2020-06-01 "Hogfather" via the upgrade plugin, two problems occur (at least using the bootstrap theme:

- The navbar CSS settings are messed up, i.e. the link to the active page gets shifted upwards, recolored and bold.
- The tools and personal menu icons in the top right corner are still there, but the menus do not show up when clicked.

**Comment by phy25** [comment]
Duplicate to https://github.com/giterlizzi/dokuwiki-template-bootstrap3/issues/483.
