### ISSUE TITLE
Hogfather RC2: PHP Fatal error for "Doku_Handler_Quote" class not found 

### ISSUE THREAD

**Issue by issmirnov** [splitbrain/dokuwiki#3141]
I'm running a vanilla dokuwiki installation, with the https://www.dokuwiki.org/plugin:markdowku plugin installed. The wiki crashes with an error 500 when I try to load any page.

Error logs:

```
2020/06/04 09:59:48 [error] 18534#18534: *4127417 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Doku_Handler_Quote' not found in /var/www/dev.smirnov.wiki/lib/plugins/markdowku/syntax/blockquotes.php:95
Stack trace:
#0 /var/www/dev.smirnov.wiki/inc/load.php(146): require()
#1 [internal function]: load_autoload()
#2 [internal function]: spl_autoload_call()
#3 /var/www/dev.smirnov.wiki/inc/Extension/PluginController.php(103): class_exists()
#4 /var/www/dev.smirnov.wiki/inc/pluginutils.php(54): dokuwiki\Extension\PluginController->load()
#5 /var/www/dev.smirnov.wiki/inc/parserutils.php(559): plugin_load()
#6 /var/www/dev.smirnov.wiki/inc/parserutils.php(204): p_get_parsermodes()
#7 /var/www/dev.smirnov.wiki/inc/parserutils.php(181): p_get_instructions()
#8 /var/www/dev.smirnov.wiki/inc/parserutils.php(501): p_cached_instructions()
#9 /var/www/dev.smirnov.wiki/inc/parserutils.php(282): p_render_metadata()
#10 /var/www/dev.smirnov.wiki/inc/common.php(254): p_get_metadata()
#11 /var/www/dev.smirnov.wiki/doku.php(93): pageinfo()
#12 {main}
```

Is this class being deprecated?

**Comment by phy25** [comment]
Duplicate to https://vcs.in-berlin.de/schrank21_dokuwiki/tktview?name=50864415a5

**Comment by issmirnov** [comment]
That's by design, in order to get the attention of the author. Given that the author's former wiki is deleted off the internet though, I'm not optimistic.

Anyway, this particular bug is to get clarity about the `Doku_Handler_Quote` class, since Dokuwiki core authorship is not responsible for plugin compatibility.

**Comment by phy25** [comment]
The new Quote class is at `\dokuwiki\Parsing\Handler\Quote`. I am just not sure if we want to provide a polyfill while refactoring it.

**Comment by splitbrain** [comment]
There's already work on markdowku being done: https://forum.dokuwiki.org/d/17870-problem-fixing-markdowku-plugin-doku-handler-callwriter-is-protected

**Comment by RaphaelWimmer** [comment]
@issmirnov I have (hopefully) fixed the plugin for Hogfather, contacted the original author (who is happy to hand over maintenance), and updated the [plugin page](https://www.dokuwiki.org/plugin:markdowku) a little bit.
Github repo is here: https://github.com/Medieninformatik-Regensburg/dokuwiki-plugin-markdowku
I'd be grateful for any co-maintainers.

The plugin version linked on the plugin page is still the one compatible with *Greebo* as I did not have time to make the plugin compatible with both old and new API. Please try out the *Hogfather*-compatible version [in the master branch](https://github.com/Medieninformatik-Regensburg/dokuwiki-plugin-markdowku/archive/master.zip)
