### ISSUE TITLE
No plugin in "Extension Manager > Installed plugins" at farm's animals

### ISSUE THREAD

**Issue by f4kt** [splitbrain/dokuwiki#3142]
Version:  2020-06-01 "Hogfather" RC2 (commit b83837)
Template: dokuwiki, but also in bootstrap3
Configuration: farms, following https://www.dokuwiki.org/farms

If I am at an animal's "Extension Manager > Installed plugins", selecting any check (enabled / disabled / updatable) no plugins are not shown. If I go to "Extension Manager > Installed templates" and select checks (enabled / disabled / updatable) the templates are shown as expected.

When doing this at the farmer's, main site's, extension panel, the behavior of showing plugins is the one expected, showing them correctly.

So the problem is that the main site (in my case a Virtual Host) must be enabled in order to install / upgrade the plugins, and to enable/disable them in a subsite (=animal) I must do it manually with php config files.

By the way, thanks a lot in advance for this so great wiki :)

**Comment by phy25** [comment]
I understand that you got an empty list of installed plugins at the animal of the farm in RC2. I don't think that is a regression because it seems to be intended as is mentioned in https://www.dokuwiki.org/plugin:farmer#usage.

**Comment by f4kt** [comment]
I'm not using farmer plugin but "standard" farming configuration described in https://www.dokuwiki.org/farms (so, I modify inc/preload.php,...). Until one month, using this configuration everything was right

**Comment by f4kt** [comment]
Instead of using the plugin I set it manually following https://www.dokuwiki.org/farms (modify inc/preload.php, etc). I've had the template set in this way for long time, and never had the problem since my last update of it

**Comment by f4kt** [comment]
After upgrading to the Hogfather stable it remains the same: no plugins (even if clicking enable,...) at `id=start&do=admin&page=extension&tab=plugins`

Any news about that?

**Comment by f4kt** [comment]
I've followed https://www.dokuwiki.org/faq:blankpage and the reason was that some old plugins (authLDAP,...) were disabled but yet installed. As soon as I have deleted them everything has gone right. Thanks a lot anyway
