### ISSUE TITLE
small amin ui issue

### ISSUE THREAD

**Issue by tomamplius** [splitbrain/dokuwiki#3143]
![2020-06-04_22-49](https://user-images.githubusercontent.com/6951820/83809169-4f205880-a6b6-11ea-972f-89e599e9db82.png)

**Comment by tomamplius** [comment]
2 ways to fix but other way can be best
In lib/tpl/dokuwiki/css/_admin.less
  - 40% => 45%
  - add  ```padding-right: 20px;```

~~~
   ul.admin_tasks {
        float: left;
        width: 45%;
        list-style-type: none;
        font-size: 1.125em;
    }
~~~
OR 
~~~
   ul.admin_tasks {
        float: left;
        width: 40%;
        list-style-type: none;
        font-size: 1.125em;
        padding-right: 20px;
    }
~~~

**Comment by phy25** [comment]
Thanks for catching the issue. The actual shifted width is `1.5em`, and a better fix would be by adding `display: flex`. I am going to submit a PR regarding this.

**Comment by tomamplius** [comment]
Thanks a lot #3145 for the quick fix of this issue. It works for me Good work
