### ISSUE TITLE
DOKU_LEXER_* constants not loaded in hogfather

### ISSUE THREAD

**Issue by schplurtz** [splitbrain/dokuwiki#3146]
Hi,

Some syntax handled by plugins are not displayed anymore. But if I edit the page, everything is good again.

This is not a plugin compatibility issue. this is a cache problem that may be related to issue #3129

For some strange reason, DokuWiki does not load some definitions. The constants `DOKU_LEXER_ENTER`, `DOKU_LEXER_EXIT` etc… are not loaded in certain conditions :
Here are the messages I got in logs (slightly reformatted for readability) :
````
2020/06/05 06:10:08 [error] 19704#19704: *4571 FastCGI sent in stderr:
   "PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER'
   (this will throw an Error in a future" while reading upstream, client: 192.168.255.103,
   server: schbruzi.mydomain.com,
   request: "GET /latestdw/start?do= HTTP/1.1",
   upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:",
   host: "schbruzi.mydomain.com", referrer: "https://schbruzi.mydomain.com/latestdw/start?do=admin&page=extension&tab=search&q=a2s"
2020/06/05 06:10:08 [error] 19704#19704: *4571 FastCGI sent in stderr:
  " version of PHP) in /opt/www/dokus/latestdw/lib/plugins/wrap/syntax/div.php on line 91PHP message:
  PHP Warning:  Use of undefined constant DOKU_LEXER_SPECIAL - assumed 'DOKU_LEXER_SPECIAL'
  (this will throw an Error in a future version of PHP) in /opt/www/dokus/latestdw/lib/plugins/wrap/syntax/div.php on line 107
  PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT'
  (this will throw an Error in a future version of PHP) in /opt/www/dokus/latestdw/lib/plugins/wrap/syntax/div.php on line 115
  PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER'
  (this will throw an Error in a future version of PHP) in /opt/www/dokus/latestdw/lib/plugins/wrap/syntax/div.php on line 91
  PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_SPECIAL - assumed 'DOKU_LEXER_SPECIAL'
  (this will throw an Error in a future version of PHP) in /opt/www/dokus/latestdw/lib/plugins/wrap/syntax/div.php on line 107
  PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT'
  (this will throw an Error in a future version of PHP) in /opt/www/dokus/latestdw/lib/plugins/wrap/syntax/div.php on line 115
  PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER'
  (this will throw an Error in a future version of PHP) in /opt/www/dokus/latestdw/lib/plugins/wrap/syntax/div.php on line 91
  PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_SPECIAL - assumed 'DOKU_LEXER_SPECIAL'
  (this will throw an Error in a future version of PHP) in /opt/www/dokus/latestdw/lib/plugins/wrap/syntax/div.php on line 107
  PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT'
  (this will throw an Error in a future version of PHP) in /opt/www/dokus/latestdw/lib/plugins/wrap/syntax/div.php on line 115
  PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_
````

I found a way to reproduce this by simply removing the xhtml cache, but not the instruction cache, and reloading the page.
For example :

- install hogfather
- install the wrap plugin
- create :start page and add some wrap syntax. 
  ```
  <WRAP center round info 60%>bloc information</WRAP>
  ```
  So far so good
- remove the xhtml cache
  ````
  find data/cache/? -name '*html' -print0 |xargs -0 rm
  ````
- reload the page in your browser
- syntax is not rendered and there are the messages in the logs

If you edit the page, and change it a little bit, everything works.

**Comment by phy25** [comment]
#3132 should fix this.

**Comment by schplurtz** [comment]
Oh, it was in a separate branch. didn't notice.

Yes, I confirm #3132 fixes it.

Big thank you to all of you.

**Comment by tmo26** [comment]
@schplurtz How do I install the branch that contains #3132 over an existing Hogfather RC2?

**Comment by Klap-in** [comment]
#3132 is merged in the master branch. The branch is can be downloaded with button at https://github.com/splitbrain/dokuwiki

**Comment by schplurtz** [comment]
@tmo26 the branch has been merged into master and removed. So the short answer is, I guess, «you can't». Assuming you want to apply the changes in this commit to your current hogfather installation, you can [download it as a diff](https://github.com/splitbrain/dokuwiki/commit/17b5bdfb9cc8fa77973e0cfb905cb4b31e3f9e15.diff) and apply the changes with the `patch` command. If you need help with `patch`, ask your favorite search engine. You may also apply by hand, that's not that long.
