### ISSUE TITLE
Report URI Deprecation Report

### ISSUE THREAD

**Issue by AmritasyaPutra** [splitbrain/dokuwiki#3153]
From few months I have started getting a new deprecation Report for my Dokuwiki. The warning is:

'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.

This is reported by Chrome browser on Windows. For example when visiting this page:
https://wiki.ekvastra.in/doku.php/start

I am running 2018-04-22c "Greebo" with PHP 7.4 on Linux 3.10.0-962.3.2.lve1.5.26.5.el7.x86_64

**Comment by phy25** [comment]
DokuWiki core does not use this at all: https://github.com/splitbrain/dokuwiki/search?q=webkitStorageInfo&unscoped_q=webkitStorageInfo

Also I did not see the report on your website now. Please check if it comes from your template or plugins.

**Comment by Klap-in** [comment]
Also I cannot find a clue sofar via the codesearch: [*StorageInfo](https://codesearch.dokuwiki.org/search?project=dokuwiki&project=plugin&project=template&q=*StorageInfo&defs=&refs=&path=&hist=&type=).

**Comment by AmritasyaPutra** [comment]
You are right this could be coming from one of the plugins, I had "updated" them around the same time this started.
