### ISSUE TITLE
Many colors black in Template Style Settings in "Hogfather"

### ISSUE THREAD

**Issue by MrReSc** [splitbrain/dokuwiki#3160]
I just installed the latest release candidate `rc-2020-06-09 "Hogfather" RC3` on a test server. The DokuWiki has no data, template or plugins installed. It is still virgin...

In the `Template Style Settings` many of the colors are set to black by default. See screenshot:
![grafik](https://user-images.githubusercontent.com/24952268/84298919-33063680-ab50-11ea-8c8e-74f43eed37ea.png)

If now the button `Save changes` or `Preview changes` is pressed, which is obvious, the following happens:
![grafik](https://user-images.githubusercontent.com/24952268/84298980-4c0ee780-ab50-11ea-9353-493754efa098.png)

**Comment by wos-hh** [comment]
seen the same problem when upgrading a dokuwiki with the upgrade plugin to RC2.
as a workaround I could fix the color codes in "style.ini".

            #333 → #333333, #080 → #008800

etc.

**Comment by phy25** [comment]
Introduced by #3065. We might need to add code to convert three-digit hex color to six-digit hex color before outputting the value. Also I am not sure if iris allows string color value (`white`), which would be more tricky.

**Comment by MrReSc** [comment]
This seems to be the problem. I changed it on my template [MindTheDark](https://github.com/MrReSc/MindTheDark) and it works now.

**Comment by phy25** [comment]
@MrReSc Actually I guess this needs to be handled here at the core level.

---

iris uses Color.js [which supports](https://github.com/Automattic/Color.js/blob/29304573e7bb07c5a2d0d1898e1113f3dc13de78/src/color.js#L62) rgb, hsl, hsv, alpha, hexcode (3/6 digit). iris won't change the value if it doesn't recognize it.

I haven't been able to go through https://codesearch.dokuwiki.org/search?project=dokuwiki&project=plugin&project=template&path=style.ini, but I already saw some color name (`white`) usage there.

We can:

- Convert color value to hex at the server end (which will make styles.ini always store hex value, and no alpha channel support)
- Find a new JavaScript color picker
- Make a naive JavaScript color picker that disables color input element when it's not a hex color, and copies the result of the color input to the text field
- Totally disable the color picker feature

**Comment by MrReSc** [comment]
@phy25 Yes, of course it has to be changed in the core. For me it was the easiest way to solve the problem. I only discovered it because a user contacted me.

The user interface as it is in Hogfather is much better. You can see at first sight which colour is chosen. In Greebo you always had to click on the hex value first.
