### ISSUE TITLE
User setting for the type of Editor to use

### ISSUE THREAD

**Issue by grbd** [splitbrain/dokuwiki#3163]
Currently for dokuwiki we have the default wiki syntax editor.
There is also the CKGEdit WYSIWYG editor - https://www.dokuwiki.org/plugin:ckgedit

On top of that I'd like to write something like an inplace markdown editor plugin using

  * https://quilljs.com/
  * https://cloverhearts.github.io/quilljs-markdown/
  * https://www.dokuwiki.org/plugin:mdpage

I think it would be useful to have some kind of user profile based setting to choose a default editor for the page

Something that editor plugins can hook into as a default setting.
Currently with CKGEdit you have to toggle back and forth using a button at the bottom

**Comment by phy25** [comment]
There is currently no standard abstraction of editors (I would call it editor federation), so it's not possible. Even we have that API, existing plugins need to adapt in order to make this possible.

**Comment by Klap-in** [comment]
At the moment there is not yet an user profile. For storing other settings it is suggested another time as well. But so far such thing is not implemented. (#2131, [old bug2872](https://bugs.dokuwiki.org/2872.html),

Another plugin that could benefit of this specific user setting as well: https://www.dokuwiki.org/plugin:prosemirror

**Comment by phy25** [comment]
@Klap-in A workaround would be to use usergroups to store this.
