### ISSUE TITLE
#!/usr/bin/php hashbang in CLI scripts fails in some environments

### ISSUE THREAD

**Issue by woutgg** [splitbrain/dokuwiki#3167]
On the shared hosting where I run Dokuwiki, PHP is located under `/usr/local/bin/php` instead of `/usr/bin/php`, causing the CLI scripts under the `bin` directory to fail.

For exactly the same reason, in my own scripts I usually use a hashbang like this: `#!/usr/bin/env php`. Perhaps the Dokuwiki CLI scripts could be updated in a similar fashion.

**Comment by fiwswe** [comment]
This is also the case on OpenBSD (probably all recent versions including 6.7) where PHP is usually installed as a package. OpenBSD packages install into /usr/local/…

How about: `#!/usr/bin/env php`? Seems to work in different environments for me.
