### ISSUE TITLE
Fatal error: require_once()

### ISSUE THREAD

**Issue by zounp** [splitbrain/dokuwiki#3169]
After upgrading to Hogfather RC3 with the Upgrade plugin I got, when loading page https;//example.com/doku.php,

Fatal error: require_once(): Failed opening required '/domains/example.com/public_html/inc/events.php' (include_path='.:/usr/local/php73/lib/php') in domains/example.com/public_html/inc/load.php on line 18

And also seen:
Fatal error: Uncaught ArgumentCountError: Too few arguments to function dokuwiki\StyleUtils::cssStyleini(), 0 passed in /domains/example.com/public_html/inc/template.php on line 251 and at least 1 expected in /domains/example.com/public_html/inc/StyleUtils.php:19 Stack trace: #0 /domains/example.com/public_html/inc/template.php(251): dokuwiki\StyleUtils->cssStyleini() #1 /domains/example.com/public_html/lib/tpl/dokuwiki/main.php(22): tpl_metaheaders() #2 /domains/example.com/public_html/inc/actions.php(27): include('/...') #3 /domains/example.com/public_html/doku.php(120): act_dispatch() #4 {main} thrown in /domains/example.com/public_html/inc/StyleUtils.php on line 19

After a minute I reloaded the page and all was fine and I was not able to reproduce the issue.

**Comment by phy25** [comment]
You either have a partial upgrade or PHP's opcache is not refreshed when you saw the error message:

https://github.com/splitbrain/dokuwiki/blob/504b44a4c7fde212be653fc640f1685318449287/inc/StyleUtils.php#L19

Could you verify if your opcache is on, and your PHP version by running the following PHP file?

```php
<?php
phpinfo();
```

**Comment by zounp** [comment]
I had a look but my hostingprovider does not have an option to view the PHP status.. Is there an other way .... Ah, yes, make a new php file containing <?php phpinfo(); and open the page. Works :-)

Zend OPcache
Opcode Caching 	Up and Running
Optimization 	Enabled
SHM Cache 	Enabled
File Cache 	Disabled
Startup 	OK 

and

opcache.enable	On	On
opcache.enable_cli	Off	Off
opcache.enable_file_override	Off	Off
opcache.error_log	no value	no value
opcache.file_cache	no value	no value
opcache.file_cache_consistency_checks	1	1
opcache.file_cache_only	0	0

There are more variables but I think this is what you are looking for.

**Comment by phy25** [comment]
The upgrade plugin already clears opcache:

https://github.com/splitbrain/dokuwiki-plugin-upgrade/blob/27c6a3e69b508309747ba2073c9a3da14622c842/admin.php#L297

I am not sure how that happened to you, but I don't think there is anything we can do here.
