### ISSUE TITLE
X-Accel-Redirect broken when $conf['savedir'] is not under DOKU_INC

### ISSUE THREAD

**Issue by schplurtz** [splitbrain/dokuwiki#3178]
Hi,

DW generates wrong `X-Accel-Redirect` header for nginx when `$conf['savedir']` is not under DOKU_INC. instructions on DW [xsendfile](https://www.dokuwiki.org/config:xsendfile) documentation page are buggy too.

The effect is that images and cached files can't be downloaded. Site looks poorly.

This happens on 
DW greebo, hogfather rc, master
debian 10, nginx-light 1.14.2-2+deb10u1

How to reproduce : 
- install DW with nginx as webserver
- move datadir and set `$conf['savedir']` accordingly in local.php
- set [xsendfile](https://www.dokuwiki.org/config:xsendfile) to 3 "nginx proprietary X-Accel-Redirect".

For this test, DW is installed in `/var/www/html`, URL is http://mysite/, userewrite = 1,
savedir is `/opt/wdat`.
`http://mysite/_media/logo.png` maps to `/opt/wdat/media/logo.png`
but [http_sendfile()](https://xref.dokuwiki.org/reference/dokuwiki/nav.html?inc/httputils.php.source.html#l64) in this case sends this header back to nginx 

    X-Accel-Redirect: ia/logo.png

The faulty line in [http_sendfile()](https://www.dokuwiki.org/config:xsendfile) is

        $file = DOKU_REL.substr($file, strlen(fullpath(DOKU_INC)) + 1);

In my case : DOKU_INC='/var/ww/html', and file = '/opt/wdat/media/logo.png';

        substr( '/opt/wdat/media/logo.png', strlen( '/var/ww/html' ) + 1 ) == 'ia/logo.png'

**Comment by schplurtz** [comment]
Found a workaround.

As per [nginx doc](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/) nginx needs an URI that it'll compare with its `location /foo` blocks. The problem is that DW has a filename and it needs to map that file back to an URI that nginx can handle. The current code merely truncates the filename and can obviously only work when `DOKU_INC` is a prefix of `$conf['savedir']`.

The workaround I found, is based on [andi's idea back in 2012](https://bugs.dokuwiki.org/2388.html) of using a specific string that cannot be mistaken for a «normal» URI :

````diff
--- /home/src/dokuwiki-git/inc/httputils.php	2020-06-14 16:11:10.880043982 +0200
+++ ./httputils.php	2020-06-14 16:12:51.364424932 +0200
@@ -82,9 +82,7 @@
         ob_end_clean();
         exit;
     }elseif($conf['xsendfile'] == 3){
-        // FS#2388 nginx just needs the relative path.
-        $file = DOKU_REL.substr($file, strlen(fullpath(DOKU_INC)) + 1);
-        header("X-Accel-Redirect: $file");
+        header("X-Accel-Redirect: /DOKU_SEND_FILE$file");
         ob_end_clean();
         exit;
     }
````
With this patch, the header sent back is

    X-Accel-Redirect: /DOKU_SEND_FILE/opt/wdat/media/logo.png

and it is easily caught by nginx with the following directive.

````nginx
location ^~ /DOKU_SEND_FILE/ {
    alias /;
    internal;
}
````

This workaround probably can't be used with windows filenames, and I don't know how it would behave with a DW farm...

As I'm about to submit this comment, I realize I could have used a symlink
`DOKU_INC/real-dw-data -> /opt/wdat`
and set `$conf['savedir']='real-dw-data';`, and use nginx directive `location ^~ /real-dw-data/ { internal; }`. However, there may exist some hosting environments where symlinks are not an option.

**Comment by phy25** [comment]
Ralated to #2895.

**Comment by schplurtz** [comment]
Thanks phy25.

This is an exact duplicate of #2895. The paths are different but the same function returns the same kind of wrong result. So I'm closing this one now. Eventually, I'll add info to #2895 if I ever make progress on this issue.
