### ISSUE TITLE
Querying the "Recent changes" page

### ISSUE THREAD

**Issue by xerus2000** [splitbrain/dokuwiki#3180]
I would like a link to the recent changes list in the wiki that only lists changes from me in a particular timeframe so I can point people to my work. I found the page https://www.dokuwiki.org/recent_changes but it doesn't list the available url parameters.

I found the equivalent thing for mediawiki though: https://www.mediawiki.org/wiki/API:RecentChanges

**Comment by Klap-in** [comment]
There is at the moment only support for filtering on the namespace you are at the moment.
e.g. if you visit https://www.dokuwiki.org/plugin:siteexport?do=recent, then you see only _Recent Changes_ from the 'plugin' namespace.

Code can be found here https://github.com/splitbrain/dokuwiki/blob/master/inc/Action/Recent.php

**Comment by phy25** [comment]
Sounds like you can implement this based on https://www.dokuwiki.org/plugin:changes.

**Comment by LMS235** [comment]
you can do this via https://www.dokuwiki.org/plugin:changes and "Whitelist/blacklist changes by user" and "Maximum age of change displayed"
`{{changes>user = username}}`

and with age 
`{{changes>user=username&maxage=10}}`
