### ISSUE TITLE
feed.php: Illegal string offset 'abstract'

### ISSUE THREAD

**Issue by tmo26** [splitbrain/dokuwiki#3182]
Release rc-2020-06-09 "Hogfather" RC3

In the nginx error log I see the following php warning several times:

`FastCGI sent in stderr: "PHP message: PHP Warning:  Illegal string offset 'abstract' in /var/www/dokuwiki/feed.php on line 406`

How can this be fixed?

**Comment by phy25** [comment]
This part of code hasn't been touched for 9 years... Also it's weird that your metadata includes string there:

https://github.com/splitbrain/dokuwiki/blob/7da47cff1f9c120084755d9a80672f210bb5efb9/inc/parserutils.php#L367-L383

Do you have other plugins installed?

Could you double check to see if every time you request `feed.php`, this error occurs?

If yes, could you replace that line in `feed.php` with this and try again?

```php
                        if (isset($meta['description']['abstract'])) { // patch
                        $content = $meta['description']['abstract'];
                        }else{ var_dump($ditem['id']); var_dump($meta); exit(); } // patch
```

And request `feed.php` again to see if there is some debug string at the end of the response. If yes, please remove sensitive data there and post it here, or if you don't feel comfortable posting it publicly, you can send it to me directly (no guarantee from me if you direct that to me :-)).

**Comment by tmo26** [comment]
> Do you have other plugins installed?
Yes, quite a lot.

> Could you double check to see if every time you request feed.php, this error occurs?

If I manually request feed.php, this issue does not occur.
However, it seems to occur regularly in the intervall set in the configuration `rss_update`, which is 30min in my case.

**Comment by tmo26** [comment]
After closer inspection of the logfiles, I can trace this back until 2020/06/14 (no logfiles before that), but to my surprise there are no error messages any more after 2020/06/28 07:30:42. Not sure what happened yesterday that made the error suddenly disappear.

I'm closing this now, but will have an eye on it.

**Comment by phy25** [comment]
I forgot to mention why you might be seeing this - one of your page metadata files might be broken and I don't see a way in core that could lead to this. If you made more changes, that broken page will be out of the recent X changes and won't be requested by feed.php.

**Comment by tmo26** [comment]
Thanks for this tip!
Is there any way I could identify broken metadata?

**Comment by phy25** [comment]
@tmo26 Unfortunately there's no such a tool that can check it as far as I know. The idea is easy: Loop through all metadata files (`data/meta/*.meta`) and check if that array exists.

Looks like `plugin:meta` could rewrite metadata but I am not sure if it can actually modify that description field. Do you happen to use that plugin?

**Comment by dblume** [comment]
I just ran into this, and I don't have plugin:meta. The offending page was one I "deleted" by deleting all of its body, and saving it empty. Navigating to the deleted page says "This page does not exist anymore." I worked around the failure by using phy25's isset(), but just setting content='' if not set.
