### ISSUE TITLE
Upgraded to latest version of Dokuwiki.  Issue with media manager

### ISSUE THREAD

**Issue by ssarkarnetip** [splitbrain/dokuwiki#3185]
Team,

I am running on Centos 7, Nginx 1.1.2.  Php 7.1
I upgraded to the new version of dokuwiki. rc-2020-06-09 "Hogfather" RC3 

  When I am uploaded a media file.  It seems everything is fine.  I click okay and the file loads into the page.  However, the okay prompt does not go away.

I have to cancel out.  Not a show stopper but annoying.  When I click the okay button, the prompt should go away.  I using this with in the ckgedit.  
![dokuwiki_issue](https://user-images.githubusercontent.com/28353306/85432584-2cfd5600-b551-11ea-8317-ffba1a2b67bb.png)

As you can see, I click okay.  The okay prompt does not go away.  

If I attach an image. I get no errors.  Everything works fine.  I only get this error when using the media manager as internal link media.  Old version, I did not have this issue.

**Comment by phy25** [comment]
What plugin are you using? That seems to come from a editor plugin.

**Comment by splitbrain** [comment]
known (and I believe solved) problem in ckgeditor
