### ISSUE TITLE
RC3 breaks Greek letter phi (φ) in file paths, titles and tags

### ISSUE THREAD

**Issue by disk0x** [splitbrain/dokuwiki#3188]
After re-basing to Release rc-2020-06-09 "Hogfather" RC3, one of the breakages I couldn't recover from is a very specific bug regarding the Greek letter Φ/φ in certain elements of dokuwiki, of which I have identified file paths (both the .txt files, and .pdf files generated from dokuwiki plugins), titles derived from filepaths (as opposed to H1 elements), and where tags are displayed. The letter φ is either replaced by an underscore (see image from search results), or elided (see filepath image).

The files on the filesystem appear to be encoded correctly: where expected, the page sources are stored as text/plain; charset=utf-8. 

![Screenshot_2020-06-26_17-21-32](https://user-images.githubusercontent.com/19468139/85874413-e585fc80-b7d2-11ea-816a-b9996b587e1e.png)
![Screenshot_2020-06-26_17-23-59](https://user-images.githubusercontent.com/19468139/85874417-e6b72980-b7d2-11ea-9102-9a076261b250.png)

This is a fresh VPS and fresh dokuwiki install (not updated from existing setup), with transferred data and conf files from earlier dokuwiki setup.
Dokuwiki: rc-2020-06-09 "Hogfather" RC3
`$conf['fnencode'] = 'utf-8';`
PHP: 
```
php-cli-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64
php-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64
php-common-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64
php-gd-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64
php-json-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64
php-pecl-zip-1.15.3-1.module_el8.2.0+313+b04d0a66.x86_64
php-intl-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64
php-fpm-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64
php-xml-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64
php-mbstring-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64
```
OS: centos-release-8.2-2.2004.0.1.el8.x86_64

**Comment by phy25** [comment]
> After re-basing to Release rc-2020-06-09 "Hogfather" RC

What was the version that was working for you?

**Comment by disk0x** [comment]
> > After re-basing to Release rc-2020-06-09 "Hogfather" RC
> 
> What was the version that was working for you?

2018-04-22c "Greebo"

**Comment by splitbrain** [comment]
Maybe something I missed in 0884c254723c9fa99e70acf920c59d7f3dbcab55

**Comment by splitbrain** [comment]
@disk0x can you type the search word and the full list of greek letters you used in your screenshots above here? This way I can copy'n'paste them and avoid that I mangle them in any way.

**Comment by disk0x** [comment]
Of course:

1) μετάφραση, ΜΕΤΑΦΡΑΣΗ (Greek uppercase strips _some_ diacritics in _some_ positions, like here where ά->A, not Ά)

2)  α β γ δ ε ϝ ϛ ζ η θ ι κ λ μ ν ξ ο π ϟ ϙ ρ σ τ υ φ χ ψ ω ϡ , Α Β Γ Δ Ε Ϝ Ϛ Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ϟ ϙ Ρ Σ Τ Υ Φ Χ Ψ Ω Ϡ

**Comment by disk0x** [comment]
Thanks for fixing this. 
If you don't mind bringing this up here instead of a separate issue, the new commit may introduce a new problem
inc/Utf8/tables/case.php

Now Σ is lowercased as σ instead of ς. ς is a special case, it's the lowercase form of σ when it occurs at the end of a word. Medial and starting Σ should indeed be σ. 

Can it be handled with a simple lookup table like this one? Perhaps with
```
 'Σ' -> 'σ'
'Σ ' -> 'ς ' 
```

**Comment by splitbrain** [comment]
Languages. Everytime you assume something about a foreign language it turns out to be more complicated than anticipated.

The current implementation (always using `σ`) is also what `mb_strtolower` uses. Since we rely on that function if available, our fallback should replicate its behavior. So unfortunately, I fear I can't fix this.

**Comment by disk0x** [comment]
I understand the reasoning. Always σ is probably preferred, compared to always ς.

Both are wrong as far as Greek is concerned, but one is less jarring than the other.

Is there a more unicode-aware library Dokuwiki could use in the future?

**Comment by splitbrain** [comment]
I don't think there is a different library. I'm closing this, thanks again for your help.
