### ISSUE TITLE
Feature Request: Code Highlighting in default editor

### ISSUE THREAD

**Issue by LMS235** [splitbrain/dokuwiki#3189]
Hello,

would it be possible to add code highlighting directly into the normal DW editor? Something like the Codemirror Editor did?

See also https://forum.dokuwiki.org/d/17950-alternative-fur-codemirror-gesucht

Regards

**Comment by splitbrain** [comment]
Syntax highlighting requires replacing the simple text area with custom HTML similar to what WYSIWYG editors do. This is a super complex topic and nothing that will be considered for default behaviour.
