### ISSUE TITLE
Can the URL of static resources have no protocol?

### ISSUE THREAD

**Issue by yszc** [splitbrain/dokuwiki#3194]
I deploy https by CDN, and CDN access origin server still via http，dokuwiki still return static file with http like:
```
<script type="text/javascript" src="http://wiki.tech.yidoutang.com/lib/tpl/bootstrap3/assets/iconify/plugins/fa.js"></script>
```
I hope does dokuwiki can return url without protocol like:
```
<script type="text/javascript" src="//wiki.tech.yidoutang.com/lib/tpl/bootstrap3/assets/iconify/plugins/fa.js"></script>
```

**Comment by splitbrain** [comment]
DokuWiki should use relative URLs for resources unless you enabled the `canonical` option. The script above seems to come from the bootstrap3 template, so maybe they are doing something different. Should be reported at their repo.
