### ISSUE TITLE
page prefix ^lib results in 404 due to apache.conf:                RewriteRule ^lib

### ISSUE THREAD

**Issue by drtonyr** [splitbrain/dokuwiki#3195]
Setup:  AWS Ubuntu 18.04.4. dokuwiki "Release 2016-06-26a "Elenor of Tsort". userewrite set to .htaccess, apache.conf has uncommented RewriteRule ^lib

Problem:  I can't access a page that has 'lib' as a prefix, the rewitte rule triggers and results in a 404.

Debug info:  Changing the rewrite rule to be RewriteRule ^lib/ shows that this is the problem, e.g. pages like https://tonyrobinson.com/libre now work again.  This might not be a tight enough fix - I'm no expert.

**Comment by mprins** [comment]
neither of the files you mention are part of DW.
An example `.htaccess` is provided both for your deprecated version in https://github.com/splitbrain/dokuwiki/blob/release_stable_2016-06-26a/.htaccess.dist as well as current https://github.com/splitbrain/dokuwiki/blob/master/.htaccess.dist but neither has a rule that is like what you provided.

**Comment by drtonyr** [comment]
Ah - thanks - I'm in the wrong place then.

This must be Ubuntu specific changes.   I'll close the issue on the basis of the information you provided.

# cat /etc/issue
Ubuntu 18.04.4 LTS \n \l
# apt install dokuwiki
# egrep lib  /etc/dokuwiki/apache.conf | head -1
                #RewriteRule ^lib                      - [L]
