### ISSUE TITLE
Clicking on non-image files in Media Manager does not insert link

### ISSUE THREAD

**Issue by AnonTester** [splitbrain/dokuwiki#3199]
In release rc-2020-06-09 "Hogfather" RC3 (but noticed in previous versions as well), when using the Media Manager popup window to insert a link to a non-image file (e.g. odt/doc/xls/pdf) does not insert a link to the file into the editor window when clicking on the filename or the file-type icon. Images work fine.

Tested in Firefox 78.0.1 (64bit) and earlier versions on Linux, console output: 

Error  in js.php:1:83508

Uncaught TypeError: $link.attr(...) is undefined
    select https://apps.amatiglobal.com/kb/lib/exe/js.php?t=dokuwiki&tseed=3352daaba830006b0648e9b46760348d:1
    jQuery 2
        dispatch
        handle

Tested in Chromium Version 83.0.4103.61 (Official Build) Built on Ubuntu , running on LinuxMint 19.3 (64-bit), console output:
 
js.php?t=dokuwiki&tseed=3352daaba830006b0648e9b46760348d:1 Uncaught TypeError: Cannot read property 'substr' of undefined
    at HTMLAnchorElement.select (js.php?t=dokuwiki&tseed=3352daaba830006b0648e9b46760348d:1)
    at HTMLDivElement.dispatch (jquery.php?tseed=5bb1a98b139b46abd22c69cae01d7704:2)
    at HTMLDivElement.v.handle (jquery.php?tseed=5bb1a98b139b46abd22c69cae01d7704:2)
select @ js.php?t=dokuwiki&tseed=3352daaba830006b0648e9b46760348d:1
dispatch @ jquery.php?tseed=5bb1a98b139b46abd22c69cae01d7704:2
v.handle @ jquery.php?tseed=5bb1a98b139b46abd22c69cae01d7704:2

**Comment by splitbrain** [comment]
I cannot reproduce this and since no one else reported this, I assume it's a problem on your setup. Maybe an interfering plugin?

**Comment by phy25** [comment]
Cannot reproduce as well. Could you also try "using the Save button in the configuration manager“ to reset all caching?

That error is about this line:

https://github.com/splitbrain/dokuwiki/blob/499d9bcd9036da8a75b9ab35154ad4eb820d21a0/lib/scripts/media.js#L717-L718

I have no idea why it could fail. Might be some JavaScript not incompatible with jQuery.

**Comment by AnonTester** [comment]
Thanks for looking into it and for the suggestions. 
I had this problem on three separate installations. Turns out the [preservefilenames plugin](https://www.dokuwiki.org/plugin:preservefilenames) which I used on all three installations was responsible for breaking this functionality. I have disabled it now and the media manager popup inserts links to non-image files as it's supposed to.

**Comment by Klap-in** [comment]
Could you please create an issue in the bug tracker of that plugin? Then other people also understand what happens, and hopefully the author could provide a fix.
