### ISSUE TITLE
PHP error on git branch

### ISSUE THREAD

**Issue by IGBC** [splitbrain/dokuwiki#3205]
I just pulled this out of my nginx log.

```
PHP message: PHP Fatal error:  Access level to refnotes_bibtex_parser::$handler must be protected (as in class Doku_Parser) or weaker in /var/lib/dokuwiki/plugins/refnotes/bibtex.php on line 79
```

I can't provide any further details I know nothing about PHP or how DokuWiki works, I am just a sysadmin with a server throwing 500 errors.

version: git head as of time posted. Also got the error in the arch package after commenting out the bad reference to JSON.php

**Comment by IGBC** [comment]
it was a plugin sh*tting its self after the update.

My bad.

**Comment by phy25** [comment]
Well I would recommend creating an issue on https://github.com/dwp-forge/refnotes/issues so that plugin author could fix it.
