### ISSUE TITLE
Media-Manager shows not all Pictures in Namespace

### ISSUE THREAD

**Issue by bgschuetze** [splitbrain/dokuwiki#3207]
As discussed in this thread: https://forum.dokuwiki.org/d/18093-problem-mit-bildern-medienmanager/9
the Media-Manager (when opened in DW-Editor) shows not all Pictures in the Namespace. 
With the Search-Function, these files are found, but only when searched with the correct filename. Wildcards or parts of the filename don't work.

About my DW-System: 
Release rc-2020-06-09 "Hogfather" RC3 
updated from Greebo with the DW-Upgrade Plugin v2020-06-03

**Comment by splitbrain** [comment]
judging from the screenshots it seems some kind of error occurs when showing the first (affected) image. Could be something in the metadata of that file. Can you please:

* upload the affected image here (should be `wiki:oeffentlich:konstruktion:funktionsarten:200.jpg`)
* check your error logs if there's a PHP error logged when listing the directory
* check your javascript console if there's a related java script error

**Comment by bgschuetze** [comment]
Ok, I checked These Things:

- here's the file:
![200](https://user-images.githubusercontent.com/68690087/88284161-395e0580-cced-11ea-8235-bdb7eb867907.jpg)
- the Content of data/Cache/debug.log: 
  `14:07:10 172.30.30.107: checkUpdateMessages(): messages up to date`
`14:07:10 172.30.30.107: require_once() is deprecated. It was called from require() in /var/www/dokuwiki/inc/load.php:147 Autoloading. Do not require() files yourself. should be used instead!`
`14:07:10 172.30.30.107: utf8_stripspecials() is deprecated. It was called from call_user_func() in /var/www/dokuwiki/inc/Input/Input.php:51 dokuwiki\Utf8\Clean::stripspecials() should be used instead!`
- the error console Shows this (I'm not very experienced with JavaScript and Debugging, is there an other error console that you mean?)
![problem6](https://user-images.githubusercontent.com/68690087/88284650-0cf6b900-ccee-11ea-8fa5-2f04aa854ce9.JPG)

I noticed that the html Code, that is produced, suddenly aborts:
![problem5](https://user-images.githubusercontent.com/68690087/88285578-a70b3100-ccef-11ea-8f16-38cee2ad7f7f.JPG)

**Comment by splitbrain** [comment]
The image works fine for me. The Error 500 is the interesting part. Please find the appropriate error log and let us know about the error that's causing the 500. See https://www.dokuwiki.org/bugs#how_to_obtain_additional_info

**Comment by bgschuetze** [comment]
In the apache2 log there's bumping up 1 row:
`[Thu Jul 23 14:34:08.427724 2020] [:error] [pid 16465] [client 172.30.30.107:59451] PHP Fatal error:  Uncaught Error: Call to undefined function xml_parser_create() in /var/www/dokuwiki/inc/JpegMeta.php:1557\nStack trace:\n#0 /var/www/dokuwiki/inc/JpegMeta.php(330): JpegMeta->_parseMarkerXmp()\n#1 /var/www/dokuwiki/inc/JpegMeta.php(151): JpegMeta->getXmpField('dc:title')\n#2 /var/www/dokuwiki/inc/media.php(1756): JpegMeta->getField(Array)\n#3 /var/www/dokuwiki/inc/media.php(1629): media_printimgdetail(Array)\n#4 /var/www/dokuwiki/inc/media.php(719): media_printfile(Array, 255, '')\n#5 /var/www/dokuwiki/inc/template.php(1356): media_filelist('wiki:oeffentlic...', 255, NULL, false, 'natural')\n#6 /var/www/dokuwiki/lib/tpl/dokuwiki/mediamanager.php(40): tpl_mediaContent()\n#7 /var/www/dokuwiki/lib/exe/mediamanager.php(126): include('/var/www/dokuwi...')\n#8 {main}\n  thrown in /var/www/dokuwiki/inc/JpegMeta.php on line 1557, referer: http://172.30.30.207/doku.php?id=wiki:oeffentlich:konstruktion:funktionsarten:start&do=edit`

**Comment by phy25** [comment]
Is this a shared server or your own server? Your environment seems to miss `php-xml`.

**Comment by phy25** [comment]
Looks like php-xml should be enabled by default and your installation for some reason disabled it.

https://github.com/splitbrain/dokuwiki/blob/master/install.php does not have checks against [xml functions](https://www.php.net/manual/en/book.xml.php). Do we want to add checks there?

**Comment by bgschuetze** [comment]
As far as I know, this is a virtual server on our Company's own server. 
I checked this and found that you are right, php-xml was not installed and the apache-mod xml2enc was also not activated!
After installing and activating, now the Media-Manager is working perfectly!

From my point, this is solved. I wanna thank all of you that helped me!!!

The Suggestion to add a check at install makes sense to me, should I let this issue open to discuss it?

**Comment by Klap-in** [comment]
Is this worth adding to the check in the installer?
https://github.com/splitbrain/dokuwiki/blob/44d7799c4ef58930b9c633482fc8a77feb0733c4/install.php#L582-L611
