### ISSUE TITLE
Question: can authPDO be used in combination with LDAP authentication?

### ISSUE THREAD

**Issue by isms-uzl** [splitbrain/dokuwiki#3212]
I.e., similar to the virtualgroups plugin. 

Use case: 
  * users are defined in LDAP directory, but this doesn't include group membership. 
  * information about group membership is stored in a local sqlite database (in fact, a struct schema, only editable by wiki admin/managers)

**Comment by splitbrain** [comment]
this is not the right place for this. please use the forum or mailinglist.
