### ISSUE TITLE
Firefox mobile trying to download fetch.php instead of opening pdf

### ISSUE THREAD

**Issue by FR86** [splitbrain/dokuwiki#3216]
When I use Firefox mobile on Android to navigate to a pdf attachment in my wiki (e.g. https://mypersonalwikiserver/wiki/lib/exe/fetch.php?media=example.pdf), Firefox mobile opens the pdf app, which soon after closes with an error message saying the pdf file cannot be displayed (fetch.php cannot be opened). This issue is not reproducible on dokuwiki.org, ~~where URL rewriting is used~~.
Edit: I tested enabling URL rewriting via the web server, now the error message is displaying the correct filename (unless it is in a namespace, then it shows the namespace + colon as part of the filename it tries to open.
I am not sure whether this is an issue with dokuwiki or Firefox mobile, feel free to close and comment accordingly if I should file a bug over there. If it is an issue with my setup specifically, I apologize for generating noise here.
I am running dokuwiki "Hogfather" on Apache/Debian, but this issue existed in previous versions already.

**Comment by phy25** [comment]
I tried to reproduce the issue - Firefox downloaded the file and attempted to open it (it asks me which PDF app I wanted to use), and the Google Drive PDF app immediately closes itself after I choose it. However if I go to the Files app, the file size is correct and I can open it through there.

Could you take a look at the downloaded file in the Files app to see if the file is actually fine? If it is, I am afraid there's nothing unintended with DokuWiki.

**Comment by FR86** [comment]
Thanks a lot for looking into this. In my case (Android 10), the file does not seem to be downloaded at all, it isn't placed in the download folder. Is there any info I can supply that would shed more light on the situation?
If you're convinced it's not an issue with dokuwiki, do you have any idea what could be going wrong?

**Comment by phy25** [comment]
That download works with other browsers on your phone or on a computer, is that correct?

Since it can't be reproduced on my end, could you use Firefox's Remote Debugging tool to see how the PDF download request goes? https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging

**Comment by FR86** [comment]
Ah well, seems to be a firefox related issue. While trying to setup USB debugging
