### ISSUE TITLE
SMTP Extension / Microsoft Exchange Help

### ISSUE THREAD

**Issue by STI-IT** [splitbrain/dokuwiki#3217]
Hey guys, I'm having some issues with setting up SMTP on my DokuWiki Site. Its running on a windows 10 VM with IIS and iIm trying to send emails through our onsite exchange server using the SMTP extension. I had no issue setting up email with our SNIPE-IT site that's hosted on the same machine so I don't believe it's my configuration. This is the read out of the STMP testing tool. Any suggestions as to where the issue could be at? 

Set: the server
Set: the auth
Set: a message will be sent
Connecting to "mail.exchange.com" at 587
Got: 220 "Exchange Server" Microsoft ESMTP MAIL Service ready at Mon, 3 Aug 2020 08:02:39 -0500
Sent: EHLO "Web Server Name"
Got: 250-"Exchange Server" Hello [IP Address]
Got: 250-SIZE 36700160
Got: 250-PIPELINING
Got: 250-DSN
Got: 250-ENHANCEDSTATUSCODES
Got: 250-STARTTLS
Got: 250-AUTH GSSAPI NTLM
Got: 250-8BITMIME
Got: 250-BINARYMIME
Got: 250 CHUNKING
Sent: STARTTLS
Got: 220 2.0.0 SMTP server ready

Other Information:
DokuWiki version: Release 2020-07-29 "Hogfather"
PHP version 7.3.20

**Comment by Klap-in** [comment]
Do you mean that you try to use this plugin? https://www.dokuwiki.org/plugin:smtp In that case it is more practical to file your issues there as well. If you try something different, it is for me not clear what you try to achieve..

**Comment by STI-IT** [comment]
> Do you mean that you try to use this plugin? https://www.dokuwiki.org/plugin:smtp In that case it is more practical to file your issues there as well. If you try something different, it is for me not clear what you try to achieve..

Im just trying to set up my DokuWiki to send emails through our exchange server and read out is the error message I recive when sending test emails from dokuwiki, and sorry about that I'm brand new to github!

**Comment by splitbrain** [comment]
There is no error shown in the details you posted and you do not give any description of the problem you're having. In any case as this is about a 3rd party plugin this is the wrong place (as @Klap-in already pointed out). I recommend to use the forum first before opening a bug report at the smtp plugin's repository.
