### ISSUE TITLE
Uncaught ReferenceError: tablecalc is not defined

### ISSUE THREAD

**Issue by peetervois** [splitbrain/dokuwiki#3224]
With the release of dokuwiki: Release 2020-07-29 "Hogfather" the TableCalc plugin seems not to work. The debug console on the browser shows that 

Uncaught ReferenceError: tablecalc is not defined

It seems that some plugin related javascript is not included in page.

**Comment by peetervois** [comment]
The plugin misses a action.php file with following contents:

```
<?php
/**
 * DokuWiki Plugin flowcharts (Action Component)
 *
 * @license GPL 2 http://www.gnu.org/licenses/gpl-2.0.html
 * @author  Jakob Schwichtenberg <mail@jakobschwichtenberg.com>
 */

// must be run within Dokuwiki
if (!defined('DOKU_INC')) {
    die();
}

class action_plugin_tablecalc extends DokuWiki_Action_Plugin
{

 public function register(Doku_Event_Handler $controller) {
        $controller->register_hook('TPL_METAHEADER_OUTPUT', 'BEFORE', $this,
                                   '_loadtablecalc');
    }

    public function _loadtablecalc(Doku_Event $event, $param) {
        $event->data['script'][] = array(
                            'type'    => 'text/javascript',
                            'charset' => 'utf-8',
                            '_data'   => '',
                            'src' => DOKU_BASE."lib/plugins/tablecalc/script.js");

    }

}
```

**Comment by Klap-in** [comment]
Please report this issue to the plugin author, via the plugin's wiki page or his contact info. It looks like that this plugin has no public bugtracker.

**Comment by phy25** [comment]
The best way to document this is by adding a comment on the page https://www.dokuwiki.org/plugin:tablecalc and probably update plugin compatibility status per https://forum.dokuwiki.org/d/17863-quick-reminder-what-to-do-when-a-plugin-doesnt-work-on-hogfather.
