### ISSUE TITLE
Unable to upgrade existing 2018-40-22c Greebo release to Hogfather via bitnami helm charts fails with PHP errors

### ISSUE THREAD

**Issue by Be-El** [splitbrain/dokuwiki#3229]
Hi,

we are currently running a Greebo installation based on the 8.0.3 version of the bitnami helm chart. Works flawlessly for us.

With the release of Hogfather and the corresponding helm chart we tried to upgrade, but PHP has some problems:

[Thu Aug 13 09:50:10.703067 2020] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND' 
[Thu Aug 13 09:50:41.247783 2020] [php7:error] [pid 90] [client X.X.X.X:54820] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\plugin\\config\\core\\Setting\\Setting' not found in /opt/bitnami/dokuwiki/inc/deprecated.php:61\nStack trace:\n#0 /opt/bitnami/dokuwiki/inc/load.php(38): require_once()\n#1 /opt/bitnami/dokuwiki/inc/init.php(200): require_once('/opt/bitnami/do...')\n#2 /opt/bitnami/dokuwiki/doku.php(36): require_once('/opt/bitnami/do...')\n#3 {main}\n  thrown in /opt/bitnami/dokuwiki/inc/deprecated.php on line 61 
X.X.X.X - - [13/Aug/2020:09:50:41 +0000] "GET /doku.php HTTP/1.1" 500 - 
[Thu Aug 13 09:50:51.118657 2020] [php7:error] [pid 91] [client X.X.X.X:54902] PHP Fatal error:  Uncaught Error: Class 'dokuwiki\\plugin\\config\\core\\Setting\\Setting' not found in /opt/bitnami/dokuwiki/inc/deprecated.php:61\nStack trace:\n#0 /opt/bitnami/dokuwiki/inc/load.php(38): require_once()\n#1 /opt/bitnami/dokuwiki/inc/init.php(200): require_once('/opt/bitnami/do...')\n#2 /opt/bitnami/dokuwiki/doku.php(36): require_once('/opt/bitnami/do...')\n#3 {main}\n  thrown in /opt/bitnami/dokuwiki/inc/deprecated.php on line 61 
X.X.X.X - - [13/Aug/2020:09:50:51 +0000] "GET /doku.php HTTP/1.1" 500 - 

I reverted back to the former release, upgraded all plugins with pending upgrades and removed unused plugins. But the net upgrade attempt resulted in the same errors.

The stack trace also does not seem to indicate a problem with plugins, but seem to happen without the core classes itself. Removing the troubliing definitions in deprecated.php only results in other downstream errros.

I'm not sure whether this is a dokuwiki problem, or a problem with the docker images created by bitnami.

**Comment by phy25** [comment]
Do you know if your helm chart include the `config` plugin?

**Comment by splitbrain** [comment]
I guess this is better reported at bitnami?

**Comment by phy25** [comment]
https://github.com/splitbrain/dokuwiki/blob/release_stable_2020-07-29/lib/plugins/config/core/Setting/Setting.php

I don't have time to test the helm chart upgrade process, so it would be great if you could ask on their issue tracker as well. If you could add a a link to there in this issue and point it back to here, that would be great.

**Comment by Be-El** [comment]
Thx for having a look at this.

I've reported the issue as bitnami/charts#3433

As far as I understand the chart, it mostly takes care for the setting up the environment, adding passwords etc. It is based on their own docker container, see https://github.com/bitnami/bitnami-docker-dokuwiki.

Regarding the config plugin: there is an lib/plugin/config directory in the kubernetes volume containing the installed plugins:

base   config
author Christopher Smith
email  chris@jalakai.co.uk
date   2015-07-18
name   Configuration Manager
desc   Manage Dokuwiki's Configuration Settings
url    http://dokuwiki.org/plugin:config

**Comment by Klap-in** [comment]
If you install a new version of DokuWiki, it includes already some plugins. These plugins are the ‘bundled plugins’. See for current list: https://github.com/splitbrain/dokuwiki/tree/master/lib/plugins

One of challenges for the Docker approach is that lib/plugins/ could contain a mix of self installed plugins and these bundled plugins. Bundled are only updated if you perform the DokuWiki-upgrade. So if you update the whole wiki, but exclude the lib/plugins folder, your bundled plugins are outdated.

**Comment by Klap-in** [comment]
Btw, one of the ideas is to split these plugins in two folders, which would simplify the situation for a Docker setup, such that it is easier maintainable. But we need yet someone who works on this issue:
https://github.com/splitbrain/dokuwiki/issues/791

**Comment by Be-El** [comment]
Hi,

I was finally able to spend some time on this issue. @Klap-in  was right, the problem was due to stale plugins in the lib/plugins directory. I've moved the whole directory and replaced it with the corresponding directory from the latest stable release. Dokuwiki is now up and running.

I'll also update the bitnami ticket and propose the solution mentioned above.
