### ISSUE TITLE
Add CLI for user managment

### ISSUE THREAD

**Issue by e1mo** [splitbrain/dokuwiki#3233]
It would be great to have a CLI to manage users in the same fashion as it's now possible with extensions. This CLI should work for all backends. That way, you can create users automatically using automation tools such as ansible or your own scripts to create users across numerous services.

The nextcloud CLI could serve as an example of possible commands

```
 user
  user:add                            adds a user
  user:delete                         deletes the specified user
  user:disable                        disables the specified user
  user:enable                         enables the specified user
  user:info                           show user info
  user:list                           list configured users
  user:resetpassword                  Resets the password of the named user
  user:setting                        Read and modify user settings
```

**Comment by phy25** [comment]
I would say PR is welcome.
