### ISSUE TITLE
Charset in Caption-Abstract

### ISSUE THREAD

**Issue by jancla** [splitbrain/dokuwiki#3249]
Why isn't the Caption-Abstract field used in images uploaded to DW? DW seem to clear the content on upload.

Using Mediamanager to enter text in the Caption field works and the text is visible in DW pages, BUT the text is stored in a strange coding not readable in other applications.

Before upload to DW

$ exiftool -Caption-Abstract image-orginal.jpg

gives

Caption-Abstract : Swedish åäö and ÅÄÖ

The same image uploaded to DW and edited in Media Manager taken from /data/media...

$ exiftool -Caption-Abstract image-orginal-dw.jpg

gives

Caption-Abstract : Swedish Ã¥Ã¤Ã¶ and Ã…Ã„Ã–

Looks like mojibaki to me.

I'm on MacOS and Hogfather.

**Comment by Klap-in** [comment]
The metadata fields available in the image metadata editor are defined in this file: https://xref.dokuwiki.org/reference/dokuwiki/nav.html?conf/mediameta.php.html

I guess that these lines provide the caption.
https://github.com/splitbrain/dokuwiki/blob/a3cafac5ceb903787e591f90795b7927a492c09c/conf/mediameta.php#L42-L47

By using `conf/mediameta.local.php` you can overwrite the original definition. If your caption is not recognized, you could try to extend the lookup list of the definition.

About the encoding, the steps were the data is retrieved or stored are listed below. I have no suggestions, maybe others can give better suggestions.
If the metadata editor is shown, the data is retrieved and cleaned by
https://github.com/splitbrain/dokuwiki/blob/a3cafac5ceb903787e591f90795b7927a492c09c/inc/media.php#L166-L167

The input of the form is saved by 
https://github.com/splitbrain/dokuwiki/blob/a3cafac5ceb903787e591f90795b7927a492c09c/inc/media.php#L56-L97
which uses the JpegMeta object, which performs a conversion depending on the type of metadata tag.

**Comment by jancla** [comment]
I looked at the Caption-Abstract field more carefully...

Dokuwiki stores the field in Windows Latin1 encoding. 

exiftool -L -Caption-Abstract image-orginal.jpg  gives

Caption-Abstract                : Swedish åäö and ÅÄÖ

OK, thats a bit disappointing but it's not bug.

It is not possible to copy commented photos to DW media folder and use the metadata without first converting both filename and metadata textfields.

Nowadays, of course, most software use utf-8 so there are no interoperability problems.

The problem seems to have popped up before: https://forum.dokuwiki.org/d/10957-exif-ipct-and-utf8-problem

I'll close this since it's not a bug. The charset used could be configurable, though or at least follow $conf['fnencode'] = 'utf-8';

**Comment by jancla** [comment]
I looked at the Caption-Abstract field more carefully...

Dokuwiki stores the field in Windows Latin1 encoding. 

exiftool -L -Caption-Abstract image-orginal.jpg  gives

Caption-Abstract                : Swedish åäö and ÅÄÖ

OK, thats a bit disappointing but it's not bug.

It is not possible to copy commented photos to DW media folder and use the metadata without first converting both filename and metadata textfields.

Nowadays, of course, most software use utf-8 so there are no interoperability problems.

The problem seems to have popped up before: https://forum.dokuwiki.org/d/10957-exif-ipct-and-utf8-problem

I'll close this since it's not a bug. The charset used could be configurable, though or at least follow $conf['fnencode'] = 'utf-8';

**Comment by phy25** [comment]
This sounds like a feature request to [JpegMeta](https://github.com/sd/jpeg-php), but that library is hardly maintained...

**Comment by jancla** [comment]
Yes, I suppose it's a feature request.... There are many feature requests...

JpegMeta is old and contains to much low level code. It's hard to maintain and should be replaced by a PHP EXIF library. Thats a lot of work.

**Comment by Klap-in** [comment]
Similar library is suggested at this thread: https://github.com/splitbrain/dokuwiki/issues/1970#issuecomment-347030937 and some further development is found in https://github.com/LycheeOrg/php-exif
