### ISSUE TITLE
Allow installing extenions from URL via the CLI

### ISSUE THREAD

**Issue by e1mo** [splitbrain/dokuwiki#3258]
Using the web based extensions manager you can Install plugins straight from a URL. It would be awesome, if this also could be done via the CLI.

# Example / Current beaviour

```
$ php bin/plugin.php extension install https://github.com/YoitoFes/dokuwiki-plugin-oauth/archive/support_keycloak10.zip
✗ Could not find download for https:github.com:yoitofes:dokuwiki-plugin-oauth:archive:support_keycloak10.zip
```

# Expected behaviour

Have it download the Plugin and install it, you could add an option to declare this as an Remote URL not an plugin ID.

**Comment by phy25** [comment]
PR welcome: https://github.com/splitbrain/dokuwiki/blob/f3b7716065e1ddcddead7ba2f14aa2f60161f740/lib/plugins/extension/cli.php#L208-L239

**Comment by locness3** [comment]
Should this be added as an option, or should the URL be detected automatically?

**Comment by Klap-in** [comment]
I’m not sure if I understand your question. You can already install a plugin by providing its name (same name as its wiki page at dokuwiki.org). It will automatically search the download url.

This feature request is about using non-default download urls.

**Comment by locness3** [comment]
Yes. So should it be
```shell
php bin/plugin.php extension install https://github.com/.../support_keycloak10.zip # installs from the URL
php bin/plugin.php extension install addnewpage # finds the download URL, install from it
```
or something like :
```
php bin/plugin.php extension install --url https://github.com/.../support_keycloak10.zip # installs from the URL
php bin/plugin.php extension install addnewpage # finds the download URL, install from it
```
So, should a CLI option be provided to download from the URL, or should the program detect that it's a URL and download that? Sorry for any confusion, first time contributing here.

**Comment by splitbrain** [comment]
The first one

**Comment by locness3** [comment]
Okay. Any recommendations to detect the URL (like, is there any particular function or regex that could be used)?

**Comment by splitbrain** [comment]
Naa, a simple `/https?:\/\//i`should be fine.

**Comment by Klap-in** [comment]
Or this function can be used https://github.com/splitbrain/dokuwiki/blob/8b2b6356d13f827032c82b7376a41bd0e56e3850/inc/media.php#L108

**Comment by splitbrain** [comment]
@Klap-in no, because our HTTP client does not support FTP ;-)
