### ISSUE TITLE
Incomplete toolbar with ldap authentification

### ISSUE THREAD

**Issue by eclyspe** [splitbrain/dokuwiki#3263]
DokuWiki : Release 2020-07-29 "Hogfather"
LDAP Auth Plugin up to date

While using ldap authentification, the toolbar used to edit pages is incomplete when the user has a non-ASCII character in his name.

**Browser errors** 
SyntaxError: expected expression, got ';'  doku.php:24:31
ReferenceError: JSINFO is not defined      js.php:1:93942

**Source code of the page** 
`<script >/*<![CDATA[*/var NS='something';var SIG=;var JSINFO = <SOME VALID JSON>;
/*!]]>*/</script>`

The problem seems to be in inc/toolbar.php, in toolbar_signature()
https://github.com/splitbrain/dokuwiki/blob/656cb03223898bc17f215be41d3e697d2b9fbed1/inc/toolbar.php#L267-L274

This doesn't return a string, as json_encode() expects a valid UTF8 string and  `$INFO['userinfo']['name']` appears to contain latin1.

I don't know if the problem is really in the plugin or in DokuWiki, but maybe the return value of json_encode should be checked.

**Workaround**
Don't put `@NAME@` in the signature.

**Comment by splitbrain** [comment]
Can you try switching the LDAP version to 3?

**Comment by eclyspe** [comment]
I switched the LDAP version to 3, reconnected and it worked. Thank you !

Should I close this issue or would you like to keep it opened  ?

**Comment by splitbrain** [comment]
Interesting. LDAP 3 mandates UTF-8 connections apparantly LDAP 2 doesn't. Ususally LDAP 2 still uses UTF-8. :shrug: I'm glad it works for you.
