### ISSUE TITLE
Please add my language (ckb)

### ISSUE THREAD

**Issue by qezwan** [splitbrain/dokuwiki#3275]
Hi
My language (ckb) is not one among the available languages for Dokuwiki, and I'd like to help in translation. Please add it .
Thanks!

**Comment by lpaulsen93** [comment]
Did you have a look at https://translate.dokuwiki.org/? If you select _"Showing translation status for"_ there is the language _"Central kurdish, Sorani"_. You can use the translation tool to give translations to the project which can then be merged.

**Comment by qezwan** [comment]
Thanks so much.

**Comment by Klap-in** [comment]
Thank you for the big contribution to the translations!
