### ISSUE TITLE
Add ckb language

### ISSUE THREAD

**Issue by qezwan** [splitbrain/dokuwiki#3283]
Hi Dokuwiki 
Please add **ckb** language  option on download page .
https://download.dokuwiki.org/

Regards.

**Comment by Klap-in** [comment]
This is actually an issue for https://github.com/splitbrain/download.dokuwiki.org/ But of course that repository is difficult to find, so I will respond here. 

That download page uses the function:
https://github.com/splitbrain/download.dokuwiki.org/blob/b386d89bca6b9149f58d170784e679ba805f88f1/lib/Template.php#L25-L37

It is a function that searches the folder: `/stable/inc/lang/` for languages. Your big contribution add the language files for the development version of DokuWiki (Thanks!). These are not automatically included in the existing downloads of stable version of DokuWiki.

If you would use these for your own wiki based on a stable version of DokuWiki, you can just copy-paste the language `ckb` folder from a download of the development version to your current wiki and most strings will be found. For development this is too much work, so we only provide updates of languages with upgrades of DokuWiki.

**Comment by moisesbr-dw** [comment]
_The following comment is in #3281 ([link](https://github.com/splitbrain/dokuwiki/pull/3281#issuecomment-703949738)), already merged. I moved it here so it can be more visible._


@Klap-in, I'd like to remember an issue regarding language codes.

New translations should be checked against [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) (for 2-letter codes) or [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3) (for 3-letter codes), to prevent problems such as those in #3242 and #3252.

This update represents no problem at all, as `ckb` is present in ISO 639-3.

I'd like to inform @splitbrain and @phy25 about this too.

Best regards,
-- Moisés

**Comment by Klap-in** [comment]
Yeah, I understand, but it is also some work to implement these ideas...

**Comment by moisesbr-dw** [comment]
As new translations seldom appear, this work can be manual.

For a 2-letter code, consult the table
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#Table_of_all_possible_two_letter_codes

For a 3-letter code, do a Ctrl-F in the page
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Languages/List_of_ISO_639-3_language_codes_(2019)

**Comment by Klap-in** [comment]
Sure, for the languages in DokuWiki itself it is easy. But there are also ~1300 plugins and ~140 templates, which could contain language strings. e.g. for `no`: https://codesearch.dokuwiki.org/search?project=dokuwiki&project=plugin&project=template&q=&defs=&refs=&path=lang%2Fno%2F&hist=&type=
To change these files manual is a lot of work, and some plugins are slow with accepting changes. Which means that more wikis will be affected if you do only renaming. So therefore it is easier to implement a fallback mechanism that creates some aliases in the background in the language handling of dokuwiki. What means someone should built this :-)
