### ISSUE TITLE
Cannot Update Pages, Save/Preview/Cancel buttons don't work

### ISSUE THREAD

**Issue by clintiepoo** [splitbrain/dokuwiki#3314]
dokuwiki is running on a raspberry pi in docker (linuxserver/dokuwiki).

When I edit a page, any changes I make aren't saved. When I click save, preview, or cancel, the buttons don't do anything and the page is unaffected.

This is the second time this has happened. Last time I had to completely wipe and rebuild the wiki. I'm hoping to avoid that this time.

**Comment by phy25** [comment]
What plugins do you have? Could you open your browser javascript console (F12) to see if there's any error?

**Comment by splitbrain** [comment]
Note: there is another user having problems with this docker container: https://forum.dokuwiki.org/d/18312-search-index-only-refreshes-after-a-page-is-edited 

I haven't looked into it yet, but their setup might be weird.

**Comment by clintiepoo** [comment]
@phy25  - I do see an error as I page around in the console: 
`doku.php?id=start&do=admin:322 GET http://192.168.1.194:8282/data/dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.png 404 (Not Found)`

Plugins are pretty minimal: 

- ACL Manager
- authpdo plugin
- Plain Auth Plugin
- Bootstrap Wrapper Plugin 
- Configuration Manager 
- Extension Manager
- Indexmenu Plugin
- Info Plugin 
- numberof plugin
- Popularity Feedback Plugin 
- PDF.js
- Revert Manager
- safefnrecode plugin
- Searchindex Manager 
- styling plugin 
- User Manager

**Comment by clintiepoo** [comment]
Hey guys, what more info is required? This is still broken for me.

**Comment by phy25** [comment]
Someone has to spend time reproducing and  troubleshooting this but unfortunately I don't have time. Since this is Do ker, could you open another container on the same hardware and on a different hardware to see if it's still happening? If both answer is yes, it's an upstream issue, otherwise it's more complicated.

**Comment by clintiepoo** [comment]
I think I'm going to move to a different wiki instead of fiddling with this. Thanks for your help.
