### ISSUE TITLE
"Forbidden" message when saving a page

### ISSUE THREAD

**Issue by alexey-vladilenov-sokolov** [splitbrain/dokuwiki#3322]
I ran into a problem (though it could be some unknown feature): when using some special words (login, password, SQL commands) I get "Forbidden" message when trying to save the page. I just now upgraded to the last version of dokuwiki but the problem persists.
For example the following paragraph:

Install postgresql11-contrib package. Then using admin rights (''postgres'') add the extension to DB.
  CREATE EXTENSION IF NOT EXISTS pgcrypto;
Function crypto() must be used to calculate password hashes and check a password against a hash:
  UPDATE account SET password_hash = crypt('new password', gen_salt('md5')) where .....;
  SELECT (password_hash = crypt('entered password', password_hash ))
    AS match FROM account;

In this paragraph the words SELECT & FROM are dangerous (give them character spacing and you will solve the problem).
The only annoying thing is that you can not guess exact combination which causes the deadlock.  To save a passage I need repeatedly remove word by word and try to save a page.

**Comment by phy25** [comment]
See https://www.dokuwiki.org/faq:mod_security. If you feel that this is a DokuWiki issue, please reopen and provide more details on your server.
