### ISSUE TITLE
Moment.js Vulnerability

### ISSUE THREAD

**Issue by BaileyMatt** [splitbrain/dokuwiki#3328]
**Describe the bug**
Moment.js version 2.18.1 is used on the site with 1 known low vulnerability. Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS). It used a regular expression (/[0-9]*['a-z\u00A0-\u05FF\u0700-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+|[\u0600-\u06FF\/]+(\s*?[\u0600-\u06FF]+){1,2}/i) in order to parse dates specified as strings. This can cause a very low impact of about 2 seconds matching time for data 50k characters long.

**To Reproduce**
(There are a few methods but I have used Google Lighthouse)

Go to any website running Dokuwiki using a Chromium based browser.
Click F12
Scroll along the tabs to Lighthouse
Untick all bar 'Best Practices'
Click Generate Report
Scroll down to the bottom section which outlines Trust & Safety.
See vulnerability

**Expected behavior**
It would be expected that there are no vulnerabilities listed in the section.

**Screenshots**
![image](https://user-images.githubusercontent.com/60200588/97886923-2366d480-1d21-11eb-8757-10e56665d576.png)

**Desktop:**
OS: Windows 10
Browser Google Chrome
Version 86

**Additional context**
Further reading around the library: https://snyk.io/vuln/npm:moment?lh=2.18.1&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit

Version of Dokuwiki used: Release 2020-07-29 "Hogfather"

**Comment by phy25** [comment]
What is PWM? How is that related to DokuWiki? Could you provide a link to the website you are having issues with?

**Comment by BaileyMatt** [comment]
Sorry I made a typo. This is for Dokuwiki.

**Comment by phy25** [comment]
There is no moment.js as far as I can tell in DokuWiki: https://github.com/splitbrain/dokuwiki/search?l=JavaScript&q=moment&type=

Again, could you provide a link to the website you are having issues with?

**Comment by BaileyMatt** [comment]
Hello, 

Our site is internal and not available from the internet but I can share this site with you which is identical and also presents the same issue. 

https://wiki.rightdigitalsolutions.com/doku.php

Thanks

**Comment by splitbrain** [comment]
dokuwiki does not use moment.js. A plugin installed in your wiki might. You need to figure out which one and raise this issue with its maintainer.
