### ISSUE TITLE
Sessions and PHP 7.4

### ISSUE THREAD

**Issue by bradbulger** [splitbrain/dokuwiki#3329]
I am testing a migration from PHP 7.0 to 7.4. We use MantisBT for authentication, which I imagine is related to this issue. I find that the call to session_name() and the related code in init_session() is giving me an error, saying that a session already exists. It probably was always like that, and it's just that now PHP reports it as an error.

If I don't run the session calls in that function when a session already exists, everything seems to be fine. I can log in as different users, they show up in the history of changes to a page, so forth. I just wonder if there will be other complications.

**Comment by phy25** [comment]
Sounds like you are using `plugin:authmantis`? I am honestly not sure if DokuWiki should check this, or the plugin should handle the session.

See also: https://www.dokuwiki.org/devel:session_handling

**Comment by bradbulger** [comment]
Ah, it closes the session eventually anyway? Normally, I mean. So it might work to close it first. I don't know how that will interact with Mantis, but it does seem like a thing for the authmantis plugin to work out if it can.

**Comment by phy25** [comment]
I am going to close this since for now to fix your issue, the plugin should do something. If you have other ask, please reopen the issue.
