### ISSUE TITLE
PHP 7.4 error with extension plugin and custom plugin

### ISSUE THREAD

**Issue by bradbulger** [splitbrain/dokuwiki#3330]
helper_plugin_extension_repository::getData() look for information about plugins at www.dokuwiki.org. For custom plugins that aren't on the site, the result is an empty array. The function tries to serialize $result[0], which doesn't exist. In PHP 7.4 (at least) this results in a PHP error about the undefined offset.

**Comment by phy25** [comment]
https://github.com/splitbrain/dokuwiki/blob/31a58aba4c24b34c34ad5764d1a35b7c398c3a2c/lib/plugins/extension/helper/repository.php#L111

**Comment by locness3** [comment]
So isntead of checking the data is not false, we also check it's not an empty array?
