### ISSUE TITLE
session cookies lost behind proxy

### ISSUE THREAD

**Issue by doubledgedboard** [splitbrain/dokuwiki#3334]
Hello,

I'm using a cloudflare worker proxy to proxy requests to my private dokuwiki server on a non-standard port.

Everything works beautifully when hitting dokuwiki directly, however when visiting through the proxy, I noticed my session regularly gets dropped (The login cookie disappears) and I have to re-authenticate.

I believe that requests from the proxy are coming from various different endpoints (IP addresses).

Can anyone confirm if e.g. REMOTE_ADDR or similar is tied to session cookies, and if so, how do I bypass or address that behavior so that a user's session persists even if it moves IP addresses?

**Comment by phy25** [comment]
Yes, it's used as part of the browser fingerprint. Please try again after configuring https://www.dokuwiki.org/config:trustedproxy

Next step before closing this: Call out in the doc that this impacts login

**Comment by doubledgedboard** [comment]
Thanks for the link. Unfortunately with the long list of IPs that cloudflare uses (https://www.cloudflare.com/ips/) it doesn't appear that there's a straightforward way to configure the regex for these diverse IPs without also allowing many IPs outside of those ranges.

**Comment by phy25** [comment]
I have updated the wiki.
