### ISSUE TITLE
Error upon saving config settings page.

### ISSUE THREAD

**Issue by witchka** [splitbrain/dokuwiki#3338]
> Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in /[...]/lib/plugins/config/core/Writer.php on line 79
Settings updated successfully.

> Warning: Cannot modify header information - headers already sent by (output started at /[...]/lib/plugins/config/core/Writer.php:79) in /[...]/inc/common.php on line 1975

Per the forum thread I was asked to put this here: https://forum.dokuwiki.org/d/18490-strange-error-upon-saving-config-page

**Comment by phy25** [comment]
A quick fix is to add `@` to this line, I guess.

https://github.com/splitbrain/dokuwiki/blob/2b1010d577d6e06cf6b5e2872eb76ecbb017d77c/lib/plugins/config/core/Writer.php#L79
