### ISSUE TITLE
found malicious files

### ISSUE THREAD

**Issue by dvarrel** [splitbrain/dokuwiki#3352]
hi,
i 've found some files named .xxxx.ico and modified php files with @includes .xxxx.ico inside, in  data folder :

a script name "check-site.pl" helps me to found infected files :

https://github.com/JavierElices/php-renamer-malware

Release 2020-07-29 "Hogfather"
Apache/2.4.46 (Ubuntu) 
PHP version: 7.4.12

**Comment by mprins** [comment]
check your log files to find out what happened, these files are not part of DW.

**Comment by dvarrel** [comment]
thanks
In my apache log, i've got this :
51.81.54.76 - - [29/Nov/2020:19:35:37 +0100] "GET /doku HTTP/1.1" 301 539 "-" "Python-urllib/2.7"
51.81.54.76 - - [29/Nov/2020:19:35:38 +0100] "GET /doku/ HTTP/1.1" 302 540 "-" "Python-urllib/2.7"

**Comment by splitbrain** [comment]
Yeah sorry. There is nothing substantial here that helps us to even understand what happened.

You need to dig further into this.

* which process created the files (ownership may help)
* when were they created?
* what (access) logs were written at that time?
* which of the log entries seem to be the requests that lead to the file creation?
* was it actually a DokuWiki mechanism that created the file?
* if so, where standard security measurements like ACLs and webserver access correctly in place?

Without this, there is no way we can figure out what happened and if it is actually an issue with DokuWiki.

**Comment by dvarrel** [comment]
thank you , i must improve....

**Comment by dvarrel** [comment]
Hi, i found in access.log , this request at the time files were created :
`103.244.44.111 - - [01/Dec/2020:21:02:58 +0100] "POST /?lvt=iyeun HTTP/1.1" 302 223 "http://varrel.fr/?lvt=iyeun" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1"
103.244.44.111 - - [01/Dec/2020:21:02:59 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?lvt=iyeun" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1"
103.244.44.111 - - [01/Dec/2020:21:02:59 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?lvt=iyeun" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1"
103.244.44.111 - - [01/Dec/2020:21:03:00 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?lvt=iyeun" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1"
138.201.19.137 - - [01/Dec/2020:21:03:00 +0100] "POST /?lvt=iyeun HTTP/1.1" 302 223 "http://varrel.fr/?lvt=iyeun" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
138.201.19.137 - - [01/Dec/2020:21:03:00 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?lvt=iyeun" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
138.201.19.137 - - [01/Dec/2020:21:03:00 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?lvt=iyeun" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
138.201.19.137 - - [01/Dec/2020:21:03:00 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?lvt=iyeun" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
191.232.215.64 - - [01/Dec/2020:21:03:05 +0100] "POST /station/galerie/images/ym0lwega.php HTTP/1.0" 200 541 "http://varrel.fr/station/galerie/images/ym0lwega.php" "Mozilla/5.0 (Windows NT 6.1; rv:54.0) Gecko/20100101 Firefox/54.0"
159.148.27.30 - - [01/Dec/2020:21:03:07 +0100] "POST /?crl=yuxza HTTP/1.1" 302 223 "http://varrel.fr/?crl=yuxza" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1"
159.148.27.30 - - [01/Dec/2020:21:03:07 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?crl=yuxza" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1"
159.148.27.30 - - [01/Dec/2020:21:03:07 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?crl=yuxza" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1"
159.148.27.30 - - [01/Dec/2020:21:03:07 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?crl=yuxza" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1"
205.233.59.204 - - [01/Dec/2020:21:03:08 +0100] "POST /?crl=yuxza HTTP/1.1" 302 223 "http://varrel.fr/?crl=yuxza" "Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1"
205.233.59.204 - - [01/Dec/2020:21:03:08 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?crl=yuxza" "Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1"
205.233.59.204 - - [01/Dec/2020:21:03:09 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?crl=yuxza" "Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1"
205.233.59.204 - - [01/Dec/2020:21:03:09 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?crl=yuxza" "Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1"
192.169.233.196 - - [01/Dec/2020:21:03:10 +0100] "POST /?sjym=zpou HTTP/1.1" 302 223 "http://varrel.fr/?sjym=zpou" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
192.169.233.196 - - [01/Dec/2020:21:03:11 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?sjym=zpou" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
192.169.233.196 - - [01/Dec/2020:21:03:11 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?sjym=zpou" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
192.169.233.196 - - [01/Dec/2020:21:03:11 +0100] "GET /doku/doku.php HTTP/1.1" 200 5802 "http://varrel.fr/?sjym=zpou" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
176.31.124.115 - - [01/Dec/2020:21:03:12 +0100] "POST /?sjym=zpou HTTP/1.1" 302 223 "http://varrel.fr/?sjym=zpou" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.3 Safari/534.53.10"
176.31.124.115 - - [01/Dec/2020:21:03:12 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?sjym=zpou" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.3 Safari/534.53.10"
176.31.124.115 - - [01/Dec/2020:21:03:12 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?sjym=zpou" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.3 Safari/534.53.10"
176.31.124.115 - - [01/Dec/2020:21:03:12 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?sjym=zpou" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.3 Safari/534.53.10"
37.187.111.123 - - [01/Dec/2020:21:03:12 +0100] "POST /?gtz=ayb HTTP/1.1" 302 223 "http://varrel.fr/?gtz=ayb" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
37.187.111.123 - - [01/Dec/2020:21:03:12 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?gtz=ayb" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
37.187.111.123 - - [01/Dec/2020:21:03:12 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?gtz=ayb" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
37.187.111.123 - - [01/Dec/2020:21:03:12 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?gtz=ayb" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
162.144.220.103 - - [01/Dec/2020:21:03:13 +0100] "POST /?gtz=ayb HTTP/1.1" 302 223 "http://varrel.fr/?gtz=ayb" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
162.144.220.103 - - [01/Dec/2020:21:03:13 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?gtz=ayb" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
162.144.220.103 - - [01/Dec/2020:21:03:14 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?gtz=ayb" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
162.144.220.103 - - [01/Dec/2020:21:03:14 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?gtz=ayb" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
138.68.56.76 - - [01/Dec/2020:21:03:15 +0100] "POST /?bpqzi=jled HTTP/1.1" 302 223 "http://varrel.fr/?bpqzi=jled" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
138.68.56.76 - - [01/Dec/2020:21:03:16 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?bpqzi=jled" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
138.68.56.76 - - [01/Dec/2020:21:03:16 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?bpqzi=jled" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
138.68.56.76 - - [01/Dec/2020:21:03:16 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?bpqzi=jled" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
192.138.189.190 - - [01/Dec/2020:21:03:17 +0100] "POST /?bpqzi=jled HTTP/1.1" 302 223 "http://varrel.fr/?bpqzi=jled" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
192.138.189.190 - - [01/Dec/2020:21:03:17 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?bpqzi=jled" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
192.138.189.190 - - [01/Dec/2020:21:03:18 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?bpqzi=jled" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
192.138.189.190 - - [01/Dec/2020:21:03:18 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?bpqzi=jled" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
144.208.75.41 - - [01/Dec/2020:21:03:19 +0100] "POST /?gip=ico HTTP/1.1" 302 223 "http://varrel.fr/?gip=ico" "Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G935F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.4 Chrome/51.0.2704.106 Mobile Safari/537.36"
144.208.75.41 - - [01/Dec/2020:21:03:19 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?gip=ico" "Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G935F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.4 Chrome/51.0.2704.106 Mobile Safari/537.36"
144.208.75.41 - - [01/Dec/2020:21:03:19 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?gip=ico" "Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G935F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.4 Chrome/51.0.2704.106 Mobile Safari/537.36"
144.208.75.41 - - [01/Dec/2020:21:03:19 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?gip=ico" "Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G935F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.4 Chrome/51.0.2704.106 Mobile Safari/537.36"
91.134.188.37 - - [01/Dec/2020:21:03:20 +0100] "POST /?gip=ico HTTP/1.1" 302 223 "http://varrel.fr/?gip=ico" "Mozilla/5.0 (Windows NT 6.1; rv:54.0) Gecko/20100101 Firefox/54.0"
91.134.188.37 - - [01/Dec/2020:21:03:20 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?gip=ico" "Mozilla/5.0 (Windows NT 6.1; rv:54.0) Gecko/20100101 Firefox/54.0"
91.134.188.37 - - [01/Dec/2020:21:03:20 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?gip=ico" "Mozilla/5.0 (Windows NT 6.1; rv:54.0) Gecko/20100101 Firefox/54.0"
91.134.188.37 - - [01/Dec/2020:21:03:20 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?gip=ico" "Mozilla/5.0 (Windows NT 6.1; rv:54.0) Gecko/20100101 Firefox/54.0"
94.130.10.20 - - [01/Dec/2020:21:03:20 +0100] "POST /?jkoml=ath HTTP/1.1" 302 223 "http://varrel.fr/?jkoml=ath" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
94.130.10.20 - - [01/Dec/2020:21:03:20 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?jkoml=ath" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
94.130.10.20 - - [01/Dec/2020:21:03:20 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?jkoml=ath" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
94.130.10.20 - - [01/Dec/2020:21:03:20 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?jkoml=ath" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
79.137.34.146 - - [01/Dec/2020:21:03:20 +0100] "POST /?jkoml=ath HTTP/1.1" 302 223 "http://varrel.fr/?jkoml=ath" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
79.137.34.146 - - [01/Dec/2020:21:03:20 +0100] "GET /doku HTTP/1.1" 301 563 "http://varrel.fr/?jkoml=ath" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
79.137.34.146 - - [01/Dec/2020:21:03:20 +0100] "GET /doku/ HTTP/1.1" 302 572 "http://varrel.fr/?jkoml=ath" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
79.137.34.146 - - [01/Dec/2020:21:03:20 +0100] "GET /doku/doku.php HTTP/1.1" 200 5803 "http://varrel.fr/?jkoml=ath" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
`

**Comment by splitbrain** [comment]
This line looks suspicious:

`191.232.215.64 - - [01/Dec/2020:21:03:05 +0100] "POST /station/galerie/images/ym0lwega.php HTTP/1.0" 200 541 "http://varrel.fr/station/galerie/images/ym0lwega.php" "Mozilla/5.0 (Windows NT 6.1; rv:54.0) Gecko/20100101 Firefox/54.0"`

From what I can see, your wiki resides in `/doku/`. That post goes to something within `/station/` which seems to be something else. It is a post on a PHP file with a very strange name and it is answered with a 200 status code, so it was successful.

However the URL no longer seems to exist, I am now getting a 404 for it. Maybe you removed it?

My guess is that this line is not the actual break in. Instead something created that `ym0lwega.php` file before. The URL suggests that it was maybe uploaded in an image gallery? You need to go further back in the logs to see if you can figure out when this file was created. Maybe also have a look at what requests came from the same IP before.

To me it seems the break-in happened at the `/station/` software but it can't be said for sure without the earlier logs.

PS: the other POST logs with the weird parameters are suspicous too, but seem not to create any actual issues - they simply redirect back to the wiki.

**Comment by dvarrel** [comment]
thank you for your help !

**Comment by Rainbow-Spike** [comment]
Dokuwiki never tires of proving that it is seriously protected from being stabbed from the outside

Against a stab in the back, any code is powerless except the completely paranoid
