### ISSUE TITLE
Google Chrome adding line-break after triple-clicking text in code boxes

### ISSUE THREAD

**Issue by Espionage724** [splitbrain/dokuwiki#3357]
I don't think this is DokuWiki-specific, but I wonder if there's a setting I can toggle to change this behavior?

In Chrome, if I triple-click text in code boxes and copy/paste it into something, a line-break is added. [I have a test wiki page](https://wiki.realmofespionage.xyz/notes:chome_text_test) to show this, but it can also be reproduced right here:

```
Here is a test line
```

Triple-click it the above line, copy it (Ctrl + C), and paste it (Ctrl + V) into a text editor. It adds a new-line with the text.

Firefox on both Windows and Linux doesn't do this (it only selects the text in the code box, and doesn't add any spaces at the end or line-break). I'm wondering if anyone knows a way to stop Chrome from doing this, either via DokuWiki itself, or from a Chrome setting globally?

**Comment by phy25** [comment]
I assume your question is similar to https://github.com/splitbrain/dokuwiki/issues/2838. There's nothing we can do about it except overriding the behavior somehow which is out of scope of DokuWiki core.

**Comment by Espionage724** [comment]
Yeah that looks like the same issue. I ended up installing the [Copycode Plugin](https://www.dokuwiki.org/plugin:copycode) which seems to help with this.
