### ISSUE TITLE
DokuWiki Setup Error Something unforeseen has happened: Maximum action transitions reached

### ISSUE THREAD

**Issue by gen2** [splitbrain/dokuwiki#3362]
I tried to upgrade our DokiWiki installations from 20180422b to 20200729 by using the Gentoo standard "`webapp-config ... -U ...`" procedere, and i'm running constantly into

> 
> **DokuWiki Setup Error**
> 
> Something unforeseen has happened: Maximum action transitions reached
> 

(and that's it.)

A new installation works like a charm, so my current setup (apache, php) shouldn't be the problem here.

Is there any chance to get a more detailed error log explaining what's going wrong here? I've some really well used documentation spaces, and there's no way to copy all the stuff manually w/o going mad...

**Comment by Chewie9999** [comment]
Are you using LDAP for logins? If so, can you disable it and see if that makes any difference?
I'm trying to set up LDAP on the same version (never tried before), and am running into the same problem, and I don't seem to be able to generate any [debug info](https://www.dokuwiki.org/devel:debugging)

**Comment by gen2** [comment]
Hi folks, i tested further (all tests are exercised by using the standard Gentoo `webapp-config` tool), and i got some interesting results:

1. i was able to install version 20180422b, and upgraded to version 20200729 - it works
2. i was able to downgrade to version 20180422b w/o problem - it just works
3. i changed the template to the former DokuWiki standard template named _default_  (all my wikis use this template because i don't want to waste space on my screen) - it works
4. i upgraded to version 20200729 - FAILURE
5. i downgraded to version 20180422b - it works again
6. i changed the template to the new default tamplate named _dokuwiki_ and upgraded to version 20200729 - FAILURE
7. i downgraded to version 20180422b - it works again
8. i changed template to the former DokuWiki standard template named _default_ - it still works

It seems the use of the former DokuWiki standard template named _default_  pollutes the installation and make an upgrade to version 20200729 impossible.

Any help to come out of this deadlock is highly appreciated!

@Chewie9999: i use a MySQL database for authorization, LDAP/AD is not involved here.

**Comment by gen2** [comment]
One more observation: disabling my standard (old?) `authmysql ` value for `$conf['authtype']` shows at least the start (i.e. login) page again.

**Comment by micgro42** [comment]
> One more observation: disabling my standard (old?) `authmysql ` value for `$conf['authtype']` shows at least the start (i.e. login) page again.

The authmysql plugin is marked as deprecated on https://www.dokuwiki.org/plugin:authmysql since 2016. Can you try the authpdo plugin? See https://www.dokuwiki.org/plugin:authpdo


If the authmysql is broken with the new release, we should probably do something about that. Maybe remove it? cc @splitbrain @Klap-in

**Comment by splitbrain** [comment]
authmysql has been removed in the last stable release already.
