### ISSUE TITLE
showSecurityCheck can trigger IP ban on shared hosting

### ISSUE THREAD

**Issue by PhilippImhof** [splitbrain/dokuwiki#3363]
The function `showSecurityCheck` in `inc/Ui/Admin.php` tries to load `dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.png`. If the server is correctly configured, this will trigger a 403 error. Certain shared hostings are configured to ban IP addresses that trigger more than a certain number of 403 (or similar) errors in a certain period, e.g. more than 3 in 1 hour. See https://talk.plesk.com/threads/dokuwiki-gets-my-banned-from-my-plesk-server.359022 for one example (this is not me).

I think that the method is very good to inform users about a potential security risk. However, it has the downside of locking people out of their Wiki as a consequence of having a good configuration. (And they have no possibility to deactivate those Plesk bans.)

I would suggest the following: 
* The function is only executed every 10th or 100th time the admin page is accessed.
* The admin page shows a button "check the security" to trigger the check manually.

Also, I'd suggest that the `showSecurityCheck` function can be entirely disabled in the config. (With a bold warning message, of course.)

**Comment by Klap-in** [comment]
Of course this is annoying if seen this at your shared hosting, but it feels for me quite strange to limit the number of these errors? Is it reasonable to put effort in these kind of hostings? I think it is not worth the clutter for all our other users to introduce an config settings especially for this very corner case. At most I think a`if(!defined('VAR_TO_PREVENT_403')) ...` is worth this case.

As workaround you can disable this check by just commenting this line:
https://github.com/splitbrain/dokuwiki/blob/413313a1557b246296ce666c3c01263a139988e1/inc/Ui/Admin.php#L31

Disadvantage of manually commenting this line is that you have to redo it after every wiki upgrade. So make for example a note that this change is needed.  

Btw, this check is only performed if you visit the admin overview page.

**Comment by PhilippImhof** [comment]
> it feels for me quite strange to limit the number of these errors?

I do not think it is a good strategy, but I can see the reasoning behind it, as it will block bots and scripts that probe for files.

> Is it reasonable to put effort in these kind of hostings? I think it is not worth the clutter for all our other users to introduce an config settings especially for this very corner case. At most I think a`if(!defined('VAR_TO_PREVENT_403')) ...` is worth this case.

As the problem mainly occurs while installing and setting up DokuWiki, people are probably more likely to switch to another software than to change their hosting provider with all the consequences that has. Especially if they send a support request and the answer is likely to be: DokuWiki is doing it wrong, we cannot help you.

The setting does not have to be made visible. It can be something one can add, if they encounter the problem. An easy solution could be to have an empty `.no_security_check_needed` file in the same directory. If this file is present, we show a banner saying that the security check is disabled; with a link showing how to enable it again.

> As workaround you can disable this check by just commenting this line:
> https://github.com/splitbrain/dokuwiki/blob/413313a1557b246296ce666c3c01263a139988e1/inc/Ui/Admin.php#L31

That's what I did, but I don't think every user knows how to solve that. (At least now this issue will show up when they perform a Google search.)

I will try to come up with a PR in the near future if you are OK with my suggestion.

**Comment by PhilippImhof** [comment]
I would not want to publicly put the blame on them, but you are right that this might help people with a similar problem. I experienced the problem on a server hosted by a Swiss hoster called [ServerTown](https://servertown.ch/), but as the linked forum post in my starting comment shows, this also happens to other people.

**Comment by splitbrain** [comment]
Interestingly enough I might have encountered the same problem at a customer's server today. This might be a new default setting for Plesk systems which would make this a pretty huge problem. I don't think #3365 is the right way to address this.

If this is gonna impact all Plesk users, we need to rethink the whole mechanism.

**Comment by PhilippImhof** [comment]
I agree that if this is the case, the problem deserves a proper solution rather than a workaround. What do you think of the following idea: 

We place an empty file in the `data` directory. On each invocation, `showSecurityCheck` checks the `mtime` of that file. If it is older than a certain threshold, e.g. 3 hours, the function executes normally, i. e. it shows the warning banner if needed (or shows nothing, because the configuration is fine) and touches the file. Otherwise, the function simply returns.

That would IMHO be a good solution. The user has nothing to do, the warning is not generally suppressed, but the forbidden file is not accessed often enough for the ban to be triggered. And it is simple.

**Comment by splitbrain** [comment]
Hmm yeah, something in that direction. However we have multiple requirements:

* avoid too many checks, to not trigger the block
* a negative result info (ie. data is insecure) should not suddenly vanish - a user might overlook or ignore it for a bit to finish their admin task, when they come back the warning should still be visible
* a positive result should be rechecked frequently
* users need a way to immediate recheck (because they adjusted their server config and want to make sure it's okay)

However, only positive results are actually problematic because they are the ones that run into a 403. This means we only need to ensure to not rerun positive checks too often. A bit of JavaScript caching a positive result in the session storage and preventing the further loading of the image could work.

**Comment by PhilippImhof** [comment]
I suggest the following: (positive = config is OK, no warning to be shown)

#### First invocation
* perform check as it is now
* if check is positive
  * create status file in `data` dir 
  * show nothing, as it is now
* if check is negative
  * remove the status file, as the check can be repeated without limitation
  * output: current warning banner

#### Subsequent invocations
* check the status file
* if it is not present or its `mtime` is older than the threshold: perform the check as described above, no need to worry about a possible ban
* otherwise: show positive output
  * picture with a green checkmark plus tooltip with message saying that security was checked (with date/time), the check was positive and that it can be repeated by clicking the image <img align="right" src="https://user-images.githubusercontent.com/52650214/103621873-2dca6800-4f36-11eb-9b63-a7dd1a55c64b.png" width="80" height="80">
  * click might additionally show a popup saying something like "repeating a positive check too often in a short time might lead to your IP being banned."
  * clicking the image leads to a forced run

#### Forced run (after click)
The easiest would probably be to have a short independent PHP script that
* removes the status file
* issues a `Location` header to take the user back to the admin page 
As the status file is gone by now, the check is executed normally.


#### Downside

Currently, no news is good news. The user is never informed about a positive check. With the change outlined above, a new element will show up in the admin tool, so we should find a way to have that as small and as unintrusive as possible.  I am most certainly not the right guy to do this :)
