### ISSUE TITLE
Stylesheet generated by css.php contains warning on PHP 8

### ISSUE THREAD

**Issue by dregad** [splitbrain/dokuwiki#3393]
The following can be found on top of the generated CSS
```
<br />
<b>Warning</b>:  Undefined array key "speech" in <b>.../lib/exe/css.php</b> on line <b>83</b><br />
```

This can be fixed in css.php, but maybe it's more appropriate to define `speech` in config_cascade.php ?

**Comment by mprins** [comment]
duplicates #3470
