### ISSUE TITLE
Section Edit sometimes duplicates the section

### ISSUE THREAD

**Issue by fwolfst** [splitbrain/dokuwiki#3401]
I am still on a hunt where and when this happens, but sometimes when using the section edit functionality, parts of the page are duplicated.

I am using the sprintdoc template but I remember that this happened before already.

From what I read, most likely this is a plugin-compatibility issue, can anybody point me into debugging directions?

Related issue might be https://github.com/splitbrain/dokuwiki/issues/3364 .

**Comment by whateverusernameisnottaken** [comment]
Well there's at least three of us now. I just posted about this here:

[](https://forum.dokuwiki.org/d/18824-whole-sections-of-text-multiplied-on-page/3)

It's driving me crazy, and causing me to do a lot of extra work. I'm more of a PC/network guy, not knowledgeable about wikis, so I have no idea how to troubleshoot it.

**Comment by splitbrain** [comment]
according to https://forum.dokuwiki.org/d/18824-whole-sections-of-text-multiplied-on-page this seems to be a problem in ckgedit. Thus I'm closing this here.
