### ISSUE TITLE
Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by slackline** [splitbrain/dokuwiki#3407]
Hi,

Trying to upgrade my install under Arch Linux where I'm on PHP-8.0.2.  I've encountered #3393 but also a number of instances in `vendor/marcusschwarz/lesserphp/lessc.inc.php` where its reported that...

    Array and string offset access syntax with curly braces is no longer supported

I've two wiki's and have corrected these under one, the `diff`of these shows the lines...

    761c761                                                                                                     
    <                                               $subProp[1][0] != $this->vPrefix)
    ---
    >                                               $subProp[1]{0} != $this->vPrefix)
    2762c2762                                                                                                   
    <                                               if (!is_string($tag) || $tag[0] != $this->lessc->mPrefix) {
    ---
    >                                               if (!is_string($tag) || $tag{0} != $this->lessc->mPrefix) {
    2816c2816
    <                       if ($tag[0] == $this->lessc->vPrefix)
    ---
    >                       if ($tag{0} == $this->lessc->vPrefix)
    

Currently one wiki works but without the selected template being displayed, the other has errors with a Class not being found, both of which are separate issues.

**Comment by phy25** [comment]
Hi, I believe this is already fixed in master branch - you can install nightly build to test.

https://github.com/splitbrain/dokuwiki/commit/6b6d27d96506910658af844fbe6b4ecd12201065

Is there anything else that we can do to help?

**Comment by slackline** [comment]
Great, thank you and my apologies for not checking the source.  I'll give the master branch a whirl and see if I've any of the other problems I mention persist or are solved already, cheers.

**Comment by phy25** [comment]
No problem! I will close this issue for now. Please create a new one if you have more.
