### ISSUE TITLE
[dokuwiki.org site] Installation docs for IIS - please explicitly mention PHP 7

### ISSUE THREAD

**Issue by jmbreuer** [splitbrain/dokuwiki#3415]
I hope this is the right place for this. If not, please point me in the appropriate direction. ;-)

A few days ago, I moved a dokuwiki installation to IIS (don't ask).

I followed the docs:

  https://www.dokuwiki.org/install:iis

and hit a snag in my first attempt.

Currently, dokuwiki only works with PHP 7. However, the download page on https://windows.php.net/download/ starts with PHP 8 and offers no obvious suggestion to _really_ check which version is required.

In its current release "Hogfather", dokuwiki will valiantly try to somewhat run on PHP 8, but the stylesheet fails to load - this breaks on some obscure syntax thing somewhere deep in vendor/.../lesserphp/... - ah that's right over in #3399 

I would suggest to clarify the installation docs to very clearly state that at this time, a version of PHP 7 must be used, to save people from wild goose chases.

Alternatively, the code could fail somewhat more gracefully, suggesting that a wrong PHP version is being used.

I'm somewhat aware of the PHP versions incompatibility issue especially between 7 and 8. Since this wasn't the first and only hurdle to get it running as part of a pre-existing typical real-life IIS instance with other stuff already on it, that still wasn't my very first idea of what might be wrong at that particular point (i.e. dokuwiki kinda works, displays pages, but looks horrible).

Thank you!

**Comment by splitbrain** [comment]
> I hope this is the right place for this. If not, please point me in the appropriate direction. ;-)

The right place is the wiki. It is a wiki. So please correct whatever
wrong or missing information you find yourself.

Andi

**Comment by jmbreuer** [comment]
Ah, thank you! I wasn't aware it was _that_ open ;-)

I added the information there.
