### ISSUE TITLE
Autogenerated Navigation Menu with Expanding option

### ISSUE THREAD

**Issue by jcbeppler** [splitbrain/dokuwiki#3420]
Hello!

One feature which would be quite handy is DW having a default plugin for autogenerating index menus, would this be possible?
Today I use _simplenavi_ plugin but it lacks a feature to expand namespaces without having to go to the next level.

I imagine something similar to this:
![image](https://user-images.githubusercontent.com/59994318/108988608-f609b200-7694-11eb-932d-1ed22a30820e.png)

**Comment by splitbrain** [comment]
Nope. There are many plugins tackling this, each having different approach. There is no one fits all solution. And it is defintely not a core feature. Also see https://www.patreon.com/posts/41964941
