### ISSUE TITLE
Although action "Old revisions" is deactivated, all old versions can be viewed.

### ISSUE THREAD

**Issue by Michaelsy** [splitbrain/dokuwiki#3421]
Although action "Old revisions" is deactivated, all old revisions can be viewed.

**Steps to reproduce:**
- Disable action "Old revisions"
- Enable action "Recent Changes"

**Unexpected behaviour:**
Via "Show differences to current revisions" in "Recent Changes" you can view all old revisions of the page.

See also [Forum](https://forum.dokuwiki.org/d/18854-disabling-restoring-old-revision/7)

\- Michael Sy.

**Comment by Klap-in** [comment]
I’m wondering what would be the expected behavior?
I guess the same question can be asked for some other actions combinations. Could you make an overview?
Is diff also such an action?

**Comment by ssahara** [comment]
@Klap-in , the revision list is generated in anonymous class defiled in Ui\Revisions.php file.  It does not take care gloval $conf, and always shows link icon for (&do=revisions) . I will fix this.  
https://github.com/splitbrain/dokuwiki/blob/b5b12e446f420be6305d55841704207096b889db/inc/Ui/Revisions.php#L120-L126

**Comment by Klap-in** [comment]
Directly another question, a bit offtopic: is it needed to have anonymous class? I see [IDEA IntelliJ](https://www.dokuwiki.org/devel:intellij_idea) is not handling it nicely everywhere... Do you mind to make it a normal class?

**Comment by ssahara** [comment]
The anonymous classes defined temporary in Ui\Recent and Ui\Revisions will soon become a normal class.

**Comment by Klap-in** [comment]
The reference to `&do=revisions` is now checked. So this issue can be closed.
(btw `do=diff` can be added manually to the disabled actions. So if someone did there are links that go nowhere, but I think it is not worth doing that now. - If you try to use it the permissions are checked and access is refused. So that works as expected.)
