### ISSUE TITLE
DokuWiki sponsoring through Liberapay

### ISSUE THREAD

**Issue by fschrempf** [splitbrain/dokuwiki#3425]
@splitbrain This is rather a question than an issue: Would you mind setting up an account on [Liberapay](https://liberapay.com) for DokuWiki and/or yourself? I'm asking because I'd like to setup a small sponsorship and I would prefer Liberapay over GitHub and others may too (apart from me there's already one other person committing to [sponsor you on Liberapay](https://liberapay.com/on/github/splitbrain/) :wink:).

**Comment by phy25** [comment]
I am not sure the benefit of this new tool, but there are already https://www.dokuwiki.org/donate (PayPal, Patreon besides GitHub that you don't want to use)  and https://www.splitbrain.org/personal/wishlist (Bitcoin)

**Comment by splitbrain** [comment]
🤷‍♂️ not sure what the advantage of liberapay over the other options are, but I created the account anyway.

**Comment by fschrempf** [comment]
@splitbrain Thanks!

For me the main advantage of Liberapay is, that there is a non-profit organization behind it, which I prefer to use/support rather than the big ones like PayPal, GitHub, Patreon, etc.

I don't know about the features of the other platforms, but Liberapay also allows you to set up a project team (e. g. for DokuWiki) and split the donations for the project between the main contributors/maintainers. This way sponsors can select to support individuals and/or teams/projects.

Also if creators/developers set up a bank account and not only PayPal, sponsors can set up recurring donations with automatic renewal (no manual action needed when the payment is due).
