### ISSUE TITLE
User self-registration is gone once plugin is installed

### ISSUE THREAD

**Issue by pczekalski** [splitbrain/dokuwiki#3427]
I'm using `authad` plugin along with `authchained` (it includes `authad` and `authplain`, to let me inject non-ad users of Dokuwiki).
`Authad` by design disables self-registration, however, in this case, it is reasonable to keep self-registration enabled.

How to re-enable it back still having `authad` running? I cannot see any option in the config files to force-enable it back.

Regards,

P

**Comment by phy25** [comment]
This is a question more suitable for the plugin authchained.

**Comment by pczekalski** [comment]
Sure about it?
Please read the `authad` documentation: "_Also self registration by users is disabled by the authAD plugin._" (source: [](https://www.dokuwiki.org/plugin:authad))

I believe `authchained` has nothing to do here. 

Please reopen...

**Comment by splitbrain** [comment]
Nope. AuthAD works as intended. When AuthChained allows for multiple auth backends it has to care about how to "merge" capabilities.

**Comment by pczekalski** [comment]
Thanks for the reply, however cannot agree.

Please consider the example:
1. `authad`, `authplain` enabled and `authchained` enabled = no local registration possible (wrong):
![Screenshot from 2021-03-03 16-55-41](https://user-images.githubusercontent.com/23726790/109834165-3394af00-7c42-11eb-8ac5-dca63e1b1150.png)

2. `authad` disabled, `authplain` enabled and `authchained` enabled = local registration possible (right):
![Screenshot from 2021-03-03 16-59-16](https://user-images.githubusercontent.com/23726790/109834400-6b035b80-7c42-11eb-85a3-db19dbcb8c59.png)

Please reopen...

**Comment by Klap-in** [comment]
The `authad` and the `authplain` give both a signal yes/no whether it supports local registration. If you use them separately I understand that you see that these signals are recognized by the `authchained` plugin as well.

However, it appears that the `authchained` does not see (yet/anymore) that in this case one plugin says 'yes' and the other say 'no'. So in my opinion the first logic step is that the mechanism in `authchained`  that checks these yes/no's have to be verified. Probably there something is not handled as expected.

**Comment by phy25** [comment]
And please create a new issue in authchained. I would say I don't see any reason to reopen this if you can point out which code in DokuWiki is causing the issue.

**Comment by pczekalski** [comment]
> And please create a new issue in authchained. I would say I don't see any reason to reopen this unless you can point out which code in DokuWiki core is causing the issue.

Submitted in `authchained`. Thank you for your support.
