### ISSUE TITLE
Help Wanted -> Utf8 (utf8.php and Utf8 folder)

### ISSUE THREAD

**Issue by ClaudiuHKS** [splitbrain/dokuwiki#3429]
Hi, I am using **XenForo 1.5** (contains **Zend Framework**).
I don't know, if you guys know, but **XenForo 1.5**, uses Lgpl\ **Utf8**, made by **splitbrain**, to romanize URLs, for example.
ميا خليفة -> **mia xlif** (Mia Khalifa).
Anyways, I can use, a lot of symbols (entities), like, ✨, ☝, ⚓, & others.
Though, I can't use, 📁, or 💣.
In **phpMyAdmin** (**PMA**), yes, I can set text fields, to contain, 📁, or 💣, it works like a charm, but, afterwards, the **XenForo 1.5** pages, will display these symbols (entities), as **?**. **PMA**, like I just said, displays them correctly, into the **/phpMyAdmin/index.php** page.
How can I edit, myself, **utf8.php** file, or files, within the **Utf8** folder, manually adding, symbols (entities), like, 📁, or 💣, to properly work?
Note, ✨, ☝, ⚓, & other symbols (entities), do already work, in both **XenForo 1.5**, & **PMA**!
Thanks!

All my **MariaDB** / **MySQL** connections, databases, & tables, are **utf8mb4** @ **utf8mb4_unicode_520_ci**.

**Comment by phy25** [comment]
Sorry, but how is this related to DokuWiki? Do they just take the Utf8.php file from DokuWiki source?

**Comment by ClaudiuHKS** [comment]
Yes!

**Comment by splitbrain** [comment]
Sorry we can't help you. I'm not sure I fully understand what you're asking for, but I'm a) pretty sure it has nothing to do with the utf-8 library and b) we cannot support other software than Dokuwiki.
