### ISSUE TITLE
Linking the mailing list archive in the black top navigation bar

### ISSUE THREAD

**Issue by Michaelsy** [splitbrain/dokuwiki#3435]
I think it would be useful to link the mailing list archive in the black top navigation bar of the wiki. (Also according to the systematics of the bar this link should be entered there.)

\- Michael Sy.

**Comment by Klap-in** [comment]
Via ‘Get support’ in the sidebar, you could find a overview of all these communication channels.

There is also an instruction that the purpose of the mailing list is to have development related discussion. I’m wondering if that is clear enough of added there.

a bit off-topic, jacking the topic..
I would vote for another update. The codesearch.dokuwiki.org is worth some extra attention. And, btw, xref might be better replaced by a pointer to https://codesearch.dokuwiki.org/xref/

Source of the top bar, https://www.dokuwiki.org/teams:top_nav_toolbar

**Comment by Michaelsy** [comment]
> The codesearch.dokuwiki.org is worth some extra attention. 

+1 (meanwhile established)

\- Michael Sy.

**Comment by splitbrain** [comment]
There's not enough happening on the mailing list anymore to warrant that link.
