### ISSUE TITLE
risk of invalid xhmlt because of double sectionID

### ISSUE THREAD

**Issue by gturri** [splitbrain/dokuwiki#3436]
The method [sectionID](https://github.com/splitbrain/dokuwiki/blob/master/inc/pageutils.php#L234) tries to ensure that it returns unique id, however there is a case not correctly handled: consider this page:

    ======A======
    section 1

    ======A======
    section 2

    ======A1======
    section 3

This would lead to a page with three `<h1>` titles which would look like

    <h1 id="A" ...../>
    <h1 id="A1" .../>
    <h1 id="A1" .../>

ie: when generating the 3rd title we fail to notice that we already have a `A1` one.

(Note that we would also have a similar an issue with this page:

    ======A======
    section 1

    ======A1======
    section 2

    ======A======
    section 3

both cases may look pretty similar, however we could easily end up with a patch that could fix the issue in the 1st case but fail to fix the 2nd one)

**Comment by splitbrain** [comment]
Can you provide a PR with a failing test and maybe a fix?

**Comment by gturri** [comment]
From a technical point of view I think I can do that.
From a "when will I have the time to work on that" point of view it's a bit
harder... but I guess all open source maintainers have the same concerns.
So, sure, I'll try to work on a PR. (I just don't know when)

Le mar. 16 mars 2021 à 09:14, Andreas Gohr ***@***.***> a
écrit :

**Comment by gturri** [comment]
Don't hesitate to let me know if the pull request https://github.com/splitbrain/dokuwiki/pull/3442 (which fixes this bug) looks good to you or if you'd rather I change it
