### ISSUE TITLE
Notice with outside authentication and PHP8

### ISSUE THREAD

**Issue by perrick** [splitbrain/dokuwiki#3455]
We get a notice with our Dokuwiki install with PHP8 :

`Warning: Trying to access array offset on value of type null in /dokuwiki/inc/common.php on line 169`

Adding a verification with an "isset" shoud do the trick, i.e on line 169 :

`if(!isset($info['userinfo']['name']) or !$info['userinfo']['name']) {`

**Comment by Ammarpad** [comment]
This is not a PHP 8 issue. If $info['userinfo'] is null, array offset warning will be raised as far back as PHP 7.4. Guarding it with isset() seems prudent here.
