### ISSUE TITLE
PHP Warning:  Undefined array key "fperm" in inc/io.php line 255

### ISSUE THREAD

**Issue by jeffnoparking** [splitbrain/dokuwiki#3468]
When editing an item on a clean PHP8 installation, we get a warning:
`PHP Warning:  Undefined array key "fperm" in inc/io.php line 255`

See pull request #3469

**Comment by splitbrain** [comment]
This looks like a duplicate of #3382 which should be fixed with 23420346128e0894d85f8475f8e0488fb80cdb24

Have you verified this issue exists with a current master checkout?
