### ISSUE TITLE
AUTH_ACL_CHECK checks also media and not only page

### ISSUE THREAD

**Issue by gerardnico** [splitbrain/dokuwiki#3476]
Hallo,

The documentation on [AUTH_ACL_CHECK](https://www.dokuwiki.org/devel:event:auth_acl_check) says that this event is for a page or namespace but I can see that this also used for media via the `mediamanager` for instance.

Is this the correct behavior ?
If yes, how do we know if this is a media or a page ? There is only the id available in the data array.
For now, I extract the extension but this is just a hack.

Thanks
Nico

**Comment by splitbrain** [comment]
The behaviour is correct (feel free to adjust the docs). There is no way to know what is checked (in this event) because the ACL system doesn't care. ACLs apply to media and pages.

**Comment by gerardnico** [comment]
Thanks. Done. I have adjusted the doc.
