### ISSUE TITLE
Dokuwiki editor should create image tags automatically when pasting/d&d an image

### ISSUE THREAD

**Issue by nerdoc** [splitbrain/dokuwiki#3479]
One of the features that Atom (Github etc) has and I terribly miss in DokuWiki, is the possibility to paste images into the Editor, and let it generate a link automatically.

Github creates an automatic filename, which Dokuwiki does/should not, so it could be done in 2 steps:

* Paste an image with [Ctrl]+[V] or drag&drop it into the editor space
* Dokuwiki opens a modal form which asks for the file name and the location
* Ok/Enter saves the image and creates the corresponding link.

This would be a very good feature IMHO, and move DokuWiki a bit further.

**Comment by Klap-in** [comment]
You could try the imgpaste plugin: https://www.dokuwiki.org/plugin:imgpaste

**Comment by nerdoc** [comment]
This definitely is a good solution. Moving that into core would be a great addition to DokuWiki IMHO. But this fixes my issue, thanks.
