### ISSUE TITLE
How to configure DokuWiki Farm on Nginx?

### ISSUE THREAD

**Issue by FelipoAntonoff** [splitbrain/dokuwiki#3481]
I would like to know if there is any example of how to configure DokuWiki Farm with Nginx using the preferred subdomain mode.

I tried the article: https://www.dokuwiki.org/farms

And Plugin https://www.dokuwiki.org/plugin:farmer, but both are focused on Apache, I looked for some examples on the Internet, but it still didn't work.

I managed to make the new Wiki appear, but do not take the links from the Administrator or to create a page, I believe it is some detail of the redirection.

In the open Dokuwiki mode I was able to create the Wiki page, but in the other modes if I join my user, nothing appears to create the page.

**Comment by splitbrain** [comment]
Sorry, usage questions are better suited for the [forum](https://forum.dokuwiki.org). The issue tracker is reserved for bugs and feature requests.

**Comment by FelipoAntonoff** [comment]
Hello, thanks for the feedback, I asked a question on the forum.
