### ISSUE TITLE
Breadcrumbs aren't generated

### ISSUE THREAD

**Issue by Poorchop** [splitbrain/dokuwiki#3482]
I'm using the latest development snapshot, 51.3, with PHP version 8.0.3, nginx 1.16.1 and breadcrumbs are only generated for the current page. No error logs have been generated and I don't see any errors when checking the version information. I'm not able to check against PHP7 at the moment but I'm guessing that this is a PHP8 bug since breadcrumbs work fine on the main DokuWiki website.

I have not changed the default breadcrumb settings. This is a mostly stock install with the exception of the backlinks and color text plugins, but this issue was present on a fresh install and before installing any plugins.

**Comment by splitbrain** [comment]
Your PHP session isn't working correctly. Check your settings and ensure the php process may write to the session dir.

**Comment by Poorchop** [comment]
Thanks. I checked my nginx error log and saw that the process didn't have write access to /var/lib/php/session, which was owned by the group apache instead of nginx for some reason. `chgrp nginx /var/lib/php/*` fixed it.
