### ISSUE TITLE
New DokuWiki Logo Contest? 😳

### ISSUE THREAD

**Issue by cgalo5758** [splitbrain/dokuwiki#3488]
The logo has been around for 16 years now. While it is a pretty neat logo, design trends have changed plenty, I was thinking maybe we ought to have a new logo contest to make DokuWiki look more modern and less 2005.

Requirements: (? updating this as comments come in)
- Must be SVG
- Scalable (it looks okay both really big and really small, like in a favicon)
- Be creative?

**Comment by cgalo5758** [comment]
I just felt very very inspired, so I wanted to drop in an entry. Am also not sure what the right avenue would be for coordinating and announcing a contest 🤷🏽‍♂️

![DokuWiki Logo Entry](https://user-images.githubusercontent.com/36752715/117600021-1b954c00-b119-11eb-829c-a4477acd4211.png)

**Comment by splitbrain** [comment]
duplicate of #1623
