### ISSUE TITLE
&do=export_xhtml

### ISSUE THREAD

**Issue by Quentin-ctrL** [splitbrain/dokuwiki#3490]
Hi,

I tried to export a page using `&do=export_xhtml` and I got "this page doesn't exist"
I can create a new page named "wiki:script:mcsa_do_export_xhtml"

According to the docs, I also tried :
`wget -E -r https://wiki.xyz/doku.php/script/mcsa  -l 0 --header="X-DokuWiki-Do: export_xhtml"`
it works this way.

Last time I used export it worked but it was months ago.
With a fresh install, it works. I suppose some settings broke the functionnality
I really dont know what can cause this :/

**Comment by michitux** [comment]
Did you try `https://wiki.xyz/doku.php/script/mcsa?do=export_xhtml`? If there is no `?` in your path, you need `?` instead of `&` before the first parameter. Apart from that, such issues with the setup might be better suited for the [forum](https://forum.dokuwiki.org/).

**Comment by Quentin-ctrL** [comment]
Yes, it works adding `?` . 
I never had to use `?` before and it worked. I assume some changes in the last version of dokuwiki

I followed the french version of the wiki :
https://www.dokuwiki.org/fr:export
Following this link, the syntax is more obvious : 
https://www.dokuwiki.org/start?id=export

If someone can update this page : https://www.dokuwiki.org/fr:export ;)

Thanks for help

This issue can be closed.

**Comment by michitux** [comment]
I have changed the URLs to be similar to the English version. Note that you can log in on dokuwiki.org with an account from the DokuWiki forum and change the content yourself - it is a wiki after all.

**Comment by Quentin-ctrL** [comment]
I'll edit myself next time
:) thanks
