### ISSUE TITLE
Adjacent sibling combinator stripped from CSS in conf/userstyle.css

### ISSUE THREAD

**Issue by mcorrin** [splitbrain/dokuwiki#3494]
When custom styles are written that employ the adjacent sibling combinator (+) in the userstyle.css file in (conf/userstyle.css), the rules appear to be stripped on final rendered page. 
For example, if I write:
h2 + h3:first-of-type { /* rules */}
This rule does not appear in the development tools in Chrome or Safari (14.1, MacOS 10.14.6)
Issue appears in Release 2020-07-29 "Hogfather" running in Linux/Apache/PHP 7.2 environment

**Comment by Klap-in** [comment]
If I try https://leafo.net/lessphp/ the current example`h2 + h3:first-of-type { /* rules */}` is deleted from the compiled output, but if I add something within the brackets, it is passed to the output.

This compiles:
```
h2 + h3:first-of-type { color:black; /* rules */}
```

So are you sure there are statements in this section?
I have not tested in DokuWiki.

**Comment by mcorrin** [comment]
Thank you for looking into this. Spent more time with it tonight and could not reproduce my issue again. I think that the empty statements may have been my issue. Thank you.
