### ISSUE TITLE
Admin menu sort order

### ISSUE THREAD

**Issue by lazyzero** [splitbrain/dokuwiki#3495]
Hi, 

I encounter a strange problem. the getMenuSort() of admin plugins seams not to be used at all. I double checked in the sources of inc/Ui/Admin.php there are the sort functions for the three menu categories. I added in the function generating the menu the weight of the plugins and it is not respected at all. I checked with other dokuwiki instances and the order is every time different. 

Dokuwiki version: Hogfather
PHP version: PHP 7.3.27 (cli) (built: Feb  4 2021 21:04:33) ( NTS )

Best Christian

![screenshot of problem](https://cloud.m2ct.de/s/sf8dyDyjo9iKPLk/preview)

**Comment by splitbrain** [comment]
The order is no longer used. Plugins are ordered alphabetically.

**Comment by lazyzero** [comment]
Okay, I see. 

But it was handy that the order of the menu was always the same independent from the language used. May I propose a patch to make the sort order configurable? Default current behaviour, and if enabled the order by weight?

Otherwise the https://www.dokuwiki.org/devel:admin_plugins should be changed and the inc/Ui/admin.php is calling the getMenuSort() as well. Could be removed if it is not used any more.

**Comment by splitbrain** [comment]
> May I propose a patch to make the sort order configurable? Default current behaviour, and if enabled the order by weight?

No. This is a config option 99.9999% of the users would never use.

> https://www.dokuwiki.org/devel:admin_plugins should be changed

Yes. Please do so. Pull requests to improve the code are also welcome.
