### ISSUE TITLE
CLS caused by mobile menu (div.menu-toggle, .sub-menu-toggle)

### ISSUE THREAD

**Issue by maartjehensen** [splitbrain/dokuwiki#3497]
My mobile menu toggle (min-height: 52px) causes CLS. The menu appears later (it's only a split second). I have tried everything I thought of (critical CSS in WP rocket, and custom CSS) but it doesn't work. I suspect it's the .sub-menu-toggle item that is 'lazy loading' or something. I have two screenshots of the .sub-menu-toggle display [disabled](https://i.stack.imgur.com/RkHF2.jpg) and [enabled](https://i.stack.imgur.com/Csmel.jpg) and that looks like what's happening on mobile. I'd love to hear if someone has a solution for this!

Website: vegarecepten.com

**Comment by selfthinker** [comment]
vegarecepten.com uses WordPress, but this is the bug tracker for DokuWiki.

**Comment by phy25** [comment]
> critical CSS in WP rocket

and also I don't think DokuWiki default template includes `sub-menu-toggle`.

Closing, but please reopen if you tell us how this is related to DokuWiki.
