### ISSUE TITLE
Make link wizard to search page titles as well.

### ISSUE THREAD

**Issue by alexdraconian** [splitbrain/dokuwiki#3498]
I use alphanumeric pagenames, and non-latin page titles(first heading). So when I need to insert links, it's confusing to find page's 'true' name instead of their titles.

So I suggest when 'useheading' option is 1(always) or content, link wizard searches through page titles as well as pagenames.

I'll open pull request about this suggestion right away.

**Comment by sokolgeo** [comment]
I strongly support this request.
It defeats the purpose of having 'useheading'=1, if link wizard only searches in pagenames!
