### ISSUE TITLE
Change identical footnotes to use the same number

### ISSUE THREAD

**Issue by racquetmaster** [splitbrain/dokuwiki#3504]
If footnotes have identical content, it is easier to read if they both use the same number. It is nice that we group them together but it makes it harder to read the content if you already know the references. You still have to manually look them up or hover over each of them.

#### Markup ####
```
I'm explaining about something ((Website A)).

Later I refer to the same source ((Website A)).
```
#### Render ####
```
I'm explaining about something 1)
Later I refer to the same source 1)

------------------------
1) Website A
```

**Comment by molefunk** [comment]
From https://www.dokuwiki.org/plugin:footnotestyle:

**Style – How the footnote references appear in the text**
* Superscript
* Square brackets
* Superscript and square brackets
* Superscript and right parenthesis (Original DokuWiki)

**Stylebottom – How the footnote numbers appear at the bottom of the page**
* Followed by a dot
* In square brackets
* In superscript
* In square brackets and superscript
* With right parenthesis and superscript (Original DokuWiki)

**Join identical footnotes** <-- LOOK HERE!
* Separated by a comma
* Separated by a space
* Separated by a space-comma-space (Original DokuWiki)
* Don't join identical footnotes

Here is an example image from the plugin page, showing joint footnotes:
![An example of joint footnotes](https://www.dokuwiki.org/lib/exe/fetch.php?tok=6c4920&media=http%3A%2F%2Fwww.zuiderkwast.se%2F_media%2Fdokuwiki%2Ffootnotestyle-2.png)

**Comment by splitbrain** [comment]
Footnotes use multiple numbers so that you can jump back to the correct place in the text.
