### ISSUE TITLE
LogOut not working (cookie get's deleted, but re-added immediately?)

### ISSUE THREAD

**Issue by Edgepath** [splitbrain/dokuwiki#3505]
Hello,

Dokuwiki is part of my daily life and absolutely love it :)

a strange happened: logout ain't workin no more?

https://user-images.githubusercontent.com/86378999/123156471-9e742b00-d469-11eb-87dd-b0fdf21fde2d.mp4

![hpenekehnlodbdem](https://user-images.githubusercontent.com/86378999/123156580-c06dad80-d469-11eb-867b-08dcac28a4ac.png)

means: can login

but can't logout X-D (cookie get's deleted, but re-added immediately?)

thanks & have a good time

**Comment by phy25** [comment]
Could you provide the request logs in the network tab, specifically HTTP header of the logout request/response and subsequent requests? What server are you using (Apache/nginx)?

**Comment by Edgepath** [comment]
Hello,

imho it is a ngingx behind a apache2 reverse proxy

here it is:

```
GET /projects/doku.php?id=start&do=logout&sectok=fc3b5c904be1ce9131e86c05xxxxxxxx HTTP/1.1
Host: domain.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Basic YWRtaW46bXc4RlZTRnFrxxxxxxxx
Connection: keep-alive
Referer: https://domain.com/projects/doku.php
Cookie: DokuWiki=46df9ba19a84f65e0d408405xxxxxxxx; DW0dd5613b3c7d66d8e81280b395da470b=YWRtaW4%3D%7C0%7C2cTD9gIcKTPFU6n%2F84ctECtuArt%2BsfxnGixWu7xxxxxxxx
Upgrade-Insecure-Requests: 1
```

**Comment by michitux** [comment]
The headers indicate that you are sending user and password via HTTP basic authentication. DokuWiki uses these credentials to log you in automatically. Unfortunately, there is no (easy) way to clear these credentials when you press the logout button. Browsers only clear them when you close the browser.

**Comment by phy25** [comment]
Yes, if `Authorization` contains your actual DokuWiki credential there's nothing we can do about it. If it's not the case please add more information and reopen the issue.
