### ISSUE TITLE
In some situations, formating breaks or does not work at all

### ISSUE THREAD

**Issue by rstemmer** [splitbrain/dokuwiki#3507]
Hello,

I've some Issues with the formatting for a while.
Most time everything works as expected, but in some situations, pages break partially or even complete.
"Breaking" means, that the DokuWiki syntax gets not processes and is shown as written.

Simple example: `Link: [[https://www.google.de|Google]] ` breaks, while `[[https://www.google.de|Google]] ` works.
So it seems that here the `Link: ` breaks the parsing process.
This issue occurs in lots of situations quiet often. Sometimes only edited parts are affected, sometimes the begin of a page is correct until a certain point, then successive parts break until at the end of a page not even headlines are shown correct.

Reproduce:

 - Create an empty page.
 - Add `Link: [[https://www.google.de|Google]]`
 - Save Page
 - Output: `Link: [[https://www.google.de|Google]] `
 - Expected: `Link: Google`

Log when clicking on Save:
```
05:30:30 192.168.1.214: INFO_DEPRECATION_LOG:BEFORE event triggered before event system was initialized
05:30:30 192.168.1.214: require_once() is deprecated. It was called from require() in /srv/dokuwiki/inc/load.php:147 Autoloading. Do not require() files yourself. should be used instead!
05:30:30 192.168.1.214: INFO_DEPRECATION_LOG:AFTER event triggered before event system was initialized
05:30:30 192.168.1.214: checkUpdateMessages(): messages up to date
05:30:30 192.168.1.214: INFO_DEPRECATION_LOG:BEFORE event triggered before event system was initialized
05:30:30 192.168.1.214: require_once() is deprecated. It was called from require() in /srv/dokuwiki/inc/load.php:147 Autoloading. Do not require() files yourself. should be used instead!
05:30:30 192.168.1.214: INFO_DEPRECATION_LOG:AFTER event triggered before event system was initialized
05:30:30 192.168.1.214: checkUpdateMessages(): messages up to date
05:30:30 192.168.1.214: INFO_DEPRECATION_LOG:BEFORE event triggered before event system was initialized
05:30:30 192.168.1.214: require_once() is deprecated. It was called from require() in /srv/dokuwiki/inc/load.php:147 Autoloading. Do not require() files yourself. should be used instead!
05:30:30 192.168.1.214: INFO_DEPRECATION_LOG:AFTER event triggered before event system was initialized
```

Latest version of DokuWiki via Update Manager.
I have to use `PHP 7.4.20 (cli) (built: Jun  2 2021 04:08:27) ( NTS )` because I run some web apps that are not as advances as DokuWiki and still do not work with PHP 8 :roll_eyes:

**Comment by splitbrain** [comment]
This is a known bug in the PCRE library used by PHP.

See https://forum.dokuwiki.org/d/19270-dokuwiki-instance-no-longer-rendering-some-syntax-correctly for more background info and how different people solved it by reverting to older libraries or updating PHP.

Bug report at the PHP project: https://bugs.php.net/bug.php?id=81101

PCRE upstream bug report: https://bugs.exim.org/show_bug.cgi?id=2763

**Comment by rstemmer** [comment]
Thank you.
I'll keep an eye on updates of PHP and PCRE2.
