### ISSUE TITLE
QCadCam Pro fails to export .nc file in this version of Windows-11 while it worked fine in Windows-10.

### ISSUE THREAD

**Issue by Danny-40** [splitbrain/dokuwiki#3522]
QCadCam Pro fails to export .nc file in this version of Windows-11 while it worked fine in Windows-10. Saving the .dxf file also fails in the same way as the "save file" dialog behaves like the "open file" dialog. I also interested Microsoft about this problem through feedback in the Insider channel. The problem is really serious because failing to export both the Q-Code (.nc) and the drawing (.dxf) the program becomes unusable. 
![Screenshot (1398)](https://user-images.githubusercontent.com/29312489/129534330-7de0a955-9553-48c8-8000-5cb7e4197b24.png)
![Screenshot (1400)](https://user-images.githubusercontent.com/29312489/129534582-f20c71f8-377f-4492-bc10-0a4d0aae71d2.png)
![Screenshot (1398)](https://user-images.githubusercontent.com/29312489/129534614-2c8268e4-7073-40d7-a0d4-678f0e6e0b31.png)
![Screenshot (1399)](https://user-images.githubusercontent.com/29312489/129534647-10786e61-448d-4cbd-b695-6dfb593f0ce6.png)

**Comment by splitbrain** [comment]
wrong bug tracker
