### ISSUE TITLE
How to setup authentication and/or authorization with customized SSO.

### ISSUE THREAD

**Issue by biganan2012** [splitbrain/dokuwiki#3523]
BackGround:
I am looking for a wiki tool for my company and after some investigation, i think dokuwiki is the best compared with wiki.js/mediawiki. I agree confluence is good but it is not free here, so it is not an option.

We also have 2 other systems. Let's say A and B here.
A: A system which can do SSO to other apps. Here SSO only stand for authentication. 
A add a link for dokuwiki. When user login to A, user gets a token and userId. A request like http://<ip>/access_token=xxxx&userId=yyyy generated to App.
App should callback with url like http://<A_IP>/
zuul/data-auth-provider/open_api/user/get_user_by_id?accesstoken=xxxx&userId=yyyy. When authenticated success, A system will return confirmation code and user information to App.
Here system A has no aothorization.

B: B system which can do SSO and called with SSO center. SSO here means authentication and authorization.
B add a link for dokuwiki. When user login to B, user gets a token. Then app generate request like http://<ip>/access_token=xxxx&appId=yyyy to B. Here appId used for authorization. A user might be administrator in app X but normal user in app Y, so need different appId to distinguish accordingly.

You may say SSO means we can login through any app to SSO center. But now we just talk about this scenario, to redirect to dokuwiki from SSO center after login.

Need Help:
Does dokuwiki support with such integration with system A or B please? I have tried many plugins but haven't found a way for this. 
From open issue [2431](https://github.com/splitbrain/dokuwiki/issues/2431), it seems authorization has been implemented. But it is not for authentication. I really hope i am wrong here. Could some one figure it out please? Thank you very much!

**Comment by Klap-in** [comment]
DokuWiki has plugins that provide a lot of specific functions. There is a specific group of plugins: the 'Auth Plugins' that provides a lot of variants for different authentication methods. You can find them in the plugin repository. You can install them from the Extension Manager in your wiki and often configure them from the Configuration Manager (see the wiki page of an auth plugin for details). No idea which kind of existing apps you have already, but I expect a search in the Auth Plugins is worth the effort.

Please see the wiki, https://www.dokuwiki.org/auth

**Comment by biganan2012** [comment]
@Klap-in ， thank you for your reply. I know that we have many plugins. But to be honest, i am not a PHP developer, i am just looking for an integration with dokuwiki and existing system in authentication perspective.

As i mentioned in the issue, we have existing system (call it app A) which was developed in Java. we have added UI in A, when user login to A, and click the UI of dokuwiki, there will be link in browser generated (http://dokuwiki_ip/access_token=xxxx&userId=yyyy ).
We expect that dokuwiki can call back A with url(http://<A_IP>/
zuul/data-auth-provider/open_api/user/get_user_by_id?accesstoken=xxxx&userId=yyyy).

I know that there might be no existing plugins which can meet this requirement. But i am still asking here, just want to be lucky, may be someone is developing this kind of plugins.

**Comment by splitbrain** [comment]
Since this is a business context, I would recommend a consultant https://www.wikimatrix.org/consultants/dokuwiki/-/-
