### ISSUE TITLE
Generated Section Id does not follow the HTML specification

### ISSUE THREAD

**Issue by gerardnico** [splitbrain/dokuwiki#3528]
**Issue**
A heading with the value 
```
YYYY-MM-DD
20210913
```
will result in the following id in the html heading
```html 
<h1 id="section20210913">2021-09-13</h1>
```
but according to the [HTML specification](https://www.w3.org/TR/html401/types.html#type-name), the value entered is valid:
```
ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".")
```
the id therefore should be equal to the content:
```
2021-09-13
```

**Code**
The code generating the id can found [here](https://codesearch.dokuwiki.org/xref/dokuwiki/inc/pageutils.php#225-254)

**History and CSS**
Historically, this change was made because [CSS identifier does not authorize number at the begining](https://bugs.dokuwiki.org/1627.html)
but in this case, a fully qualified selector should be used.

For instance:
```css
h1[id="2019-10-01"] {
    color:blue;
}
```

**Forum**
The original discussion can be found in the [forum](https://forum.dokuwiki.org/d/19523-dw-creates-broken-links-when-using-date-yyyy-mm-dd-as-section/16)

**Comment by selfthinker** [comment]
Historically, this change was made because an ID starting with a number used to not be valid. It is still invalid in HTML4 but became valid in HTML5.

**Comment by gerardnico** [comment]
@selfthinker missed that point. Thanks for clarifying.

**Comment by gerardnico** [comment]
It seems that this is not seen as an issue. I close it.
