### ISSUE TITLE
Warning for incompatible plugins/Friendlier failure mode

### ISSUE THREAD

**Issue by solarkraft** [splitbrain/dokuwiki#3535]
Hey! I love Dokuwiki, but here's a rough edge I've stumbled upon. 

I've had it happen multiple times that a plugin I installed completely wrecked my DokuWiki installation, requiring manual deletion of the folder. Luckily this is relatively easy if you know how it's done, but it should probably not be required as I could imagine it leading a less advanced user into despair. 

The extension manager should maybe show a strong warning if a plugin isn't marked compatible and maybe there should be some way to automatically revert the installation if it results in an error. Or, at least, perhaps there should be an error message instead of just a blank screen.

**Comment by Klap-in** [comment]
The development version has a nicer fall back mechanism included for big errors. So on that side there should be progress with the next release.

**Comment by phy25** [comment]
I don't think incompatible plugins break things that much (even though to be honest I haven't run a DokuWiki instance for years). As for error handling see #3203.

Is it ok if we close this issue?

**Comment by TheNomad11** [comment]
With last years update lots of instances broke due to incompatible plugins, there were lots of forum posts about blank pages
