### ISSUE TITLE
hidepages setting does not accept "?" in regexp

### ISSUE THREAD

**Issue by fthommen** [splitbrain/dokuwiki#3538]
Using "?" for single characters in the [`hidepages`](https://www.dokuwiki.org/config:hidepages) setting doesn't seem to work.  E.g. `^:providers:my?emplate3` does not filter out `^:providers:mytemplate3` and `?_template` is not accepted at all (settings cannot be saved, field gets a red warning background in the configuration manager).

DW release is 2020-07-29 "Hogfather"

**Comment by splitbrain** [comment]
You are aware that a `?` in regular expressions make the previous character optional, right? `my?` will match `mytemplate` and `mtemplate` but not `myxtemplate`.

**Comment by fthommen** [comment]
Ouch.  Silly me.  Too many shell globs and too little "real" regexes lately.  Sorry for the noise
