### ISSUE TITLE
<html> does not work in list

### ISSUE THREAD

**Issue by ppasedach** [splitbrain/dokuwiki#3539]
[Here](https://muk.li/upama/haravijaya), in the introductory paragraph, `Ś<html><sub>c</sub></html>` produces the expected result, but in the following list

`  - [[haravijaya:01:hv-01-k|Purāripurīvarṇanam]] [[haravijaya:01:hv-01-j|(J)]] [[haravijaya:01:hv-01-s-c|(Ś<html><sub>c</sub></html>)]]`

`<html><sub>c</sub></html>` is displayed in the output. I assume this is because of the list?

**Comment by phy25** [comment]
I don't think html block is supported inside the paragraph:

https://github.com/splitbrain/dokuwiki/blob/0b63e09a6f6e45247d064792d2ff494cbec46979/inc/Parsing/Handler/Block.php#L16-L35

**Comment by splitbrain** [comment]
I'm not sure I understand the problem. HTML is accepted in lists. Assuming that htmlok is set, the following works fine:

```
  * html: <html>is <b>html</b><sub>subtext</sub></html>
  * HTML: <HTML>is <b>HTML</b><sub>subtext</sub></HTML>
```
However, no HTML is need for `<sub>` and `<sup>` as they are supported by DokuWiki's syntax.
