### ISSUE TITLE
Old version of page gets restored automatically

### ISSUE THREAD

**Issue by zoof** [splitbrain/dokuwiki#3543]
I've recently experienced an issue where an old version of a page gets repeatedly restored, through no action on my part.  For example, looking in the attic, there are four identical gzipped versions of the same file.  (This is a family grocery list so it is highly unlikely that the same items in the same order come up over and over again.

Initially, I thought it might be a malfunctioning plugin -- cleanup or revert manager -- but I have since disabled both and the issue persists.

I have been using dokuwiki in this capacity for many years now but it is relatively recently that this has begun to happen.  And I have not noticed it happening with other pages within the same installation, although none of them are revised with the same frequency as this one.

My installation is fully up-to-date with "Hogfather" on a Centos 7 box using Apache and php 7.3 from the sclo repository.

**Comment by Klap-in** [comment]
I haven’t idea of how the wiki is used. Are there more users? Is it happening by the same user? There is also an built-in revert button for admins, ( recently updated so normal users can also use this button, not sure if that button could be used?)

Is there a description given in the list with revisions?

**Comment by zoof** [comment]
Ah, this page is wide open and looking at the revision history, someone has a bot restoring an old version.  Why though?  So weird.

**Comment by splitbrain** [comment]
See #3346
