### ISSUE TITLE
dokuwiki support for PHP8

### ISSUE THREAD

**Issue by michaelkeusch** [splitbrain/dokuwiki#3545]
Hello, 
when can we expect a stable release which supports PHP 8.
Thank you very much for your efforts.
Greetings Michael

**Comment by rotdrop** [comment]
Just to note it down here, there are some related forum posts:

https://forum.dokuwiki.org/d/19733-please-check-if-your-plugin-uses-obsolete-form-events

https://forum.dokuwiki.org/d/19700-php-8-support

I would also like to see php 8 support ... one problem seems to be that Hogfather is not in a PHP-8 capable state, while the master branch is not yet ready to be release as it contains a bunch of changes apart from supporting PHP-8.

**Comment by omerida** [comment]
I'm running a personal wiki on PHP 8 with no obvious issues at the moment. I've run PHP_CodeSniffer's compatibility checks and the main thing it highlighted was the use of create_function() in unit tests. I also ran phpstan with its version set to 8.0.0 and it didn't highlight anything specific to the versions.

**Comment by splitbrain** [comment]
https://www.dokuwiki.org/faq:nextrelease
