### ISSUE TITLE
Undefined array key warnings from inc/StyleUtils.php

### ISSUE THREAD

**Issue by chrisisbd** [splitbrain/dokuwiki#3546]
This is a minor issue but produces lots of warning messages in the apache error log, e,g,:-

```
[Tue Nov 09 21:39:03.422955 2021] [php:warn] [pid 974] [client 127.0.0.1:49454] PHP Warning:  Un
defined array key "stylesheets" in /home/chris/wiki/inc/StyleUtils.php on line 102, referer: htt
p://t470.zbmc.eu/wiki/start
[Tue Nov 09 21:39:03.423034 2021] [php:warn] [pid 974] [client 127.0.0.1:49454] PHP Warning:  Un
defined array key "replacements" in /home/chris/wiki/inc/StyleUtils.php on line 113, referer: ht
tp://t470.zbmc.eu/wiki/start
```

It's simply a result of the default empty style.ini files in the conf/tpl/<name of template> directory, which mean that though the file exists no stylesheets or replacements arrays are returned.  It's probably easy enough to fix by checking if the $config array has the key in question before checking if the element is an array.

I'm happy to submit a fix if someone can give me some simple guidance on how to do this.  I need help with the Github side of things rather than with the programming.
`

**Comment by splitbrain** [comment]
this is already fixed in master

**Comment by chrisisbd** [comment]
Ah, OK, sorry.  I did search for it here before adding the issue.
