### ISSUE TITLE
old syntax different from new syntax about whitespace

### ISSUE THREAD

**Issue by grtfou** [splitbrain/dokuwiki#3548]
Please see attached pictures.
↓↓↓↓↓

![preview](https://user-images.githubusercontent.com/1241272/141714377-00f57bd2-c5c0-4649-9411-45240a33f436.png)

---- 
Have any behavior changes in dokuwiki new version?
Thanks 🙂

* **Version**: 2020-07-29 “Hogfather”
* **OS**: Ubuntu 20.04
* **plug-in**:
  * Wrap Plugin
  *  color syntax plugin

**Comment by splitbrain** [comment]
see #3507
