### ISSUE TITLE
cannot upload files bigger than 16KB despite the php.ini setting

### ISSUE THREAD

**Issue by crixthegreat** [splitbrain/dokuwiki#3550]
when I upload a file bigger than about 15kb,  it says Failed in red. 
But SMALL FILES of size less than 15kb work well.

Why?

-------------------------------------------------------
I use dokuwiki with Chrome 94.0.4606.81(64 bit). 
The server is running PHP with fastcgi in windows server 2019 standard.

Everything goes well, only the file-uploading bothers me.

I followed the instructions and changed the php.ini setting, which now is:
file_uploads = On
#upload_tmp_dir =
upload_max_filesize = 10M
max_file_uploads = 5

The media-manager shows the 10M restrictions correctly.  

Could someone give me some help? Thanks.

**Comment by voegelas** [comment]
The value of [post_max_size](https://www.php.net/manual/en/ini.core.php#ini.post-max-size) needs to be larger than [upload-max-filesize](https://www.php.net/manual/en/ini.core.php#ini.upload-max-filesize). Your web server could also restrict the size. I know nothing about IIS, but Nginx has got the setting [client_max_body_size](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size), for example.

**Comment by crixthegreat** [comment]
> The value of [post_max_size](https://www.php.net/manual/en/ini.core.php#ini.post-max-size) needs to be larger than [upload-max-filesize](https://www.php.net/manual/en/ini.core.php#ini.upload-max-filesize). Your web server could also restrict the size. I know nothing about IIS, but Nginx has got the setting [client_max_body_size](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size), for example.

Thanks for your reply. Yes, I use IIS, and I've checked the php.ini again, where the setting is :
post_max_size = 20M

Should I check anything else?

**Comment by splitbrain** [comment]
Sorry, usage and configuration questions like this are better suited for the [forum](https://forum.dokuwiki.org). The issue tracker is reserved for bugs and feature requests.
