### ISSUE TITLE
Rewrite exposes internal animal= parameter in URL

### ISSUE THREAD

**Issue by schplurtz** [splitbrain/dokuwiki#3551]
Hi there.

When using farming, be it with the [farmer plugin](https://www.dokuwiki.org/plugin:farmer), or just a manual setup using `inc/preload.php` to include `inc/farm.php`,  there is a situation where DW will expose the internal animal parameter in the generated URL. This happens with the so called [.htaccess based setup](https://www.dokuwiki.org/farms#htaccess_based_setup).

URL like these : 

    https://my.site/...../animalname/namespace:
    https://my.site/...../animalname/namespace/

get rewritten as

    https://my.site/...../animalname/namespace:start?animal=animalname
    https://my.site/...../animalname/namespace/start?animal=animalname

The expected behaviour is

    https://my.site/...../animalname/namespace:start
    https://my.site/...../animalname/namespace/start

The addition of the animal parameter was introduced in 9dc53973704d379acf43ab39a472f6cfb0226b36.

@selfthinker already acknowledged this behaviour as a bug. Please see
* https://forum.dokuwiki.org/d/19532-animal-parameter-in-wiki-farm-set-up/7
* https://forum.dokuwiki.org/d/19532-animal-parameter-in-wiki-farm-set-up/20

As a quick workaround I [proposed](https://forum.dokuwiki.org/d/19532-animal-parameter-in-wiki-farm-set-up/17) to remove the animal parameter from the list of parameters to add to the URL. This is what @j0hannes proposes in turn in PR #3541 and this effectively fixes the bug.

**Comment by splitbrain** [comment]
The farmer plugin does not create an animal parameter but uses a `!bang` path component, so I don't think it is affected.

I'm not super keen on arbitrarily dropping a parameter from the parameter list... but maybe others can chime in here.

**Comment by schplurtz** [comment]
I don't use the farmer plugin, I just report the conversation but it is probably affected too. It uses `!animal`, but this is rewritten by the web server (at least in certain circumstances) into an `animal=animalname` query string. and the plugin [explicitly uses `$_REQUEST['animal']`](https://github.com/cosmocode/dokuwiki-plugin-farmer/blob/dbe6e959fe564067423091d25474aea4db9ffdae/DokuWikiFarmCore.php#L137) to detect the animal.

Anyway, this is how it is done in `inc/farm.php`. It relies on the web server rewrite rules to append `animal=animalname` to the querystring. Then it [uses this parameter](https://github.com/splitbrain/dokuwiki/blob/f906423e7fbc89734bb221c90d8e3b4b5f943910/inc/farm.php#L50-L52) to detect the animal and route the request to the correct DW instance.

So although the normal URL does not use `animal=animalname` query string in either case, the query string is added by the web server and is there from DW point of view. And so, when DW generate the rewrite URL, it adds it.

Now, I know I only provided a workaround, and was almost certain that a simple drop from the parameter list would not be accepted.

Would it be OK for you if `inc/farm.php` (and the farmer plugin) removed the parameter from the various $_FOO php globals once they have detected the animal ? I'm not even sure it is possible...

**Comment by j0hannes** [comment]
Another, more secure option could be to use `RequestHeader append animal $1` in the farm rewrite rules and adapt line 50 in farm.php to use that environment variable instead:
`if(isset($_REQUEST['animal']) || ('cli' == php_sapi_name() && isset($_SERVER['animal']))) {`
to
`if(isset($_SERVER['HTTP_ANIMAL']) || ('cli' == php_sapi_name() && isset($_SERVER['animal']))) {`

That way, we would 1) avoid letting the user control which animal's data is used (a potential security issue) and 2) prevent dokuwiki from exposing the parameter when issuing rewrites.

**Comment by schplurtz** [comment]
> That way, we would 1) avoid letting the user control which animal's data is used (a potential security issue) and 2) prevent dokuwiki from exposing the parameter when issuing rewrites.

Sure, but it would break existing installations.

Is it not possible to filter out any incoming `animal=foo` query string parameter at the webserver level, so you are sure that this parameter can only be set by your own rewrite rules ?

**Comment by j0hannes** [comment]
A future release could support both options controlled by boolean toggles.

It is easier to just unset any incoming header than parsing the request URL and cutting out the animal parameter. If there would be an elegant way to achieve this, we still need to apply schplurtz' patch to not expose the parameter to the user.

**Comment by splitbrain** [comment]
@j0hannes I agree, that using a header instead of a parameter would have been the better choice. However as pointed out by @schplurtz this would break all existing setups. It also seems like the RequestHeader directive needs the mod_header extension which might not be enabled.

I think the cleanest solution is what @schplurtz suggests. Removing the animal parameter directly where it is used. In the farmer plugin's FarmCore or the inc/farm.php file.

**Comment by splitbrain** [comment]
I added my suggested change to the farmer plugin (see linked commit). I am not using the traditional farm setup, so I would appreciate it if someone could submit an appropriate PR.
