### ISSUE TITLE
Increase the usage of expressions with combined operators

### ISSUE THREAD

**Issue by elfring** [splitbrain/dokuwiki#3553]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of combined operators](https://www.php.net/manual/en/language.operators.assignment.php#language.operators.assignment.arithmetic "Description for assignment operators") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal> perl -p -i.orig -0777 -e 's#(?<target>\$\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+/%^.]|-(?!>)|&(?!&)|\|(?!\|)|\*\*?|<<|>>|\?\?)#$+{target} $+{operator}=#gm' $(find ~/Aktivitäten/DokuWiki/lokal -name '*.php')
```

:crystal_ball: How will development interests evolve further also according to update candidates in 85 lines of this software?

**Comment by splitbrain** [comment]
I am not sure I understand what this ticket is about. I think it suggests to use static source code analysis to find possibilities to improve the sources. We already use php code style. Dedicated tools like phpstan, psalm or rector are for sure a better way than a unreadable perl oneliner.

**Comment by elfring** [comment]
>I think it suggests to use static source code analysis to find possibilities to improve the sources.

This view is appropriate.


>Dedicated tools like phpstan, psalm or rector are for sure a better way

Such software analysis tools are evolving in some directions.


>than a unreadable perl oneliner.

Would you dare to try the shown approach out for the application of named capture groups (according to regular expressions for the search and replacement of a bit of source code)?
