### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [splitbrain/dokuwiki#3558]
Hey there!

I belong to an open source security research community, and a member (@haxatron) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by phy25** [comment]
Meantime you can find the info you need here https://www.dokuwiki.org/security

**Comment by JamieSlome** [comment]
Just realized that I sent over the report to @splitbrain already via e-mail! Thanks for the support and direction here @phy25 ❤️

**Comment by splitbrain** [comment]
@JamieSlome can you remind me again what this was about? Or give me a subject or sender so I can search for it in my emails? 
I don't recall any recent security reports and I want to be sure I actually got it.

**Comment by JamieSlome** [comment]
@splitbrain - it was just regarding a security report that was sent to us! You can see the report here:

https://huntr.dev/bounties/d74ba950-6336-4c77-90e1-22ea3ff5cbdd/

**Comment by splitbrain** [comment]
@JamieSlome that mail landed in my spam (gmail).

Nice platform btw. It would be great though if it would automatically open a Github issue instead relying on mails.

For the issue itself, see #3559

**Comment by JamieSlome** [comment]
@splitbrain - hmm, I wonder why...? Apologies for that!

By default, our platform does open the issue automatically. In this case, the researcher just asked for some further manual support.

If you believe the report to be valid, you can mark as valid and confirm the fix on the report page!

**Comment by Haxatron** [comment]
Hi there, found another issue - https://huntr.dev/bounties/f58aea52-d7c2-4f26-8857-8a8c05f2e9fb/. Am posting it here due to maintainer preference
