### ISSUE TITLE
Solving issues about front-end

### ISSUE THREAD

**Issue by SMSadegh19** [splitbrain/dokuwiki#3568]
Hi.
For an exercise in my university course, I want to solve some issues about **Front-end**.
Please help me and introduce some good-first-issue about Dokuwiki and its plugins.

Thanks a lot.

**Comment by Klap-in** [comment]
Hi @SMSadegh19 ,

Welcome to DokuWiki! Nice that you offer this!
Recently @selfthinker did an accessibility review of DokuWiki. A lot of areas of possible improvements were mentioned. 

Please see:
Audit report: https://www.dokuwiki.org/wcag-audit
The issue are filed at GitHub:
https://github.com/splitbrain/dokuwiki/projects/5

Do you see there already a topic that fits you? Maybe @selfthinker could help you further in finding a good first issue?

**Comment by SMSadegh19** [comment]
Thanks a lot!
From the list that you mentioned, I think one of #3452 or #3463 maybe good.

@selfthinker 
What's your opinion? Are they good as an easy good-first-issue?

**Comment by splitbrain** [comment]
I'm closing this, since it's not really an issue.

@SMSadegh19 pick an issue you like for the list @Klap-in provided, get started and send a pull request. @selfthinker or someone else will review and give comments.
