### ISSUE TITLE
adding a conf setting to stop dokuwiki native syntax parsing

### ISSUE THREAD

**Issue by welkin621** [splitbrain/dokuwiki#3571]
hello

I wonder if  dokuwiki can add a setting option to stop dokuwiki native syntax parsing when showing a page(from txt files).

I am now using a thrid part editor(ueditor), and it generates page files with complete html tags inside the txt files. So dokuwiki just need to show the exact content of the txt file and no need to modify it.   But dokuwiki perses the txt content and makes it  fail to show the right content.

page file content :
![image](https://user-images.githubusercontent.com/37404414/147752390-d07042de-2039-4f1e-842f-5383155dbd94.png)

**desired output in dokuwiki ：**
  <img src="https://img3.mukewang.com/5458683f00017bab02200220-100-100.jpg"/> 

**actually output in dokuwiki：**

![image](https://user-images.githubusercontent.com/37404414/147752497-5292256f-5525-41b6-89f3-f10106ef8453.png)

 I am using hogfather version with php 7.3.5

**Comment by mprins** [comment]
Turn on the htmlok option if you want to mix in html
https://www.dokuwiki.org/config:htmlok

**Comment by Klap-in** [comment]
Disabling syntax parsing will not be implemented in DokuWiki.
If you need this, you could consider creating a (renderer) plugin.
