### ISSUE TITLE
Undefined array key "dontlog" in Logger.php#L30

### ISSUE THREAD

**Issue by mprins** [splitbrain/dokuwiki#3572]
Seeing this in the log after upgrading stable/Hogfather to master/Igor

`PHP Warning:  Undefined array key "dontlog" in /XXXXXXXXXX/www/dokuwiki/inc/Logger.php on line 30`

https://github.com/splitbrain/dokuwiki/blob/8a10303f9b6675b2e7dfc58c265ed47778e897d7/inc/Logger.php#L30

I have some plugins that use the new Logger class and running PHP 8.0.13

In the config page I have no boxes checked
![image](https://user-images.githubusercontent.com/1165786/147813964-33b2f121-bfc7-4fb7-b3b8-0a45cab80c60.png)

**Comment by Klap-in** [comment]
The conf key is also in the file with the defaults delivered at every update of DokuWiki.
If you deselect the 'debug' option of `dontlog`, it should appear white, example above is still blue.
Is your dokuwiki complete? I guess (part of) `conf/dokuwiki.php` is missing.
https://github.com/splitbrain/dokuwiki/blob/d8ab874693a369332dbbecf425e5e612fb1095a6/conf/dokuwiki.php#L114

**Comment by mprins** [comment]
Ahh, yes I may gave forgotten to upgrade the conf dir as that is separated out of the web dir.
I'll check that in the morning

**Comment by mprins** [comment]
update the `conf` directory solved that
