### ISSUE TITLE
allow using revision backend based on git (or something else) instead of archives

### ISSUE THREAD

**Issue by ochurlaud** [splitbrain/dokuwiki#3582]
Whenever we use dokuwiki in a project, it is for the fact that it is file based and can easily be used with git.

However, because the history is stored in archives (and that we don't store archives in git) after each deployment we lose all the history.

Proposition: Make an interface of the "history backend" feature that allow to do everything that is needed with history (diff, browsing history, loading an old revision etc...).  The first implementation of the interface would be (of course) the current one, and other contributors would be able to contribute other implementations (such as git).

**Comment by splitbrain** [comment]
I don't think I follow. You either use git to maintain a history *or* you use the wiki. There is no way to "create" history in git other than checking in every page revision. There are action events when pages are changed, so you could use that to trigger git checkins. Feel free to submit a PR if there are things missing in your opinion.

**Comment by ochurlaud** [comment]
Just to make sure you understand what I would like to be able to do:

When I open this page: https://www.dokuwiki.org/dokuwiki?do=revisions 
 --> I'd like to see the result of `git log pages/dokuwiki.txt` (with some formatting options).

When I open this page: https://www.dokuwiki.org/dokuwiki?rev=1313843193
--> I'd like to see the result of `git show <hash>:pages/dokuwiki.txt` 

When I open this page: https://www.dokuwiki.org/dokuwiki?do=diff&rev2%5B0%5D=1357502572&rev2%5B1%5D=1640028507&difftype=sidebyside 
--> I'd like to see the result of `git diff <hash1> <hash2> -- pages/dokuwiki.txt` 

What I ask for in this issue is not to develop it but to make it possible to someone to implement that, without forking the whole dokuwiki code.  

If this is already possible, then I'd be happy to have some pointers on how to do this.

Thank you for your time

**Comment by ochurlaud** [comment]
@splitbrain This is what I was referring to !!!
https://www.dokuwiki.org/devel:ideas:git_backend
