### ISSUE TITLE
For links that contain hyphens, the DW cuts the link before the hyphen.

### ISSUE THREAD

**Issue by Nihon-Ryori** [splitbrain/dokuwiki#3583]
See follow samples:
  * https://www.fluglärm-portal.de/laerm-vermeiden/moderne-flugzeuge/triebwerke/
  * https://www.fluglärm-portal.de/regeln-gesetze/wer-regelt-was/international/
  
For links that contain hyphens, the DW cuts the link before the hyphen.

**Comment by splitbrain** [comment]
The problem is the umlaut in the domain - DokuWiki will not autorecognize these URLs but you can use the link syntax:

```
[[https://www.fluglärm-portal.de/laerm-vermeiden/moderne-flugzeuge/triebwerke/]]
[[https://www.fluglärm-portal.de/regeln-gesetze/wer-regelt-was/international/]]
```

A URL without non-ascii chars even with hyphens works fine for me. Like this:

```
https://www.fluglaerm-portal.de/laerm-vermeiden/moderne-flugzeuge/triebwerke/
```

**Comment by Nihon-Ryori** [comment]
> A URL without non-ascii chars even with hyphens works fine for me. Like this:

You are right, the bug are not related to the hypen, its related to the umlaut.
For links containing umlauts, the DW cuts off the link before the umlaut.

The follow link are a sample of a link with hypen and without umlaut, which working fine:
* https://www.united-domains.de/

**Comment by Nihon-Ryori** [comment]
That umlaut domains are quite standardized nowadays can be seen from the following two sources:
* https://de.wikipedia.org/wiki/Internationalisierter_Domainname
* https://en.wikipedia.org/wiki/Internationalized_domain_name
