### ISSUE TITLE
Dukuwiki omits hyphens in headings.

### ISSUE THREAD

**Issue by Nihon-Ryori** [splitbrain/dokuwiki#3584]
Sample, original code:
===== Ausgelassene Bindestriche in Überschrift: 2021-12-24, pi-hole =====

How Dokuwiki presents the headline:
Ausgelassene Bindestriche in Überschrift: 2021  12  24, pi  hole

**Comment by splitbrain** [comment]
can not reproduce: https://www.dokuwiki.org/playground:issue3584

**Comment by Nihon-Ryori** [comment]
Now I checked the bug again.

The bug occurs in the following configuration:
* Release 2020-07-29 "Hogfather"
* vector design
* language de-informal

The bug don't occurs in the following configuration:
* Release 2020-07-29 "Hogfather"
* vector design
* language de

The bug don't occurs in the following configuration:
* Release 2020-07-29 "Hogfather"
* vector design
* language en

**Comment by Klap-in** [comment]
In a development version with the vector template and language de-informal it works fine for me.

The page scaling of your browser is not too small so that due to rendering of the browser the hyphens are not visible? Further no ideas.

**Comment by Nihon-Ryori** [comment]
> In a development version with the vector template and language de-informal it works fine for me.

Thats sound great.

THX
