### ISSUE TITLE
Links with an x in front of the http or https shred the display.

### ISSUE THREAD

**Issue by Nihon-Ryori** [splitbrain/dokuwiki#3585]
To test, insert the blank between the following two lines on a page of the Dokuwiki and remove the blank from the x and the http or the x and the https:
  * x http://www.startpage.com
  * x https://www.startpage.com

**Comment by splitbrain** [comment]
works for me: https://www.dokuwiki.org/playground:issue3585

Make sure you're not affected by #3507

**Comment by Nihon-Ryori** [comment]
I tested it again.

The bug occurs in the following configuration:

    Release 2020-07-29 "Hogfather"
    vector dokuwiki and design
    language de, en and de-informal

Pls copy the follow to your test page:

===== Links bei denen vor den http oder dem https ein x steht, schreddern die Darstellung von dahinter befindlichen Inhalt. =====

Zum Test das Leerzeichen zwischen folgende zwei Zeilen auf einer Seite des Dokuwiki einfügen und das Leerzeichen dem x und dem http bzw. dem x und dem https entfernen:
  * x http://www.startpage.com
  * x https://www.startpage.com

==== Testtext, der das Schreddern des Inhaltes zeigt ====

Das ist ein Text, der dazu dient um zu zeigen, das ein davor befindliches x http als auch ein x https, die Darstellung von dahinter liegenden Text schreddert, wenn sich zwischen dem x http oder zwischen dem h https kein Leerzeichen befindet.

**Comment by Klap-in** [comment]
I tried both on https://www.dokuwiki.org/playground:issue3585, x http... and xhttp... I do not yet see a difference. 
Can you reproduce it on dokuwiki.org as well?

You are indeed not affected by #3507? 

Quoted:

    PHP in version 10.37 and 10.38.
    ...
    There are additional reports that this is still broken in recent PCRE release 10.38 but can be mitigated by disabling JIT 
    compiling in php.ini:
    
       pcre.jit=0

**Comment by Nihon-Ryori** [comment]
I dont know how to edit the follow, so I cant try to reproduce it on follow page on this time:
* https://www.dokuwiki.org/playground:issue3585
You can see the bug if you compare the follow screenshots:

The 1st screenshot show the result if a space between x and http and x and https.
* pls wait some minutes

The 2.nd screenshot show the result, if the space between  x and http or x and https are removed.
* pls wait some minutes

**Comment by Klap-in** [comment]
xhttp is not a valid start of an url, therefore, it is not recognized as part of an url. A double slash e.g. `//some italic text//` is the syntax to make text italic.
If the url is not recognized as url, than DokuWiki tries to use the slashes as italic syntax.

Why is it logic to let DokuWiki recognize xhttp instead of http? Even if normal users try to copy it they have a link that is broken?

if you need text and a url that should touch each other, than you can use x[[https://www.startpagina.com]]

**Comment by Nihon-Ryori** [comment]
If I remember right, I have seen, two or 3 years ago a website which start with xhttp:// or xhttps and have seen what happen by this on dokuwiki. After than I saved it on my buglist. Now I am reporting, what I have seen.

Perhaps xttps or xhttps are related on one of the follow:
* https://xhttp.org/
* https://xhttps.com/
* https://www.codegrepper.com/code-examples/javascript/xhttp+send
* https://www.w3schools.com/xml/xml_http.asp

That all information what I have on this time.

**Comment by Klap-in** [comment]
But these have still as protocol scheme `http` or `https`, if I read quickly?

But if you need such a protocol scheme like `xhttp` or `xhttps`, you can configure it for your wiki via: https://www.dokuwiki.org/urlschemes I think then also url should be recognized.
