### ISSUE TITLE
An address notation used by Wikipedia, but which Dokuwiki misrepresents.

### ISSUE THREAD

**Issue by Nihon-Ryori** [splitbrain/dokuwiki#3586]
An address notation used by Wikipedia, but which Dokuwiki misrepresents. The link is not correctly displayed after the underscore:
  * Jetty Wikipedia Artikel: https://de.wikipedia.org/wiki/Jetty_(Webserver)

**Comment by splitbrain** [comment]
DokuWiki is not MediaWiki.  `[[Jetty_(Webserver)]]` will clean up the id properly to `jetty_webserver`.

**Comment by Nihon-Ryori** [comment]
I tested it again.

The bug occurs in the following configuration:

Release 2020-07-29 "Hogfather"
vector dokuwiki and design
language de, en and de-informal

You can see the wrong representation on the following screenshot:
* pls wait some minutes

**Comment by Klap-in** [comment]
DokuWiki accepts now external links with match the following regexp.

**Comment by Klap-in** [comment]
Sorry wrong pointer, now updated.
I guess brackets are not recognized. What are proper characters that should be recognized? are brackets logic?

**Comment by Klap-in** [comment]
I assume Mediawiki seems to use a quite different regexp, not sure if I look at the right place. https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/parser/Parser.php$2128
@micgro42 is this the right code?

**Comment by Nihon-Ryori** [comment]
> DokuWiki accepts now external links which matches the following regexp.
> 
> https://github.com/splitbrain/dokuwiki/blob/b5b12e446f420be6305d55841704207096b889db/inc/Parsing/ParserMode/Externallink.php#L15-L29

Perhaps the used regex roules can be optimized, to support one more on internet used way to write some thing.

**Comment by micgro42** [comment]
Sorry, I missed the ping earlier.

The core problem here seems to about that DokuWiki's auto-detection of links in plain text is breaking at opening parenthesis and is expecting them to be html escaped: https://www.dokuwiki.org/playground:issue3586

While I think I remember that browser _used to_ url-escape parentheses when copying the url from the address bar, they have stopped doing so now. I just tested it with Firefox and Chromium for https://de.wikipedia.org/wiki/Jetty_(Webserver).

So, given that apparently parentheses are no longer being html escaped in practice, the question would be: do we want to adjust our external-link auto-detection?

**Comment by micgro42** [comment]
@Klap-in Yes, I think that is roughly the right place. Though as the comment notes, there are also tests for this code and those are probably instructive for what mediawiki does: https://github.com/wikimedia/mediawiki/blob/master/tests/parser/parserTests.txt#L5234

Interesting side observation: In the comments here, GitHub understands the parentheses as being part of the link: https://de.wikipedia.org/wiki/Jetty_(Webserver) but in the .txt file I linked above, it does not understand that and shows the same behavior as DokuWiki:

![image](https://user-images.githubusercontent.com/7372507/157279646-68760534-6a14-403c-9de4-f99fb1392ce9.png)

**Comment by Klap-in** [comment]
Thanks for your reaction. The tests are indeed practical. 
Handling of urls by GitHub is interesting indeed. 
An example for a parser is markdown-it, which uses linkiky-it.
parser https://github.com/markdown-it/linkify-it/blob/master/lib/re.js
They provide another bunch of tests
http://markdown-it.github.io/linkify-it/

A php parser https://github.com/cebe/markdown/blob/master/inline/UrlLinkTrait.php
Tests https://github.com/cebe/markdown/blob/master/tests/github-data/url.md
