### ISSUE TITLE
table breaks by parsing malformed https. strings

### ISSUE THREAD

**Issue by viisauksena** [splitbrain/dokuwiki#3588]
Dokuwiki Pages break by having multiple tables on one site and also some https links which are badly formattet
like 

```
^example1^break1^my1^neck1^
|foo|bar|2000|none|
inline\n\nblubbel test text
blablabla:   https.//irgendwo.de, out

^example1^break1^my1^neck1^
|foo|bar|2000|none|
test text **bold** something
foofoofoo:   https.//nirgendwo.de, out

^example1^break1^my1^neck1^
|foo|bar|2000|none|
test text **bold** something
```

```
^example2^break2^my2^neck2^
|foo|bar|2000|none|
inline\n\nblubbel test text
blablablahttps://irgendwo.de, out

^example2^break2^my2^neck2^
|foo|bar|2000|none|
test text **bold** something
foofoofoohttps.//nirgendwo.de, out

^example2^break2^my2^neck2^
|foo|bar|2000|none|
test text **bold** something
```
```
^example3^break3^my3^neck3^
|foo|bar|2000|none|
inline\n\n**__blubbel test text**__**
blablabl **

^example3^break3^my3^neck3^
|foo|bar|2000|none|
test text **bold** something
foofoofoo, out


```

if 
1. String before is foobarhttps:\\   # note the missing space
2. wrong https like https.\\     # note the dot instead of : 
3. if you intermix bold and underline like * * _ _ * * _ _ * *

we have no direct control over text input by a script / automation - so people will do this mistakes.
nevertheless : dokuwiki should not break by parsing https links

**Comment by splitbrain** [comment]
these are not proper links. double slashes open italics syntax.

**Comment by viisauksena** [comment]
thanks, that explains a lot : nevertheless , this should not break pageflow or tables
