### ISSUE TITLE
Internal link with hash results in formatting as not-existing

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki#3608]
At dokuwiki.org a lot of links with a hash becomes a red internal link, while the page exists and the hash is right and works as well.

From https://www.dokuwiki.org/faq#usage for example 
  * [[page#Create a page|How to add pages?]]
  * [[page#Delete a page|Delete pages?]]
  * [[faq:howto-rename-pages]|Rename pages?]]

I guess something is changed, I haven’t traced it.

**Comment by Klap-in** [comment]
First guess, not yet tested.
In metadata the hash is splitted:
`@list($page) = explode('#', $id, 2);`
In the internallink function not, see also https://github.com/splitbrain/dokuwiki/commit/8c6be208dcb4734cf5ad7e62ab5df1d42d46ad76

Part of #3272

**Comment by splitbrain** [comment]
Correct, this broke with #3272. The old page_resolve function was also returning the existence info. For a cleaner API that part has been dropped in the new PageResolver class and the existence check is now done separately: https://github.com/splitbrain/dokuwiki/blob/014550766a823d0d84b238f30ad7cc57f8efccc5/inc/parser/xhtml.php#L896-L897

I see two ways to fix this:

1. make page_exists() handle hashes
2. remove hash handling from PageResolver and thus establish that all our methods expect IDs without hashes and that hashes have to be handled outside (eg. in the renderer above)

I think 2 would be the saner, cleaner way but 1 is probably less likely to break at further unexpected places...

**Comment by Klap-in** [comment]
3. Add manually splitting of hashes before page_exists(). Shows more explicitly what happens with the data.

code searches for quick impression:
[Explode resolve_pageid](https://codesearch.dokuwiki.org/search?full=resolve_pageid+explode&defs=&refs=&path=&hist=&type=&xrd=&nn=3&si=full&searchall=true&si=full)
[Explode page_exists](https://codesearch.dokuwiki.org/search?full=Page_exists+explode&defs=&refs=&path=&hist=&type=&xrd=&nn=3&si=full&searchall=true&si=full)

option 2 requires more changes in the logic used in the plugins, because you have to get the hash before the resolve. However, these resolve changes are of course already not backwards compatible.

I’m in favor of option 1, because it makes the page_exists() more robust, and does not change the working of page_exists().
