### ISSUE TITLE
xmlrpc: Error: Class "IXR_Error" not found

### ISSUE THREAD

**Issue by rozhuk-im** [splitbrain/dokuwiki#3619]
Got error in logs:
```
2022-02-03 12:26:53	/usr/local/www/wiki/lib/exe/xmlrpc.php(13)	Error: Class "IXR_Error" not found
  #0 {main}
```
if ```remote``` is disabled.

https://github.com/splitbrain/dokuwiki/blob/master/lib/exe/xmlrpc.php#L13
probably some include was missed and this line generates error.

**Comment by Klap-in** [comment]
I guess you are using a development version?
Probably a it is then due to #3534

**Comment by rozhuk-im** [comment]
Yes, I'm on latest commit.
