### ISSUE TITLE
 Class 'dokuwiki\\Remote\\IXR\\Client' not found

### ISSUE THREAD

**Issue by turnermm** [splitbrain/dokuwiki#3626]
I just began working again on my XML-RPC plugin (xcom), and found it throws the above error.  The code is as illustrated in https://www.dokuwiki.org/devel:xmlrpc:clients, which is the code I was using in my tests, referred to  in #3534.  At the time of #3534, I may have be using the dokuwiki version that used the kissyfrot/php-ixr ixr version.   Now I am using hogfather, and I have not been able to find the code for the IXR\Client.

**Comment by turnermm** [comment]
Looks like this has been addressed in the latest master.

**Comment by Klap-in** [comment]
Indeed, please see #3620

**Comment by Megachip** [comment]
Getting this error after upgrading from 2020-07-29 to 2023-04-04 via upgrade script :(
