### ISSUE TITLE
Dokuwiki's use of .htaccess is a violation of proper apache2 security config as documented in the apache2 webserver documentation

### ISSUE THREAD

**Issue by bakertaylor28** [splitbrain/dokuwiki#3633]
Dokuwiki should not be using .htaccess files, but rather all .htaccess directives should be hard-coded into apache2.conf - the reason why is because "AllowOveride None" should be set in apache2.conf to avoid so much as the remote potential of a .htaccess file being written to by a remote source in the event that file permissions are compromised in the server root folder or in directories contained within the server root folder. This is a well known best-security practice which has been well documented in apache2 documentation for quite some time now, and this needs to be corrected because it presents a major server security issue as defined in the apache2 documentation.

**Comment by splitbrain** [comment]
you're free to set it up this way. but we won't ignore the reality of how cheap web hosting works.
