### ISSUE TITLE
Error after trying to install an extension via 'search and install'

### ISSUE THREAD

**Issue by D4di69** [splitbrain/dokuwiki#3643]
Dokuwiki was ok. No error.
When i tried to install an extension on the extension manager i clicked 'search and install' and typed 'line break' because i wanted to add that line break plug-in from 2007, when i clicked install everything on the website broke with this error:
`
Fatal error: Declaration of action_plugin_linebreak::register(&$controller) must be compatible with dokuwiki\Extension\ActionPlugin::register(Doku_Event_Handler $controller) in /home/torre502/public_html/chaoswiki/lib/plugins/linebreak/action.php on line 41`
the website that have my wiki right now is [https://torrentdonkey.com/chaoswiki](url) now every page of my wiki contains only this stupid error. Please solve this problem, thanks.

**Comment by mprins** [comment]
@D4di69 please report this to the line break plug-in; it is no longer compatible with your version of DW
see https://www.dokuwiki.org/plugin:linebreak?s[]=line&s[]=break

**Comment by D4di69** [comment]
> @D4di69 please report this to the line break plug-in; it is no longer compatible with your version of DW see [https://www.dokuwiki.org/plugin:linebreak?s[]=line&s[]=break](https://www.dokuwiki.org/plugin:linebreak?s%5B%5D=line&s%5B%5D=break)

yes but all the wiki doesn't work now, all pages

**Comment by D4di69** [comment]
> @D4di69 please report this to the line break plug-in; it is no longer compatible with your version of DW see [https://www.dokuwiki.org/plugin:linebreak?s[]=line&s[]=break](https://www.dokuwiki.org/plugin:linebreak?s%5B%5D=line&s%5B%5D=break)

ok i'm trying to remove manually the plug-in and report it, thanks!
