### ISSUE TITLE
Layout is not complete in 2020-07-29 "Hogfather" release

### ISSUE THREAD

**Issue by gladk** [splitbrain/dokuwiki#3649]
I am working on bringing the stable 2020-07-29 version into Debian.

After the installation one can see some problems with the layout:
![2020](https://user-images.githubusercontent.com/1476497/160274790-511465eb-bf22-42b9-b5c3-cfeb160d510c.png)

---------------------------------------------
---------------------------------------------

The snapshot version (2022-03-17) does not have this problem:
![2022](https://user-images.githubusercontent.com/1476497/160274801-4c5f8c87-7dd3-41a3-858f-2254d4312a81.png)

My idea was to package the stable version. But due to this issue it is not quite possible. Is there any solution for that?

Thanks

**Comment by Klap-in** [comment]
The package from the Debian repository has a different organization of its folders if compared to the default release. Mixing them will probably mess up things.

@ortolot did the previous packaging, maybe he has the possibility to help you.

See also documentation like https://www.dokuwiki.org/install:debian

**Comment by gladk** [comment]
OK, thanks. It looks like the newer packaging version is working now. Thanks, the problem is resolved.
