### ISSUE TITLE
Change logo/site header title attribute to be more meaningful

### ISSUE THREAD

**Issue by Nightfirecat** [splitbrain/dokuwiki#3661]
Presently, the header logo and wiki title have an HTML title of `[H]` (which I assume stands for "Heading"?), which is not configurable, clear, or helpful.

![Screenshot_20220416_212752](https://user-images.githubusercontent.com/2199511/163700507-34d78e79-90b5-44f8-accb-0d7daae10d89.png)

This appears to have been added to the dokuwiki template _ten years ago_ in #82, and [remains mostly unchanged since then](https://github.com/splitbrain/dokuwiki/blob/0be5b90a0fba6cb62d991f15eb344cac1b63356e/lib/tpl/dokuwiki/tpl_header.php#L29). Ideally, I would imagine this title would be (a) removed, (b) a copy of the wiki title or tagline (if set), or (c) configurable separately from the title and tagline.

**Comment by Klap-in** [comment]
At more places you see in the titles these additional `[H]` (go to home page), [e] edit, [o] older versions, etc.
This tell there is an access key added to these elements in the wiki page.

Please see for more details and how you can use access keys in your browser, on https://www.dokuwiki.org/accesskeys

**Comment by Nightfirecat** [comment]
I see, that does explain the usage for it--thank you for that link. I still think its function is fairly unclear from the title alone. [e], [o], and [t] all have text which explains what the letters correspond to:

* Create this page [e] / Edit this page [e]
* Old revisions [o]
* Back to top [t]

The homepage title does not include any additional text which would indicate that [H] is meaningful separately from it.

**Comment by Michaelsy** [comment]
> Perhaps it could be changed to "Open homepage [H]" or something of the sort?

I would suggest `Home [H]`.

\- Michael Sy.
