### ISSUE TITLE
ACL Plugin - Cannot create group with ":" in its name

### ISSUE THREAD

**Issue by jeffchulg** [splitbrain/dokuwiki#3663]
In the way I though about how to use dokuwiki, I wanted to create a structure with namespaces that correspond to the structure of my organization.

I installed the GroupHome plugin so that any member of a team would come directely to the namespace corresponding to its team.

However, when I try to add ACL on a namespace to a group with same matching name, then the ":" is translated to "_", meaning that the GroupHome plugin cannot work as expected.

**Comment by splitbrain** [comment]
With the plain auth backend, user and group names have to be valid page names (without a namespace).
