### ISSUE TITLE
ACL malfunction? All groups frozen in read-only mode but @ALL

### ISSUE THREAD

**Issue by Guy270** [splitbrain/dokuwiki#3667]
superuser admin is ok too.
I noticed after installing ckgedit, tried everything I could think of, even uninstalling it, and the problem remains.

What I had done before:
the day before I had  replaced a number of image files with lighter versions through FileZilla ftp in a subdirectory of doku/data/media/. That doesn't seem to have caused any problem, I can see these images in the documents.

In the morning, before installling ckgedit, I had changed the permission of @ALL from read to none and activated sneaky_index so @ALL couldn't even see the site plan. I created a visitor group with read-only permission.
CKGedit worked fine for the superuser admin but the user group is stuck in read-only. I didn't creat fake accounts for the two other groups to check.

I stopped ckgedit, and even uninstalled it, to no avail. I reinstalled it and nothing changed.

At some point I cleaned the cache. Had no effect. 

At my wit's end **I changed @ALL to write and I can now use ckgedit without login in!** I reverted @ALL to its default read permission.
I unchecked sneaky_index,to no avail.

Latter, erased locks that had remained,still no effect.

I turned the debuger on and did some operation with my user group permission. Searching a unexisting file to create it I got the red filename to open it but couldn't. I logged in as admin and could edit the file. Didit for another existing file.
Went to ACL and changed @ALL to none, logged out as admin and could see site plan but not files. Normal.

Latter I put the debuger back on, edited a file as admin,  changed user group permission to read, saved changes, then back to create and saved. did some stuff as user, trying to edit a file.

Thanks for your attention.

[DokuWikiACLproblem-debuglog-grh-2022-04-25.txt](https://github.com/splitbrain/dokuwiki/files/8555701/DokuWikiACLproblem-debuglog-grh-2022-04-25.txt)

**Comment by Michaelsy** [comment]
Issue [can be closed](https://forum.dokuwiki.org/d/20127-ckgedit-only-worksfor-superuser/13).

\- Michael Sy.
