### ISSUE TITLE
Configuration manager changes don't respect fmode setting for local.php file

### ISSUE THREAD

**Issue by Nightfirecat** [splitbrain/dokuwiki#3671]
Issue opened after discussion on the forums: https://forum.dokuwiki.org/d/20140-configurations-are-world-readable-0644-permissions/5

Setting `fmode` to any non-`0644` value, then saving some subsequent change in the configuration manager updates local.php's permissions to 0644. See below:

```
$ ls -l /data/docker/dokuwiki/conf/local.php{,.bak.php}
-rw------- 1 www-data www-data 1022 May  1 10:29 /data/docker/dokuwiki/conf/local.php
-rw------- 1 www-data www-data 1.1K May  1 10:28 /data/docker/dokuwiki/conf/local.php.bak.php

$ sudo grep 'fmode' /data/docker/dokuwiki/conf/local.php
$conf['fmode'] = 0600;

# now, open configuration manager, make any configuration change, then save it.

$ ls -l /data/docker/dokuwiki/conf/local.php{,.bak.php}
-rw-r--r-- 1 www-data www-data 1023 May  1 20:28 /data/docker/dokuwiki/conf/local.php
-rw------- 1 www-data www-data 1022 May  1 10:29 /data/docker/dokuwiki/conf/local.php.bak.php

# if another configuration change is made, `local.php` is copied to `local.php.bak.php`, thereby also removing the 0600 permissions it has
```

I would expect configuration manager to follow `fmode`'s value, maintaining the 0600 value I had previously set for these files.

**Comment by Klap-in** [comment]
I assume there is no relation, but to make everybody aware, here a pointer to recent changes of the fmode/dmode mechanism: #3520

**Comment by Klap-in** [comment]
Actually code that performs the save:
https://github.com/splitbrain/dokuwiki/blob/10f359ad043755b26638bd58a4a7ee63949147e1/lib/plugins/config/core/Writer.php#L31-L57

**Comment by Klap-in** [comment]
And other fperm changes since previous release: #2985

**Comment by splitbrain** [comment]
Can anyone confirm or deny if this problem still exists in current master?

**Comment by Nightfirecat** [comment]
Testing this on a local installation on master doesn't seem to exhibit the same behavior, I'm seeing local.php created and updated with 600 permissions per the `fmode` setting. I guess this can be closed then, apologies for not checking that first!

**Comment by splitbrain** [comment]
Thank you for checking.
