### ISSUE TITLE
Add checks for config setting documentation to CI pipeline

### ISSUE THREAD

**Issue by mperry2** [splitbrain/dokuwiki#3674]
Add a CI check for config settings that ensures there's corresponding documentation on the dokuwiki.org web site for the setting. Proper documentation should be part of delivering a new feature or config setting. This check will ensure that happens before a new setting is merged.

For example, I found that the config setting, `mailreturnpath`, lacks documentation on the web site. The config setting in the Configuration Manager page links to http://www.dokuwiki.org/config:mailreturnpath but there is nothing there.

**Comment by Klap-in** [comment]
At the moment, it is only visible by the red links on the overview on the page https://www.dokuwiki.org/config
but it depends of course on manually updating of that page.

CI is welcome, but of course it needs also people writing such pages. But maybe if these pages are already created by PR authors, it invites further improving them by others.

**Comment by mperry2** [comment]
@splitbrain, why was this closed?

**Comment by mperry2** [comment]
@Klap-in, assuming that dokuwiki.org has XML-RPC enabled, then it should be easy to set up a github action to create and/or update a page on the wiki with the documentation when a commit is made to the repo that affects a config settings. In fact, it might be better to move the documentation into the repo so it's under version control along with the config setting code itself (all in one place).

**Comment by mperry2** [comment]
@splitbrain, Thanks for the fix! Do you think there would be any value to moving the documentation into the repo and having github actions create and/or update the pages on dokuwiki.org?

My reasoning is that:

  1. the documentation can stay closer to the code and under version control in the repo.
  2. if the documentation is in a machine readable format, even if it were something simple like CSV (or even simply dokuwiki syntax), then we can make sure the pages on dokuwiki.org are consistent. Right now anyone can edit the pages and change them in any way without being logged in.
  3. the config setting pages on dokuwiki.org could be locked with ACLs so that they can only be updated via the github actions. Might be a good idea given the importance of those pages.

Or would this be too much to change for too little gain?

**Comment by splitbrain** [comment]
> Right now anyone can edit the pages and change them in any way without being logged in.

Yes. That's the idea of a wiki.
