### ISSUE TITLE
All svg images in page are resized to 1.2em high

### ISSUE THREAD

**Issue by schplurtz** [splitbrain/dokuwiki#3690]
Hi,

b43eeadb4d forces svg heigth to 1.2em by adding this CSS rule to `lib/styles/all.css`
```
svg {
    width: auto;
    height: 1.2em;
}
```

The problem is that **all SVG images** wherever they come from are resized to 1.2em high. This is a problem with the [a2s](https://www.dokuwiki.org/plugin:a2s) plugin for example. The as2 plugin generates images like this :

```
<svg class="a2s media" width="721px" height="944px" viewBox="0 0 721 944" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Created with ASCIIToSVG (https://github.com/dhobsd/asciitosvg/) -->
Image content here.
</svg>
```

Yet, the svg is  resized to 1.2em high.
<img width="533" alt="image" src="https://user-images.githubusercontent.com/1008292/173499551-5c1bb12a-e42a-49de-9c26-0af051a20199.png">

In the case of the a2s plugin, I can of course add a css rule `svg.a2s { height: auto }` in he plugin style files, but I'm wondering if it should be fixed there or more generally in DokuWiki.

**Comment by splitbrain** [comment]
I think this guardian makes sense and so far I haven't heard of any plugins breaking because of it. So I would like to keep it. So yes, please add the custom height for your plugin's SVGs to the plugin's style file.

**Comment by schplurtz** [comment]
All right. Thanks for the answer.

**Comment by jdehaan** [comment]
I use a vendor lib to render svgs and have no direct control upon the attributes/style for the svg tag. The latest release candidate shows up trouble with the svg style which makes all diagrams cut-off.

This is the extension: https://www.dokuwiki.org/plugin:bpmnio

**Comment by splitbrain** [comment]
@jdehaan Of course you have control. Your plugin's style will be more specific than the default setting. In your case it's as easy as adding the following to your styles:

```
.bjs-container svg {
    height: 100%;
    width: 100%;
}
```

Though preferably you would set your own class on the wrapper (something like `plugin-bpmnio`) instead of relying on the class set by the vendor script.

**Comment by jdehaan** [comment]
You are fully right I could manage to arrange the stuff accordingly... As you have seen I am not a css master. Thanks for the precise hint!

**Comment by arlt** [comment]
> I think this guardian makes sense and so far I haven't heard of any plugins breaking because of it. So I would like to keep it. So yes, please add the custom height for your plugin's SVGs to the plugin's style file.

@splitbrain 

Here is (another) one: https://github.com/jakob1111/dokuwiki-plugin-flowcharts/issues/27

Yes, the plugins could fix this but in my opinion there is no real reason to set the default height for all svg images to 1.2em.. This is a problem for all plugins which render svg images. Maybe using a class toolbar or icon would be a better idea.

The response of plugin authors is rather slow, if at all.

**Comment by gerardnico** [comment]
I got also this problem for the [combo svg element](https://combostrap.com/content/how-to-use-a-svg-in-combostrap-t0bzvu0u)

I don't understand why this is made a global default.
It made no sense at all.
All svg have already default internal dimensions with the `width` and `height` attributes.
(Icon does, ...)

DokuWiki should also have its own namespace by applying a class to not leak this kind of rule.
This rule is for an icon.
```
svg.dokuwiki-icon {
    width: auto;
    height: 1.2em;
}
```

It will just break all svg plugins.
I don't understand the positive here.

**Comment by zeerd** [comment]
Me, too. I had to modify this `lib/styles/all.css` from 1.2em to auto  manually to make my wiki working. It terrible.

**Comment by gerardnico** [comment]
> we have to deal with it

I'm so sorry for you.
