### ISSUE TITLE
Missing IXR_Library.php

### ISSUE THREAD

**Issue by ChristianKrausse** [splitbrain/dokuwiki#3697]
After updating to rc2022-06-26 "Igor" the  doku.php?id=start&do=admin page said it is missing the IXR_Library.php.
I suspect it was from the sync-plugin...
I used the one from https://raw.githubusercontent.com/lsmonki/php-ixr/master/IXR_Library.php and placed it into the /inc/ subdir.

**Comment by Klap-in** [comment]
Of course the plugin has to update the dependencies, but normally we deprecate functionality in two release.

We need to add these classes to inc/deprecated.php
#3534
