### ISSUE TITLE
pages missing after update to Igor

### ISSUE THREAD

**Issue by maigretsshadow** [splitbrain/dokuwiki#3698]
I have just updateted my dokuwiki installation to the newest release using the update plugin. A small number of pages are now defunct. However, the corresponding txt-files are still on the server, so the data isn't lost, and tagfilter still lists links to those missing pages
![exp](https://user-images.githubusercontent.com/108334166/176153713-0c181aa9-e4f0-4b54-9189-055faf60a340.jpg)

This problem seems to only affect pages/namespaces that have the Turkish letter "ı" in their name.

**Comment by splitbrain** [comment]
for an affected file please provide:

* the name (including the full path within the data dir) used on the filesystem
* the href used in the link
* the name (including namespaces) used in the url when following the link
* all your setting regarding file name encodings, romanization etc.

**Comment by maigretsshadow** [comment]
1. the name (including the full path within the data dir) used on the filesystem: 
/dokuwiki/data/pages/kurzbiographien/hac%C4%B1h%C9%99s%C9%99nski_xudadat_b%C9%99y.txt

2. the href used in the link: /doku.php?id=kurzbiographien:hac%C4%B1h%C9%99s%C9%99nski_xudadat_b%C9%99y

3. the name (including namespaces) used in the url when following the link:
kurzbiographien:hac%C4%B1h%C9%99s%C9%99nski_xudadat_b%C9%99y

4. all your setting regarding file name encodings, romanization etc.: 
fnencode: url
deaccent: 1

Updating from Hogfather to Igor I didn't fiddle with any settings. Everything worked fine on Hogfather.

**Comment by splitbrain** [comment]
Deaccenting that character was added in a178f5e0 - I consider this a correct fix, but yes it will break page names using that character.

I created a little file that you can use to rename your files accordingly: https://gist.github.com/splitbrain/c6f1ac33d64b5290a841fbb9d1ded47e
