### ISSUE TITLE
Incorrect differences in size between old revisions

### ISSUE THREAD

**Issue by Michaelsy** [splitbrain/dokuwiki#3700]
Incorrect differences in size between old revisions are shown for this [DokuWiki page](https://www.dokuwiki.org/doku.php?id=config%3Arememberme&do=revisions).

An Igor issue?

\- Michael Sy.

**Comment by splitbrain** [comment]
Those changes are really old. I don't remember when we started tracking size changes in the changelog but it has only been in one of the last couple of releases. So for these old changes the info is not available.

**Comment by Klap-in** [comment]
Indeed, it is added by https://github.com/splitbrain/dokuwiki/pull/1316
