### ISSUE TITLE
curly braces is no longer supported in plugins/captcha/helper.php

### ISSUE THREAD

**Issue by FMescam** [splitbrain/dokuwiki#3702]
Since I upgrade to php8.1 I have these errors 
Array and string offset access syntax with curly braces is no longer supported in /var/www/html/dokuwikiFM/dokuwiki-2022-06-26-Igor-RC2/lib/plugins/captcha/helper.php on line 285
Find in attach file a patch for that
[captcha.helper.php.txt](https://github.com/splitbrain/dokuwiki/files/9026526/captcha.helper.php.txt)

**Comment by splitbrain** [comment]
please report in the captcha plugin's tracker
