### ISSUE TITLE
Page abstract doesn't escape blockquotes

### ISSUE THREAD

**Issue by iainhallam** [splitbrain/dokuwiki#3705]
In several pages of one of my DokuWiki sites, the page starts with a title immediately followed by a block quote:

```
====== My Title ======

> Quote here

Text here
```

When the page is rendered, this is early enough in the text of the page to be added to the page abstract, contained in the meta description element:

```html
    <title>blockquote-test</title>
    <meta name="description" content="My Title

	" Quote here"

Text here">
```

As you can see, the blockquote element is rendered as quotation marks around its content, when rendered into the metadata, making the content of the blockquote appear as extra attributes to the meta element. The reason I found this was that I included a quote that contained a greater than sign:

```
====== My Title ======

> Pen > Sword
```

This renders fine into the document with a correct `&gt;` entity. However, in the metadata, this happens:

```html
    <meta name="description" content="My Title

	" Pen > Sword"">
```

Because the blockquote renders as ASCII quotation marks, rather than the proper start and end quotes that would result from using `"` in the content, `Pen > Sword` is actually outside the description attribute, so the greater than sign becomes a closing of the meta element, and the `Sword"">` is then rendered by the browser into the page body, cutting off the rest of the header.

Perhaps the functions at https://github.com/splitbrain/dokuwiki/blob/master/inc/parser/metadata.php#L292 should inject UTF opening and closing quotes or HTML entities to prevent this behaviour?

**Comment by iainhallam** [comment]
I have tried replacing the string literals for `"` in those two functions with single characters UTF 8220 and 8221 (left double quote and right double quote) and it seems to fix the issue.

**Comment by phy25** [comment]
For your "meta description element", what template are you using? I can't find it in the default dokuwiki template.

**Comment by Klap-in** [comment]
What about the solution of escaping the content of the meta tag properly?

**Comment by splitbrain** [comment]
Whatever template that is - it is vulnerable to XSS attacks. The meta description is not properly escaped. This needs to be fixed in the template. Changing the quote style would only patch up some symptoms.
