### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Ashtagon** [splitbrain/dokuwiki#3707]
I just updated to the latest (Igor2) version of dokuwiki, on a localhost windows installation.

I use image resizing heavily. A typical line of wikicode for one of my images is:

<div image right 154px>{{:folder:subfolder:filename.png?154|image alternate or mouseover text}}Text below image</div>

(I use the [wrap plugin](https://www.dokuwiki.org/plugin:wrap) to position the image; this allows me to also ensure the caption below the image is properly wrapped to the width of the image exactly.)

I've noticed that although "legacy" uploaded images appear resized normally, any new images appear at a very low resolution, as if they are displaying based on the small thumbnail from the media manager rather one that is generated for the frontend "display" version of the wiki. This happens regardless of the size I try to resize the image to (even if I choose to resize it to its original width), and regardless of the use of the wrap plugin.

(ie, with an image that is natively 388 pixels wide, {{image.png?388}} results in a low-resolution, "thumbnail quality" image being displayed, but {{image.png}} results in the original high-quality image.)

Localhost details: Windows 10 Enterprise, running wampserver 3.2.0, with php 7.4.0. image magick/libgd not used and not installed.

wiki code used to demonstrate attached screenshot (the image in question is natively 388x1580 pixels):
```

{{ :wc:a-gmg:a-gmg_085.png?154|Fear of Falling}}

{{ :wc:a-gmg:a-gmg_085.png?388|Fear of Falling}}

{{ :wc:a-gmg:a-gmg_085.png|Fear of Falling}}

```
![Image1](https://user-images.githubusercontent.com/9612136/177411393-8d114f38-dc50-40e5-ad1e-d271438e7cd2.png)

**Comment by Klap-in** [comment]
There are recent changes in image resizing. I guess some thing unexpected is happening there.
Could you please tell the height and width of the resized versions of the image?

**Comment by splitbrain** [comment]
please attach the original image and the resized result here

**Comment by Ashtagon** [comment]
Here's those three images. ex1 (388x1480px) is the image displayed above on the left, and is identical to the original source image. ex2 (101x388px) is the middle one above, and ex3 (40x154px) is the one on the right. This suggests that the image resizing is resizing to set a display height for the resized image, not the display width (as older versions of dokuwiki did).

![ex1](https://user-images.githubusercontent.com/9612136/177474224-d5ac491b-0c4d-4d41-a6d6-eba3d4c49751.png)
![ex2](https://user-images.githubusercontent.com/9612136/177474230-84b15ce6-6f78-4044-9c93-28a5733a58ec.png)
![ex3](https://user-images.githubusercontent.com/9612136/177474231-0369687a-bc62-4e92-b345-93a8f2a85576.png)

**Comment by splitbrain** [comment]
:man_facepalming: Okay, the error is here:

https://github.com/splitbrain/dokuwiki/blob/04485764ff6858101a807ba0bbf78f44bf5e0cd1/inc/media.php#L1707

When only the width is given it is now used as width by width bounding box instead of resizing to the given width. This is a problem on portrait images only. Gotta invest how to best fix this. Thank you for the report
