### ISSUE TITLE
Disable repeating table header and footer

### ISSUE THREAD

**Issue by c0da** [splitbrain/dokuwiki#3720]
Is there any way to disable "thead" in tables, or to force the first header to be "th" instead of "thead"? I have a fairly long table (several pages long) with several headers, and when I save it as a pdf with dw2pdf it repeats the first header (thead) of the table in all pages, and I would like to avoid that. Thanks in advance!

**Comment by splitbrain** [comment]
nope. there might be a way to disable header repetition in dw2pdf though
