### ISSUE TITLE
xml sitemap contains non-existant pages

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#3723]
See https://forum.dokuwiki.org/d/20332-google-appears-not-to-recognize-dokuwiki-style-sub-page-links/4 for background

The sitemap is build upon the fulltext page index, which may contain pages that do not exist (yet) because links to it exist. The sitemap builder should filter those items out.

**Comment by saggi-dw** [comment]
I'm not sure when that will happen. I can't track it here.
But shouldn't the check if the page exists be done in `Item::createFromID($id)` in [Mapper.php](https://github.com/splitbrain/dokuwiki/blob/9f48b7048bfe54113e7d2ea528e226b1e3e2ab1d/inc/Sitemap/Mapper.php#L62)? After all, the function returns a `false` if the file doesn't exist. Or am I wrong there?

**Comment by splitbrain** [comment]
Ah, forgot to close this. This turned out to be an issue with the publish plugin. Unpublished pages end up in the sitemap but display as non-existant to unauthorized users...
