### ISSUE TITLE
Undefined array key warnings

### ISSUE THREAD

**Issue by tuxmika** [splitbrain/dokuwiki#3724]
Hello

I recently upgraded to version 2022-07-31 "Igor" with DokuWiki Upgrade Plugin and now when I log in and go to pages or use the wrap plugin I get error messages :

Warning: Undefined array key "lang" in /htdocs/wiki.mickaelbonnard.fr/lib/plugins/wrap/helper.php on line 94

Warning: Undefined array key "id" in /htdocs/wiki.mickaelbonnard.fr/lib/plugins/wrap/helper.php on line 117

Warning: Undefined array key "width" in /htdocs/wiki.mickaelbonnard.fr/lib/plugins/wrap/helper.php on line 119

Warning: Undefined array key "dir" in /htdocs/wiki.mickaelbonnard.fr/lib/plugins/wrap/helper.php on line 128

Warning: Undefined array key "hid" in /htdocs/wiki.mickaelbonnard.fr/inc/html.php on line 136

Warning: Undefined array key "hid" in /htdocs/wiki.mickaelbonnard.fr/inc/html.php on line 136

**Comment by Klap-in** [comment]
The first four warnings are affecting the wrap plugin. Please report them there.

**Comment by myfirstnameispaul** [comment]
I am only seeing the following errors with PHP 8.0, including on articles not using `WRAP`:

    PHP Warning:  Undefined array key "hid" in ../dokuwiki/inc/html.php on line 114

This is run locally in Linux Mint using `php8.0 -S localhost:8008 index.php` and the warnings are printed in the command line, not within the wiki or even in the wiki logs.

**Comment by Klap-in** [comment]
Can you update the wrap plugin? Could you try if that helps?
