### ISSUE TITLE
admin.php is deprecated. It was called from require_once() in <xxx>/wiki/lib/plugins/admin.php:3 Do not require() files yourself. Autoloading should be used instead!

### ISSUE THREAD

**Issue by LMS235** [splitbrain/dokuwiki#3725]
After Upgrade to IGOR:

admin.php is deprecated. It was called from require_once() in <xxx>/wiki/lib/plugins/admin.php:3 Do not require() files yourself. Autoloading should be used instead!

But i think the "admin" plugin is built in

**Comment by Klap-in** [comment]
The reported call location in gh3 message is wrong, and therefore this message is confusing. See also #3717

**Comment by Klap-in** [comment]
Closed with the commits mentioned here: #3717
