### ISSUE TITLE
update to "Igor" broken on farm setup. log dir missing

### ISSUE THREAD

**Issue by candardo** [splitbrain/dokuwiki#3727]
I've just updated to Igor on a (.htaccess based) farm setup just as I did since Hrun. All went fine with the farmer but failed with animals.
![immagine](https://user-images.githubusercontent.com/6369278/182376814-030b2094-49ad-4248-aef6-e42a01059b47.png)

Apparently the new logging mechanism requires to create a log directory that was missing. Adding the directory fixes the problem.

**Comment by splitbrain** [comment]
Yep, the log dir needs to be created manually in animals.

**Comment by candardo** [comment]
It never happened before so I thought it was worth opening an issue. Maybe a line in the changelog or in the farms page could help.
Thanks!

**Comment by splitbrain** [comment]
it's a wiki ;-)
