### ISSUE TITLE
set_doku_pref does not store a plugin setting

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki#3743]
Maybe I looking wrong. But I do not succeed storing a setting for a plugin on its admin page.

In a call from html() on the admin page of the blogtng plugin, I added a call to store a setting:
`set_doku_pref('blogtng_comment_limit', 30);`

If I follow the set_doku_pref command, it does the right thing before the actual setCookie().
After page refresh the cookie is not update with the new setting. If I try to change another setting, e.g. at recent change page the only pages to only media files, this setting is stored as expected.

Ideas how to check this? Could it be that the session is already closed, or something like that?

**Comment by splitbrain** [comment]
cookies are set in http headers, so they need to be set before any headers are sent. for an admin plugin this would be the `handle()` method.

**Comment by Klap-in** [comment]
Yes, that works. Thanks for the guidance!
