### ISSUE TITLE
PHP8, snapshot version 52.2, Undefined array key warnings

### ISSUE THREAD

**Issue by JoBongHyeon** [splitbrain/dokuwiki#3745]
PHP8, snapshot version 52.2, Undefined array key warnings

I get error messages :

Warning: Undefined array key "step" in /..../lib/plugins/upgrade/admin.php on line 44

Warning: Undefined array key "dir_nest" in /..../lib/plugins/popularity/helper.php on line 274

Warning: Undefined array key "dir_count" in /..../lib/plugins/popularity/helper.php on line 275

Warning: Undefined array key "file_count" in /..../lib/plugins/popularity/helper.php on line 283

Warning: Undefined array key "file_size" in /..../lib/plugins/popularity/helper.php on line 284

Warning: Undefined array key "file_max" in /..../lib/plugins/popularity/helper.php on line 286

**Comment by splitbrain** [comment]
Warnings in popularity has been fixed in 0d48ec5cdf1a931858bcb1183b8a6f48d4543fea

Problems in the upgrade plugin should be reported there.
