### ISSUE TITLE
authad plugin, errors with PHP8.1

### ISSUE THREAD

**Issue by tqre-mc** [splitbrain/dokuwiki#3746]
In process of migrating dokuwiki to Ubuntu 22.04 LTS, which has PHP8.1 as default.

Plugin was downloaded with dokuwiki's internal configuration manager.

Login works, but the plugin gives following errors to web browser:

Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 318
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 321
Warning: Undefined array key "" in /dokuwiki/lib/plugins/authad/auth.php on line 329
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 650
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 318
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 321
Warning: Undefined array key "" in /dokuwiki/lib/plugins/authad/auth.php on line 329
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 318
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 321
Warning: Undefined array key "" in /dokuwiki/lib/plugins/authad/auth.php on line 329
Warning: Undefined array key "REMOTE_USER" in /dokuwiki/lib/plugins/authad/auth.php on line 135
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 650
Warning: Undefined array key "REMOTE_USER" in /dokuwiki/lib/plugins/authad/auth.php on line 135
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 650
Warning: Undefined array key "REMOTE_USER" in /dokuwiki/lib/plugins/authad/auth.php on line 135
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 650
Warning: Undefined array key "REMOTE_USER" in /dokuwiki/lib/plugins/authad/auth.php on line 135
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 650
Warning: Undefined array key "REMOTE_USER" in /dokuwiki/lib/plugins/authad/auth.php on line 135
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 650
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 318
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 321
Warning: Undefined array key "" in /dokuwiki/lib/plugins/authad/auth.php on line 329
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 318
Warning: Undefined array key 1 in /dokuwiki/lib/plugins/authad/auth.php on line 321
Warning: Undefined array key "" in /dokuwiki/lib/plugins/authad/auth.php on line 329

**Comment by Klap-in** [comment]
The  'Undefined array key 1' on line 318 came from internally of the explode(). The string `'\\'` is not in the given name.
Workaround founded when searching a bit was adding an extra `\\` to the end of the username, before providing it to the explode(), such that it has always enough entries in the array. How to recognize were the empty array positions are from and cleaning them up and therefore creating of course extra steps. Therefore, for me the logic of this warning is very unclear.

**Comment by splitbrain** [comment]
@Klap-in the problem is the list() - the warning is triggered when less items than expected are provided. https://stackoverflow.com/questions/2357986/list-and-explode has some ideas on how to fix this. I will use the array_pad mechanism to fix this.
