### ISSUE TITLE
PHP message: PHP Warning:  Undefined array key 1 in /dokuwiki-test/inc/auth.php on line 78

### ISSUE THREAD

**Issue by fiwswe** [splitbrain/dokuwiki#3750]
My setup:
OpenBSD 7.1 release, all patches applied, amd64, [`httpd(8)`](https://man.openbsd.org/OpenBSD-7.1/amd64/httpd.8), PHP-FPM 8.0.22, HTTP Basic authentication configured, DokuWiki 2022-07-31 "Igor".
The Wiki is a copy of an existing Wiki based on Hogfather upgraded to Igor according to the instructions (https://www.dokuwiki.org/install:upgrade).

According to `php_info()` the array element `$_SERVER['HTTP_AUTHORIZATION']` exists and has the value `null`.

This leads to the above mentioned warning in the logs.

The relevant part of the `/etc/httpd.conf` looks like this:
```
server "wiki-test.example.com" {
	listen on $my_ipv6 tls port 443

	tls {
		certificate "/etc/ssl/acme/fullchain.pem"
		key "/etc/ssl/acme/private/privkey.pem"
	}

	log style combined

	authenticate "Private area" with "/conf/htpasswd-admin"

	root "/dokuwiki-test"
	directory index doku.php

	connection max request body 2097152	# Default is 2M for upload_max_filesize and 8M for post_max_size.

	location "*.php" {
		fastcgi socket "/run/php80-fpm.sock"
	}

	location "/*.inc" { block }
	location "/*.ht*" { block }
	location "/data/*" { block }
	location "/conf/*" { block }
	location "/bin/*" { block }
	location "/inc/*" { block }
	location "/vendor/*" { block }
}

```

It could be argued that `$_SERVER['HTTP_AUTHORIZATION']` should contain a more meaningful value. But OTOH other hosting environments do not have this array element at all (e.g. Apache httpd when using PHP_FPM).

So the check in line 76 of `/inc/auth.php` might be changed from:
`if(isset($_SERVER['HTTP_AUTHORIZATION'])) {`
to
`if(array_key_exists('HTTP_AUTHORIZATION', $_SERVER) && !empty($_SERVER['HTTP_AUTHORIZATION'])) {`
This avoids the PHP Warning in my testing.

Note: AFAICT there is no way for PHP to extract the HTTP Basic user name and password in this setup. [httpd(8)](https://man.openbsd.org/OpenBSD-7.1/amd64/httpd.8) handles it all by itself and does not pass the data to the fastcgi script. In my situation this would not matter anyhow because the HTTP Basic credentials are different from the credentials used within DokuWiki. This adds an extra layer of access protection to the private WIKI.

Thanks!
fiwswe

**Comment by fiwswe** [comment]
BTW: I only checked that the WIKI was functional and that the PHP warning went away.
TODO: Verify that the logic is what it should be, but maybe someone more familiar with the code should do that?

While we're at it should not lines 73:74 in `./inc/auth.php` be changed from:
```
    if(isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION']))
        $_SERVER['HTTP_AUTHORIZATION'] = $_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
```
to
```
    if($INPUT->server->str('REDIRECT_HTTP_AUTHORIZATION'))
        $INPUT->server->set('HTTP_AUTHORIZATION', $INPUT->server->str('REDIRECT_HTTP_AUTHORIZATION'))
```
as well?

Maybe a search over the code base for `$_SERVER`, `$_GET` and `$_POST` would reveal more potential places, where similar changes should be made?

**Comment by splitbrain** [comment]
I did not change the assignments to use the set method, because this wouldn't work with the list() construct, two lines down. For assignments it doesn't really make a difference so I opted to keep the lines consistent, reading from $INPUT but writing to $_SERVER. If anyone feels strongly about it, we can change it.

**Comment by fiwswe** [comment]
Kind of silly to have a class for input checking and then not using it because you like a questionable(*) language construct such as `list()` IMHO. Either fix the Input class to support `list()` or assign the elements separately. The later is no big deal, the former might be difficult and probably not worth it.

*) `list()` has some unspecified/undocumented behavior when it comes to source arrays that don't contain the requested element(s). Also its main purpose is strictly speaking a side effect.

**Comment by splitbrain** [comment]
* INPUT is mainly for input checking, input setting is possible but not strictly needed for anything
* I got to pick my battles, if I start to do this right :tm: I might end up refactoring that whole ugly method and/or file ;-) 
* pull request welcome

**Comment by nerun** [comment]
I had a warning for `PHP Warning: Undefined array key 1 in .../inc/auth.php on line 77`.

I use `Igor 2022-07-31a` release on `PHP 8.1`.

PR #3755 fixed it to me.

**Comment by Dtrieb** [comment]
> I had a warning for `PHP Warning: Undefined array key 1 in .../inc/auth.php on line 77`.
> 
> I use `Igor 2022-07-31a` release on `PHP 8.1`.
> 
> PR #3755 fixed it to me.

Fixed my problem on `PHP 8.x` too.
