### ISSUE TITLE
After update from "Greebo" to "Igor" plantumlparser plugin renders GraphViz code as miniature

### ISSUE THREAD

**Issue by t-aus-o** [splitbrain/dokuwiki#3752]
Recently I did an update from "Greebo" to "Igor".
From then the plantumlparser plugin renders GraphViz code as miniature (see link)

https://www.elektrowiki.de/wiki/playground:playground

Surprisingly plain PlantUML code renders fine.
Did not change anything else beside updating Dokuwiki.
Reinstalling the plugin did not help.

Any help or hint?

**Comment by splitbrain** [comment]
Please report the bug at the plugin's bug tracker. Probably related to #3690
