### ISSUE TITLE
php8 error , Is it correct to edit like this?

### ISSUE THREAD

**Issue by JoBongHyeon** [splitbrain/dokuwiki#3753]
Warning: Undefined array key "REMOTE_USER" in /home1/jbh2480/public_html/jbh2480ga/lib/plugins/captcha/action.php on line 197

Is it correct to edit like this?

  if (!$this->getConf('forusers') &&$_SERVER['REMOTE_USER'] ) {
->
  if (!$this->getConf('forusers') &&($_SERVER['REMOTE_USER'] ?? '')) {

**Comment by fiwswe** [comment]
External inputs such as $_SERVER elements should always be checked very conservatively. Assume that they might not exist or that their values are not what you expect.

In this case I would use:
```
if (!$this->getConf('forusers') && array_key_exists('REMOTE_USER', $_SERVER) && !empty($_SERVER['REMOTE_USER'])) {
```

HTH
fiwswe

**Comment by fiwswe** [comment]
Oh and to answer your actual question, no that would not work because PHP would still try to access a non-existing array element and issue the warning.

Testing with `array_key_exists` in combination with the `&&` operator avoids this.

fiwswe

**Comment by Klap-in** [comment]
This issue should be solved by the Captcha plugin. Could you report it in the issue tracker of this plugin?

It is recommended to use the INPUT class DokuWiki is using for these variables: `$INPUT->server->str('REMOTE_USER') `,
See also https://www.dokuwiki.org/devel:request_vars

**Comment by JoBongHyeon** [comment]
> $_SERVER 요소와 같은 외부 입력은 항상 매우 보수적으로 확인해야 합니다. 그것들이 존재하지 않거나 그들의 값이 당신이 기대하는 것과 다르다고 가정하십시오.
> 
> 이 경우 다음을 사용합니다.
> 
> ```
> if (!$this->getConf('forusers') && array_key_exists('REMOTE_USER', $_SERVER) && !empty($_SERVER['REMOTE_USER'])) {
> ```
> 
> HTH fiwwe

**Comment by JoBongHyeon** [comment]
Thank you for your answer
