### ISSUE TITLE
Cross-Site-Scripting vulnerability in diff viewer

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#3761]
Reported in https://huntr.dev/bounties/d72a979b-57db-4201-9500-66b49a5c1345/

The difftype parameter is not properly cleaned or escaped.

It seems at least Hogfather and Igor are affected, older versions might be, too.

**Comment by splitbrain** [comment]
@bug I fixed this in old-stable and stable. For the latter the tar was auto build and deployed, but for old-stable this isn't available yet. Can you do it and also update the update notification info?

**Comment by bug** [comment]
I just did old-stable (tarball upload and piggy update).

Strangely I don't see a cherry-picked commit on the stable branch, neither to I see a new tag for the hotfix release on the stable branch.

**Comment by splitbrain** [comment]
> Strangely I don't see a cherry-picked commit on the stable branch

Oh interesting. I had only done a `git push --tags` assuming it would push the commits and the tags, but it only pushed the tag. I did a `git push` and the commits are now also in the `stable` branch.

**Comment by bug** [comment]
Hotfix releases are both out.
