### ISSUE TITLE
missing buttons on the right side if an error occors

### ISSUE THREAD

**Issue by arlt** [splitbrain/dokuwiki#3763]
If an error occurs (e.g. using a plugin), the error is displayed but the edit-button and all the other buttons on the right side are missing. So one can't remove the problem from the wikipage.

Example to reproduce the problem and all additional version information - see: https://github.com/dokufreaks/plugin-pagelist/issues/132

**Comment by splitbrain** [comment]
The linked error is a fatal one. There is no recovery from it, so all rendering after the error is halted. It's accidental that only the buttons are affected in your case.

**Comment by arlt** [comment]
Wouldn't it be possible to render the buttons before the page content?

**Comment by Michaelsy** [comment]
> So one can't remove the problem from the wikipage.

You can and must edit the wiki page directly on the server by editing the *,txt file where the wiki page is stored.

\- Michael Sy.
