### ISSUE TITLE
Authad plugin - make it updateable with extension manager

### ISSUE THREAD

**Issue by tqre-mc** [splitbrain/dokuwiki#3767]
Related to #3746 - the plugin works now. Thanks :)

Not sure how extension manager finds the new versions, but I had to update the plugin manually. Maybe the 'date' entry in plugin.info.txt should be updated?

**Comment by mprins** [comment]
it's a built-in plugin and as such there's no downloadable archive so it cannot be updated using the plugin manager
the code lives here: https://github.com/splitbrain/dokuwiki/tree/master/lib/plugins/authad/

**Comment by tqre-mc** [comment]
Allright, thanks for the info. Got the new code in place and working already :)
