### ISSUE TITLE
New SVG smileys are too big, showed up in full size at page

### ISSUE THREAD

**Issue by j0hu** [splitbrain/dokuwiki#3772]
Hello, I did a update from Hogfather to Release 2022-07-31a "Igor" successfully.

But on every page where I putted a smiley, now the smiley showed up in full size at page?!

Went something wrong with my update or configuration due the update or have I found a bug?

To be sure I also clean up my dokuwiki cache:
`touch wiki/doku.php`

And deleted all unnessesary files:
`grep -Ev '^($|#)' wiki/data/deleted.files | xargs -n 1 rm -vf`

But the smileys still show up in full size. All other stuff (PlugIns, Templates) work as aspected.

Any ideas?

**Comment by mprins** [comment]
Perhaps your template must be fixed

**Comment by j0hu** [comment]
hm, I use the default DokuWiki Template [by Anika Henke] without any changes

**Comment by splitbrain** [comment]
- what's too big? can you post a screenshot?
- the wiki cache should be refreshed by touching conf/local.php (not sure if we check doku.php)
- the smiley sizes are set in the core styles and should be independent of the template
- how dd you upgrade? maybe some files failed to be transferred correctly?

**Comment by j0hu** [comment]
here is an example of the too large sized smiley after the update...

![grafik](https://user-images.githubusercontent.com/43872769/190578170-c856a7fb-4a0b-4ed5-9ff6-1daa7bc23e83.png)

thats the page raw code...

![grafik](https://user-images.githubusercontent.com/43872769/190578246-61951795-2ad2-4520-aac0-ce06d2d53cca.png)

```
===== Xiaomi Aqara Magic Cube =====

Volle Integration des Xiaomi Aqara Magic Cube in der Phoscon App :-D 
```

I did the update manually like coping all new files (out of the installation *igor*.gz archive file) over the old ones (my dokuwiki live system).

**Comment by j0hu** [comment]
hey Andreas, after your hint I try also

`touch dokuwiki/conf/local.php`

... and now all smileys have the normal size again.

I love such easy commands to solve a problem :-)

Thanks, Jochen

**Comment by fiwswe** [comment]
I had the exact same problem.

Switching from [sprintDoc Template](https://www.dokuwiki.org/template:sprintdoc) to default DokuWiki Template and back fixed this for me.

So my guess was some sort of stale cache issue. Note: I did **not** try appending `&purge=true` to the URL so I don't know if that would have worked as well.

See also: [Caching](https://www.dokuwiki.org/devel:caching)

fiwswe
