### ISSUE TITLE
Pages with . in the title have a buggy revisions page

### ISSUE THREAD

**Issue by Zichqec** [splitbrain/dokuwiki#3773]
Pages that have `.` characters in the title seem to have a buggy revisions page. All of the revisions are listed, however, only the top one is a clickable link. And if you click the top link, it takes you to the media page.
![image](https://user-images.githubusercontent.com/36972872/190976003-60e24f70-cff6-4c7b-9ebc-d963ab745aa1.png)

I can still do a comparison between revisions, and if I actually go to the attic folder, I can see that all of the files are there and are functional. They simply are not linked properly on my wiki.

I'm using Release 2022-07-31a "Igor", with the Vector template. I did not notice if this issue was happening before upgrading to Igor a few weeks ago, but it very well might have been.

My compression settings are set to gzip, which matches the files in my attic. Additionally, as you can see in the screenshot, I made a new page to test this with and it exhibited the same behavior.

**Comment by Klap-in** [comment]
Please see #3613, it is solved in the development release.
