### ISSUE TITLE
Undefined array key "SERVER_PORT", "HTTP_HOST" and "SERVER_PORT"

### ISSUE THREAD

**Issue by LMS235** [splitbrain/dokuwiki#3785]
Error with PHP 8.1.2 (while Indexing)

...
PHP Warning:  Undefined array key "SERVER_PORT" in .../inc/Cache/CacheParser.php on line 30
PHP Warning:  Undefined array key "HTTP_HOST" in .../inc/Cache/CacheParser.php on line 30
PHP Warning:  Undefined array key "SERVER_PORT" in .../inc/Cache/CacheParser.php on line 30
...

**Comment by fiwswe** [comment]
Normally I'd say use `$INPUT->server->str('HTTP_HOST')`, etc. would solve the problem. But I wonder why these array keys where not defined in the first place? Are you running the indexer from the command line, i.e. `$ php -f bin/indexer.php`?

If so, it's clear why these keys are not present. But to me it is unclear why they are being used in the first place and what the consequences of substituting empty strings for the value would be? What does the cache care about the hostname and port, given that the same DW instance might be reachable using different hostnames and ports concurrently?

**Comment by LMS235** [comment]
yes, I run the indexer via Command Line, since I wanted to recreate this https://github.com/splitbrain/dokuwiki/issues/3783 error here. 

Dokuwiki runs on a UBUNTU 22.04.1 LTS with NGINX 1.18 and PHP 8.1.2. Only one hostname and IP address. Version is 2022-07-31a "Igor"

**Comment by fiwswe** [comment]
The OS is probably irrelevant here. If you are using the command line then the web server (NGINX) is also irrelevant. And please note that the PHP version used by PHP-FPM might not be the same as your command line PHP. (I have setups where multiple PHP versions are installed and used for different purposes.) If in doubt: `$ php -v`. And in DW you could add something like this on a page (if you allow inline PHP in your settings -> [phpok](https://www.dokuwiki.org/config:phpok)) to see which version PHP-FPM is using:
`<php>echo '<p>PHP version: '.phpversion().'</p>'.NL;</php>`

But all of that is mostly moot. The main point is that $_SERVER will not be fully populated when running from the command line. See: `$ php -r 'print_r($_SERVER);'`

Thus having a DW command meant for being run from the command line (`bin/indexer.php`) have dependencies on `$_SERVER` keys not present in that environment is a bug.

**Comment by LMS235** [comment]
PHP is 8.1.2 (PHP 8.1.2 (cli) (built: Aug  8 2022 07:28:23) (NTS)) - only this Version is installed ;)

Ok, than only the dependencies are a problem.

**Comment by fiwswe** [comment]
I can't seem to figure out the reason for appending `$_SERVER['HTTP_HOST'].$_SERVER['SERVER_PORT']` to the filename used to generate the md5 hash that is used for the actual cache file name (the cache key). `md5($file.$_SERVER['HTTP_HOST'].$_SERVER['SERVER_PORT'])` is used as the key to the cache. In a plain vanilla setup the `$_SERVER['HTTP_HOST'].$_SERVER['SERVER_PORT']` part should be a constant value that never changes, e.g. `'wiki.example.com443'`. So it does not help to differentiate conflicting file names. In a more complex setup, where the same DW instance can be additionally accessed using a different host/port combination this string will vary depending on the access method, e.g. `'wiki.example.org443'`. But should the cache really be different? The only reason for having different caches based on access method would be that the pages are actually generated differently. But that could only happen when custom PHP code is used on the page in which case the author could easily use `~~NOCACHE~~`.

From what I can see on GitHub this is basically very old code, modernized/refactored a few times, but without changing this strange name generation method.

Also when rebuilding the index from the command line, the string will be empty, i.e. `''` (and newer versions of PHP will generate the aforementioned warnings). What use are the cache files in that case when an access through the web server will use different keys?

Am I missing something here? If not I propose to remove the `$_SERVER['HTTP_HOST'].$_SERVER['SERVER_PORT']` suffix to the cache key as it serves no discernible purpose and causes PHP warnings.

**Comment by Klap-in** [comment]
I expect that this issue is solved by #3832. Or needs some of the other questions more attention?

**Comment by splitbrain** [comment]
> In a plain vanilla setup the $_SERVER['HTTP_HOST'].$_SERVER['SERVER_PORT'] part should be a constant value that never changes

Yeah. But in non-vanilla setups the same wiki can be available under different hostnames. Eg. an internal and an external one. Making the cache dependent on host:port does not make a difference for vanilla setups, but prevents internal and external to be mixed in the cache.
