### ISSUE TITLE
Igor shows no links to old revisions anymore for pages with '.' in their name

### ISSUE THREAD

**Issue by trollkotze** [splitbrain/dokuwiki#3787]
After upgrading to Igor, on many pages old revisions are not shown as links anymore in the "Old revisions" view.

Before Igor:
https://test.sangham.net/en/tipitaka/sut/an/an10/an10.092.than?do=revisions&first=0
After Igor:
https://sangham.net/en/tipitaka/sut/an/an10/an10.092.than?do=revisions&first=0

These are using the same data directory, so the same pages, attic, etc.
Version before Igor shows links to old revisions which exist in the attic. Version after Igor does not.

However, if I copy the URL from a link to an old revision from the old Dokuwiki (before Igor) and simply adjust the URL to the new Dokuwiki (after Igor), the old revision is shown under that URL even by Igor. Both of these work:
Before Igor:
https://test.sangham.net/en/tipitaka/sut/an/an10/an10.092.than?rev=1648124464
After Igor:
https://sangham.net/en/tipitaka/sut/an/an10/an10.092.than?rev=1648124464

Not all pages are affected, however. E.g. the index page shows link to old revisions: https://sangham.net/index?do=revisions
It seems all pages with a '.' in their name have this problem.

**Comment by trollkotze** [comment]
And on the pages where this bug occurs, the only still existing link in the revisions overview (the current version) for some reason links to the media manager as if it was an image file.

**Comment by Klap-in** [comment]
This issue is addressed in the development version.
https://github.com/splitbrain/dokuwiki/issues/3613

**Comment by trollkotze** [comment]
Thank you!
Applying all changes up to current master fixed the issue.
