### ISSUE TITLE
Can't translate logviewer on translate.dokuwiki.org

### ISSUE THREAD

**Issue by schplurtz** [splitbrain/dokuwiki#3791]
Hi,

The logviewer plugin strings can't be found on https://translate.dokuwiki.org/translate/dokuwiki. For example, search "View Logs", which is the title in [lib/plugins/logviewer/lang/en/intro.txt](https://github.com/splitbrain/dokuwiki/blob/7f7e5699c910ba910964357371369bb8d5cc4ef0/lib/plugins/logviewer/lang/en/intro.txt#L1), nothing appears.

**Comment by Klap-in** [comment]
I wonder whether the translation tool is updating properly. I think it is not.
E.g. https://github.com/dokuwiki-translate/dokuwiki

**Comment by splitbrain** [comment]
This had two problems. The first was a timeout communicating with github because the git:// protocol was used instead of https://. The other was that the logviewer plugin had not been configured as source of language strings for the core. Should both be fixed now.

**Comment by schplurtz** [comment]
Thank you. everything is fixed now. New untranslated strings just appeared.
