### ISSUE TITLE
Spam Assassin says I have MISSPACED HEADERS

### ISSUE THREAD

**Issue by weissmar48** [splitbrain/dokuwiki#3802]
Here is the PHP code that builds my headers then sends the email.  What's wrong with these?

$work_From = "Post474Commander@jwv-mi.org\r\n\r\n";
$mail_From = "MIME-Version: 1.0\r\nContent-Type:text/html; charset=UTF-8\r\nFrom:" . $work_From;
mail($donoreml, $mail_Subject, $ThankYouText, $mail_From);

**Comment by mprins** [comment]
Is this dokuwiki code? Or you just looking for general php support?

**Comment by weissmar48** [comment]
Mark,

It is homegrown .php code. It's a Listener put together to handle Paypal
donations. The email being sent is a "Thank You for your donation".

Mark Weiss

**Comment by mprins** [comment]
> It is homegrown .php code. I

I don't think this is the place for your problem
