### ISSUE TITLE
Datepicker is in Cyrillic after "Igor" upgrade

### ISSUE THREAD

**Issue by m4nu75** [splitbrain/dokuwiki#3803]
Hi all , i don't know if is an issue of the new version but after the upgrade with DokuWiki Upgrade plugin, my datepicker pop up on bureaucracy is in cyrillic. I don't understand how to change it. 
Any idea ?

![image](https://user-images.githubusercontent.com/61206552/195806703-cc638060-af09-4815-8e3d-f5f6b674fcef.png)

**Comment by fiwswe** [comment]
This sounds like an issue with the bureaucracy plugin? Might be better to open an issue [there](https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/issues).

Could also be an issue with caching? I needed to switch back to the default template once to get some things fixed after upgrading to Igor. Appending `&purge=true` to the URL might also help.

As a test I installed the plugin in a DokuWiki 2022-07-31a "Igor" test wiki and built a simple testing page containing a date field. The localization was English (en) as expected as that was the setting my wiki uses.

What localization where you expecting?
Does DW have that localization (check your `inc/lang/` directory)?
Does the bureaucracy plugin have that localization (`lib/plugins/bureaucracy/lang/`)?

What is your [lang](https://www.dokuwiki.org/config:lang) configuration setting?

**Comment by m4nu75** [comment]
Thanks for the reply, my localization is in english, i have that localization both in `inc/lang/` and in `lib/plugins/bureaucracy/lang/`, but i don't have the `jquery.ui.datepicker.js` in the `inc/lang/` directory. 
I've also searched in the `inc/lang/` and the output of `find ./ -name  '* datepicker *' is only : 
```
./cy/jquery.ui.datepicker.js
./pt-br/jquery.ui.datepicker.js
./zh/jquery.ui.datepicker.js
./zh-tw/jquery.ui.datepicker.js
./de-informal/jquery.ui.datepicker.js
./af/jquery.ui.datepicker.js
``` 
but the files are all empty .....

**Comment by fiwswe** [comment]
> output of `find ./ -name '* datepicker *' is only :

That should probably be: `find . -name '*datepicker*' -print`?

Ok, my wiki has more languages that include `jquery.ui.datepicker.js` in `./inc/lang/` than yours. But that should not matter. Like apparently your setup, there is no ìnc/lang/en/jquery.ui.datepicker.js` though. The English strings seem to come from `lib/scripts/jquery/jquery-ui.min.js`.

Can you check whether that file is present and contains the English strings?

**Comment by fiwswe** [comment]
Well that sounds like you messed up your installation.

If I where you, I'd start over with a fresh install of DokuWiki from https://download.dokuwiki.org. If the problem persists then raise the issue again.

**Comment by m4nu75** [comment]
I'm trying to update from command line how suggested [here](https://www.dokuwiki.org/install:upgrade).

**Comment by m4nu75** [comment]
Ok i find the plug-in responsible of the issue, is not bureaucracy and is not dokuwiki upgrade ... but is the [https://www.dokuwiki.org/plugin:davcal](https://www.dokuwiki.org/plugin:davcal) . Thanks @fiwswe for the support i close
