### ISSUE TITLE
It would seem that there's an issue with the dokuwiki.org zone?

### ISSUE THREAD

**Issue by itfors** [splitbrain/dokuwiki#3821]
I've been having issues (in Europe) when attempting to check various pages at dokuwiki.org as DNS lookups keep failing.

However, since (amongst others) mxtoolbox.com seems to agree with me I'm inclined to think that this isn't a local issue:
![image](https://user-images.githubusercontent.com/82437124/198270143-4d998c3c-6938-405f-aad1-2e452ad69d15.png)

**Comment by splitbrain** [comment]
Yeah. See https://twitter.com/dokuwiki/status/1585588826407374849

**Comment by itfors** [comment]
Ahh! - yeah, that would explain it :-(

You have my commiserations.

**Comment by splitbrain** [comment]
seems to work again
