### ISSUE TITLE
Undefined array keys 3/4 in authplain/auth.php

### ISSUE THREAD

**Issue by demiankatz** [splitbrain/dokuwiki#3833]
I noticed that since upgrading to Igor, my PHP error logs were filling with warnings like:

```
[11-Nov-2022 11:33:59 UTC] PHP Warning:  Undefined array key 3 in .../lib/plugins/authplain/auth.php on line 424
[11-Nov-2022 11:33:59 UTC] PHP Warning:  Undefined array key 4 in .../lib/plugins/authplain/auth.php on line 420
```

The root cause was some spammy-looking user accounts which contained pound signs in one of the user-entered fields. These were getting misinterpreted as comments and causing invalid parsing of the users.

I wrote this quick-and-dirty script to filter the bad users out of my user file:

```
$handle = fopen("users.auth.php", 'r');
$count = 0;
while ($rawLine = fgets($handle)) {
    $count++;
    $line = preg_replace('/#.*$/', '', $rawLine);
    $parts = explode(":", $line);
    if (count($parts) == 5) {
        echo $rawLine;
    }
}

fclose($handle);
```

...and that solved the problem for me.

However, I'm not sure what the best long-term solution for Dokuwiki should be. Does this indicate a problem with the comment parsing? Is there a user input validation problem? Is this the result of some bug from the distant past, and it's only likely to affect users like me who have been running Dokuwiki for many years?

In any case, just sharing my experience in case it's useful for others. If somebody has an opinion about a clear path forward, I might be able to contribute a PR to help.

**Comment by Klap-in** [comment]
What are the actual characters in the fields? You mention pound sign, but if interpret your regexp correctly, it shows only a `#`? In which field where these characters?

**Comment by demiankatz** [comment]
Thanks, @splitbrain!
