### ISSUE TITLE
502 Bad Gateway nginx/1.22.1

### ISSUE THREAD

**Issue by rardcode** [splitbrain/dokuwiki#3840]
Hi to all.
Dokuwiki version: version-2022-07-31a

After restart docker, first time i visit dokuwiki appear error:

**502 Bad Gateway
nginx/1.20.2**

I press F5 and start page load correctly.

There are this error in nginx error log:
`2023/02/05 20:56:34 [error] 313#313: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins
2023/02/05 20:56:34 [error] 313#313: *1 upstream sent too big header while reading response header from upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wiki.localdomain:8180"`

**Comment by rardcode** [comment]
i close this issue, posted in docker-dokuwiki:
https://github.com/linuxserver/docker-dokuwiki/issues/58

**Comment by fiwswe** [comment]
I can't follow your reasoning for moving the issue to the docker-dokuwiki repo but the PHP warnings seem to come from the [Wiki-Style Script](https://www.dokuwiki.org/plugin:wikiformatstyling) plugin. So raising the issue [there](https://github.com/hokkaidoperson/DokuWiki-WikiFormatStyling-Plugin) may be more productive.

> `2023/02/05 20:56:34 [error] 313#313: *1 upstream sent too big header while reading response header from upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wiki.localdomain:8180"`

I think this might be a followup issue caused by the previous PHP warnings. Given that the last PHP warning was truncated I suspect that the sheer size of the warning messages was too big for your proxy/FastCGI setup.

HTH
fiwswe

**Comment by rardcode** [comment]
> I can't follow your reasoning for moving the issue to the docker-dokuwiki repo but the PHP warnings seem to come from the [Wiki-Style Script](https://www.dokuwiki.org/plugin:wikiformatstyling) plugin. So raising the issue [there](https://github.com/hokkaidoperson/DokuWiki-WikiFormatStyling-Plugin) may be more productive.
> 
> > `2023/02/05 20:56:34 [error] 313#313: *1 upstream sent too big header while reading response header from upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wiki.localdomain:8180"`
> 
> I think this might be a followup issue caused by the previous PHP warnings. Given that the last PHP warning was truncated I suspect that the sheer size of the warning messages was too big for your proxy/FastCGI setup.
> 
> HTH fiwswe

I have reopen issue
i don't have a proxy, i think is internal in dokuwiki docker
my last error:
`2023/02/06 07:26:38 [error] 312#312: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins
2023/02/06 07:26:38 [error] 312#312: *1 upstream sent too big header while reading response header from upstream, client: 172.21.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wiki.localdomain:8180"`

**Comment by fiwswe** [comment]
Like I wrote previously, the PHP warnings come from the [Wiki-Style Script](https://www.dokuwiki.org/plugin:wikiformatstyling) plugin. That is a separate project from DokuWiki so raising the issue here for DokuWiki makes no sense and will not lead to a fix.

You are using FastCGI according to the cited messages. It could be argued that this is somewhat similar to a proxy server as it seems to communicate via a network connection, not a UNIX socket in your setup. But like I wrote, the related error is likely to be a secondary effect. I'd fix the root cause with the plugin first.

**Comment by rardcode** [comment]
> Like I wrote previously, the PHP warnings come from the [Wiki-Style Script](https://www.dokuwiki.org/plugin:wikiformatstyling) plugin. That is a separate project from DokuWiki so raising the issue here for DokuWiki makes no sense and will not lead to a fix.
> 
> You are using FastCGI according to the cited messages. It could be argued that this is somewhat similar to a proxy server as it seems to communicate via a network connection, not a UNIX socket in your setup. But like I wrote, the related error is likely to be a secondary effect. I'd fix the root cause with the plugin first.

Thanks fiwswe!
Disabling **Wiki-Style Script** solved problem!
Close this issue and open in https://github.com/hokkaidoperson/DokuWiki-WikiFormatStyling-Plugin/issues/3
