### ISSUE TITLE
Typo in x-auto-response-suppress header field value

### ISSUE THREAD

**Issue by rswindell** [splitbrain/dokuwiki#3842]
https://github.com/splitbrain/dokuwiki/blob/67e0898e5c30672b0af85498d39eca2794c96759/inc/Mailer.class.php#L67

Pretty sure that's supposed to be "OFF" not "OOF".

**Comment by splitbrain** [comment]
nope.

**Comment by Michaelsy** [comment]
@rswindell  see: [To generate an X-Auto-Response-Suppress...](https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcmail/ced68690-498a-4567-9d14-5c01f974d8b1?redirectedfrom=MSDN)

\- Michael Sy.

**Comment by rswindell** [comment]
Cool, thanks. My bad.
