### ISSUE TITLE
"File not found." from root, but works with "/start"?

### ISSUE THREAD

**Issue by Espionage724** [splitbrain/dokuwiki#3850]
- Instance: https://wiki.realmofespionage.xyz
- Instance with /start: https://wiki.realmofespionage.xyz/start
- Config: https://wiki.realmofespionage.xyz/servers/nginx/dokuwiki

nginx reports:

```
2022/12/15 15:53:33 [error] 4526#4526: *7 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.1.1, server: wiki.realmofespionage.xyz, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/wiki.sock:", host: "wiki.realmofespionage.xyz"
```

I believe it's likely something simple, but I haven't ran into this before. Does anyone have any suggestions?

**Comment by splitbrain** [comment]
Sorry, usage questions are better suited for the [forum](https://forum.dokuwiki.org). The issue tracker is reserved for bugs and feature requests.
