### ISSUE TITLE
Code block has links inserted?

### ISSUE THREAD

**Issue by suedunham** [splitbrain/dokuwiki#3854]
I've noticed just now that my `<code latex>` blocks have links inserted into them in the commands, going to the golatex.de/wiki page for that command. This seems odd. My German is pretty poor, as it happens.

Is this as it should be? Pasting something like this into a page should illustrate it.

Igor, Windows, Chrome.

```
<code latex>
\documentclass[12pt]{article}

\usepackage[option1, option2]{package}

\begin{document}

% Here is a comment. Commands in tex are called by backslash: \command 
\section{Section head}
\subsection{Subsection head}

This is text, and the following is in-line mathematics:
$\mathrm{e}^{-\pi\matrhm{i}} = -1$.
A display-style equation is shown below:

\begin{equation}
  E = mc^2
\end{equation}

\end{document}
</code>
```

**Comment by fiwswe** [comment]
DW uses [GeSHi](https://github.com/GeSHi/geshi-1.0) for syntax highlighting. So https://github.com/splitbrain/dokuwiki/blob/master/vendor/geshi/geshi/src/geshi/latex.php#L134 shows where the base URLs for LaTeX keywords come from.

You could possibly patch that line to something more to your liking. I do not know if GeSHi has a mechanism to override these URLs that does not involve patching the source code? The [documentation](http://qbnz.com/highlighter/geshi-doc.html#language-file-urls) does not seem to offer such a mechanism. But I am neither a GeSHi nor a LaTeX expert.

Or if you know about a good and free Englisch HTML resource for LaTeX documentation you could submit a patch to the [GeSHi](https://github.com/GeSHi/geshi-1.0) project. That would eventually find its way back into DokuWiki if accepted. The official [LaTeX website](https://www.latex-project.org/help/documentation/) does not seem to offer HTML documentation. I only saw PDFs which don't lend themselves to the deep links produced by GeSHi. But as mentioned, I'm not a LaTeX expert and only did a quick search.

fiwswe

**Comment by fiwswe** [comment]
You could also disable the links by adding `enable_keyword_links="false" ` to the `<code latex>`  statement like this:
`<code latex [enable_keyword_links="false"]>`

See: https://www.dokuwiki.org/syntax_highlighting

**Comment by suedunham** [comment]
Ah, gotcha. I did not know that this was expected behavior and that there was an option to turn it off. That should do. Thanks.
