### ISSUE TITLE
Asterisks in lists break pages

### ISSUE THREAD

**Issue by rebeka-catalina** [splitbrain/dokuwiki#3856]
The usage of asterisk in lists make dokuwiki render the page in a wrong way.

In an article I tried to describe the order of priority of config files which is

```
/etc/<software>/<software>.conf
/etc/<software>/<function.d>/*.conf
/etc/<software>/<software>.local
/etc/<software>/<function.d>/*.local
```

I used an ordered list for this and after saving the file everything after the list until the next heading disappeared completely and the the headline got merged directly to the end of the last list item's content.

The following things don't matter:

- How many list items contain an asterisk
- What exact content is after the list
- If it's an ordered list or an unordered list

My workaround is to enclose each asterisk with **nowiki**:

```
  * /etc/<software>/<function.d>/<nowiki>*</nowiki>.conf
  * /etc/<software>/<function.d>/%%*%%.local
```

**Comment by fiwswe** [comment]
I tried this on DW 2022-07-31a "Igor", PHP 8.0.24.

No apparent problem reproducable.

Here is the source of the test page I was using:
```
====== Issue #3856 ======

[[https://github.com/splitbrain/dokuwiki/issues/3856|DokuWiki Issue #3856]]

  - /etc/<software>/<software>.conf
  - /etc/<software>/<function.d>/*.conf
  - /etc/<software>/<software>.local
  - /etc/<software>/<function.d>/*.local

===== Test =====

Something
```

Maybe something else is going on, possibly some plugin?

FYI, I have these plugins installed in my test Wiki:
  * [Add New Page](http://www.dokuwiki.org/plugin:addnewpage) (Last updated on 2015-11-02)
  * [Advanced DokuWiki](https://www.dokuwiki.org/plugin:advanced) (Last updated on 2022-12-10)
  * [Blog](https://www.dokuwiki.org/plugin:blog) (Last updated on 2020-09-19)
  * [Bureaucracy Plugin](https://www.dokuwiki.org/plugin:bureaucracy) (Last updated on 2022-01-24)
  * [Changes Plugin](http://www.dokuwiki.org/plugin:changes) (Last updated on 2022-09-07)
  * [charpicker](https://www.dokuwiki.org/plugin:charpicker) (Last updated on 2022-09-06)
  * [color syntax plugin](https://www.dokuwiki.org/plugin:color) (Last updated on 2022-10-19)
  * [DocNavigation plugin](https://www.dokuwiki.org/plugin:docnavigation) (Last updated on 2022-10-06)
  * [Extended List syntax](https://www.dokuwiki.org/plugin:extlist) (Last updated on 2016-07-26)
  * [folded plugin](http://dokuwiki.org/plugin:folded) (Last updated on 2020-09-24)
  * [geoPHP plugin for DokuWiki](https://www.dokuwiki.org/plugin:geophp) (Last updated on 2022-11-21)
  * [include plugin](http://dokuwiki.org/plugin:include) (Last updated on 2022-01-23)
  * [Login/Logout logging plugin](http://www.dokuwiki.org/plugin:loglog) (Last updated on 2020-11-16)
  * [Meta plugin](https://www.dokuwiki.org/plugin:meta) (Last updated on 2021-10-16)
  * [Move plugin](http://www.dokuwiki.org/plugin:move) (Last updated on 2022-01-23)
  * [nspages plugin](http://www.dokuwiki.org/plugin:nspages) (Last updated on 2022-11-27)
  * [Pagelist Plugin](http://www.dokuwiki.org/plugin:pagelist) (Last updated on 2022-09-28)
  * [PHP Wikify](https://www.dokuwiki.org/plugin:phpwikify) (Last updated on 2020-06-05)
  * [Searchindex Manager](http://www.dokuwiki.org/plugin:searchindex) (Last updated on 2020-06-21)
  * [Tag Plugin](https://www.dokuwiki.org/plugin:tag) (Last updated on 2022-10-02)
  * [User History Manager Plugin](http://www.dokuwiki.org/plugin:userhistory) (Last updated on 2021-02-07)
  * [Wrap Plugin](https://www.dokuwiki.org/plugin:wrap) (Last updated on 2022-08-10)

And I am using the template:
  * [sprintDoc Template](https://www.dokuwiki.org/template%3Asprintdoc) (Last updated on 2022-10-09)

**Comment by michitux** [comment]
This sounds like you're using the [comment plugin](https://www.dokuwiki.org/plugin:comment) which defines `/*` as pattern for starting comments. If true, this is intended and not a bug.

**Comment by rebeka-catalina** [comment]
> This sounds like you're using the [comment](https://www.dokuwiki.org/plugin:comment) or [comment syntax](https://www.dokuwiki.org/plugin:commentsyntax) plugin which define `/*` as pattern for starting comments. If true, this is intended and not a bug.

Oh... yes you're right!! I'm sorry for that. I forgot about it :-/
