### ISSUE TITLE
Semicolon (;) in page title is replaced with colon (:, i.e. namespace separator) in page id

### ISSUE THREAD

**Issue by fiwswe** [splitbrain/dokuwiki#3857]
This issue actually came up in https://github.com/dokufreaks/plugin-blog/issues/114 but seems to be a general DokuWiki issue.

It seems that a semicolon in a page title will be converted to a colon in the page id which causes the part before the semicolon to act as a namespace.

For example: The page source `[[Test; Something]]` will be converted to the page id `id=test:something` and it will consequently be displayed as `Something`, leaving out the incorrectly generated namespace. This replacement and misinterpretation can also happen multiple times: `[[Test; B; Something else]]` -> `id=test:b:something_else` displayed as `Something else`.

This seems to be happening in the function [cleanID()](https://github.com/splitbrain/dokuwiki/blob/master/inc/pageutils.php#L120).

Is there any reason for this behavior or is this a bug?

DW 2022-07-31a "Igor", PHP 8.0.24

fiwswe

**Comment by DB1BMN** [comment]
Hi, I came from
https://github.com/dokufreaks/plugin-blog/issues/114
and tested the other special characters of the German keyboard.

When entered in the address-bar of the browser (FireFox 108.0.1) to create a new page most of them are working correctly.
But the following anomalies I found:

- ';' is changed to ':' and therfore creates a new sub-namespace
- '%' is *not* substituted to '_' like the others but deleted completely
- '&' and '#' are cutting away all letters that follow

Best regards /M.

**Comment by splitbrain** [comment]
Semicolons can be used as alternative namespace separator. This is by design. It was introduced for compatibility reasons with windows setups.

**Comment by fiwswe** [comment]
Ok, noted. `;` as namespace separator is [undocumented](https://www.dokuwiki.org/pagename#naming_conventions) but intentional.

However I would argue that there is still a more general issue. Whenever human readable titles are used to generate page ids, there is a risk that certain characters will be interpreted differently than the user expects.

For a human readable page title basically the expectation is that anything goes. This includes special characters such as `:`, `;`, `#`, `?`, `/`, `\`, `&`, `%` and probably more.

For page ids the rules are much more strict and that is fine. The problem area is where DW can not easily tell whether the string is a page id or a human readable title. So it converts whatever it finds to a valid page id.

Unambiguous:
  - URL (If someone directly edits the URL in the browser then it is clear that a page id is required. And any conversion to a valid page id is perfectly fine.)
  - A link in the form `[[page_id|Title]]`. The `page_id` can be safely converted to a valid form and the `Title`can remain untouched.
  - In the case of the [Blog plugin](https://github.com/dokufreaks/plugin-blog/issues/114) It is clear that the user is entering a human readable title. So spechial characters should be ignored when converting to a page id. Other plugins that allow page creation, such as the [Add New Page Plugin](https://github.com/samwilson/dokuwiki-plugin-addnewpage) may be similar.

Ambiguous:
  - A link such as `[[Title]]`. Here the `Title` must be converted to a page id. And as it might even be a page id some special characters might need to be conserved or converted according to the Wiki settings.

So focussing on the ambiguous case, here are some test cases and what I think the result SHOULD be:
  - `[[Something]]` -> page id: `something`, title: `Something`
  - `[[test:something]]` -> page id: `test:something`, title: `something`
  - `[[Test; Issue #114 alternate 3 & extra / additional % special \ characters? ok]]` -> page id: `test_issue_114_alternate_3_extra_additional_special_characters_ok`, title: `Test; Issue #114 alternate 3 & extra / additional % special \ characters? ok`

A simple first step might be to treat any string containing a space (or non-breaking space) as a human readable string, i.e. ignore special characters when converting to page id.

I'm not sure where this might best be implemented though.
