### ISSUE TITLE
Link isn't being parsed correctly

### ISSUE THREAD

**Issue by eduardomozart** [splitbrain/dokuwiki#3863]
When posting the following link at the DokuWiki:

https://higherlogicdownload.s3.amazonaws.com/HPE/MigratedAssets/Howto%20Aruba%20external%20web%20authentication%20(EN).pdf

It creates a broken hyperlink:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/2974895/214592525-73c1dde2-5d4d-4d37-80d7-b16d4c5e3591.png">

It's rendered as expected when inside ``[[https://higherlogicdownload.s3.amazonaws.com/HPE/MigratedAssets/Howto%20Aruba%20external%20web%20authentication%20(EN).pdf|Test]]``

**Comment by Klap-in** [comment]
Might be related: #2869

**Comment by splitbrain** [comment]
Yeah basically the same "problem" as #2869

TBH I don't think this is worth fixing since the link syntax can be used for links like that.

**Comment by eduardomozart** [comment]
Sometimes I just post the link at the DokuWiki with a "FIXME" tag so I know I have to access it to add it's content to the Wiki later on. When clicking into the link, it's broken and doesn't work as expected. I know I can use the Link syntax, but a new comer wouldn't know that and would not fix the link. The DokuWiki parser should be able to parse valid links correctly instead of relying into the user knowledge about DokuWiki syntax as a workaround "solution".

**Comment by splitbrain** [comment]
Sorry, "fixing" this is even harder than the cyrillic problem in #2869 because it would easily break the followoing:

```
You should remember the name of my homepage (https://splitbrain.org)

This is a cool link: https://splitbrain.org(just kidding) Yeah people forget whitespaces...

We might even have problems with footnotes https://splitbrain.org((here is a footnote))
```

In any case feel free to open a pull request that includes sufficient unit tests

**Comment by eduardomozart** [comment]
Maybe parsing the link from ``(`` to the last ``)`` would be an acceptable solution. It would force the end user to use spaces, but they should do it from the beginning because the [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) that rules the behavior from URL specification allows to use parenthesis into URL and optionally allows to escape them using HTML chars “%28” and “%29”, which could be used for users that are facing those kind of problems right now.
