### ISSUE TITLE
Sitemap shows namespaces even if ACL is 0

### ISSUE THREAD

**Issue by powermosfet** [splitbrain/dokuwiki#3866]
I'm trying to set up a private wiki with no access unless logged in. But, even though logged-out users do not have access to any pages, they can still see the namespaces in the sitemap (just without any pages)

ACL config:
```
        *               @ALL              0
        *               @user            16
```

![bilde](https://user-images.githubusercontent.com/53771/215551715-ccc785a0-6b47-4064-a5a5-6cac4097bff5.png)

**Comment by mprins** [comment]
You have failed to provide you config, so I think this works as designed: https://www.dokuwiki.org/config:sneaky_index
