### ISSUE TITLE
PHP error on http://wiki.synchro.net/

### ISSUE THREAD

**Issue by WolfEye939** [splitbrain/dokuwiki#3882]
I recently discovered a PHP error on the synchronet wiki I have attached a screenshot:
![wiki_synchronet PHP ERROR](https://user-images.githubusercontent.com/53997057/216805216-3e1bcf5f-b165-4457-a0f2-5f8b7faa95a6.png)

If anyone knows how I can contact SynchroNet wiki's developers about this issue I would appreciate it

**Comment by splitbrain** [comment]
try https://github.com/SynchronetBBS
