### ISSUE TITLE
"Uncaught TypeError: Cannot read properties of undefined (reading '0')" when typing on search box

### ISSUE THREAD

**Issue by eduardomozart** [splitbrain/dokuwiki#3891]
Hello,
When I start to type words to search into the search box using the default template on DokuWiki Release 2022-07-31a "Igor", PHP 8.1 and Google Chrome (Stable), I'd start receiving the following error on browser console:

````
content.js:7 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Array.<anonymous> (content.js:7:88613)
    at c.trigger (content.js:7:81786)
    at HTMLDocument.<anonymous> (content.js:7:81433)
````

It seems to be related to the following event:

````
document.addEventListener("change", e=>c.trigger(e.type, e), !0),
````

But the search result preview seems to be working, and pressing Enter or clicking into the search button too.

**Comment by splitbrain** [comment]
Can you reproduce this in an incognito tab? content.js is not a DokuWiki file. I think it's part of an extension. Interestingly I see the same in my console, so I might use the same extension...

Digging deeper, it seems to be the Typio Form Recovery Extension

**Comment by eduardomozart** [comment]
Oh, I also use this extension. It seems to be not working as expected into latest versions of Chrome, as I'm having trouble on recovering text using it lately. I disabled the extension and the error is gone. Thank you for the digging!
