### ISSUE TITLE
PHP Warning: Undefined array key 1 dokuwiki/inc/auth.php on line 78

### ISSUE THREAD

**Issue by sollemar** [splitbrain/dokuwiki#3892]
PHP Warning: Undefined array key 1 dokuwiki/inc/auth.php on line 78
PHP 8.0

Fix: 
Change
if(isset($_SERVER['HTTP_AUTHORIZATION'])) {
to
if(!empty($_SERVER['HTTP_AUTHORIZATION'])) {

**Comment by Klap-in** [comment]
Thanks for your report. This is implemented recently in the development version, please see #3750
