### ISSUE TITLE
Some suggestions for Editing Content, linked to TOC and Editor

### ISSUE THREAD

**Issue by FelipoAntonoff** [splitbrain/dokuwiki#3894]
Hi, some suggestions for Editing Content, linked to TOC and Editor:
- Being able to keep the TOC when editing a content, when we edit the whole page, because it is difficult to go to the Hending and its contents, if it had a floating TOC on the right side it could help a lot in editing the complete page
- Edit by Hending content block, could take within the page, as if it were an inline edit, or even better, all content could be edited inline, it would make editing Dokuwiki content much better
- Editing by content block currently only shows the content block, but sometimes we need to see other content above or below and unfortunately at the moment it is not possible, so the editor could go to the block clicked on edit, but let it go to top and below the other contents
- The Edit button by content block (h1, h2, h3...) could be next to the Heading and not just below the entire content block
- Quick option on the page and perhaps in the user configuration so that we can leave or hide the Edit button in the contents, as sometimes we want to focus more on viewing and less on editing
- Perhaps a visual change in the Editor, similar to other Wikis, which becomes almost an inline edition
- Native support for Markdown would be very good, but I understand that this has already been discussed and probably was not considered viable, but it would make DokuWiki much more attractive to more current users, the biggest detail of the current markup used is the Headings (h1, h2) is very unintuitive, while in Markdown we just use '#, ##, ###, ####', that is, 1 digit or even 4-5, much simpler than '===== = ======, ===== =====, ==== ====', which requires us to repeatedly type the = on the left side and then on the right side
- Native resource of Transclusio of contents, also perhaps known as include, that is, we can add blocks of contents from other pages, this is something very interesting for a Wiki
- Finally, a suggestion would be to add the best plugins natively to DokuWiki, so everyone could take advantage of their unique features, such as the plugin manager, which is very good, or maybe a document should be made to indicate the essential plugins

In general, I really like DokuWiki, I just feel some difficulties mainly related to editing, I find it interesting to use it for more elaborate content and quick notes too, I also make a lot of use of H2, H3 and the like, Editing is very good at the current Heanding level , but there are some details mentioned above that can help to improve.

There are some improvements to improve some points, such as editing opening in the block without opening a whole screen for editing, but this feature and other native ones in DokuWiki would be interesting.

**Comment by mprins** [comment]
thank you for your opinion, this issue tracker is dedicated to bugs so your issue will likely be closed and ignored.
please use https://forum.dokuwiki.org/

**Comment by FelipoAntonoff** [comment]
> thank you for your opinion, this issue tracker is dedicated to bugs so your issue will likely be closed and ignored. please use https://forum.dokuwiki.org/

Hello, thanks for informing.
Posted on Forum: https://forum.dokuwiki.org/d/20839-some-suggestions-for-editing-content-linked-to-toc-and-editor

I hope they serve as suggestions for future features.
