### ISSUE TITLE
Resized avif not shown

### ISSUE THREAD

**Issue by schnackOpPlatt** [splitbrain/dokuwiki#3972]
If mimetype image/avif is used with resizing - syntax, the image is not visible.

`
{{image.avif?600|}}
`

**Comment by Klap-in** [comment]
It looks as relatively new supported format? https://php.watch/versions/8.1/gd-avif

**Comment by splitbrain** [comment]
This needs to be implemented upstream in Slika first: https://github.com/splitbrain/slika PR welcome.
