### ISSUE TITLE
authldap plugin alters the public interface of getUserData()

### ISSUE THREAD

**Issue by Chris--S** [splitbrain/dokuwiki#587]
```
public function getUserData($user, $inbind = false)
```
This makes it problematic to change the public interface later for other plugins which are based off the same code (e.g. [authldaplocal](https://www.dokuwiki.org/plugin:authldaplocal)).

I think its better to create an internal method which uses extra parameters, e.g.
```
public function getUserData($user) {
  return this->_getUserData($user);
}
protected function _getUserData($user, $inbind = false) {
...
}
```

This issue relates to [FS#2086](https://bugs.dokuwiki.org/index.php?do=details&task_id=2086) which requests extending getUserData() to indicate whether group information is required.  Adding an additional parameter to support the new behaviour would conflict with authldap and derivatives.

**Comment by Klap-in** [comment]
Implemented, see #606
