### ISSUE TITLE
testExtensionParameters fails sometimes

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#598]
```
1) helper_plugin_extension_extension_test::testExtensionParameters
Failed asserting that false is true.
/home/travis/build/splitbrain/dokuwiki/lib/plugins/extension/_test/extension.test.php:71
```

line 71 is a check for is_bundled. I don't see how this can sometimes fail and sometimes not. @michitux can you have a look?

**Comment by LarsGit223** [comment]
@splitbrain: How do you produce this error?

I cannot re-produce it. Is it maybe gone by updating PHP? (Just a guess)

**Comment by splitbrain** [comment]
I haven't seen this in a while. let's close it.
