### ISSUE TITLE
Installing a plugin manual, still shows info of repository

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki#627]
First i had installed(if i remember it right) the linksuggest Plugin via the Extension Manager. Fine sofar. This is done by url given at plugin page [1].

Now i installed it from a different url [2] than provided at plugin page. (the url of master branch zip)

When looking at the info section, it still shows that my download url is the link from the repository.

When i uninstall, and manual install the plugin from url [2] again, the wrong download url is shown again.

[1] https://github.com/lisps/plugin-linksuggest/releases/download/2014-02-18/linksuggest.zip
[2] https://github.com/lisps/plugin-linksuggest/archive/master.zip

**Comment by phy25** [comment]
Closed by #704.
