### ISSUE TITLE
xmlrpc: the offset parameter on getPageVersions can be incremented to infinity

### ISSUE THREAD

**Issue by flypenguin** [splitbrain/dokuwiki#714]
when you get the page versions using xmlrpc, then you can increment the offset-parameter to infinity, dokuwiki will always return items.
so this is not possible: 

```
i=0
versions = getPageVersions(pagename, i)
while len(versions):
  i+=1
  versions = getPageVersions(pagename, i*len(versions))
```

... because it never stops. (And there is to my testing no other reliable indicator available for "all versions fetched").

**Comment by Klap-in** [comment]
When no results are found the parameter $first is reset to zero.

Fine if I just remove that fallback?
https://github.com/splitbrain/dokuwiki/blob/master/inc/RemoteAPICore.php#L756
Or does that affect backward compatibility?

**Comment by flypenguin** [comment]
I hope you don't ask me cause I don't even remember what I needed this for :) . Buf *if* you ask me, yeah, go ahead ...
