### ISSUE TITLE
New install template overwrites current template

### ISSUE THREAD

**Issue by ghost** [splitbrain/dokuwiki#715]
I installed a template using the extension manager.
(https://www.dokuwiki.org/template:greensteel)

It was installed into the current template in use, eg dokuwiki.

In the file template.info.txt the field base has parameter : dokuwiki.
This is wrong, should be : greensteel

I don't want this kind of trouble and i think this is not meant to happen.

Maybe check for loading in existing template and ad a warning.

**Comment by phy25** [comment]
The override check code is already there from the beginning:
https://github.com/splitbrain/dokuwiki/blob/b8b278447f9b09c4c227bb3197fc7694ce873ace/lib/plugins/extension/helper/extension.php#L1042-L1045

However it's not checking at all, if you manually install plugin/template by URL/upload. We can probably use the override option concept from media upload form, which is what is already in place.
