### ISSUE TITLE
Wrong code download in preview of section edit

### ISSUE THREAD

**Issue by phallobst** [splitbrain/dokuwiki#741]
Given this page content:

```
====== Test 1 ======
<code c test1.c>
int x=1;
</code>

====== Test 2 ======
<code c test2.c>
int x=2;
</code>
```

If you just edit the section "Test 2" (not the whole page), select "Preview" and try to download the code of "test2.c", you will be served the contents of "test1.c".

The download address ends in "?do=export_code&codeblock=0". The index 0 would be correct for the section, but the download handler uses the index for the whole page, resulting in the download of the "test1.c" code block.

**Comment by LarsGit223** [comment]
This has been fixed a while ago, so we can close this.
