### ISSUE TITLE
Extension Manager: display security warning shortcuts correctly

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#759]
The plugin repo allows to use some predefined shortcuts (BTW: where is that described?) in security warning fields. Alternatively any text can be given instead.

In the extension manager currently only the shortcut is shown:

![2014-06-17-155852_550x121_scrot](https://cloud.githubusercontent.com/assets/86426/3301068/965ebeee-f627-11e3-80f5-1396a70463c5.png)

This is how it looks on the plugin page:

![2014-06-17-155901_657x88_scrot](https://cloud.githubusercontent.com/assets/86426/3301069/965eee28-f627-11e3-9de2-89209c45c083.png)

This could be fixed in two ways:

1. in the pluginrepo plugin by automatically expanding the shortcuts when outputting the info in the API
  * needs maintenance of shortcuts at one place only
  * fixes current installations instantly
2. in the extension manager by resolving shortcuts
  * would allow for translation - OTOH non shortcut texts would still be untranslated as is the rest of the plugin description

I'm leaning slightly towards 1)

PRs welcome.

**Comment by LarsGit223** [comment]
I just added a description, please see https://www.dokuwiki.org/plugin:repository#security_warningpredefined_shortcuts.

**Comment by LarsGit223** [comment]
I  opened a pull-request for pluginrepo to fix this issue. So I followed option 1)

**Comment by Klap-in** [comment]
https://github.com/splitbrain/dokuwiki-plugin-pluginrepo/pull/89

**Comment by LarsGit223** [comment]
I think this can be closed?
