### ISSUE TITLE
authmysql: Using stored procedures does not work

### ISSUE THREAD

**Issue by DG1000** [splitbrain/dokuwiki#771]
I've set-up a DokuWiki and tried to use it with 'authmysql' but failed to do so, cause 'authmysql' does not support stored procedures. In MySQL stored procedures require taking result sets into account.

Since I have already a working user-management in a DB I need to use stored procedures in the configured statements to get the complex queries working (and it's saver).

**Comment by Klap-in** [comment]
(See also PDO stuff in #1029)

**Comment by Klap-in** [comment]
This will be replaced by #1029
