### ISSUE TITLE
Heading containing the word "social" is not visible

### ISSUE THREAD

**Issue by ohmmega** [splitbrain/dokuwiki#811]
When creating a header with the word SOCIAL (e.g. ====== Social ======), the TOC is updated accordingly, the page source &lt;h1 class="sectionedit1" id="social"&gt;Social&lt;/h1&gt; looks correct, nevertheless, the heading is not visible on the page (template issue?)

Version: Release 2014-05-05a "Ponder Stibbons"
Template: DokuWiki Template by Anika Henke

**Comment by TimHandy** [comment]
For others, I had the same issue for the word 'Policy' in a heading which hid the whole heading. Through a process of elimination narrowed it down to the Chrome plugin 'Accept all Cookies'. Removed the plugin.
