### ISSUE TITLE
Acronyms coming back after every update

### ISSUE THREAD

**Issue by borekb** [splitbrain/dokuwiki#816]
I don't want acronyms showing up in my wiki, so I've cleared `acronyms.conf` and have my `acronyms.local.conf` empty. The problem is that after every DokuWiki upgrade, the `acronyms.conf` with full contents get copied back and acronyms start showing up again and I have to rectify it manually every time.

I think the best solution would be to have a global switch to turn acronyms / abbreviations on and off from the administration, or a more geeky approach would be to have some kind of syntax for `acronyms.local.conf` to clear all the built-in acronyms, like:

    #REMOVE ALL  <-- a directive to remove all system acronyms
    
    MCA    My Custom Acronym
    MOA    My Other Acronym

**Comment by Chris--S** [comment]
Resolved in https://github.com/splitbrain/dokuwiki/pull/1158 (but differently to the above idea).
