### ISSUE TITLE
add ?linkonly to embedded media section of wiki:syntax

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki#833]
https://www.dokuwiki.org/wiki:syntax#supported_media_formats

This syntax is explained at the :images page, but people don't find it.

**Comment by LarsGit223** [comment]
I wanted to quickly copy the few lines in there but it seems I don't have the permission to edit the page.

**Comment by Klap-in** [comment]
Needs to be improved via a pull request. (Because this page is also included in the installation package)
