### ISSUE TITLE
Change LESS compiler

### ISSUE THREAD

**Issue by selfthinker** [splitbrain/dokuwiki#836]
DokuWiki currently uses https://github.com/leafo/lessphp as its LESS compiler, but we had several issues with it. It's also hardly maintained anymore.

It might be worth thinking about changing to this new alternative: https://github.com/oyejorge/less.php
They even provide an easy (?) way of making this specific change, see http://lessphp.gpeasy.com/#transitioning-from-leafolessphp

**Comment by Klap-in** [comment]
See #1153
