### ISSUE TITLE
<code> / <file>: would it be possible to send files with CRLF as line feed if client is Windows?

### ISSUE THREAD

**Issue by FreakC** [splitbrain/dokuwiki#863]
Hi,

We make heavy use of the file and code tags, where the use simply clicks the file name to download code snippets. Unfortunately, these snippets all have LF as line terminator. I found that in inc/parser/code.php, if you add these lines before you send the snippet.

        global $_SERVER;
        if (strstr($_SERVER['HTTP_USER_AGENT'], "Windows") != FALSE)
            $text = str_replace("\n", "\r\n", $text);

Files arrive on a Windows PC with the correct line endings. Would that be a meaningful enhancement that you would want to consider for the next release?

Michael

**Comment by Klap-in** [comment]
This is fixed, it isn't?

**Comment by greenseeker** [comment]
Can we not do this on code types that are clearly meant for Unix (eg. bash, awk, diff)?

Or can we at least have another parameter to the <code> tag that lets us specify the linefeed style for the download?

The whole reason I put shell scripts on my wiki is for people who don't know Unix and now I have to explain how to do linefeed conversion.
