### ISSUE TITLE
gzopen missing, gzopen64 could replace

### ISSUE THREAD

**Issue by necarnot** [splitbrain/dokuwiki#865]
See https://forum.dokuwiki.org/post/45469

Known bug in PHP 5.3+, hitting dokuwiki : Though the correct php libs and functions are installed and activated, the use of the gzopen function fails because not found. It has been replaced by gzopen64.

A proposed workaround would be to autodetect which one is present, wrap it around and use its wrapper.

**Comment by necarnot** [comment]
Almost one year later, I still have to add one thing I'm almost sure about : 
this bug is not fully fixed!
For a long period, I was forced to run dokuwiki in a complete 32 bits installation (LAMP+linux distro all in 32 bits, but on a 64 bits hardware. I know that sounds crazy but it was the way I had to do with.
And though my comments above were optimistic, I eventually found out that the decompression/unzipping was not acting as expected : the downloading was going fine, but the unzipping was failing, leading to a blank page with no err info, and nothing in the log files.

Last week, I had the opportunity to completely wipe this install and put a 64 bits LAMP on this same 64 bit hardware, and I just tested the same case now, and it is now working fine.
In last September, I took a very long time to debug it, and yes, I'm sure of what I witnessed (decompression failing).

I don't know if it's worth re-opening a bug for such a weird setup (32 bits bins on 64 bits HW), and I won't have the opportunity to help on this anymore.

Thanks for reading this far :)

**Comment by Klap-in** [comment]
If it is still an issue (for someone), then I would recommend testing with current devel version of dokuwiki which is based at the file archiver maintained at https://github.com/splitbrain/php-archive
If it is affected, please file the bug at the tracker linked to that project.
