### ISSUE TITLE
Warnings after last update

### ISSUE THREAD

**Issue by swell-d** [splitbrain/dokuwiki#883]
I have updated my dokuwiki, but I'm still see warnings: 

![2014-10-01_19-14](https://cloud.githubusercontent.com/assets/8986006/4477374/afd11698-497d-11e4-8993-0b45968d8d0b.PNG)

**Comment by zaroth** [comment]
Can't we somehow remove the warnings from cache automatically during the update mechanism? I mean, the issue is old, nagging and very visible - user shouldn't have to manually do anything to make nagging notifications go away after upgrading.

**Comment by zaroth** [comment]
@up 
Scratch that, I just noticed https://github.com/splitbrain/dokuwiki-plugin-upgrade/issues/53 .
