### ISSUE TITLE
Update check should not directly inject remote HTML messages

### ISSUE THREAD

**Issue by kxz** [splitbrain/dokuwiki#894]
When `updatecheck` is enabled, new messages from update.dokuwiki.org are fetched over plain HTTP and inserted directly into the HTML through the `html_msgarea` function, with only a check that the update response ends with a `%` symbol. This is a potential source of XSS attacks against admin users if the update server or the local network is compromised. A safer way to do this would be to have the response be plain text with a known structure, which is then parsed and used to populate an HTML template on the local side.

I'm reporting against Hrun, but the code in question doesn't appear to have changed in master.

**Comment by splitbrain** [comment]
update check is now using HTTPS
