### ISSUE TITLE
HTTPClient stream_socket_enable_crypto error

### ISSUE THREAD

**Issue by dspiegel** [splitbrain/dokuwiki#915]
When trying to update extension plugin:upgrade I get following error:

`SSL operation failed with code 1. OpenSSL Error messages: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure in /export/home/dave/Projects/dokuwiki/inc/HTTPClient.php on line 571`

I upgraded to latest Release 2014-09-29a "Hrun" and same error, but new line number, 583 instead of 571.

I did quick search on web and found similar issue which mentioned using STREAM_CRYPTO_METHOD_TLS_CLIENT instead of STREAM_CRYPTO_METHOD_SSLv3_CLIENT. 

Don't understand details, but I changed HTTPClient.php line 583 to use STREAM_CRYPTO_METHOD_TLS_CLIENT and then plugin update was successful.

I am running from inside company proxy, so not sure if this is just specific to my company, but wanted you to know anyway. Seems like it's worked in the past so I don't know what changed.

Running PHP version 5.3.10

Thanks, Dave

**Comment by igittigitt** [comment]
Andy, your patch in current master works. But why using unsafe protocoll anyhow? Changing the SSL-method to TLS should do the job.

**Comment by splitbrain** [comment]
@igittigitt see my comment at https://github.com/splitbrain/dokuwiki/blob/master/inc/HTTPClient.php#L595

thanks for testing

**Comment by dspiegel** [comment]
@splitbrain When will this fix be released?
I'm running Release 2014-09-29d "Hrun" but it has old code.
I was able to test your fix, and it works for me too.

thanks, Dave
