### ISSUE TITLE
Search and Install Extensions Sourced from Github

### ISSUE THREAD

**Issue by theNerd247** [splitbrain/dokuwiki#916]
Plugins that have the URI format: `https://github.com/<plugin-name-here>/archive/master.zip?raw=true` (where `raw=true` is optional) seem to fail in attempting to download. I have the php-zlib extension isntalled and the the proper file permissions for the `lib/plugins/` directory.

**Comment by Klap-in** [comment]
Are you still affected by this? No error messages from webserver as well?
Can you download packages from https locations with other means at your server?

Sofar we have not enough information to draw conclusions here.

**Comment by theNerd247** [comment]
Honestly I'm not sure. I'm no longer managing the webserver  these errors are created with. If nobody else is experiencing issues such as these then it may just have been a local server error.

**Comment by Klap-in** [comment]
Of course, reopening fine if someone can add more details.
