### ISSUE TITLE
Mediamanager ajax calls fails when using subdomain

### ISSUE THREAD

**Issue by Ginko-Aloe** [splitbrain/dokuwiki#919]
Hi there,

Example: 
Subdomain "wiki" on site domain.com pointing to /foo/bar/dokuwiki/ (on same webserver).

The wiki can be accessed through:
* wiki.domain.com/doku.php (way # 1)
* domain.com/foo/bar/dokuwiki/doku.php (way # 2)

On way # 1 ajax calls to upload files in media manager will fail returning HTTP 403 on /lib/exe/ajax.php.

Everything remaining the same (user, file, destination namespace,browser, etc), the same ajax call will succeed using way # 2.

Indicating basedir and baseurl in wiki settings will not make it work better than autodetection (in my case at least).

I don't know if it is fully reproductible or if it depends on specific webserver config.

NB: if subdomain does not point to wiki folder but an upper one (eg. foobar.domain.com/dokuwiki/doku.php), the bug does not happen. This can be used as a workaround of some sort.

**Comment by Klap-in** [comment]
So far I understand, this only a matter of configuring the web server? Therefore I will close it.
