### ISSUE TITLE
http://search.dokuwiki.org/ is not https

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki#925]
Chrome warns for mixed content on the wiki pages at https://www.dokuwiki.org/ and the other pages with https.

In the console it is explained:
"The page at 'https://www.dokuwiki.org/plugin:bureaucracy?&#mail_mode' was loaded over HTTPS, but is submitting data to an insecure location at 'http://search.dokuwiki.org/': this content should also be submitted over HTTPS."
- [ ] create a https alias to google search
- [ ] Update the topbar

**Comment by Klap-in** [comment]
When is the renewal of the certificate? Is this extension of certificate with search.dokuwiki.org know for the who will renew this cert?

**Comment by mprins** [comment]
the certificate has an expiration date of 7/17/16, 6:08:11 PM GMT+2

**Comment by splitbrain** [comment]
this has been fixed a while ago with the switch to letsencrypt
