### ISSUE TITLE
~~NOTOC~~ is propagated to Admin pages

### ISSUE THREAD

**Issue by ajfre** [splitbrain/dokuwiki#934]
Opening Admin | Configuration from a wiki page with `~~NOTOC~~` causes DW to open the config page w/o toc.

**Comment by Chris--S** [comment]
I could not replicate this and don't see the mechanism by which it could happen.  Can you advise the template you are using.

**Comment by ajfre** [comment]
I also can't replicate it any more. I'm using the Arctic template.
