### ISSUE TITLE
Rendering a unix path may result in strange text

### ISSUE THREAD

**Issue by ajfre** [splitbrain/dokuwiki#936]
Attempting to render the unix path 
/home/strato/www/wu/www.wunschname.de/htdocs/
leads a string "/home/strato/www/wu/" followed by an external link "www.wunschname.de/htdocs/"

**Comment by Klap-in** [comment]
Workaround sofar to prevent linkification: `%%/home/strato/www/wu/www.wunschname.de/htdocs/%%`
