### ISSUE TITLE
Add a "lazy load" option

### ISSUE THREAD

**Issue by duenni** [splitbrain/dokuwiki#944]
Hi!

Would it be possible to implement a "lazy load" option for images?
This means all images outside the users viewport are not loaded until the user scrolls to them. This will come in handy for very long pages and will improve performance. 
Thanks!

**Comment by molefunk** [comment]
This functionality is baked into the [Strap](https://dokuwiki.org/template:strap) theme, info and docs: https://combostrap.com/image#features

**Comment by splitbrain** [comment]
Lazy loading is already in master
