### ISSUE TITLE
"?&" in anchors

### ISSUE THREAD

**Issue by chang-zhao** [splitbrain/dokuwiki#962]
Page sections have anchors, like

page#anchor

After I edit a section of a page, then save it and see the edited version in a browser, I see then, that all the anchors on a page (for example in TOC, etc.) have became

page?&#anchor

All the anchors look like that, until the page is reloaded with no such '?&' in the address bar.

It happens with different browsers (I tested in Firefox, Opera & IE), on MApache.exe server (Windows 7).

**Comment by splitbrain** [comment]
removed in 326dd43a06ec0806d8771d08a0733d63090e126f
