### ISSUE TITLE
HTTP Strict Transport Security (HSTS)

### ISSUE THREAD

**Issue by glensc** [splitbrain/dokuwiki#967]
imho dokuwiki should set http://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security when using https

perhaps configurable

**Comment by splitbrain** [comment]
Would it make sense to combine this feature with the securecookie option?

**Comment by glensc** [comment]
```php
$conf['securecookie'] = 1;               //never send HTTPS cookies via HTTP
```

:+1:

**Comment by whiskeysierra** [comment]
:+1:

**Comment by SFITCS** [comment]
See also [Mozilla Observatory/Set more security headers](https://github.com/splitbrain/dokuwiki/issues/1676#issuecomment-249546229) (?)

**Comment by splitbrain** [comment]
Actually, I'm not sure setting the HSTS header is the repsonsibility of DokuWiki. The admin who sets up the SSL stuff in the webserver should probably also take care of this.

**Comment by whiskeysierra** [comment]
> The admin who sets up the SSL stuff in the webserver should probably also take care of this.

As a directive in nginx, e.g.?

**Comment by splitbrain** [comment]
Yes. All major webservers allow to add arbitrary headers to all responses and most modern tutorials on setting up SSL include how to add the HSTS header as well. I think letsencrypt's certbot might even add it automatically?

**Comment by whiskeysierra** [comment]
Sounds reasonable to me. :+1:

**Comment by phy25** [comment]
I agree that this should not be in core, such as bundling with `securecookie`. Maybe server-wide config or a plugin to DokuWiki make more senses? Anyway in docs we can leave hints to this.

**Comment by splitbrain** [comment]
okay. closing this.
