### ISSUE TITLE
A row with some Hangul(Korean letter) is not displayed.

### ISSUE THREAD

**Issue by simryang** [splitbrain/dokuwiki#988]
Host OS : *nix (unverified distribution which is hosted by hostinger.com)
Client OS : Linux Mint 17
Client Language : Korean, Unicode
Client Web Browser : Firefox 34.0

Hi, I'm Korean user. I found that some rows are not displayed.
![dokuwiki-not_displayed_rows](https://cloud.githubusercontent.com/assets/239260/5577021/c882666e-904b-11e4-93a4-34d93deb0241.png)

These rows contains some unicode letter which is from U+B800 to U+B83F and from U+C800 to U+C83F. Other rows without these unicode letters are displayed very well.

Here are test page for displaying row with each single unicode Hangul table.
http://simryang.pe.hu/dokuwiki/doku.php?id=wiki:system:ko:fault-occuring-letters

And other examples below:
http://simryang.pe.hu/dokuwiki/doku.php?id=wiki:system:ko:fault-occuring-rows

I could not find any clue except the range of the letters(U+B800~U+B83F, U+C800~U+C83F) with problem.

**Comment by simryang** [comment]
almost a year passed. anybody no idea??
it occurs on Windows 7 64bit Internet explorer 10 also.

**Comment by splitbrain** [comment]
The example pages above are not accessible. Can you please post an example to https://www.dokuwiki.org/playground:bug988

**Comment by simryang** [comment]
I added page and it is shown correctly on https://www.dokuwiki.org/playground:bug988 . Is it fixed on latest version?

**Comment by splitbrain** [comment]
There were no changes in this regard. My guess is there's something wrong in your wiki. Maybe a plugin interfering?

**Comment by simryang** [comment]
Thank you for apply :)

My plugins are
ACL Manager
Active Directory Auth Plugin
LDAP Auth Plugin
MYSQL Auth Plugin
PostgreSQL Auth Plugin
Plain Auth Plugin
CAPTCHA Plugin
Cloud Plugin
color syntax plugin
Configuration Manager
Extension Manager
folded plugin
Gallery Plugin
Info Plugin
NBSP Plugin
Popularity Feedback Plugin
Revert Manager
safefnrecode plugin
Timer plugin
Translation Plugin
DokuWiki Upgrade Plugin
User Homepage
User Manager
Video Sharing Site Plugin
Wrap Plugin

Anyway, is it better remove and install newest one?

**Comment by splitbrain** [comment]
Yes, an upgrade is always recommended. Then try disabling plugins one by one to see if one of them is the culprit.

**Comment by simryang** [comment]
Thank you splitbrain!!!
NBSP Plugin by Matthias Watermann causes that problem.
Thank you again :)

Q: how to attach label?
